### ISSUE TITLE
Unarmed and Taming being more mod compatible and configurable

### ISSUE THREAD

**Issue by Enbraend** [mcMMO-Dev/mcMMO#1021]
Just a small request on my part but I'm hoping like the other skills unarmed can be applied to any weapon under it's configuration so that weapons that are related to it (Like nun-chucks) could benefit from the skill as well as level it up. Just so that players can have more of a variety of what they want to fight with.

Also for taming to have it's own configuration of what creature you can summon using a x amount of a certain item to gain a tamed creature. (For example enderman, creepers, skeletons, and on a more complicated yet personal note an Ender dragon, as well as any custom mod mob.)

**Comment by t00thpick1** [comment]
Closing due to 1.13 overhaul changes in progress touching the affected areas.
