### ISSUE TITLE
Additional Woodcutting Features?

### ISSUE THREAD

**Issue by Rowen2003** [mcMMO-Dev/mcMMO#1109]
Based on the abilities to acquire rare materials, or provide other similar bonuses, I feel that woodcutting is quite the underdog, and is lacking the same amount of attention that other skills garner. With that said, I've been trying to brain storm some ideas that may help woodcutting be more of an appealing skill.

Here are more ideas:

charcoal lasts longer (as a fuel source)

more experience when cooking with wood products (as a fuel source)

more experience when cooking charcoal (creating charcoal)

chance to drop materials from logs/leaves. example: feathers, bottle o' enchanting, spider eye, golden apple(tier 1), ink sac, etc (similar to how excavation works)

I originally had considered having tree feller grant buffs based on which kind of tree/mushroom was harvested, but I felt that it was either over powered, or impractical. I'll leave this idea here anyway, in case you guys decide otherwise.

Thank you for your time, and of course, the work you put into the mcMMO plugin.

**Comment by malbosia2013** [comment]
i switched the treefeller threshold to 10000 but it still wont break a tree of 2578 blocks (gianttree)
