### ISSUE TITLE
mcMMO and bungeecord

### ISSUE THREAD

**Issue by chillecharlie** [mcMMO-Dev/mcMMO#1159]
Hi, We have recently split up our server with bungeecord due to too many players causing immense lag.
Now we have the following issue, mcmmo does not really load playerdata from the database when a player logs in, so when a players gets his levels in one of our servers and goes to the next his levels wont go with him, they are stored in the database, though after a while the levels completely dissapear because it looks like mcmmo from one of the other servers overwrites these values in the database.

That makes me wonder, why does mcmmo write values to a database without changes beeing made to them in the first place? and then again, why does mcmmo not load player stats when a player logs in? is there somehow a way to fix this terrible issue?

**Comment by riking** [comment]
It's not really fixed. Truly fixing this requires something more than what BungeeCord has to offer.

**Comment by jjacobson** [comment]
This is still an issue for me. The workaround I was using before was broken last august in this commit buy @t00thpick1 https://github.com/mcMMO-Dev/mcMMO/commit/857e12b96edf68bc2e2fdbdf72659ce82612bda1#diff-554e52de240856c7b62ed93b95a6924cL18

Any advice on how to get this to work, even just a ghetto work around would be great.

**Comment by t00thpick1** [comment]
Workaround: 
A.   Listen on logout. Save user on main thread.
B.  Write custom db manager that somehow syncs all bungee stuffs

**Comment by jjacobson** [comment]
@t00thpick1 thank you for the response. Does mcmmo have any documentation on how I would go about saving user data on the main thread?

**Comment by krillr** [comment]
You guys might want to consider adding RedisBungee support. Many other plugins use RedisBungee for sync.
