### ISSUE TITLE
mcMMO stats reset

### ISSUE THREAD

**Issue by Zippyduda** [mcMMO-Dev/mcMMO#1306]
I am not getting any errors, however all players mcMMO stats are being reset regularly (I am the only OP/Admin/Owner of the physical server). Does it do this on server reboot/plugin reload?

As far as I'm aware there is not a setting to reset the stats. I have done some research on Google and a few other servers have had this issue in the past 2 years.

Can you please advise?

**Comment by ForeverHectic** [comment]
This appears to be happening again in mcmmo version 1.5.00-b3547 on a server I am currently staff on every time a play logs in every skill gets reset to 0
