### ISSUE TITLE
Add config option for Green Terra

### ISSUE THREAD

**Issue by CommodoreAlpha** [mcMMO-Dev/mcMMO#1421]
I've noticed there are per-block permissions nodes for Green Thumb, but not for Green Terra. I don't want my players to be able to obtain mossy cobblestone and mossy stone brick so easily, so I want a way for them to keep Green Terra, but not be able to turn blocks into other plant-counterparts. This can probably be done by adding more permissions to Green Terra in the way that you've done with Green Thumb.

**Comment by Flavourized** [comment]
Was this ever added?

**Comment by t00thpick1** [comment]
Closing due to 1.13 overhaul changes in progress touching the affected areas.
