### ISSUE TITLE
Customizable horse spawning for Call Of The Wild

### ISSUE THREAD

**Issue by dddeeefff** [mcMMO-Dev/mcMMO#1481]
It would be nice to add some element of customization to Call of The Wild:
- [x] Configurable COTW items
- [x] Configurable amounts needed for COTW
- [ ] Configurable weighting of spawn rates for horse variants, patterns, and styles
- [ ] Configurable weighting of spawn rates for ocelots

Thanks very much!

**Comment by t00thpick1** [comment]
Closing due to 1.13 overhaul changes in progress touching the affected areas.
