### ISSUE TITLE
Player can get mining skill exp from stone generator.

### ISSUE THREAD

**Issue by ghost** [mcMMO-Dev/mcMMO#1609]
Player create a smooth stone generator and break the smooth stone will earned mining skill exp.

Bukkit Version: git-Spigot-1130 (MC: 1.6.4)
mcMMO Version: v1.4.07-b3337

**Comment by zaphod77** [comment]
so while the piston based generator doesnt' work, the freestanding single row smooth stone generator still works.

that said there is a very simple check that will work to block this.

If stone is adjacent to water or redstone anything when it is mined, give no exp.  simple?

**Comment by zaphod77** [comment]
btw, this same trick works better with a basalt generator in the nether. Basalt is two experience, and lava flows with water speed there.  So you set up with blue ice on top, lava sources to the side, and soul soil at the bottom. add a mining haste 2 beacon, and it's godly fast. sure you won't get the drops, but that's hardly an issue when the goal is converting netherite pick durability to mining experience fast.
