### ISSUE TITLE
Fishing loot generates otherwise impossible enchants (sharp on axes, for instance)

### ISSUE THREAD

**Issue by Kerrus** [mcMMO-Dev/mcMMO#1646]
Currently when fishing is enabled, people can get enchantments on items that would otherwise normally not be available, like sharp or fire on axes. As our server is a PVP heavy server, we do not want sharp 5 fire 2 knockback 2 axes in circulation, and have had to COMPLETELY disable fishing for enchanted loot, because we cannot otherwise block users from getting these items which are comparatively much stronger than any other weapon in the game.

Please either add a config for enchantments from fishing, or block these enchantment combinations from being acquirable through fishing. As we'd love to be able to configure enchanted gear rewards, we'd definitely prefer that option, but either would help in the short term.

**Comment by PgBiel** [comment]
@Glitchfinder Yeah, I think that's what @Kerrus meant.
