### ISSUE TITLE
Can't disable perk

### ISSUE THREAD

**Issue by jaredcat** [mcMMO-Dev/mcMMO#1662]
Perks were enabled by default for admins. Had to manually add -mcmmo.perks.\* to remove them but I am still seeing one enabled that I can't seem to get rid of. 
Further more, with only level 106 repair skill I have 100% chance of AF.
How come admins are not treated equally as other players initially?

![image](https://f.cloud.github.com/assets/3268576/1653118/99f3c6f0-5b2a-11e3-864d-aa89dd1e7ad7.png)
![image](https://f.cloud.github.com/assets/3268576/1653102/26e8fa86-5b2a-11e3-9d8b-a2ccd3cfea95.png)

![image](https://f.cloud.github.com/assets/3268576/1653111/70ed661c-5b2a-11e3-81d0-2ea2e3f50d26.png)

**Comment by ucrania** [comment]
I found in the documentation:
[List of permissions](https://github.com/mcMMO-Dev/mcMMO/wiki/List-of-permissions)
you just need do remove this permission: 
mcmmo.bypass.arcanebypass
