### ISSUE TITLE
"♥♥♥♥♥♥♥♥♥♥ was killed by {player}".

### ISSUE THREAD

**Issue by JagSwag2014** [mcMMO-Dev/mcMMO#1726]
Hi, I've been having the issue with mcMMO where if a player would kill any mob, it would display in chat the following:
"♥♥♥♥♥♥♥♥♥♥ was killed by {player}". 

I've tried different options in your config to try and get rid of it, but nothing seems to work. :L

**Comment by CamNFG** [comment]
Thank you for contacting Nonflavored Network support! We will get to you as fast as possible! 

Visit our website for updates and more!
Also follow our Twitter account www.twitter.com/camnfg for quick updates on server statuses, upcoming events and news!
