### ISSUE TITLE
Ops get these perk things that are unfair to the rest of the players.

### ISSUE THREAD

**Issue by SalC1** [mcMMO-Dev/mcMMO#1753]
I am the owner of a server that runs mcmmo and for some reason I get a lot more exp when I mine, excavate, ect. I could not find a way to disable this for ops and looked everywhere to find a way to fix this. I use Group Manager for permissions. I hope somebody can find a way to fix this problem.

**Comment by eZPvPer** [comment]
Hello I'm very confused
I have no McMMo perks in my Permissions file, yet I still have the McMMo perks. How can I possibly remove them?
