### ISSUE TITLE
New Fishing Ability - Lava Fishing

### ISSUE THREAD

**Issue by Xyntak** [mcMMO-Dev/mcMMO#1783]
This feature is an idea that I had when thinking about how to make fishing a more appealing skill. This ability would be a high risk, high reward ability.

To use this ability you would need to be a high fishing level, be in the nether, and fishing in lava (obviously).

Some things you may get from lava fishing are cooked fish, rotten flesh, gold, ore blocks, and other random loot.

Some traps could be  agro'd pigmen, wither skeletons, blaze swarms, wither splash potions and the very rare wither boss.

The lava kraken would of course be a super powered ghast.

**Comment by Konpaku-LVX** [comment]
how about nowadays? is minecraft still limited in this regard?
