### ISSUE TITLE
Alchemy - No xp gain from automated bottle in/out

### ISSUE THREAD

**Issue by Alemence** [mcMMO-Dev/mcMMO#1927]
"Potions made through automated means by using hoppers, redstone, etc. will not yield any experience. A hopper can put in or take out bottles/potions, but the player must actually put the ingredient in to gain experience. "

This is an excerpt from the mcmmo wiki regarding alchemy. My issue is that I cannot gain xp via adding/removing bottles autonomously. 

Ive tried the following:
Hand placed ingredients with hand placed bottles = xp
Hand placed ingredients with hopper placed bottles = no xp
Hand placed ingredients with a set of finished potions and a fresh set ready to be dropped in with a hopper, when the finished set is removed by hand, the fresh set drops down and brews = xp
Hopper placed ingredients with hand placed bottles = no xp

If what the article says is meant to be true, then xp should be given as long as the ingredients are hand placed, regardless of the placement of bottles.

**Comment by NateTheCodeWizard** [comment]
Was this ever finished or done?

**Comment by SotomaniaGr** [comment]
Greetings, any updates on this? Since brewing stands register to the player who placed them now. shouldn't this work? Currently on version 2.1.217.

**Comment by jrdrennan31** [comment]
This does not work on the 1.19.3 version of Mcmmo. At least is everything is put in via hoppers.

**Comment by Chew** [comment]
Please create a new issue if you're currently experiencing it, this issue is over 8 years old and necroing it wont do you any good
