### ISSUE TITLE
Farmer's diet ruining food saturation

### ISSUE THREAD

**Issue by Tslat** [mcMMO-Dev/mcMMO#1942]
I'm not sure of the effects of mid-range levels, but I was running along with a stack of bread ingame and realised I was almost constantly eating bread, as if it was giving me no saturation..

I'm not sure of the extents of this, whether it happens to other herbalism foods, or what ranks, but at the time of testing I was around 1200 Herbalism.
EDIT: Carrots also give 1.2 saturation

Healing myself, then draining hunger manually, followed by eating a piece of bread; I ran the /whois command (which shows saturation bonus) - I was only getting 1.2 saturation from Bread. The default saturation is 6 minimum, and I should effectively be far more than that given my herbalism level.

Removing the plugin put bread back up to the normal 6 saturation

I am an opped player, with all permissions, if that matters.

McMMO ver. 1.4.08-SNAPSHOT-b3542

**Comment by Glitchfinder** [comment]
Over four years later and well past it's general relevance, this bug has been resolved via a fix to the source of the problem: [Bukkit](projects/SPIGOT/repos/bukkit/commits/59b49b81dd4dd7c29debd3bb46961001531ea5ca).
