### ISSUE TITLE
Ops get max skill bonuses

### ISSUE THREAD

**Issue by Tslat** [mcMMO-Dev/mcMMO#1943]
I'm hoping it's just something I've missed in the configs, but I've been through all of them and can't seem to find anything to change it, but currently, anyone who is opped/has all perms automatically gets max iron arm style for unarmed, and 100% AF success with 0% AF downgrade chance for repair.

This may also affect other skills, but I haven't noticed anything yet.

While this may be a useful feature, an option to turn it off is definitely needed. I can't seem to find anything on it.

EDIT: Also note that I currently have -mcmmo.perks.* for all players regardless, whether that matters or not

**Comment by t00thpick1** [comment]
The issue originally reported has been resolved, any subsequent issues please make a new report.
