### ISSUE TITLE
mcMMO w/ mod's tools configs

### ISSUE THREAD

**Issue by IronicMollusk** [mcMMO-Dev/mcMMO#1971]
I’ve used some of the mod config examples to add tools from some of my mods. 

The issue i am having is, I can seem to use abilities for the tools...Like the Ironwood axe, for instance, I can use it to acquire XP and level up, but i cant use treefeller. When I right click, nothing happens. is this just how modded tools work right now? or is there something wrong with my configs?

Heres the pastebin link for my McMmo/mods/default.tools.yml:
http://pastebin.com/0j1tpQDQ

Let me know if you need another file... 
By the way, i really appreciate the ability you've added to make forge mods compatible with MCmmo, not a lot of people will do that.

**Comment by MegaPunchQ** [comment]
I can confirm this bug, in the latest update 1.5 on minecraft 1.7.10 any modded tools ie swords axes etc. can only gain you xp, none I have used so far can access the special abilities like serrated strikes or whatnot.
