### ISSUE TITLE
SQL to flatfile conversion

### ISSUE THREAD

**Issue by insigniajoe** [mcMMO-Dev/mcMMO#1987]
When I try the conversion command ( 'mcconvert database sql' in console) It shows in console like it works (makes a database connection, converts users, states flatfile now has the sql database information). Then nothing happens, no one has any data in the flatfile, no errors.

Version: 1.5.01-SNAPSHOT-b3559
(Ive tried downgrading as well, no luck)

the only way I can get it to convert anything is is I let people on the server, it will convert any/everyone on the server.

**Comment by Grixer** [comment]
This feature is still broken. This is something that could save my ass in a horrible situation with MySQL. Are there any plans to fix this?
