### ISSUE TITLE
Issue with the ChunkStore

### ISSUE THREAD

**Issue by jefffliu** [mcMMO-Dev/mcMMO#2077]
- Instructions moved to Trello -

**Comment by bm01** [comment]
So I was lurking around and came across this report. Went to our old Trello see what was going on.

I found the source of this issue, it's actually very simple, unfortunately a patch has to be written to correct already stored chunk meta data and that's much more complicated.

Where do you want me to give you the details?

**Comment by t00thpick1** [comment]
bm01, if you want to figure out where I went wrong, I have a 75% functional converter in one of my hidden repositories,  you can message me in irc for access.

**Comment by Glitchfinder** [comment]
@t00thpick1 this wouldn't happen to be the same as #3429, would it?

**Comment by t00thpick1** [comment]
@Glitchfinder it was
