### ISSUE TITLE
Discuss about Potion Stage

### ISSUE THREAD

**Issue by jefffliu** [mcMMO-Dev/mcMMO#2081]
I saw #1926 and 37aebc1716b82274adfcf1bc3a420e2fb7ab4747
i think that was a good idea.
And i test it at lastbuild(b3593) with craftbukkit-1.7.9-R0.2.
_i am not sure why i still can use **Redstone** and **Glowstone** to leveling._ 
(Same Stage check not working?)
( i test like Poison or Regeneration )

And some potion only has level II or extended (like Healing or Weakness)
_Weakness <-> Weakness (extended)_
_Healing II <-> Healing_
I am not sure they have same Potion Stage

And some potion need  *Fermented Spider Eye* to Corrupts effect
_Healing -> Harming_
i guest they have same Potion Stage

**Comment by t00thpick1** [comment]
With 1.9 potions having a slight overhaul this is no longer relevant.
