### ISSUE TITLE
No reload command for mcmmo

### ISSUE THREAD

**Issue by Primetime4549** [mcMMO-Dev/mcMMO#209]
It is impossible to reload the config without restarting the server

**Comment by mibby** [comment]
Still no reload command? :(

**Comment by BillyGalbreath** [comment]
Why would you cache the config values anyways? They're already loaded in an API controlled cache called a MemorySection which is accessed via FileConfiguration or even ConfigurationSection.

aka, calling getConfig() does not read from disk, it reads from cached memory...

If everywhere a config value was needed simply called getConfig() to get it then reloading would be as simple as reloadConfig(). Literally thats it. Done. Crisis averted.
