### ISSUE TITLE
Getting the following errors on server load (using Cauldron and McMMO)

### ISSUE THREAD

**Issue by crazz2323** [mcMMO-Dev/mcMMO#2094]
On server start, I am getting the following errors:
http://pastebin.com/2ag51DQ7

I am using the latest recommended cauldron-1.7.2-1.1126.04.35-server.jar and mcMMO.jar.

**Comment by t00thpick1** [comment]
This is a disable error, most likely caused by whatever happened during enable,  please report the onENable error.
