### ISSUE TITLE
MCMMO and RedLogic conflict

### ISSUE THREAD

**Issue by crazz2323** [mcMMO-Dev/mcMMO#2100]
Using Minecraft 1.7.2 and cauldron-1.7.2-1.1126.04.46-server, MCMMO will not load with  RedLogic-1.7.2-58.0.2 with ImmibisCore-1.7.2-58.0.3.

I created a fresh server and new world, added and restarted the world with each mod and plugin going one at a time as a test. My server started fine with all my mods and plugins except when I added RedLogic. Not sure what the conflict is... This is the error.

http://pastebin.com/HHQ0cpiJ

EDIT: I also tried versions: immibis-core-58.1.3, redlogic-58.1.2
and same issue.
http://pastebin.com/PrRCXNVz

EDIT: I also tried MCMMO with a Minecraft 1.6.4 server with RedLogic for 1.6.4 and it worked fine. So something changed with 1.7.2. Please, kindly fix this issue.

**Comment by t00thpick1** [comment]
Been over a year,  I can only assume this isn't valid anymore
