### ISSUE TITLE
mcMMO prevents Multiverse from deleting world

### ISSUE THREAD

**Issue by neero82** [mcMMO-Dev/mcMMO#2152]
mcMMO leaves open files in the world folder (world/mcmmo_regions/), and prevents multiverse from deleting the world.

This can of course be deleted manually by shutting down the server, but with automated world regeneration it is a problem.

**Comment by t00thpick1** [comment]
This should be closed properly based on the current code.  I will mark this as resolved unless someone re-reports it.
