### ISSUE TITLE
One-hit kill using Serrated Strikes AoE

### ISSUE THREAD

**Issue by Byteflux** [mcMMO-Dev/mcMMO#2170]
Version: CraftBukkit/Spigot 1.7.10 and using mcMMO commit 87bce65098504524002a8d968750cb99bc59de50

I am experiencing an issue where Serrated Strikes AoE may occasionally one-hit kill a player in range. The issue only seems present when there is more than one player being affected by the AoE damage, and even then it only happens some of the time.

My test case for verifying the bug was very simple. Gear up 3 players in Protection 4 diamond armor, ensure they are all in Serrated Strikes AoE range, use one guy to attack another using Serrated Strikes and monitor the HP of each player after each Serrated Strikes attack.

It is not always a one-hit kill. Sometimes it's just a lot of damage but doesn't kill the target (e.g., 5 hearts off a Protection 4 armored player).

**Comment by xion87** [comment]
this bug returned back, axe oneshot sometimes... too much damage
