### ISSUE TITLE
mcmmo.users losing players on server boot

### ISSUE THREAD

**Issue by Ironic8b498** [mcMMO-Dev/mcMMO#2225]
Not sure why this ticket keeps getting closed before I can fix the issue, if it's me please help figure it out. I restore my mcmmo.user file and delete the update.yml file and it still removes the player from when I was running #3654 I'm currently running #3664 updated three times since this problem started. Any ideas on how to fix this so I can have my server return to auto reboot.

My OS is MineOS, running craftbukkit 1.7.9-RO.2 b3116

**Comment by DahFrozen** [comment]
Has this been fixed yet?

**Comment by benokelvin** [comment]
is it fixed i cant login to mcmmo

**Comment by Aggroblut** [comment]
so with the latest dev #23 from jenkins you have no problems?
