### ISSUE TITLE
Change the xp rate for abilities.

### ISSUE THREAD

**Issue by mcMMO** [mcMMO-Dev/mcMMO#2246]
So Giga Drill Breaker gives x3 drops and x3 xp, we should be able to change the amount dropped and how much extra xp is given. Same applies for all other abilities.

**Comment by t00thpick1** [comment]
Hey bud, nothing personal but as long as you keep using that username I'm going to close your tickets, the username is really misleading especially given that you have elected to use @TfT-02's profile picture as well.
