### ISSUE TITLE
Enchantments for all abilities.

### ISSUE THREAD

**Issue by mcMMO** [mcMMO-Dev/mcMMO#2247]
Please add custom enchantments for each ability use as it will stop the need for compact NCP and gives more freedom to the server. Example:

Serrated_Strikes:
  Sharpness: 5
  Smite: 5

If NCP is used, tree feller won't work without compact NCP, and making the trees explode can cause some lag issues even when set to low.

**Comment by t00thpick1** [comment]
Hey bud, nothing personal but as long as you keep using that username I'm going to close your tickets, the username is really misleading especially given that you have elected to use @TfT-02's profile picture as well.
