### ISSUE TITLE
More custom XP perks

### ISSUE THREAD

**Issue by mcMMO** [mcMMO-Dev/mcMMO#2261]
At the moment we are only allowed to set one custom xp perk. Please add options to allow us to add more. For example:

    #mcmmo.perks.xp.customboost.one.all
    Custom_XP_Perk_One:
        Boost: 8
    #mcmmo.perks.xp.customboost.two.all
    Custom_XP_Perk_Two:
        Boost: 16

**Comment by t00thpick1** [comment]
Hey bud, nothing personal but as long as you keep using that username I'm going to close your tickets, the username is really misleading especially given that you have elected to use @TfT-02's profile picture as well.

**Comment by AlucardTheRed9** [comment]
> Hey bud, nothing personal but as long as you keep using that username I'm going to close your tickets, the username is really misleading especially given that you have elected to use @TfT-02's profile picture as well.

Seemed almost... personal to me. *gasp*. Lil human.
