### ISSUE TITLE
Inspect doesn't show all skills on negitive perm

### ISSUE THREAD

**Issue by mcMMO** [mcMMO-Dev/mcMMO#2278]
If the player has mcmmo.skills.swords and uses /inspect on another player, the swords skill will not show. This applies with every skill. If this is intentional please add in config to show removed skills in /inspect and any other commands.

**Comment by t00thpick1** [comment]
Hey bud, nothing personal but as long as you keep using that username I'm going to close your tickets, the username is really misleading especially given that you have elected to use @TfT-02's profile picture as well.
