### ISSUE TITLE
/xprate for individual skill (/xprate swords 2 true)

### ISSUE THREAD

**Issue by mcMMO** [mcMMO-Dev/mcMMO#2279]
We have a global /xprate but not per skill.

/xprate swords 2 true
Provides x2 xp to swords.

/xprate 2 true
Is global as normal

/xprate all 2 true
Is also global.

Would be nice if we could also change the messages on xprate start and end.

**Comment by t00thpick1** [comment]
Hey bud, nothing personal but as long as you keep using that username I'm going to close your tickets, the username is really misleading especially given that you have elected to use @TfT-02's profile picture as well.
