### ISSUE TITLE
mcMMO userdata clearing

### ISSUE THREAD

**Issue by Theepwner** [mcMMO-Dev/mcMMO#2281]
Hello,

I am using mcMMO #3682 and it loads user data perfectly after the first time the server loads, but when the server stops/restarts, then all of the data is cleared.  The data that I was trying to convert was data from almost a month ago.  I really hope you guys can fix this.

**Comment by TfT-02** [comment]
This ticket is a duplicate of https://github.com/mcMMO-Dev/mcMMO/issues/2225, please refer to that ticket and post your findings or questions on there. We're aware of this issue and are working on a fix.
