### ISSUE TITLE
Color Schemes For Chat Output

### ISSUE THREAD

**Issue by PunkFunk** [mcMMO-Dev/mcMMO#2283]
mcMMO's contribution to fun on my server is amazing yet it craps a rainbow in everyone's chat boxes. I can understand that the authors of the plugin may not want people to be able to edit the output text (which honestly would be nice) but, even having a few solid color schemes to choose from would be amazing. You can call the original "Rainbow Crap", See you already have one. xD

**Comment by Colemac2233** [comment]
Wait ! How did you add that into your minecraft server ? What type of file did you save it as ? What did you call it? Where does it go ? because I changed everything I wanted, but I cant add thos settings to the server please help

**Comment by EvilOlaf** [comment]
Get the source code and change it till it fits your taste and then build the jar by yourself. Ask Google for a tutorial.

**Comment by TfT-02** [comment]
I like the idea of having configuration options for certain types of text. We could read the color formatting from there instead from the locale files. I'll put it somewhere on the todo's.
