### ISSUE TITLE
Allow us to chose at what ranks abilities get unlocked.

### ISSUE THREAD

**Issue by mcMMO** [mcMMO-Dev/mcMMO#2296]
So at the moment some abilities are locked at certain ranks and we can not chose at what rank they unlock at. For example setting the following.

    Fishing:
        # Rank_Levels: Fishing level where rank gets unlocked
        Rank_Levels:
            Rank_1: 90
            Rank_2: 90
            Rank_3: 90
            Rank_4: 90
            Rank_5: 90
            Rank_6: 90
            Rank_7: 90
            Rank_8: 90

Shake will be unlocked at level 90.

**Comment by t00thpick1** [comment]
Hey bud, nothing personal but as long as you keep using that username I'm going to close your tickets, the username is really misleading especially given that you have elected to use @TfT-02's profile picture as well.
