### ISSUE TITLE
 Chat colors with mcmmo

### ISSUE THREAD

**Issue by KevinEssence** [mcMMO-Dev/mcMMO#2321]
On my network, servers without mcmmo and the proper colored chat permissions work fine. The four servers with mcmmo don't allow it, as in it registers the code but doesn't display the color. Ideas?

**Comment by KevinEssence** [comment]
This is still an issue..

**Comment by t00thpick1** [comment]
Could I get a list of plugins you use?

**Comment by KevinEssence** [comment]
Sorry this is already fixed. For some reason an option in ncp causes this with mcmmo. I simply disabled the option and got it to work again. Thanks.
