### ISSUE TITLE
Disable enchanting axes with sharpness

### ISSUE THREAD

**Issue by PhanaticD** [mcMMO-Dev/mcMMO#2390]
Just like the title says, axes with sharpness enchant can end up very OP, I would like to be able to prevent axes from being enchanted with sharpness

**Comment by PhanaticD** [comment]
I would like to be able to disable vanilla sharpness from being applied

**Comment by TfT-02** [comment]
I don't believe that this is something that mcMMO should control. I'd bet that there are other plugins out there that are capable of controlling which items can be enchanted.

**Comment by PhanaticD** [comment]
well the most I found was this https://gist.github.com/andrepl/8413129

**Comment by t00thpick1** [comment]
This isn't really something that mcMMO involves itself in?  So..

**Comment by PhanaticD** [comment]
well its a balance issue is why I suggested it
