### ISSUE TITLE
Acrobatics - Max_Times_per_location doesn't work if the play relogs

### ISSUE THREAD

**Issue by Time6628** [mcMMO-Dev/mcMMO#2391]
For mcMMO acrobatics, if you relog the MAX_Times_per_location setting resets to the max count. For example, if someone jumps in the same spot 3 times, relogs, then they are able to jump in the same spot again. Please fix this! Thanks!

-Time

**Comment by t00thpick1** [comment]
No efficient way of preventing this.  Just watch your players as if they are constantly relogging thats suspicious.
