### ISSUE TITLE
Enchanting- new enchants / more powerful old ones

### ISSUE THREAD

**Issue by CFLPlayer** [mcMMO-Dev/mcMMO#2393]
Hi, I've played around with mcmmo for a while now and feel that in certain cases pvp can get a bit boring. 2 players equally matched facing it off until someone forgets to splash a potion or click fast enough. Well I say, let's spice it up;
Xp: xp would be based on how much mc xp it costs to create the enchantment, more xp would be given to those who enchant items instead of books. (so that know one can just spam level 1 book enchants)
200 mark: the first set of buffs come. A slight decrease in experience needed to enchant. And a some new enchants; for Armor the first new enchant would be called "holy" and it would reduce the damage by undead. For melee weapons, "decapitation" could be added which increases the chance of head drops from mobs. For bows, perhaps "high ground" which increases damage against targets lower than the block your standing on. "stubborn" as an enchantment for everything, this would make tools more effective the less durability they have (is not compatible with unbreaking).
500 mark: again another decrease in required xp, and this has now capped. An increase on all old enchants get raised by 1. New enchants; For Armor its "Plated" which reduces the affect of all mcmmo perks which are used on the wearer eg.wearer will bleed for a shorter amount of time. For melee weapons "First Blow" it adds a bonus amount of damage if you deal the first blow on an enemy before they hit you. For bows "Focused" roots user to the ground but when hit your opponents Armor takes a large amount of damage and even has a chance to break completely. Tools get "Heavy" adds mining fatigue when tool is equipped but the tools breaks multiple blocks at a time.
1000 mark: All old enchants get another raise. New Enchants; Bows get "Trick Shot", fires multiple arrows at once in a horizontal line. Armor gets "Absorbant" Armor will soak up poisons but make the wearer slower when swimming. For Melee it's "revenge", damage increases depending on how many times your opponent has killed you within 30 mins. Tools get, "Lottery" which has a random chance of recieving a relevant extra drop.
2500 cap: Old enchants get raised again. Bows receive "Strike" damage increases depending on how far it travels, also has a chance of calling down lightning. Melee obtains "leech" which drains health per hit. Aswell as "shattering" which damages the opponents weapon per hit. Everything obtains "Symbiote" which increases item durability when your eat. Everything gains "End-Bound" which makes items on death return to empty spaces within your ender chest.
Passive unlock at 1000 called "Printing" which allows the user to copy enchantments into empty books, without loosing the original.

Thankyou for your it,e reading this. Please comment and offerfeedback. If you want to see more, you know where to find me.
-Regards CFLPlayer

**Comment by CFLPlayer** [comment]
No feedback?

**Comment by t00thpick1** [comment]
Not a planned feature currently.
