### ISSUE TITLE
Stealth, new skill?

### ISSUE THREAD

**Issue by CFLPlayer** [mcMMO-Dev/mcMMO#2394]
Hi, one thing I think is missing from mcmmo that could make it truly an mmo is stealth. Stealth could be implemented using varying player model transparancys and a timed invisibility as an ability. Stealth could lower mob detection. When in "stealth" damage could double. But you would be exposed as soon as you strike.
Another interesting feature would be pickpocketing. Pickpocketing could allow a player to look into the inventory of another player for a limited amount of time. Not all items would be visible though, items would be separated into rarity groups. As you level stealth these groups become available.
You could gain low stealth xp from hiding from mobs (escaping their detection) and higher xp based on the items you pickpocket. Perhaps even a way to lock pick through a trial and error system. Just some small ideas on something that could be amazing.

-Regards CFLPlayer

**Comment by CFLPlayer** [comment]
No feedback?

**Comment by t00thpick1** [comment]
Not a planned feature at this time.
