### ISSUE TITLE
Specialisation for axes, swords and unarmed.

### ISSUE THREAD

**Issue by CFLPlayer** [mcMMO-Dev/mcMMO#2395]
Berserk, skull splitter and serrated strikes. In hypothetical terms, every person who wields an axe isnt always going to crack a skull open. A martial arts expert is hardly going to go into a full Celtic berserk are they?
So. My point is that there is no diversity. As you train up your skill you should be able to choose what you focus on when wielding your weapon. I'm proposing we add a progression system, which allows players to build upon a basic foundation of an ability. Using a point every 100 levels you should be able to build a "ability specialisation" that is unique to the player. I will use unarmed as an example;
When your reach level 100 in unarmed you receive a small menu (possibly use the chest menu system?) from this you select a foundation perk, this gives you your beginning ability. Here's some ideas of unarmed abilities:
Forceful Kick. Ready your feet and deal astounding knock back damage to your foe.
Berserk (changed). Ready your fists and enter a rage dealing more damage per hit though hitting slower.
Kneck Snap. Ready your hands as you approach your target, and if they are weak enough instantly put them to rest.
Drunken Slugging. Ready your fists and enter a drunken state where you take less damage and deal a small amount more.
Claws. Ready your hands as you tear at your enemy adding the bleed effect to them.
Low Blow. Raise your foot and aim low, dazing your opponent.

Lets say I select Drunken Slugging. I cannot go back on that decision. Then I receive another menu giving me options into which aspect of drunken slugging I should focus on. My options would be:
Drunken Resistance. Take less damage
Drunken Bravery. Do slightly more damage
Drunken belching. When fighting you belch causing a nausea effect to enemies around you.

I would then gain more points every 100 levels to improve myself even more. These skills would cap at 1000 giving a varied result. Once completed you can rename your Technique for all to fear. This would be available for axe users and sword users to just different foundations.

Thank you for reading. Pls criticise / praise. Ask for more if you want it.
-Regards CFLPlayer

**Comment by CFLPlayer** [comment]
No feedback?

**Comment by t00thpick1** [comment]
Not a planned feature,  very possible to add via a third party plugin though.
