### ISSUE TITLE
Mcmmo x2

### ISSUE THREAD

**Issue by Retrinity** [mcMMO-Dev/mcMMO#2398]
I would love a command to double the Mcmmo exp gained on the server for x amount of times. Like a booster. Because that would be a great and legal donation feature. (Need to be a command)

**Comment by kingremco** [comment]
This is possible without that new feature. Just give the default rank the double exp permission (mcmmo.perks.xp.double) and set the expiry to 1 hour (in the buycraft package) and add a command to remove the permission when it expires

**Comment by TfT-02** [comment]
Yup, thats the way to do it! ^
