### ISSUE TITLE
Mcmmo not loading on my modpack 1.7.10 and I can't figure out why it doesn't

### ISSUE THREAD

**Issue by Dreamxangel** [mcMMO-Dev/mcMMO#2400]
Here's the latest log files 
https://www.dropbox.com/s/ofhtvq41ts2deaf/fml-server-latest.log.txt?dl=0

As of the pack itself here a proper list of the mod in it
https://www.dropbox.com/s/jsi1d1xkbumswrw/modlist.txt?dl=0

**Comment by EvilOlaf** [comment]
Just a hint so more peope are interested in reading:
Either use markdown (https://guides.github.com/features/mastering-markdown/) or paste your log and error message to pastebin.com and put the link here.
Also a full startup log till the error message might be useful as well as more information about your "modpack".

**Comment by Dreamxangel** [comment]
Here's the latest log files 
https://www.dropbox.com/s/ofhtvq41ts2deaf/fml-server-latest.log.txt?dl=0

As of the pack itself here a proper list of the mod in it
https://www.dropbox.com/s/jsi1d1xkbumswrw/modlist.txt?dl=0

**Comment by t00thpick1** [comment]
There appears to be an error within the NMS classes, report it to either Cauldron or the mod itself.
