### ISSUE TITLE
Bred Rabbits Give Combat Experience When Killed

### ISSUE THREAD

**Issue by Innatefulness** [mcMMO-Dev/mcMMO#2402]
As the title suggests, all rabbits, no matter whether they originated naturally or from breeding, deal out experience in all of the combat skills: swords, axes, archery, and unarmed. I've tested with other bred animals, and they do not.

**Comment by TfT-02** [comment]
I've tested this with bred sheep and they also give XP. I will add an option to disable this behavior.

**Comment by TfT-02** [comment]
Set [this](https://github.com/mcMMO-Dev/mcMMO/commit/385fe1bb053cbaf2e2d74e0ebc9fc104efb35012#diff-266a30c586be746c55e6c2cb93a54269R41) setting to 0 and it will be disabled.
