### ISSUE TITLE
The /mcimport command is not working...

### ISSUE THREAD

**Issue by SlayingSlayer** [mcMMO-Dev/mcMMO#2407]
I have a Cauldron Server, with the Lord of the Rings Mod 21.3 and McMMO 1.15
I have tried to get all the mod items to work with McMMO using the /mcimport command and everytime I do it, it comes up with

Unknown Command Type /help or whatever it says.

What do I do? I have followed the tutorial and nothing

**Comment by TfT-02** [comment]
Usage instructions are on the wiki, here https://github.com/mcMMO-Dev/mcMMO/wiki/Command-reference#-mcimport-command

If you server says "Unknown Command Type /help", that means that you're using a mcMMO version which doesn't have this command. It was added in mcMMO v1.5.01
