### ISSUE TITLE
mcMMO v1.5.01-b8 generated an exception java.lang.IllegalStateException: Unregistered scoreboard component

### ISSUE THREAD

**Issue by FCScrap** [mcMMO-Dev/mcMMO#2408]
I get this error when I seem to level up in mining. I haven't tested on other tiers, but it throws this error in console. It doesn't crash or anything it just spams console: pastebin.com/PXiCxq9Y

**Comment by FCScrap** [comment]
Err, Is anyone going to help or just change the title?

**Comment by EvilOlaf** [comment]
Maybe you wanna give the authors a little more time to analyze this??

**Comment by michalet** [comment]
This seems very similar to #2412.

**Comment by TheChampTF** [comment]
Is fixed on the latest update from Spigot

**Comment by t00thpick1** [comment]
Was a spigot issue.
