### ISSUE TITLE
EntityDamageByEntityEvent

### ISSUE THREAD

**Issue by farget92** [mcMMO-Dev/mcMMO#2409]
Hello comunity,

I have one confusing error of McMMO, actually in EntityDamageByEntityEvent.
Because McMMO is sophisticated plugin, I can not find cause of this error.
Please if you know some solution or if you have some advice, I will be so thankful

http://pastebin.com/BSF4qKv0

**Comment by TfT-02** [comment]
`Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Guardian.isElder()Z`
Are you perhaps running mcMMO v1.5.02 on a 1.7 server?

**Comment by TheChampTF** [comment]
I can confirm this one also and yes to the 1.7 java , but in the progress to change to 1.8 java. But would be nice with a temp fix

**Comment by TfT-02** [comment]
I was actually referring to Minecraft 1.7 and not Java 1.7 :P I understand the confusion though, I didn't make this very clear in my previous comment.

**Comment by TheChampTF** [comment]
Oh sorry

**Comment by farget92** [comment]
Thanks for response, i feel like fool, this problem was quite stupid.
Only because I don't see this line of error ... . Once more - Thanks
