### ISSUE TITLE
b${BUILD_NUMBER}

### ISSUE THREAD

**Issue by MCTyler** [mcMMO-Dev/mcMMO#2410]
Sorry for being an idiot but how do I edit the fork to get rid of this ugly version tag when I type mcmmo from console after I do a local build? I'm using Netbeans...

**Comment by TfT-02** [comment]
Happens when you compile mcMMO locally without using Jenkins, you could either download the latest release from Spigot resources, download the latest dev build from our Jenkins or edit the building pom.xml
