### ISSUE TITLE
Task #17 for mcMMO v1.5.02-SNAPSHOT-b23 generated an exception java.lang.NullPointerException

### ISSUE THREAD

**Issue by TWSSYesterday** [mcMMO-Dev/mcMMO#2412]
http://pastebin.com/dKSfVUL5
Using mcmmo https://ci.drtshock.net/job/MCMMO/23/
http://gyazo.com/17595c0c37fb9f945df841ceff1a0495 - Latest Spigot currently.

**Comment by TheChampTF** [comment]
Same issue on later builds even 1.5 for mcmmo

I think this change https://hub.spigotmc.org/jenkins/view/RSS/job/CraftBukkit-RSS/64/ made the issue for both Spigot/Craftbukkit version(s) of 1.8+

**Comment by SmallSansSerif** [comment]
Yes I have something similar too: http://pastebin.com/b1EsVdVb

**Comment by michalet** [comment]
The only difference for me is that it's task number 11, rest same. Both build 22 and 23 from jenkins spam the same error. My version of Spigot - git-Spigot-fa7cbf9-00eba53

**Comment by Maximvdw** [comment]
http://www.spigotmc.org/threads/latest-spigot-builds-scoreboard-problems.44751/

**Comment by TheChampTF** [comment]
Is fixed on the latest update from Spigot

**Comment by TfT-02** [comment]
Thanks for the replies, but yeah. This was a bug with Spigot and has been solved now. Just update to the latest version of Spigot.
