### ISSUE TITLE
Task #10 for mcMMO v1.5.02-SNAPSHOT-b22 generated an exception

### ISSUE THREAD

**Issue by krustymk** [mcMMO-Dev/mcMMO#2413]
Tried the 1.5.02-SNAPSHOT-b23 also same problem

Occured after compiling and uploading the latest spigot build about 10 minutes ago (rolled back to a week old build and its fine now)

http://pastebin.com/w0AuTYvN

**Comment by TWSSYesterday** [comment]
Issue #2412 has this issue too

**Comment by michalet** [comment]
The only difference for me is that it's task number 11, rest same. Both build 22 and 23 from jenkins spam the same error.

**Comment by TfT-02** [comment]
^ jup, this is a duplicate
