### ISSUE TITLE
How to get mcMMO UUID conversion to start?

### ISSUE THREAD

**Issue by DahFrozen** [mcMMO-Dev/mcMMO#2414]
Hello,
I've got a mcmmo.users file with over 8500 lines from an old mcMMO version. When I updated to the newest version, the conversion only takes place when the player logs on. Is there anyway to start a conversion which converts all the users in the mcmmo.users file to UUIDS?

thanks.

**Comment by TfT-02** [comment]
Delete upgrades.yml and mcMMO will check the database for any outdated lines again.

**Comment by DahFrozen** [comment]
Ok thanks. Now it's just converting certain ones and deleting the rest :(
