### ISSUE TITLE
Issue with ability tool enchantment

### ISSUE THREAD

**Issue by jakeyray18** [mcMMO-Dev/mcMMO#2416]
[ Information moved to Trello - developers can only access this https://trello.com/c/TAcdTwPV ]
If you need anything else form me then let me know.

~Jakey

**Comment by TfT-02** [comment]
Thank you for reporting this, we will try to fix this asap as it's a pretty nasty issue.

**Comment by TfT-02** [comment]
Whoops, didn't mean to close the ticket already!

**Comment by jakeyray18** [comment]
Is there any chance of getting a status update on this?
