### ISSUE TITLE
couple issues

### ISSUE THREAD

**Issue by zRiaz** [mcMMO-Dev/mcMMO#2418]
http://pastebin.com/LvU03uyn
Getting this spammed, aswell as players using Super breaker gets a mcmmo tool...

Players using abilities such as Super breaker and the sword skill also turn invisible for a few minutes after usage....

**Comment by t00thpick1** [comment]
First issue was spigot issue,  update spigot.  SEcond issue would result of some sort of console error, throw a report up for whichever it is,  and the last thing is not a result of mcMMO.
