### ISSUE TITLE
Support for Flan's Modern Warfare Content Pack

### ISSUE THREAD

**Issue by axelpx** [mcMMO-Dev/mcMMO#2422]
Hello, 
I couldn't find any information about it so I decided to ask here: is there any way to make Flan's mod work with mcMMO? 

When I add firearms to tools.default.yml (into the bow section), mcMMO loads just fine, without any errors in logs. But I don't get experience for shooting mobs. Probably it is just because Flan used some specific events, not like those when using bows or something.

Thanks for attention!

P.S. Also it would be cool to be able to add your own skills using mcMMO. Or is it already possible?

**Comment by t00thpick1** [comment]
If they don't throw the proper events, there is not much we can do, sorry :(
