### ISSUE TITLE
Resetting all players' levels in a skill?

### ISSUE THREAD

**Issue by Theepwner** [mcMMO-Dev/mcMMO#2433]
Is it possible to reset all data for a particular skill?  If not, would it be possible to add this feature?

**Comment by TfT-02** [comment]
This feature is already present.
https://github.com/mcMMO-Dev/mcMMO/wiki/Command-reference#skillreset-command

**Comment by Theepwner** [comment]
By reset all data, I was referring to all player data for that skill.

I am aware of the command /skillreset [player] <skill>
Maybe add a method so we can "/skillreset all <skill>?

**Comment by ArranisAwesome** [comment]
bump ?
