### ISSUE TITLE
Ability Item Toggle

### ISSUE THREAD

**Issue by Anoplexian** [mcMMO-Dev/mcMMO#2436]
So, I have a server in which I'd like to implement a magic plugin (McMMo doesn't do it yet, but it already does so much for my server I'd be happy to not have it do everything). The problem I keep running into is the magic plugin I've found and would like to use has the Wooden Hoe as its "wand". 

My request is to simply add in a configuration piece that would toggle what abilities activate and what items are used to activate those abilities on an individual skill basis. I don't know if this is possible but if it is, I'd love for it to be implemented. :)

**Comment by TfT-02** [comment]
Well it wouldn't make any sense if we would allow to customize which tools activate which ability, as they are connected to the skill they're meant for. For example, pickaxes for mining. Though what you could try to do, is disable any hoe related abilities for mcMMO using permission nodes. This should stop activating abilities when using a wooden hoe. This does mean, unfortunately, that you're also unable to use abilities with any other hoe (iron gold diamond). Hope this helps!
