### ISSUE TITLE
Bleeding in Griefprevntion claims

### ISSUE THREAD

**Issue by kroko1992** [mcMMO-Dev/mcMMO#2437]
A person wrote on the Griefprevention forum:
"Hello, I have found either a bug or an error with players pets and players being able to be killed.
I run mcMMO along side with GP. I have noticed some of my players being able to kill others pets by using mcMMO's special ability attacks with the right clicking then attacking the pets which bleed then die..."

The developer then replayed:
"It's a bug in mcMMO - GP says "cancel that event, don't hurt the animal", but mcMMO ignores that and applies the bleed effect anyway.  :("

Is that something that can looked into?

**Comment by TfT-02** [comment]
As far as I'm aware, we are properly checking if the event is cancelled. Can you tell us with which mcMMO, Griefprevention and Spigot versions this is happening?
