### ISSUE TITLE
AdminChat

### ISSUE THREAD

**Issue by xtomyserrax** [mcMMO-Dev/mcMMO#2439]
Hey! I am using a plugin of admin chat! And it has the same command  ( /adminchat ), how can i disable mcMMO's adminchat commands.??

Thanks!

**Comment by EvilOlaf** [comment]
Just turn it around. Dismiss your "adminchat" plugin and use mcMMOs one. One plugin less which uses your space ;)

Anyway: http://bukkit.org/threads/mcmmo-admin-chat.61339/
