### ISSUE TITLE
Essentials Chat Prefix Bug

### ISSUE THREAD

**Issue by KhajiitV** [mcMMO-Dev/mcMMO#2444]
Pretty much whenever I update my McMMO, my chat formats are ignored and prefixes/suffixes are duplicated.

So I have a chat format that displays rank, in this example I will use a game rank, Deity. Without McMMO, it displays [Deity] [Moderator] KhajiitV: (Grey Chat) Like it should. WITH McMMO it displays (random space here) [Moderator] [Moderator] KhajiitV: (White Chat)

I have no idea what is wrong, the logs display nothing.

**Comment by t00thpick1** [comment]
Ive been told this is not an issue iwth mcMMO but ncp compat
