### ISSUE TITLE
Updating to 1.8 build #27 Issue

### ISSUE THREAD

**Issue by Catpants** [mcMMO-Dev/mcMMO#2448]
I am trying to update to mcmmo 1.8 with build #27 however most of the player data gets removed in mcmmo.users once I update. I am using flatfile. With debugging turned on it prints out it is "Updating database line from before version 1.5.01 for player" for a small amount of the large number of players. The rest are removed from the file, this is alarming as I'd like to keep all the player data. I have payed for this project, I hope to see a fix for uuid conversion.

**Comment by TfT-02** [comment]
I'm sorry for not getting back to you sooner, but are you still not able to convert the database properly? If so, can you give us a bit more information? Such as, which version of Spigot are you running, which mcMMO are you now using (probably not b27 anymore?) and is your server in online-mode?

**Comment by Catpants** [comment]
I appreciate the response either way :) I am using spigot 1.8 build #35 (https://hub.spigotmc.org/jenkins/job/BuildTools/35/) 

Using Mcmmo 1.8 dev build #34

I have debug on, I don't get any error messages, it just doesn't seem to convert all of them, once the "conversion" is over, the file size is greatly reduced with 90% of playerdata not converted. Yes I am in online mode, here is the paste of the conversion: http://pastebin.com/sCv7Cvs5

Here is the file I am trying to convert: http://pastebin.com/FRWi3B13
Here is the file after I have attempted to convert: http://pastebin.com/St8kWEkN

Let me know if using pastebin for large files is troublesome sharing, I've never tried it before. I would really appreciate a fix, or if anything, if you could send me the converted mcmmo.users file from my unconverted file.I have been waiting to update to 1.8 for quite some time. Thank you so much for your time, I am willing to work with this because it is a great plugin.

**Comment by NoChanceSD** [comment]
Got the same problem, is this ever going to get fixed?
Still have to use mcmmo version from bukkit because of this.

**Comment by t00thpick1** [comment]
I believe I personally recently fixed and tested flatfile uuid conversion.  Make me aware if its still acting up on the latest dev's.

**Comment by Catpants** [comment]
I just tested it, the issue still persists for me... If a fix doesn't work then I might have to reset all my mcmmo, I would really appreciate if you could look a little more into this.

**Comment by t00thpick1** [comment]
Could you send me a copy of your users file?

**Comment by t00thpick1** [comment]
And a server log of your test on the latest build

**Comment by Catpants** [comment]
mcmmo.users: https://www.mediafire.com/?za5c57lc2skmty8
log: https://www.mediafire.com/?za5c57lc2skmty8

**Comment by NoChanceSD** [comment]
Hello, this is still a issue for me. Any news on a fix?
