### ISSUE TITLE
Piston Ore Duplication bug still exist in  v1.5.02-SNAPSHOT-b27

### ISSUE THREAD

**Issue by jessefjxm** [mcMMO-Dev/mcMMO#2452]
Using latest version of spigot & mcmmo (v1.5.02-SNAPSHOT-b27) ,and found that Sticky Piston Ore Duplication bug still exist, which should already been fixed :(

Detail:

Edit:
Test that mcMMO 1.5.00 has already fixed this bug.

**Comment by TfT-02** [comment]
Duplicate of https://github.com/mcMMO-Dev/mcMMO/issues/2419

**Comment by k3ldon** [comment]
still works =/ on last build
