### ISSUE TITLE
MCStats Error, 'Command still being processed', build #27

### ISSUE THREAD

**Issue by ArmanA145** [mcMMO-Dev/mcMMO#2453]
When users type /mcstats, this error is put in console: http://hastebin.com/ugohubiqep.profile

Then, if they try to type another mcMMO command such as /mctop, it just says: http://prntscr.com/62qlz7

mcMMO version: 1.5.02-SNAPSHOT-b27

Server version: http://prntscr.com/62qnw0

**Comment by t00thpick1** [comment]
Should not be the case on current versions
