### ISSUE TITLE
Not getting drops from Obsidian

### ISSUE THREAD

**Issue by Ironic8b498** [mcMMO-Dev/mcMMO#2457]
When breaking a obsidian block which has lava touching one of it's side it's, you get a one out of 20 chance to get a drop. And no the blocks are not dropping in the lava since you can see and hear that happen. Also Eff V shovel don't drop any gravel when you excavate Gravel. I have tested this in 1.5.01-SNAPSHOT-b3710 and 1.5.02-SNAPSHOT-b27.  I have tried this version of mcMMO in craftbukkits latest and it works fine

**Comment by TfT-02** [comment]
mcMMO is not doing anything with the normal obsidian drop rates. Though, just to make sure I just went in-game to try and reproduce this bug, but was not able to. Obsidian is dropping fine for me, regardless if it's touching lava on one of it's sides.

Are you still having this issue on the latest Spigot and mcMMO versions? If so, am I missing something whilst trying to reproduce?
