### ISSUE TITLE
mcMMo

### ISSUE THREAD

**Issue by GhostHacks** [mcMMO-Dev/mcMMO#2459]
I Have Created A Custom Plugin That Adds A PickAxe, A Shovel, And A Axe. But My Server Has mcMMo And Id Like to Add my tools to the list so my users can still level up when using my tools is this possible?

**Comment by TfT-02** [comment]
You can use the mod config files to add custom tools. An example file can be found here https://github.com/mcMMO-Dev/mcMMO/blob/master/extras/mods/1.7.x/twilightforest.tools.yml
