### ISSUE TITLE
Stats/Internal Error

### ISSUE THREAD

**Issue by xxchikaxx** [mcMMO-Dev/mcMMO#2463]
Hello. Recently, on my Minecraft server, my Admins and I got two plugins we had been struggling to get (Autorank and Stats) to work, to actually work on our server. It came to our attention that later, McMMO started to bug out. Thinking it was our Stats plugin, we removed it, but it didn't work. We tried a few different version of McMMo, but that didn't work either. In-Game, you can't check your stats, and you can't do any admin commands via McMMO. We even went through AutoRank and scanned through the wiki, but couldn't find anything that seemed to work.

Here is the server log:

http://pastebin.com/ayPbE9G6

**Comment by xxchikaxx** [comment]
bump

**Comment by xxchikaxx** [comment]
bump

**Comment by xxchikaxx** [comment]
bump

**Comment by TfT-02** [comment]
mcMMO v1.4.08-b3544 is outdated and not supported anymore. Please update to the latest version of Spigot and mcMMO.
