### ISSUE TITLE
Database Error after changing Username

### ISSUE THREAD

**Issue by Lyndariel** [mcMMO-Dev/mcMMO#2467]
Hi there,

Since Mojang gave the User the oppurtunity to change their Accountnames, we have some problems with the mcMMO Database. If User join after Namechanging, they get the Error below:

[Craft Scheduler Thread - 20920/INFO]: mcMMO was unable to load the player data. Please inspect your database setup.

Some ideas how to fix it?

lg
Lyn

**Comment by tomibizjak123** [comment]
Not your problem. Just mcmmo needs to add support for name changing.

**Comment by zreed** [comment]
I haven't had any issues with players changing names, is there a stack trace with the error message?

**Comment by tomibizjak123** [comment]
I think that they didn't use uuids. Only uuid can fully protect players and
other things.

**Comment by t00thpick1** [comment]
If you haven't updated to a uuid compatible build, do so.
