### ISSUE TITLE
How to best use mcMMO only for stats tracking?

### ISSUE THREAD

**Issue by madtomic** [mcMMO-Dev/mcMMO#2470]
How to best setup and use this for only stats tracking?

I don't need to use special abilities for each skills. I just need this plugin to work as a form of stats tracking. Can someone help me?

**Comment by TfT-02** [comment]
mcMMO is not really intended as a stat tracking plugin, so maybe its best to try to find a dedicated stat tracking plugin. Though what you could try to do is negate any and all permission nodes which give players access to mcMMO's abilities or skills.

**Comment by madtomic** [comment]
Thanks TfT-02 as always.
