### ISSUE TITLE
PVP Rewards - money?

### ISSUE THREAD

**Issue by madtomic** [mcMMO-Dev/mcMMO#2471]
Can mcMMO pvp rewards be setup so player a killed player b, it would drop percent of holdings (money, player b had total.)

When money drops, it goes to player a's wallet automatic.?

Player A killed Player B, looted 50 Gold. etc.

If player killed had no money. It would drop nothing for killer.

**Comment by TfT-02** [comment]
mcMMO does not have any features which use PVP rewards. You could request this feature on the PVP rewards tracker.
