### ISSUE TITLE
Mcmmo Error

### ISSUE THREAD

**Issue by Damien111** [mcMMO-Dev/mcMMO#2472]
http://pastebin.com/nSC35eNU
The 3 errors underneath towny I need help solving. The server is 1.8 and using spigot.

**Comment by TfT-02** [comment]
Please update mcMMO, you're still using v1.5.00 while we're already at version v.1.5.02. I'm pretty sure this error has been solved already.

**Comment by Damien111** [comment]
Wheres the download link for 1.5.02? I can't find it anywhere on the bukkit page?

**Comment by TfT-02** [comment]
http://www.spigotmc.org/resources/mcmmo.2445/

**Comment by Damien111** [comment]
One last question, sorry, but how do I update it without it resetting? Last time I did it it reset everyones mcmmo points
