### ISSUE TITLE
Shovels not Salvagable

### ISSUE THREAD

**Issue by madisonofccs** [mcMMO-Dev/mcMMO#2473]
Shovels seem to have issues with salvaging, I have 610 repair, and 600 fishing, but for some reason even at 90% durability, I can't salvage them. The error message coming back saying that it is too damaged to be salvaged.

The server is running Spigot 1.8 (updated to the 2-24-2015 revision), and McMMO Build #34.

**Comment by TfT-02** [comment]
This is intended behavior. It's because a shovel with 90% durability is not worth a full ingot, because to craft a shovel you only need 1 ingot.
