### ISSUE TITLE
Power Level Tag

### ISSUE THREAD

**Issue by Mythcartoonist** [mcMMO-Dev/mcMMO#2474]
Could we get a way to change what the tag says instead of "[Level] Power Level"? It's a small change but I prefer "Level [Level]". Thanks!

**Comment by TfT-02** [comment]
Good suggestion.

**Comment by TfT-02** [comment]
Ohh hang on, I believe that it's not possible to place the text before the power level. Due to how Mojangs scoreboard system works it has to be `<LEVEL>  TEXT`.

**Comment by Mythcartoonist** [comment]
Does that affect the tags as well? If so, that's too bad but I appreciate that you answered back.

**Comment by TfT-02** [comment]
Yeah, I meant that the tag has to start with the number.

**Comment by madtomic** [comment]
close this, since it's not something doable.
