### ISSUE TITLE
Party Chat gets deleted on every server restart.

### ISSUE THREAD

**Issue by AnnioOoO** [mcMMO-Dev/mcMMO#2477]
Every time I restart the server the parties.yml gets completely wiped.
I'm running the latest mcmmo build on Spigot 1.8 (1.8-R0.1-SNAPSHOT).
The mcmmo.users works fine, only party chats getting deleted. We have a bungee network and this server runs offline - could that be the problem?
Any help would be appreciated.

**Comment by zreed** [comment]
If multiple minecraft servers are reading the same data files they're probably overwriting each other.

**Comment by AnnioOoO** [comment]
McMMO is only installed on one server.
I deleted the .converted file and let it recreate from the old parties.yml. It seems like that fixed it.
Thanx for your help!
