### ISSUE TITLE
Change damage values

### ISSUE THREAD

**Issue by GamingStudioX** [mcMMO-Dev/mcMMO#2478]
My server have increased all damage values x15. Players have 300 health and half a heart 15 health.
I also want mcMMO to increase these values so players dont get axe, sword or unarmed skills trained insanely quick or buffs be really underpowered.
Basically, how do I increase all the damage values and health of mcMMO to x15?

**Comment by TfT-02** [comment]
Edit the advanced.yml config file
https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/advanced.yml
