### ISSUE TITLE
onPlayerJoin causing CPU spike

### ISSUE THREAD

**Issue by LegendaryRP** [mcMMO-Dev/mcMMO#2480]
Whenever I join my server, the CPU spikes very high.
I did a timings, and it looks like McMMO is one of the main issues.
http://gyazo.com/6678f14d434322f782e21fad6346c3d3

Please overlook your onPlayerJoin code? (:

**Comment by thepotatoarmyhd** [comment]
Lol you think thats bad.... I Run a server with 40-100 players on here is my lag spike from mcmmo 
http://gyazo.com/d1c905a999c5733cae250f1f4654095e

**Comment by t00thpick1** [comment]
If you are using flatfile,  your userbase might just be large enough to necessitate the usage of mySQL

**Comment by FortyEffs** [comment]
I fixed this on my server by setting the mcmmo config "motd" property to false. For whatever reason this conditional statement in onPlayerJoin creates the lag spike:

        if (Config.getInstance().getMOTDEnabled() && Permissions.motd(player)) {
            Motd.displayAll(player);
        }
