### ISSUE TITLE
MCMMO leveling fast

### ISSUE THREAD

**Issue by Sil3ntAssassin** [mcMMO-Dev/mcMMO#2482]
I have deleted the plugin folders multiple times and reset all the configs and it seems to not fix the problem and I don't have any perms for mcmmo assigned

**Comment by EvilOlaf** [comment]
That's nice but due to no one has a second sight: Please provide more information about your issue.

If you deleted the mcmmo folder then there should be no need to reset your configs, due to the fact the the folder you deleted contained those.

**Comment by Sil3ntAssassin** [comment]
Like One hit to a mob on the server will bring my unarmed skill up 4-5 points every hit but I don't have any perms set to any group and I have reset the config so it's nothing in there...

**Comment by EvilOlaf** [comment]
mcMMO is highly configurable. Adjust the values as you need it. For example lower the extra damage for unarmed fights. Just read your config files.

**Comment by Sil3ntAssassin** [comment]
I spent hours looking at all the configs and even reset them they should be set to normal sir

**Comment by jjacobson** [comment]
If you think people are leveling too fast decrease the amount of XP gained from doing stuff.

**Comment by TfT-02** [comment]
@Sil3ntAssassin You probably have given yourself all of the XP boost perks by accident, because you have given your self all of mcMMO's permission nodes. Don't use the '*' permission or mcmmo.*
Select which permission nodes you need and grant those, instead of giving them all at once.
