### ISSUE TITLE
onPlayerJoin causing CPU spike! this need to be fixed asap....

### ISSUE THREAD

**Issue by thepotatoarmyhd** [mcMMO-Dev/mcMMO#2484]
ok.. The onplayerjoin event for mcmmo is causing my server huge lag... I need this fixed now. Can you please fix this for me. My server gets 50-100 players on mcmmo is making lag spikes.

Heres the timings for mcmmo 
http://gyazo.com/6678f14d434322f782e21fad6346c3d3

Please fix this <3

**Comment by t00thpick1** [comment]
If you are using flatfile,  your userbase might just be large enough to necessitate the usage of mySQL
