### ISSUE TITLE
Permanantly Tool Change

### ISSUE THREAD

**Issue by smooth708** [mcMMO-Dev/mcMMO#2485]
When my players are using a MCMMO Ability, such as super breaker or giga breaker, the current shovel or pickaxe they are using perminatly turns in to the McMMO GiggaDrill or MCMMO Pickaxe, I would like them to be able to use the ability with their personal tool. Thank you.

Thank you, Brendon

**Comment by TfT-02** [comment]
Can you please elaborate? I don't understand what you're requesting. Every player can use those abilities with the tools their using. What do you mean with "their personal tool"?

**Comment by smooth708** [comment]
When they use an McMmmo super breaker it makes it into just a diamond pick with McMmmo enchants and doesn't change back to there personal pickaxe

**Comment by Ericyeah** [comment]
The user is claiming that the temp. enchant doesn't revert.

**Comment by PgBiel** [comment]
I consider that a "glitch", because it VERY RARELY happens to me. But yeah, it's possible.

**Comment by EvilOlaf** [comment]
I use mcMMO nearly for half a year, mostly in the latest available versions, and never had an issue like this.
Do you have other plugins that modify items?

**Comment by GiovanH** [comment]
This seems like an unconfirmed bug report, and not a feature request at all.

**Comment by Glitchfinder** [comment]
Indeed it does.
