### ISSUE TITLE
Leaf blower not working

### ISSUE THREAD

**Issue by SirGoldman-git** [mcMMO-Dev/mcMMO#2487]
Looks like mcmmo is having some issues with 1.8.3. Some of the abilities like leaf blowing are not working anymore. It will play the sound but the ability will not work. No errors in the console.

**Comment by TfT-02** [comment]
Leaf blower is working for me, please check if you are running the latest versions of mcMMO and Spigot. Also check if you have sufficient permissions to use the ability, and have unlocked the skill.
