### ISSUE TITLE
Player Data Reset 

### ISSUE THREAD

**Issue by OffLuffy** [mcMMO-Dev/mcMMO#2488]
Using v1.5.02-b35 and Spigot 1.8, I've had 2 players now, after updating to the premium version of mcMMO, whom have had their data reset (skills and party data), and I'm not sure why. Most players so far seem to retain their data. I have a backup of the old data. Here's two user's old data (which were reset)
```
rozman888:80:::4287:0:756:31:0:8:19:3:40:0:0:4388:1331:3153:3796:1689:4160:554:1793::0:982:0:0:0:0:1425503823:1425241460:1425789904::0:0:0:1425861346:HEARTS:0:0:

kalkal14:247:::4395:152:12923:59:11:123:141:1:67:1:8:14231:6009:8223:6753:6181:6020:15269:3692::1:11686:1425227060:1424409271:1425863134:1424484670:1425855708:1424302440:1425870572::4:3260:1425270052:1425871043:HEARTS:7:11700:
```

And here's their new data (maybe some skills accrued since being online)
```
rozman888:0:::0:0:0:0:0:0:0:0:3:0:0:137:0:0:0:551:702:0:0::0:351:0:0:0:0:0:0:0::0:0:0:1425941409:HEARTS:0:0:417afb0a-401d-4a3a-a302-d4018f24dedc:1:

kalkal14:10:::380:0:0:2:0:0:0:0:0:0:0:388:0:0:0:0:0:0:0::0:0:0:0:0:0:0:0:1425943126::0:0:0:1425943313:HEARTS:0:0:216112d3-ff52-4eed-b590-7b135564f358:1:
```

I couldn't find any logs or any conspicuous errors when mcMMO initialized or when these two logged in pertaining to any issues it had converting files.

**Comment by OffLuffy** [comment]
I was able to manually correct these player's lost data by appending the UUID and the value immediately following that in the new data lines to the end of the old data lines. I've only verified this by doing /mctop and seeing the top user was back on the top and not apparently reset. Have not had that player login again yet, however.

**Comment by t00thpick1** [comment]
Odd, cannot reproduce though, if it happens again open a new issue
