### ISSUE TITLE
Combat Skills for Hoe

### ISSUE THREAD

**Issue by korianton** [mcMMO-Dev/mcMMO#2490]
I know, no sane person is going to try and fight with a hoe, but what if the hoe had special abilities?
Such as, active stills that would slow the opponent down (can call it Limb Chopper or something).  And a passive skill that would allow for mob heads to drop easier (Beheader?).  And higher attack damage as well.

**Comment by t00thpick1** [comment]
Eventually the plan is to have mcMMO modular enough to do this via configuration.  However, barring that development, hoe combat will not be a feature any time soon.
