### ISSUE TITLE
MCMMO Fishing Skill w/ Enchants

### ISSUE THREAD

**Issue by Ericyeah** [mcMMO-Dev/mcMMO#2492]
How are the MCMMO treasure drops for fishing affected by the enchantments on a fishing rod?

**Comment by t00thpick1** [comment]
Currently, not at all

**Comment by Ericyeah** [comment]
@t00thpick1 Does that mean that if your fishing rod is enchanted, the enchantments are ignored, or does that mean your MCMMO skill is ignored?
Can you make this a TODO to implement? Couldn't you just check for enchantments up the mcmmo skills effectiveness.

**Comment by TfT-02** [comment]
Actually, enchanting your fishing rod **does** influence the treasure drop rates. The enchantment 'Luck of the Sea' increases the odds of getting rarer treasures, for about 1% for each enchantment level. It's not much, but certainly some way to increase the odds of getting higher tier treasures.

**Comment by Ericyeah** [comment]
@TfT-02 When I use a rod with Luck of the Sea X on an account with lvl 1000 fishing, I almost exclusively catch fish (just normal fish).
Also, above 1000 are any variables/skills increased when you level your fishing #.

**Comment by TfT-02** [comment]
By default the Fishing treasure drop rates are configured as shown on the wiki https://github.com/mcMMO-Dev/mcMMO/wiki/Fishing#-item-drop-rates

The levels required to reach a certain tier are configureable here https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/advanced.yml#L146

By default you will not increase your variables in Fishing beyond level 875.
