### ISSUE TITLE
java.lang.IllegalStateException: Unregistered scoreboard component

### ISSUE THREAD

**Issue by Ebed-Melek** [mcMMO-Dev/mcMMO#2493]
I am setting up a new server and would like to offer mcMMO as a feature to our players. I installed the plugin and it was working great. I later installed FeatherBoards to display a scoreboard to show things like # of users online, # of kills, # of Death, .etc. As soon as I loaded that plugin I started getting console errors when running /mcstats. The first time it flashes the mcMMO scoreboard for a split second. The second time if throws a stacktrace:

13.03 19:15:18 [Server] INFO ... 14 more
13.03 19:15:18 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot18.jar:git-Spigot-c3c767f-33d5de3]
13.03 19:15:18 [Server] INFO at com.gmail.nossr50.commands.player.McstatsCommand.onCommand(McstatsCommand.java:34) ~[?:?]
13.03 19:15:18 [Server] INFO at com.gmail.nossr50.util.scoreboards.ScoreboardManager.enablePlayerStatsScoreboard(ScoreboardManager.java:267) ~[?:?]
13.03 19:15:18 [Server] INFO at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.setTypeSelfStats(ScoreboardWrapper.java:299) ~[?:?]
13.03 19:15:18 [Server] INFO at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.loadObjective(ScoreboardWrapper.java:374) ~[?:?]
13.03 19:15:18 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scoreboard.CraftObjective.unregister(CraftObjective.java:104) ~[Spigot18.jar:git-Spigot-c3c767f-33d5de3]
13.03 19:15:18 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scoreboard.CraftObjective.checkState(CraftObjective.java:112) ~[Spigot18.jar:git-Spigot-c3c767f-33d5de3]
13.03 19:15:18 [Server] INFO Caused by: java.lang.IllegalStateException: Unregistered scoreboard component
13.03 19:15:18 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72]
13.03 19:15:18 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
13.03 19:15:18 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
13.03 19:15:18 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
13.03 19:15:18 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
13.03 19:15:18 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_72]
13.03 19:15:18 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_72]
13.03 19:15:18 [Server] INFO at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
13.03 19:15:18 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
13.03 19:15:18 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
13.03 19:15:18 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
13.03 19:15:18 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
13.03 19:15:18 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[Spigot18.jar:git-Spigot-c3c767f-33d5de3]
13.03 19:15:18 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot18.jar:git-Spigot-c3c767f-33d5de3]
13.03 19:15:18 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot18.jar:git-Spigot-c3c767f-33d5de3]
13.03 19:15:18 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'mcstats' in plugin mcMMO v1.5.02-b35
13.03 19:15:18 [Server] ERROR null

Is there something I can do in the configs to allow FeatherBoard and mcMMO to work together. I am not sure, but I believe Vortex has both working in their Skyblock server.

Thanks,

Chris

**Comment by t00thpick1** [comment]
Is a spigot issue, update spigot.

**Comment by Sketaful** [comment]
I have this problem and I run the latest compiled spigot. Also installed featherboard. So something between them.

**Comment by justin2001** [comment]
I also have this problem. When i type /mcstats it cant show anything after i have featherboard installed. How do i allow mcstats to show on featherboard?

**Comment by Sketaful** [comment]
That is a featherboard issue. Ask there. You must turn off scoreboard in mcmmo as well..

**Comment by justin2001** [comment]
Thanks.

**Comment by justin2001** [comment]
If I turn off scoreboard in mcmmo, can i see mcstats in featherboard verion?

**Comment by justin2001** [comment]
#version
