### ISSUE TITLE
Pool of Reflection - XP Bonus (Diablo III)

### ISSUE THREAD

**Issue by mcMMO** [mcMMO-Dev/mcMMO#2496]
Featured in Diablo 3, there is a Pool of Reflection which increased your XP rate by 25%.

If we could add in a similar style for example:

Touch_block_active: false
    TOUCH_BLOCK: DIAMOND ORE
Stay_alive_active: true
    STAY_ALIVE: 3600
XP_Bonus: 50.0
XP_Amount: 100000
XP_Stack: true

The player would have to stay alive for one hour to receive a XP bonus of 50%. The XP bonus is lost on death.

With Touch_Block, the player would have to punch or right click a specific block to start the XP bonus.

XP_Amount refers to the amount of bonus XP which can be given. Set 0 for unlimited. Once the limit is exceeded the XP bonus will end.

XP_Stack means if the player receives the bonus twice would the XP_Amount increase or not. The XP_Bonus can not increase with stack enabled.

**Comment by t00thpick1** [comment]
Hey bud, nothing personal but as long as you keep using that username I'm going to close your tickets,  the username is really misleading especially given that you have elected to use @TfT-02's profile picture as well.
