### ISSUE TITLE
Fishing Bug

### ISSUE THREAD

**Issue by Ericyeah** [mcMMO-Dev/mcMMO#2500]
Sometimes if you're fishing with other players in range the fish (or caught item) will be shot into the vicinity of those players rather then yourself.

**Comment by Ericyeah** [comment]
get! bug id 2500.

**Comment by TfT-02** [comment]
Does this happen when catching fish, treasures or traps? Also, please include the version numbers of mcMMO and Spigot in your ticket. ;)

**Comment by Ericyeah** [comment]
I've never observed it w/ traps being my lvl is so high. (be jelly jk)
protocol hack 1.7.10 spigot version
1.5.02 snapshot-b27

**Comment by TfT-02** [comment]
mcMMO does not alter the trajectory of a fish when it's caught. We do calculate it when a trap is found, but that is a different situation. So I believe that this bug you're describing is not caused by mcMMO.
