### ISSUE TITLE
Could not load player profile after namechange

### ISSUE THREAD

**Issue by Bestle** [mcMMO-Dev/mcMMO#2503]
I just want to quickly preface this issue and say that name changes work absolutely fine usually, but not in this specific case.

A player of mine has now changed their name twice. The first time there were no issues but after the second name change, their mcMMO player profile never loads and the "giving up loading profile" message is shown.

The new username of this player is a username previous used by another player on the server. I think this is the cause of the issue.

No useful errors seem to be shown in the console.

I am using and SQL database for player storage.

**Comment by t00thpick1** [comment]
I am aware of the issue and contemplating a possible solution, thankyou for the report.

**Comment by Bestle** [comment]
Good to hear, currently this player cannot use mcMMO on my server so a quick fix would be appreciated.

**Comment by Bestle** [comment]
Any progress on this? Pretty frustrating for some of my players.

**Comment by Bestle** [comment]
Happened again now with another player - Is there even a possible temporary workaround?

**Comment by ashower** [comment]
This affects usernames of 16 or more characters and creating all the mcmmo tables using mysql insert statements works around the problem
I believe it can be some problem inside the mcmmo code not working for usernames longer than 16 characters  when new user joins  as the username isn't stored in mcmmo users table

**Comment by iProLynch98** [comment]
Yes the same thing has happened to me. I changed my name and all my McMMO stats reset back to 0... :-1:

**Comment by iProLynch98** [comment]
Is there any solution to get my stats back without changing my name back to the original in a month?

**Comment by ashower** [comment]
Server admins / whoever administers the mcmmo database can edit it at will.
Also what works for me is grabbin the username / uuid off the log and inserting it via SQL statement to the mcmmo users table, and then inserting the internal mcmmo database user_id to all the other tables to fix the problem.

**Comment by Bestle** [comment]
Has this project been abandoned? Seems odd that such a critical bug hasn't yet been resolved.

**Comment by Jaremoea** [comment]
Also having this issue, any fix?

**Comment by Bestle** [comment]
Still no fix for this? :(

**Comment by Bestle** [comment]
Here's what is shown in console when one of these players login.

http://pastebin.com/rJCnqCc2
