### ISSUE TITLE
Communications link failure

### ISSUE THREAD

**Issue by Ownercz** [mcMMO-Dev/mcMMO#2504]
Hello, 
from time to time, McMMO crashes one of my Minecraft servers (running on the same machine, not happening simultaneously) and error is always the same.

I already tried multiple McMMO versions (now running latest dev) and multiple Spigot versions 1.8 and 1.8.3 (now).

**DB**
MySQL is MariaDB server, no problems overload, running on the same machine and all other servers don´t any trouble when the crash happens.
Screenshot, how large DB for one specific server is.
![screenshot_53](https://cloud.githubusercontent.com/assets/1702837/6769026/d76e5448-d089-11e4-9ecb-40d8a3f9a35c.png)
Config:
![screenshot_54](https://cloud.githubusercontent.com/assets/1702837/6769034/51839504-d08a-11e4-925d-73cda30b3a7e.png)
DB server itself has default configuration.

**Error**
McMMO crash: http://pastebin.com/gJFz9qsP
Thread dump: http://pastebin.com/Px5ABW4A

Thank you for any advice!

**Comment by t00thpick1** [comment]
Will investigate, thankyou for the thorough report.

**Comment by t00thpick1** [comment]
The thread dump says its something to do with jobs.
