### ISSUE TITLE
second smelt doesn't work with fish.

### ISSUE THREAD

**Issue by Ericyeah** [mcMMO-Dev/mcMMO#2507]

**Comment by Time6628** [comment]
Maybe an option in the config to enable this? I think this isn't in mcMMO because it's just not logical...fish don't duplicate.. :laughing:

**Comment by Ericyeah** [comment]
neither do raw materials...

**Comment by Time6628** [comment]
Have you ever looked at an ore? There is defiantly more than 1 ingot in them. :stuck_out_tongue:

**Comment by t00thpick1** [comment]
Second Smelt is meant to work with ores exclusively,  until we fully modularize mcMMO(thereby making full configuration possible) this will not be an option.
