### ISSUE TITLE
Lost all of my stuff!

### ISSUE THREAD

**Issue by pwiglet** [mcMMO-Dev/mcMMO#2508]
Logged on and my sword with knock back 2 flame and power 2 my bow with flame power IV and i think infinity my prot 2 armour. Stack of cooked meat My axe 3 stacks of quarts torches and 6 diamonds more stuff as i was in the middle of building but will do with the essentials.

**Comment by Time6628** [comment]
Why report this to mcMMO? I don't think mcMMO even can delete all items, and if it did I don't think the mcMMO team is going to give back the items you listed...

**Comment by TfT-02** [comment]
Report this to the server you're playing on. This is the issue tracker for mcMMO.
