### ISSUE TITLE
Java 8 not supported

### ISSUE THREAD

**Issue by MCArcadeX** [mcMMO-Dev/mcMMO#2510]
i use my spigot1.7-patched with mcmmo, it crashes the server at startup, but when i remove the plugin, then the server works

**Comment by Time6628** [comment]
Then use Java 7? :cat:

**Comment by EvilOlaf** [comment]
My guess is this issue is related to Spigot 1.7, because with Spigot 1.8 mcMMO runs quite well with Java8.

**Comment by MCArcadeX** [comment]
i run a norwegian hosting company, and i use java 8 to fully support new plugins. Btw its an issue with mcmmo on spigot 1.8 too

**Comment by t00thpick1** [comment]
"crashes the server"    <--  This is useless to me unless you provide a crash report,   if there is a crash, there will be a crash report or error somewhere,  find it,  and provide it to us, and we can investigate further,  otherwise, nothing I can do as others state it works for them.
