### ISSUE TITLE
Ability to watch over player's party chat

### ISSUE THREAD

**Issue by Someguynamedbob** [mcMMO-Dev/mcMMO#2511]
Would only work with people that are opped in the multiplayer server.

**Comment by Time6628** [comment]
Look up mcMMO Party admin.

**Comment by Someguynamedbob** [comment]
Do you know if mcMMO Party admin works with version 1.5.00-b3547?

**Comment by TheChampTF** [comment]
Would like to see support for this also as the thirdparty plugin is way out of date.
