### ISSUE TITLE
Skill caps that truncate

### ISSUE THREAD

**Issue by z1haze** [mcMMO-Dev/mcMMO#2512]
I have an issue with adding mcmmo caps as an after thought of about a year. I have players with over 35k per skill, and I've just set the cap to 8k. Unfortunately mcmmo doesnt have the functionality built in to truncate existing players over that cap down the the cap level. I would think that should be something that would be standard. Maybe it was an oversight?

**Comment by JH159753** [comment]
Why would you do that? the players worked hard for it, please don't shoot them down

**Comment by z1haze** [comment]
That's irrelevant

**Comment by t00thpick1** [comment]
Well crafted SQL queries could do this for you, but I can potentially look into building this into us in the future..

**Comment by z1haze** [comment]
Indeed, that's how I solved this issue, but it would be nice if the plugin offered support for this.
