### ISSUE TITLE
Walking skill ... how to disable?

### ISSUE THREAD

**Issue by bloggy** [mcMMO-Dev/mcMMO#2515]
Hello,
1.) when did you add walking skill? And how can I disable it or disable the firework for it?

2.) I am missing the tools.yml and armor.yml which you mention in the changelog. They have not been generated. I am using mcmmo 1.5.03-dev-b45

**Comment by TfT-02** [comment]
1) April fools! :)

2) Enable them here https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/config.yml#L198

**Comment by PassiveBrain** [comment]
config.yml 490 line LargeFireworks: true -> false 
https://github.com/mcMMO-Dev/mcMMO/issues/2879#issuecomment-478628191
