### ISSUE TITLE
Where can I see a real full list of permissions? 

### ISSUE THREAD

**Issue by drtro** [mcMMO-Dev/mcMMO#2517]
Your github page cuts off half the description on every browser I've tried. Would like to see what each permission node does rather than just guessing or assuming.

**Comment by EvilOlaf** [comment]
Mark the text in the 3rd column from the left to the right. This will shift the whole column to the right so you can see the complete description.
This is a known issue with Github wiki.

**Comment by drtro** [comment]
I don't see an option to do that.

**Comment by EvilOlaf** [comment]
There isn't. That's just a workaround.

**Comment by drtro** [comment]
How do I do that?

**Comment by drtro** [comment]
I don't think its worth going through all of them actually. 

mcmmo.ability.all
mcmmo.commands.mctop.all
mcmmo.skills.all

These are all I really need for players to level up, use the abilities, and view to top level players right?

**Comment by TfT-02** [comment]
Yeah, sorry about the wiki page cutting off.

You can find all of the nodes in plugin.yml
https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/plugin.yml
