### ISSUE TITLE
Duplication bug

### ISSUE THREAD

**Issue by thepotatoarmyhd** [mcMMO-Dev/mcMMO#2519]
Players are able to place down ores, switch sticky pistons to move them back and forth a few times, then mine them up with silk touch for mining xp, and it also duplicates ores. We are running version 1.5.02,

Here are some screenshots of the machine.

Spigot Build:
http://gyazo.com/0d13312c6b4421326ede4fbcec0be7e9

Pics of machine:
http://gyazo.com/917f88efd1031e65ba4c4cc96e3f948c
http://gyazo.com/f860e9c1d97054501f0bda964673b989
http://gyazo.com/1d23f012b756f532588b6e9f374a980a

**Comment by TfT-02** [comment]
This has been fixed in the latest dev build, mcMMO 1.5.03-b45
