### ISSUE TITLE
mcMMO Perks Experience Always displaying

### ISSUE THREAD

**Issue by Vandesdelca32** [mcMMO-Dev/mcMMO#2525]
The latest build of mcMMO (build 46 on the jenkins) using spigot 1.8, as well as bpermissions latest version, mcMMO always displays [mcMMO perks] Experience: Recieve boosted XP in certain skills when no XP event is running, nor whether or not the player has any of the XP boost permissions.

I am using currently no permissions, just being OP is enough to display it.

Edit: This is only on login when opped, that's it. None of the skills list a perk active.

**Comment by TfT-02** [comment]
It's because you're OP - you've granted yourself ALL of mcMMO's permission nodes, including all of the perks.
https://github.com/mcMMO-Dev/mcMMO/wiki/Permissions#using-permissions-to-give-certain-groups-perks

**Comment by Vandesdelca32** [comment]
Those permissions aren't granted to ops. The only mcmmo permissions I gave myself were mcMMO.defaults and mcMMO.defaultsop, to be sure it was a bug

**Comment by TfT-02** [comment]
> I am using currently no permissions, just being OP is enough to display it.

If you're OP'ed you have all permissions granted.

**Comment by Vandesdelca32** [comment]
That doesn't explain why the message shows up when the permissions are set up properly though...
Here's a [link to my permissions file](http://pastebin.com/ETSdXq9Z).

Sorry if I'm being obnoxious about this, if it really is a permission node that is just falsely documented (I checked the plugin.yml to be sure as well, and it is not given to Ops by default).

And [here's a screenshot](http://i.imgur.com/efar3rZ.png) showing superperms reporting I don't have the permissions. Being OPed has never overridden that. 

[Just for good measure, the login message](http://i.imgur.com/pYtebjg.png)
