### ISSUE TITLE
Certain players can't harm each other only when mcmmo is installed.

### ISSUE THREAD

**Issue by NobleStrike** [mcMMO-Dev/mcMMO#2527]
EDIT: Issue was due to the players being in the same party and it interfered with pvp in arenas and worlds. Can i toggle it so even if they are in a party they can harm eachother?

Im having a bug where certain players cant pvp eachother in pvp worlds/areas

Its only when mcmmo is installed. When i remove mcmmo it works fine.
That rules out any other plugins affecting pvp.
I had them try with bow, sword and fist to rule out anything like that.
I can harm them (even with op off), but they cant harm eachother unless mcmmo is uninstalled.
I only changed one config setting for debug to be on. Nothing pops up in console for this error.

Version.
CraftBukkit version git-Spigot-2f787bd-1a1bc08 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)

Also i was the one with the issue of mcmmo crashing on /stop but that error fixed itself for no reason.

Thank you for your time.

**Comment by TfT-02** [comment]
Yes, you can enable friendly fire using permissions 
https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/plugin.yml#L1258
