### ISSUE TITLE
/(skill) not updated. /mctop (skill) shows accurately

### ISSUE THREAD

**Issue by Zodzie** [mcMMO-Dev/mcMMO#2529]
Hello.

I am on spigot 1.8.3 and I put into spigot/plugins my old mcmmo directory + files from 1.7.10 bukkit.

I then also put in the latest mcmmo jar (the one i paid 10 bucks for) in spigot/plugins.

Now when players do /mctop mining , it shows their mining level as it was on 1.7.10.
When they do /mining it shows as level 0, and they are able to increase it.

Please advice at how i can get it synced back up. Was thinking 10 buck purchase would be a little more seamless.

Thanks,

Xodz 'coragaming.com' RSGP server

**Comment by Zodzie** [comment]
Any advice for this? In the flatfile > mcmmo.users  it shows the exp and levels correctly... But in-game if i type /mining it doesn't show what flatfile shows (says level 0) and i get no mining bonuses. Please assist

**Comment by t00thpick1** [comment]
Any errors in the server console?
