### ISSUE TITLE
Summoned Mobs mobs don't despawn after relog

### ISSUE THREAD

**Issue by minoneer** [mcMMO-Dev/mcMMO#2531]
Expected behaviour:
When summoning a mob with "Call of the Wild", they get a live span of 240 seconds. If not renamed, they despawn after that amount of time is up.

Problem:
When a player summons a mob, logs out and back in, the mobe will stay alive much longer, possibly forever. I've watched one for 20 minutes and it did not die. When the player stays with it, everything works as expected. Not sure if it's related to the actual logout or just the chunk reloading, I'll investigate on that further.

Versions:
mcMMO: 1.5.03-SNAPSHOT-b46
spigot: git-Spigot-4c7d0c0-7d020a7 (MC: 1.8.3)
(we have also noticed the same bug with prior versions of mcMMO and spigot 1.8)

No errors or other related entries in logs.

Thanks for your time, minoneer

**Comment by PsychoNavigator** [comment]
Can confirm this. It doesn't just happen on relog, but on death as well. I've had players reporting no despawn for well over an hour, and having tested myself, I'm currently in a staring match with a wolf that's going 15 minutes strong nearly.

Please, help me. I think he's going to win...
