### ISSUE TITLE
Bad hitboxes?

### ISSUE THREAD

**Issue by TheExceed** [mcMMO-Dev/mcMMO#2532]
I have a lot of players complain about hitboxes being terrible. The only plugin that handles any type of PvP event is McMMO. So, is this a known problem? Is there a fix to it?
Any help would be appreciated.

**Comment by Theepwner** [comment]
Do you use NoCheatPlus? If so, that would be the case.

**Comment by TheExceed** [comment]
@Theepwner 
Do you suggest something else? Or proper configuration? 
I guess I might just be bad, but I feel like NCP is extremely difficult to configure for PvP.

**Comment by Theepwner** [comment]
Check out this: https://github.com/asofold/NCPDocs/blob/master/wiki/configuration/checks%2Fchecks.creole

**Comment by TheExceed** [comment]
@Theepwner 
I will check it out, but not sure how checks would screw with hitboxes.

**Comment by Theepwner** [comment]
Do you use cncp as well?

**Comment by TheExceed** [comment]
@Theepwner 
Yes, I do.

**Comment by TfT-02** [comment]
I don't see how mcMMO would or could influence hitboxes.

**Comment by TheExceed** [comment]
@TfT-02 
It handles quite a few things dealing with PvP, it can easily mess them up.

**Comment by TfT-02** [comment]
Damage values in entity damage events, yes. We don't do anything with the actual hitboxes though. Aren't you suffering from lag? That could also cause hits to not get detected properly.

**Comment by TheExceed** [comment]
No, its not lag, I have tested it quite thoroughly. but glad you use lag as an excuse.

**Comment by Theepwner** [comment]
@TheExceed Take off nocheatplus and see the difference.

mcMMO has nothing to do with hit detection, hit boxes, whatever you may call it.

**Comment by t00thpick1** [comment]
mcMMO does not alter hitboxes in any fashion.
