### ISSUE TITLE
Bedrock

### ISSUE THREAD

**Issue by Juusotnt** [mcMMO-Dev/mcMMO#2533]
Mining Skill does not increas when mining bedrock (op factions, op prison) and stuff. is this a problem in mcMMo? if it is fix it please. if its about the owner of the server may i know so ill talk with him

**Comment by EvilOlaf** [comment]
Bedrock was never meant to be breakable without creative mode. Therefore my guess is mcMMO does not recognize it at mining.

**Comment by t00thpick1** [comment]
This would be up to the plugins allowing you to break bedrock
