### ISSUE TITLE
Can not change party chat format

### ISSUE THREAD

**Issue by RobertKozin** [mcMMO-Dev/mcMMO#2534]
I cant seem to be able to change the name color in party chat

Config:
'[[LIGHT_PURPLE]][[BOLD]]PARTY [[DARK_PURPLE]]{0}'

Output:
(bold purple)PARTY (gold)AIDERMOI message

Versions:
mcMMO: 1.5.03-SNAPSHOT-b46
git-Spigot-dbe012b-61ef214 (MC: 1.8.3)

**Comment by TfT-02** [comment]
Party leaders' names will be in gold.
