### ISSUE TITLE
MCMMO and Magical Crops

### ISSUE THREAD

**Issue by Disturbeddragon1** [mcMMO-Dev/mcMMO#2535]
I'm not even sure if I'm posting in the right area, if not by all means feel free to tell me, but I was wondering if anyone has got magical crops to work with MCMMO? I've tried setting the tile entity name in and a few other variations of the crops to the herbalism section in the config for MCMMO, but alas it never seems to either recognize or attempt to read those as valid. So I'm not sure if I'm just doing something wrong or if there may be a possible issue with MCMMO.

**Comment by t00thpick1** [comment]
No clue sorry :(
