### ISSUE TITLE
Players dupping ores with double drops with silk touch.

### ISSUE THREAD

**Issue by NobleStrike** [mcMMO-Dev/mcMMO#2539]
I have players dupping ores with silk touch after placing the ores, moving them with pistons and mining them. Please disable double drops with silk touch.

**Comment by EvilOlaf** [comment]
Version?

Did you try latest dev build?

https://github.com/mcMMO-Dev/mcMMO/issues/2522

**Comment by NobleStrike** [comment]
Seems to be fixed! thank you!

**Comment by TfT-02** [comment]
Glad to hear :)
