### ISSUE TITLE
Support for Multiverse

### ISSUE THREAD

**Issue by Fate-Kun** [mcMMO-Dev/mcMMO#254]
Either implement a way to turn it on/off for each specific world with Mulitverse.
or create a blacklist option in the config to disable it on worlds with the names specified
e.g:

Blacklisted_Worlds:
- World_the_End
- Adventure_World

**Comment by Proplex** [comment]
Curious as to the progress of this feature. I'd rather have multiworld support than relying on setting up another server and Bungee'ing everything together just so my players can have different McMMO levels per-world.

**Comment by nossr50** [comment]
https://github.com/mcMMO-Dev/mcMMO/issues/4333#issuecomment-727137665
