### ISSUE TITLE
Alchemy Bug

### ISSUE THREAD

**Issue by Cyber4** [mcMMO-Dev/mcMMO#2542]
Basically a bug with all versions since the beginning of alchemy.

Players can keep alternating redstone and glowstone on one set of pots to grind super fast.  Can you make it so you can't get xp by adding glowstone to extended potions or redstone to boosted pots?

**Comment by JH159753** [comment]
not a bug, it's in Minecraft's code.

**Comment by t00thpick1** [comment]
As said above
