### ISSUE TITLE
Bungee issue.

### ISSUE THREAD

**Issue by Jerethkhan** [mcMMO-Dev/mcMMO#2543]
When running Bungee the server needs to be set offline. mcMMO doesn't seem to like this:

[Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.

That last part " set "online-mode" to "true"" is not possible with bungee networks. Port-forwarding is on in Bungee and the servers are set Bungee:true, however, no UUID's are populating. What's more alarming is renamed players cause and additional error:

[Server] ERROR Could not obtain a name for the player with UUID 7a579558-dd76-3f1a-899a-75d261cd20ae
22.04 21:30:06 [Server] ERROR Could not obtain a name for the player with UUID 626b5ecd-08ae-37a7-a3e8-1d02cdf24994
22.04 21:30:06 [Server] ERROR Could not obtain a name for the player with UUID 024e54f8-d9f5-360d-8669-968d04f658f5

I recently fixed an issue with another plugin not working properly through bungee and I compared them to my list, they are Offline UUID's of players that had been renamed in the past. The names associated with those UUID's are their current names. Back with mcMMO 1.5.0 with UUID support, when a renamed player connected it completely wiped the mcmmo.users file and gave, "player not set up" errors for everyone afterwards. Versions between 1.5.02 and 1.5.03 are causing the issues mentioned above.

**Comment by BlackBeltPanda** [comment]
That's not an MCMMO issue.

**Comment by tofwap** [comment]
not an MCMMO issue, but the fix is simple, go to your bungee config and enable UUID forward.

**Comment by t00thpick1** [comment]
See above
