### ISSUE TITLE
archery mcmmo xp bug

### ISSUE THREAD

**Issue by ashower** [mcMMO-Dev/mcMMO#2545]
when using bow / arrows, players gain xp from naturally spawned mobs even when the mobs have xp gain disabled.

relevant part of config.yml
    Archery:
        Enabled_For_PVP: true
        Enabled_For_PVE: true
        Level_Cap: 0
relevant part of experience.yml

Experience gained in every skill will get multiplied by this value. 1.0 by default, 2.0 means two times as much
    Multiplier:
        Global: 1.0
        PVP: 1.0
   Experience gained from mobs not naturally spawned will get multiplied by this value. 0 by default.
    Mobspawners:
        Multiplier: 0
    Experience gained will get divided by these values. 1.0 by default, 2.0 means two times less XP gained.
    Modifier:
        Swords: 1.0
        Taming: 1.0
        Acrobatics: 1.0
        Excavation: 1.0
        Herbalism: 1.0
        Unarmed: 1.0
        Woodcutting: 1.0
        Mining: 1.0
        Archery: 1.0
        Axes: 1.0
        Repair: 1.0
        Fishing: 1.0
        Alchemy: 1.0
  Combat:
        Multiplier:
            Animals: 0.0
            Creeper: 0.0
            Skeleton: 0.0
            Spider: 0.0
            Giant: 0.0
            Zombie: 0.0
            Slime: 0.0
            Ghast: 0.0
            Pig_Zombie: 3.0
            Enderman: 0.0
            Cave_Spider: 0.0
            Silverfish: 0.0
            Blaze: 0.0
            Magma_Cube: 0.0
            Ender_Dragon: 0.0
            Wither: 0.0
            Witch: 0.0
            Iron_Golem: 0.0
            Wither_Skeleton: 0.0
            Endermite: 0.0
            Elder_Guardian: 0.0
            Guardian: 0.0
    Archery:
        Distance_Multiplier: 1.0

**Comment by ashower** [comment]
Also Archery XP is gained from mobs spawned by mob_spawner blocks despite the setting being 0

**Comment by t00thpick1** [comment]
Archery gains bonus XP based on archery shot distance, if you want to disable that and only have damage xp,   set the DistanceMultiplier to 0

**Comment by ashower** [comment]
I respectfully disagree - see the math.
1) mobs XP is set to 0.0, spawner xp is set to 0.0
2) according to what's documented in config, then if base XP (mob xp and spawner xp ) is 0 then any "bonus" should be multiplication of 0 which yields 0 result

**Comment by t00thpick1** [comment]
That would be a way to think about it,  but in this case, at least the way it is currently implemented,  the distance multiplier is (distance * multiplier)  and that amount is ADDED to the normal exp calculations,  since there is really no way to multiply it in sanely.  If you can think of one, feel free to suggest it.
