### ISSUE TITLE
Build error - just tried

### ISSUE THREAD

**Issue by madtomic** [mcMMO-Dev/mcMMO#2546]
[INFO] Compiling 335 source files to C:\gitbase\mcMMO\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] \gitbase\mcMMO\src\main\java\com\gmail\nossr50\skills\fishing\FishingMan
ager.java:[108,30] error: reference to getTargetBlock is ambiguous
[ERROR] \gitbase\mcMMO\src\main\java\com\gmail\nossr50\listeners\PlayerListener.
java:[239,36] error: reference to getTargetBlock is ambiguous
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 29.675 s
[INFO] Finished at: 2015-04-23T11:16:47-04:00
[INFO] Final Memory: 18M/230M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.
3.2:compile (default-compile) on project mcMMO: Compilation failure: Compilation
 failure:
[ERROR] \gitbase\mcMMO\src\main\java\com\gmail\nossr50\skills\fishing\FishingMan
ager.java:[108,30] error: reference to getTargetBlock is ambiguous
[ERROR] \gitbase\mcMMO\src\main\java\com\gmail\nossr50\listeners\PlayerListener.
java:[239,36] error: reference to getTargetBlock is ambiguous
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption

**Comment by t00thpick1** [comment]
Fix your project setup
