### ISSUE TITLE
Duplication issues

### ISSUE THREAD

**Issue by XenRevo** [mcMMO-Dev/mcMMO#2547]
There's currently a dupe glitch with ores using mcmmo
Here's a link to a video outlining it and how to do it https://www.youtube.com/watch?v=0kLHjVw0BhA

**Comment by EvilOlaf** [comment]
Duplicate https://github.com/mcMMO-Dev/mcMMO/issues/2539 https://github.com/mcMMO-Dev/mcMMO/issues/2522 https://github.com/mcMMO-Dev/mcMMO/issues/2519

**Comment by Asura35** [comment]
Why do you think its a duplicate? this issue isn't fixed, it said in one of those posts to use a higher build that I can't even find.

**Comment by Asura35** [comment]
https://ci.drtshock.net/job/MCMMO/lastBuild/ would  this fix this issue or not? it shouldn't have to make us go to a dev version but would that fix it?

**Comment by XenRevo** [comment]
@EvilOlaf can you reply?

**Comment by EvilOlaf** [comment]
Actually there is nothing more I have to say about that. As readable in the related issue reports the duplication bug has been fixed in the current dev builds. If you want this to be fixed on your servers, use them. Otherwise don't.

**Comment by Asura35** [comment]
"https://ci.drtshock.net/job/MCMMO/lastBuild/ would this fix this issue or not? it shouldn't have to make us go to a dev version but would that fix it?"
As far as I'm concerned that is the dev builds but apparently not as you didn't confirm that? please link me to the right page @EvilOlaf

**Comment by TfT-02** [comment]
Using the latest dev build will fix the issue.

**Comment by Asura35** [comment]
Lol........................... *facepalm* so hard
