### ISSUE TITLE
how to disable admin chat

### ISSUE THREAD

**Issue by ghost** [mcMMO-Dev/mcMMO#2548]
How can i disable admin chat? I have separate plugin for admin chat, and i want to disable the one form MCMMO, i tried to delete the command from plugin.yml but after, mcmmo didn't worked anymore. Can anyone give me the modified mcmmo jar file without admin chat please?

**Comment by xion87** [comment]
mcmmo must only use skill and stop, not more extra features like adminchat -_- and i can't disable now with latest releases! GG
