### ISSUE TITLE
You need to get these bugs fixed.

### ISSUE THREAD

**Issue by mcMMO** [mcMMO-Dev/mcMMO#2549]
25.04 06:32:19 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
25.04 06:32:19 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [minecraft_server.jar:git-Spigot-2ec6f06-7722428]
25.04 06:32:19 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [minecraft_server.jar:git-Spigot-2ec6f06-7722428]
25.04 06:32:19 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [minecraft_server.jar:git-Spigot-2ec6f06-7722428]
25.04 06:32:19 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:720) [minecraft_server.jar:git-Spigot-2ec6f06-7722428]
25.04 06:32:19 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [minecraft_server.jar:git-Spigot-2ec6f06-7722428]
25.04 06:32:19 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-2ec6f06-7722428]
25.04 06:32:19 [Server] INFO at com.gmail.nossr50.runnables.items.TeleportationWarmup.run(TeleportationWarmup.java:39) ~[?:?]
25.04 06:32:19 [Server] INFO at org.bukkit.Location.distanceSquared(Location.java:452) ~[minecraft_server.jar:git-Spigot-2ec6f06-7722428]
25.04 06:32:19 [Server] INFO java.lang.IllegalArgumentException: Cannot measure distance to a null location
25.04 06:32:19 [Server] WARN Task #638920 for mcMMO v1.5.03-dev-b45 generated an exception

**Comment by t00thpick1** [comment]
I will not respond to support requests from you while you use @TfT-02's image and our name unofficially
