### ISSUE TITLE
Disabling Itemshare for parties?

### ISSUE THREAD

**Issue by Theepwner** [mcMMO-Dev/mcMMO#2552]
Is there a way to disable itemsharing for parties that currently have that feature enabled/unlocked?

We have come across a problem with using itemsharing alongside our current gameplay, and wish for current parties to remain, just without itemsharing. I have attempted negating the perm mcmmo.commands.party.itemshare, but that just disallows players from changing their current itemshare setting. I have also tried removing the itemshare unlock level line from the config, but that just regenerates.

Any possible things I could do? Also, if resetting parties is the only option, would there still be a way to make it so parties could never unlock it? (besides making it so they can't use the command, or by making the unlock level very high)

Thanks.

**Comment by Ericyeah** [comment]
What issue is availed through itemshare being enabled?

**Comment by Theepwner** [comment]
@Ericyeah the issue won't affect every type of server. With itemshare, some of the items you pickup will instead go to online members of your party. Players on my server have used this feature to transfer important items to party members that are pvping and low on supplies.

**Comment by Ericyeah** [comment]
ItemShare_UnlockLevel:11

Try this.

**Comment by Theepwner** [comment]
Thanks, never thought of that. Will reply back if it doesn't work.
