### ISSUE TITLE
Console getting lots of warns from mcmmo

### ISSUE THREAD

**Issue by rafiport** [mcMMO-Dev/mcMMO#2556]
Hey,
I dunno when but i noticed recently lots of warnings coming out of the mcmmo plugin
here is the log:
http://pastebin.com/kNs59vkr

Spigot Ver: git-Spigot-2ec6f06-7722428 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)

**Comment by t00thpick1** [comment]
There appears to be an error of some sort,  find the error(Would be near the top of the log)  and post a new issue
