### ISSUE TITLE
When smelting a flux pickaxe, it clears all existing lore

### ISSUE THREAD

**Issue by JamieSinn** [mcMMO-Dev/mcMMO#2557]
Replicate:

Smelt a pickaxe with lore on it in a furnace.
Item that returns out is a  flux pickaxe, but with removed lore.

This is an issue for us, and as far as I can tell, I can't prevent this with any custom plugin

**Comment by JamieSinn** [comment]
@TfT-02 Update?

**Comment by JamieSinn** [comment]
@TfT-02 Update please?

**Comment by EvilOlaf** [comment]
😍
