### ISSUE TITLE
Aborting player profile

### ISSUE THREAD

**Issue by BlackBeltPanda** [mcMMO-Dev/mcMMO#2558]
Spigot version: git-Spigot-870264a-0a645a2 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)
MCMMO version: 1.5.03-SNAPSHOT-b46

Occasionally MCMMO will abort loading a player profile when they log in with the following error: "[mcMMO] Aborting profile loading recovery for DerpyMiner659 - player logged out"

The player, however, never logged out. =/

**Comment by t00thpick1** [comment]
The serer is telling us they logged out though, so not much we can do.
