### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by ElitStrikerzHD** [mcMMO-Dev/mcMMO#2559]
org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[spigot-1543.jar:git-Spigot-1543]
07.05 13:28:31 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
07.05 13:28:31 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
07.05 13:28:31 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
07.05 13:28:31 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
07.05 13:28:31 [Server] INFO at com.gmail.nossr50.listeners.PlayerListener.onPlayerQuit(PlayerListener.java:360) ~[?:?]
07.05 13:28:31 [Server] INFO at com.gmail.nossr50.util.player.UserManager.getPlayer(UserManager.java:94) ~[?:?]
07.05 13:28:31 [Server] INFO at java.util.Collections$UnmodifiableList.get(Collections.java:1309) ~[?:1.8.0_45]
07.05 13:28:31 [Server] INFO at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_45]
07.05 13:28:31 [Server] INFO at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_45]
07.05 13:28:31 [Server] INFO Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
07.05 13:28:31 [Server] INFO at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [spigot-1543.jar:git-Spigot-1543]
07.05 13:28:31 [Server] INFO at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:490) [spigot-1543.jar:git-Spigot-1543]
07.05 13:28:31 [Server] INFO at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:584) [spigot-1543.jar:git-Spigot-1543]
07.05 13:28:31 [Server] INFO at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:284) [spigot-1543.jar:git-Spigot-1543]
07.05 13:28:31 [Server] INFO at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:731) [spigot-1543.jar:git-Spigot-1543]
07.05 13:28:31 [Server] INFO at net.minecraft.server.v1_7_R3.ServerConnection.c(ServerConnection.java:75) [spigot-1543.jar:git-Spigot-1543]
07.05 13:28:31 [Server] INFO at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:733) [spigot-1543.jar:git-Spigot-1543]
07.05 13:28:31 [Server] INFO at net.minecraft.server.v1_7_R3.PlayerList.disconnect(PlayerList.java:321) [spigot-1543.jar:git-Spigot-1543]
07.05 13:28:31 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1543.jar:git-Spigot-1543]
07.05 13:28:31 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1543.jar:git-Spigot-1543]
07.05 13:28:31 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1543.jar:git-Spigot-1543]
07.05 13:28:31 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[spigot-1543.jar:git-Spigot-1543]
07.05 13:28:31 [Server] INFO org.bukkit.event.EventException
07.05 13:28:31 [Server] ERROR Could not pass event PlayerQuitEvent to mcMMO v1.5.00-b3547

**Comment by t00thpick1** [comment]
Should be fixed

**Comment by ElitStrikerzHD** [comment]
it is?
