### ISSUE TITLE
Party Chat issues

### ISSUE THREAD

**Issue by SullyTheUnusual** [mcMMO-Dev/mcMMO#2561]
Tried disabling party chat by setting perm "mcmmo.chat.partychat" to false, but doesn't work.  Tried "mcmmo.chat.*" also.

The reason I want it disabled, is because it bypasses Pwnfilter.  Is there any way to run party chat through Pwnfilter?

**Comment by Momshroom** [comment]
You can disable party chat by setting the party level it unlocks at very very high.  That's what we did when the perms didn't work to do so.

**Comment by SullyTheUnusual** [comment]
This is exactly what I ended up doing, thanks.  :)
