### ISSUE TITLE
Salvage is not its own skill?

### ISSUE THREAD

**Issue by Gameplayerx100** [mcMMO-Dev/mcMMO#2563]
I was wondering why salvage on my server is not its own skill? when I do /salvage it says "Unknown command. Type "/help" for help."
Pls help! :)

**Comment by TfT-02** [comment]
Salvage is a child skill. If its not on your server you're probably running an older version of mcMMO. See https://github.com/mcMMO-Dev/mcMMO/wiki/Skills for more info about the skills.
