### ISSUE TITLE
Duplicate how to solve?

### ISSUE THREAD

**Issue by alundra009** [mcMMO-Dev/mcMMO#2564]
17.05 23:20:18 [Server] ERROR VendorError: 1062 17.05 23:20:18 [Server] ERROR SQLState: 23000 17.05 23:20:18 [Server] ERROR SQLException: Duplicate entry 'Dj_air' for key 'user' 17.05 23:20:18 [Server] ERROR Location: sun.reflect.NativeConstructorAccessorImpl newInstance0 -2 17.05 23:20:02 [Server] ERROR VendorError: 1062 17.05 23:20:02 [Server] ERROR SQLState: 23000 17.05 23:20:02 [Server] ERROR SQLException: Duplicate entry 'Dj_air' for key 'user' 17.05 23:20:02 [Server] ERROR Location: sun.reflect.NativeConstructorAccessorImpl newInstance0 -2 17.05 23:20:00 [Server] INFO §cCocoaBeansForeva §4was denied access to command. 17.05 23:19:52 [Server] INFO Dj_air authenticated 17.05 23:19:52 [Server] ERROR VendorError: 1062 17.05 23:19:52 [Server] ERROR SQLState: 23000 17.05 23:19:52 [Server] ERROR SQLException: Duplicate entry 'Dj_air' for key 'user' 17.05 23:19:52 [Server] ERROR Location: sun.reflect.NativeConstructorAccessorImpl newInstance0 -2 17.05 23:19:47 [Server] ERROR VendorError: 1062 17.05 23:19:47 [Server] ERROR SQLState: 23000 17.05 23:19:47 [Server] ERROR SQLException: Duplicate entry 'Dj_air' for key 'user' 17.05 23:19:47 [Server] ERROR Location: sun.reflect.NativeConstructorAccessorImpl newInstance0 -2

**Comment by xion87** [comment]
Is fun that they don't care about it, they will no support offline mode, and is the only plugins with these issue

**Comment by EvilOlaf** [comment]
I would not support this report due to the lack of proper formatting ^^ No one likes to read this unformatted waste.

**Comment by t00thpick1** [comment]
Might work now,  might not,  either way I don't directly support offline mode sorry.
