### ISSUE TITLE
Duplication glitch

### ISSUE THREAD

**Issue by DiscoveriesMC** [mcMMO-Dev/mcMMO#2565]
It was reported to me that players can push/pull blast mined ore with pistons and keep blast mining the pushed/pulled ores to duplicate them. Tested this and can confirm that this is a bug.

Using v1.5.02.-b35

**Comment by EvilOlaf** [comment]
Get latest dev, has been fixed a while ago afaik.

**Comment by DiscoveriesMC** [comment]
Thanks!
