### ISSUE TITLE
McMMOPlayerNotFoundException

### ISSUE THREAD

**Issue by EarlyReflex** [mcMMO-Dev/mcMMO#2567]
I get this error with one of my players:

[13:29:02 ERROR]: [Autorank] Could not get user 'player' of McMMO. Report McMMOPlayerNotFoundException to mcmmo devs.

It's a reoccuring error that comes up regularly, for one particular player. Others don't seem to be affected. Everything in the database looks OK, can't find any errors.

mcMMO v1.5.02-SNAPSHOT-b27
spigot1.8.3

Edit: I just realized #2538 is the same issue, dating from a month ago, and didn't get any reply... Now I'm kinda scared.

**Comment by EarlyReflex** [comment]
Perhaps I came to the wrong place for support? Where is it I should go?

**Comment by t00thpick1** [comment]
I think it should be fixed now, if not,  please give me a full server log in which this happens

**Comment by EarlyReflex** [comment]
OK I'll get back if error shows up again. Thank you very much! :)
