### ISSUE TITLE
Mob_HealthBar

### ISSUE THREAD

**Issue by merlinshaw** [mcMMO-Dev/mcMMO#2568]
The mobs healthbar will not go away when I try to disable them in the config. 
Version of mcMMO: mcMMO v1.5.03-SNAPSHOT-b46
Server Version: This server is running CraftBukkit version git-Spigot-870264a-0a645a2 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)

Mob_Healthbar:
    # Display_Type: Default display for mob health bars - HEARTS, BAR, or DISABLED
    # Display_Time: Amount of time (in seconds) to display. To display permanently, set to -1
    Display_Type: DISABLED
    Display_Time: 1

**Comment by zRiaz** [comment]
got the same issue

**Comment by TfT-02** [comment]
Changing those settings only changes the default value for new players. To disable the health bars, you need to use permissions. For more information check the wiki here

https://github.com/mcMMO-Dev/mcMMO/wiki/Frequently-asked-questions#how-do-the-new-mob-healthbars-work
