### ISSUE TITLE
WorldGuard?

### ISSUE THREAD

**Issue by ISanderI** [mcMMO-Dev/mcMMO#2569]
Hey, could you add better implementation for worldguard support for the skills of Axes, Swords, Archery etc.
If player A is outside the worldguard region
Player B is inside it
And player A hits the other player from outside the worldguarded region (with axe,sword,bow) player B will start to bleed, get dazed, armor will break etc.

Becoming a big problem people with axes just standing on the edge hitting afk people and just shredding their armor.

**Comment by ISanderI** [comment]
@t00thpick1

**Comment by t00thpick1** [comment]
Not much more we can do aside from our fake events,  you can write a compatibility plugin that checks for worldguard regions and cancels our ability activations

**Comment by ISanderI** [comment]
Dam, wish I knew coding. Guess ill have to pay a dev to make something for me then 3:

**Comment by t00thpick1** [comment]
Actually I think we have a mcmmo-Worldguard plugin that may or may not be up to date, if not you can find someone to update it rather than write something from scratch
