### ISSUE TITLE
SQLite?

### ISSUE THREAD

**Issue by ISanderI** [mcMMO-Dev/mcMMO#2570]
Instead of using a flatfile, could you add implemention to use a SQLite file instead?
Thanks :]

**Comment by nightmarex** [comment]
There already is...
http://mcmmo.wikia.com/wiki/Configuration

**Comment by t00thpick1** [comment]
Not in my current plans, sorry.  but feel free to PR it if you can do it yourself

**Comment by ISanderI** [comment]
*cries*

**Comment by ISanderI** [comment]
If i pay a dev to PR it, will you for sure add it to the plugin?

**Comment by t00thpick1** [comment]
If its well done,  I can't just pull any code in,  as if its super inefficient/ error prone,  that would be bad for the project.

**Comment by ISanderI** [comment]
Ok, I see that one. Just making sure that if I pay someone to make it and it works well that it would be added so I wouldnt waste time or money on it.

**Comment by t00thpick1** [comment]
Although as a note, we support CustomDatabase implementations from other plugins, so even if we didn't accept it you could make it work in its own plugin that hooks us.

**Comment by t00thpick1** [comment]
If you have them implement this interface:  https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/database/DatabaseManager.java

And then call this method: https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/database/DatabaseManagerFactory.java#L45


It would work as a standalone addon plugin
