### ISSUE TITLE
Remove a message through locale

### ISSUE THREAD

**Issue by nightmarex** [mcMMO-Dev/mcMMO#2571]
Hello,
Is it possible to remove a message through the locale?

I've tried removing the entry but that just sent a blank message.
Im trying to remove the Skill cooldown message if that matters.

Thank you,
-Robert

**Comment by nightmarex** [comment]
Bump.

Tried removing the whole line, nope.

**Comment by EvilOlaf** [comment]
Due to the fact that it sends a blank line my guess is that it is not possible this way.

**Comment by t00thpick1** [comment]
Nope sorry :(
