### ISSUE TITLE
Player data deleted

### ISSUE THREAD

**Issue by NoChanceSD** [mcMMO-Dev/mcMMO#2572]
https://github.com/mcMMO-Dev/mcMMO/issues/2448
Hi, this is still a issue for me, is it because of offline mode?
I try to update to latest dev build and all player data just gets deleted.. so i'm still using the mcmmo version from bukkit.
Please take a look on this issue.

**Comment by t00thpick1** [comment]
Should be fixed,  might be because of offline mode if not.  If offline mode is the cause,  sorry you are SoL,

**Comment by NoChanceSD** [comment]
Yes, it probably is because of offline mode, doesn't mean it isn't an easy fix. 
Thanks anyway, i will fix it myself. I would make a PR but you don't seem interested.

**Comment by NoChanceSD** [comment]
Actually, nevermind one of the latest commits seems to have fixed it.
