### ISSUE TITLE
Block syncing issue between server/client when using Super Breaker

### ISSUE THREAD

**Issue by SullyTheUnusual** [mcMMO-Dev/mcMMO#2574]
After using Super Breaker, some broken blocks are "still there" server side.  One of my players found a way to avoid it by not breaking blocks at the end of the Super Breaker cycle (e.g. if your Super Breaker lasts 7 seconds, stop mining after 6).

**Comment by PsychoNavigator** [comment]
I experience this constantly, but chalk it up to having a very high level of latency as my server is halfway around the world from me.

Players local to my server don't have this issue. I can't say for sure but there's really no way of solving this issue, as it can happen in a vanilla environment as well.

**Comment by SullyTheUnusual** [comment]
Since Minecraft 1.8 came out, the "ghost blocks" due to latency has not been an issue.

I started a local copy of my server, and it's still an issue.  That tells me it's not just a latency issue.

**Comment by PsychoNavigator** [comment]
It'd be nice if MCMMO could hook into something like Title Manager and do a count down for the last 3-5 seconds of a superbreak. Then players could figure when is best for them to stop to prevent them.

**Comment by EvilOlaf** [comment]
There is an option to force chunk update after finishing superbreaker but as suggested there it is not suitable for larger servers, because it might cause performance issues. For smaller servers this should work fine.
Check your config for it.

**Comment by PsychoNavigator** [comment]
Yeah we're teeny-tiny. We can handle it. Thanks for the heads up!
