### ISSUE TITLE
File Wipes when brining over past user level data

### ISSUE THREAD

**Issue by Mike7493** [mcMMO-Dev/mcMMO#2575]
When bringing over the flatfile with all of the players data into the new 1.8 plugin with UUID support, it seems to work fine at first. However, after a little while, it matches up the UUIDs with the players that are currently online, but then deletes all of the other player data from the flatfile, or at least the ones that check their stats.

This currently makes the plugin unusable to us.

We tried on 1.8.3 and on the latest 1.8.6. We also tired the latest dev builds and the latest public release from back in march.

**Comment by Mike7493** [comment]
It seems that the flatfile conversion issue is still not fixed. We can't update our server until this issue is fixed so any feedback would be appreciated.

**Comment by t00thpick1** [comment]
It should be fixed now,  sorry for the delayed response
