### ISSUE TITLE
Super Breaker and other abilities overwrite the 3rd enchantment in tools.

### ISSUE THREAD

**Issue by ronangamero** [mcMMO-Dev/mcMMO#2578]
So we had MCMMO for a while in our server play.envyblock.net and it worked fine. After a while, I don't know if MCMMO itself was updated or not during this, we couldn't use superbreaker or other ability like that, because the mcmmo ability tag wouldn't fade after the ability time was ended. For now the plugin is disabled in the server, but there is a lot of players asking for it, it would be good to have it back.

**Comment by EvilOlaf** [comment]
More information about Bukkit/Spigot version, mcMMO version log entries might be interesting.

**Comment by JANEXLEBJAKOT** [comment]
same problem 
spigot 1.8.4
last mcmmo
nothing interesting in logs.
