### ISSUE TITLE
unable to get mcmmo to work

### ISSUE THREAD

**Issue by eforme123** [mcMMO-Dev/mcMMO#2579]
I have followed all steps and it still isn't working is there any specific version numbers i have to worry about or should it pick the right one automatically when in the plugins tab of bukkit please help this has been a week long effort and i still cant fix it.
mc version latest 1.8.6
bukkit version 1.8.0.541
mcmmo version 1.5.00-b3547

**Comment by t00thpick1** [comment]
Without errors or descriptions of the issues, I can do nothing.
