### ISSUE TITLE
Acrobatics Glich

### ISSUE THREAD

**Issue by GamerGamerFTW** [mcMMO-Dev/mcMMO#2581]
When i fall from high places (More than 40-Endless amount of blocks) i don't get acrobatics xp levels but my friend does and my other friends do and this is not first time when that happens to me and others... Can anyone say why is this happening?

**Comment by EvilOlaf** [comment]
Bad luck I guess...

**Comment by GamerGamerFTW** [comment]
But at other servers it works.... Or it's a Minecraft glich or something?

**Comment by TfT-02** [comment]
Are you falling at the same spot over and over? Are you in god-mode?

**Comment by PgBiel** [comment]
Hmmm... Yeah, @TfT-02 must be right. If you're falling at the same spot over and over, then that might be it.
