### ISSUE TITLE
Call of the Wild Infinite Duration Option

### ISSUE THREAD

**Issue by Trainerredstone7** [mcMMO-Dev/mcMMO#2590]
I noticed in the mcMMO config that it's not possible to make the summon duration of Call of the Wild infinite. Setting it to 0 just disables the plugin. This option would be nice for servers where most wild wolves are already tamed.

**Comment by TfT-02** [comment]
Setting it to 0 should work for disabling the feature. Can you post your config.yml file? Can you post a log of when it disables the plugin?

**Comment by EvilOlaf** [comment]
From the context I would guess that he means that 0 would disable the taming feature at all instead of making tams infinite.

**Comment by Trainerredstone7** [comment]
Sorry for the false alarm - it turns out there was something else wrong with my config that was disabling the plugin. Setting the value to 0 does work.

**Comment by TfT-02** [comment]
Great! Glad to hear.
