### ISSUE TITLE
Player Join Lag (PlayerProfileLoadingTask$ApplySuccessfulProfile(Single))

### ISSUE THREAD

**Issue by ViscousSummer88** [mcMMO-Dev/mcMMO#2591]
Hello, I have been noticing player joining lag. After running timings on the server for period of time in two different instances I have been noticing the following. When a player joins the server a *small* amount of lag is noticed.

Timings:-
1. Ran for 810919 ticks - http://imgur.com/tCqO7Xo
2. Ran for 16887 ticks - http://imgur.com/U2xDJJU

Any support on this issue would be greatly appreciated.

**Comment by t00thpick1** [comment]
I did as much as I could,  but there is only so much we can do when we have to load player data
