### ISSUE TITLE
Herbalism skill not raising when hit from minecart

### ISSUE THREAD

**Issue by EvilOlaf** [mcMMO-Dev/mcMMO#2592]
I set up a line of sugar cane and put rails next to it. At "drive-by" harvesting the herbalism experience does not raise. When harvesting without sitting in a vehicle it works fine.
mcMMO 1.5.03 @ Spigot 1.8.3

**Comment by TfT-02** [comment]
This is not a bug, its a feature. Toggle to enable/disable is located here https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/config.yml#L331

**Comment by EvilOlaf** [comment]
Oops, never thought that could be a feature, sorry.
Wondering how AFK herbalism farming should work...
