### ISSUE TITLE
McMMO Skill Glitch Major

### ISSUE THREAD

**Issue by Schiehsl3** [mcMMO-Dev/mcMMO#2593]
For some reason when I have a person set to the group manager default permission of Owner it gives 3 times as much XP for everything and I added no permissions to make  this happen.

Another major issue is levels keep randomly going on most notable is the mining and repair skill. Players might be doing something completely else and keep getting leveled up. No errors are showing and nothing was changed from the original McMMO config.

**Comment by EvilOlaf** [comment]
And you are sure that this person or group does not have any perks as permission?

**Comment by TfT-02** [comment]
1. Is a permissions issue. You must've given the XP boost perks https://github.com/mcMMO-Dev/mcMMO/wiki/Permissions#using-permissions-to-give-certain-groups-perks

2. Check if those players are in a party with XP sharing enabled. That probably explains the "random" leveling.

**Comment by Schiehsl3** [comment]
No they are not in any party and no I have not touched the permissions as I said everything is default settings. For some odd reason only "Owner" from group manager which is a default rank is effected. Admin, Mod, Builder and Default are not.

**Comment by EvilOlaf** [comment]
And the owner group does not have `* ` permission for example?

**Comment by t00thpick1** [comment]
Someway or another you have the bonus exp permission nodes, either OP or * or some method,  You need to find that and negate it.
