### ISSUE TITLE
429 causes users to be skipped in UUID upgrade

### ISSUE THREAD

**Issue by ejona86** [mcMMO-Dev/mcMMO#2595]
While trying to diagnose UUID upgrade issues in 1.5.02, I discovered that UUIDUpdateAsyncTask can [skip users](https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/runnables/database/UUIDUpdateAsyncTask.java#L79). If an error happens fetching UUIDs, and the error message contains 429, then a sleep occurs and the while loop continues. However, size was modified immediately after calling `subList()`, so the size is 1) guaranteed to be wrong and 2) is == 0 if userNames.size() <= MAX_LOOKUP. If (2), the loop will exit and the users of that batch will not have their UUIDs assigned.

The symptom I had was UUID lookup appearing to happen:
```
[22:10:51] [Craft Scheduler Thread - 0/INFO]: [mcMMO] Starting to check and update UUIDs, total amount of users: 16
[22:10:51] [Craft Scheduler Thread - 0/INFO]: [mcMMO] UUID upgrade completed!
```

Notice that there is no "_X_ entries written while saving UUID batch" log entry that `saveUserUUIDs()` would have written from its finally block.

I'm not convinced I'm hitting this precise issue, as I wouldn't expect to reliably get 429 (I've tested many times) for 16 users. When combined with #2594, this bug will cause data loss.

**Comment by t00thpick1** [comment]
Fixed
