### ISSUE TITLE
juul's

### ISSUE THREAD

**Issue by juulspartacus** [mcMMO-Dev/mcMMO#2597]
juul's is the boss plis event od diamonds D:

**Comment by juulspartacus** [comment]
![kris12--575x323](https://cloud.githubusercontent.com/assets/12942345/8217641/f4c5db7a-153e-11e5-902b-c4484b8727e0.jpg)

**Comment by juulspartacus** [comment]
yeaaa

**Comment by zStreezy** [comment]
sssssssssssssssssssssssssssss
