### ISSUE TITLE
Disabling Xp Gain?

### ISSUE THREAD

**Issue by lavabird** [mcMMO-Dev/mcMMO#2600]
I want to make it so that players cannot gain xp from using their skills, but I cannot figure out how. I tried setting the multiplier to 0, but it causes the plugin to not work. Also, when I set each way of leveling up to 0, the same thing happens. I need to disable xp, for it acts as a core function on my server.

**Comment by zStreezy** [comment]
sss

**Comment by t00thpick1** [comment]
Hmmm  your best bet is just cancelling the McMMOPlayerXpGainEvent
