### ISSUE TITLE
Unable to run mcMMO

### ISSUE THREAD

**Issue by pchard** [mcMMO-Dev/mcMMO#2602]
Running on Cauldron and Forge. 1.7.10

23.06 12:44:38 [Server] INFO [12:44:38 INFO]: [mcMMO] Disabling mcMMO v1.5.02-b35
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at java.lang.Thread.run(Thread.java:745)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1325)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:104)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:286)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:147)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:433)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at com.gmail.nossr50.config.skills.repair.RepairConfigManager.<init>(RepairConfigManager.java:34)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at com.gmail.nossr50.config.skills.repair.RepairConfig.<init>(RepairConfig.java:24)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at com.gmail.nossr50.config.skills.repair.RepairConfig.loadKeys(RepairConfig.java:139)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at com.gmail.nossr50.util.skills.SkillUtils.getRepairAndSalvageQuantities(SkillUtils.java:279)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.getRecipesFor(CraftServer.java:1120)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.inventory.RecipeIterator.next(RecipeIterator.java:10)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.inventory.RecipeIterator.next(RecipeIterator.java:32)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at net.minecraft.item.crafting.ShapedRecipes.toBukkitRecipe(ShapedRecipes.java:13)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at net.minecraft.item.crafting.ShapedRecipes.toBukkitRecipe(ShapedRecipes.java:34)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.inventory.CraftShapedRecipe.<init>(CraftShapedRecipe.java:19)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.inventory.CraftShapedRecipe.<init>(CraftShapedRecipe.java:15)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at org.bukkit.inventory.ShapedRecipe.<init>(ShapedRecipe.java:31)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:130)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.inventory.CraftItemStack.getDurability(CraftItemStack.java:170)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: 	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:238)
23.06 12:44:38 [Server] INFO [12:44:38 WARN]: java.lang.NullPointerException
23.06 12:44:38 [Server] INFO [12:44:38 ERROR]: [mcMMO] There was an error while enabling mcMMO!
23.06 12:44:37 [Server] INFO [12:44:37 INFO]: [mcMMO] Enabling mcMMO v1.5.02-b35

**Comment by PgBiel** [comment]
Hmm.... Seems to be something about the recipes and the Repair. I think that it's something related to Forge, but I can't think in anything that could help.

**Comment by pchard** [comment]
So in other words, I should get a refund on my purchase of this plugin?

**Comment by t00thpick1** [comment]
No you should go talk to cauldron devs and see why this is happening,   The plugin does not have this issue when used on regular spigot.  In the past cauldron devs have been pretty quick on these types of things, so it should be fine.
