### ISSUE TITLE
McMMO Fishing Ice Breaker Ability can break any kind of sign ontop of the ice - LWC, Ess, etc.

### ISSUE THREAD

**Issue by JamieSinn** [mcMMO-Dev/mcMMO#2603]
Can break any sign put directly on the ice, just like breaking the block beneath the sign.

This should probably check if it can build/destroy the block above, not just the blocks that will be cleared.

Alternatively, possible config option to disable this would be nice.

Image.

![Imgur](http://i.imgur.com/FYdt4IP.jpg)

**Comment by PgBiel** [comment]
I agree, but I never see someone put signs above ice...

**Comment by JamieSinn** [comment]
Sadly actually happens a lot with ECC

**Comment by JamieSinn** [comment]
Nothing really can be done about this. Has to be done on the essentials side, or this cancels it.
