### ISSUE TITLE
Auto Smelting Not Working

### ISSUE THREAD

**Issue by EnderSandman69** [mcMMO-Dev/mcMMO#2609]
I bought the premium version of McMMO and iron ores never auto smelt anymore even with a mining level over 700.

**Comment by TfT-02** [comment]
The Flux Mining ability from Smelting has been changed. You need a special pickaxe before you can use the ability, see the wiki for more information. 
https://github.com/mcMMO-Dev/mcMMO/wiki/Smelting#flux-mining
