### ISSUE TITLE
Custom colors

### ISSUE THREAD

**Issue by Colemac2233** [mcMMO-Dev/mcMMO#2610]
Hi, I have a server with a nice blue themed chat system, but the default mcmmo colors are really ugly and I have been trying to change all the colors on chat for awhile and got no progress, there are no tutorials on how to do it, but I did find this: https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/locale/locale_en_US.properties
and I changed all the colors I wanted, but I don't know where to put it or what to call it or what type of file it needs to be but if you could give me a link on a tutorial or just give me instructions that would be fantastic ! please help

**Comment by EvilOlaf** [comment]
See other comment. There are actually no editable language files available without editing the source code.

**Comment by Colemac2233** [comment]
Well how do I do that ?

**Comment by Colemac2233** [comment]
How do I build it into a jar
and like I said google has no tutorials

**Comment by TfT-02** [comment]
Rename mcMMO.jar to .zip copy your edited locale file, rezip it and rename.

**Comment by Colemac2233** [comment]
What do you mean ? rezip it and rename... what do I rename? and what do I call it ? How do I rezip a text document ? I am so confused... so far I renamed the mcMMO.jar to mcMMO.zip. how what do I do ?

**Comment by Colemac2233** [comment]
I renamed the jar to zip now mcmmo does not even work !

**Comment by Colemac2233** [comment]
Can you please give me very specific instructions please, I am really not the smartest with doing this stuff. if you could that would be great

**Comment by Kerrus** [comment]
He doesn't mean 'renaming it to .zip will magically fix everything'. He means 'make it into a zip file, extract  the locale file, edit it, re-add it to the zip file, then rename the zip file back to .jar.

**Comment by Colemac2233** [comment]
Thank you ! but what is the locale file ? and where is it in the zip file?

**Comment by Colemac2233** [comment]
And make what into a zip file

**Comment by Colemac2233** [comment]
There is no local file in mcmmo jar

**Comment by Colemac2233** [comment]
What do I rename my edited colour message thing

**Comment by Colemac2233** [comment]
ok this is what I did, from what you guys told me I turned mcmmo into zip, than I playced the custom notpad message thingy into the mcmmo.zip (I put it right beside the config) Than I turned it back to jar and BOOM it does not work... again....

**Comment by t00thpick1** [comment]
Get a fresh jar,  unzip it   look inside the directory /locale  find whichever base one you want to edit,  edit it,  rezip the jar
