### ISSUE TITLE
kill/death tracker?

### ISSUE THREAD

**Issue by PsychoNavigator** [mcMMO-Dev/mcMMO#2611]
I have players asking for a death counter for my server, catch is that the scoreboard won't work when MCMMO already has a scoreboard in place. 

Is there any way to set up tracking kills and deaths in the sidebar?

**Comment by t00thpick1** [comment]
Disable our scoreboards in the config,  this is a minecraft limitation unfortunately.

**Comment by PsychoNavigator** [comment]
What I was hoping is that you could be able to add the feature into the MCMMO scoreboard actually.
