### ISSUE TITLE
PLEASE! Disable MCMMO Repair of items which have a lore

### ISSUE THREAD

**Issue by bloggy** [mcMMO-Dev/mcMMO#2613]
We are running a popular RPG minecraft server and do not want people to be able to repair special gear like bows. All these items have a lore. So can you please add a setting to the config to disable repairing of items if its lore contains a specific word???

Thanks a lot!

**Comment by ISanderI** [comment]
Agree +1 (config option to enable/disable would be nice too!)

**Comment by t00thpick1** [comment]
Using our API you can do this via a third party plugin
