### ISSUE TITLE
Tree feller is not working

### ISSUE THREAD

**Issue by Elioz** [mcMMO-Dev/mcMMO#2616]
Hello, 
i'm using latest version of mcmmo and spigot 1.8.7 and treefeller not working, working only for ops
I added permission and still same.

Thank you

**Comment by EvilOlaf** [comment]
Practically there is no need to configure any permissions for mcmmo at all.
Maybe you tested in spawn-protection radius area or other kind a protected place?

**Comment by Elioz** [comment]
Nope, I tested it in wildzone, still nothing, working only for ops, not for players.

**Comment by PgBiel** [comment]
Did you tried <code>mcmmo.ability.woodcutting.treefeller</code>?

**Comment by Elioz** [comment]
no way, I made it myself, all regions
and yes I tried the permission also
