### ISSUE TITLE
Command Blocks and mcMMO

### ISSUE THREAD

**Issue by Simon8198** [mcMMO-Dev/mcMMO#2617]
Is there a way to get Command blocks to check if a person has a certain skill level and then issue a command based if that is true or not.

I would like to do this as the server I am working on needs to rank up people based on how high their mcMMO skill level is and I don't want to have a ton of mod Micromanaging it.

Thank You For Reading

**Comment by t00thpick1** [comment]
Not built in, but using our API you could likely write a plugin to do that for you.

**Comment by Simon8198** [comment]
If you could I would be very grateful
