### ISSUE TITLE
Some Things.

### ISSUE THREAD

**Issue by DutchUser** [mcMMO-Dev/mcMMO#2621]
Hello. I have some thing that i want to ask.

1, When i use the plugin before OP's still got more points then set on the config file.
Is there an option to disable this? That players with OP not get more points?

2, Wil work the last version on 1.8? (and higher)

3, Have the last version UUID support?

4, Are you still updating it for 1.8 and higher? (1.9 2.0 etc,)

**Comment by EvilOlaf** [comment]
1. As OPs always have all permissions they also receive points from mcMMO perks. Disable them by using a permissions plugin (and deop yourself....)
2. Yes.
3. Not absolutely sure, but I think so.
4. Can't answer

**Comment by DutchUser** [comment]
1, Is there not an option to disable thse perks %100 for all users and ranks.
And i use an permission plugin. Named PermissionEX

**Comment by t00thpick1** [comment]
2-3-4: Yes   1: EvilOlaf answered this
