### ISSUE TITLE
Premium and open source?

### ISSUE THREAD

**Issue by kangarko** [mcMMO-Dev/mcMMO#2622]
Sorry for being silly, but I just want to make sure that if this is the latest code that matches the premium plugin? Is it possible to sell a premium plugin that has its code publicly available at the same time? 
~just curious

**Comment by EvilOlaf** [comment]
My two cents:

The source might be more up-to-date as the dev build will be built from it and need testing before releasing it to SpigotMC. So player get more stable versions.

Surely plugins can be both premium and open source at the same time.

**Comment by kangarko** [comment]
>Surely plugins can be both premium and open source at the same time.

But that's great! I really like it and hope it will stay like this. I though that if it will stay both open source and premium noone is going to buy it

**Comment by t00thpick1** [comment]
Nope I keep it open and just occasionally push to the premium page,  Its really just a donation rather than a purchase.

**Comment by kangarko** [comment]
All right, before I though it was premium-only some time and recently became open source again.

**Comment by t00thpick1** [comment]
People don't realize that its both open source, and that we even have a link to free builds on the Premium page.   The Premium is just a way of telling me that you don't hate me and want me to stop working on this ever again

**Comment by EvilOlaf** [comment]
It is always sad when people stop working on plugins which are basically awesome because often other people don't really appreciate the hard work and many (MANY!) hours it takes to make it that way...

**Comment by kangarko** [comment]
I understand. Sorry again I missed the link. I am thinking over to converting my most popular plugin, since I received only about two donations of only a few bucks over past 2.5 years, and you expressed it exactly in the FAQ.

**Comment by EvilOlaf** [comment]
Well in one point I can understand the lack of donations. The average age of Minecraft players as well as owners is quite low so many still going to school or similar and just have some pocket money to spend.
And as written above they have no clue that it isn't that easy to write a very complex plugin.
So to make money coding plugins for CB is the wrong way ^^ (Of course it isn't about the money)
