### ISSUE TITLE
Mctop not working (spigot 1.8.7) (mcmmo v1.5.03-SNAPSHOT-b46)

### ISSUE THREAD

**Issue by Enjo999** [mcMMO-Dev/mcMMO#2624]
because
19.07 05:32:26 [Server] INFO ... 3 more
19.07 05:32:26 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
19.07 05:32:26 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
19.07 05:32:26 [Server] INFO at com.gmail.nossr50.runnables.commands.MctopCommandAsyncTask.run(MctopCommandAsyncTask.java:38)
19.07 05:32:26 [Server] INFO at com.gmail.nossr50.database.SQLDatabaseManager.readLeaderboard(SQLDatabaseManager.java:408)
19.07 05:32:26 [Server] INFO at java.lang.Integer.valueOf(Integer.java:582)
19.07 05:32:26 [Server] INFO at java.lang.Integer.parseInt(Integer.java:495)
19.07 05:32:26 [Server] INFO at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
19.07 05:32:26 [Server] INFO Caused by: java.lang.NumberFormatException: For input string: "12999999987"
19.07 05:32:26 [Server] INFO at java.lang.Thread.run(Thread.java:745)
19.07 05:32:26 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
19.07 05:32:26 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
19.07 05:32:26 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
19.07 05:32:26 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin mcMMO v1.5.03-SNAPSHOT-b46 generated an exception while executing task 283264

**Comment by t00thpick1** [comment]
You have a skill WAYYY too high in the database..  someones playing with their skills in ways they shouldn't
