### ISSUE TITLE
Losing pickaxe texture when activating super breaker

### ISSUE THREAD

**Issue by SullyTheUnusual** [mcMMO-Dev/mcMMO#2628]
The texture for my pickaxe reverts to the red and black checkered box when activating super breaker.  It is an iron pickaxe with the "Unbreakable" attribute and Efficiency VI and Silk Touch I enchantments.

**Comment by SullyTheUnusual** [comment]
Did some testing, and it looks like it's being triggered when the pick has the "Unbreakable" attribute.

**Comment by SullyTheUnusual** [comment]
Looks like it's happening when using Tree Feller with axes that have the "Unbreakable" attribute, also.

**Comment by astemus** [comment]
This problem is caused by modifying the damage value on the tool when it's flagged as unbreakable.  Minecraft sets the damage value of the item instead of causing durability loss when it's unbreakable.

**Comment by SullyTheUnusual** [comment]
So is this something that can be fixed?  Or should I report it on the MC bug tracker?

**Comment by astemus** [comment]
It's an mcMMO bug.  The plugin doesn't check to see if the tool has the unbreakable flag before applying durability damage.  I tried to hack something in myself, but the unbreakable flag seems to be rather ornery with craftbukkit.
