### ISSUE TITLE
Player-Error

### ISSUE THREAD

**Issue by SirHF** [mcMMO-Dev/mcMMO#2629]
When a player joins a server, and he or she accidentally got the same name as a previous player on the server, mcMMO is not able to load the new player profile, but does also not transform the skills and stats from the "old" player. The "new" player is then not able to use any mcMMO-related commands other then /mcmmo and /mcmmo help (Error message: Player profile is not loaded yet.) With every reconnect the "new" player will get a message: 
mcMMO still cannot load your data. You may want to contact the server owner.
You can still play on the server, but you will have no mcMMO levels and any XP you get will not be saved.
The server owner tried to use /mcremove {playername}, but there was always the error message "An internal error occurred while attempting to perform this command." while the player was online and "This command does not work for offline players." while the player wasn´t on the server.

EDIT: The server is running the version 1.5.02-SNAPSHOT-b27

**Comment by EvilOlaf** [comment]
Did you have a look at your console? In most cases `An internal error occurred while attempting to perform this command.` means that there is more debug output in your console. 
You may want to post this here or put it to pastebin.

**Comment by SirHF** [comment]
This is printed on the console, when /mcremove {playername} is used:
21:34:11 CONSOLE: ERROR]: null
21:34:11 CONSOLE: exception executing command 'mcremove' in plugin mcMMO v1.5.02-SNAPSHOT-b27
21:34:11 CONSOLE: java.lang.IndexOutOfBoundsException: Index: 0

When the "new" player joins, this appears on the console:

21:35:10 CONSOLE: WARN]: java.sql.SQLException: Unable to run insert stmt on object com.Acrobot.ChestShop.Database.Account@370ed942: INSERT INTO `accounts` (`name` ,`shortName` ,`uuid` ) VALUES (?,?,?)
21:35:10 CONSOLE: WARN]: at com.Acrobot.ChestShop.ORMlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22)
21:35:10 CONSOLE: WARN]: at com.Acrobot.ChestShop.ORMlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135)
21:35:10 CONSOLE: WARN]: at com.Acrobot.ChestShop.ORMlite.stmt.StatementExecutor.create(StatementExecutor.java:450)
21:35:10 CONSOLE: WARN]: at com.Acrobot.ChestShop.ORMlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310)
21:35:10 CONSOLE: WARN]: at com.Acrobot.ChestShop.UUIDs.NameManager$1.run(NameManager.java:157)
21:35:10 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
21:35:10 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
21:35:10 C
21:36:02 CONSOLE: ERROR]: [mcMMO] VendorError: 1062
21:36:02 CONSOLE: ERROR]: [mcMMO] Giving up on attempting to load the PlayerProfile for {playername}
21:36:02 A: mcMMO was unable to load the player data for {playername}. Please inspect your database setup.

The following message is appearing almost all the time on the console:
21:44:04 CONSOLE: ERROR]: [mcMMO] Location: sun.reflect.GeneratedConstructorAccessor298 newInstance -1
21:44:04 CONSOLE: ERROR]: [mcMMO] SQLException: Duplicate entry '{playername}' for key 'user'
21:44:04 CONSOLE: ERROR]: [mcMMO] SQLState: 23000
21:44:05 CONSOLE: ERROR]: [mcMMO] VendorError: 1062

**Comment by t00thpick1** [comment]
This issue cannot occur in recent versions of mcMMO.
