### ISSUE TITLE
Error during UUID Conversion

### ISSUE THREAD

**Issue by astr1al** [mcMMO-Dev/mcMMO#2630]
I am trying to update to McMMO build #60 with a SQL database. I have tried a bunch of different settings in hidden.yml but still get "Unable to fetch UUIDs!"

I saw some older tickets that marked this as fixed, but I still can't seem to get this to work. I've been avoiding this issue for a while by not updating. But after a year and a half, it's time to catch up. 

Here's the error if it helps http://pastebin.com/1cbwC6KD

Running on Spigot 1.8.3

**Comment by t00thpick1** [comment]
Seems like an issue with your connection with Mojang servers.  This code has worked fine

**Comment by astr1al** [comment]
How many players did you covert? I can only seem to convert 6,000 or so of the 10,000 players in the database before getting the error. I've tried purging old players to try and thin out the database, but there still appears to be an issue with purging. If I set it to purge players not logged on more than x months ago it will only purge players that logged in during the most recent startup.
