### ISSUE TITLE
McMMO Acrobatics Help

### ISSUE THREAD

**Issue by trollkarl** [mcMMO-Dev/mcMMO#2631]
When taking fall damage on any server with McMMO you get acrobatics XP. Well on all the server that I can find you only do get XP the first or second fall. On the Wiki it says that you have to wait about 5 seconds before jumping again to get XP but even after waiting 5 seconds you still don't get any XP at all. I've tried to relogg multiple times and wait 10 minutes+ but still son't get any XP what so ever. Any explanation or help? PS: I have feather falling 4 on my boots so it might think I died and therefore don't give me the XP, in that case it is a bug and should be fixed in next patch.

**Comment by EvilOlaf** [comment]
Try a different spot or try without your boots. There should be no need to fall hard to death to get XP for.
