### ISSUE TITLE
McTOP Not working

### ISSUE THREAD

**Issue by DarkKnight-FMC** [mcMMO-Dev/mcMMO#2633]
I'm having a problem with the latest mcMMO built: 1.5.04-SNAPSHOT
I get the following error when anyone issues the following command: /mctop

25.07 22:09:32 [Server] INFO ... 3 more
25.07 22:09:32 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
25.07 22:09:32 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
25.07 22:09:32 [Server] INFO at com.gmail.nossr50.runnables.commands.MctopCommandAsyncTask.run(MctopCommandAsyncTask.java:38)
25.07 22:09:32 [Server] INFO at com.gmail.nossr50.database.SQLDatabaseManager.readLeaderboard(SQLDatabaseManager.java:352)
25.07 22:09:32 [Server] INFO at java.lang.Integer.valueOf(Integer.java:582)
25.07 22:09:32 [Server] INFO at java.lang.Integer.parseInt(Integer.java:495)
25.07 22:09:32 [Server] INFO at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
25.07 22:09:32 [Server] INFO Caused by: java.lang.NumberFormatException: For input string: "12999999987"
25.07 22:09:32 [Server] INFO at java.lang.Thread.run(Thread.java:745)
25.07 22:09:32 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
25.07 22:09:32 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
25.07 22:09:32 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
25.07 22:09:32 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin mcMMO v1.5.04-SNAPSHOT-b64 generated an exception while executing task 273
25.07 22:09:32 [Server] WARN Exception in thread "Craft Scheduler Thread - 40"

**Comment by t00thpick1** [comment]
SOmeone gave somebody a super high skill level "12999999987"  this is higher than mcMMO supports,  you need to manually fix that.  And then instruct your mods/admins not to play around with skill levels they shouldn't

**Comment by DarkKnight-FMC** [comment]
I downloaded all my tables from my MysQL database and searched it for something like 129999999 but it came up clean?

**Comment by t00thpick1** [comment]
Its in there, otehrwise that error would not occur

**Comment by DarkKnight-FMC** [comment]
http://prntscr.com/7xjjjh

I wouldn't be here asking you if I had of found it ._.

**Comment by t00thpick1** [comment]
Actually, it could also be someone having total levels exceeding that number,  which is still way higher than should be possible with normal play.  so look for really high numbers in the DB  

SELECT user, mcmmo_skills.* FROM mcmmo_users JOIN mcmmo_skills ON (user_id = id) ORDER BY taming+mining+woodcutting+repair+unarmed+herbalism+excavation+archery+swords+axes+acrobatics+fishing+alchemy LIMIT 10

This query should give you it

**Comment by DarkKnight-FMC** [comment]
http://prntscr.com/82uy00

Didn't work

**Comment by willotree** [comment]
My solution was (I was using bukkit Stream) Removing it and all worked fine! :D Maybe try removing some plugins that are not mcMMO but are related.
