### ISSUE TITLE
MCMMO not working

### ISSUE THREAD

**Issue by TinySenTendo** [mcMMO-Dev/mcMMO#2634]
McMMO just isn't working at all and I don't know what to do. I have the latest (stable) 1.8 McMMO and I have Spigot 1.8.7 so I just don't know why it doesn't work I looked through the config and through everything and nothing was there, so if I do (ex) /mining it tells me "an internal error has occurred while attempting to do this command" please help

**Comment by t00thpick1** [comment]
If you do not actually post the console error, I can literally do absolutely nothing for you
