### ISSUE TITLE
IDEA: Enchanting skill

### ISSUE THREAD

**Issue by Articdive** [mcMMO-Dev/mcMMO#2635]
I thought of this when i was playing some Minecraft (on an mcmmo server)
There should be an enchanting skill which when you upgrade you can get custom enchants like Viper (gives people poison) and e.t.c you can also make it allow people to get Sharpness 6, Power 7 e.t.c
The chances should be similar to Repair's (arcane salvage) level 120 or 115 gives you 10% and so on,
or it should go up in normal ways like mining's double drop you should also make a child skill of Enchanting and Repair (Maybe salvage) called Infusion this would allow you to enchant non-tools/books with enchantments in an anvil (just a normal anvil),
Thanks for Reading
-articdive

**Comment by t00thpick1** [comment]
Sorry not happening
