### ISSUE TITLE
When is UUID supported in mcMMO?

### ISSUE THREAD

**Issue by madtomic** [mcMMO-Dev/mcMMO#2636]
as subject.

I am using mcMMO v1.5.00-b3547

**Comment by madtomic** [comment]
Is there any snapshot I can download for 1.7 that support UUID or the last snapshot for 1.7?

**Comment by EvilOlaf** [comment]
Does the latest 1.5 not work for 1.7?

**Comment by madtomic** [comment]
I thought the latest 1.5.01+ are 1.8 only?

**Comment by madtomic** [comment]
I don't remembered it working on 1.7 servers

**Comment by EvilOlaf** [comment]
I actually don't know. Give it a try. Either it works or not ^^

**Comment by madtomic** [comment]
Thank you for helping.
