### ISSUE TITLE
Mobs not giving Exp

### ISSUE THREAD

**Issue by dvdtores** [mcMMO-Dev/mcMMO#2638]
I don't know why I don't receive experience points when I kill a player or mobs using an axe or just using hand.

**Comment by EvilOlaf** [comment]
Using different items to cause damage will skill different skills.
Check your skills in `unarmed`, `axe`, and `sword`.
Also keep in mind that mobs created from spawneggs or spawners might not give exp at all.

**Comment by dvdtores** [comment]
I have a server and I want people receive exp when they kill mobs, and thats not happening... I have no way to improve axes and unarmed because mobs are not giving exp.
How can I fix this? 
Ps: I'm using groupmanager and other plugins

**Comment by EvilOlaf** [comment]
There is actually no need to set any permissions for mcMMO at all. The default permissions work in most cases well.
Are you sure that mcMMO is loaded properly on server startup?

**Comment by dvdtores** [comment]
The problem is that only endermans are giving experience. Zombies, blazes, etc are not giving experience points and I don't know why. Mcmmo is running well.
