### ISSUE TITLE
How do I fix the BUILD_NUMBER?

### ISSUE THREAD

**Issue by madtomic** [mcMMO-Dev/mcMMO#2639]
[13:58:07 INFO]: [mcMMO] Enabling mcMMO v1.5.03-SNAPSHOT-b${BUILD_NUMBER}

**Comment by EvilOlaf** [comment]
You've built mcMMO from source.
The build number is added by Jenkins for the dev builds.
Edit your `pom.xml` and replace the fitting string with your own build number or use dev builds instead.

**Comment by madtomic** [comment]
Thank you,

**Comment by madtomic** [comment]
https://github.com/madtomic/mcMMO/blob/master/src/main/resources/.jenkins

Is this the file I need to edit?

**Comment by EvilOlaf** [comment]
Oops, you probably want to edit this one: https://github.com/madtomic/mcMMO/blob/master/src/main/resources/plugin.yml

**Comment by madtomic** [comment]
version: ${project.version}-b${BUILD_NUMBER}

Ok, why my BUILD_NUMBER is not pulled automatic? Just wondering... If it does, where is that information coming from? you mentioned Jenken?

**Comment by EvilOlaf** [comment]
This number comes from Jenkins, yes.
https://ci.drtshock.net/job/MCMMO/

**Comment by madtomic** [comment]
I see, thank you!
