### ISSUE TITLE
mcmmo block worlds

### ISSUE THREAD

**Issue by BoomScoom** [mcMMO-Dev/mcMMO#2644]
Is there a way to block mcmmo in certain worlds?  If so which config is it in so I can block certain worlds?

**Comment by EvilOlaf** [comment]
Use your favorite permission management plugin and negate all mcmmo permission for a certain world.

**Comment by BoomScoom** [comment]
I don't get it....

**Comment by EvilOlaf** [comment]
Read the documentation of your permission management plugin.

**Comment by BoomScoom** [comment]
I still don't get it...

**Comment by SullyTheUnusual** [comment]
I use zPermissions, and here is how I would do it:

perm group <group name> set <world>:<perm> false

**Comment by t00thpick1** [comment]
Use a permission plugin with per world permissions
