### ISSUE TITLE
Action-bar!

### ISSUE THREAD

**Issue by TheSuperAtia** [mcMMO-Dev/mcMMO#2659]
**So, I thought of this idea.**
Instead of getting spammed with messages in chat, why don't they get sent to the actionbar instead.
_There can also be an option in the config where you can choose between the chat and actionbar._

![mcmmo actionbar](https://cloud.githubusercontent.com/assets/13793238/9268465/958afdfe-425f-11e5-9aff-2205c2afe031.png)

If you don't want this to be a feature in the plugin, why not create it as an add-on?

**Comment by TheSuperAtia** [comment]
Bump

**Comment by t00thpick1** [comment]
I would have no qualms against someone putting in a Pull Request adding this,  however I might not have the time to do it myself for a while.
