### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by TheBlueKingLP** [mcMMO-Dev/mcMMO#2660]
If I use silk touch pickaxe to break the diamond ore to bring it home, place it, and use the piston to pall it, using silk touch pickaxe to break it again, it will be doubled

**Comment by EvilOlaf** [comment]
Fixed long time ago. Update mcmmo.

**Comment by TheBlueKingLP** [comment]
is sticky piston and i am newest version

**Comment by bm01** [comment]
Duplicate of #2655
