### ISSUE TITLE
Mob spawner experience multiplier isn't applied to pigmen spawned by nether portals

### ISSUE THREAD

**Issue by bm01** [mcMMO-Dev/mcMMO#2662]
Gold farms allow players to kill many pigmen in a short amount of time and have pretty much the same effect on level progression as mob spawners do. Because of that and because it is already possible with mob spawners, server administrator should be able to prevent gold farms from rewarding experience.

CreatureSpawnEvent.SpawnReason.NETHER_PORTAL can be used to fix this.

**Comment by EvilOlaf** [comment]
Agree

**Comment by ASuperthings** [comment]
Agree too

**Comment by t00thpick1** [comment]
I'll grab this on my next mcMMO passthrough,  I'm thinking of doing one on the weekend of the 12th
