### ISSUE TITLE
Salvage not working?

### ISSUE THREAD

**Issue by Spagz** [mcMMO-Dev/mcMMO#2664]
Ever since the last update Salvage is no longer working for my players. I double checked everything in the files and the child.yml but the things I tried don't fix it and nothing appears broken.

Placing the gold blocks doesn't do anything anymore and placed ones can't be used.

Im on the latest build and Spigot 1.8.8

**Comment by EvilOlaf** [comment]
Latest dev build? Latest official build?
"Latest" is not a very useful version declaration.

**Comment by Mike7493** [comment]
Latest Dev build

**Comment by leasoncre** [comment]
where do i set at what level salvage is unlocked? v1.5.03-b62 
or do i have to set it for each item in the salvage.yml?
