### ISSUE TITLE
Limit Unarmed Skill

### ISSUE THREAD

**Issue by CakeArmy** [mcMMO-Dev/mcMMO#2665]
How do I limit the unarmed skill?

**Comment by EvilOlaf** [comment]
Read the config files

**Comment by CakeArmy** [comment]
I did not see it in the config file which is why I created this thread.

**Comment by bm01** [comment]
You mean the level cap?

Here: https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/config.yml#L392
