### ISSUE TITLE
MCMMO will not start on modpack server.

### ISSUE THREAD

**Issue by Zilacon** [mcMMO-Dev/mcMMO#2672]
So i bought MCMMO on SpigotMC and threw it on all of my 1.7.10 servers.
It started and looks to work on RR3: Mainline, RR3:Project Flux, FTB Infinity, Agrarian Skies 2, Sky Factory 2, but it will not work on my own modpack server.

Here is what it says on the console: http://prntscr.com/86p8m7
I dont see any option to disable specific skills because i wanted to disable repairing/salvaging to see if that stopped the error.

Server Information:
Server: KCauldron Build 1492-152 1.7.10
Java: Java 8 64 Bit JRE
OS: Linux CENTOS 7
Modpack: http://www.technicpack.net/modpack/apocalyptic-gaming-tech-rpg.363244

Any help on this would be greatly appreciated!

**Comment by Zilacon** [comment]
Any news on this? I bought the plugin i would kinda like to use it on my modpack server >_>

**Comment by bm01** [comment]
mcMMO tries to get all the valid recipes on your server but an exception is thrown in the base Minecraft code.

The method used is CraftServer.getRecipesFor(ItemStack arg0) and works on a pure Craftbukkit / Spigot server.

I suggest you to report that error to them, since this isn't caused by neither mcMMO nor Spigot / CraftBukkit code.

**Comment by Zilacon** [comment]
I emptied the repair and salvage configs and its still giving the same error.
And report the error to who?

**Comment by bm01** [comment]
To whoever modified Minecraft's base code, it can pretty much be anyone. You could wait for t00thpick1 and see if he can find a better solution, but in my opinion I consider that to be an incompatibility that can't be dealt with from mcMMO's side.

**Comment by Zilacon** [comment]
I found out whats causing the error. Its IC2. All servers WITHOUT IC2 work. I had MCMMO on Tekkit Legends and they recently just added IC2 and now it errors just like TRPG.

Is it because it has its own recipe system? Could MCMMO just be patched to ignore IC2?

**Comment by Zilacon** [comment]
@bm01 

I found out whats causing the error. Its IC2. All servers WITHOUT IC2 work. I had MCMMO on Tekkit Legends and they recently just added IC2 and now it errors just like TRPG.

Is it because it has its own recipe system? Could MCMMO just be patched to ignore IC2?

**Comment by Speiger** [comment]
OK thats really interesting. @bm01 how does the Algorhym work?
I was first thinking you are making wrong keys or something but that seems to be not the case.
https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/util/skills/SkillUtils.java#L279
That line crashes it. I was sadly not able to find the Server Implementation from the bukkit source but if you could help me i can maybe track that down and we can maybe fix that...

What should be a temporary fix throw a TryCatch function in there to prevent problems. (I know IC2 is the problem but we can not fix something if we can not see the source of the problem and that will take time unless you have the name of the ServerImplementation^^)

**Comment by ClutchCabbage** [comment]
Any update on this??

**Comment by shinji257** [comment]
Ok.  So I thought I'd take a stab at this.  Wish I could get more visibility on what the code saw in this.  I went and did a try/catch where it generated configs.  I'm working with the 1.5.0.0 codebase and not the newer commited code.

Code edits in: src/main/java/com/gmail/nossr50/config/skills/repair/RepairConfig.java
