### ISSUE TITLE
How to turn off mcMMO parties

### ISSUE THREAD

**Issue by rubota** [mcMMO-Dev/mcMMO#2674]
How do I completely turn off the party options?

**Comment by bm01** [comment]
Do not give them the permissions, or negate them in your permissions plugin.

**Comment by rubota** [comment]
Thank you for replying so quickly. Do you know if there’s going to be an update later on so it’s a simple config switch like

 party mode: false


Also, is there a specific perm that takes away the option all together? or is it several?

**Comment by YoshiRulz** [comment]
Looking at the [permission list](https://github.com/mcMMO-Dev/mcMMO/wiki/List-of-permissions), the permission `mcmmo.commands.party` gives users access to `/party`. As long as no group or user has this permission, parties will be effectively disabled.
