### ISSUE TITLE
Scoreboard crash

### ISSUE THREAD

**Issue by Charityss** [mcMMO-Dev/mcMMO#2679]
Hi i'm not sure if i'm doing the right thing, but my server is a spigot 1.8.8 and we're running mcMMO Version 1.5.00-b3547 

The server keeps crashing and this is what console says:

29.08 03:51:54 [Server] ERROR ------------------------------
29.08 03:51:54 [Server] ERROR java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)
29.08 03:51:54 [Server] ERROR java.lang.Object.wait(Object.java:503)
29.08 03:51:54 [Server] ERROR java.lang.Object.wait(Native Method)
29.08 03:51:54 [Server] ERROR Stack:
29.08 03:51:54 [Server] ERROR PID: 2 | Suspended: false | Native: false | State: WAITING
29.08 03:51:54 [Server] ERROR Current Thread: Reference Handler
29.08 03:51:54 [Server] ERROR ------------------------------
29.08 03:51:54 [Server] ERROR java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)
29.08 03:51:54 [Server] ERROR java.lang.ref.ReferenceQueue.remove(Unknown Source)
29.08 03:51:54 [Server] ERROR java.lang.ref.ReferenceQueue.remove(Unknown Source)
29.08 03:51:54 [Server] ERROR java.lang.Object.wait(Native Method)
29.08 03:51:54 [Server] ERROR Stack:
29.08 03:51:54 [Server] ERROR PID: 3 | Suspended: false | Native: false | State: WAITING
29.08 03:51:54 [Server] ERROR Current Thread: Finalizer
29.08 03:51:54 [Server] ERROR ------------------------------
29.08 03:51:54 [Server] ERROR Stack:
29.08 03:51:54 [Server] ERROR PID: 5 | Suspended: false | Native: false | State: RUNNABLE
29.08 03:51:54 [Server] ERROR Current Thread: Signal Dispatcher
29.08 03:51:54 [Server] ERROR ------------------------------
29.08 03:51:54 [Server] ERROR java.util.TimerThread.run(Unknown Source)
29.08 03:51:54 [Server] ERROR java.util.TimerThread.mainLoop(Unknown Source)
29.08 03:51:54 [Server] ERROR java.lang.Object.wait(Object.java:503)
29.08 03:51:54 [Server] ERROR java.lang.Object.wait(Native Method)
29.08 03:51:54 [Server] ERROR Stack:
29.08 03:51:54 [Server] ERROR PID: 11 | Suspended: false | Native: false | State: WAITING
29.08 03:51:54 [Server] ERROR Current Thread: Snooper Timer
29.08 03:51:54 [Server] ERROR ------------------------------
29.08 03:51:54 [Server] ERROR net.minecraft.server.v1_8_R3.DedicatedServer$1.run(DedicatedServer.java:54)
29.08 03:51:54 [Server] ERROR java.lang.Thread.sleep(Native Method)
29.08 03:51:54 [Server] ERROR Stack:
29.08 03:51:54 [Server] ERROR PID: 15 | Suspended: false | Native: false | State: TIMED_WAITING
29.08 03:51:54 [Server] ERROR Current Thread: Server Infinisleeper
29.08 03:51:54 [Server] ERROR ------------------------------
29.08 03:51:54 [Server] ERROR java.lang.Thread.run(Unknown Source)
29.08 03:51:54 [Server] ERROR net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
29.08 03:51:54 [Server] ERROR net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
29.08 03:51:54 [Server] ERROR net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
29.08 03:51:54 [Server] ERROR net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722)
29.08 03:51:54 [Server] ERROR org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
29.08 03:51:54 [Server] ERROR org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
29.08 03:51:54 [Server] ERROR com.gmail.nossr50.runnables.player.PowerLevelUpdatingTask.run(PowerLevelUpdatingTask.java:10)
29.08 03:51:54 [Server] ERROR com.gmail.nossr50.util.scoreboards.ScoreboardManager.<clinit>(ScoreboardManager.java:97)
29.08 03:51:54 [Server] ERROR com.gmail.nossr50.util.scoreboards.ScoreboardManager.getOfflinePlayer(ScoreboardManager.java:121)
29.08 03:51:54 [Server] ERROR com.gmail.nossr50.util.scoreboards.ScoreboardManager.getOfflinePlayer(ScoreboardManager.java:133)
29.08 03:51:54 [Server] ERROR org.bukkit.craftbukkit.v1_8_R3.CraftServer.getOfflinePlayer(CraftServer.java:1299)
29.08 03:51:54 [Server] ERROR net.minecraft.server.v1_8_R3.UserCache.getProfile(UserCache.java:145)
29.08 03:51:54 [Server] ERROR net.minecraft.server.v1_8_R3.UserCache.a(UserCache.java:85)
29.08 03:51:54 [Server] ERROR com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:81)
29.08 03:51:54 [Server] ERROR java.lang.Thread.sleep(Native Method)
29.08 03:51:54 [Server] ERROR Stack:
29.08 03:51:54 [Server] ERROR PID: 14 | Suspended: false | Native: false | State: TIMED_WAITING
29.08 03:51:54 [Server] ERROR Current Thread: Server thread
29.08 03:51:54 [Server] ERROR ------------------------------
29.08 03:51:54 [Server] ERROR Stack:
29.08 03:51:54 [Server] ERROR PID: 16 | Suspended: false | Native: false | State: RUNNABLE
29.08 03:51:54 [Server] ERROR Current Thread: DestroyJavaVM
29.08 03:51:54 [Server] ERROR ------------------------------
29.08 03:51:54 [Server] ERROR java.lang.Thread.run(Unknown Source)
29.08 03:51:54 [Server] ERROR org.bukkit.craftbukkit.v1_8_R3.util.TerminalConsoleWriterThread.run(TerminalConsoleWriterThread.java:25)
29.08 03:51:54 [Server] ERROR com.mojang.util.QueueLogAppender.getNextLogEvent(QueueLogAppender.java:77)
29.08 03:51:54 [Server] ERROR java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
29.08 03:51:54 [Server] ERROR java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
29.08 03:51:54 [Server] ERROR java.util.concurrent.locks.LockSupport.park(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.misc.Unsafe.park(Native Method)
29.08 03:51:54 [Server] ERROR Stack:
29.08 03:51:54 [Server] ERROR PID: 18 | Suspended: false | Native: false | State: WAITING
29.08 03:51:54 [Server] ERROR Current Thread: Thread-4
29.08 03:51:54 [Server] ERROR ------------------------------
29.08 03:51:54 [Server] ERROR net.minecraft.server.v1_8_R3.DedicatedServer$2.run(DedicatedServer.java:81)
29.08 03:51:54 [Server] ERROR org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:2257)
29.08 03:51:54 [Server] ERROR org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:2269)
29.08 03:51:54 [Server] ERROR org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:2333)
29.08 03:51:54 [Server] ERROR org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLineSimple(ConsoleReader.java:3183)
29.08 03:51:54 [Server] ERROR org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2145)
29.08 03:51:54 [Server] ERROR org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:198)
29.08 03:51:54 [Server] ERROR org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:261)
29.08 03:51:54 [Server] ERROR org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:248)
29.08 03:51:54 [Server] ERROR java.io.BufferedInputStream.read(Unknown Source)
29.08 03:51:54 [Server] ERROR java.io.BufferedInputStream.fill(Unknown Source)
29.08 03:51:54 [Server] ERROR java.io.FileInputStream.read(Unknown Source)
29.08 03:51:54 [Server] ERROR java.io.FileInputStream.readBytes(Native Method)
29.08 03:51:54 [Server] ERROR Stack:
29.08 03:51:54 [Server] ERROR Locked on:org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:198)
29.08 03:51:54 [Server] ERROR Locked on:org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:261)
29.08 03:51:54 [Server] ERROR Locked on:java.io.BufferedInputStream.read(Unknown Source)
29.08 03:51:54 [Server] ERROR Thread is waiting on monitor(s):
29.08 03:51:54 [Server] ERROR PID: 17 | Suspended: false | Native: true | State: RUNNABLE
29.08 03:51:54 [Server] ERROR Current Thread: Server console handler
29.08 03:51:54 [Server] ERROR ------------------------------
29.08 03:51:54 [Server] ERROR java.lang.Thread.run(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.java2d.Disposer.run(Unknown Source)
29.08 03:51:54 [Server] ERROR java.lang.ref.ReferenceQueue.remove(Unknown Source)
29.08 03:51:54 [Server] ERROR java.lang.ref.ReferenceQueue.remove(Unknown Source)
29.08 03:51:54 [Server] ERROR java.lang.Object.wait(Native Method)
29.08 03:51:54 [Server] ERROR Stack:
29.08 03:51:54 [Server] ERROR PID: 20 | Suspended: false | Native: false | State: WAITING
29.08 03:51:54 [Server] ERROR Current Thread: Java2D Disposer
29.08 03:51:54 [Server] ERROR ------------------------------
29.08 03:51:54 [Server] ERROR org.spigotmc.WatchdogThread.run(WatchdogThread.java:76)
29.08 03:51:54 [Server] ERROR sun.management.ThreadImpl.dumpAllThreads(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.management.ThreadImpl.dumpThreads0(Native Method)
29.08 03:51:54 [Server] ERROR Stack:
29.08 03:51:54 [Server] ERROR PID: 23 | Suspended: false | Native: false | State: RUNNABLE
29.08 03:51:54 [Server] ERROR Current Thread: Spigot Watchdog Thread
29.08 03:51:54 [Server] ERROR ------------------------------
29.08 03:51:54 [Server] ERROR java.util.TimerThread.run(Unknown Source)
29.08 03:51:54 [Server] ERROR java.util.TimerThread.mainLoop(Unknown Source)
29.08 03:51:54 [Server] ERROR java.lang.Object.wait(Native Method)
29.08 03:51:54 [Server] ERROR Stack:
29.08 03:51:54 [Server] ERROR PID: 24 | Suspended: false | Native: false | State: TIMED_WAITING
29.08 03:51:54 [Server] ERROR Current Thread: Spigot Metrics Thread
29.08 03:51:54 [Server] ERROR ------------------------------
29.08 03:51:54 [Server] ERROR java.lang.Thread.run(Unknown Source)
29.08 03:51:54 [Server] ERROR io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
29.08 03:51:54 [Server] ERROR io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
29.08 03:51:54 [Server] ERROR io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
29.08 03:51:54 [Server] ERROR io.netty.channel.epoll.Native.epollWait(Native Method)
29.08 03:51:54 [Server] ERROR Stack:
29.08 03:51:54 [Server] ERROR PID: 25 | Suspended: false | Native: true | State: RUNNABLE
29.08 03:51:54 [Server] ERROR Current Thread: Netty Epoll Server IO #0
29.08 03:51:54 [Server] ERROR ------------------------------
29.08 03:51:54 [Server] ERROR java.lang.Thread.run(Unknown Source)
29.08 03:51:54 [Server] ERROR io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
29.08 03:51:54 [Server] ERROR io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:219)
29.08 03:51:54 [Server] ERROR io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:194)
29.08 03:51:54 [Server] ERROR io.netty.channel.epoll.Native.epollWait(Native Method)
29.08 03:51:54 [Server] ERROR Stack:
29.08 03:51:54 [Server] ERROR PID: 26 | Suspended: false | Native: true | State: RUNNABLE
29.08 03:51:54 [Server] ERROR Current Thread: Netty Epoll Server IO #1
29.08 03:51:54 [Server] ERROR ------------------------------
29.08 03:51:54 [Server] ERROR java.util.TimerThread.run(Unknown Source)
29.08 03:51:54 [Server] ERROR java.util.TimerThread.mainLoop(Unknown Source)
29.08 03:51:54 [Server] ERROR java.lang.Object.wait(Native Method)
29.08 03:51:54 [Server] ERROR Stack:
29.08 03:51:54 [Server] ERROR PID: 34 | Suspended: false | Native: false | State: TIMED_WAITING
29.08 03:51:54 [Server] ERROR Current Thread: Timer-0
29.08 03:51:54 [Server] ERROR ------------------------------
29.08 03:51:54 [Server] ERROR java.util.TimerThread.run(Unknown Source)
29.08 03:51:54 [Server] ERROR java.util.TimerThread.mainLoop(Unknown Source)
29.08 03:51:54 [Server] ERROR java.lang.Object.wait(Native Method)
29.08 03:51:54 [Server] ERROR Stack:
29.08 03:51:54 [Server] ERROR PID: 36 | Suspended: false | Native: false | State: TIMED_WAITING
29.08 03:51:54 [Server] ERROR Current Thread: Timer-1
29.08 03:51:54 [Server] ERROR ------------------------------
29.08 03:51:54 [Server] ERROR java.lang.Thread.run(Unknown Source)
29.08 03:51:54 [Server] ERROR com.Acrobot.ChestShop.Updater.Updater$UpdateRunnable.run(Updater.java:586)
29.08 03:51:54 [Server] ERROR com.Acrobot.ChestShop.Updater.Updater.access$400(Updater.java:41)
29.08 03:51:54 [Server] ERROR com.Acrobot.ChestShop.Updater.Updater.versionCheck(Updater.java:466)
29.08 03:51:54 [Server] ERROR com.Acrobot.ChestShop.Updater.Updater.shouldUpdate(Updater.java:508)
29.08 03:51:54 [Server] ERROR com.Acrobot.ChestShop.Updater.Updater.getLatestType(Updater.java:241)
29.08 03:51:54 [Server] ERROR com.Acrobot.ChestShop.Updater.Updater.waitForThread(Updater.java:289)
29.08 03:51:54 [Server] ERROR java.lang.Thread.join(Unknown Source)
29.08 03:51:54 [Server] ERROR java.lang.Thread.join(Unknown Source)
29.08 03:51:54 [Server] ERROR java.lang.Object.wait(Native Method)
29.08 03:51:54 [Server] ERROR Stack:
29.08 03:51:54 [Server] ERROR PID: 47 | Suspended: false | Native: false | State: WAITING
29.08 03:51:54 [Server] ERROR Current Thread: Thread-15
29.08 03:51:54 [Server] ERROR ------------------------------
29.08 03:51:54 [Server] ERROR com.vexsoftware.votifier.net.VoteReceiver.run(VoteReceiver.java:114)
29.08 03:51:54 [Server] ERROR java.net.ServerSocket.accept(Unknown Source)
29.08 03:51:54 [Server] ERROR java.net.ServerSocket.implAccept(Unknown Source)
29.08 03:51:54 [Server] ERROR java.net.AbstractPlainSocketImpl.accept(Unknown Source)
29.08 03:51:54 [Server] ERROR java.net.PlainSocketImpl.socketAccept(Native Method)
29.08 03:51:54 [Server] ERROR Stack:
29.08 03:51:54 [Server] ERROR PID: 48 | Suspended: false | Native: true | State: RUNNABLE
29.08 03:51:54 [Server] ERROR Current Thread: Thread-16
29.08 03:51:54 [Server] ERROR ------------------------------
29.08 03:51:54 [Server] ERROR com.gamingmesh.jobs.tasks.DatabaseSaveThread.run(DatabaseSaveThread.java:47)
29.08 03:51:54 [Server] ERROR java.lang.Thread.sleep(Native Method)
29.08 03:51:54 [Server] ERROR Stack:
29.08 03:51:54 [Server] ERROR PID: 49 | Suspended: false | Native: false | State: TIMED_WAITING
29.08 03:51:54 [Server] ERROR Current Thread: Jobs-DatabaseSaveTask
29.08 03:51:54 [Server] ERROR ------------------------------
29.08 03:51:54 [Server] ERROR com.gamingmesh.jobs.tasks.BufferedPaymentThread.run(BufferedPaymentThread.java:47)
29.08 03:51:54 [Server] ERROR java.lang.Thread.sleep(Native Method)
29.08 03:51:54 [Server] ERROR Stack:
29.08 03:51:54 [Server] ERROR PID: 50 | Suspended: false | Native: false | State: TIMED_WAITING
29.08 03:51:54 [Server] ERROR Current Thread: Jobs-BufferedPaymentThread
29.08 03:51:54 [Server] ERROR ------------------------------
29.08 03:51:54 [Server] ERROR java.lang.Thread.run(Unknown Source)
29.08 03:51:54 [Server] ERROR java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
29.08 03:51:54 [Server] ERROR java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
29.08 03:51:54 [Server] ERROR org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
29.08 03:51:54 [Server] ERROR org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
29.08 03:51:54 [Server] ERROR net.milkbowl.vault.Metrics$4.run(Metrics.java:275)
29.08 03:51:54 [Server] ERROR net.milkbowl.vault.Metrics.access$400(Metrics.java:63)
29.08 03:51:54 [Server] ERROR net.milkbowl.vault.Metrics.postPlugin(Metrics.java:501)
29.08 03:51:54 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.net.www.http.HttpClient.New(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.net.www.http.HttpClient.New(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.net.www.http.HttpClient.<init>(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.net.www.http.HttpClient.openServer(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.net.www.http.HttpClient.openServer(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.net.NetworkClient.doConnect(Unknown Source)
29.08 03:51:54 [Server] ERROR java.net.Socket.connect(Unknown Source)
29.08 03:51:54 [Server] ERROR java.net.Socket.connect(Unknown Source)
29.08 03:51:54 [Server] ERROR java.net.SocksSocketImpl.connect(Unknown Source)
29.08 03:51:54 [Server] ERROR java.net.AbstractPlainSocketImpl.connect(Unknown Source)
29.08 03:51:54 [Server] ERROR java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
29.08 03:51:54 [Server] ERROR java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
29.08 03:51:54 [Server] ERROR java.net.PlainSocketImpl.socketConnect(Native Method)
29.08 03:51:54 [Server] ERROR Stack:
29.08 03:51:54 [Server] ERROR Locked on:sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
29.08 03:51:54 [Server] ERROR Locked on:sun.net.www.http.HttpClient.openServer(Unknown Source)
29.08 03:51:54 [Server] ERROR Locked on:java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
29.08 03:51:54 [Server] ERROR Thread is waiting on monitor(s):
29.08 03:51:54 [Server] ERROR PID: 60 | Suspended: false | Native: true | State: RUNNABLE
29.08 03:51:54 [Server] ERROR Current Thread: Craft Scheduler Thread - 0
29.08 03:51:54 [Server] ERROR ------------------------------
29.08 03:51:54 [Server] ERROR java.lang.Thread.run(Unknown Source)
29.08 03:51:54 [Server] ERROR java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
29.08 03:51:54 [Server] ERROR java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
29.08 03:51:54 [Server] ERROR org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
29.08 03:51:54 [Server] ERROR org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
29.08 03:51:54 [Server] ERROR me.xADudex.RandomLocation.MetricsLite$1.run(MetricsLite.java:147)
29.08 03:51:54 [Server] ERROR me.xADudex.RandomLocation.MetricsLite.access$3(MetricsLite.java:253)
29.08 03:51:54 [Server] ERROR me.xADudex.RandomLocation.MetricsLite.postPlugin(MetricsLite.java:334)
29.08 03:51:54 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.net.www.http.HttpClient.New(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.net.www.http.HttpClient.New(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.net.www.http.HttpClient.<init>(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.net.www.http.HttpClient.openServer(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.net.www.http.HttpClient.openServer(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.net.NetworkClient.doConnect(Unknown Source)
29.08 03:51:54 [Server] ERROR java.net.Socket.connect(Unknown Source)
29.08 03:51:54 [Server] ERROR java.net.Socket.connect(Unknown Source)
29.08 03:51:54 [Server] ERROR java.net.SocksSocketImpl.connect(Unknown Source)
29.08 03:51:54 [Server] ERROR java.net.AbstractPlainSocketImpl.connect(Unknown Source)
29.08 03:51:54 [Server] ERROR java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
29.08 03:51:54 [Server] ERROR java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
29.08 03:51:54 [Server] ERROR java.net.PlainSocketImpl.socketConnect(Native Method)
29.08 03:51:54 [Server] ERROR Stack:
29.08 03:51:54 [Server] ERROR Locked on:sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
29.08 03:51:54 [Server] ERROR Locked on:sun.net.www.http.HttpClient.openServer(Unknown Source)
29.08 03:51:54 [Server] ERROR Locked on:java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
29.08 03:51:54 [Server] ERROR Thread is waiting on monitor(s):
29.08 03:51:54 [Server] ERROR PID: 61 | Suspended: false | Native: true | State: RUNNABLE
29.08 03:51:54 [Server] ERROR Current Thread: Craft Scheduler Thread - 1
29.08 03:51:54 [Server] ERROR ------------------------------
29.08 03:51:54 [Server] ERROR java.lang.Thread.run(Unknown Source)
29.08 03:51:54 [Server] ERROR java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
29.08 03:51:54 [Server] ERROR java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
29.08 03:51:54 [Server] ERROR org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
29.08 03:51:54 [Server] ERROR org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
29.08 03:51:54 [Server] ERROR com.gmail.filoghost.holographicdisplays.metrics.MetricsLite$1.run(MetricsLite.java:175)
29.08 03:51:54 [Server] ERROR com.gmail.filoghost.holographicdisplays.metrics.MetricsLite.access$3(MetricsLite.java:281)
29.08 03:51:54 [Server] ERROR com.gmail.filoghost.holographicdisplays.metrics.MetricsLite.postPlugin(MetricsLite.java:362)
29.08 03:51:54 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.net.www.http.HttpClient.New(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.net.www.http.HttpClient.New(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.net.www.http.HttpClient.<init>(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.net.www.http.HttpClient.openServer(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.net.www.http.HttpClient.openServer(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.net.NetworkClient.doConnect(Unknown Source)
29.08 03:51:54 [Server] ERROR java.net.Socket.connect(Unknown Source)
29.08 03:51:54 [Server] ERROR java.net.Socket.connect(Unknown Source)
29.08 03:51:54 [Server] ERROR java.net.SocksSocketImpl.connect(Unknown Source)
29.08 03:51:54 [Server] ERROR java.net.AbstractPlainSocketImpl.connect(Unknown Source)
29.08 03:51:54 [Server] ERROR java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
29.08 03:51:54 [Server] ERROR java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
29.08 03:51:54 [Server] ERROR java.net.PlainSocketImpl.socketConnect(Native Method)
29.08 03:51:54 [Server] ERROR Stack:
29.08 03:51:54 [Server] ERROR Locked on:sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
29.08 03:51:54 [Server] ERROR Locked on:sun.net.www.http.HttpClient.openServer(Unknown Source)
29.08 03:51:54 [Server] ERROR Locked on:java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
29.08 03:51:54 [Server] ERROR Thread is waiting on monitor(s):
29.08 03:51:54 [Server] ERROR PID: 62 | Suspended: false | Native: true | State: RUNNABLE
29.08 03:51:54 [Server] ERROR Current Thread: Craft Scheduler Thread - 2
29.08 03:51:54 [Server] ERROR ------------------------------
29.08 03:51:54 [Server] ERROR java.lang.Thread.run(Unknown Source)
29.08 03:51:54 [Server] ERROR java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
29.08 03:51:54 [Server] ERROR java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
29.08 03:51:54 [Server] ERROR java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
29.08 03:51:54 [Server] ERROR java.util.concurrent.SynchronousQueue.poll(Unknown Source)
29.08 03:51:54 [Server] ERROR java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
29.08 03:51:54 [Server] ERROR java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
29.08 03:51:54 [Server] ERROR java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
29.08 03:51:54 [Server] ERROR sun.misc.Unsafe.park(Native Method)
29.08 03:51:54 [Server] ERROR Stack:
29.08 03:51:54 [Server] ERROR PID: 63 | Suspended: false | Native: false | State: TIMED_WAITING
29.08 03:51:54 [Server] ERROR Current Thread: Craft Scheduler Thread - 3
29.08 03:51:54 [Server] ERROR ------------------------------
29.08 03:51:54 [Server] ERROR java.lang.Thread.run(Unknown Source)
29.08 03:51:54 [Server] ERROR java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
29.08 03:51:54 [Server] ERROR java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
29.08 03:51:54 [Server] ERROR org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
29.08 03:51:54 [Server] ERROR org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
29.08 03:51:54 [Server] ERROR me.Mammothskier.Giants.util.Metrics$1.run(Metrics.java:223)

Can anyone help?

**Comment by t00thpick1** [comment]
Fixed
