### ISSUE TITLE
Salvage Bug - Player receives only 1 of any item

### ISSUE THREAD

**Issue by NmExHunTeRz** [mcMMO-Dev/mcMMO#2680]
As the title says, this has been an on-going issue for nearly an ENTIRE month. Salvaging is a huge part of mcMMO and a lot of players are eager for it to be fixed.

Currently on the latest dev build (#67) running Spigot. 

A bit information about the bug, when salvaging any given armor piece you only receive 1 of the item instead of the correct amount, so for a diamond chestplate you should receive 9 diamonds but instead you receive 1. 

Thanks.

**Comment by EvilOlaf** [comment]
Duplicate https://github.com/mcMMO-Dev/mcMMO/issues/2627
