### ISSUE TITLE
Double Drops Not Applying To Mesa Biome Blocks

### ISSUE THREAD

**Issue by oopsidoodles** [mcMMO-Dev/mcMMO#2681]
Title says it all, naturally spawning blocks of hardened/stained clay are not affected by double drop ability when mining. Not sure about red sand, but I'd assume same thing applies.

You can, however, get mining exp by mining them, just not double drops.

**Comment by FabioZumbi12** [comment]
This is true, and not only for hardened/stained clay but with Aquatic Temple blocks too! Please fix!!

**Comment by oopsidoodles** [comment]
^ Didn't know that, and to add on. If you try to add the blocks into double drops for mining in config.yml, the config just removes the extra lines. I've tried enabling mod blocks and adding hardened clay as one and enabling double drops for it, and while there were no errors in console, it still wouldn't do double drops.

**Comment by Tslat** [comment]
Just checked the code base for it, hardened and stained clay should be working..
Are you sure they're not?
Prismarine definitely isn't in there though, so that one is true
