### ISSUE TITLE
[Feature Request] Resistance Skill.

### ISSUE THREAD

**Issue by Sven65** [mcMMO-Dev/mcMMO#2683]
I'd like to see this skill and I think it would be really cool.

# Resistance Skill

## Leveling up:

- Dying

###### Take less damage
- The higher level, the less damage taken.

###### More hearts
- At a higher level, unlock more hearts.

Thanks.

\- Mackan

**Comment by CeIebrimbor** [comment]
Reference the Alchemy skill. You can unlock absorption and resistance potions.

Nobody would make a skill that requires player to spam the chat with death messages to boost.

**Comment by t00thpick1** [comment]
Sorry no
