### ISSUE TITLE
Error occurred while disabling mcMMO v1.5.04-SNAPSHOT-b67

### ISSUE THREAD

**Issue by TheChampTF** [mcMMO-Dev/mcMMO#2685]
Hey

For some reason I'm getting this on shot down http://paste.yu8.me/?8d1a04990079f95d#kNWL/BEopsJZEhyhC2EWZCrA1Sx7Qy4qeBF3bFm25sM=

**Comment by t00thpick1** [comment]
Sorry I don't use paste services other than hastebin and pastebin.
