### ISSUE TITLE
Please help!!!!!!

### ISSUE THREAD

**Issue by lotami** [mcMMO-Dev/mcMMO#2687]
Help me, when I try to get into the protected area of ​​my home I check and I think it's because I put too much protection blocks and three months ago can not go and I would like to help me please .

**Comment by lotami** [comment]
Please help me a hard time getting everything that I have :(

**Comment by lotami** [comment]
tambien hablo español pero es que no se en que idioma me ibais a entender....

**Comment by EvilOlaf** [comment]
Probably not related to mcmmo at all.
Therefore invalid.

**Comment by lotami** [comment]
then I do so you can enter mcmmo please help me :(

**Comment by madtomic** [comment]
What other plugins are there on the server?

**Comment by lotami** [comment]
Please help me want to go to Pure survival =(

**Comment by madtomic** [comment]
This is your own server? If so, can you do in game chat.

/plugins

And list the plugins here. What you mean pure survival?

**Comment by lotami** [comment]
yes

**Comment by NmExHunTeRz** [comment]
This is probably the most toxic thing I've seen in a long while. 

@lotami I recommend you avoid using this issue reporting system until you can understand the basics of running a server. Perhaps try watching some youtube tutorials. 

@lotami Te recomiendo que evite el uso de este sistema de notificación de tema hasta que pueda entender los conceptos básicos de la gestión de un servidor. Tal vez tratar de ver algunos tutoriales de youtube.

**Comment by lotami** [comment]
Como va a salir un tutorial de esto no habra otra forma ?
