### ISSUE TITLE
Salvage

### ISSUE THREAD

**Issue by GothkittyGirl** [mcMMO-Dev/mcMMO#2689]
ive been trying to figure how to allow players to salvage but got a % of the mats back. ive searched everywhere and cant find anyone talking about that. is there something missing in config??

**Comment by NmExHunTeRz** [comment]
You could of been a more detailed and helpful with your issue but I think the issue you're having is that players are only receiving one of an item they salvage if so this is a known issue for over 4 weeks, shame there's been such a delay on resolving it.

**Comment by GothkittyGirl** [comment]
no my issue is they get it all back at low lvls and i want to allow them to salvage but not get it all back from the items the salvage but get a % of the items back. ive seen this done on other servers but no idea how. so i thought the staff here would know this answer

**Comment by t00thpick1** [comment]
Not built in,  they probably use our event system to modify the results based on level
