### ISSUE TITLE
Fishing bite chance and Catch rate

### ISSUE THREAD

**Issue by Delliurm** [mcMMO-Dev/mcMMO#2690]
It currently takes a long time to catch a fish. I set the cap at 2k. Gave myself 2k mcmmo fishing levels. The bite chance is .20%. I have no idea how to change it. I did see the boat modifier. I was able to change it where while in a boat i have 100% bite chance. I really feel like it still takes just as long to catch even in a boat with 100% bite chance. I am trying to increase the speed of which you catch fish/items.

**Comment by CeIebrimbor** [comment]
Fishing in River or Ocean Biome decreases time between chances to get bite. Along with boat.

**Comment by t00thpick1** [comment]
Find and check the biome modifier in the configs.  The math works as follows:
We get the bite chance from minecraft. (somewhere between 0 and 1)
We multiply by biome modifier
We multiply by boat modifier
we set.
1 is insta catch
0 is no catch
