### ISSUE TITLE
Spigot Merge Items and Mining Double Drops

### ISSUE THREAD

**Issue by CeIebrimbor** [mcMMO-Dev/mcMMO#2693]
I created a bug report on the Spigot JIRA, but it also relates to MCMMO. 

When you mine ore above your head in a cave and get a double drop (mining skill ability), the Spigot "merge-items" feature merges them and has a chance to force the dropped blocks upwards. If there is solid blocks above the ore, there is a chance that the merging item trajectory forces the blocks to appear in the next available location. This causes the ore to teleport to the surface of the world.

This happens about 50% of the time when you get a double drop and have the above described specifications in play.

**Comment by t00thpick1** [comment]
Not much I can do about this.
