### ISSUE TITLE
Is it worth it to buy? (pay vs free)

### ISSUE THREAD

**Issue by xkitox** [mcMMO-Dev/mcMMO#2698]
Has anything new been added to this version that isnt included in the free one?

**Comment by EvilOlaf** [comment]
As written at the plugin page at spigotmc  the free version is exactly the same as the premium one. If you buy it anyways it is like a donation to the project and support the developer :)

**Comment by xkitox** [comment]
Ah, I did see the part about their concern about the lack of donations, I did not see where it says they are the same though.  Anyway, thanks.
