### ISSUE TITLE
My server stops with MCMMO

### ISSUE THREAD

**Issue by ElitStrikerzHD** [mcMMO-Dev/mcMMO#2699]
12.10 08:12:00 [Server] INFO Disabled link to plugin mcMMO, version 1.5.04-SNAPSHOT-b67
12.10 08:12:00 [Server] INFO Disabling mcMMO v1.5.04-SNAPSHOT-b67
12.10 08:12:00 [Server] INFO Disabling Multiverse-Portals v2.5-b725
12.10 08:12:00 [Server] INFO Disabling Vault v1.5.6-b49
12.10 08:12:00 [Server] INFO GAListener v1.3.1 Disabled
12.10 08:12:00 [Server] INFO Disabling GAListener v1.3.1
12.10 08:12:00 [Server] INFO Disabling EssentialsSpawn vTeamCity
12.10 08:12:00 [Server] INFO Disabled
12.10 08:12:00 [Server] INFO Disabling MassiveCore v2.7.5
12.10 08:12:00 [Server] INFO Disabling uSkyBlock v2.4.7
12.10 08:12:00 [Server] INFO Disabling HolographicDisplays v2.1.10
12.10 08:12:00 [Server] INFO has been disabled.
12.10 08:12:00 [Server] INFO Disabling WhatIsIt v1.3.9
12.10 08:12:00 [Server] INFO Version: 3.7 by [Herbystar] disabled!

Nothing more comes it just crashes and says this
i'm running 1.8.8 spigot and MCMMO 1.8

12.10 08:12:34 [Multicraft] JAR file not found, copying from global JAR directory
12.10 08:12:33 [Multicraft] Loaded config for "Spigot 1.8.8 (Auto Update)"
12.10 08:12:33 [Multicraft] Starting server!
12.10 08:12:33 [Multicraft] Loading server properties
12.10 08:12:33 [Disconnect] User ElitStrikerzHD has disconnected, reason: Server shutting down
12.10 08:12:33 [Multicraft] Server stopped
12.10 08:12:33 [Multicraft] Looks like a crash, check the server console. Return value: 143
12.10 08:12:33 [Multicraft] Server shut down
12.10 08:12:32 [Multicraft] Terminating server via signal
12.10 08:12:00 [Server] INFO Disabled link to plugin mcMMO, version 1.5.04-SNAPSHOT-b67
12.10 08:12:00 [Server] INFO Disabling mcMMO v1.5.04-SNAPSHOT-b67
12.10 08:12:00 [Server] INFO Disabling Multiverse-Portals v2.5-b725

**Comment by ElitStrikerzHD** [comment]
Dayhmmm bad support

**Comment by t00thpick1** [comment]
This is an issue with the metrics library we used.  If you use the latest dev build, I have removed all of our metrics as they were unused anyways.
