### ISSUE TITLE
McMMO Wont Launch

### ISSUE THREAD

**Issue by rockclimb3r** [mcMMO-Dev/mcMMO#2701]
Hey Guys,

Have the latest spigot 1.8.8 and can't seem to get mcMMO to initiate. 

I have updated to Java 8 as someone previously recommended and still nothing.
http://pastebin.com/r3ek0vWJ#

<script src="http://pastebin.com/embed_js.php?i=r3ek0vWJ"></script>

**Comment by t00thpick1** [comment]
Thats interesting...  Are you sure you are on java 8 or 7?

**Comment by clive9455** [comment]
was a fix ever found for this?
