### ISSUE TITLE
mcmmo free version link is broken for me

### ISSUE THREAD

**Issue by Jordan0Davis** [mcMMO-Dev/mcMMO#2712]
the https://ci.drtshock.net/job/MCMMO/ when i click on it, it says the website is unavaiable

**Comment by Jordan0Davis** [comment]
id buy it but im really really poor lol

**Comment by EvilOlaf** [comment]
CI is online and working well.

**Comment by Jordan0Davis** [comment]
wierd i keep getting this A secure connection cannot be established because this site uses an unsupported protocol. any ideas on how to fix?

**Comment by EvilOlaf** [comment]
Update your browser ^^

**Comment by Jordan0Davis** [comment]
i checked and it says my google crome is up to date wierd

**Comment by EvilOlaf** [comment]
Also using Chrome, tried with latest stable and beta. Works perfectly. 

The CI is using SSL. Maybe your firewall or other (bad) services are trying to interfere your connection to the server ("man-in-the-middle")?

**Comment by Jordan0Davis** [comment]
is there a way to allow ssl on my firewall? and thanks for the help @EvilOlaf

**Comment by EvilOlaf** [comment]
I do not have a second sight so I have no idea what kind of firewall you are using ^^
This question might be answered by the maker of your firewall anyways as this is not an issue with the CI.

**Comment by Jordan0Davis** [comment]
in any case i still thank you for trying to help me in this endeavor.
