### ISSUE TITLE
Experience formula for Exponential is currently actually Polynomial

### ISSUE THREAD

**Issue by Hirokuzu** [mcMMO-Dev/mcMMO#2715]
Was play testing to see whether or not I could implement #2464 properly, and discovered that the experience required for exponential gain was rising _extremely_ slowly. This is with the base values given, it would go from 2000 exp to next level, to 2001 exp, after a few levels. Some digging revealed the formula below in FormulaManager (line 127)

``` Java
experience = (int) Math.floor(multiplier * Math.pow(level, exponent) + base);
```

The above is polynomial gain (x^a), not exponential(a^x). This might be the reason for the slow growth. I believe the formula should be corrected to the following:

``` Java
experience = (int) Math.floor(multiplier * Math.pow(exponent, level) * base);
```

the variable names become confusing at this point.

The configuration files will also have to be tuned or else the experience curve will spiral out of control -- level 50 to level 51 would need `1.8^50 * 0.1 * 2000 ~= 1.2*10^15` experience points, whereas an "exponent" of 1.05 and "multiplier" of 1 would result in `1.05^50 * 2000 = 22934` experience points.

**Comment by t00thpick1** [comment]
OK 2 things,  A: SPlit your PR into 2 PR's  one for #2669  and another for #2464  In that second one you can patch this and fix our default config values.   Make sure ALL of the default config values for individual skills are LINEAR.   If you are feeling up to it, you can write into our config checker a condition to update the previous key into the new ones.

**Comment by Hirokuzu** [comment]
My group mate has done the proposed changes and made a separate pull request. Didn't write into the configuration checker as we have other school projects to work on. Let us know if anything else needs to be changed.
