### ISSUE TITLE
1.8 and doors

### ISSUE THREAD

**Issue by puppy0cam** [mcMMO-Dev/mcMMO#2717]
https://gaming.youtube.com/watch?v=41S2CD0ZLpQ
this describes the glitch and where it works but the gist of it is that on all 1.8 doors and the iron trapdoor mcmmo readies the ability when you interact with them.
a possible way to help with future incompatibilities is a config for specifying specific blocks to not do certain things on.

**Comment by t00thpick1** [comment]
Should not be the case on our spigot builds.
