### ISSUE TITLE
Server Startup Error

### ISSUE THREAD

**Issue by ultracasual** [mcMMO-Dev/mcMMO#2721]
KCauldron-1.7.10-1517.168

Mods:
NEI,CodeChicken Core,Flaxbeard's Steam Power,GrowthCraft,Inventory Tweaks,JourneyMap,JourneyMap Server,Primitive Mobs,Recall Stones,Screenshots Enhanced,Waila,Waila Harvestability

Plugins:
Vault,WorldGuard,WorldEdit,PermissionsEX,ChatEX,Modifyworld, Multiverse-Core,Multiverse-Portals,Essentials

Error Log:
http://pastebin.com/ALpFXkYw

Server appears to start fine despite the error which is unusual, plugin doesn't work in-game. I've already purchased a plugin that did not work with my server, and now hesitant to invest in mcMMO.

**Comment by t00thpick1** [comment]
Please ensure that the jar is full and correct, it looks like its missing classes?   Otherwise it might be a corrupted config which would mean just rebuild the config.
