### ISSUE TITLE
McMMO , spigot 1.8.8

### ISSUE THREAD

**Issue by kiaph** [mcMMO-Dev/mcMMO#2727]
Not sure where the problem is, completely re installed with your most recent .05 snapshot and just spigot , but no luck, I am not sure what is wrong, or if I have to use craftbukkit jar to run it instead of sippot, I have not tried that but I felt stupid even considering that could be it, so I am not sure where to go with this but to you.

**Comment by t00thpick1** [comment]
Well this gives me almost no information on whats not working so...
