### ISSUE TITLE
Call of the Wild Pet Names - Typo

### ISSUE THREAD

**Issue by Braleth** [mcMMO-Dev/mcMMO#2731]
mcMMO ver 1.5.04-snapshot-b82 (Although I've seen this in earlier versions as well.)

There is a typo in the locale_en_US.properties file: Taming.Summon.Name.Format={0}''s {1}

This line contains two ' symbols when it should only be one. Summoned pets are showing up in game as Joe''s Horse instead of Joe's Horse.

Manually editing the local file and injecting it back into the .jar file corrects the issue when in-game.

**Comment by Tslat** [comment]
Yeah it also affects Fisherman''s Diet

**Comment by Braleth** [comment]
Add the following to the list as well:

Farmer''s Diet
Using the /mcrefresh <player name> command:  Tslat''s cooldowns have been refreshed.

These are all present in the latest dev build of mcMMO.
