### ISSUE TITLE
not sure if this is the right place...

### ISSUE THREAD

**Issue by thekiltedcook** [mcMMO-Dev/mcMMO#2732]
ive been playing with mcmmo on my private server for a few months now, and everything is great, except the salvage feature. my fishing is 82, and my repair is 54, but it still says im not skilled enough to salvage. is that an issue in my game, or am i doing something wrong? thank you in advance for taking the time to help me!

**Comment by Ironic8b498** [comment]
default unlock level is 350 which means you need a total of 700 between fishing and repair. You can edit if you want in the advance.yml file.

**Comment by thekiltedcook** [comment]
ok, i messed with that file, and at least on the server that im using (hosthorde), it seems to me that it only uses the repair number, not fishing. i say that because i leveled my fishing to 538 and repair to 295, for a total of 833, and couldnt salvage. when i went in the file you mentioned, i found salvage under repair, and mine was set to 600. as soon as i changed it to 200, i could salvage. not sure if its just hosthorde or what, just thought you should know. thank you for helping me!
