### ISSUE TITLE
mcMMO Mob Health disable

### ISSUE THREAD

**Issue by DahFrozen** [mcMMO-Dev/mcMMO#2734]
Hi,

I would like to disable the Mob Heathbar feature of the plugin but it is not working when I try to. Here is my configuration: 

Mob_Healthbar:
    # Display_Type: Default display for mob health bars - HEARTS, BAR, or DISABLED
    # Display_Time: Amount of time (in seconds) to display. To display permanently, set to -1
    Display_Type: DISABLED
    Display_Time: 3

Thanks,
Frozon.

**Comment by t00thpick1** [comment]
Make sure to edit the config while the server is offline?  Not sure, that config should work.

**Comment by DahFrozen** [comment]
The server has restarted at least twice over the 17 days from when i made this post.

I checked the config and found this:

Mob_Healthbar:
    # Display_Type: Default display for mob health bars - HEARTS, BAR, or DISABLED
    # Display_Time: Amount of time (in seconds) to display. To display permanently, set to -1
    Display_Type: DISABLED
    Display_Time: 1


I'm pretty sure it's broken and mcMMO is ignoring the configuration.
