### ISSUE TITLE
Allow mcMMO to use its healthbars even if HealthBar is installed

### ISSUE THREAD

**Issue by RoboMWM** [mcMMO-Dev/mcMMO#2737]
I'm not using healthbars for mobs with the HealthBar plugin, but mcMMO will always disable its healthbars when it detects the presence of HealthBar.

**Comment by Tslat** [comment]
Why would you want it to work like that?

**Comment by RoboMWM** [comment]
Because you can disable Healthbar's mob bars... and I'd prefer mcMMO's way of displaying healthbars? (scales bar size on mob type, only appears when mob is damaged, etc.)

**Comment by Tslat** [comment]
Then why do you have a healthbar mod?

**Comment by RoboMWM** [comment]
I'm using it for the players... you don't really seem to understand, do you?

**Comment by Tslat** [comment]
Oh so you're asking for it only on mobs, not players?

**Comment by RoboMWM** [comment]
Yes... mcMMO's healthbars only apply to mobs...
