### ISSUE TITLE
Dupe

### ISSUE THREAD

**Issue by zzkanezz2** [mcMMO-Dev/mcMMO#2738]
Pistons, ores. Same issue as always, latest mcmmo. Please fix it as it's been a few months now.

**Comment by EvilOlaf** [comment]
What is latest for you? Latest official? Latest dev?

**Comment by zzkanezz2** [comment]
Latest official mcmmo build, premium spigot resource.

**Comment by EvilOlaf** [comment]
You may take a look here: https://ci.drtshock.net/job/MCMMO/

**Comment by zzkanezz2** [comment]
Awesome, does this contain the dupe fix?

**Comment by EvilOlaf** [comment]
There were several attempts to fix this in the past, so it may contain a fix or  it is still not 100% fixed. Don't know.

**Comment by t00thpick1** [comment]
With our later versions this should not be an issue, we no longer allow any blocks that interact with a piston to be double dropped, regardless of previous state.
