### ISSUE TITLE
Permission Problem

### ISSUE THREAD

**Issue by Flash2over** [mcMMO-Dev/mcMMO#2740]
We have a problem with the permissions. if i grant users mcmmo.skills.taming they get mcmmo.ability.taming.all. It would we nice if we could give a permission only for level that skill and dont use the abilities. even - permisions cant handle it if i give -mcmmo.ability.taming.all the skill mcmmo.skills.taming overrates the - permission.

Backround: we got an own skill plugin which manages Classes and you get the abilities with levels and skills. So all players should be able to level each different skill but they get the permissions for abilities at a higher level.

**Comment by EvilOlaf** [comment]
Most permissions are `true` at default, so there is no need to give someone `mcmmo.ability.taming`.

**Comment by Flash2over** [comment]
yes but to disable all permissions you need to -mcmmo.default. so you dont got any permissions. if i negate all permissions which need to be negatet just to give the taming skill to level i would have a huge permission file.

Its just bad to true all permissions at start. thats only for servers who dont want to set permissions. you cant even change a config to disable everything by default. 

The easyiest way to give that all a change would be to give a level permission for each skill. they wouldnt be so hard to program.

**Comment by t00thpick1** [comment]
Use a setup like this:
+mcmmo.skills.alchemy
-mcmmo.ability.alchemy.all

**Comment by Flash2over** [comment]
yes plugin of the year award goes to mcmmo....

we fixed it for us like that: unpack mcmmo.jar open plugin.yml remove all that fucking permissions repack everything....good to pay 10bucks via spigot premium to get 0 help from admin.
I Think the owner should rethink his permission system and change something. dont be such a "user negative permissions" fool.

just my 2 cent....

**Comment by t00thpick1** [comment]
The system we have in place is the one that works for the widest range of users.  Special cases like yours might require some finagling, but the vast majority of mcMMO users want it the way it is...
