### ISSUE TITLE
mcMMO console spam

### ISSUE THREAD

**Issue by Dynarrhian** [mcMMO-Dev/mcMMO#2742]
This is the first time I've set up a server for a pretty long while, but there seems to be a problem with Spigot 1.8.8 and the newest mcMMO dev build 82. Errors keep spamming my console and I have no idea why. I've already tried regenerating the configs, but that didn't help either.

Here are two errors which can be seen frequently in the console. Looks like they occur everytime someone levels up.
http://pastebin.com/Pcg7vA6F
http://pastebin.com/UsFN3H4g

Thanks in advance!

**Comment by EvilOlaf** [comment]
Do you have other plugins that are using the scoreboard?

**Comment by Dynarrhian** [comment]
I'm using InfernalMobs which displays the health of a mob in a scoreboard. Well, looks like that's the reason...is there any chance to somehow hook into InfernalMobs or do I have to disable scoreboards for InfernalMobs completely?

**Comment by EvilOlaf** [comment]
After a few seconds reviewing: `showHealthOnScoreBoard: true` try set this to `false`.
For further support you should ask the developer of InfernalMobs  directly.

**Comment by Dynarrhian** [comment]
Yup, will do so.
Thanks for your help!
