### ISSUE TITLE
Herbalism Suggestion

### ISSUE THREAD

**Issue by EldestSaber** [mcMMO-Dev/mcMMO#2748]
Hi there, I've been playing on McMMO servers a lot, and I have always wondered why bonemealing crops doesn't give herbalism experience. As you upgrade your herbalism, I think it'd be cool to decrease the amount of bonemeal it takes to grow a certain crop, and it could be scaled to each level of herbalism. Thanks!

**Comment by Tslat** [comment]
There's really not much to scale, since a relatively small chance you'll fail anyway

**Comment by t00thpick1** [comment]
Unfortuanently we don't have the capability of storing that kinda data on it.  We have a boolean for EXP or NO EXP, and nothing else can be persisted.   So there is not really a good way to do this without either: 
A: Ballooning our storage with more metadata
B: Forgetting all bonemeal metadata every server restart and not awarding those ones any exp
C: Forgetting all bonemeal metadata every server restart and awarding those ones full exp
