### ISSUE TITLE
Error: "Invalid class () detected for"

### ISSUE THREAD

**Issue by KruhlSentru** [mcMMO-Dev/mcMMO#2749]
I've been working on setting up a Cauldron server, which includes both mcMMO and Thaumcraft.  I've finally filled in the necessary data for the various files in the mods folder, but I keep getting this error:

[16:44:52] [Server thread/WARN]: [mcMMO] Invalid class () detected for THAUMCRAFT_TAINTEDCREEPER.

The same error is also applied for every other creature.  I don't see any class listed to edit in the entities.default.yml file.  I am using version 1.7.10, so it's possible this is an error that is fixed in later versions, which, unfortunately, would be incompatible with many of my mods/plugins.  Below is an example of how I've written these creatures out, in case there's some simple error I've made:

THAUMCRAFT_TAINTEDCREEPER:
  XP_Multiplier: 4.0
  Tameable: false
  Taming_XP: 0
  CanBeSummoned: false
  COTW_Material: ''
  COTW_Material_Data: 0
  COTW_Material_Amount: 0

If this error doesn't really do anything to the game, please let me know.  I know some errors are superficial, but I want to make sure this doesn't mean you can't, for example, get xp from attacking the thaumcraft mobs.

In any case, thanks for your help, and for the great plugin.

**Comment by t00thpick1** [comment]
Ok so the name of the section(in this case THAUMCRAFT_TAINTEDCREEPER)  has to be the name of the entity class for that creature.  You will need to check into your thaumcraft mod and find out the classnames for the entities
