### ISSUE TITLE
Bug priority for other plugins.

### ISSUE THREAD

**Issue by voodootje0** [mcMMO-Dev/mcMMO#2752]
I'm using autosell (premium plugin) with blocks to inventory enabled and I have enabled mod blocks for items with <item;data>. I have send the developer of autosell a message that he needs to fix the problem, he said he can't fix it because the priority event is wrong. Can you please fix the priority problem? 
- voodootje0

**Comment by t00thpick1** [comment]
I have no idea what you are asking.
