### ISSUE TITLE
Backend Conversion

### ISSUE THREAD

**Issue by Kilovice** [mcMMO-Dev/mcMMO#2754]
When doing /mcconvert database sql

Chat returns:
"Starting conversion from SQL to FLATFILE..."
"Database migration complete; the FLATFILE database now has all data from the SQL database."

Along with this, when doing /mcconvert database flatfile

Chat returns:
"You are already using the FLATFILE database!"

I'm 99% sure this is an issue as both are converting to FLATFILE and not from flatfile to mysql.

**Comment by t00thpick1** [comment]
The conversion only moves the data from the db named,  it does not actually change which db is currently being used, you need to restart the server to be using SQL,  then do /mcconvert database flatfile  which will take all the flatfile data and put it into the SQL db
