### ISSUE TITLE
Scoreboard issue

### ISSUE THREAD

**Issue by MarkElf** [mcMMO-Dev/mcMMO#2757]
Console is being spammed by errors. http://pastebin.com/N5mJ47b5

Also posted this on spigot with no response: 

"When running /mctop I obtain the following message, could this be tied to mcmmo in any way, or is it an outside plugin?

https://proxy.spigotmc.org/cf6eb3bcba0f5f90b5a34497bb9e6592118f20ba?url=http%3A%2F%2Fprntscr.com%2F9qp06s%2Fdirect

Edit: Ran into this error while using /mining

http://pastebin.com/nYVfBpjt"

**Comment by EvilOlaf** [comment]
Do you use other plugins using the scoreboard?

**Comment by MarkElf** [comment]
I don't believe so as KoTH's and Factionsuuid's are both disabled. Plugin list: http://prntscr.com/9swcq2

**Comment by MarkElf** [comment]
It seems there is now a startup error: http://pastebin.com/mLshnq0w

**Comment by EvilOlaf** [comment]
Seems like something is wrong with you parties. I'm on my cell phone so I cannot check. Is 82 the latest available build on Jenkins CI? If not try to update.

**Comment by MarkElf** [comment]
I am running build 82, I reset the files and that seems to have resolved the issue, thank you for your time.
