### ISSUE TITLE
Feature Request: Action Bar Notifications

### ISSUE THREAD

**Issue by EnderSandman** [mcMMO-Dev/mcMMO#2759]
It would be nice if there was a config item that would specify if the notifications are to appear in the chat as they do now or if they are to appear above the action bar.

**Comment by MarkElf** [comment]
Please learn to Google things.

https://www.spigotmc.org/resources/mcmmoaction.17261/

**Comment by EnderSandman** [comment]
I do google things and try not to waste people's time and I still get smarted off. I have tried this plugin and it has problems and screws up the chat.  So just forget it.

**Comment by games647** [comment]
@EnderSandman Do you still have these issues? I tried to fix them with the version 0.2.4. Relevant ticket games647/mcMMOAction#3

**Comment by EnderSandman** [comment]
yes they were resolved and I was able to use mcMMOAction plugin.  It works very well. Thanls for checking up on this ticket.
