### ISSUE TITLE
Suggestion on Minecraft Wither

### ISSUE THREAD

**Issue by XoXKittyXoX** [mcMMO-Dev/mcMMO#2760]
I see that every mob in minecraft has a mcMMO boost up, such as Sheeps, Creepers, Etc. but I've noticed that The Wither doesn't give you any upgrades. Now seeing as many players tend to fight withers for Mob Drops to sell at Shops on popular and famous servers, This is a small issue. So i simply suggest that you put mcMMO Upgrades (Such as Archery, Swords, Acrobatic's. ETC.) on this wither, due to many people fighting them often. thanks for reading my comment :+1: :)

**Comment by Tslat** [comment]
What do you mean?
Withers are affected by skills just like any other

**Comment by XoXKittyXoX** [comment]
No, i meant. Withers do get affected by mcMMO, but with how many times i've
seen people fight withers with mcMMO mods they don't gain more skills
whatsoever from them.

**Comment by t00thpick1** [comment]
Thats a configuration issue not on us.
