### ISSUE TITLE
Lag by Player Join Event

### ISSUE THREAD

**Issue by Briareos82** [mcMMO-Dev/mcMMO#2762]
Hello, we get laags for seconds by a Player Join Event

Configuration:

Bungeecort Network with 17 Servers, all Servers are on Spigot 1.8.0
MCMMO ist configured with MySQL options

MySQL:
    Enabled: true
    Database:
        User_Name: ********
        User_Password: *********
        Name: mcglobal
        TablePrefix: mcmmo_
        # This setting is the max simultaneous mysql connections allowed at a time, needs to be
        # high enough to support multiple player logins in quick succession
        MaxConnections:
            Misc: 300
            Load: 300
            Save: 300
        # This setting is the max size of the pool of cached connections that we hold available
        # at any given time
        MaxPoolSize:
            Misc: 100
            Load: 200
            Save: 200
    Server:
        Port: 3306
        Address: localhost
# 

Could somone Help me pls?

Briareos82

**Comment by EvilOlaf** [comment]
Try lowering your SQL connections to default. Having a too high number of simultaneously connections can be counter-effective.

**Comment by Briareos82** [comment]
I have it same Problem when Player join the Server it will hang up to 4 seconds

**Comment by EvilOlaf** [comment]
Do you use mysql backend too?

**Comment by Briareos82** [comment]
no i should do?

**Comment by EvilOlaf** [comment]
I'm sorry for the misapprehension, I just read your 2nd post earlier on phone and thought you were someone else who has the same issue. 

Do you use the latest available dev build from CI (build 82)?
Do you consider upgrading Spigot to at least 1.8.4 or latest 1.8.8 as earlier versions also have security flaws?
Did you try to not use mysql for mcMMO? For example I have up to 80 players on one server and mcMMO is somewhere at the bottom in my timings. So no load/issues from it at all.

**Comment by Briareos82** [comment]
the problem is that we need mysql because we use mcmmo on 7 Server at same time

**Comment by Briareos82** [comment]
we have the same problem on 1.84 and 1.8.8

**Comment by t00thpick1** [comment]
Can I see your timings report?
