### ISSUE TITLE
How do i get version 1.7.10 of MCMMO?

### ISSUE THREAD

**Issue by drumerpunk1** [mcMMO-Dev/mcMMO#2767]
Can someone help me out with this? I can't find the right version for my server. Is there a version 1.7.10?

**Comment by Tslat** [comment]
The plugin is now a paid plugin.
You can get the files by supporting the project:
https://www.spigotmc.org/resources/mcmmo.2445/

**Comment by t00thpick1** [comment]
You might be able to find an old copy somewhere, otherwise you can just compile off the old commit history for yourself.
