### ISSUE TITLE
Unarmed skill triggering while unnessery

### ISSUE THREAD

**Issue by kobini2** [mcMMO-Dev/mcMMO#2771]
Hello,

I just found a bug, when I don't have any items in my hand and I rightclick a fence to open it I get the message for the skill.
I hope you'll fix it.

**Comment by Tslat** [comment]
This isn't a bug, it's intentional.

When you right click on a block while holding no items, your unarmed will activate

**Comment by kobini2** [comment]
I do get it's intentional.

But I don't think its needed/wanted if you want to open a fence gate or something

**Comment by t00thpick1** [comment]
Action blocks like fences should be on the blacklist,  what block exactly did you click?

**Comment by Tslat** [comment]
@t00thpick1 
Here:
https://github.com/mcMMO-Dev/mcMMO/pull/2783/commits
