### ISSUE TITLE
mcMMO commands unresponsive in KCauldron

### ISSUE THREAD

**Issue by clive9455** [mcMMO-Dev/mcMMO#2774]
I have searched all sites i can find showing similar issues for what seems like an eternity, tried all suggestions and nothing has solved my problem, i am running a server using KCauldron 1.7.10 and mcMMO 1.5.04 SNAPSHOT b85 installed (have also tried A LOT of different versions) but when i try using mcmmo commands in game i get no response, other than "22.02 11:14:53 [Server] INFO clive9455 issued server command: /mcscoreboard" in the servers console, only thing that shows for mcmmo in the console is "22.02 11:02:30 [Server] INFO [mcMMO] Loading mcMMO v1.5.04-SNAPSHOT-b85"
Here is the full log from the console: http://pastebin.com/KU1Yv79d
Thanks in advance for any help.

Edit: Now im getting this instead http://pastebin.com/cmyUUd3g
Is there anywhere i can manually download the configs for this version so i can try that?
Sorry about all the edits but ive just looked through, it seems that the problem is that it is looking for yml files in plugins/mcMMO rather than plugins/mcMMO/src/resources, is there a known fix to this?

**Comment by ZombieHDGaming** [comment]
Clive, I hate to be the one to tell you this, but you should never put trust in putting a Bukkit/Spigot plugin into a modified server, such as KCauldron. Most of those servers have new protocols, and Forge options, that need to be added to the plugin, so it can work properly. For a plugin such as McMMO, it's either a hit or miss to get it to work.

I would recommend using the 1.5.00 release for your server, seeing as, by the looks of things, anything at or above 1.5.01 is a Minecraft 1.8 build. And don't quote me on this, but theoretically, if you downgrade, it MAY work. Like I said, KCauldron and normal plugins are hit and miss. But, if you really need this, I would recommend finding a developer that could modify this to make the plugin work on KCauldron (And yes, there are devs that do this, and make KCauldron/Cauldron/etc. plugins, I saw one last week).

**Comment by clive9455** [comment]
Ok thanks for the info, ill extract the jar and poke around to see if I can
get it going, if not ill try to find someone more experienced, thanks for
the help
