### ISSUE TITLE
mcMMO ERROR on enable and disable

### ISSUE THREAD

**Issue by kretowicz14** [mcMMO-Dev/mcMMO#2777]
KCuldron with FTB Infinity Evolved
Here is log:

> [12:50:14] [Server thread/INFO]: [mcMMO] Enabling mcMMO v1.5.00-b3547
> [12:50:15] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
> [12:50:15] [Server thread/WARN]: java.lang.NullPointerException
> [12:50:15] [Server thread/WARN]: 	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:243)
> [12:50:15] [Server thread/WARN]: 	at net.minecraft.item.crafting.ShapedRecipes.toBukkitRecipe(ShapedRecipes.java:91)
> [12:50:15] [Server thread/WARN]: 	at net.minecraft.item.crafting.ShapedRecipes.toBukkitRecipe(ShapedRecipes.java:13)
> [12:50:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.inventory.RecipeIterator.next(RecipeIterator.java:32)
> [12:50:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.inventory.RecipeIterator.next(RecipeIterator.java:10)
> [12:50:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.getRecipesFor(CraftServer.java:1120)
> [12:50:15] [Server thread/WARN]: 	at com.gmail.nossr50.skills.repair.Repair.getRepairAndSalvageQuantities(Repair.java:85)
> [12:50:15] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.repair.RepairConfig.loadKeys(RepairConfig.java:139)
> [12:50:15] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.repair.RepairConfig.<init>(RepairConfig.java:24)
> [12:50:15] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.repair.RepairConfigManager.<init>(RepairConfigManager.java:34)
> [12:50:15] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:424)
> [12:50:15] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:134)
> [12:50:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
> [12:50:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
> [12:50:15] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
> [12:50:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415)
> [12:50:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349)
> [12:50:15] [Server thread/WARN]: 	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462)
> [12:50:15] [Server thread/WARN]: 	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:137)
> [12:50:15] [Server thread/WARN]: 	at net.minecraft.world.World.<init>(World.java:360)
> [12:50:15] [Server thread/WARN]: 	at net.minecraft.world.WorldServer.<init>(WorldServer.java:160)
> [12:50:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:367)
> [12:50:15] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
> [12:50:15] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
> [12:50:15] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
> [12:50:15] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.5.00-b3547
> [12:50:15] [Server thread/ERROR]: Error occurred while disabling mcMMO v1.5.00-b3547 (Is it up to date?)
> java.lang.ExceptionInInitializerError
> 	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:206) ~[?:?]
> 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:318) ~[JavaPlugin.class:1.7.10-R0.1-SNAPSHOT]
> 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:392) [JavaPluginLoader.class:1.7.10-R0.1-SNAPSHOT]
> 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:429) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
> 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:193) [mcMMO_1.5.00.jar:?]
> 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) [JavaPlugin.class:1.7.10-R0.1-SNAPSHOT]
> 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-R0.1-SNAPSHOT]
> 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
> 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
> 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
> 	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462) [ayq.class:?]
> 	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:137) [ayq.class:?]
> 	at net.minecraft.world.World.<init>(World.java:360) [ahb.class:?]
> 	at net.minecraft.world.WorldServer.<init>(WorldServer.java:160) [mt.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:367) [MinecraftServer.class:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
> Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
> 	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_72]
> 	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_72]
> 	at org.bukkit.craftbukkit.v1_7_R4.CraftOfflinePlayer.<init>(CraftOfflinePlayer.java:35) ~[CraftOfflinePlayer.class:1.7.10-R0.1-SNAPSHOT]
> 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.getOfflinePlayer(CraftServer.java:1302) ~[CraftServer.class:1.7.10-R0.1-SNAPSHOT]
> 	at com.gmail.nossr50.util.scoreboards.ScoreboardManager.getOfflinePlayer(ScoreboardManager.java:133) ~[?:?]
> 	at com.gmail.nossr50.util.scoreboards.ScoreboardManager.getOfflinePlayer(ScoreboardManager.java:121) ~[?:?]
> 	at com.gmail.nossr50.util.scoreboards.ScoreboardManager.<clinit>(ScoreboardManager.java:43) ~[?:?]
> 	... 18 more

**Comment by t00thpick1** [comment]
Cannot fix on my end, its a problem with a mod item.
