### ISSUE TITLE
[1.9] Brewing Strength potion creates Water Bottles?

### ISSUE THREAD

**Issue by jpmac26** [mcMMO-Dev/mcMMO#2778]
I'm not sure if this is a bug due to the 1.9 update, but when you brew a Blaze Powder into Awkward potions, instead of giving you 3 Strength Potions, it gives you 3 Water Bottles. I have tried using Awkward Potions which were brewed in both 1.8.8 and 1.9, and neither works correctly.

**Comment by t00thpick1** [comment]
Alchemy is not yet functional in 1.9
