### ISSUE TITLE
Could not pass event PotionSplashEvent to mcMMO v1.5.04-SNAPSHOT-b92

### ISSUE THREAD

**Issue by dumptruckman** [mcMMO-Dev/mcMMO#2779]
Except as stated in title. Full stack trace here: http://hastebin.com/xegigomice.avrasm (looks like 2 events)

I don't have much context for when this happened but I might speculate that it is due to the new AoE potions maybe (I know people had been playing with those...)

Spigot version at time of creating this issue is 33 builds behind. (git-Spigot-1a196e1-92602ad) I have updated and realize it could be a spigot issue that has since been resolved. I will post back if I see it is still happening.

**Comment by t00thpick1** [comment]
Working on fixing this on spigot side.
