### ISSUE TITLE
"Mcconvert experience" generates an out of bounds exception

### ISSUE THREAD

**Issue by BornToDoStuff** [mcMMO-Dev/mcMMO#2780]
**Error:**
04.03 20:52:58 [Server] INFO at java.util.Collections$EmptyList.get(Unknown Source) ~[?:1.8.0_60]
04.03 20:52:58 [Server] INFO java.lang.IndexOutOfBoundsException: Index: 0
04.03 20:52:58 [Server] WARN [mcMMO] Task #447 for mcMMO v1.5.04-SNAPSHOT-b92 generated an exception

**command used:**
/mcconvert experience exponential
The variable Exp_Modifier was set to 2.875

ingame there is a message given: Starting conversion from UNKNOWN to EXPONENTIAL

converting to LINEAR was also tried but it appears that it is unable to determine what type it is starting from in the first place.

**Full Error Log:**
04.03 20:52:58 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
04.03 20:52:58 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-7d15d07-c194444]
04.03 20:52:58 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot.jar:git-Spigot-7d15d07-c194444]
04.03 20:52:58 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-7d15d07-c194444]
04.03 20:52:58 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:724) [spigot.jar:git-Spigot-7d15d07-c194444]
04.03 20:52:58 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-7d15d07-c194444]
04.03 20:52:58 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-7d15d07-c194444]
04.03 20:52:58 [Server] INFO at com.gmail.nossr50.runnables.database.FormulaConversionTask.run(FormulaConversionTask.java:31) ~[?:?]
04.03 20:52:58 [Server] INFO at com.gmail.nossr50.util.player.UserManager.getOfflinePlayer(UserManager.java:90) ~[?:?]
04.03 20:52:58 [Server] INFO at com.gmail.nossr50.util.player.UserManager.retrieveMcMMOPlayer(UserManager.java:108) ~[?:?]
04.03 20:52:58 [Server] INFO at com.gmail.nossr50.util.player.UserManager.getPlayer(UserManager.java:94) ~[?:?]
04.03 20:52:58 [Server] INFO at java.util.Collections$EmptyList.get(Unknown Source) ~[?:1.8.0_60]
04.03 20:52:58 [Server] INFO java.lang.IndexOutOfBoundsException: Index: 0
04.03 20:52:58 [Server] WARN [mcMMO] Task #447 for mcMMO v1.5.04-SNAPSHOT-b92 generated an exception

**Comment by CorporalBruno** [comment]
saw something similar

**Comment by clovisd** [comment]
Getting the same issue. Would be great if we had an explanation or a fix! ;)
