### ISSUE TITLE
Mcmmo - Repair

### ISSUE THREAD

**Issue by MomaCods** [mcMMO-Dev/mcMMO#2784]
My server is a freshly restarted 1.9 I bought the Mcmmo 2 days ago...

I have used it before and loved it however when trying to repair items on an Iron Block it is taking the supplies ... says it is repairing them even has the "that felt easy" on the screen, it looks like the levels are going up but they arent... and the item never repairs at all... you could click it until your entire stack of supplies is gone and its still broken 

any suggestions?
and this is the error console throws
http://pastebin.com/cX4wrk1F
![screen shot 03-06-16 at 09 03 am](https://cloud.githubusercontent.com/assets/17677132/13554809/9070e920-e37f-11e5-84ed-6f155967ed02.PNG)

**Comment by MomaCods** [comment]
http://pastebin.com/cX4wrk1F

**Comment by EvilOlaf** [comment]
Your version is outdated. Get current dev build here: https://ci.drtshock.net/job/MCMMO

**Comment by MomaCods** [comment]
What? I just bought it 2 days ago on Spigot!

**Comment by t00thpick1** [comment]
@MomaCods As 1.9 support is still only partial, I haven't updated the build on spigot. I want to get it to be FULLY functional on 1.9 before doing so.  RIght now it is just Mostly functional
