### ISSUE TITLE
Mcmmo - Sounds

### ISSUE THREAD

**Issue by MomaCods** [mcMMO-Dev/mcMMO#2785]
Hi ... just wondering if anyone can direct me to where I turn off the level up sounds and the fireworks in mcmmo ... It gives me a headache when repairing items and leveling up I really apreciate it...

I have scoured the config and I dont know where to look

**Comment by MomaCods** [comment]
The sound of the anvil banging is SO loud!!!!! It scares the shit outta me! the only thing i can find in config is the level up sound.... where do i find the option to lower the sound of the repair anvil... I have my game sounds low and still its louder than anything else!!!

**Comment by t00thpick1** [comment]
Hmm, let me add in an option for that real quick

**Comment by t00thpick1** [comment]
Grab the latest dev build and there is now a MasterVolume option in the main config.

**Comment by MomaCods** [comment]
Oh you are a dream boat! thank you from the bottom of my heart.. and my ears thank you! LOL
