### ISSUE TITLE
MySQL / McMMO / 1.9

### ISSUE THREAD

**Issue by Sikatsu** [mcMMO-Dev/mcMMO#2787]
Everytime I restart my server my config seems to be reset or something. All the settings are reverted and all the players data is gone.

The only way to fix this is to put my config in before I restart the server. Using latest mcmmo #95

**Comment by t00thpick1** [comment]
odd.. Can i see a startup log?

**Comment by t00thpick1** [comment]
I think I fixed that just now.

**Comment by Sikatsu** [comment]
I was sleeping, I was unable to send the startup log. I'll test the new update :)
