### ISSUE TITLE
/fishing error

### ISSUE THREAD

**Issue by Toorastic** [mcMMO-Dev/mcMMO#2788]
Every time I do /fishing I get an internal error. The skill itself seems to be working, I can level up and whatnot. But the scoreboard wont come up when doing /fishing. The error I'm getting is as follows.

08.03 00:29:17 [Server] INFO Toorastic issued server command: /fishing
08.03 00:29:17 [Server] ERROR null
08.03 00:29:17 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'fishing' in plugin mcMMO v1.5.04-SNAPSHOT-b82
08.03 00:29:17 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.9.jar:git-Spigot-604e046-69e196f]
08.03 00:29:17 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.jar:git-Spigot-604e046-69e196f]
08.03 00:29:17 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.9.jar:git-Spigot-604e046-69e196f]
08.03 00:29:17 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1302) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
08.03 00:29:17 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1137) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
08.03 00:29:17 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
08.03 00:29:17 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
08.03 00:29:17 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
08.03 00:29:17 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
08.03 00:29:17 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
08.03 00:29:17 [Server] INFO at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
08.03 00:29:17 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:716) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
08.03 00:29:17 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
08.03 00:29:17 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
08.03 00:29:17 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
08.03 00:29:17 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
08.03 00:29:17 [Server] INFO Caused by: java.lang.NoSuchFieldError: TAIGA_MOUNTAINS
08.03 00:29:17 [Server] INFO at com.gmail.nossr50.skills.fishing.Fishing.<clinit>(Fishing.java:61) ~[?:?]
08.03 00:29:17 [Server] INFO at com.gmail.nossr50.commands.skills.FishingCommand.dataCalculations(FishingCommand.java:88) ~[?:?]
08.03 00:29:17 [Server] INFO at com.gmail.nossr50.commands.skills.SkillCommand.onCommand(SkillCommand.java:65) ~[?:?]
08.03 00:29:17 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.9.jar:git-Spigot-604e046-69e196f]
08.03 00:29:17 [Server] INFO ... 15 more

**Comment by t00thpick1** [comment]
Update mcMMO, this has been fixed
