### ISSUE TITLE
1.9 changes

### ISSUE THREAD

**Issue by Vinomadd** [mcMMO-Dev/mcMMO#2789]
1.9 has broken the functionality of McMMO.

It needs to be reconfigured to allow a differen't button press other than right click to enable the secondary features of various weapons and tools. 

I don't need gigadrill active every time I'm trying to make grass paths. I need to be able to use my shield without activating skullsplitter, etc.

**Comment by DorCoMaNdO** [comment]
You can enable "Only_Activate_When_Sneaking" in the config

**Comment by t00thpick1** [comment]
Should be fixed

**Comment by Vinomadd** [comment]
This is not acceptible. We need more options that this.

**Comment by DorCoMaNdO** [comment]
The possibilities are very limited, we do not receive any data about which keys you're pressing, we get information about actions you're doing.

Anyway, this was changed, by default you need to press only right click, like it has always been, but if you're using the offhand and you're not in a vehicle (boat, minecart, horse, etc) then you have to sneak and right click.

**Comment by t00thpick1** [comment]
@Vinomadd If you can implement another option that works, be my guest, unfortunately minecraft 1.9 has left me with none but this.
