### ISSUE TITLE
Recurring server error MCMMO 1.5.04 snapshot

### ISSUE THREAD

**Issue by PippaSmith** [mcMMO-Dev/mcMMO#2791]
Hi, I'm getting this error recurringly. Is it important?
I'm running latest spigot.
08.03 05:34:26 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
08.03 05:34:26 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
08.03 05:34:26 [Server] INFO at com.gmail.nossr50.metrics.mcstats.Metrics$1.run(Metrics.java:353)
08.03 05:34:26 [Server] INFO at com.gmail.nossr50.metrics.mcstats.Metrics.access$500(Metrics.java:45)
08.03 05:34:26 [Server] INFO at com.gmail.nossr50.metrics.mcstats.Metrics.postPlugin(Metrics.java:502)
08.03 05:34:26 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
08.03 05:34:26 [Server] INFO at java.lang.Thread.run(Thread.java:745)
08.03 05:34:26 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
08.03 05:34:26 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
08.03 05:34:26 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
08.03 05:34:26 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin mcMMO v1.5.04-SNAPSHOT-b82 generated an exception while executing task 10
08.03 05:34:26 [Server] INFO ... 3 more
08.03 05:34:26 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
08.03 05:34:26 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
08.03 05:34:26 [Server] INFO at com.gmail.nossr50.metrics.mcstats.Metrics$1.run(Metrics.java:353)
08.03 05:34:26 [Server] INFO at com.gmail.nossr50.metrics.mcstats.Metrics.access$500(Metrics.java:45)
08.03 05:34:26 [Server] INFO at com.gmail.nossr50.metrics.mcstats.Metrics.postPlugin(Metrics.java:502)
08.03 05:34:26 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
08.03 05:34:26 [Server] INFO at java.lang.Thread.run(Thread.java:745)
08.03 05:34:26 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
08.03 05:34:26 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
08.03 05:34:26 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
08.03 05:34:26 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin EMetrics v0.0.4 generated an exception while executing task 9
08.03 05:34:26 [Server] WARN Exception in thread "Craft Scheduler Thread - 132" 
08.03 05:34:26 [Server] WARN Exception in thread "Craft Scheduler Thread - 130"

**Comment by t00thpick1** [comment]
Your mcMMO build is ancient
