### ISSUE TITLE
Pvp Bug

### ISSUE THREAD

**Issue by dazhawk12** [mcMMO-Dev/mcMMO#2793]
I am Running the latest version of mcmmo and craftbukkit 1.8.8 and there is a peculiar bug where for some reason, mcmmo is disabling pvp, I have plugman installed and when I disable it, pvp returns to normal.

The other problem is that It doesn't say anything in to console, please fix this issue

**Comment by t00thpick1** [comment]
Cannot do anything with the little information.

**Comment by alnoise** [comment]
Having the exact same problem.
