### ISSUE TITLE
Auto brewing with mcmmo

### ISSUE THREAD

**Issue by japtic** [mcMMO-Dev/mcMMO#2794]
so i found out today that the ingredient from mcmmo [carrots for example] does not work on auto brewing stand.  at this point i really dont care about the xp but i want to brew the potions automatically.  the brewing stand would not accept the carrots when using hopper to put them in. also it seems like they do not work when placing carrots in the brewing stand and adding awkward potions in with hoppers.  its either i manual place carrot/at least one bottle in the brewing stand to get it work for each brewing.

i personally dont know if this was fixed in 1.8 since i havent used it yet. (server is still 1.7) I am sorry if this was already viewed and fixed/add .  thank you for reading.

**Comment by t00thpick1** [comment]
Sorry I don't support 1.7 :(
