### ISSUE TITLE
Is it possible to add mending to treasure.yml Spigot 1.9

### ISSUE THREAD

**Issue by TechManDylan** [mcMMO-Dev/mcMMO#2798]
Basically what the title says I tried adding it to the common enchants on the list for fishing and increased probability but have yet to see it while testing with an auto Fisher curious if it is even possible right now or it just passes it over because it is not currently a valid enchantment.

Edit: It might also help to mention I am on 1.5.04-SNAPSHOT-b96 edited title as well.

**Comment by t00thpick1** [comment]
Fixed
