### ISSUE TITLE
java.lang.NoSuchFieldError: MENDING

### ISSUE THREAD

**Issue by Scrity1976** [mcMMO-Dev/mcMMO#2809]
spigot-1.8.8-R0.1-SNAPSHOT
mcMMO v1.5.04-SNAPSHOT-b110

http://pastebin.com/0wr71xWH

**Comment by t00thpick1** [comment]
We have moved to 1.9 compat, sorry :(

**Comment by Jawakotb** [comment]
t00thpick1,  Do you mean that if we see this error, we are not on 1.9?   I am seeing the same "NoSuchFieldError: MENDING" with the latest build of Spigot. I also noticed two errors stating that experience.yml and repair.vanilla.yml files are missing and when I check the dir, they are indeed not there.  

git-Spigot-ee4e41a-ea28c1e (MC: 1.9)
1.9-R0.1-SNAPSHOT
mcMMO v1.5.04-SNAPSHOT-b115  (and b116)

Running Oracle Java 1.8.0_74 on Ubunut 15.10

I del'd the directories, recopied jar and restarted server..several times....no files appear with those names and I still see the same "MENDING" error in console disabling MCMMO.

Thanks!
((Sorry for posting on a closed ticket, but wanted information prior to opening up a new issue, Hope I am not violating any rules))
