### ISSUE TITLE
Party chat socialspy?

### ISSUE THREAD

**Issue by Sikatsu** [mcMMO-Dev/mcMMO#2811]
Is there anyway to enable socialspy for the party chat? Or could you create one?

**Comment by TheChampTF** [comment]
Used to be one http://dev.bukkit.org/bukkit-plugins/mcmmopa/ , but not seen it updated for some time.

**Comment by NoChanceSD** [comment]
That would be nice, also admins being able to move players between parties,

**Comment by Sikatsu** [comment]
Hope they can just integrate it :s

**Comment by Momshroom** [comment]
the mcmmo party spy plugin seems to have stopped working (at least on our server) with the newest mcmmo update/1.9.

**Comment by t00thpick1** [comment]
@Momshroom Is it having errors or?  it would be much easier for me to just push out a quick update to that plugin than to integrate it.

**Comment by Momshroom** [comment]
Yes, it was spamming errors.  I'll reinstall it and post them for you.  Thanks!

**Comment by Sikatsu** [comment]
Integrating would be nicer then having to use an extra plugin for it tho

**Comment by Momshroom** [comment]
Here's the error we see when someone talks in party chat:
http://pastebin.com/4PbhjzUW

**Comment by Sikatsu** [comment]
@t00thpick1

There just was a quite big group going on in party chat which went up in advertising. Could you really not just integrate it instead of an individual plugin?

**Comment by Momshroom** [comment]
@t00thpick1 Sorry to bother you, but any chance we could get an update to mcmmo party spy?

**Comment by Sikatsu** [comment]
I'm still hoping for that too.
