### ISSUE TITLE
Older versions download

### ISSUE THREAD

**Issue by Fedozzo** [mcMMO-Dev/mcMMO#2812]
Where can I find the download of older versions?
In particular I need the 1.5.02, It's still available somewhere?

Thank you

**Comment by ElnanMillstone** [comment]
A 1.8 version would be appreciated as well.

**Comment by ElnanMillstone** [comment]
I believe this is a 1.8 version of mcmmo, it works on 1.8.8 spigot so...
[mcMMO.zip](https://github.com/mcMMO-Dev/mcMMO/files/201537/mcMMO.zip)

**Comment by t00thpick1** [comment]
Links to official builds can be found on the spigot page, you should only trust builds from that page and my CI

**Comment by ElnanMillstone** [comment]
Jenkins doesn't have 1.8 afaik

**Comment by ElnanMillstone** [comment]
Ignore that comment ^

**Comment by Fedozzo** [comment]
I tryed but I'm still unable to download the specific 1.5.02 version. Anyway I no more need it, I risigned using the last update :P 
I would thank you for the great job you're doing! Thank you to all! Bye
