### ISSUE TITLE
Error on enable

### ISSUE THREAD

**Issue by HollishKid** [mcMMO-Dev/mcMMO#2815]
Hello,

I get the following error, making mcMMO crash entirely on server start up:
http://pastebin.com/FMumUQW0

Any ideas on this?

**Comment by DorCoMaNdO** [comment]
mcMMO only supports the latest version of minecraft, that being 1.9 as of right now.

**Comment by RagingThunder28** [comment]
Had same problem, Updated McMMO to build 116 and spigot to Build 695, and deleted treasures file. Problem solved.

**Comment by HollishKid** [comment]
Thanks for your responses!
I followed advice and upgraded to 1.9
Still, I get the following error:

http://pastebin.com/RnzDJ4dE

**Comment by HenrikoMagnifico** [comment]
I'm currently having the exact same issue, I don't think mcmmo works for 1.9 right now. :P

**Comment by HenrikoMagnifico** [comment]
It works for me, just update to the latest version of Spigot

**Comment by DorCoMaNdO** [comment]
Remove the mcMMO configs and restart the server.

**Comment by HollishKid** [comment]
@DorCoMaNdO 
This seems to have worked!

Thanks for your help!
