### ISSUE TITLE
Update Locales

### ISSUE THREAD

**Issue by HollishKid** [mcMMO-Dev/mcMMO#2819]
Hello,

I got the latest version of mcmmo up and running. Thanks to your previous advice. Nevertheless, it seems that the locales are not updated. 
I have contributed to the French translation (https://www.getlocalization.com/mcmmo/) which is done now.

Could you update this please?

Thanks!

**Comment by t00thpick1** [comment]
OMG I forgot about that site.

**Comment by HollishKid** [comment]
Is that a yes ? ^^

**Comment by t00thpick1** [comment]
I gotta figure out our login info

**Comment by HollishKid** [comment]
Ok, please keep me posted on this, I spent some serious time on these translations and undoing the horrors some people considered as french langage ...

Thanks in advance ^^

**Comment by t00thpick1** [comment]
Worst case you can just send me the translations directly :P

**Comment by HollishKid** [comment]
They're all on that site, the interface made things easier I must admit, I have no idea how to export everything from there ...

**Comment by t00thpick1** [comment]
Working on getting the login info.
