### ISSUE TITLE
Dupe Fix

### ISSUE THREAD

**Issue by ChibbyHD** [mcMMO-Dev/mcMMO#2821]
Here is a video showing the dupe in action.
https://www.youtube.com/watch?v=fqUXNT_YW7g

A fix to this could be.. Not changing any ORE data when being pushed by a piston.

Meaning, keeping in memory that the player placed that block. (Cache or whatever)

or

Making it so ORE can't be pushed by a piston.

Etc.

I am sure there are several ways to fix this issue, and if you could sometime implement a fix I would very much appreciate that!

If it's already fixed and I am just being silly, then no harm done. Just close the thread if so (:

Thanks,
Shane.

**Comment by ChibbyHD** [comment]
You could say "Use another plugin to fix" or "fix it yourself"

But why should we, the users of McMMO, have to use another plugin to fix a glitch caused by McMMO when you, the developer of McMMO, could just fix it yourself and not make us, the users, need another plugin.

**Comment by t00thpick1** [comment]
This has been fixed for many many builds.  Update your mcMMO

**Comment by ChibbyHD** [comment]
I have updated my McMMO just wasn't sure if it was indeed fixed.
