### ISSUE TITLE
Error on startup, plugin does not enable

### ISSUE THREAD

**Issue by ElnanMillstone** [mcMMO-Dev/mcMMO#2822]
So I'm using build v1.5.04-SNAPSHOT-b116 of mcmmo and using MC 1.8.8 spigot on my server.  When I start my server it generates an error saying there are missing files.  I have tried deleting the mcMMO file in the directory and regenerating it but it still does not make them.  Here is a log of the error:

http://pastebin.com/ZsP9xnCA

Here is also a list of my current plugins:
Plugins (36): CoreProtect, WorldEdit, GameModeInventories, Essentials, GroupManager, ClearLag, CrackShot, Chairs, Lockette, Votifier, Multiverse-Core, WorldGuard, ProtocolLib, NoCheatPlus, RadioBeacon, EssentialsChat, EchoPet, StatusSign, mcMMO, Multiverse-Portals, SimpleVoteListener, RacesAndClasses, EssentialsSpawn, MassiveCore, MassiveTickets, HolographicDisplays, Vault, EnjinMinecraftPlugin, ChestShop, Herochat, CommandSigns, Citizens, Factions, MythicMobs, Autorank, BetonQuest

**Comment by t00thpick1** [comment]
Newer builds are 1.9 only :(

**Comment by ElnanMillstone** [comment]
What build is 1.8 then?

**Comment by t00thpick1** [comment]
uhh, anything built before march.  although the Ci recently dropped our old builds..  You can grab the last build on the spigot page?

**Comment by ElnanMillstone** [comment]
I'll just look on Jenkins, see if I can find one.

**Comment by ElnanMillstone** [comment]
Seems Jenkins only has build 96 and up which is 1.9, any chance of you being able to upload/give me a 1.8 jar?
