### ISSUE TITLE
Mcmmo Minecraft 1.9 yeah same old problem different person sorry

### ISSUE THREAD

**Issue by GothCartel** [mcMMO-Dev/mcMMO#2825]
Hi guys and girls

I am pretty new to mcmmo Ive run vanilla servers and modded servers in the past with no probs but this one is really stumping me.

I have seen mcmmo running on 1.9 servers, plenty of YT vids about and yes there are some glitches I know but for some reason I cannot get any commands to work, the world is stable no issues there, running the latest versions available on craftbukkit on mcprohosting but I cannot get any command to work. eg /mcstats you type it in and nothing happens no error code for a command but nothing shows up on screen. Also it appears that levels may not be being given but I don't know as we cant check them.

Any ideas?

Regards

Goth_Cartel

**Comment by EvilOlaf** [comment]
Check your startup log if mcMMO has been enabled at all.

**Comment by GothCartel** [comment]
It lists all the commands in game when you /help but I will have another look

**Comment by GothCartel** [comment]
Update after the 10th restart of the server for some unknown reason it works :S gg to Me, but thanks for the advice EvilOlaf, much appreciated, alas the alchemy part of it doesn't work as its failing to load but hey ho..

**Comment by Kamisaji** [comment]
so i had the same problem, ive restarted numerous times.  i checked the log and this is what it says when enabling mcmmo...help plz :(

16.03 13:19:54 [Server] ERROR Error occurred while disabling mcMMO v1.5.00-b3547 (Is it up to date?)
16.03 13:19:54 [Server] INFO Disabling mcMMO v1.5.00-b3547
16.03 13:19:54 [Server] WARN at java.lang.Thread.run(Unknown Source)
16.03 13:19:54 [Server] WARN at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:506)
16.03 13:19:54 [Server] WARN at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:182)
16.03 13:19:54 [Server] WARN at net.minecraft.server.v1_9_R1.DedicatedPlayerList.<init>(SourceFile:14)
16.03 13:19:54 [Server] WARN at net.minecraft.server.v1_9_R1.PlayerList.<init>(PlayerList.java:69)
16.03 13:19:54 [Server] WARN at org.bukkit.craftbukkit.v1_9_R1.CraftServer.<init>(CraftServer.java:256)
16.03 13:19:54 [Server] WARN at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:318)
16.03 13:19:54 [Server] WARN at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:346)
16.03 13:19:54 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
16.03 13:19:54 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
16.03 13:19:54 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
16.03 13:19:54 [Server] WARN at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:163)
16.03 13:19:54 [Server] WARN java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
16.03 13:19:54 [Server] ERROR There was an error while enabling mcMMO!
16.03 13:19:53 [Server] INFO Enabling mcMMO v1.5.00-b3547

**Comment by EvilOlaf** [comment]
Update mcMMO.

**Comment by Kamisaji** [comment]
thank you, i saw the version that the server host im using was not the same as the current build, i swapped out the jar and it seems to be working fine, thanks :)
