### ISSUE TITLE
Could not pass event FoodLevelChangeEvent to mcMMO v1.5.04-b123

### ISSUE THREAD

**Issue by SioWolf** [mcMMO-Dev/mcMMO#2830]
Running latest official release of McMMO from spigotmc.org

Running Spigot version git-Spigot-23e921f08b69bdd which was the latest version at the time of this McMMO version being released.

http://pastebin.com/2FE0MZyR

**Comment by t00thpick1** [comment]
Somethings corrupted in your jar, perhaps you replaced the jar while the server was running or somehow otherwise only have some of it, but its missing mcMMO files
