### ISSUE TITLE
Lots of Errors

### ISSUE THREAD

**Issue by SioWolf** [mcMMO-Dev/mcMMO#2832]
You know what? There's a lot of stuff going on here. I'm just going to leave this here.

I did extract the jar, change the language file, and recompile it, but I've done this before and ran it just fine... maybe I messed something up somehow this time around.

Again, Running latest official release of McMMO from spigotmc.org and running Spigot version git-Spigot-23e921f08b69bdd which was the latest version at the time of this McMMO version being released.

[latest.txt](https://github.com/mcMMO-Dev/mcMMO/files/179800/latest.txt)

**Comment by EvilOlaf** [comment]
Try updating Spigot anyways. Might help.

**Comment by t00thpick1** [comment]
Somethings corrupted in the jar as its missing files,  not an issue on our end.
