### ISSUE TITLE
Could not pass event BlockBreakEvent

### ISSUE THREAD

**Issue by CitrusFruit** [mcMMO-Dev/mcMMO#2838]
Getting this error a lot - 
`19.03 08:05:13 [Server] INFO ... 17 more
19.03 08:05:13 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9-6f291ea-55a8535.jar:git-Spigot-6f291ea-55a8535]
19.03 08:05:13 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
19.03 08:05:13 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
19.03 08:05:13 [Server] INFO at sun.reflect.GeneratedMethodAccessor700.invoke(Unknown Source) ~[?:?]
19.03 08:05:13 [Server] INFO at com.gmail.nossr50.listeners.BlockListener.onBlockBreak(BlockListener.java:233) ~[?:?]
19.03 08:05:13 [Server] INFO at com.gmail.nossr50.skills.herbalism.HerbalismManager.herbalismBlockCheck(HerbalismManager.java:151) ~[?:?]
19.03 08:05:13 [Server] INFO at com.gmail.nossr50.skills.herbalism.HerbalismManager.processGreenThumbPlants(HerbalismManager.java:329) ~[?:?]
19.03 08:05:13 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftInventory.contains(CraftInventory.java:132) ~[spigot-1.9-6f291ea-55a8535.jar:git-Spigot-6f291ea-55a8535]
19.03 08:05:13 [Server] INFO at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.9-6f291ea-55a8535.jar:git-Spigot-6f291ea-55a8535]
19.03 08:05:13 [Server] INFO Caused by: java.lang.IllegalArgumentException: Material cannot be null
19.03 08:05:13 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
19.03 08:05:13 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9-6f291ea-55a8535.jar:git-Spigot-6f291ea-55a8535]
19.03 08:05:13 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9-6f291ea-55a8535.jar:git-Spigot-6f291ea-55a8535]
19.03 08:05:13 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9-6f291ea-55a8535.jar:git-Spigot-6f291ea-55a8535]
19.03 08:05:13 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9-6f291ea-55a8535.jar:git-Spigot-6f291ea-55a8535]
19.03 08:05:13 [Server] INFO at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9-6f291ea-55a8535.jar:git-Spigot-6f291ea-55a8535]
19.03 08:05:13 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
19.03 08:05:13 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
19.03 08:05:13 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9-6f291ea-55a8535.jar:git-Spigot-6f291ea-55a8535]
19.03 08:05:13 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.9-6f291ea-55a8535.jar:git-Spigot-6f291ea-55a8535]
19.03 08:05:13 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.9-6f291ea-55a8535.jar:git-Spigot-6f291ea-55a8535]
19.03 08:05:13 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:824) [spigot-1.9-6f291ea-55a8535.jar:git-Spigot-6f291ea-55a8535]
19.03 08:05:13 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:193) [spigot-1.9-6f291ea-55a8535.jar:git-Spigot-6f291ea-55a8535]
19.03 08:05:13 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:292) [spigot-1.9-6f291ea-55a8535.jar:git-Spigot-6f291ea-55a8535]
19.03 08:05:13 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9-6f291ea-55a8535.jar:git-Spigot-6f291ea-55a8535]
19.03 08:05:13 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9-6f291ea-55a8535.jar:git-Spigot-6f291ea-55a8535]
19.03 08:05:13 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9-6f291ea-55a8535.jar:git-Spigot-6f291ea-55a8535]
19.03 08:05:13 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9-6f291ea-55a8535.jar:git-Spigot-6f291ea-55a8535]
19.03 08:05:13 [Server] INFO org.bukkit.event.EventException
19.03 08:05:13 [Server] ERROR Could not pass event BlockBreakEvent to mcMMO v1.5.05-SNAPSHOT-b127`

**Comment by t00thpick1** [comment]
Fixed
