### ISSUE TITLE
Cant load

### ISSUE THREAD

**Issue by Madszinader** [mcMMO-Dev/mcMMO#2839]
The plugin disables itself at startup (Red name in /plugins)
[http://hastebin.com/avefebonul.avrasm](url)

**Comment by Rhmul** [comment]
I am using the latest build (#127) and I also get it disabled.

**Comment by Senofa** [comment]
I too am using the #127 build and it disables at startup. Log entries:

`6:38:30 AM
 mcMMO:
Enabling mcMMO v1.5.05-SNAPSHOT-b127
6:38:30 AM
 CONSOLE:
ERROR]: [mcMMO] There was an error while enabling mcMMO!
6:38:30 AM
 CONSOLE:
WARN]: java.lang.NoSuchFieldError: MENDING
6:38:30 AM
 CONSOLE:
WARN]: at com.gmail.nossr50.util.EnchantmentUtils.<clinit>(EnchantmentUtils.java:34)
6:38:30 AM
 CONSOLE:
WARN]: at com.gmail.nossr50.config.treasure.TreasureConfig.loadEnchantments(TreasureConfig.java:478)
6:38:30 AM
 CONSOLE:
WARN]: at com.gmail.nossr50.config.treasure.TreasureConfig.loadKeys(TreasureConfig.java:135)
6:38:30 AM
 CONSOLE:
WARN]: at com.gmail.nossr50.config.treasure.TreasureConfig.<init>(TreasureConfig.java:76)
6:38:30 AM
 CONSOLE:
WARN]: at com.gmail.nossr50.config.treasure.TreasureConfig.getInstance(TreasureConfig.java:82)
6:38:30 AM
 CONSOLE:
WARN]: at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:403)
6:38:30 AM
 CONSOLE:
WARN]: at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:145)
6:38:30 AM
 CONSOLE:
WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291)
6:38:30 AM
 CONSOLE:
WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
6:38:30 AM
 CONSOLE:
WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
6:38:30 AM
 CONSOLE:
WARN]: at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361)
6:38:30 AM
 CONSOLE:
WARN]: at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321)
6:38:30 AM
 CONSOLE:
WARN]: at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:202)
6:38:30 AM
 CONSOLE:
WARN]: at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:522)
6:38:30 AM
 CONSOLE:
WARN]: at java.lang.Thread.run(Unknown Source)
6:38:30 AM
 mcMMO:
Disabling mcMMO v1.5.05-SNAPSHOT-b127`

**Comment by EvilOlaf** [comment]
Backup your current config and let mcmmo generate a new one. Might help.

**Comment by Senofa** [comment]
Thanks for the comment. I just tried it and I'm getting the same errors, plus one looking for some tables that will be generated later. Any other ideas?

**Comment by Senofa** [comment]
Also, I have run it with no other plugins enabled and still have the same issue.

**Comment by Senofa** [comment]
Could it be a Java 7 thing? My host keeps trying to talk me out of updating to Java 8. Any thoughts?

**Comment by EvilOlaf** [comment]
Will probably not solve your issue but might give a little extra performance in general.

**Comment by t00thpick1** [comment]
Update spigot.
