### ISSUE TITLE
Green Thumb Issue

### ISSUE THREAD

**Issue by ncatania** [mcMMO-Dev/mcMMO#2843]
If you have two seeds min in your inventory, then you can right click cobble stone and the seeds will go down to the negatives to -127 if you fail changing it to moss cobblestone; and then the seeds will go back to positive and keep cycling around until you create mossy cobble stone. Therefore giving you an infinite amount of tries to create mossy cobble from seeds.

**Comment by DorCoMaNdO** [comment]
What version of mcMMO are you using?

**Comment by EvilOlaf** [comment]
Which version of your server software might be interesting as well...

**Comment by cricketcricketcricket** [comment]
spigot 1.9 r1 ... 1.5.04-SNAPSHOT-b92

**Comment by Tslat** [comment]
I submitted a fix for this like 2 weeks ago as a quickfix and Dor cleaned it up afterwards, try redownloading the plugin
