### ISSUE TITLE
is there a 1.7.10 version with the import command?

### ISSUE THREAD

**Issue by jeviuss** [mcMMO-Dev/mcMMO#2844]
Just paid for this on spigot and would like to know if there's a version for 1.7.10 that can import mods. Can't figure out how to add items without it. Thanks!

**Comment by t00thpick1** [comment]
umm.. I think we list the 1.7 version on the page.

**Comment by t00thpick1** [comment]
Oh hmm...  I think we had 1.7 mod support at some point.  Let me see if I can dig up an old jar.  No promises though.

**Comment by jeviuss** [comment]
It's all good man, I got the 1.5.01 jar in and it's working fine! Thanks for checking up on it for me.

Love the mod & keep up the great work!
