### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Sprattle** [mcMMO-Dev/mcMMO#2845]
Downloaded plugin, put onto one of my game servers on my bungeecord network. Does the same thing as 1.8.9 versions when put onto 1.9. Un-responsive and does not do anything when a command is entered? Please help, just paid for this because it is the last plugin that my network needs before I can launch the server. I'm desperate

**Comment by t00thpick1** [comment]
make sure that you have a new copy of spigot/craftbukkit.  what version are you running?

**Comment by ViceCity** [comment]
Having the same problems lad.

**Comment by t00thpick1** [comment]
@ViceCity In that case I have the same exact questions....
