### ISSUE TITLE
Is there a 1.9 release of this?

### ISSUE THREAD

**Issue by jodinar1993** [mcMMO-Dev/mcMMO#2846]
Looking at the update list it looks like there's only a 1.7 release, but I know ofcourse it worked in 1.8.

So I'm wondering if a 1.9 release is out or in the works.

We just recently updated our server to 1.9, and we can still see Power Levels above everyones' heads - however we cannot use any commands or skills.

**Comment by EvilOlaf** [comment]
There is a build for 1.9, but not 100% functional yet.
https://www.spigotmc.org/resources/mcmmo.2445/updates
