### ISSUE TITLE
Salvaging does not yield xp 

### ISSUE THREAD

**Issue by Rowen2003** [mcMMO-Dev/mcMMO#2847]
There are configuration options for the multipliers that salvaging should be using when rewarding xp, but there's no code that actually awards the xp.

**Comment by DorCoMaNdO** [comment]
Salvage is a child skill. Child skills do not have their own experience, the level of child skills is the average of parent skill levels.

**Comment by Rowen2003** [comment]
That's correct. Smelting is also a child skill, and when you smelt stuff, you get xp for mining + repair

**Comment by satelitecraft** [comment]
agree salvaging should gain xp
