### ISSUE TITLE
How do I disable perks?

### ISSUE THREAD

**Issue by zechatron** [mcMMO-Dev/mcMMO#2849]
How do I stop the annoying perk thingy that pops up every time I join my server? It always bugs me...

![82828903f4284c15c1d884b1ff1603c3](https://cloud.githubusercontent.com/assets/17990391/13929945/1526972e-ef73-11e5-910b-58dcbbbb9ce8.png)

Please help! 
Regards~ zechatron

**Comment by EvilOlaf** [comment]
add `-mcmmo.perks.*` to your permissions.

**Comment by zechatron** [comment]
EvilOlaf I am a OP

**Comment by EvilOlaf** [comment]
Remove your op status ^^

**Comment by zechatron** [comment]
Hmm... Thanks.. lol I have another problem you know how to remove the on join thing which says:
![21332f3e10794aff24b5c1253a4d78e3](https://cloud.githubusercontent.com/assets/17990391/13930717/6caba6e4-ef76-11e5-9aea-a857f732915f.png)

**Comment by TheExceed** [comment]
Likely due to you have * permission

**Comment by zechatron** [comment]
* permission?

**Comment by EvilOlaf** [comment]
When you give yourself `*` as permission node, this basically means you gain any available permission node from any plugin. This can also lead to unexpected results or unwanted behavior. Therefore it is recommended, unless you know what you do, to setup a proper permission system and give yourself the permissions you really need only.
On the bottom line it is also a matter of security somehow.

**Comment by zechatron** [comment]
oohhhh! Ty
