### ISSUE TITLE
Doesnt work.

### ISSUE THREAD

**Issue by tobi224c** [mcMMO-Dev/mcMMO#2852]
I bought the plugin so i could use it on my faction server...
Well:
I have added it to a spigot1.8.8 server.

When i type /plugins it displays with red.

Console:
22.03 08:52:55 [Server] ERROR There was an error while enabling mcMMO!
22.03 08:52:55 [Server] WARN java.lang.NoSuchFieldError: MENDING
22.03 08:52:55 [Server] WARN at com.gmail.nossr50.util.EnchantmentUtils.<clinit>(EnchantmentUtils.java:34)
22.03 08:52:55 [Server] WARN at com.gmail.nossr50.config.treasure.TreasureConfig.loadEnchantments(TreasureConfig.java:478)
22.03 08:52:55 [Server] WARN at com.gmail.nossr50.config.treasure.TreasureConfig.loadKeys(TreasureConfig.java:135)
22.03 08:52:55 [Server] WARN at com.gmail.nossr50.config.treasure.TreasureConfig.<init>(TreasureConfig.java:76)
22.03 08:52:55 [Server] WARN at com.gmail.nossr50.config.treasure.TreasureConfig.getInstance(TreasureConfig.java:82)
22.03 08:52:55 [Server] WARN at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:403)
22.03 08:52:55 [Server] WARN at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:145)
22.03 08:52:55 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
22.03 08:52:55 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
22.03 08:52:55 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
22.03 08:52:55 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356)
22.03 08:52:55 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316)
22.03 08:52:55 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:739)
22.03 08:52:55 [Server] WARN at org.bukkit.Bukkit.reload(Bukkit.java:534)
22.03 08:52:55 [Server] WARN at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25)
22.03 08:52:55 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
22.03 08:52:55 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:640)
22.03 08:52:55 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:626)
22.03 08:52:55 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:411)
22.03 08:52:55 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
22.03 08:52:55 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
22.03 08:52:55 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
22.03 08:52:55 [Server] WARN at java.lang.Thread.run(Unknown Source)
22.03 08:52:55 [Server] INFO Disabling mcMMO v1.5.04-b123
22.03 08:52:55 [Server] ERROR Error occurred while disabling mcMMO v1.5.04-b123 (Is it up to date?)

Please tell me what the problem is.

**Comment by EvilOlaf** [comment]
Support für 1.8 has been dropped. Try a older build.

**Comment by t00thpick1** [comment]
Newer builds do not support 1.8, download an older build.
