### ISSUE TITLE
Green Thumb auto-replant doesn't work

### ISSUE THREAD

**Issue by itsmeOli** [mcMMO-Dev/mcMMO#2853]
Hi. On my server, Green Thumb auto-replant doesn't work at all. It worked up until we updated to 1.9; then it stopped working. Sometimes it will randomly start working but then stop working again.

If anyone knows how to fix this, I'd appreciate it. Thanks.

**Comment by ViceCity** [comment]
Doesn't work for me either.

**Comment by Momshroom** [comment]
Replant is not working on ours either for green terra or regular harvesting.   Help would be nice.

**Comment by EvilOlaf** [comment]
Did you upgrade you mcMMO as well?
Grab it here: https://www.spigotmc.org/resources/mcmmo.2445/updates
Also make sure you run a current version of CB/Spigot.

**Comment by Momshroom** [comment]
I can't speak for his/her server, but on ours, yes, mcMMO is upgrated to the beta released on Thursday(1.5.04-b123).   We're running Spigot, (git-Spigot-90839e6-0ff499c)
There are no errors on console or to the player when harvesting.   Herbalism level of test player is 1555, should be getting 100% replant, isn't getting any, with or without green terra.  Tested on potatoes and carrots, with them in inventory

**Comment by Momshroom** [comment]
This is fixed in the new snapshot.  Thank you!
