### ISSUE TITLE
Failure to work

### ISSUE THREAD

**Issue by ViceCity** [mcMMO-Dev/mcMMO#2854]
Running the latest version of Spigot 1.8.8 on my minecraft server, as well as the latest version of ViaVersions. I am running only around 18 other plugins as the server is in development mode. I disabled every single other plugin as well as ViaVersion only to have the plugin still not work which makes absolutely no sense. I as well downgraded the version to see if it being updated for 1.9 would be the problem, so I downgraded and the same problem occurs. 

I paid money for this plugin and wish for it to be fixed. Thank you.

**Comment by t00thpick1** [comment]
The latest builds of mcMMo do not support 1.8,  you can find older builds on our spigot page.

**Comment by ViceCity** [comment]
" I as well downgraded the version to see if it being updated for 1.9 would be the problem, so I downgraded and the same problem occurs." Please read carefully. It still does not work.

**Comment by t00thpick1** [comment]
@ViceCity What version did you downgrade to, whats the errors in your server.log

**Comment by ViceCity** [comment]
I downgraded to the version updated on December 2nd, 2015. No errors occur in console.

**Comment by t00thpick1** [comment]
So whats not working?

**Comment by ViceCity** [comment]
The plugin which you make updates for and charge $10. mcMMO is not working and shows up RED in the plugin list /pl.

**Comment by t00thpick1** [comment]
@ViceCity It would not show up red if there were no errors.  Upload your startup log somewhere.

**Comment by ViceCity** [comment]
Here you go sir: http://pastebin.com/d9Z3GC0f

**Comment by t00thpick1** [comment]
@ViceCity Regenerate your treasures.yml(delete it then re-run the plugin)

**Comment by ViceCity** [comment]
Have done so just now, plugin still appears to be doing the same thing.

**Comment by t00thpick1** [comment]
@ViceCity Lets see the new startup please.

**Comment by ViceCity** [comment]
Appreciate the help so far. Here it is: http://pastebin.com/Nh8iLYsK

**Comment by t00thpick1** [comment]
@ViceCity Just regenerate all your configs, I think the newest jar's configs are not compatible with the older ones, and since you ran the newest jar first...

**Comment by ViceCity** [comment]
Deleting the entire mcMMO folder, ill let you know what happens.

**Comment by ViceCity** [comment]
Well that solved my problem, thank you sir.

**Comment by ViceCity** [comment]
Lastly, how do I disable serrated strikes?
