### ISSUE TITLE
Failure to work #2

### ISSUE THREAD

**Issue by ViceCity** [mcMMO-Dev/mcMMO#2855]
ViceCity commented 2 hours ago
Running the latest version of Spigot 1.8.8 on my minecraft server, as well as the latest version of ViaVersions. I am running only around 18 other plugins as the server is in development mode. I disabled every single other plugin as well as ViaVersion only to have the plugin still not work which makes absolutely no sense. I as well downgraded the version to see if it being updated for 1.9 would be the problem, so I downgraded and the same problem occurs.

I paid money for this plugin and wish for it to be fixed. Thank you.
 @t00thpick1
  mcMMO Development member
t00thpick1 commented 10 minutes ago
The latest builds of mcMMo do not support 1.8, you can find older builds on our spigot page.
 @t00thpick1t00thpick1 closed this 10 minutes ago
@ViceCity
      
ViceCity commented 3 minutes ago
" I as well downgraded the version to see if it being updated for 1.9 would be the problem, so I downgraded and the same problem occurs." Please read carefully. It still does not work.

Read thoroughly through the problematic paragraph before you suggest a fix that has already been applied and still corrects nothing.

**Comment by t00thpick1** [comment]
Already resolved in the original ticket.
