### ISSUE TITLE
Brewing lingering potions doesn't give alchemy experience

### ISSUE THREAD

**Issue by TheBentoBox** [mcMMO-Dev/mcMMO#2856]
Hello!

Using the latest build, my players aren't able to earn mcMMO alchemy experience from brewing lingering potions. This occurs when players put dragon breath in the brewing slot with splash potions in the brewing stand. This could be considered another "tier" beyong splash potions, and should give experience to match that.

**Comment by t00thpick1** [comment]
You can fix this yourself by adding to your potions config:  https://github.com/mcMMO-Dev/mcMMO/pull/2850/files#diff-100a67cd6bf7a0631290e83aecd4e9beR21

**Comment by t00thpick1** [comment]
That being said I'm fixing the default config.
