### ISSUE TITLE
Mcmmo doesn't work on 1.9

### ISSUE THREAD

**Issue by FlamexAdv** [mcMMO-Dev/mcMMO#2858]
on 1.8.9 it worked perfectly no there is an error
19:51:15 [INFO] [mcMMO] Loading mcMMO v1.5.05-SNAPSHOT-b131
19:51:15 [INFO] [mcMMO] Enabling mcMMO v1.5.05-SNAPSHOT-b131
19:51:15 [ERROR] [mcMMO] There was an error while enabling mcMMO!
19:51:15 [WARN] java.lang.NoSuchFieldError: MENDING
19:51:15 [WARN] 	at com.gmail.nossr50.util.EnchantmentUtils.<clinit>(EnchantmentUtils.java:34)
19:51:15 [WARN] 	at com.gmail.nossr50.config.treasure.TreasureConfig.loadEnchantments(TreasureConfig.java:478)
19:51:15 [WARN] 	at com.gmail.nossr50.config.treasure.TreasureConfig.loadKeys(TreasureConfig.java:135)
19:51:15 [WARN] 	at com.gmail.nossr50.config.treasure.TreasureConfig.<init>(TreasureConfig.java:76)
19:51:15 [WARN] 	at com.gmail.nossr50.config.treasure.TreasureConfig.getInstance(TreasureConfig.java:82)
19:51:15 [WARN] 	at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:403)
19:51:15 [WARN] 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:145)
19:51:15 [WARN] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291)
19:51:15 [WARN] 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
19:51:15 [WARN] 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
19:51:15 [WARN] 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361)
19:51:15 [WARN] 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321)
19:51:15 [WARN] 	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:202)
19:51:15 [WARN] 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:522)
19:51:15 [WARN] 	at java.lang.Thread.run(Unknown Source)
19:51:15 [INFO] [mcMMO] Disabling mcMMO v1.5.05-SNAPSHOT-b131
19:51:15 [ERROR] [mcMMO] Cannot read C:\Users\Donatas\Desktop\minecraft server 1.9\plugins\mcMMO\experience.yml(File Permissions?)
19:51:15 [ERROR] [mcMMO] Cannot read C:\Users\Donatas\Desktop\minecraft server 1.9\plugins\mcMMO\repair.vanilla.yml(File Permissions?)
19:51:15 [ERROR] Error occurred while disabling mcMMO v1.5.05-SNAPSHOT-b131 (Is it up to date?)
19:51:15 java.lang.NullPointerException
19:51:15 at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:247) ~[?:?]
19:51:15 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:293) ~[spigot-1.9-R0.1-SNAPSHOT-latest.jar:git-Spigot-7d15d07-c194444]
19:51:15 at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot-1.9-R0.1-SNAPSHOT-latest.jar:git-Spigot-7d15d07-c194444]
19:51:16 at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-1.9-R0.1-SNAPSHOT-latest.jar:git-Spigot-7d15d07-c194444]
19:51:16 at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:201) [mcMMO.jar:?]
19:51:16 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) [spigot-1.9-R0.1-SNAPSHOT-latest.jar:git-Spigot-7d15d07-c194444]
19:51:16 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9-R0.1-SNAPSHOT-latest.jar:git-Spigot-7d15d07-c194444]
19:51:16 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9-R0.1-SNAPSHOT-latest.jar:git-Spigot-7d15d07-c194444]
19:51:16 at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9-R0.1-SNAPSHOT-latest.jar:git-Spigot-7d15d07-c194444]
19:51:16 at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9-R0.1-SNAPSHOT-latest.jar:git-Spigot-7d15d07-c194444]
19:51:16 at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:202) [spigot-1.9-R0.1-SNAPSHOT-latest.jar:git-Spigot-7d15d07-c194444]
19:51:16 at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:522) [spigot-1.9-R0.1-SNAPSHOT-latest.jar:git-Spigot-7d15d07-c194444]
19:51:16 at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]

**Comment by Morleyy** [comment]
I'm having the same issue on my server. Help?

**Comment by t00thpick1** [comment]
Update spigot,  you need a newer 1.9 version of spigot.
