### ISSUE TITLE
mcMMO just will not work on my server..

### ISSUE THREAD

**Issue by Mutt420** [mcMMO-Dev/mcMMO#2859]
My server has been running fine and ive been using mcmmo for almost a month now, but recently it just stopped working, and I mean I type /mcmmo or any of the commands and nothing happens at all..

if I type /plugins, its shows up but its red, so I figured it was one of the other plug-ins but I wasn't sure which one it was because I installed a bunch, so I uninstalled all of them.. same issue, even being the only plugin installed it was still red, so then I deleted all the files on my server and ran it again hopeing this would reset things and fix the issue.. however log on install mcmmo first and only plugin and still same issue... so I took it a step further contacted my host, told them I made a mistake and asked them to do a factory reset on my server. they did it about an hour ago, I just tried installing mcmmo again and it is still coming up red in my /plugins list...

please help, I cleared my console and restarted the server then copied it so you can see the error I'm getting, mcMMO is currently the only plugin installed on my server and this was the fresh restart done by my host...  

 hope you can help. My Server is no fun without mcMMO!!!

http://hastebin.com/qubihuhimo.vbs

**Comment by EvilOlaf** [comment]
Make sure you run the very latest version of Spigot available. Use BuildTools.jar to get the latest one.

**Comment by Mutt420** [comment]
my spigot is up to day, it wont even load old mcmmos.. same thing just shows up red in my /plugins list

**Comment by EvilOlaf** [comment]
Older version of mcMMO does not work which is expected.
Try backing up your current config set and let mcMMO generate a new one.

**Comment by Mutt420** [comment]
that doesn't really make sense to me, did I not explain that ive uninstalled it as well as every other file on my server multiple times and let it all regenerate...

its been fresh genereated with and without mcmmo several times, its still not working.. 

but doubts aside, I tried it and sure enough still does not work, instead of guessing different things can you not look at the errors in the console and actually tell me what the problem is?

**Comment by DorCoMaNdO** [comment]
Your Spigot is not up to date, before claiming it is, please check it...
There was an update to fix the potions API, an update which the version you're using does not include, hence the startup error, you're probably behind by at least a hundred commits, to confirm, just insert "/version" in the chat or "version" in the server console.
To update Spigot, either compile it yourself or have someone else do it for you, if you're using a host that provides the Spigot jar, let them know that it is outdated.

**Comment by Mutt420** [comment]
There we go an answer that helped, while also making me feel dumb! Sorry about that, but thanks for your help, my host has been contacted and the issue has been solved!

Thank you for your time!
