### ISSUE TITLE
Updated and it broke everything.

### ISSUE THREAD

**Issue by dart737** [mcMMO-Dev/mcMMO#2860]
I got a message saying my Mcmmo was out of date, so I decided to update it. That was a rather large mistake since my server is still in 1.8. The newest update doesn't work with 1.8. So, decided to downgrade, but I could not find a version for 1.8. Only a version for 1.7.10 and for 1.9. I downgraded to 1.7.10, only to realize that version allows duplication of blocks (I have not edited my hidden.yml) via silktouch then just placing the block back and mining it again. (Luckily I found this before my players have.) so of course, I deleted that version. Now I'm kinda just stuck using the 1.9 version that simply doesn't work on my server.

**Comment by Tim-Schneider** [comment]
If you are using 1.5.05 form dev.bukkit.org quickly stop your server and remove this version. This version is poisoned -> https://www.spigotmc.org/threads/mcmmo-paid.39629/page-42#post-1427922
Get a clean version from spigotmc.org.

**Comment by dart737** [comment]
Ok thanks, But I can't get the safe 1.5.04-snapshot version because I haven't paid for it and I can't find the 1.5.04-snapshot on Bukkit either

**Comment by Tim-Schneider** [comment]
a) support this awesome plugin by a donation
b) compile it your self: https://github.com/mcMMO-Dev/mcMMO/tree/6cf7167c09cae3330a63ad20215219b3226b91e1

**Comment by t00thpick1** [comment]
Yeah uhh, sorry I lost all my old builds when the CI had to be moved :(
