### ISSUE TITLE
1.9 Break

### ISSUE THREAD

**Issue by Miffedgrunt** [mcMMO-Dev/mcMMO#2861]
Hello, 

With the last update, everything broke for me. 

[error.txt](https://github.com/mcMMO-Dev/mcMMO/files/190692/error.txt)

Is it something I'm causing?

**Comment by Tslat** [comment]
Is your Spigot up to date?
Did you also let your treasures.yml regenerate?

**Comment by Tim-Schneider** [comment]
Your Spigot is outdated.

**Comment by t00thpick1** [comment]
Update spigot
