### ISSUE TITLE
Mcmmo internal error....

### ISSUE THREAD

**Issue by Titaxiam** [mcMMO-Dev/mcMMO#2862]
So i use paper spigot on the server and i was using 1.5.04 for the server... and it works and all but every time i try to do /mctop,/mcstats or any command ex. /mining it would always say a internal error.. Please someone help me fix this problem... I have the full version of it and its not cracked...

**Comment by Tslat** [comment]
What's the error in console?

**Comment by Titaxiam** [comment]
We installed paper spigot 1.8.8 and it messed up the console and we can see error commands since it is flooded with java scripts and errors. I really dont know what to do... I have basically wasted 10$ and i don't have proof or the errors ;p But any commands such as /unarmed /mining /skills /mctop /mcstats doesnt work it keeps saying "internal error command"

**Comment by t00thpick1** [comment]
Lets see all the console errors....
