### ISSUE TITLE
Custom blocks doesn't work.

### ISSUE THREAD

**Issue by Vauxite** [mcMMO-Dev/mcMMO#2866]
**Versions:**
mcmmo 1.5.03-b62
Minecraft 1.7.10 
Thermos 1.7.10-1614.32

**Startup verbose logging**
http://pastebin.com/j78xchAF

**tools config(works):**
http://pastebin.com/67UBpT0X

**block config(Doesn't work):**
http://pastebin.com/X7b5yT6V

Tried with both custom and vanilla tools. No error message in log when the block is broken. Prism is able to register the blockbreak (so that event should be ok).

How shall I proceed?

**Comment by t00thpick1** [comment]
I *think* you need XP_GAIN to be XP_Gain

**Comment by Vauxite** [comment]
Thank you, this issue has been resolved.
