### ISSUE TITLE
mcMMO error on Enabling

### ISSUE THREAD

**Issue by IamJustBad** [mcMMO-Dev/mcMMO#2867]
`28.03 23:18:19 [Server] ERROR Error occurred while disabling mcMMO v1.5.00-b3547 (Is it up to date?)
28.03 23:18:19 [Server] INFO Disabling mcMMO v1.5.00-b3547
28.03 23:18:19 [Server] WARN at java.lang.Thread.run(Unknown Source)
28.03 23:18:19 [Server] WARN at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527)
28.03 23:18:19 [Server] WARN at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:202)
28.03 23:18:19 [Server] WARN at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321)
28.03 23:18:19 [Server] WARN at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361)
28.03 23:18:19 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
28.03 23:18:19 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
28.03 23:18:19 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
28.03 23:18:19 [Server] WARN at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:163)
28.03 23:18:19 [Server] WARN java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
28.03 23:18:19 [Server] ERROR There was an error while enabling mcMMO!
28.03 23:18:16 [Server] INFO Enabling mcMMO v1.5.00-b3547
28.03 23:18:16 [Server] INFO Enabled Version 1.5.6-b49`

Using Spigot 1.9 and mcMMO version 1.5.00-b3547.
It worked fine yesterday but now it just doesn't work

**Comment by EvilOlaf** [comment]
Update Mcmmo

**Comment by IamJustBad** [comment]
> Update Mcmmo

MCProHosting says McMMO is up to date (Version 1.5.00-b3457)
