### ISSUE TITLE
Will Not Work :(

### ISSUE THREAD

**Issue by lilmikey0174** [mcMMO-Dev/mcMMO#2868]
When I installed mcMMO NONE of the functions worked. The jar that I used was the newest one on the spigotmc site. please help me out here

**Comment by t00thpick1** [comment]
Probably outdated spigot.  Update to latest spigot.

**Comment by lilmikey0174** [comment]
I have updated spigot to the newest version ( I thing, how do I check for newer versions?)

**Comment by t00thpick1** [comment]
use /version  and copy the git-spigot-blah blah string into the spigot IRC chat and a bot will tell you how far you are behind if at all.

**Comment by lilmikey0174** [comment]
ok then what? THE BOT IS DEAD! :( R.I.P Spigot Bot
