### ISSUE TITLE
Feather Falling Not Giving Double Acrobatics XP

### ISSUE THREAD

**Issue by Tydye101** [mcMMO-Dev/mcMMO#2870]
Enchanted boots and got Unbreaking 3 and Feather Falling 4. Proceeded to try and fall from ladder and I am not gaining any XP at all in the skill. Works fine when boots are off.

**Comment by t00thpick1** [comment]
acrobatics is based on damage taken,  if you take 0 damage because of feather falling, you will get 0 xp
