### ISSUE TITLE
mcmmo-worldguard

### ISSUE THREAD

**Issue by darkarrow** [mcMMO-Dev/mcMMO#2872]
First off I'm sorry if this is the wrong place to ask this but it's the only thing I've found thus far.

On McMMO's spigotmc page it lists a plugin, mcmmo-worlguard but when I click on it it takes me to a page that has a 404 error. Is this addon no longer up/being supported? If not that's a shame because that would come in handy.

Thanks!

**Comment by t00thpick1** [comment]
I'll see if I can get an updated build up somewhere. no promises though

**Comment by Portanna** [comment]
Is this gonna ever be released?
