### ISSUE TITLE
locale

### ISSUE THREAD

**Issue by WPMDev** [mcMMO-Dev/mcMMO#2874]
How do I use this? I made a locale folder, placed locale_en_US.properties in it (I edited the messages) and it does not show to correct messages. My config.yml does contain this:
General:
    Locale: en_US

**Comment by Tslat** [comment]
Edit it inside the Jar

**Comment by WPMDev** [comment]
I have tried unzipping (changing prefix to .zip) the Plugin, editing the locale properties file, reziping it (changing suffix back to .jar)

**Comment by Tslat** [comment]
Open the jar with an archive program (winrar, or something similar)
extract the locale file
Edit the locale file
Put the locale file back in

No unpackaging needed
