### ISSUE TITLE
Block places

### ISSUE THREAD

**Issue by timmayxo** [mcMMO-Dev/mcMMO#2875]
When you want to build up in a straight line, there seems to be a block glitch and teleports you down. And its your plugin. Tested it without it and the bug isn't there but with the plugin its there and my players are annoyed by it

**Comment by EvilOlaf** [comment]
CB/Spigot version?
mcMMO version?
Given permissions?
Configuration?


Insufficient information.

**Comment by timmayxo** [comment]
Spigot Version: git-Spigot-d20369f-7fc5cd8 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)

mcMMO Version: 1.5.05-SNAPSHOT-b133

Permssions: default setup

Config: default config, just added mysql and disabled health bars.

**Comment by t00thpick1** [comment]
Could I get a video or something?  I am unable to reproduce.
