### ISSUE TITLE
Potion of Water Breathing

### ISSUE THREAD

**Issue by sigmaroot** [mcMMO-Dev/mcMMO#2876]
Potion of Water Breathing can't be brewed by placing a lily pad into the brewing stand. Checked some other potions, they work.

Please check all alchemy potions, thanks :)

Version: mcMMO version 1.5.05-SNAPSHOT-b133
Server: git-Paper-617 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)

**Comment by t00thpick1** [comment]
Check your config,  it might just be missing.

**Comment by sigmaroot** [comment]
Noooo...To rash!

It's **not** missing in my configuration:

http://pastebin.com/aUn66Uyk

http://pastebin.com/5bteb53B
