### ISSUE TITLE
Random Error - Pastebin included

### ISSUE THREAD

**Issue by AdamTragedy** [mcMMO-Dev/mcMMO#2877]
http://pastebin.com/x8sPDehs

**Comment by t00thpick1** [comment]
Investigating.

**Comment by satelitecraft** [comment]
have the same problem
server crashed overnite & crashes with mcmmo enable
tried ver from june & same prob
never had a prob with mcmmo till now
eula mojang maybe?
help plz

**Comment by Tslat** [comment]
The reason you never had a problem is because it's caused by the April Fools stuff
It'll go away again after today, whether t00thpick1 fixes it or not

**Comment by t00thpick1** [comment]
@Tslat Yes and no, this particular error would go away, but the underlying cause of the IndexOutOfBounds for our mcMMO player collection is a bug thats I've seen crop up a few times in different places.  So I'm looking into it

**Comment by Tslat** [comment]
Yeah I remembered that when I made the post, which is why I removed it straight after ;)
