### ISSUE TITLE
disabling 'april fools' in config

### ISSUE THREAD

**Issue by LXsource** [mcMMO-Dev/mcMMO#2879]
A config setting to disable 'april fools' is needed. Fake skills are spamming our server. We disabled mcMMO for now.

**Comment by Tslat** [comment]
It should be over very soon anyway, it only lasts for a day

**Comment by SioWolf** [comment]
I just went to like this post to find out I had already liked it many months ago. I guess I was thinking the same thing last year too.

**Comment by PassiveBrain** [comment]
config.yml 490 line     **LargeFireworks: true -> false** 
`
Particles:
    # These settings determine if fireworks should get launched when a player activates/deactivates an 
ability
    Ability_Activation: false
    Ability_Deactivation: false
    # Determines if the fireworks should be a large ball or a small one
    LargeFireworks: true
`
well, it's not disabling, but makes it much smaller = way less patricles = way less lagg (helped us alot)
Worst option is to disable/reduce all particles (fireworks particles?) in game settings. 
Should be option in config to disable tho, can be spammed to create tons of lags, pulling burnt stones from furnaces one by one for example
