### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by meegamax** [mcMMO-Dev/mcMMO#2880]
Can you disable ALL features of mcmmo except party chat for certain groups? I've put in '-mcmmo.defaults' '-mcmmo.\* '-mcmmo.commands.defaults' and even '-mcmmo.skills.all' How can i remove mcmmo from groups???

**Comment by Tslat** [comment]
Permissions removal will work

Make sure your permissions are set up properly.

**Comment by meegamax** [comment]
I've done that and it doesn't remove it. Here's the group in group managers file. 
![capture](https://cloud.githubusercontent.com/assets/18221830/14224142/a1667640-f857-11e5-8e05-a3233cd1e197.PNG)

**Comment by meegamax** [comment]
They have the - node but it doesn't seem to be working!

**Comment by Tslat** [comment]
Show full file

http://pastebin.com/

**Comment by meegamax** [comment]
Default Group starts at line 101 i think.

http://pastebin.com/SKV3yqS5

**Comment by meegamax** [comment]
Is it wrong?

**Comment by Tslat** [comment]
Not sure what permissions plugin you're using (I assume Pex)
Try and avoid using the pre-built groups as inheritance -- build the permissions yourself.

Remove the negative nodes and just leave the single negative ones -mcmmo.*
Then give the group mcmmo.commands.party

The permissions work fine, and haven't been changed in a long time

**Comment by meegamax** [comment]
So change it to this?

http://pastebin.com/AkLt5Rsy

**Comment by meegamax** [comment]
Still not working

**Comment by Tslat** [comment]
Doesn't really look like you did anything though
