### ISSUE TITLE
Scoreboard.dat Spam?

### ISSUE THREAD

**Issue by SioWolf** [mcMMO-Dev/mcMMO#2881]
Hello. First off, I apologize if this is not related to your plugin. I have been having this issue and since I can not figure out what is causing it I am contacting the developers of the plugins I use.

Every day my scoreboard.dat becomes bloated with thousands teams. When these teams are created players experience very long delays when joining and get stuck at the "downloading terrain" screen. Each day I have to delete it before starting up the server again.

I have included the raw scoreboard.dat, as well as a screenshot of what it looks like opened up with NBTExplorer, linked below. If you think this could be your plugin causing this or have any idea WHAT might be causing it, please let me know. Thank you.

http://i.imgur.com/ICPiEQv.png

Scoreboard.dat: https://onedrive.live.com/redir?resid=C6469F6919D23669!78018&authkey=!AKXWjlNYKhs8Src&ithint=file,dat

NBTExplorer: https://github.com/jaquadro/NBTExplorer/releases/tag/v2.7.6.-win

**Comment by t00thpick1** [comment]
not us.
