### ISSUE TITLE
Fuel efficiency seemingly broken.

### ISSUE THREAD

**Issue by MetaHero** [mcMMO-Dev/mcMMO#2882]
No errors are being reported in the server feed. However I have noticed i'm getting a static 1 coal to 8 smelts with 891 smelting. This says my fuel efficiency multiplier is 3.67x. If i am understanding that correctly my fuel should last for 29 smelts. I know this isn't a huge issue and more of annoyance when in situations when fuel lasting longer is useful, but i thought i'd mention that i noticed it. Just to mention some things, I haven't changed any of mcmmo values besides turning off AF downgrade change. Other than this everything is kept with default settings. Thanks a bunch.

Note: i forgot to mention this. This is on 1.9

**Comment by t00thpick1** [comment]
I'll take a look
