### ISSUE TITLE
/stats 1.8 internal error

### ISSUE THREAD

**Issue by rewtie** [mcMMO-Dev/mcMMO#2883]
Whenever I try to view my stats with like /stats or /mctop I get an internal error and this in console: http://hastebin.com/ejuzojerug.vbs I just bought it on spigot because I was having this issue with the bukkit version and I was hoping this would fix it and it didn't. I'm using an older version of mcmmo for 1.8

**Comment by t00thpick1** [comment]
So this is likely your spigot/cb version, see if you can find a newer 1.8 version of spigot/cb, otherwise see if you can find the latest 1.8 build of mcMMO(I don't have any downloads for it anymore sorry :( )

**Comment by rewtie** [comment]
What version of Spigot or Minecraft is mcMMO v1.5.04-SNAPSHOT made for? I'm currently using 1.8.7

**Comment by rewtie** [comment]
Update: I changed to the most recent version of PaperSpigot and it still gave me this error. I've been getting it for AGES. Could it be any of my plugins interfering with it? Here's the list: http://prntscr.com/ans59z

**Comment by rewtie** [comment]
I found out the issue. I was using an outdated version of featherboard. Thanks

**Comment by t00thpick1** [comment]
Cool :D
