### ISSUE TITLE
mcmmo admin chat request

### ISSUE THREAD

**Issue by Zayeir** [mcMMO-Dev/mcMMO#2884]
My friend and I are creating a network, and we have a custom made plug-in which we're using for all of our staff chats, and mcmmo is over-riding this. Would it be possible for us to receive a version of mcmmo without admin chat implemented?

**Comment by t00thpick1** [comment]
You can actually use the commands.yml in your server folder to override which plugin implements a command.

**Comment by ABNGaming** [comment]
I just bought the mcmmo plugin but everytime I join the server it says that my plugin is outdated.. what shall I do?

**Comment by t00thpick1** [comment]
@ABNGaming I had some legacy "update checker" code in the plugin for a very long time that didn't actually function and just always said you were behind,  you can grab the very latest from spigot to remove that.

**Comment by ABNGaming** [comment]
I did use the last version and same issue! and the mcmmo commands arent working..

**Comment by t00thpick1** [comment]
@ABNGaming Can you tell me your mcMMO version and spigot version?

**Comment by ABNGaming** [comment]
mcMMO: 1.5.04
Spigot: 1.8.8

**Comment by ABNGaming** [comment]
I downloaded the latest mcMMO from the spigot website!

**Comment by t00thpick1** [comment]
Ohhh yeah so unfortuanently for you, since you are running 1.8, you will not be able to avoid the "outdate plugin" message,  that being said you need to use 1.5.04-snapshot,  you can look for a link on the spigot page with the tag "Latest 1.8 Build"

**Comment by ABNGaming** [comment]
it worked.. Thanks a lot <3333
