### ISSUE TITLE
alchemy broken?

### ISSUE THREAD

**Issue by ciwe90** [mcMMO-Dev/mcMMO#2886]
hello, i fot a problem with mcmmo, when someone make special potion on my server it works (for example we can make haste potion with carrot, but when someone try to upgrade this with redstone glowstone or gunpowder the potion becomes into a vulgar potion. We are remove the file of pots and clear all but it dont work
can u help me please?

**Comment by Nickshelton80** [comment]
Level II mcMMO alchemy potions are broken for me, but the rest are fine.
