### ISSUE TITLE
Change name of abilities

### ISSUE THREAD

**Issue by Mihawka** [mcMMO-Dev/mcMMO#2887]
Hello
I would change the name of abilities . I just have to do it in the advanced.yml ?

**Comment by t00thpick1** [comment]
Edit the language files

**Comment by Mihawka** [comment]
In the language file? But there is no

**Comment by Mihawka** [comment]
In config.yml ?

**Comment by SioWolf** [comment]
The only language files I have found are if you decompile the plugin and navigate the folders. Last time I did this, however, it caused the plugin to stop working. According to this: http://mcmmo.wikia.com/wiki/Localization it appears that is the only way to do it.

This is very inconvenient when updating to newer versions. Perhaps localization should be added in the configurations folder.

**Comment by Mihawka** [comment]
Thanks you !
