### ISSUE TITLE
Administrative Party Features

### ISSUE THREAD

**Issue by eightbitx** [mcMMO-Dev/mcMMO#2888]
I was looking today for the ability to spy on party chats and found several requests for this that have been closed. I would like to bring these up again since it has been two years since they've last been mentioned, and to voice my support for the features. It is my assumption that a feature is more likely to be added if more people show interest. I would also like to take the opportunity to answer some of the questions raised last time these features were mentioned.

I am referencing issues: #124, #1845, and #2145. This feature has been requested 3 different times that I am aware of, spanning from 2012 to 2014, and now 2016.

In #2145 several questions were raised by @TfT-02:

> Things I think admins should have in regards to mcmmo parties:
> -ability to join any party

Why would this be necessary to do as an admin? I feel like this is a bit intrusive and unnecessary.

Although I do not see a reason for an Admin to become a full member of a party, I do feel that they should be able to send messages to the party's chat. It would allow Admins to talk to the group should they have a question, need to be warned about what they are doing/talking about, etc.

> -ability to take or give levels to a party

Why would this be necessary to do as an admin?

We are able to give or take levels for individual players, why would it be necessary to do so for players but not for a party? If a party expires or is accidentally deleted we may want to help the player fix this mistake and get their levels back. If, for some reason, some or all of the parties are lost due to an error with the database, we would want to be able to give players their parties back and their appropriate levels. Currently, if we lose the parties there is nothing we can do to fix it. Finally, admins may want to give levels as a reward or as compensation for another issue. McMMO levels as rewards for donating and what not is becoming increasingly popular.

> -ability to change the owner of a party (incase the owner gets banned, goes inactive, or loses their account for whatever reason)

Not necessary; that is if you have kept the party auto kick feature enabled (here). This will kick players from their party after 7 days (default value) and if that player happend to be the party member, the next player becomes the party leader. Order is determined by the order of joining. Last to join becomes party leader last.

I believe this is completely necessary. We may not necessarily WANT that player to be the owner. Players could have been added that are perfectly fine just playing and enjoying the perks, but are not or can not be trusted with full control of the party, specifically locking it. Players may also want to resign or leave a party WITHOUT being gone for 7 days.

> -ability to spy on party chat

Has been requested a long time ago. See #124, it has now been put on hold since it's not really on of our priorities at the moment.

This is the big one. The one I was looking for. Most other plugins that offer a chat feature allow staff to moderate those chats. This has all been mentioned before. It is extremely worrying that players have the ability to chat on the server in a channel that can not be moderated, allowing them to cuss out staff, plan a grief/raid, admit to hacks, advertise, and more, without the Moderators ever having any idea.

**Comment by jordanwilliams1** [comment]
ye pls i want this <3

**Comment by Momshroom** [comment]
@SioWolf 
There are several open tickets about this, including this one: https://github.com/mcMMO-Dev/mcMMO/issues/2811 and this one: https://github.com/mcMMO-Dev/mcMMO/issues/2511

I can't help with the rest of this, but for the issue of the chat, we were able to disable party chat w/o disabling parties by setting the level party chat unlocks at absurdly high.  (Negating the perm didn't work. https://github.com/mcMMO-Dev/mcMMO/issues/2561 )

**Comment by SioWolf** [comment]
@Momshroom we don't want to take away functionality from the players. That is a feature they should be able to use. We just want to be able to moderate it.
