### ISSUE TITLE
BUG? Not earning EXP

### ISSUE THREAD

**Issue by nebih** [mcMMO-Dev/mcMMO#2890]
Sometimes when I'm using a trainer for acrobatics I won't earn the exp that I should. Or when I'm at my mob farm sometimes I will only earn 1 or 0 exp. Other times it works just fine. A few other players on my server have noticed this as well and have said that even when not using a trainer or grinder they sometimes won't earn their exp. 

If you need any configuration files, let me know

**Comment by DorCoMaNdO** [comment]
Experience is gained based on the damage taken. Unequip your feather falling boots.

**Comment by t00thpick1** [comment]
There are some safeguards against XP farming in what we consider "unfair" ways, this might be your issue.
