### ISSUE TITLE
Environmentally Awareness

### ISSUE THREAD

**Issue by xhatz** [mcMMO-Dev/mcMMO#2891]
Hi! There is still a problem with this skill.
When at level 100, the player should unlock the "environmentally aware" skill for taming, but it only works for OP players...
EDIT: For non-op players, it's not even showing.

Thanks!

**Comment by Tslat** [comment]
That's an issue with your permissions system I'd say

**Comment by xhatz** [comment]
Everything is default, I never had another issue... I tried adding the permission, removing some, but nothing seems to work.

**Comment by Tslat** [comment]
What locale are you using?
What spigot build and what McMMO build?

**Comment by xhatz** [comment]
Sorry for late reply.
That happened to me on multiple versions of mcMMO, I usually get the latest build from jenkins (I think).
And same for spigot, I had the latest 1.9.2 build, but that happened on my 1.8 and 1.7.10 server as well :/

**Comment by Tslat** [comment]
Did you use the same config for all those times, perhaps?

**Comment by xhatz** [comment]
I often change server and reset it ^^

**Comment by Kalrathia** [comment]
One of the players on my server ahs noticed this as well. This is his report:

"After these past 2 days, I've been leveling my taming up really high and it's reached 375. But there are some problems with taming that I have seen. These are the 2 problems I have encounter.

Environmentally Aware:

This ability is crucial to any tamer past level 100. But for some reason this ability does not exist and makes the usefulness of the wolves drop drastically. This is the ability description: The skill "Environmentally Aware" comes after your taming reaches past level 100. This skill grants your summoned wolves the ability of teleporting to you when nearing cacti or lava. This also allows your wolf to be immune to fall damage. It is a hidden skill that improves the usefulness of wolves drastically.

Holy Hound:

This ability lets your wolves get healed whenever they take poison damage or get hit with instant damage potions. This ability works partially but they still take the damage from poison and instant damage. This bug makes it so they don't take poison damage but also don't get healed from it. They take a lot of damage from the harming potions and barely get healed for any of it."

I have not changed the config of mcmmo for taming at all. I don't believe i have changed any of it actually. Is this a possible bug or would there be a specific part of the config that would need to be looked at that would cause these issues?

**Comment by xhatz** [comment]
Up :s

**Comment by Momshroom** [comment]
We're also having issues with this.  We have mostly default mcmmo perms (I explicitly added a greenthumb perm that was supposed to be given by default and wasn't.)  I've noticed that my players are ALSO not getting mcmmo.ability.taming.environmentallyaware by default even though the help says it is given by default, but adding this doesn't seem to help.  I'm looking into other perms now, but there are several mcmmo perms that are no longer given by default that the documentation says are.

**Comment by Momshroom** [comment]
After explicitly adding the permssion, it gets more confusing:
http://prntscr.com/kulbcd <-that's the perm checks when I do /taming, BUT:
If I check for the permission, I have it: http://prntscr.com/kulbkt
I'm not sure what's going on.

**Comment by t00thpick1** [comment]
Found it...  this is annoying.....
