### ISSUE TITLE
Small issue

### ISSUE THREAD

**Issue by DaffyFluck** [mcMMO-Dev/mcMMO#2892]
It seems I can't turn the hearts off for the mobs I have it disabled and set to -1 on the time yet they keep showing up and it's stopping some of my other plugins from working right.

**Comment by Vauxite** [comment]
I'm not sure if this will work for you. But I'd troubles disabling it (chat got flooded when someone killed something) and added a negative permission (I use PEX).

` - -mcmmo.mobhealthdisplay`
