### ISSUE TITLE
Truncate levels

### ISSUE THREAD

**Issue by vuurwerkPWN** [mcMMO-Dev/mcMMO#2893]
Can someone tell me more about this feature because I do not understand what this does?
(give an example?)

" Should mcMMO truncate levels if you lower your max level cap for a skillname"
    TruncateSkills: true

**Comment by t00thpick1** [comment]
If you had a skill cap of 5000, and then you lowered it to 1000, that option controls whether or not to adjust any players skill who was above 1000 to 1000
