### ISSUE TITLE
Mcmmo error

### ISSUE THREAD

**Issue by YoungChilo** [mcMMO-Dev/mcMMO#2894]
http://pastebin.com/w44bLj8j
My server has mcmmo but it docent work. I have it when i do /help and i can do /help mcmmo and i can see all commands but its not active it docent let use any of the commands and it dosent let me get mcmmo skill. So i have mcmmo but it dosent enable. Please help the link is my latest log.

**Comment by EvilOlaf** [comment]
Seems like your `potions.yml` is corrupted. Back it up and let mcMMO generate a new one by simply restarting your server.
