### ISSUE TITLE
Mobspawner granting exp.

### ISSUE THREAD

**Issue by Vauxite** [mcMMO-Dev/mcMMO#2895]
Hey

**Problem**
A mobspawner is not being detected as such and grant experience when monsters are killed. Settings
`Mobspawners:
        Multiplier: 0`

**Additional info**
[The spawner](https://github.com/brandon3055/Draconic-Evolution/blob/master/src/main/java/com/brandon3055/draconicevolution/common/blocks/CustomSpawner.java)

**Server info**
The Goldencobblestone 1.0.5

**Versions:**
Minecraft 1.7.10
Mcmmo 1.5.03-b62

**Comment by t00thpick1** [comment]
We use the CreatureSpawnEvent and check if the SpawnReason is SpawnReason.SPAWNER   make sure whatever server implementation you use adapts their spawn event to such.

**Comment by Vauxite** [comment]
Sorry, I may sound stupid. But how shall I as a server owner/admin proceed? Contact draconic-evolution creator? Or what?

**Comment by t00thpick1** [comment]
Them or Tekkit/whatever actual server software you use.
