### ISSUE TITLE
Beetroot?

### ISSUE THREAD

**Issue by nebih** [mcMMO-Dev/mcMMO#2896]
How do I add beetroots to the experience.yml so they can give herbalism exp to my users?

I tried just adding 

Beetroot: 50

But after a restart, it was gone. I'm not very skilled at doing things like this, and your help is very appreciated :)

**Comment by DorCoMaNdO** [comment]
It has to be handled via the code first, this will be done sometime soon.

**Comment by minoneer** [comment]
Would be great to see this implemented

**Comment by andrewkm** [comment]
Can confirm this issue here as well.
