### ISSUE TITLE
Disable XP gain in certain worlds

### ISSUE THREAD

**Issue by Gaelan** [mcMMO-Dev/mcMMO#2897]
I have a server which is currently creative-mode only. I would like to add a survival/McMMO world with Multiverse. Obviously, players shouldn't be able to gain XP in the creative world. As much as possible, the two worlds should act like separate servers, one with McMMO and one without. Is there a way to implement this?

**Comment by DaffyFluck** [comment]
You will need to setup the Permissions to be per world and give out a negative node for the Creative world.

**Comment by Gaelan** [comment]
Is there a node for XP gain? I didn’t see one in the list. Am I blind?

**Comment by DaffyFluck** [comment]
You could just give out - -mcmmo.skills.* that would disable all the skills in the creative world.

**Comment by Gaelan** [comment]
I was hoping to disable XP gain to avoid using creative to gain huge amounts of XP (I see in the code that XP is disabled for creative players, but /gamemode is available in that world). Looking at that code, I could just set a custom 0x XP "perk" and give that permission to players in the creative world. Suboptimal (a `mcmmo.xpgain.*` or similar would be nice), but does the trick.

**Comment by Tslat** [comment]
Isn't xp gain in creative already disabled?

**Comment by Gaelan** [comment]
@Tslat As I said, in the creative world users are permitted to use /gamemode.

**Comment by Tslat** [comment]
So to clarify; you want players to not gain xp in that world under any circumstances, but still want them to be able to use abilities while in survival mode?

**Comment by Gaelan** [comment]
@Tslat No. In one world, standard McMMO. In the other world, McMMO should act as if it is not installed. (Or as close as possible–I don't mind if `/mcmmo` displays a help message).

**Comment by Tslat** [comment]
Then do wha twas already suggested and use a negative permission node of -mcmmo.*

That definitely works, I've used it many times

**Comment by Gaelan** [comment]
@Tsalt OK.
