### ISSUE TITLE
Potions: If left in inv upon logout, it is a water bottle upon login.

### ISSUE THREAD

**Issue by AdamTragedy** [mcMMO-Dev/mcMMO#2898]
So if a player has a vanilla potion in their inventory and logs out, upon logging back in the potion will have turned into a water bottle.

**Comment by t00thpick1** [comment]
Umm.. spigot version and mcMMO version please.

**Comment by AdamTragedy** [comment]
McMMO Version 1.5.05-SNAPSHOT-b131
git-Spigot-933aa20-11e8c6d (MC:1.9.2.) 1.9.2-R0.1-SNAPSHOT

Put Instant Health II into your inventory....log offline....log online. Boom. Water Bottle.
