### ISSUE TITLE
mod folder config file not working on server with mods

### ISSUE THREAD

**Issue by Shadowmaster94** [mcMMO-Dev/mcMMO#2900]
my issue is that each time i try to run mcmmo i get this error
![capture](https://cloud.githubusercontent.com/assets/17537681/14480987/6821e8f8-00fc-11e6-969b-76495f832ac7.JPG)

i'm really not certain how to fix it. nor do i know how to set up the config file. directions in the wiki would be useful as a side note

**Comment by t00thpick1** [comment]
Can I see your config.yml and your mod configs.  Also what server are you running?

**Comment by Shadowmaster94** [comment]
i'm running on 1.7.10 .i'm using cauldron and as for my config for both they are as listed below 

this is the mcmmo mod config that i got off the wiki for 1.7.10 an twilight forest
  http://pastebin.com/STrzVWaS

this is the mcmmo config file
http://pastebin.com/eNsKEUH4

**Comment by t00thpick1** [comment]
Err the mod config you have shown here is not the one that the console is reading in...

**Comment by Shadowmaster94** [comment]
i'm very sorry about that. let me send you one that is set with what the current config files are set with
![capture](https://cloud.githubusercontent.com/assets/17537681/14481667/3e56717c-0103-11e6-9326-2338937ade62.JPG)

**Comment by t00thpick1** [comment]
I see..  Try using the following command and instructions:  https://github.com/mcMMO-Dev/mcMMO/wiki/Command-reference#mcimport

**Comment by Shadowmaster94** [comment]
i tired that command on both the console and server logged in as a host. an op but found that it gave me this error

![capture](https://cloud.githubusercontent.com/assets/17537681/14482364/f755faa2-0109-11e6-8cfd-4d7c7e239422.JPG)

![capture2](https://cloud.githubusercontent.com/assets/17537681/14482365/f8d23b20-0109-11e6-9d19-0eed060c4b0c.JPG)

one is of the console and the other is of the server

i had fallowed the instructions though i'm not certain i did this right

![capture3](https://cloud.githubusercontent.com/assets/17537681/14482375/11813d06-010a-11e6-89a2-3e86e5f0360b.JPG)

![capture4](https://cloud.githubusercontent.com/assets/17537681/14482376/11819a26-010a-11e6-8a41-f6cd81f5035e.JPG)

i really suck at these kinda things. but mods i can do just not plugins XD

**Comment by Shadowmaster94** [comment]
so did i do this right?
 if so then the command ain't working mcimport

**Comment by t00thpick1** [comment]
Umm try running it from the console and not as a player.  it should be in /mcmmo/mods/import/import.log

**Comment by Shadowmaster94** [comment]
would it matter that it's on Kcauldron not cauldron ?

**Comment by Shadowmaster94** [comment]
i tried that and it gave me an error saying to use the help command as mcimport was not a command

**Comment by t00thpick1** [comment]
#2901
