### ISSUE TITLE
mcmmo missing mcimport command

### ISSUE THREAD

**Issue by Shadowmaster94** [mcMMO-Dev/mcMMO#2901]
after long searching i have found out that mcmmo 1.5.00 is missing the mcimport command
idk why and i'm not sure. but anyways i am runnning on Kcauldron 1.7.10 and idk why it's not working.

**Comment by t00thpick1** [comment]
Oh.  We probably didn't have it at that time.. that would make sense.... Uhhhh, I'll see what I can do but don't expect results for a couple of days.
