### ISSUE TITLE
Repair skill not working - cannot interact with mcmmo anvil.

### ISSUE THREAD

**Issue by tara81** [mcMMO-Dev/mcMMO#2902]
Loadup Log: http://pastebin.com/tQvnszTs
Attached File: Configs.
[mcMMO.zip](https://github.com/mcMMO-Dev/mcMMO/files/220023/mcMMO.zip)

Using mcMMO 1.5.05-SNAPSHOT-b133
Spigot 1.9.2 [INFO] This server is running CraftBukkit version git-Spigot-5a40365-f631379 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)

**Comment by DorCoMaNdO** [comment]
Clear the configs and restart the server.

**Comment by tara81** [comment]
I cleared all the configs, restarted, and it still doesnt work. I also tried Mcmmo Build #134 (Apr 3, 2016 12:26:00 AM) and still doesn't work.

**Comment by tara81** [comment]
[mcmmo_latest.zip](https://github.com/mcMMO-Dev/mcMMO/files/232726/mcmmo_latest.zip)

**Comment by t00thpick1** [comment]
Resolved issue in 1 on 1.
