### ISSUE TITLE
A bit much spam.

### ISSUE THREAD

**Issue by Ragatokk** [mcMMO-Dev/mcMMO#2903]
I think you are overdoing it a bit on the spam. Whenever a player logs in he gets four lines of mcmmo spam on his screen.
Version number (why would a player want this? O_o)
a line that says  mcmmo perks experience: recive boosted xp in certain skills
That line does not help at all, nobody can know how or why you get boosted xp in certain skills... and neither it the place for this information the login screen of the player.
Last message is a link to your spigot site... I mean dude... Everyone on a server that uses your plugin knows they are using mcmmo... and your spigot site is the third result on google after bukkit and the wiki...

By all means, its your plugin... do whatever you want... But its rather annoying to get this much spam.
What if all the other devs did the same... getting 28 pages of help version number website link etc etc of all the plugins on the server... Sounds a bit ridiculous right?

This said I appreciate your work on this plugin and it is very nice of you to not charge for it.

**Comment by EvilOlaf** [comment]
You can achieve not bothering players with version numbers and so on by properly setting up your configuration as well as your permissions ;)

**Comment by Ragatokk** [comment]
Thank you for your quick comment. Nice to hear that it is possible to fix that with settings, but I am a bit puzzled why it is not default.

**Comment by EvilOlaf** [comment]
This unfortunately I can not answer, but @t00thpick1 might be able to do so ;)
