### ISSUE TITLE
Lag on leveling up

### ISSUE THREAD

**Issue by Tomographix** [mcMMO-Dev/mcMMO#2905]
Hi everyone,
Recently my players have been getting a substantial amount of lag after they level up in any area in MCMMO. It will cause of a delay between 20-30 seconds. The lag does not affect the entire server or its performance - only the individual player.

Furthermore, slow loading times for the map have been encountered. From doing some experimenting I have worked out that deleting the scoreboard.dat file in the world > data folder fixes the MCMMO lag and slow login times. This is not a permanent fix though and the lag slow returns over the next day or so.

Any help would be really appreciated!
Thanks

**Comment by Tomographix** [comment]
Just a small update on this. The scoreboard.dat file has a size of approx 400,000 kb compared to 5,000 kb when MCMMO is not on the server.

**Comment by mbax** [comment]
Alright, @t00thpick1 this is what you're gonna do.

You're gonna stop touching the main scoreboard, because you store all this data anyway. This way, you just populate a fresh scoreboard on startup and modify as necessary, but don't have Minecraftcode getting in the way saving and breaking hearts.

**Comment by ocelotpotpie** [comment]
I have nothing constructive to add, except to say that I like @mbax

**Comment by Deiscorides** [comment]
I have the same trouble on a server (Spigot 1.10) I frequent. My client will freeze up a few moments before the scoreboard is able to display when I level up. It unfreezes while the scoreboard is displayed, for a few seconds then freezes again when the scoreboard disappears. My personal work around for this on servers is this command:

/mcscoreboard time 0

I use it immediately when I log into the server. If I level up, I only get the chat notification. However, if I use this command after a scoreboard has popped up, it will pop up that scoreboard again and leave it there; yet that scoreboard won't update. Thus, after using this command I never have the level up lag associated with the scoreboard. It needs to be used every time you login to a server. Don't use the command during the level up client lag spike it sometimes doesn't work then.

I hope this helps those of you who are not the server's admin. Hopefully, this problem will be fixed soon.
