### ISSUE TITLE
Disable Features

### ISSUE THREAD

**Issue by systemacc** [mcMMO-Dev/mcMMO#2906]
I am using mcMMO 1.5.04-SNAPSHOT for my Spigot 1.8.8 server which also supports 1.9 using ViaVersions (Plugin).

I want to disable Salvage, so players cannot use anything related to the skill. The reason i want this is because players can exchange the armor for Diamonds or etc and sell it back, messing with the economy. I want to skill disabled on my server, how would i go about doing this? thanks

**Comment by EvilOlaf** [comment]
All the features are toggleable using permission nodes. Most of them are enabled by default to make it easier for the majority of owners to setup their mcMMO.
Check the wiki page for all the permission nodes and negate the nodes/features you do not need.
