### ISSUE TITLE
How to disable fishing loot.

### ISSUE THREAD

**Issue by formalkilling** [mcMMO-Dev/mcMMO#2911]
I want to be able to get all the vanilla fishing loot instead of getting the MCMMO loot. I want to still be able to level up my fishing skill but I want nothing else from mcmmo fishing. Please help I really want to be able to get mending and lilypads and saddles.

**Comment by iSkeptical** [comment]
I 100% agree with this.

**Comment by Denny966** [comment]
I 100% agree with this.
