### ISSUE TITLE
Downloaded 1.5.04-b123 but can't get it to work on server.

### ISSUE THREAD

**Issue by ShadyVADER** [mcMMO-Dev/mcMMO#2914]
I'm using CraftBukkit version git-bukkit-194444 (MC 1.9).

However, when I put the plugin into my FTP and transferred the files into the plugins folder, it does not show up on my server.  All of the config files show in my Control Panel, but it doesn't register on the server.   Am I using the wrong version of mcMMO, the wrong version of CraftBukkit, or do I have to use Spigot in order for it to work?

I'm really new to FTP and manually installing plugins, so I need some help.

If it helps, I use the Fluctis Minecraft Panel to run my server.

**Comment by ShadyVADER** [comment]
I just changed to using the latest Spigot build.  It hasn't changed anything.  The files still show up, but they don't work when I start the server.

**Comment by EvilOlaf** [comment]
What version of Spigot?
What version of mcMMO?
How do you assume that the files do not register? Did you restart the server to make this happen?
What does the console output looks like?


Insufficient information.

**Comment by ShadyVADER** [comment]
"[00:19:24] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-d20369f-7fc5cd8 (MC: 1.9)"

I am attempting to use mcMMO 1.5.04

The files do not register in the server.  I know this because in my server host and my FTP, the files show they are in the plugins folder.  There's an mcMMO folder with every little file and subfolder.  However, when I turn the server on, the console does not show mcMMO starting up, and there are no commands for it.  /pl shows it is not there as well.

**Comment by EvilOlaf** [comment]
Update spigot to 1.9.2
Update mcmmo to the latest available dev build.
