### ISSUE TITLE
Unarmed unaffected by spam-click?

### ISSUE THREAD

**Issue by Zath137** [mcMMO-Dev/mcMMO#2915]
The 1.9 feature that makes it so when you spam-click it does less damage doesn't affect unarmed. Unsure if intentional or bug.

**Comment by DorCoMaNdO** [comment]
1.9 did not apply the cooldown on the bare hand, it does in 1.9.2, this is not related to mcMMO

**Comment by DarwinTrue** [comment]
Looks like axes are broken too. So much OP.
