### ISSUE TITLE
Works for 5 seconds, then errors

### ISSUE THREAD

**Issue by AlHollandiyah** [mcMMO-Dev/mcMMO#2917]
I have installed McMMO on my 1.8.7 server I am currently building up, and I found this weird error. Whenever I type a command, for example /stats or /inspect or anything really, the scoreboard shows up for 1 second and disappears. If I type the command again I get an error message. If I then proceed to delete said user I can get the scoreboard to appear for 1 second again, but then I get the same error.

Here are the error messages that I plucked from my console, does anyone know what goes wrong here and how I can fix it? Is there a known plugin incompatability of sorts?

`25.04 12:42:34 [Server] [Informatie] AlHollandiyah issued server command: /stats
25.04 12:42:36 [Server] [Informatie] AlHollandiyah issued server command: /stats
25.04 12:42:36 [Server] ERROR null
25.04 12:42:36 [Server] [Informatie] org.bukkit.command.CommandException: Unhandled exception executing command 'stats' in plugin mcMMO v1.5.04-SNAPSHOT-b82
25.04 12:42:36 [Server] [Informatie] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot1.8.7.jar:git-Spigot-6d16e64-09ddd9b]
25.04 12:42:36 [Server] [Informatie] at me.incomprehendable.dev.pwp.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:98) ~[?:?]
25.04 12:42:36 [Server] [Informatie] at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:640) ~[spigot1.8.7.jar:git-Spigot-6d16e64-09ddd9b]
25.04 12:42:36 [Server] [Informatie] at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [spigot1.8.7.jar:git-Spigot-6d16e64-09ddd9b]
25.04 12:42:36 [Server] [Informatie] at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [spigot1.8.7.jar:git-Spigot-6d16e64-09ddd9b]
25.04 12:42:36 [Server] [Informatie] at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot1.8.7.jar:git-Spigot-6d16e64-09ddd9b]
25.04 12:42:36 [Server] [Informatie] at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot1.8.7.jar:git-Spigot-6d16e64-09ddd9b]
25.04 12:42:36 [Server] [Informatie] at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot1.8.7.jar:git-Spigot-6d16e64-09ddd9b]
25.04 12:42:36 [Server] [Informatie] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
25.04 12:42:36 [Server] [Informatie] at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
25.04 12:42:36 [Server] [Informatie] at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot1.8.7.jar:git-Spigot-6d16e64-09ddd9b]
25.04 12:42:36 [Server] [Informatie] at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot1.8.7.jar:git-Spigot-6d16e64-09ddd9b]
25.04 12:42:36 [Server] [Informatie] at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot1.8.7.jar:git-Spigot-6d16e64-09ddd9b]
25.04 12:42:36 [Server] [Informatie] at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot1.8.7.jar:git-Spigot-6d16e64-09ddd9b]
25.04 12:42:36 [Server] [Informatie] at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot1.8.7.jar:git-Spigot-6d16e64-09ddd9b]
25.04 12:42:36 [Server] [Informatie] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
25.04 12:42:36 [Server] [Informatie] Caused by: java.lang.IllegalStateException: Unregistered scoreboard component
25.04 12:42:36 [Server] [Informatie] at org.bukkit.craftbukkit.v1_8_R3.scoreboard.CraftObjective.checkState(CraftObjective.java:112) ~[spigot1.8.7.jar:git-Spigot-6d16e64-09ddd9b]
25.04 12:42:36 [Server] [Informatie] at org.bukkit.craftbukkit.v1_8_R3.scoreboard.CraftObjective.unregister(CraftObjective.java:104) ~[spigot1.8.7.jar:git-Spigot-6d16e64-09ddd9b]
25.04 12:42:36 [Server] [Informatie] at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.loadObjective(ScoreboardWrapper.java:374) ~[?:?]
25.04 12:42:36 [Server] [Informatie] at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.setTypeSelfStats(ScoreboardWrapper.java:299) ~[?:?]
25.04 12:42:36 [Server] [Informatie] at com.gmail.nossr50.util.scoreboards.ScoreboardManager.enablePlayerStatsScoreboard(ScoreboardManager.java:267) ~[?:?]
25.04 12:42:36 [Server] [Informatie] at com.gmail.nossr50.commands.player.McstatsCommand.onCommand(McstatsCommand.java:34) ~[?:?]
25.04 12:42:36 [Server] [Informatie] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot1.8.7.jar:git-Spigot-6d16e64-09ddd9b]
25.04 12:42:36 [Server] [Informatie] ... 15 more`

**Comment by EvilOlaf** [comment]
Your build is probably outdated. Try to get latest for 1.8.x working build and update to 1.8.8 if you don't need to especially stick to 1.8.7.

**Comment by AlHollandiyah** [comment]
I have downloaded the newest 1.8 McMMO plugin that you offer on the page, or are you referring to a dev build? Also, 1.8.7 is the 'newest' 1.8 spigot jar that my server offers. Could this be a plugin incompatability of sorts?

**Comment by AlHollandiyah** [comment]
Welp, it turned out to be a very stupid mod conflict. I unloaded all of my plugins and restarted the server multiple times, adding sets of plugins to find out the culprit. It turnes out to be 1 single setting in the 'infernal mobs' config, where it defaults the scoreboard to false. That in turn effects the scoreboard in McMMO explaining why this bug happened in scoreboard related errors. After setting this to true McMMO works fine again! Thanks for you time and efforts!
