### ISSUE TITLE
McMMO OnJoint event lag

### ISSUE THREAD

**Issue by jordanwilliams1** [mcMMO-Dev/mcMMO#2919]
When people join my server ti freezes for around 1-2 seconds, When there's 3-5 people joining it freezes my server for about 3 seconds and its a pain.

Here's my timings from paper to show its mcmmo causing it:
https://timings.aikar.co/v2/?id=e76fd7db387e46d881459e2228780a34&section=lag

This has happens on spigot as well so its not a issue on paper.

Is there a fix for this? I Don't use mysql for mcmmo by the way.

Running build: https://i.gyazo.com/9749eff9a27679ccdd878d8e4c0a90a4.png

**Comment by jordanwilliams1** [comment]
https://gyazo.com/b044876a3a9764c6cb97e35c67723031

**Comment by Tomographix** [comment]
Out of interest, what is the size of your scoreboard.dat in the world > data folder?

**Comment by jordanwilliams1** [comment]
@Tomographix https://i.gyazo.com/7384b1306b6c356e99d09fddbdb124c8.png
