### ISSUE TITLE
Treefeller ability not working.

### ISSUE THREAD

**Issue by ABNGaming** [mcMMO-Dev/mcMMO#2922]
I'm running the mcmmo version that is compatible with spigot 1.8.8 and its working fine except the treefeller plugin as the ability isnt working it says that the ability have been used but tree's arent going down, only opped people are able to use it, I tried the mcmmo.ability.woodcutting.treefeller permission but same issue, please help!

**Comment by MURD3RUS** [comment]
Check if you are using an anti-cheat/hack program.  We use NoCheatPlus on our server and had to download a fix-plugin called CompatNoCheatPlus to fix this exact issue.  Sorry if this isn't your issue, was browsing for mine and saw it.  Figured I'd comment.

**Comment by Glitchfinder** [comment]
Was this issue ever sorted out? It sounds like @MURD3RUS was likely correct, but I'd rather be sure prior to closing this issue.
