### ISSUE TITLE
Says it is outdated but it is newest version.

### ISSUE THREAD

**Issue by Buster801** [mcMMO-Dev/mcMMO#2926]
I have paid for the mcmmo plugin, however it is not working on my server. It says that the version is outdated however I am downloading the newest version their is. Here is the error it is giving me:

05.05 22:27:17 [Server] WARN [EnjinMinecraftPlugin] Your version of mcMMO is outdated! Please update here: http://dev.bukkit.org/bukkit-plugins/mcmmo/

**Comment by t00thpick1** [comment]
The latest version removed that code from the plugin, so I don't think you are on the latest version :P
