### ISSUE TITLE
Not Enabling 

### ISSUE THREAD

**Issue by Stuart74** [mcMMO-Dev/mcMMO#2927]
Running  kcauldron,cauldron,craftbukkit,mcpc,fml,forge 1.7.10
Plugin Versions I have tried 1.5.00, 1.5.04

Pretty disapointed that i paid money to get this and it simply does not work at all will not enable 

With the 1.7 version i get the below error

http://pastebin.com/dHZCkArr

When i tried the 1.5.04 i get the below error added error cause i have no mending being non 1.9 server but was hoping it would work like some other plugins that will work on multiple versions

http://pastebin.com/dHZCkArr

**Comment by t00thpick1** [comment]
Use the 1.7 version, but fix your config, the error on startup is because your config is broken somehow.  specifically the treasures.yml

**Comment by Stuart74** [comment]
i have not even touched the treasure.yml the only thing that i have touched is entering the sql details in the config.yml file so if the treasures.yml is broken then it was delivered to me broken.
