### ISSUE TITLE
New Alchemy Potion: Splash Water Extended

### ISSUE THREAD

**Issue by FatherWh0** [mcMMO-Dev/mcMMO#2943]
When sulfur is added to a mcmmo extended or level II potion it becomes splash water. Interestingly, if the gunpowder is added first then the splash potion has redstone or glowstone dust added it successfully makes a extended or level II splash potion.
I have tested this with blindness, saturation, absorbtion, wither, and resistance. Simply brew one of these potions, then add either redstone or glowstone dust, then add gunpowder. You can now splash water on your enemies.
No console errors on load or otherwise. Potions.yml regenerated back in the 1.5.04 days.
git-Paper-727 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT (don't hate)
mcmmo 1.5.05-SNAPSHOT-b136

**Comment by t00thpick1** [comment]
Try regenerating your potions.yml again I think, if it still occurs respond

**Comment by FatherWh0** [comment]
That fixed it. t00thpick1 once again proves his awesomeness. :+1:
