### ISSUE TITLE
Issue with mcmmo being unresponsive on my (1.8.8) Spigot server

### ISSUE THREAD

**Issue by DavidisaWinner** [mcMMO-Dev/mcMMO#2948]
Ok, so basically the issue I am experiencing on my server, is the mcmmo plugin is unresponsive. I downloaded the plugin and when I run /plugin on my server it shows every plugin green except mcmmo which is red. I cannot run /mcmmo at all. It is unresponsive. Please contact me asap. email is david.enoughsaid@gmail.com if you need to contact me that way.

**Comment by t00thpick1** [comment]
I need a server.log of the startup.

**Comment by DavidisaWinner** [comment]
So, when I first start up the server you want a copy of the logs?

**Comment by DavidisaWinner** [comment]
ok looking into the logs I found the issue, my copy of mcmmo was outdated, thanks for the help!
