### ISSUE TITLE
Can't find Player Profile in docs

### ISSUE THREAD

**Issue by jaspersorrio** [mcMMO-Dev/mcMMO#2949]
Hi all, been trying to use the api provided [here](https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/datatypes/player/McMMOPlayer.java#L98) but can't seem to find a PlayerProfile class at [spigot docs](https://hub.spigotmc.org/javadocs/spigot/).

**Comment by t00thpick1** [comment]
Please describe what you are trying to do.
