### ISSUE TITLE
1.10 update

### ISSUE THREAD

**Issue by renzotom** [mcMMO-Dev/mcMMO#2955]
Please, update on 1.10 spigot, it has some bugs.

**Comment by Sikatsu** [comment]
@t00thpick1

**Comment by renzotom** [comment]
He is has bad activity and don´t come here this month, what now.

**Comment by Sikatsu** [comment]
What do you mean? He didn't login for a month already, or that he's busy for this month?

**Comment by renzotom** [comment]
I mean, he didn´t login for a month. Maybe, he stop develop plugin, or is busy. Hm. You think, he login soon? This month, or next?

**Comment by Sikatsu** [comment]
I think maybe he died

**Comment by TheChampTF** [comment]
Hey

If you go read his message on spigot, he is only doing major bug fixing/updates to new version due to irl.

Please keep this in mind and wait for him to respond, as he has been doing this for many years now and a little thank you helps more than just bad comments.

**Comment by TheChampTF** [comment]
Thank you so much for the update!
