### ISSUE TITLE
mcMMO not activating.

### ISSUE THREAD

**Issue by Forgetsu** [mcMMO-Dev/mcMMO#2959]
I'm running my server through Multicraft on spigot 1.9.4. I just purchased and uploaded the .jar through FTP File Access and restarted. In game, typing /plugins shows mcMMO in red text, with my other two Bukkit plugins in green. Thanks for your time.
![mcmmoimgur1](https://cloud.githubusercontent.com/assets/20001795/16164662/71b4722a-34ad-11e6-987a-41b28615ea5c.jpg)

**Comment by EvilOlaf** [comment]
Check your server logs for errors.
