### ISSUE TITLE
Repair- takes ingots but item is not repaired.

### ISSUE THREAD

**Issue by bonzaboy** [mcMMO-Dev/mcMMO#2960]
Running a 1.10 server with bukkit, trying to repair items. The game takes the ingots, but the item is not repaired. All other skills seem to be working fine. 

Also, another issue I've had is the level up sounds are not playing. I've looked in the config and level sounds are set to true. 

Any ideas on these two issues?

TIA

**Comment by amandanicolee** [comment]
Got the same problem.
