### ISSUE TITLE
Specific player data cannot be loaded

### ISSUE THREAD

**Issue by elFlashor** [mcMMO-Dev/mcMMO#2965]
Some of the players, upon logging, receive the following error message:
"mcMMO still cannot load your data. You may want to contact the server owner."

Trying to inspect that player or reset its skills result in an error like the following:
21.06 03:10:57 [Server] INFO Caused by: java.lang.IndexOutOfBoundsException: Index: 0
21.06 03:10:57 [Server] INFO at java.util.Collections$EmptyList.get(Collections.java:3212) ~[?:1.7.0_13]
21.06 03:10:57 [Server] INFO at com.gmail.nossr50.util.player.UserManager.getPlayer(UserManager.java:94) ~[?:?]
21.06 03:10:57 [Server] INFO at com.gmail.nossr50.util.player.UserManager.retrieveMcMMOPlayer(UserManager.java:108) ~[?:?]
21.06 03:10:57 [Server] INFO at com.gmail.nossr50.util.player.UserManager.getOfflinePlayer(UserManager.java:90) ~[?:?]
21.06 03:10:57 [Server] INFO at com.gmail.nossr50.commands.experience.SkillresetCommand.onCommand(SkillresetCommand.java:70) ~[?:?]
21.06 03:10:57 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]

The users data are stored in a mysql database. That specific player is absent from the database. Even after logging off and on several times, even after a server restart. Which means nothing works, even the admin commands as, as you can see, they all produce the out of bounds exception (since no user with that name is registered... vicious circle!)

Shouldn't the player get added to the database?
A command to force a specific player to be registered by the plugin could be useful here.

**Comment by t00thpick1** [comment]
This is very interesting, could you somehow get me an example username or two, or a full server log I need more information.

**Comment by elFlashor** [comment]
I know at least one account that currently have that issue, username is Hogo_Fox .
I had several others in the past, can't remember the names.

What kind of server log are you looking for? Startup?

**Comment by elFlashor** [comment]
This is still happening, for various users on my server. It seems completely random and suddenly happens for accounts that have been used regularly before and after the issue.

Here's a veru brief log I get:
[07:10:46] [Craft Scheduler Thread - 126/ERROR]: [mcMMO] Giving up on attempting to load the PlayerProfile for like_an_employee
[07:10:46] [Craft Scheduler Thread - 126/INFO]: [A] mcMMO was unable to load the player data for like_an_employee. Please inspect your database setup.

I don't have a bigger log unfortunately, mcmmo is not very verbose with this error...

The database functions perfectly without any issue for all the other players. There's 732 registered users in the DB currently, and only 2 or 3 have issues at this time...
