### ISSUE TITLE
1.10 Blocks & Mobs

### ISSUE THREAD

**Issue by Sikatsu** [mcMMO-Dev/mcMMO#2968]
Hey,

Could you add the new 1.10 blocks and mobs to complete the 1.10 update?

**Comment by t00thpick1** [comment]
such as??????

**Comment by Sikatsu** [comment]
Mobs: Polar bear, Husk, Stray

Blocks: Magma Block, Nether Wart Block, Red Nether Brick, Bone Block

**Comment by Sikatsu** [comment]
@t00thpick1 So ?
