### ISSUE TITLE
1.10 Potion Making with mcMMO v 1.5.05-b143

### ISSUE THREAD

**Issue by quietlikeafox** [mcMMO-Dev/mcMMO#2970]
When making splash potions it takes 2 gunpowder instead of 1. I tried this out with JUST mcMMO on my server, with all of my plugins, with absolutely no plugins (which used only 1 gunpowder), with different potions ingredients... mcMMO makes it take 2 instead of just 1 for some reason. No error comes up in the console and I read through the config file and the wiki but I can't seem to find an answer.
![mcmmo potions 1](https://cloud.githubusercontent.com/assets/15848957/16387619/803bdc1c-3c63-11e6-96b4-d8a126619f14.png)
(The Potion of Healing is just 1 potion)
![mcmmo potions](https://cloud.githubusercontent.com/assets/15848957/16387535/3c27fb32-3c63-11e6-9929-84b4eeb38a54.png)

The server itself is on spigot/craftbukkit 1.10 not 1.10.2

Thank you for your time.

**Comment by t00thpick1** [comment]
Looking into it.
