### ISSUE TITLE
[mcMMO] [Debug] Console Spam

### ISSUE THREAD

**Issue by LoXR** [mcMMO-Dev/mcMMO#2971]
Im getting this spam after a player has left the server...

30.06 08:55:57 [Server] INFO [mcMMO] [Debug] Name change detected: MrTester => 
30.06 08:55:57 [Server] INFO [mcMMO] [Debug] Name change detected: MrTester => 
30.06 08:55:57 [Server] INFO [mcMMO] [Debug] Name change detected: MrTester => 
30.06 08:55:57 [Server] INFO [mcMMO] [Debug] Name change detected: MrTester => 
30.06 08:55:57 [Server] INFO [mcMMO] [Debug] Name change detected: MrTester => 
30.06 08:55:57 [Server] INFO [mcMMO] [Debug] Name change detected: MrTester => 
30.06 08:55:57 [Server] INFO [mcMMO] [Debug] Name change detected: MrTester => 
30.06 08:55:57 [Server] INFO [mcMMO] [Debug] Name change detected: MrTester => 
30.06 08:55:57 [Server] INFO [mcMMO] [Debug] Name change detected: MrTester => 
30.06 08:55:57 [Server] INFO [mcMMO] [Debug] Name change detected: MrTester => 
30.06 08:55:57 [Server] INFO [mcMMO] [Debug] Name change detected: MrTester => 
30.06 08:55:57 [Server] INFO [mcMMO] [Debug] Name change detected: MrTester => 
30.06 08:55:57 [Server] INFO [mcMMO] [Debug] Name change detected: MrTester => 
30.06 08:55:57 [Server] INFO [mcMMO] [Debug] Name change detected: LondoneShine => 
30.06 08:55:57 [Server] INFO [mcMMO] [Debug] Name change detected: LondoneShine => 
30.06 08:55:57 [Server] INFO [mcMMO] [Debug] Name change detected: LondoneShine => 
30.06 08:55:57 [Server] INFO [mcMMO] [Debug] Name change detected: LondoneShine => 
30.06 08:55:57 [Server] INFO [mcMMO] [Debug] Name change detected: LondoneShine => 
30.06 08:55:57 [Server] INFO [mcMMO] [Debug] Name change detected: LondoneShine => 
30.06 08:55:57 [Server] INFO [mcMMO] [Debug] Name change detected: LondoneShine => 
30.06 08:55:57 [Server] INFO [mcMMO] [Debug] Name change detected: LondoneShine => 
30.06 08:55:58 [Server] INFO [mcMMO] [Debug] Name change detected: LondoneShine => 
30.06 08:55:58 [Server] INFO [mcMMO] [Debug] Name change detected: LondoneShine => 
30.06 08:55:58 [Server] INFO [mcMMO] [Debug] Name change detected: LondoneShine => 
30.06 08:55:58 [Server] INFO [mcMMO] [Debug] Name change detected: LondoneShine => 
30.06 08:55:58 [Server] INFO [mcMMO] [Debug] Name change detected: LondoneShine => 

Aswell as other debug messages.

30.06 08:59:58 [Server] INFO [mcMMO] [Debug] Saving Parties... (3)

**Comment by MrProtagonist** [comment]
Im getting the same thing. Did you figure out what it was?

**Comment by LoXR** [comment]
Yeah. it was in the latest version of the plugin. Revert back to 1.5.03
