### ISSUE TITLE
(1.8) Unbreakable tag not respected

### ISSUE THREAD

**Issue by Roadhog360** [mcMMO-Dev/mcMMO#2972]
Plugin tries to take durability from Unbreakable items.
Item never breaks, but turns to a purple square.
Very annoying, please fix it for 1.8.

**Comment by Roadhog360** [comment]
Closed? Was it fixed?

**Comment by Glitchfinder** [comment]
It should be fixed as of https://github.com/mcMMO-Dev/mcMMO/commit/40b609ccd8a4a49b278c5780fbb60be3e11e814a, but I'm not sure that code is in anything other than the current dev builds.
