### ISSUE TITLE
mcMMO does not work

### ISSUE THREAD

**Issue by Weedscoped** [mcMMO-Dev/mcMMO#2973]
I have a Spigot server running Minecraft 1.7.9 and the correct version of mcMMO for it. Whenever I type ANY mcMMO command or right click, nothing happens whatsoever. Nothing appears in the console, except for the message which shows that I issued the command. I tried deleting the mcMMO folder, changing server version and plugin version (yes, they were the same every time). I tried 1.9.4, 1.7.10 and 1.7.9 - none worked. I'm afraid that the issue could be me using Spigot instead of Craftbukkit? I'm not too sure about that, I might be wrong. Also, when I start the server, looking at the console, there's not a single message about mcMMO, so it looks like it can't be found or something like that (?), but then again, the folder is created. Anyways, any help would be appreciated!

**Comment by Weedscoped** [comment]
Today I reloaded my server, and in the log, I saw "Enabling mcMMO" and a few lines later "Disabling mcMMO". That's weird...

**Comment by Weedscoped** [comment]
Anyone?

**Comment by t00thpick1** [comment]
There is literally nothing I can do without some sort of console log.   Nobody else has reported this issue its just you, and I have no information to work off of.

**Comment by Weedscoped** [comment]
[This is the server initiation log.](http://pastebin.com/ZpQTCqAy)

**Comment by t00thpick1** [comment]
Oh you are running a version from over a year ago.
