### ISSUE TITLE
Second Smelt not working in Spigot 1.10.2 and mcMMO 1.5.05

### ISSUE THREAD

**Issue by Momshroom** [mcMMO-Dev/mcMMO#2978]
This has been partially addressed before in open tickets https://github.com/mcMMO-Dev/mcMMO/issues/2934 and https://github.com/mcMMO-Dev/mcMMO/issues/2751 and we had issues with it before with the snapshot version of mcMMO and 1.9.4 with furnaces sometimes losing their second smelt functionality until completely emptied of everything and restarted, but in 1.10.2 with mcMMO 1.5.05 players with 100% second smelt chance are seeing NO or almost no second smelt at all (one player reported ONE ingot beyond what was put in, 2 others, including myself, are getting no noticable second smelt), and resetting the furnace no longer fixes it.

Our Spigot version is this:
http://prntscr.com/bpkb71

Our mcmmo version is: version 1.5.05-b143

This is our advanced.yml:
http://pastebin.com/ebNfn0Mx

**Comment by Momshroom** [comment]
Update, updated to latest dev build: http://prntscr.com/bpp0cs
No change.

**Comment by t00thpick1** [comment]
Taking a looksy

**Comment by Momshroom** [comment]
Revision:  emptying the furnaces is no longer fixing them, but breaking them and replacing them IS fixing it.
