### ISSUE TITLE
mcmmo doesn't work

### ISSUE THREAD

**Issue by beerxbeerWTF** [mcMMO-Dev/mcMMO#2993]
so i just started a server and i installed mcmmo when i do /plugins the mcmmo turns up red so it isnt working, i don't know what to do.
i already thank you for reading this

**Comment by EvilOlaf** [comment]
Check your console output for errors on startup.

**Comment by beerxbeerWTF** [comment]
this pops up
[12:12:17 ERROR]: [mcMMO] There was an error while enabling mcMMO!

what do i need to do ?

**Comment by EvilOlaf** [comment]
Restart your server. 
Then check your `latest.log` (which yo will find in your `logs` directory) for further information. If in doubt put the whole file to pastebin.com and put the link here.

**Comment by beerxbeerWTF** [comment]
http://pastebin.com/xZSTNd8N

**Comment by beerxbeerWTF** [comment]
the last build is 1.5 of mcmmo
and that is 1.5

**Comment by beerxbeerWTF** [comment]
http://dev.bukkit.org/bukkit-plugins/mcmmo/

**Comment by EvilOlaf** [comment]
```
Game version
CB 1.7.9-R0.2
```

Get a up to date build here: https://www.spigotmc.org/resources/mcmmo.2445/

**Comment by beerxbeerWTF** [comment]
tnx

**Comment by beerxbeerWTF** [comment]
it worked thank you
