### ISSUE TITLE
McMMO Won't work for me. 

### ISSUE THREAD

**Issue by Mixeyy** [mcMMO-Dev/mcMMO#2996]
Hi! I am using Minespan as my server hoster. I checked the logs on my server an NOTHING showed up on MCMMO, When I open my plugins list in MC, McMMO is red. Please help me.

**Comment by EvilOlaf** [comment]
` I checked the logs on my server an NOTHING showed up on MCMMO,`
cannot go with
`When I open my plugins list in MC, McMMO is red.`
or Minespan is garbage.

No useful information like server version or plugin version given.

If in doubt put a full startup log to pastebin and put the link here.

**Comment by Jackieeex143** [comment]
I suggest deleting the plugin and the folder it generated and downloading the latest version from here: https://ci.drtshock.net/job/MCMMO/
