### ISSUE TITLE
Can't use the plugin it's red on plugin list

### ISSUE THREAD

**Issue by sitdownsun** [mcMMO-Dev/mcMMO#3003]
I added mcMMO to my server, and it's red. The plugins on my server are: MarriageMaster, Plugman, WorldEdit, mcMMO (red of course), Floating_Items, Essentials, EssentialsSpawn, GroupManager, EssentialsChat, and Multiverse-Core.
The errors I got in console when starting it: http://pastebin.com/hQmGiGv5

Thank you for your help!

**Comment by Jackieeex143** [comment]
Which version are you using? I have almost all the same plugins as you, and mine is working fine.

**Comment by sitdownsun** [comment]
1.8.8 spigot

**Comment by sitdownsun** [comment]
Or were you asking the version of the plugin? Cause that's the most recent one.

**Comment by EvilOlaf** [comment]
Your version is outdated.

Try an older version from the history here as the newer ones supporting 1.9 and above only: https://www.spigotmc.org/resources/mcmmo.2445/history

**Comment by sitdownsun** [comment]
So I installed a later version of mcmmo, and I'm still having the same error. It says this mcmmo is for 1.7.9 but it's also the latest that's on the website I got it from.

**Comment by sitdownsun** [comment]
What version of mcmmo shoud I be using? Right now I'm using version 1.5.00-b3547

**Comment by Jackieeex143** [comment]
Download the latest stable build or latest build here: https://ci.drtshock.net/job/MCMMO/

**Comment by EvilOlaf** [comment]
This will not help but give it a try.
Support for 1.8 afaik has not been re-added yet and there a no older builds on the CI that still support 1.8
