### ISSUE TITLE
Modded logs not getting added

### ISSUE THREAD

**Issue by tincopper2** [mcMMO-Dev/mcMMO#3006]
I tried adding logs to the custom block files for logs and none of the woodcutting features work, I am able to add blocks like ores and herbalism blocks but I have tried adding both of the type of rubberwood trees from IC2 and MFR and neither will work, it does not say invalid material name in server logs either... I'm thinking it has something to do with this line of code:
`protected void loadKeys()
  {
    loadBlocks("Excavation", this.customExcavationBlocks);
    loadBlocks("Herbalism", this.customHerbalismBlocks);
    loadBlocks("Mining", this.customMiningBlocks);
    loadBlocks("Woodcutting", null);  <--See how this is null where the others have customSomethingBlocks?
    loadBlocks("Ability_Blocks", this.customAbilityBlocks);`

**Comment by tincopper2** [comment]
mcMMO.jar!\com\gmail\nossr50\config\mods\CustomBlockConfig.class
This is the qualified location of where I found this line of code.

**Comment by Glitchfinder** [comment]
Were you ever able to sort this out? I just traced through all of the related code, and it appears to work as intended. The null you pointed out is actually intentional, as woodcutting blocks are handled slightly differently.
