### ISSUE TITLE
Mcmmo Trouble with spigot 1.9.4

### ISSUE THREAD

**Issue by NexusCannon** [mcMMO-Dev/mcMMO#3013]
So I've just started up a new server, and I've installed some plugins. Mcmmo is the only plugin I have right now on my server that doesn't work. It shows up red in the plugins list, and when the commands are used, nothing shows up. Am I using the wrong mcmmo version? It's 1.5.00-b3547

**Comment by EvilOlaf** [comment]
Update mcmmo. Current build available here: https://www.spigotmc.org/resources/mcmmo.2445/
