### ISSUE TITLE
Is there a leaderboard plugin that works with mcmmo?

### ISSUE THREAD

**Issue by CanadianKing** [mcMMO-Dev/mcMMO#3014]
Like something where I can put the top people skills, maybe top 3 or something. I have seen it around

**Comment by CeIebrimbor** [comment]
Give this a go: https://www.spigotmc.org/resources/mcmmoaction.17261/

You can't necessarily hide messages, but they are FAR less evil because they don't spam chat.

**Comment by CeIebrimbor** [comment]
This one is fancy. I love it.

https://www.spigotmc.org/resources/leaderheads.2079/
