### ISSUE TITLE
The problem with shroom thumb

### ISSUE THREAD

**Issue by someguyinthecorner** [mcMMO-Dev/mcMMO#3018]
Shroom thumb's existence is a horrible one. It now takes two mushrooms to make an attempt at placing one mushroom. Emphasis on attempt. Because of shroom thumb, it isn't a 100% chance that when you place a mushroom the mushroom actually gets placed. If it doesn't fail to place you still lose both of your mushrooms! Shroom thumb is also always on so no matter what you are going to face this issue. Shroom thumb is probably the absolute WORST idea you have ever come up with in your life. Please do us all a service by taking shroom thumb behind the shed and end its misery.

**Comment by Rowen2003** [comment]
Turn shroom thumb off in your plugin.yml

**Comment by Momshroom** [comment]
Or just place your mushrooms on stone or mycelium. Or change the chance of shroom thumb in the config.
