### ISSUE TITLE
Feature request : Different world, different stats

### ISSUE THREAD

**Issue by raikenjenova** [mcMMO-Dev/mcMMO#3019]
A request that I've been wondering for my versatile server, can you add something like different stats on different world thing?
It's for Multiverse including Survival and mini MMO
Thanks a lot! =D

**Comment by t00thpick1** [comment]
So I actually have a full rewrite of mcMMO that I might release soon if I actually get the time/urge to finish it, its fully modular and API driven so this would be possible with that but not with the current versions sorry.
