### ISSUE TITLE
Aterno's mcmmo plugin not working

### ISSUE THREAD

**Issue by MrGamerPro1** [mcMMO-Dev/mcMMO#3020]
so im using aternos and mcmmo doesn't work for some reason

**Comment by EvilOlaf** [comment]
Insufficient information. Server version and software. Mcmmo version. Logs and console output.

**Comment by Knuspergamer** [comment]
Hello I have a problem with the plugin MCMMO. And although I own a CraftBukkit 1.9.2 Aternos server and wanted very much to install the plugin on the server. The MCMMO plugin only goes to version 1.7.9. I have also installed other plugins in the version and all working, only the plugin MCMMO does not work in the version. I then tried it with other versions eg in version 1.4.6 and others and it just does not. Could you possibly help me?
