### ISSUE TITLE
Build number

### ISSUE THREAD

**Issue by sigmaroot** [mcMMO-Dev/mcMMO#3022]
Small issue:

Running b173, /version mcmmo displays the following informations:

version: 1.5.07-SNAPSHOT-b${BUILD_NUMBER}

I guess 1.5.07 is dev (see commit 9ec75fb47030911477dc20c9d7be436bcf276ad2) :smile:
Oh and the build number is not displayed :smile:

Just as an information

**Comment by electronicboy** [comment]
This is to be expected when you build manually, The BUILD_NUMBER variable is filled in by the CI system. If you wanna remove that, just modify the pom before you build it, and reset the pom back to it's original whenever you gotta pull.

**Comment by sigmaroot** [comment]
I've just downloaded it from the build server :smiley:

**Comment by sigmaroot** [comment]
Build number disappeared, I'm closing.
