### ISSUE TITLE
Fishing, new mechanics, MCMMO not increasing chance anymore.

### ISSUE THREAD

**Issue by Dukisef012** [mcMMO-Dev/mcMMO#3034]
The new fishing mechanics have nothing to do with chances, they take one random number from 100 to 900 and then with each tick its lessened by 20 until it reaches 0, when it reaches zero it sends the fish. So are you actually modifying those number or you just increasing bite chance per tick is pointless?

**Comment by Dukisef012** [comment]
@t00thpick1 Can you pls comment on this issue :)

**Comment by Dukisef012** [comment]
@nossr50 what is the reason for closing? Are you droping the mechanic of increasing bite?

**Comment by nossr50** [comment]
I'm rewriting how fishing works in 2.2

**Comment by Dukisef012** [comment]
Noice
