### ISSUE TITLE
Console spamming "[mcMMO] [Debug] Name change detected"

### ISSUE THREAD

**Issue by ghost** [mcMMO-Dev/mcMMO#3035]
Hi,

I'm using latest mcMMO version, and I'm getting constantly spammed with these messages:

[mcMMO] [Debug] Name change detected

My log gets cluttered immediately (2 gigs of logs...)

**Comment by iliveforgod347** [comment]
I am having this issue as well.  It is also saying [mcMMO][Debug] Saving Parties... (2) about every 5 minutes or so.
I think the name change thing could be do to a skript I have that changes the player name so I will disable that and see what happens but I am not sure what is causing the saving parties message.
