### ISSUE TITLE
[Salvage]EnchantDowngradeEnabled not working

### ISSUE THREAD

**Issue by marat569** [mcMMO-Dev/mcMMO#3037]
Hey, I'm having a small issue with the salvage skill.

When people salvage a broken enchanted item, the enchant book will have the same enchants as the item, no loss of enchant levels. I have my YML set up so you always get a book, but as it is right now it's TOO op. 

How it works right now:
100% to get a book from salvaging
I salvage a wooden shovel with fortune 3, i get a fortune 3 book (100%)

How I would like it:
100% to get a book from salvaging
I salvage wooden shovel fortune 3, unbreaking 2, I get fortune 1 unbreaking 1 book [due to my level being low]

Here is the salvage part of my advanced.yml
http://paste.ubuntu.com/23236502/

If more information is needed, I'll post; but

**Comment by Momshroom** [comment]
I would try changing it so that  EnchantLossEnabled: true and then increasing the partial enchant rates very high and the keeping the full enchant rates low.  I haven't tried this, but it's an idea.

**Comment by marat569** [comment]
@Momshroom that would have a chance of players loosing enchants when salvaging; and I dont want that -- Unless you mean setting the % to 100% so they never loose for every rank?

**Comment by Momshroom** [comment]
Yes, or 100% minus the full enchant chance, depending on which way it's
coded.

**Comment by marat569** [comment]
so with
`            ExtractPartialEnchant:
                Rank_1: 100
                Rank_2: 100
                Rank_3: 100
                Rank_4: 100
                Rank_5: 100
                Rank_6: 100
                Rank_7: 100
                Rank_8: 100`

Will it assume since it's 100% to always give partial and never full?

**Comment by marat569** [comment]
I'm going to try 100 and get back to you <3
