### ISSUE TITLE
Change block breaking rate

### ISSUE THREAD

**Issue by djquedenfeld** [mcMMO-Dev/mcMMO#3039]
Is it possible to change block breaking rates? For example as you level up mining skill your rate would increase, but at level 1 it would be slow (maybe even a smaller than 100% value).

**Comment by EvilOlaf** [comment]
By block breaking rates you mean double drop or how fast a block could be broken?

**Comment by djquedenfeld** [comment]
How fast a drop could be broken, such as the difference in rate between a wood pick and a diamond pick breaking blocks at different speeds.

**Comment by CeIebrimbor** [comment]
Not with McMMO, no.

That is the value of leveling up the skills to get longer lasting abilities like Super Breaker. You could always decrease the cooldown time as a reward for power levels or give skill length bonuses. If you google McMMO Permissions, you will find a great deal of custom perms to add a more custom feel to your McMMO setup.
