### ISSUE TITLE
mcMMO plugin Herblore skill problem

### ISSUE THREAD

**Issue by andris155** [mcMMO-Dev/mcMMO#3040]
There is a problem with Herblore skill Double Drop ability: If i harvest the watermelons with a silktouch enchanted axe, I get the second melon in slices and not in block, like the first. I am over level 200 in Herblore, my inventory is full with melon slices very fast.

**Comment by CeIebrimbor** [comment]
Very interesting/annoying. Could you test the same concept with Diamond Ore to see if an Ore Drops and a diamond drop?

Thus proving it may be something on your server and not just a melon issue.
