### ISSUE TITLE
Tree Feller doesnt work on Dark Oak Trees

### ISSUE THREAD

**Issue by grandmen123** [mcMMO-Dev/mcMMO#3041]
I Have checked, all perms and everything are set correctly, I'm running version 1.5.05-SNAPSHOT-b133 and paper spigot version git-Paper-809 (MC: 1.10.2)

Basically the Tree Feller ability doesnt work on dark oak trees for none OPs, however it works for OPs even though perms are correct

Could you give me a hand please?

Regards,
                 Grandmen123
                 Nemesis Gaming Technical Manager

**Comment by CeIebrimbor** [comment]
Why not update to McMMO #1​73 and PaperSpigot #885 and see if it is still occurring?
