### ISSUE TITLE
Player exp gain event

### ISSUE THREAD

**Issue by cpgoss** [mcMMO-Dev/mcMMO#3042]
I would love to see something like this in the exp api or maybe even in the McMMOPlayer class. I am wanting to write a plugin that will need to know when a player gains exp, what skill the exp was gained in, and how much exp was gained. I have looked at the events and listeners and can't figure out how I would go about this. Any suggestions to help with this would be greatly appreciated!

**Comment by wysohn** [comment]
#3201
