### ISSUE TITLE
Mob_Healthbar DISABLED still displaying healthbar

### ISSUE THREAD

**Issue by ghost** [mcMMO-Dev/mcMMO#3043]
> version
> [15:53:12 INFO]: This server is running Paper version git-Paper-885 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
> [15:53:12 INFO]: Checking version, please wait...
> [15:53:12 INFO]: You are running the latest version
> plugins
> [15:53:13 INFO]: Plugins (16): AsyncWorldEditInjector, AsyncWorldEdit, ChatControl, mcMMO, Vault, MassiveCore, ProtocolLib, LibsDisguises, WorldEdit, Essentials, EssentialsChat, EssentialsAntiBuild, TrailGUI, EssentialsSpawn, WorldGuard, Factions

![8c85faa29ab88bff8e03a077fe1073cf](https://cloud.githubusercontent.com/assets/8303245/19253538/b6def4d0-8f00-11e6-827f-00d6feb6ed40.png)
![pig](https://cloud.githubusercontent.com/assets/8303245/19253564/e6494da6-8f00-11e6-850a-bb3d11c483f9.png)

**Comment by ChibbyHD** [comment]
Please reply ASAP, I would like this to be fixed.

**Comment by ChibbyHD** [comment]
Can we please get a fix for this issue?

**Comment by ShaneFromPortland** [comment]
Still an issue.

**Comment by Portanna** [comment]
Bump, still an issue
