### ISSUE TITLE
Add mcmmo 1.10 on aternos

### ISSUE THREAD

**Issue by MrGamerPro1** [mcMMO-Dev/mcMMO#3044]
i was wondering when the mcmmo 1.10 can be added on aternos, only shows 1.7.9 and older versions, they dont work for newer ones... yes ik this isn't an issue but..just wondering

**Comment by EvilOlaf** [comment]
If you cannot add plugins by hand ask ateros to do that. It's their job.
BTW since 1.8 mcmmo is a premium plugin, so this might be a reason.
