### ISSUE TITLE
Command not working

### ISSUE THREAD

**Issue by ghost** [mcMMO-Dev/mcMMO#3045]
I am doing /mining and it does enternal error
http://pastebin.com/KSESABwq this is the error in console

**Comment by ChibbyHD** [comment]
Try using the correct version of mcMMO for your server version.

**Comment by nate9790** [comment]
The 1.8 download link is offline
It has been for a long time now

**Comment by ChibbyHD** [comment]
https://www.spigotmc.org/resources/mcmmo.2445/download?version=56109
Go ahead and try that version and let me know if it resolves the issue.
