### ISSUE TITLE
Potion Item Names

### ISSUE THREAD

**Issue by grandmen123** [mcMMO-Dev/mcMMO#3047]
On the network I manage, we have a Drugwars Server, and so certain items are automatically renamed to drug names, and so we arent able to brew certain potions due to this, any chance you could make potions function on Item Data Numbers instead of names.

Ingredients in cause are Poisonous Potatos & Nether Quartz

**Comment by JayGamer128** [comment]
?

**Comment by grandmen123** [comment]
Issue has since been resolved, apologies.
