### ISSUE TITLE
misspelled wrong in acrobatics

### ISSUE THREAD

**Issue by hcjoel** [mcMMO-Dev/mcMMO#3053]
this is no bug but donno where else to put it 
when looking at the guide for dodge I found a wrong spelled word
Dodge is a passive change when you are injured in combat to HALVE the damage taken It is tied to your skill level

If anyone knows where I should put it plz tell me

**Comment by mb243** [comment]
I looked at https://github.com/mcMMO-Dev/mcMMO/wiki/Acrobatics and don't see any issues with the way it is written. Is this where you see it?
