### ISSUE TITLE
Bug with version Non Paywalled ?? Help me :( crashh

### ISSUE THREAD

**Issue by hlong1909** [mcMMO-Dev/mcMMO#3056]
This is my bug  please help me fix it , it crash my server :(
http://pastebin.com/ZQH2nqzA

**Comment by EvilOlaf** [comment]
Insufficient information. Exact build number? Server software and version?

**Comment by hlong1909** [comment]
I Run build 1.5.04 http://www.dirkocraft.net/mcMMO.jar on spigot 1.8.8

**Comment by EvilOlaf** [comment]
Support for 1.8 has been dropped quite a while ago. Update your spigot.

**Comment by hlong1909** [comment]
Iff i buy Latest 1.8 Build: 1.5.04-SNAPSHOT link  https://www.spigotmc.org/resources/mcmmo.2445/download?version=56109 , my spigot have running no crash ??

**Comment by EvilOlaf** [comment]
No.
