### ISSUE TITLE
1.11 bug

### ISSUE THREAD

**Issue by Sikatsu** [mcMMO-Dev/mcMMO#3058]
Error from 1.11:

http://hastebin.com/eyihesiney.vbs

**Comment by Nory23** [comment]
I cant see if he has the same error because when i open the link of hastebin shows empty, but i have bug too in my 1.11 server with this error

http://pastebin.com/tqsm4x4G

**Comment by Sikatsu** [comment]
Not the same error, mine had to do with particles.

Weird that it became empty tho.
