### ISSUE TITLE
Tree Skill and Roffed Forest

### ISSUE THREAD

**Issue by jiuribu** [mcMMO-Dev/mcMMO#3061]
Current mc 1.11

roffen forest is pain to chop down a tree , i have to climb every single dark oak , remove all leaves , to chop
down a single tree.

 this cap of 500 is worst idea that could be implemented ever

used before veinminer , it was capped at 10k blocks and it worked fine but 500 is nothing

16 x 16 x 2 block of wood , u cant even chop down a tall spruce tree with that low cap

please increase it to 5k blocks or go yourself to roffed forest and try hard choping a single tree there

**Comment by t00thpick1** [comment]
cap is configurable
