### ISSUE TITLE
1.11

### ISSUE THREAD

**Issue by iSkeptical** [mcMMO-Dev/mcMMO#3066]
1.10 Build of McMMO not working properly for 1.11... Leveling up skills seems to be working, but all features, such as double drops, and abilities are not working. Wondering on next build?

**Comment by iSkeptical** [comment]
Nevermind... I wasn't using the latest version of spigot and seems to be working now.

**Comment by t00thpick1** [comment]
Starting work this weekend

**Comment by Sikatsu** [comment]
Any news on this?
