### ISSUE TITLE
Potion of leaping wiki and language need to be updated to reflect change to rabbit foot.

### ISSUE THREAD

**Issue by mibby** [mcMMO-Dev/mcMMO#3069]
@t00thpick1 Since potion of leaping is made with a rabbit foot now instead of a red mushroom, wiki and language files need to be updated.

https://github.com/mcMMO-Dev/mcMMO/blob/a51585f5d0cfe08e4da3196022c3242a6b53a5fc/src/main/resources/potions.yml#L117

https://github.com/mcMMO-Dev/mcMMO/wiki/Alchemy

https://github.com/mcMMO-Dev/mcMMO/blob/a51585f5d0cfe08e4da3196022c3242a6b53a5fc/src/main/resources/locale/locale_en_US.properties#L724

Might as well also remove red mushroom from being a tier item since it isn't used for anything as far as I can tell?
https://github.com/mcMMO-Dev/mcMMO/blob/a51585f5d0cfe08e4da3196022c3242a6b53a5fc/src/main/resources/potions.yml#L27

**Comment by sigmaroot** [comment]
Yes, that's right.

I had to add both materials in the config files manually because players start complaining about that, because "The wiki says..." and so on...

Please, update the wiki OR update the potions.yml :smile:

**Comment by cunningdevil666** [comment]
Still a problem - both Wiki & in-game ./alchemy ? 5 displays red mushroom as the ingredient for the potion of leaping.
