### ISSUE TITLE
adminchat Could not pass event AsyncPlayerChatEvent to mcMMO

### ISSUE THREAD

**Issue by mikeseiku** [mcMMO-Dev/mcMMO#3070]
when using "/ac" to toggle admin chat on then send message in chat the error appear and message goes to regular chat instead of admin chat. it seems rather inconsistent sometimes there's no error and the message goes to admin chat. but if using "/ac <message>" it works fine.

http://pastebin.com/vzdrRZYW

Spigot 1.10.2 git-Spigot-de459a2-51263e9 (MC: 1.10.2)
mcMMO  #175

**Comment by t00thpick1** [comment]
175 is 1.11 compat not 1.10 compat sorry :(
