### ISSUE TITLE
Error with EntityHornedHorse

### ISSUE THREAD

**Issue by FatherWh0** [mcMMO-Dev/mcMMO#3074]
Ever since the latest update of mcmmo on my Alpha 1.2 server when we dance across rainbows unicorns no long fly out of our buttocks.  Pls see error below.
http://pastebin.com/kHHazKkg
I would expect for a premium plugin that dancing across rainbows should always result in unicorns from the posterior for all players online as well as offline. 
Pls fix a.s.a.p.
Plugin: MCMMO 1.5.07
Server: hMod Alpha 1.2

**Comment by prplz** [comment]
I lost braincells from this

**Comment by MiniDigger** [comment]
👍 for hMod support
