### ISSUE TITLE
Using abilities turns mobs and players invisible

### ISSUE THREAD

**Issue by melinstagibson** [mcMMO-Dev/mcMMO#3078]
like in this video, just that it happens to players too.

After i used an ability stuff just turns invisible

https://www.youtube.com/watch?v=mtSh0KV9NiQ

**Comment by renzotom** [comment]
I also have that issue, I think, it is maybe with that:
    # This should fix blocks being broken client side, but not server-side.
    # Enable to refresh the chunks around a player at the end of Super Breaker,
    # Giga Drill Breaker, and Berserk. Resource intensive for larger servers.
    Refresh_Chunks: true

But I am not sure, please author fix it!

**Comment by EvilOlaf** [comment]
Confirmed. It seems like  `Refresh_Chunks: ` set to `false` resolves this issue. The option does not work properly anyways...for me at least.

**Comment by renzotom** [comment]
I disabled it, but I think, it still works....
