### ISSUE TITLE
Fireworks from abilities damage the players in 1.11.2 .

### ISSUE THREAD

**Issue by ThierryKamber** [mcMMO-Dev/mcMMO#3088]
The fireworks that are shown when a player activates an ability or when ability runs out, damage the player.

Fireworks for leveling milestones have not been tested.

Note: I am aware that the fireworks can be disabled using a config option. I am reporting this to let you know about this issue.

Solution (maybe):
I'm not sure how the particles are being sent to the client currently, but wouldn't it be possible to send just the particles to the client, without the full firework effect?

**Comment by Sikatsu** [comment]
Spigot has made an API to cancel firework damage. He should be able to implement that.

**Comment by mibby** [comment]
@t00thpick1 I'd also like to see this fixed if at all possible. :)

**Comment by der71** [comment]
@t00thpick1 Any fix yet? Or do I just have to disable fireworks from now on?

**Comment by PsychoNavigator** [comment]
+1 for this.

**Comment by BlackBeltPanda** [comment]
+1 also.
