### ISSUE TITLE
Arrow ability, shouldn't interact with McMMO

### ISSUE THREAD

**Issue by Loonyy** [mcMMO-Dev/mcMMO#3091]
Hey,
I have this DaggerThrow ability where player's can shoot arrows from their hand. Issue is, McMMO thinks they're shooting the arrows from a bow and it's leveling them up in Archery and making the ability do the added damage that their Archery skill is. 

I'm wondering how I can cancel the McMMO event so that it doesn't level them up or deal the added damage?

I can share the code if needed.
~ Thanks.

**Comment by t00thpick1** [comment]
Hmmm.. I'm not sure this is possible in the current API, I will keep this in mind during this update.
