### ISSUE TITLE
MCMMO Premium -> Not working out of the box

### ISSUE THREAD

**Issue by CakeArmy** [mcMMO-Dev/mcMMO#3093]
Hello, I purchased McMMO Premium yesterday and out of the box is red in /pl an doesn't work. I tried deleting the config and re-genning and it still didn't work. Just to be clear- I didn't edit or even OPEN the config.yml or anything like that.

**Comment by EvilOlaf** [comment]
Check your console output for errors.

**Comment by CakeArmy** [comment]
http://pastebin.com/p6UDafSt

Line 111 there are some errors. Don't know what they mean though.

**Comment by CakeArmy** [comment]
its 1.8 with viaversion.

**Comment by EvilOlaf** [comment]
Get the proper mcmmo version for your server.
