### ISSUE TITLE
Mcmmo PHP

### ISSUE THREAD

**Issue by SinlesFlyer376** [mcMMO-Dev/mcMMO#3097]
Should make a Mcmmo plugin for php

**Comment by SinlesFlyer376** [comment]
Mcpe

**Comment by flatbmx** [comment]
You can use the SQL backend and query the SQL server for user stats.

**Comment by SinlesFlyer376** [comment]
Idk how to do anything

**Comment by HellFive** [comment]
_**To import from bukkit to pocketmine? Import the MCMMO from bukkit to pocketmine**_
