### ISSUE TITLE
Salvage and acrobatics not working 1.11

### ISSUE THREAD

**Issue by NJ2013** [mcMMO-Dev/mcMMO#3103]
I am trying to get salvage to work it after it was reported to me as an issue. Running spigot 1.11 along with latest release of mcmmo. It works fine for OP but for anyone else it is not working the gold anvil does not message even. I tried changing the block to see if it was a conflicting plugin that does not help. I added every permission for salvage and repair and that does not help. Both players testing this were level 39+. 

Acrobatics seems to be the same issue no error just not working and i dont have the permissions negated anywhere i know of.

Any help appreciated.

**Comment by clovisd** [comment]
I have the same problem. Players don't earn XP at all for salvage and sometimes, at random occasionally earn acrobatics.

**Comment by NJ2013** [comment]
i believe i had to open the perms for it they werent automatically granted and i had to use a different perm format that isnt posted let me check

**Comment by NJ2013** [comment]
This is what i used and it seems to work fine i might have some duplicate perms in it though
[spoiler]   
 - mcmmo.ability.*
    - mcmmo.ability.blastmining.all
    - mcmmo.ability.excavation.all
    - mcmmo.ability.fishing.all
    - mcmmo.ability.herbalism.all
    - mcmmo.ability.mining
    - mcmmo.ability.mining.doubledrops
    - mcmmo.ability.mining.superbreaker
    - mcmmo.ability.repair.all
    - mcmmo.ability.smelting.all
    - mcmmo.ability.woodcutting.all
    - mcmmo.commands.defaults
    - mcmmo.commands.inspect
    - mcmmo.commands.mcability
    - mcmmo.commands.mchud
    - mcmmo.commands.mcrank
    - mcmmo.commands.mcscoreboard.clear
    - mcmmo.commands.mcscoreboard.keep
    - mcmmo.commands.mcstats
    - mcmmo.commands.mctop
    - mcmmo.commands.mctop.all
    - mcmmo.commands.mctop.excavation
    - mcmmo.commands.mctop.fishing
    - mcmmo.commands.mctop.herbalism
    - mcmmo.commands.mctop.mining
    - mcmmo.commands.mctop.repair
    - mcmmo.commands.mctop.smelting
    - mcmmo.commands.mctop.woodcutting
    - mcmmo.commands.xplock.all
    - mcmmo.motd
    - mcmmo.skills.*
    - mcmmo.skills.excavation
    - mcmmo.skills.fishing
    - mcmmo.skills.herbalism
    - mcmmo.skills.mining
    - mcmmo.skills.repair
    - mcmmo.skills.salvage
    - mcmmo.skills.smelting
    - mcmmo.skills.swords
    - mcmmo.skills.woodcutting
[/spoiler]
