### ISSUE TITLE
MCMMO Abilities not respecting other plugins overriding ItemBreakEvent

### ISSUE THREAD

**Issue by JamieSinn** [mcMMO-Dev/mcMMO#3112]
We've noticed that regarding the abilities that damage tools, such as fishing's hooking into mobs, as well as woodcutting's tree feller, do not respect other plugins cancelling the itembreakevent. 

@andrewkm

I can put together a PR for this if needed, but I'd likely make a config option that toggles whether or not the tool is actually broken, or whether it's just set to 1 durability.

**Comment by andrewkm** [comment]
@t00thpick1 can you please have a look at this.
@Jamiesinn if possible please put together a PR.

**Comment by JamieSinn** [comment]
Looks like removing item damage in the config to 0 resolves this problem. 
Ideally it should be fixed but that's a patch for now.
