### ISSUE TITLE
Can't find the source of the problem.

### ISSUE THREAD

**Issue by Corcustos** [mcMMO-Dev/mcMMO#3116]
I recently edited the advanced.yml and after doing so there seems to be an error. I can't exactly put my finger on it, but I know it's probably me making a typo or being oblivious to something. Either way, I simply can find the problem for the life of me.

I'm using Spigot 1.8.8 and the 1.5.04-SNAPSHOT build of mcmmo.

Here is my advanced.yml: [Click](http://pastebin.com/BWshHqDR)
And here is the error message: [Click](http://pastebin.com/N51401tv)

I hope I'm not just an idiot and ended up missing something, but that's probably the case. Thanks.

Note: If I delete the advanced.yml and use the default one, mcmmo works fine. I compared the default one and my file. The ONLY difference is the changing of values, so I'm rather confused what exactly is happening.

**Comment by EvilOlaf** [comment]
mcMMO is not backwards compatible. Try an older build.

**Comment by Corcustos** [comment]
I am using the 1.8 build EvilOlaf. It works fine on 1.8. I think I may have messed something up in the config.
1.5.04-SNAPSHOT is for 1.8. http://prntscr.com/e4ye53

**Comment by EvilOlaf** [comment]
Yeah, my bad.
Try to use a YAML Validator to check your config files for syntax errors.

**Comment by Corcustos** [comment]
That was the first thing that I did, EvilOlaf. After looking at the console for hints about what might be wrong, I tried it on two different sites just to be sure. It's perfectly valid. My confusion lies in why isn't the configuration file working for mcmmo. It seems just fine to me. I opened up the default config and my editted config and kept switching between the two while scrolling to that any difference would flicker, and the only difference is the values, which are the parts that should be changed.

http://prntscr.com/e5e0fw 
http://prntscr.com/e5e0sb

**Comment by EvilOlaf** [comment]
The unleashed and defeated messages are quoted in one screenshot, on the other it is not.
That is what I've noticed however....

**Comment by Corcustos** [comment]
For some reason the YAML validator added quotes. I pasted the same config file into both of them.

**Comment by Corcustos** [comment]
Turns out the issue was that the Archery Daze chancemax has to be at least one. I'm trying to disable dazing because I'm using Mythicdrops which has the ability to cause weapons to blind and daze.

**Comment by EvilOlaf** [comment]
Glad you figured it out ☺️

**Comment by Glitchfinder** [comment]
Marking this as a feature request because our internal configs clearly need better error messages.
