### ISSUE TITLE
McMMO + Selling Items

### ISSUE THREAD

**Issue by Mineacer** [mcMMO-Dev/mcMMO#3117]
Hey guys,

When using items mid - MCMMO ability such as super breaker then auctioning the item, the item has an Efficiency VIII enchantment added to it. Is it possible to add compatability to AuctionHouse with this?

It will be really helpful!

**Comment by EvilOlaf** [comment]
As this is kind a rare case the requested implementation may not come in near future or not at all. You may have noticed that @t00thpick1 is really busy these days and cannot provide much spent time for mcMMO help yourself for a  snack because this might need a long long time to be fulfilled.

**Comment by kduggan15** [comment]
You could probably fix this just by making super breaker give the user haste opposed to efficiency

**Comment by nossr50** [comment]
This bug was fixed
