### ISSUE TITLE
hurting from firework when use like super drill 

### ISSUE THREAD

**Issue by DanielEXQ** [mcMMO-Dev/mcMMO#3120]
Since the upgrade to version 1.11.2, the use of skills such as "Super Breaker" and "Super Drill" leads to damage to the player.
At the beginning and at the end of the use of the ability, a firework is fired, which in about 75% of the cases hits the player and pulls a half heart or damages his armor. Check out this video: https://gfycat.com/BlackInfatuatedAsiaticgreaterfreshwaterclam

This also happens with other Perks as soon as one reaches a hundredth stage.
I guess you can only escape this when you continue and is hit when you stand still.

**Comment by Ironic8b498** [comment]
got same issue on my server, where the fireworks from super skills are hurting or killing players

**Comment by t00thpick1** [comment]
Out on a vacation right now, will get this when I get back monday

**Comment by t00thpick1** [comment]
Committing something now, please tell me if it works.

**Comment by t00thpick1** [comment]
*should* be fixed with:
https://github.com/mcMMO-Dev/mcMMO/commit/69151f0855ef6ec3d6f3add82519f05203bf1d9c
and 
https://github.com/mcMMO-Dev/mcMMO/commit/bb27d753b1fb0217e30cfbe6bb243014b057456a
