### ISSUE TITLE
Health Tag

### ISSUE THREAD

**Issue by ChibbyGit** [mcMMO-Dev/mcMMO#3124]
Health Tags can not be disabled, please fix. I have been asking for months

**Comment by Skillers** [comment]
And you think by saying the been asking for months they are going to do it. You can try it a different way a more appropriate. start with a thing you like about the plugin and don't finish with been asking for months that just saying that think you have more rights than others.

**Comment by ChibbyGit** [comment]
Dear Skillers,

You are obviously a fucking retarded child, amen.

**Comment by Skillers** [comment]
And still no one wants to help you.
