### ISSUE TITLE
PlayerListener::onPlayerJoin(PlayerJoinEvent)

### ISSUE THREAD

**Issue by swedsesn** [mcMMO-Dev/mcMMO#3125]
Have done some timings on my server recently and seen that PlayerListener::onPlayerJoin(PlayerJoinEvent)   takes pct tick 862.89%	total  4.75 s	   avg 431.45 ms is this a bug or am I doing something wrong? thanks in advance for the help

**Comment by FortyEffs** [comment]
I fixed this on my server by setting the mcmmo config "motd" property to false. For whatever reason this conditional statement in onPlayerJoin creates the lag spike:

        if (Config.getInstance().getMOTDEnabled() && Permissions.motd(player)) {
            Motd.displayAll(player);
        }
