### ISSUE TITLE
Ingredients not being consumed in brewing stand

### ISSUE THREAD

**Issue by Lord-Me** [mcMMO-Dev/mcMMO#3126]
I'm running the latest version od MCmmo from what I know. Its on a 1.11 spigot local server. Just put the plugin on and was testing it out. I started doing some brewing and found that for some reason it didnt consume any of the ingredients, nor did it give me any lvl. I checked in the /alchemy and it was still at lvl 0.

**Comment by bingoberra** [comment]
This
