### ISSUE TITLE
Mob_Healthbar Display_Type: DISABLED not working

### ISSUE THREAD

**Issue by shamshamm** [mcMMO-Dev/mcMMO#3127]
So , basically , i at first Under Mob_Healthbar: i had it as Display_Type: HEARTS
But then i realised it was messing with my /testfor commands so i decided to set it as Display_Type:DISABLED 
aaand ... it still shows as hearts even after restarting my server multiple times :v 

Sooo , what should i do ? :v 

Edit , changing Display_Time also doesn't change anything it still stays at the default 3 seconds

**Comment by nektaris1** [comment]
helper enabled working
hi my name is lord_of_the_kid and i like play minecraft i am verry good i would like to have a position on the helpers . 
PS. i would have loved this location . Thank you very much

**Comment by Portanna** [comment]
This is still an issue, I also tried with "/mobhealth DISABLED" but seems like nothing really happens.

This is really annoying because it messes up LibsDisguises mob disguises, adding that ugly health bar and of course blowing up every disguise.
