### ISSUE TITLE
Adding weapons from mods

### ISSUE THREAD

**Issue by Aleksej2001** [mcMMO-Dev/mcMMO#3129]
i cant seem to find a way to add weapons and tools from lotr mod by using the config, I enabled mod support in main config and downloaded the configs from mod support page and changed the id's to new ones but it doesn't work, so can someone tell me how do I add tools and weapons from other mods so that I can use skills with them thanks.

**Comment by tara81** [comment]
This is what I did. IN the Mcmmo/Mods folder , I created a file called : server.tools.yml

This is the format I used to change carpets and items into weapons:

https://pastebin.com/3prAF133
