### ISSUE TITLE
Database conversion does not work

### ISSUE THREAD

**Issue by gerardvanschip** [mcMMO-Dev/mcMMO#3130]
The instructions on the wiki state that I need to run /mcconvert database flatfile to convert from mysql to flatfile but when I do this I get a blank file.

Searching online told me that I first need to set mysql to false and then run the command but when I run the command I get "you are already running flatfile.

I tried all combos.
mysql false while server running, empty users file
mysql false and server restart, im told I already have flatfile and no conversion
mysql true while server running, empty user file
mysql true and server restart, empty user file

**Comment by gerardvanschip** [comment]
Ok, learned the hard way that the command is reversed. So its /mcconvert database mysql to go from mysql to flatfile.

Problem is that it does not convert anyone who is not logged on. I have 619 users in mysql.

**Comment by gerardvanschip** [comment]
Ok, sorted it but you guys need to update your wiki. In order to get the data over I had to first manually put every single player into the flatfile, then run the import which then populated the skills.

**Comment by tara81** [comment]
yikes , I always had truoble trying to convert to sql so i stopped trying. Now I see why.

**Comment by nossr50** [comment]
@gerardvanschip that actually sounds like a big bug I'll look into it
