### ISSUE TITLE
Salvage and alchemy custom

### ISSUE THREAD

**Issue by YumiKariTurBo** [mcMMO-Dev/mcMMO#3132]
I have been going through the salvage and potions yml files trying to figure out if you can make your own recipes and items to run through these skills. 

I have tried with salvage to add a few things but something is amiss. It errors saying that they're not recognized even after using the proper name for the item used for salvage. 

As with the potions, I was thinking if there is a way to add another tier to the potion process and add items to for more and extra powered potions. 

Thank you for your input on the subject. -Yumi

**Comment by Glitchfinder** [comment]
Are you still having issues adding things to the salvage config? If so, can you provide more information on the issue?

As for potions, unfortunately, no. The number of tiers isn't configurable, and there are no plans to change that.
