### ISSUE TITLE
Super breaker doesn't check if item is unbreakable and doesn't check if slot changed.

### ISSUE THREAD

**Issue by GotoFinal** [mcMMO-Dev/mcMMO#3135]
NOTE: not sure if this bug still exists, I use version for 1.8

There are 2 pretty annoying issues, and one of them can be even used to cheat and change ANY item type... or players can just lose their items, like mob spawn eggs etc.

## unbreakable 
Super breaker ignore unbreakable status, so after increasing durability texture of pick changes to missing one.

## Slot change
Player can change item in hand when digging, and mcmmo doesn't check for that, so player can change durability of any item, like spawn egg or slab block etc (if he will be able to break block with it, I successfully used it with egg, but due to how eggs works now, it was useless no-mob egg).

I hope this will get fixed...

**Comment by JamieSinn** [comment]
This is related to https://github.com/mcMMO-Dev/mcMMO/issues/3112
