### ISSUE TITLE
Commands Don't Respond

### ISSUE THREAD

**Issue by DaBeast893** [mcMMO-Dev/mcMMO#3137]
On the server I am running none of the commands respond when writing them.
They appear as commands when you type in /help mcMMO but when you use one of the commands nothing happens. There's no message saying that the command is unknown or invalid it just doesn't work.

MC version: 1.11.2
CraftBukkit Version: Newest
McMMO Version: Newest

**Comment by Glitchfinder** [comment]
It sounds like mcMMO may not have started properly. If you're still having this problem, can you tell me if [the latest dev build](https://popicraft.net/jenkins/job/mcMMO/) fixes it?
