### ISSUE TITLE
1.7.10 McMMO?

### ISSUE THREAD

**Issue by MCDoctor** [mcMMO-Dev/mcMMO#3138]
Hello I was wondering where I could find a version of McMMO that worked for 1.7.10, I have tried version 1.5.00 (both of them) off of the Bukkit site, and neither worked running Cauldron with FTB Infinity Evolved. 

I really enjoy the McMMO plugin and would like for my players to be able to use it with the mods on 1.7.10, my Cauldron is working and in proper order with all other plugins working (except for McMMO and Citizens). 

Thank you for your time.

http://pastebin.com/97xYQV1S

**Comment by riking** [comment]
I did the effort of recompiling the old 1.7.10 version of mcMMO. https://github.com/mcMMO-Dev/mcMMO/releases/tag/1.4.06-rerelease
