### ISSUE TITLE
New Path too Complicated vs. old advanced config

### ISSUE THREAD

**Issue by Nesseley** [mcMMO-Dev/mcMMO#3139]
Could not what so ever get this plugin to work. Tried for over an hour. 
This plugin used to be SO easy and convenient. Now it's a big mess.

All I want is to rankup my players from default to rank1 to rank2. (using a simple ontime from autorank), but this is not shown anywhere in config or explained easly.

ranks:
    Default:
        requirements:
            global time:
                value: 1h
        results:
            command: 'pex user &p group set Rank1'
^ Old config, it was SO easy. Why make this plugin too complicated to use for users. I spend alot of time setting up plugins, and im not new to this. But this plugins is really too complicated for how easy it used to be.

You dont even show how to make a "path" rankup players multiple times after diffrent requirements.

Ended up using another plugin, where it was so easy to setup it took me less then 10 minutes to understand and make it to what I wanted.

Please take some learning from this, AutoRank used to be my favorite plugin. Now I don't even wanna use it again because of this "path"config.

- Nesseley

**Comment by t00thpick1** [comment]
not mcmmo
