### ISSUE TITLE
1.11+ : New mobs/mob variants do not give XP

### ISSUE THREAD

**Issue by aeonlamb** [mcMMO-Dev/mcMMO#3142]
Title speaks for itself. With the changes to the EntityType enum in 1.11+, mobs such as zombie villagers, husks, strays, etc. do not give combat (swords, axes, unarmed, archery, potentially taming?) xp. In addition horse variants (donkeys, mules, zombie/skeleton horses) and llamas do not give taming xp. Other 1.10 mobs do give combat xp (polar bears), but the rest are broken and give none. I've tried manually adding these entities to my experience.yml file and the plugin automatically regenerates the config file removing the values it doesn't recognize. I'm using the latest beta version available on paper 1.11.2.

**Comment by t00thpick1** [comment]
Fixed
