### ISSUE TITLE
Party and Party chat bugs

### ISSUE THREAD

**Issue by Metisuneatn** [mcMMO-Dev/mcMMO#3143]
So on our server we have one world that has mcmmo disabled (by removing the default perms in the world). Players state that when they go there they cant use party chat (well yea its disabled) but once they leave it doesnt work again. They have to relog to get it to work. Also I believe they somehow join the same party several times (each message will send to them 4-5 times) with this per world issue.

**Comment by Glitchfinder** [comment]
Is this an issue you're still running into? If so, is it resolved by [the latest dev build](https://popicraft.net/jenkins/job/mcMMO/)?
