### ISSUE TITLE
Using MobArena with McMMO

### ISSUE THREAD

**Issue by MeesterPlusser** [mcMMO-Dev/mcMMO#3145]
I'm currently building a new server and i have a great plan for it, ofcourse it includes McMMO but i've encountered a slight problem. I want to use one of the Hardcore options from McMMO so you lose stats on death, but dying in MobArena is almost certain.

So could there be an option that stats are only lost when killed by another player? And not lose stats when killed by a monster or not lose stats when die in MobArena?

Thanks in advance!

**Comment by tara81** [comment]
I dont think so but an option could be to place mob arena in a different world and use different permissions ? Just a guess probably won't work

**Comment by Glitchfinder** [comment]
I'm going to leave this open for the moment, but for more information, see #2370.
