### ISSUE TITLE
McMMo won't load after a restart

### ISSUE THREAD

**Issue by tara81** [mcMMO-Dev/mcMMO#3146]
McMMO V: 1.5.07 and 1.5.06 (tried both)

Issue: Mcmmo doesn't load after a restart. It says something about the parties file. So i delete the file. Then the next restart it won't restart unless I delete the file again.

Error Log: https://pastebin.com/dgLeJxgK

Parties file that doesn't load:  http://www.mediafire.com/file/vfdt763bx73b05v/parties.yml

**Comment by WyRe** [comment]
What's your server brand and version? Maybe would be much more helpful the complete server log.

**Comment by EvilOlaf** [comment]
mcMMO is not backwards compatible, so my guess is your mcMMO version is too new for your 1.9 server. Try an older build.

**Comment by tara81** [comment]
It says on the main page that version 1.5.06 is latest for 1.9

1.5.06 -- the same glitch happens with this version also !
