### ISSUE TITLE
Where do I get my download?

### ISSUE THREAD

**Issue by AncientTom** [mcMMO-Dev/mcMMO#3148]
I just purchased mcMMO and didn't get a download or a link to download it. How do I get my copy of mcMMO?

**Comment by dweSheppard** [comment]
On the overview page of MCMMO or under "Resources" > "Purchased Resources".

https://www.spigotmc.org/resources/mcmmo.2445/
https://www.spigotmc.org/resources/purchased

**Comment by Glitchfinder** [comment]
If you still haven't had the download added to your resources, you should [contact Spigot](mailto:support@spigotmc.org) and have them fix that for you. And while I know this more than a bit late, if you have any trouble accessing the download you can always try one of the latest dev builds [here](https://popicraft.net/jenkins/job/mcMMO/).
