### ISSUE TITLE
Invisible block | Giga Drill Breaker or Super Breaker

### ISSUE THREAD

**Issue by dweSheppard** [mcMMO-Dev/mcMMO#3149]
If a player use the Giga Drill Breaker or Super Breaker, the last 4-6 blocks ar invisible for the player.

**Comment by EvilOlaf** [comment]
Known issue which has been there for years now.
Set `    Refresh_Chunks: true` in your `config.yml`.

**Comment by dweSheppard** [comment]
When I activate this function, players see the items that are dropped from a block, which have already been collected.

**Comment by FrukTik** [comment]
I set Refresh_Chunks: true in my config.yml.
But If a player use the Giga Drill Breaker or Super Breaker, the last 4-6 blocks ar invisible for the player.

**Comment by pvprangergod** [comment]
reduce the enchant effect and increase the duration, this will probably stop lag without nerfing it

**Comment by Volander** [comment]
How do I reduce the enchant effect?

**Comment by Glitchfinder** [comment]
Advanced,yml, Skills->General->Ability->EnchantBuff is the number of levels of Efficiency added. There isn't currently a minimum configurable time for abilities, but the other setting in that same grouping lets you change how many levels it takes to add a second to the ability duration.
