### ISSUE TITLE
How to customize the enchantments found in fishing?

### ISSUE THREAD

**Issue by CookieGamerPT** [mcMMO-Dev/mcMMO#3151]
I have a server in which some incantations that are achieved in fishing, become something without function.
Then I'd like to remove them. Is it possible to do this in any way?

**Comment by CookieGamerPT** [comment]
Thanks for the response and hope this is helpful to other people.
Because I do not have Minecraft Server anymore ;)

**Comment by Glitchfinder** [comment]
Yeah, I came back to about four years of open issues on this tracker. I'm digging through it fairly slowly, but I want to figure out what there is in terms of relevant bugs and feature requests. This might end up helping other people in the sense that, once I've got the tracker mostly sorted, I can start addressing bugs and feature requests.
