### ISSUE TITLE
Mcmmo scoreboard shows under a sec

### ISSUE THREAD

**Issue by mathiaslk** [mcMMO-Dev/mcMMO#3152]
When I level up or use any commands that have anything to do with scoreboard it shows on the screen for under a sec,

Not sure what can be the reason, I'm using version 1.5.04 and sure if there is a fix out for it

**Comment by Chewsterchew** [comment]
Are there any other scoreboard plugins? When I had featherboard, it stayed for a second then reappeared, I have to turn featherboard off then it works fine.

**Comment by mathiaslk** [comment]
I don't use any other scoreboard plugins

**Comment by Zazalanz** [comment]
Yo dood, I am having the same issue can this guy get a response!

**Comment by Glitchfinder** [comment]
Is this an issue you're still running into? If so, does [the latest dev build](https://popicraft.net/jenkins/job/mcMMO/) fix it?
