### ISSUE TITLE
Axes- Critical hits.

### ISSUE THREAD

**Issue by Barbarx** [mcMMO-Dev/mcMMO#3153]
Hello. i using with my script my own crit. hits system where i can use custom items with it.So i wanna disable critical hits. when i do in advanced.yml ChanceMax: 0.00 so i mcmmo didnt work. so can i disable crit. hits in axes?
Sorry for my bad english

**Comment by Glitchfinder** [comment]
If you want to prevent players from using the mcMMO critical hits feature for the Axes skill, you can deny this permission: `mcmmo.ability.axes.criticalhit`
