### ISSUE TITLE
Tradução

### ISSUE THREAD

**Issue by N0CRYB4BY** [mcMMO-Dev/mcMMO#3155]
Para português o plugin está com traduções erradas, por exemplo [[amarelo]Acrobacia upou para o nivel 2, gostaria que arrumasse ou me ensinasse a arrumar, pois ja abri com winrar e não encontro uma parte de tradução

**Comment by Chewsterchew** [comment]
Hello! Here are the language files: https://github.com/mcMMO-Dev/mcMMO/tree/master/src/main/resources/locale
Feel free to make a Pull Request to make any changes,

**Comment by BigMrBad** [comment]
Clica com o botão direito no mcMMO.jar e clique em "Abrir como". Depois, abre a "src", depois a "main", depois "resources" e por fim, "locale". Você tem 2 opções, arrumar os erros do "locale_pt_BR" (que eu não recomendo, pois o arquivo foi traduzido por um gringo) ou traduzir 100% o "locale_en_US" (que eu super recomendo).

Note que ao abrir os dois arquivos, o pt_BR tem apenas 200 linhas e já no en_US tem 900. Então mesmo que você resolva apenas os erros de tradução do pt_BR, algumas coisa continuarão em inglês. Aí vai de ser gosto.

Para editar é simples: Segura e puxa o arquivo para fora no winrar, isso vai criar uma cópia. Abra o arquivo em um editor de texto puro. Após alterar o que quiser, jogue o arquivo para dentro do winrar novamente. Ele vai perguntar se pode substituir, e você clica em "sim" sem medo.
