### ISSUE TITLE
Lore and Custom names with treasures

### ISSUE THREAD

**Issue by Metisuneatn** [mcMMO-Dev/mcMMO#3163]
I had found an old post saying Custom_Name and Lore were added. I tested these out and got custom name to work, but you cannot add color code to it and the lore actually does not add. Making it easy for a player to just rename an item to that which defeats the purpose. 

1.11.2 latest version

**Comment by VoxPopuliZombiemold** [comment]
Any update on this? mcMMO has a really archaic implementation of treasures.

Not only is the method for adding lore not working, you can't seemingly have more than one of any given item material within treasures.yml either.

For instance, let's say I wanted to create a "Red Diamond" and a "Blue Diamond" in treasures.yml, using "Custom_name", mcmmo will only accept the last most item defined for that material.

**Comment by t00thpick1** [comment]
I can possibly grab this in a few days.  I've been trying to get the configurations more robust and future proofed(so I need to do less work when new items/mobs are added) so this is on my list

**Comment by dkhawser** [comment]
For anyone who is interested, I was not able to get Lore to work, but I was able to make Colored Text for the item names to work. Instead of using the & symbol for the color codes, you have to use the § symbol

**Comment by Glitchfinder** [comment]
There seem to be some issues with the lore and item name tags at the moment. I'll look into it once I have some time.
