### ISSUE TITLE
Killing orphans

### ISSUE THREAD

**Issue by JBlackbean** [mcMMO-Dev/mcMMO#3164]
Sorry i am not savy with code or anything. is there anyway of switching off "killing orphans" message that keeps popping up in console?

Thanks
Bean

**Comment by JBlackbean** [comment]
bump

**Comment by t00thpick1** [comment]
Err.. it only happens on startup and it refers to the removal of "orphaned" table values where some tables have values for a given keys, but the primary table doesn't.  I.e. their "parent" row is missing.
