### ISSUE TITLE
Won't work

### ISSUE THREAD

**Issue by Youtube-Gman** [mcMMO-Dev/mcMMO#3165]
I'm trying to add mcmmo to my server and I don't know why it won't add

**Comment by Sargee** [comment]
same

**Comment by EvilOlaf** [comment]
Insufficient information.

**Comment by Glitchfinder** [comment]
Is this still an issue you're running into? If so, does it still happen on [the latest dev build](https://popicraft.net/jenkins/job/mcMMO/)?
