### ISSUE TITLE
unable to load profile

### ISSUE THREAD

**Issue by PhanaticD** [mcMMO-Dev/mcMMO#3167]
some players are getting this problem https://images.discordapp.net/.eJwFwcENwyAMAMBdGAADKWCyRgeoEEEQKcEIO6-qu_fuq551qV11kck7wHFyoXVoFlq5Vd2I2lXzPFkXuiGL5NLvOoTBRnQBI1qMPvktBA-bSegtuogxOTThZeBdVq2DO8nH6Tma-v0BvowkoA.kvtzfQcaxLM62HhP9SlPGynkBoU

**Comment by Glitchfinder** [comment]
Is this still an issue you're running into? If so, is it resolved by [the latest dev build](https://popicraft.net/jenkins/job/mcMMO/)?
