### ISSUE TITLE
Xp infinite proliferation bug And Double Drop Bug

### ISSUE THREAD

**Issue by Noahtaro** [mcMMO-Dev/mcMMO#3171]
*link removed*

How can i fix it..

Coordinate values only in certain places
This bug will be activated

Sorry I have bad english skill
Japanese bugs video
*link removed*

plz fix it..

**Comment by Glitchfinder** [comment]
This is fixed as of https://github.com/mcMMO-Dev/mcMMO/commit/be2de1d487a2390b227528866dedf96d0cd60941.
