### ISSUE TITLE
mcmmo disabling automatically 

### ISSUE THREAD

**Issue by Sprungente** [mcMMO-Dev/mcMMO#3173]
Hello people

at first: Thanks you for developing this plugin

On my server mcmmo will disabling it self after some times with an Error

https://pastebin.com/NbK9a7cc

Data's will save on mysql

Server is running on Bungeecord (((This server is running BungeeCord version git:BungeeCord-Bootstrap:1.11-SNAPSHOT:bfab8a1:1230 by md_5)))  and servers with spigot (((This server is running CraftBukkit version git-Spigot-3fb9445-fecf4b4 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT) ))) 

I use mcmmo's newest dev build 

What's my problem?

**Comment by Glitchfinder** [comment]
Is this still an issue you're running into? If so, is it resolved by [the latest dev build](https://popicraft.net/jenkins/job/mcMMO/)?
