### ISSUE TITLE
Minecraft 1.12-pre2

### ISSUE THREAD

**Issue by TheChampTF** [mcMMO-Dev/mcMMO#3174]
Hey

On latest version (Pre version released from Spigot) I'm getting http://paste.yu8.me/?d6067a72a1895aea#e4GBH2qEuYoqji6NkWQKkOMdpPNsSRh2uA23DEUsjQI=

Just giving you a heads up before 1.12 is released

Looks like this pull request might fix it [here](https://github.com/mcMMO-Dev/mcMMO/pull/3175)

**Comment by Legoman99573** [comment]
can confirm

**Comment by mrfloris** [comment]
mcMMO is definitely not working with 1.12-pre5 at this point.

**Comment by Legoman99573** [comment]
@mrfloris I would presume it is dead at this point as well. Welp, good while it lasted.

**Comment by Ironic8b498** [comment]
Hope you are working hard in updating your plugin to run in 1.12.

**Comment by krustymk** [comment]
The lack of update/comment made by a dev is worrying

**Comment by Zrips** [comment]
I think dev will fix this issue when he gets informed about directly. Its like 1 min fix.

**Comment by LogGits** [comment]
Guys, the plugin works fine. Download the latest developer build from the jenkins which can be found here https://ci.drtshock.net/job/mcMMO
