### ISSUE TITLE
A bug with  mcMMOAction 1.3

### ISSUE THREAD

**Issue by DanielTravi** [mcMMO-Dev/mcMMO#3177]
Error: 
23.05 15:36:19 [Server] ERROR Unhandled exception number 64 occured in onPacketSending(PacketEvent) for mcMMOAction
23.05 15:36:19 [Server] INFO java.lang.NoSuchMethodError: com.comphenix.protocol.events.PacketContainer.getChatTypes()Lcom/comphenix/protocol/reflect/StructureModifier;
23.05 15:36:19 [Server] INFO at com.github.games647.mcmmoaction.MessageListener.onPacketSending(MessageListener.java:37) ~[mcMMOAction.jar:?]
23.05 15:36:19 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.2.1]
23.05 15:36:19 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.2.1]
23.05 15:36:19 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:608) [ProtocolLib.jar:4.2.1]
23.05 15:36:19 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:584) [ProtocolLib.jar:4.2.1]
23.05 15:36:19 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:309) [ProtocolLib.jar:4.2.1]
23.05 15:36:19 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:269) [ProtocolLib.jar:4.2.1]
23.05 15:36:19 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:396) [ProtocolLib.jar:4.2.1]
23.05 15:36:19 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77) [ProtocolLib.jar:4.2.1]
23.05 15:36:19 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:362) [ProtocolLib.jar:4.2.1]
23.05 15:36:19 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:330) [ProtocolLib.jar:4.2.1]
23.05 15:36:19 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.2.1]
23.05 15:36:19 [Server] INFO at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.2.1]
23.05 15:36:19 [Server] INFO at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:194) [spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
23.05 15:36:19 [Server] INFO at net.minecraft.server.v1_11_R1.NetworkManager.sendPacket(NetworkManager.java:143) [spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
23.05 15:36:19 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.sendPacket(PlayerConnection.java:1090) [spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
23.05 15:36:19 [Server] INFO at de.robingrether.idisguise.management.channel.InjectedPlayerConnection1111.sendPacket(InjectedPlayerConnection1111.java:71) [iDisguise.jar:?]
23.05 15:36:19 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:147) [spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
23.05 15:36:19 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:154) [spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
23.05 15:36:19 [Server] INFO at com.gmail.nossr50.runnables.skills.ToolLowerTask.run(ToolLowerTask.java:27) [mcMMO.jar:?]
23.05 15:36:19 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
23.05 15:36:19 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot1.11.2.jar:git-Spigot-7d78b81-a6d8fa2]
23.05 15:36:19 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
23.05 15:36:19 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]

**Comment by LogGits** [comment]
update your protocollib.

**Comment by DanielTravi** [comment]
ok
