### ISSUE TITLE
Eating food with your left hand slot will not give you Herbalism's Farmer's Diet's bonus

### ISSUE THREAD

**Issue by TBlazeWarriorT** [mcMMO-Dev/mcMMO#3181]
Eating food with your left hand slot will not give you Herbalism's Farmer's Diet's bonus.
E.G. If you have Herbalism at 1000 and eat Bread using your left (F) hand slot, you will only refill 2 hunger bars (4-5 hunger) instead of 5 bars (10 hunger).

**Comment by Glitchfinder** [comment]
Confirmed. Working on this right now.

**Comment by Glitchfinder** [comment]
Looking into this further, there's a quick but bad fix that would potentially allow one food to override another, or there's a proper fix I can't do right now, where tracking is set up to figure out which hand was used. There are alternative fixes, such as switching to the PlayerItemConsumeEvent, but a switch like that also requires some in-depth work and changes.
