### ISSUE TITLE
McMMO Skill problem

### ISSUE THREAD

**Issue by asdlol911** [mcMMO-Dev/mcMMO#3182]
Hello!
I am asdlol911 from the TheOld-Crafters hungarian server group.
We got a little problem with the McMMO.
When you use an McMMO skill in the plotme world, the Item frames, mobs and players become invisible near you, until you die or relog.
Server version: Paper build 1104 (MC: 1.11.2)
Minecraft launcher: Shiginima Launcher, Team Extreme Launcher
First picture is after using the McMMO skill (Berserk) in the plotme world. Sercond is after relogging.
![2017-05-26_15 16 34](https://cloud.githubusercontent.com/assets/17855326/26559591/e34f33f2-44b0-11e7-8bb0-fbbf3f82c0d5.png)
![2017-05-26_15 17 17](https://cloud.githubusercontent.com/assets/17855326/26559596/e6c737be-44b0-11e7-83ff-6a0a6d4969f2.png)

**Comment by Glitchfinder** [comment]
Is this still an issue you're running into? If so, is it resolved by [the latest dev build](https://popicraft.net/jenkins/job/mcMMO/)?
