### ISSUE TITLE
Mcmmo for 1.7.10?

### ISSUE THREAD

**Issue by Sargee** [mcMMO-Dev/mcMMO#3189]
I've looked everywhere and I cant find a mcMMO for 1.7.10. Is there one? If so where can I find it.

I've only found mcmmo for 1.6.4 1.7.9 and 1.8+ but no 1.7.10.
I'm trying to get mcMMO for my server but no luck. I've tried to use the 1.7.9 and 1.8 versions but it didn't work it automatically disabled it and when I tried /pl mcMMO was red.

**Comment by EvilOlaf** [comment]
Then it is bad luck. mcMMO is not backwards compatible and probably will never be. Sorry.

**Comment by Sargee** [comment]
but shouldn't there be at least an old version that was created for 1.7.10

**Comment by EvilOlaf** [comment]
If you cannot find a build on dev bukkit or spigot that works for you then there is none. Quite a while ago a new jenkins build server has been set up (due to fail I guess). All old builds are lost.

**Comment by Sargee** [comment]
oh ok :/ thanks

**Comment by riking** [comment]
I recompiled the old version of mcmmo for 1.7.10 (required removing dead metrics code):
https ://github.com/mcMMO-Dev/mcMMO/releases/tag/1.4.06-rerelease
