### ISSUE TITLE
mcMMO for 1.12?

### ISSUE THREAD

**Issue by TomTheMan2016** [mcMMO-Dev/mcMMO#3190]
With 1.12 here, im ready to upgrade my server, but i need 1.12 mcMMO. can anyone tell me when it will be here? thanks.

**Comment by hamcoremusic** [comment]
I'm on the same page. 1.12 support please!

**Comment by LeChatP** [comment]
Same Please <3 We love ur work <3

**Comment by LogGits** [comment]
Its already out download a dev build from the jenkins: https://ci.drtshock.net/job/mcMMO
