### ISSUE TITLE
please add crackshot support in some way

### ISSUE THREAD

**Issue by chillerkraft** [mcMMO-Dev/mcMMO#3193]
https://dev.bukkit.org/projects/crackshot
https://www.spigotmc.org/resources/%E2%96%91-crackshotplus-%E2%96%91-1-8-x-1-12-x-%E2%96%91.18085/
they both have a viewable api
i just noticed when i switched projectiles to arrows for the guns that it counts as archery and levels u up Really quickly

**Comment by bc-hill** [comment]
I would love to see some kind of gun skill added to MCMMO.  Where your accuracy would increase, the more you use guns.  Crackshot integration would be perfect for me.
