### ISSUE TITLE
Lag ScoreboardWrapper$ScoreboardChangeTask(Single) 6556 pct tick ....

### ISSUE THREAD

**Issue by diolegend** [mcMMO-Dev/mcMMO#3194]
https://timings.spigotmc.org/?url=racikeguhu

What is that ..?

**Comment by diolegend** [comment]
I have upgraded
https://timings.spigotmc.org/?url=jagetanuwi

16900 pct ticks

**Comment by Glitchfinder** [comment]
Unfortunately, the timings are gone so I can't get a good look at those. Is this still an issue you're running into, and, if so, is it fixed in [the latest dev build](https://popicraft.net/jenkins/job/mcMMO/)?
