### ISSUE TITLE
Toggling mcmmo effects

### ISSUE THREAD

**Issue by nayfaan** [mcMMO-Dev/mcMMO#3196]
would like to see a command implemented where people can use to toggle the mcmmo buff on oneself (i.e. temporarily return to vanilla state) and can use the same or another command to re-enable the mcmmo effects on oneself.

Could be useful on servers with mcmmo where we want an area for fair vanilla pvp in a certain area, and players can toggle their mcmmo skills off and go in there to fight

**Comment by nayfaan** [comment]
#FeatureRequest

**Comment by pvprangergod** [comment]
https://github.com/mcMMO-Dev/mcMMO-WorldGuard
