### ISSUE TITLE
Axes, tree dissapears instead of dropping blocks. 1.12 (Bug)

### ISSUE THREAD

**Issue by Sollembum78** [mcMMO-Dev/mcMMO#3197]
As title says, when you use tree feller skill trees just dissappear, no drops or anything, log blocks are just gone. I have latest 1.12 server and latest build of mcmmo to date.

**Comment by Pearlyglow** [comment]
I am also experiencing this issue. My server is also 1.12 and I have the latest build for Mcmmo.

**Comment by t00thpick1** [comment]
Investigating

**Comment by Pearlyglow** [comment]
My issue has been resolved. I managed to figure it out. In the configuration for mcMMO it will say 'tree feller threshold: 500' change that to a higher number. Along with that if you have fast async world edit you need to turn the limit ticker off. If it remains on, it will stop tree feller from dropping blocks. These are the 2 things I needed to change in order for it to work on my server. I hope this helps anyone else experiencing this issue.

**Comment by Sollembum78** [comment]
Just so you know, method suggested by @Pearlyglow fixes the problem. It helped me too.
