### ISSUE TITLE
party issue

### ISSUE THREAD

**Issue by CakeLady** [mcMMO-Dev/mcMMO#3198]
I am having an issue with some players not being able to leave particular parties.  Take my character for example, I can leave the party and join another, but as soon as i log out and log back in, it puts me right back in the original party. I cant disband that party because I am not the party leader and that player is not active, so I am 100% stuck in that party. I know of at least two other players with this same problem.  Is there any way to force a party to disband? Maybe add an admin command to force disband a party?

**Comment by Glitchfinder** [comment]
Is this still an issue you're running into? If so, is it resolved by [the latest dev build](https://popicraft.net/jenkins/job/mcMMO/)?
