### ISSUE TITLE
Unarmed

### ISSUE THREAD

**Issue by Truthm** [mcMMO-Dev/mcMMO#3199]
You can't level up your unarmed by fighting mobs.

**Comment by pvprangergod** [comment]
works for me in 1.12, make sure to be not holding any item, try to level up in a new world perhaps

**Comment by Glitchfinder** [comment]
Is this still an issue you're running into? If so, is it fixed in [the latest dev build](https://popicraft.net/jenkins/job/mcMMO/)?
