### ISSUE TITLE
mcMMO killing wither in just 10 (unarmed) clicks?

### ISSUE THREAD

**Issue by FrankHeijden** [mcMMO-Dev/mcMMO#3202]
All mobs etc can be killed within almost 3 clicks by hand.... Is there a way to solve this? bc killing a wither with just 10 clicks.... is just nah

**Comment by pvprangergod** [comment]
use the config and nerf unarmed

**Comment by Glitchfinder** [comment]
As noted, Unarmed is configurable. You'll want to look in config.yml and advanced.yml.
