### ISSUE TITLE
Health bar become villager's name

### ISSUE THREAD

**Issue by Playerian** [mcMMO-Dev/mcMMO#3203]
After I cure the zombie villager, health bar has become villager's name and the health bar keeps showing
![bug pic](https://user-images.githubusercontent.com/29447547/27265409-fd5a6b88-5449-11e7-9c0a-5cbad9115e35.png)

**Comment by Glitchfinder** [comment]
Is this a bug you're still running into? If so, does it still happen on [the latest dev build](https://popicraft.net/jenkins/job/mcMMO/)?
