### ISSUE TITLE
Change Ability Length

### ISSUE THREAD

**Issue by hamcoremusic** [mcMMO-Dev/mcMMO#3214]
Hi there!

I was just wondering how I would go about changing the time length of an ability (i.e Tree Feller). Right now I'm sure it is 2s and increases by 1 every 50 levels. How can I change the base length and level increase value (i.e +1s every 15 levels or +5s every 50 levels).

Thanks!

**Comment by pvprangergod** [comment]
the first setting at the top of advanced.yml config

**Comment by SpencerMT** [comment]
Just going to bump this, I'm unable to find this in the advanced.yml what is it called? as I would like to increase the duration of the ability.
