### ISSUE TITLE
[Feature Request] Signs

### ISSUE THREAD

**Issue by hamcoremusic** [mcMMO-Dev/mcMMO#3219]
Hello!

I would love to see the implementation of signs natively in your plugin just like Jobs Reborn does. It would be cool to have a top sign that showed you the top power levels or even skill specific levels. Having the ability to place heads above the signs would be awesome too! Also, skill signs that when clicked show what your level is and perks (i.e the same as typing /mining or /archery).

I really hope you guys could add this in natively so I don't have to play around with stupid placeholders and incompatibility issues!

Thanks!

**Comment by nossr50** [comment]
Use PAPI for this
