### ISSUE TITLE
New jenkins with maven repository

### ISSUE THREAD

**Issue by sgdc3** [mcMMO-Dev/mcMMO#3222]
Hello, i just wanted to tell you that i added mcMMO to the build jobs on my jenkins server, it also provides a simple and automatic maven repository.

Jenkins job: http://ci.xephi.fr/job/mcMMO/
Maven: http://ci.xephi.fr/plugin/repository/everything

**Comment by games647** [comment]
BTW: The job no longer exists.

**Comment by sgdc3** [comment]
@games647 I'll readd it  if needed, not a problem.

**Comment by sgdc3** [comment]
@Glitchfinder if you still need a build server i'll readd the job asap ;)

**Comment by Glitchfinder** [comment]
It's fine. We've got one going [right here](https://popicraft.net/jenkins/job/mcMMO/) at the moment.

**Comment by games647** [comment]
@Glitchfinder What's the Maven repository URL for that? It looks like it only builds the project, but doesn't provide a Maven repository.

**Comment by sgdc3** [comment]
@Glitchfinder i can setup it in 5 minutes if you agree.

**Comment by Glitchfinder** [comment]
If you like, yes.

**Comment by sgdc3** [comment]
Job url: https://ci.codemc.org/view/Author/job/mcMMO-Dev/job/mcMMO/
Repository: https://repo.codemc.org/repository/maven-public/

Sorry for the delay i was very busy xD @games647 @Glitchfinder
