### ISSUE TITLE
Tree Feller giving less wood than deserved

### ISSUE THREAD

**Issue by hamcoremusic** [mcMMO-Dev/mcMMO#3227]
Hi there,

While using the latest build of McMMO (1.5.08), my players are not getting the right amount off wood after using tree feller. We put it to the test; if a player plants 15 trees and used bonemeal on them to grow them, once Tree Feller is activated and they clear all 15 trees, they only recieve 15 raw wood.

**Comment by Glitchfinder** [comment]
Is this still an issue you're having, and, if so, is it resolved by [the latest dev build](https://popicraft.net/jenkins/job/mcMMO/)?
