### ISSUE TITLE
(Solved) When people got Level up , they will get kicked

### ISSUE THREAD

**Issue by Kuroyabumozu** [mcMMO-Dev/mcMMO#3232]
as title I'm using PaperSpigot 1.11.2, and host in McProHosting
in the before there was fine to level up with McMMo
but I don't know why and what time it become like that
when people got level up however any skills they will get kicked and shows this msg
> <img src="https://i.imgur.com/gs5HSxR.png"></a>

and if you type /mctop -> /mcsb keep everything will be fine..
but I don't know why when I use my private computer it is no problem...
does someone has solution can give me ? pls

**Comment by Xardas88** [comment]
1)open and control the console of bungeecord
2)there is a scoreboard that will get kick
3)find and delete it

**Comment by Kuroyabumozu** [comment]
I found this from logs of bungee console.
https://paste.ubuntu.com/25089198/

but I don't even know what thing makes this happen how can I delete it?

**Comment by Xardas88** [comment]
do this command on your server spigot
/scoreboard remove num

**Comment by Kuroyabumozu** [comment]
No, it does not work ..
> <img src="https://i.imgur.com/v4bGu79.png"></a>

**Comment by Xardas88** [comment]
yes it is
Sorry I have confused the commands

**Comment by Kuroyabumozu** [comment]
yeah and can you tell me what is the num means?

**Comment by Xardas88** [comment]
nothing. It could be an object created by you by mistake

**Comment by Kuroyabumozu** [comment]
ok thank you so very much for helping me solve it out :)
