### ISSUE TITLE
Problem when register the listener (API)

### ISSUE THREAD

**Issue by FabioZumbi12** [mcMMO-Dev/mcMMO#3233]
Hi,
I am the owner of RedProtect and i hook into skills events.
Recently i having this issue: http://prntscr.com/fv8pjd

This is the line of error: https://github.com/FabioZumbi12/RedProtect/blob/master/RedProtect-Spigot/src/main/java/br/net/fabiozumbi12/RedProtect/RedProtect.java#L183

And this is the class: https://github.com/FabioZumbi12/RedProtect/blob/master/RedProtect-Spigot/src/main/java/br/net/fabiozumbi12/RedProtect/hooks/McMMoListener.java

But seems you have not added `getHandlers()` on some event in your code.

EDIT:
Seems is the removed handlers from this commit https://github.com/mcMMO-Dev/mcMMO/commit/f7187410449c8deb6433fad6314a3d054c235dbd on McMMOPlayerExperienceEvent class.

**Comment by DrOreo002** [comment]
please fix this mcmmo!
