### ISSUE TITLE
McMMO Data Backups

### ISSUE THREAD

**Issue by Sobki** [mcMMO-Dev/mcMMO#3240]
Hey, I more just had a quick question to ask regarding backups.
I currently have data stored in a MySQL database and am switching VPS. I've been having a lot of issues with my old VPS databases, and so am having to transfer McMMO data manually. The backups directory under plugins/mcMMO, are those backups taken from the current database info? Or are they just copies of the flatfile data before me switching to MySQL?

Thanks!

**Comment by t00thpick1** [comment]
Flatfile data and configs... You should just need to connect to your mysql server and do a SQL dump though,  then restore on your new server.  Read https://dev.mysql.com/doc/refman/5.7/en/mysqldump.html
