### ISSUE TITLE
Default vanilla xp multiplier for fishing is 0

### ISSUE THREAD

**Issue by ezeiger92** [mcMMO-Dev/mcMMO#3251]
In FishingManager, the method getVanillaXpModifier returns 0 if your skill is too low for all tiers. I believe this is supposed to be 1, which would leave xp unaffected for low skill rather than removing it.

**Comment by AllPlayed** [comment]
Hello
This will be fixed with the new 1.12.1 version of MCMMO, just be patient 🙂

**Comment by ezeiger92** [comment]
I've haven't seen your name around before and don't see any contributions to mcmmo from you... Who are you?

**Comment by AllPlayed** [comment]
I just want to help people 🙂

**Comment by ezeiger92** [comment]
But who are you to say that anything will be fixed? If you're not involved with this project, you can't know that info.

**Comment by AllPlayed** [comment]
Why not?

**Comment by ezeiger92** [comment]
"I **know** this thing will be fixed despite knowing nothing about the project and having no authority over what is released"
Stop that, it's not helpful.

**Comment by AllPlayed** [comment]
Hey, the developer tell everyone that this will be fixed on the new 1.12.1 version

**Comment by ezeiger92** [comment]
You aren't the developer and you haven't provided links so I don't believe you.
