### ISSUE TITLE
PlayerFishEvent Error Spam

### ISSUE THREAD

**Issue by LoXR** [mcMMO-Dev/mcMMO#3253]
Error: https://pastebin.com/n0Bkdgdp
Version: 1.5.08-Snapshot
Server Version: 1.12.1

**Comment by TheChampTF** [comment]
Samme as #3250

**Comment by OozeIam** [comment]
I just wonder how long will it take him to update the plugin.

**Comment by TheChampTF** [comment]
@OozeIam As he is doing it in his spare time, it might be a few. Just be patient.

**Comment by darkboomba** [comment]
Same problem using latest build (#196), Running PaperSpigot https://pastebin.com/XtLHyHbg

**Comment by t00thpick1** [comment]
Working on this this week, just got back from a vacation.
