### ISSUE TITLE
Old Farms Don't Work For Herbalism

### ISSUE THREAD

**Issue by PetrichorCraft** [mcMMO-Dev/mcMMO#3254]
On some older farms, players do not gain mcMMO xp from their harvests. If you create a new farm, or find one (village), then it works fine, and players get xp from farming. I'm using the default files, so I didn't screw it up myself. It would be very nice to have all farms work. 

Thank you for your time.

**Comment by SXRWahrheit** [comment]
This was identified but not resolved in #3226

**Comment by PetrichorCraft** [comment]
My apologies, closing this now.
