### ISSUE TITLE
No Kraken for players spamming fishing rod

### ISSUE THREAD

**Issue by SXRWahrheit** [mcMMO-Dev/mcMMO#3259]
I haven't seen a Kraken in a long time. There's a new machine in 1.12 (or at least it works in 1.12.1) that allows players to stand in front of a single block of water and spam a fishing pole. I added a plugin that costs hunger when you fish, but if they equip food, they still can spam.

Where's the Kraken?

**Comment by REXKrash** [comment]
Running PaperSpigot 1.12.1
This is the related error: https://hastebin.com/qorehukufo.vbs when a player is fishing.

**Comment by CeIebrimbor** [comment]
Confirmed here 1.12.1

**Comment by Croyd** [comment]
Getting a similar error also running Spigot 1.12.1.

I'm running latest MobHunting also could they be conflicting, not getting any errors from it?

https://pastebin.com/6ZP9qtDU

**Comment by SXRWahrheit** [comment]
I don't use MobHunting.

**Comment by Croyd** [comment]
Yeah I tested without it and still had the problem.

**Comment by Croyd** [comment]
I disabled the Kraken in the advanced.yml and the PlayerFishEvent error goes away. So definitely something in the Kraken code that is shooting out that error.

**Comment by ezeiger92** [comment]
Same cause as #3250, [see my post here](https://www.spigotmc.org/threads/mcmmo-paid.39629/page-80#post-2611172) for a quick fix.

That is, assuming the only issue is the exceptions being thrown. If the kraken still doesn't work then there is another issue.

**Comment by SXRWahrheit** [comment]
@t00thpick1 The commits from @ezeiger92 are unlikely to fix this bug; I was using his build but still had no Kraken. I can make a new issue, though.

**Comment by t00thpick1** [comment]
New issue please. I'll check it out tonight
