### ISSUE TITLE
Do we plan on seeing an mcMMO config reload?

### ISSUE THREAD

**Issue by LogGits** [mcMMO-Dev/mcMMO#3260]
This should be added already. It is really inconvenient to have to restart the server for minor changes. A /mcmmo reload would be a really great addition to the plugin. (Unless there is already a config reload for mcMMO and I am just stupid)

**Comment by AllPlayed** [comment]
I think there is not a command for reload just the MCMMO plugin, but I recommend you to download any plugin that reload anything or something like that.

**Comment by LogGits** [comment]
I do know about those plugins however there are many plugins that hook into mcMMO that would require a restart to hook back into it. Thus, It would be really convenient to have a reload command for mcMMO.

**Comment by SXRWahrheit** [comment]
This has been a requested feature for a long time, check past issues. They'll add it if and when they can.

**Comment by Glitchfinder** [comment]
The short answer is no. The longer answer is that I almost had this in about five years ago, before some of the other devs rewrote huge chunks of the plugin to load config information into Java enumerators, which can't be safely reloaded. They're faster and easier to work with, but not being reloadable is the cost.

**Comment by nossr50** [comment]
It's possible to rewrite the plugin to be reload safe, it would just be a huge pain in the ass.

**Comment by nossr50** [comment]
Since 2.2 is adding reload I will close this issue
