### ISSUE TITLE
mcMMO Bug: Not gaining any Herbalism xp while collecting

### ISSUE THREAD

**Issue by MrGamerPro1** [mcMMO-Dev/mcMMO#3262]
so recently, i been collecting stuff that's replantable, when it comes to wheat, carrots, beetroots and potatos, they do not give any herbalism xp, heres 2 comparisons that shows the scoreboard of gaining it
![image](https://user-images.githubusercontent.com/21155871/29299703-a063ef86-813e-11e7-8e48-fe8f253366ff.png)
this image is before getting wheat
![image](https://user-images.githubusercontent.com/21155871/29299716-be59c470-813e-11e7-9902-b7859bb66afe.png)
this image after getting wheat

could this be a rare bug that some people might experience?
(note: i'm not an expert on codes and stuff, this is a thing that's been happening for a while now)

**Comment by AllPlayed** [comment]
I think that this will be fixed when the new MCMMO version for 1.12.1 come out, so I think the best now is to be patient

**Comment by ezeiger92** [comment]
See this f1ac5739e4681fb3e14849baf3738a0df97a3a95 commit message, which is likely your problem. Short version is that the herbalism config changed, and you need to update your experience.yml file to make those crops work again.

**Comment by Braleth** [comment]
Can anyone confirm the corrected xp file and updated build 196 are actually working to fix the Herbalism XP issue? My testing shows this doesn't fix the problem.

I've tested with a manually corrected experience.yml file as well as deleting it and letting the plugin create a new one. Same issue still persists. The crops with the odd _Ripe names are not rewarding mcMMO herbalism XP.
