### ISSUE TITLE
mcmmo mining

### ISSUE THREAD

**Issue by globalshot** [mcMMO-Dev/mcMMO#3263]
i dont get xp to my mining level, i was mining 1000 ores and blocks and dont get nothing

**Comment by Glitchfinder** [comment]
Is this still an issue you're having? If so, does [the latest dev build](https://popicraft.net/jenkins/job/mcMMO/) fix it? And if that doesn't fix it, can you provide more information, such as your copies of experience.yml, advanced.yml, and config.yml?
