### ISSUE TITLE
Unarmed skill isn't affecting players

### ISSUE THREAD

**Issue by Burrito132** [mcMMO-Dev/mcMMO#3266]
Hey, so I was trying to pvp a friend, and we were both wearing no armor whatsoever. I have LVL 140 Unarmed skill, so +5 damage, but I was only dealing half a heart of damage per punch.

**Comment by razorrider7** [comment]
I haven't had a chance to check this out, but line 391 or so of your mcMMO config.yml should enable (true) or disable (false) pvp with unarmed.

**Comment by Glitchfinder** [comment]
Is this still an issue you're having? If so, is unarmed enabled for pvp in the config? And, if that's the case, does [the latest dev build](https://popicraft.net/jenkins/job/mcMMO/) resolve the issue?
