### ISSUE TITLE
Missing required method in an event

### ISSUE THREAD

**Issue by Morphan1** [mcMMO-Dev/mcMMO#3269]
`McMMOPlayerLevelChangeEvent` is missing a `getHandlerList()` method.

**Comment by mcmonkey4eva** [comment]
y'know This can be fixed as easily as undoing the accidental deletion in https://github.com/mcMMO-Dev/mcMMO/commit/f7187410449c8deb6433fad6314a3d054c235dbd

**Comment by mcmonkey4eva** [comment]
In fact there's a PR for that open https://github.com/mcMMO-Dev/mcMMO/pull/3234

**Comment by mcmonkey4eva** [comment]
Should be fixed now, https://github.com/mcMMO-Dev/mcMMO/pull/3234 was pulled
