### ISSUE TITLE
Flux mining breaks if using a pickaxe with other enchantments.

### ISSUE THREAD

**Issue by mibby** [mcMMO-Dev/mcMMO#3272]
Flux mining (smelting benefit - smelting a pickaxe in a furnace to get the enchantment) stops working if you enchant your pickaxe with other enchantments.

**Comment by Glitchfinder** [comment]
I'll have to look into this one. It might be a priority issue, where a "normal" pick takes precedence.

**Comment by Glitchfinder** [comment]
So, it doesn't look like there's anything happening like I mentioned above. However, it would also appear that it intentionally omits silk touch pickaxes. So if you enchant a flux pickaxe with silk touch, it won't smelt mined ore anymore. Was the pick you were testing with as silk pick, by any chance?
