### ISSUE TITLE
[Feature] Support for [[STRIKETHROUGH]], [[BOLD]], etc

### ISSUE THREAD

**Issue by FrankHeijden** [mcMMO-Dev/mcMMO#3275]
Heya,

Could you maybe add support for the miscellaneous formatting codes of minecraft in the locale folder of mcMMO? e.g. [[STRIKETHROUGH]] and [[BOLD]] dont work atm.

Thanks in advance,
Frank

**Comment by ezeiger92** [comment]
[[STRIKE]], not [[STRIKETHROUGH]]
This has been a feature since ebd83e1 and this issue can be closed.
