### ISSUE TITLE
Wheat in Ocean no xp

### ISSUE THREAD

**Issue by HeadlessJoey** [mcMMO-Dev/mcMMO#3276]
One of my players noted that in the Ocean and Beach biomes you do not get herbalism experience from breaking wheat.
Sugar cane does give xp when broken in an ocean biome.
Just to be sure I tried wheat in a jungle biome and that gave me xp (same in an extreme hills biome).
I also tried potatos thinking it might be because of the growing/aging mechanism for wheat but potatos give xp in ocean.

So just wheat gives no xp in Beach and Ocean biomes.

Spigot 1.12.1
Mcmmo: 1.5.08

**Comment by Flavourized** [comment]
I can confirm this bug too for both beach and ocean biome

Paper 1.11.2 b1104
mcMMO 1.5.07

**Comment by HeadlessJoey** [comment]
Another biome that's affected is the mushroom biome.

**Comment by t00thpick1** [comment]
Cannot reproduce on latest build.  Ran 1.12.1 spigot and current source for mcMMO.  Ocean biomes crops gave herbalism xp
