### ISSUE TITLE
Chunkerror MCmmo

### ISSUE THREAD

**Issue by Sprungente** [mcMMO-Dev/mcMMO#3277]
Hey people i have this Issue

https://pastebin.com/UZpvMxPb

But i don't know how and why this happens or how it is to fix

I use the newest spigot und mcmmo build

**Comment by Glitchfinder** [comment]
Is this still an issue you're encountering? If so, does it also occur on [the latest dev build](https://popicraft.net/jenkins/job/mcMMO/)?
