### ISSUE TITLE
Herbalism - Greenthumb autoplant does not award XP

### ISSUE THREAD

**Issue by Braleth** [mcMMO-Dev/mcMMO#3284]
The Herbalism passive skill of greenthumb (auto planting a crop when harvesting) still fails to award you Herbalism XP.

Tested using the latest 201 dev build on Spigot 1.12.1.

**Comment by MineServidorCraft** [comment]
I was the same error, how fix it?

**Comment by Braleth** [comment]
For now, I've disabled the greenthumb autoplant skill.
