### ISSUE TITLE
Error out of nowhere

### ISSUE THREAD

**Issue by PengBread** [mcMMO-Dev/mcMMO#3290]
https://pastebin.com/D7nL9L8q
Got this error out of no where. Not sure what caused it.
Using Spigot 1.12

**Comment by AgentBaron** [comment]
I'm seeing craftbukkit errors in there. Just to be clear, you're running the spigot version on the spigot server, correct?

**Comment by Glitchfinder** [comment]
There are a couple of issues on the tracker with this same error. I've been consolidating them to #3344.
