### ISSUE TITLE
I don't get exp for skills.

### ISSUE THREAD

**Issue by MineServidorCraft** [mcMMO-Dev/mcMMO#3291]
I mining stone or collect the potatoes / carrots / wheat or any but the experience or level does not reach me.
The last version stable on spigot with 1.11.2 (java 8).

**Comment by AgentBaron** [comment]
Try testing it with version 1.12.2. I am currently running it with mcMMO v1.5.09-SNAPSHOT and it seems to be running without any problems like those.

**Comment by MineServidorCraft** [comment]
I have the last version of spigot and the last of mcmmo in my server, and my users do not get experiences for breaking trico and others ... Nor can they use the ability of herbalism because it does not work, it activates but it does not do what it has to do. Nor does he replant it and that has a very high level.

**Comment by Glitchfinder** [comment]
This is fixed by https://github.com/mcMMO-Dev/mcMMO/commit/6876f192de4b22f44d7080b65fbe71e68361824d/
