### ISSUE TITLE
GitHub Wiki is Outdated

### ISSUE THREAD

**Issue by Cabji** [mcMMO-Dev/mcMMO#3294]
Large parts of the official wiki here on GitHub are outdated, including missing information related to updates made over the last four years.

**Comment by Glitchfinder** [comment]
Oh man. I just poked my head into the wiki and, well. Out of date isn't the best way to put it. It seems that large swaths of it haven't been touched since the last time I was active on the project, *four years ago*. I'm going to appropriate this issue for general wiki updates.

**Comment by Glitchfinder** [comment]
*Original issue text:*
***

GitHub wiki needs edit for Mining ability
---
>The Mining page in the wiki needs updating. 
>
>Currently reads: 
>---
>Passive Abilities
>
>Double Drops
>
>Each time you level up in mining you get a 0.1% chance of getting 2 drops with every mine of an ore. For example, a level 500 miner will have a 50% chance to get a double drop from one ore! Double drops works on all materials that are gathered fastest with a pickaxe. (Stone, Ore, etc)
>-- 
>
>Needs editing to ensure reader knows that double drops occuring on player placed blocks is a bug and should be reported to server admins and GitHub project pages.
