### ISSUE TITLE
Fishing does not incorporate vanilla treasures into the custom loot table.

### ISSUE THREAD

**Issue by MichaelPriebe** [mcMMO-Dev/mcMMO#3298]
I don't mind mcMMO changing the fishing loot tables and making them work differently. But its not good when you completely remove items you get from vanilla fishing. For example fishing up fishing rods, or enchanting books is not possible with the mcMMO loot tables. The mcMMO loot tables should only expand upon fishing instead of removing items from it.

**Comment by AgentBaron** [comment]
You can alter the config to add everything back if you have the patience and effort.

**Comment by hoorigan** [comment]
@AgentBaron Patience and effort won't get the plugin to force enchanted books to actually have enchantments.  That's a conditional that has to be written into the code, not something you can do in the config, unless I'm completely missing something here.

My tests have me sitting on a bunch of "enchanted books" without any enchantments.  Do you know of a way to remedy that?

**Comment by hoorigan** [comment]
Submitted pull request to resolve enchanted book issue.  The fix would ideally ensure that there’s a 100% chance of getting an enchantment on an enchanted book.  With that fixed, it should be possible to replicate the vanilla loot table.  I really hope that makes it in.

**Comment by Glitchfinder** [comment]
@t00thpick1 what's the status on this one?
