### ISSUE TITLE
Mob_Healthbar DISABLED does not disable the healthbar...

### ISSUE THREAD

**Issue by ChibbyGit** [mcMMO-Dev/mcMMO#3299]
`Mob_Healthbar:
    # Display_Type: Default display for mob health bars - HEARTS, BAR, or DISABLED
    # Display_Time: Amount of time (in seconds) to display. To display permanently, set to -1
    Display_Type: DISABLED
    Display_Time: 1`

Still displays hearts above the mob. This has been an issue for a long time and I have reported it SEVERAL times this year.

**Comment by Leomixer17** [comment]
Try to set Display_Time to 0

**Comment by ChibbyGit** [comment]
That is terrible advice kid, do not make unacknowledged assumptions on here. 
DISABLED should mean DISABLED. Never set any configuration numerical number to 0.

**Comment by ChibbyGit** [comment]
I can not believe this is being ignored for over a year.

**Comment by ChibbyGit** [comment]
Fuck the developers of this shit plugin, I am going to use Heroes.

**Comment by t00thpick1** [comment]
Good news everyone, now that this guy has left I can finally fix this issue. I've literally been holding off on doing it just to spite specifically this one guy.  Cheers

**Comment by ChibbyGit** [comment]
Huh, seems I got my way, despite what you said. I would say thanks, but you are an asshole, who for what possible reason, holds back an update, for an issue, despite the complaints... Asshole Of A Developer.

**Comment by ChibbyGit** [comment]
Thanks for the update, being an asshole in issues always gets you what you want, seriously, you just now decide to release an update for this issue that you "literally have been holding off on doing it" for what reason? Fuck you, asshole.

**Comment by t00thpick1** [comment]
If sarcasm were a razor blade, you would be bald now.

**Comment by ChibbyGit** [comment]
How about your STFU and fix your plugin already, super breaker is a broken feature to start with, let's take things slow for you bud, we know how long it takes to release your famous 1 line updates.
*cough* 
`|| !Config.getInstance().getMobHealthbarEnabled())`
*cough "pathetic" cough cough*

"Been holding off on this difficult/important update for awhile now"
"I was totally aware of this issue and totally wasn't ignoring the reports"
"I am a piece of shit developer, but people are still paying for my premium version of this shitcrap that's free on github & ci.drtshock.net"
"My username is t00thpick1 because after I suck hairy balls I have to pick at least 1 pube out of my teeth"
"I am like Trump, you all hate me, but yet you all rely on me, my friends"
