### ISSUE TITLE
No Herbalism XP for Wheat - Carrots - potato

### ISSUE THREAD

**Issue by Fancepants** [mcMMO-Dev/mcMMO#3303]
My server is on 1.11.2 and no one is able to get xp for carrots , wheat or potatoes. This happened after I downloaded the latest version of Mcmmo (premium)  . I have another 1.12 test server and it works on here. They have the same files and folders.  There is not an error message. It just fails to give XP

**Comment by AgentBaron** [comment]
Have you checked the configs to make sure mcMMO is set to give more than 0 xp? Are there any error messages being thrown in the console whenever a person breaks carrots, wheat, or potatoes? Between the two, something must be misbehaving and if I had to guess it would likely be either the spigot build or some Minecraft version tomfoolery.

**Comment by Glitchfinder** [comment]
This has been fixed in https://github.com/mcMMO-Dev/mcMMO/commit/6876f192de4b22f44d7080b65fbe71e68361824d.
