### ISSUE TITLE
mcMMO not responding

### ISSUE THREAD

**Issue by Sindri** [mcMMO-Dev/mcMMO#3305]
mcMMO commands do not respond when I type them into the console...

/mcstats
/mcmmo

nothing works, how can I get it to work?

**Comment by AgentBaron** [comment]
Check your console as the server is loading and look for mcMMO-related messages. Post them here for us to view. It sounds like mcMMO is disabled for one reason or another on launching the server.

**Comment by Glitchfinder** [comment]
It looks like mcMMO failed to start with the server. If this is still an issue, can you check to see if there is an error when the server starts, and if so, provide a copy of the error stacktrace so I can track down what's happening?
