### ISSUE TITLE
MCMMO Disable on startup

### ISSUE THREAD

**Issue by ITechnologyman** [mcMMO-Dev/mcMMO#3306]
Java: 8
Spigot 1.8.8 (No clue what version)

Console error:
https://pastebin.com/Ya6RrxW2

**Comment by Hartii14** [comment]
Use https://ci.drtshock.net/job/MCMMO/lastBuild/ this one

**Comment by Glitchfinder** [comment]
It looks like there was an issue with metrics when the server started up. Is this still an issue, and if so can you provide a current startup log showing the full error stacktrace?

**Comment by ITechnologyman** [comment]
not sure i no longer use it on my server.
