### ISSUE TITLE
Herbalism not leveling UP

### ISSUE THREAD

**Issue by Ironic8b498** [mcMMO-Dev/mcMMO#3311]
if I don't have seeds, carrots, potatoes, beets, etc in my inventory it works sometimes once I pick up one of the items that is used for planting it stops leveling up, I'm running Spigot 1.12.2 and mcMMO-#208
https://youtu.be/snxFvGOEO6w

**Comment by Glitchfinder** [comment]
This one was fun to track, and is a group effort. Fun fact: you can blame a combination of oversights by at least half the dev list for this particular bug, but it can actually be resolved by making use of the `org.bukkit.event.block.BlockGrowEvent` to unflag crops. Unfortunately, I don't have time to actually fix it right now, so if anyone, particularly @t00thpick1 gets some time, that would be nice.
