### ISSUE TITLE
treefeller activates large trees but there are zero drops.

### ISSUE THREAD

**Issue by ghost** [mcMMO-Dev/mcMMO#3313]
Running Spigot 1.12.2 (latest version) / mcmmo.1.5.09.snapshot

We are getting drops from regular trees but no drops from 2x2 trees. no wood, no saplings.

**Comment by Ironic8b498** [comment]
same problem, but it works most of the time on single trunk trees, when I tested chopped down 8 trees and 3 trees them left logs, this was during one treefeller activate

**Comment by t00thpick1** [comment]
Ill take a look

**Comment by unsivilaudio** [comment]
Just chiming in to say I'm experiencing this too. Spigot 1.11.2  no errors in console.

**Comment by unsivilaudio** [comment]
Well I figured out my issue, thank god.  FastAsyncWorldEdit has a 'tick-limiter' that was limiting drops in a chunk.

**Comment by Glitchfinder** [comment]
Is anyone else still having this issue, and, if so, is it being caused by the same problem mentioned by @unsivilaudio?

**Comment by unsivilaudio** [comment]
Sean in my case it was caused by FAWE, lag protection zapping the drops
because they exceeded an entity count limit.

**Comment by Glitchfinder** [comment]
Yes, in your particular case. Others have reported the same issue, and I don't know whether or not they're using FAWE or a similar plugin, or simply had a similar issue at the same time that was the fault of mcMMO. That's what I'm trying to confirm.

**Comment by unsivilaudio** [comment]
Oh sorry, didn't realize you are a dev.  Good luck on your hunt then.

**Comment by Glitchfinder** [comment]
I mostly stopped being a dev for this plugin about four years ago, so I can see why you wouldn't have seen me around. That said, I seem to have some time to pick up some slack, so I'm slowly digging my way through the tracker to see what's in the backlog.
