### ISSUE TITLE
Stats being reset

### ISSUE THREAD

**Issue by aaa8881** [mcMMO-Dev/mcMMO#3314]
Player stat gets reset when their UUID changes with same name. 
This is normally not possible, but sometimes possible in my server for some failures. I have an offline server, and let premium player without login, and non-premium(cracked) players to login by reading online UUID by mcapi. For whatever reason, if it fails to retrieve correct UUID, premium players sometimes log in with cracked UUID. Data storage is flat file, haven't tested on mySQL. Let me give example.

For example, player "username1" is premium player. He has UUID of "aaaa" , and offline-UUID of "bbbb".
He should log in with "aaaa", and his data is ofc stored with "aaaa".
However, for whatever reason, it failed and he logged in with "bbbb" UUID
His real MCMMO file gets removed, and MCMMO creates new data.

So I suppose- it might be nice to make MCMMO not create new one if that username already has MCMMO data - or something like that.

**Comment by t00thpick1** [comment]
Im sorry, Offline minecraft server is not actively supported, if it works, great, if not, sorry :(
