### ISSUE TITLE
Vanilla fishing treasures not working.

### ISSUE THREAD

**Issue by Goldy93** [mcMMO-Dev/mcMMO#3315]
After using mcMMO for awhile, players wanted vanilla treasures back, so, in the config.yml file, I changed the following setting to this:

 Override_Vanilla_Treasures: false

However, we are not seeing vanilla treasures and are still getting the mcMMO treasures.  I deleted out the plugin (.jar file only, not corresponding folders) restarted the server, logged in reinstalled the plugin and restarted server and that did not fix the issue.

**Comment by t00thpick1** [comment]
Ill take a look

**Comment by vikingofdisco** [comment]
Same issue

**Comment by Glitchfinder** [comment]
Is this still an issue you're having?
