### ISSUE TITLE
No xp for salvage?

### ISSUE THREAD

**Issue by AgentBaron** [mcMMO-Dev/mcMMO#3317]
I've noticed that the salvage.vanilla.yml has config values for xp multipliers, but there is no experience gain from performing salvage. Is this intended or are we supposed to be getting experience for it?

**Comment by Glitchfinder** [comment]
You are correct - Salvage has configurable experience values, but does not currently provide experience. This contradicts Smelting, which splits provided experience between its two parent skills.
