### ISSUE TITLE
Transferring skills from a player to another

### ISSUE THREAD

**Issue by Portanna** [mcMMO-Dev/mcMMO#3318]
Add a command to easily transfer all data of a player to another (useful when a player changes nickname).

Example: /mmotransfer <player1> <player2> : transfers player1 data to player2, deleting player1 from database.

Of course this command should support transferring data also when the 2 players are offline.

**Comment by t00thpick1** [comment]
Why would this be needed?

**Comment by Portanna** [comment]
When a player changes nickname, it would be useful to have just a command to transfer his data to the new nickname.

**Comment by t00thpick1** [comment]
we store by UUID so I don't see how this is necessary?

**Comment by Glitchfinder** [comment]
I can think of at least two situations where UUID-based storage doesn't help. First is the obvious one of offline worlds, where the server will gen a UUID by username. The second is if the player manages to login but the server fails to obtain an appropriate UUID for some reason. There's at least one other issue on the tracker right now involving that second case, so it's entirely possible.
