### ISSUE TITLE
Fishing

### ISSUE THREAD

**Issue by madtomic** [mcMMO-Dev/mcMMO#3320]
Fishing:
        Level_Cap: 0
        Drops_Enabled: true
        Override_Vanilla_Treasures: true
        # Always catch fish, even when treasure is found
        Extra_Fish: false

I had been playing with fishing skills and I noticed the drops are a bit buggy.

With extra fish set to false and drops enabled set to false. I understand that vanilla would be still override and no extra fish would be catch if it’s a treasure. Is this how it should be? Can anyone explain this better to me? I am expecting with both set to false, players can sometimes catch a fish and sometime not.

**Comment by SXRWahrheit** [comment]
When you catch a treasure, you will not get a fish, but it still counts as a "catch" from other plugins. You will always "catch" something.

**Comment by Glitchfinder** [comment]
Are you able to clarify your question? In terms of the settings above, fishing has no maximum level, will use mcMMO's custom treasure system, and will only drop one thing at a time, be it a single fish, a treasure drop, or a trap.

**Comment by madtomic** [comment]
This has been resolved. Thank you all
