### ISSUE TITLE
Free download link not working

### ISSUE THREAD

**Issue by vikingofdisco** [mcMMO-Dev/mcMMO#3322]
Wanted to try the plugin before i bought, however the free link on https://www.spigotmc.org/resources/mcmmo.2445/ doesnt work . The paragraph links to an error saying 

this page (https://ci.drtshock.net/job/mcMMO/) is currently offline. However, because the site uses Cloudflare's Always Online™ technology you can continue to surf a snapshot of the site. We will keep checking in the background and, as soon as the site comes back, you will automatically be served the live version. Always Online™ is powered by Cloudflare | Hide this Alert

**Comment by popcorn9499** [comment]
Here is one that may help. the orriginal is down but here https://popicraft.net/jenkins/job/mcMMO/ I am not affiliated with these guys but I created a mirror

**Comment by vikingofdisco** [comment]
Thanks
