### ISSUE TITLE
Dupe bug on break ores

### ISSUE THREAD

**Issue by FabioZumbi12** [mcMMO-Dev/mcMMO#3324]
Hi,
We can dupe ores placing the ore blocks under stairs(or some half blocks) and then breaking with silk touch. The amount of ores dropped increase depending of mcmmo level.

Using the latest build of mcmmo, and tested on 1.12.1 and 1.12.2.

**Comment by t00thpick1** [comment]
Cannot reproduce running latest mcMMO and 1.12.2, can you give me more information?

**Comment by FabioZumbi12** [comment]
Oh, my description is wrong, this is the correct:
Placing the ores above a stair, or any half block, the mcmmo plugin has the chance to dupe the block, instead of the player has placed it. It was suposed to happen just with natural ores found, not placed by players

**Comment by Seeroh** [comment]
I cannot duplicate this issue.

**Comment by Glitchfinder** [comment]
Are you able to provide more information about this? From how the plugin works, adjacent blocks should have no impact on the mining skill at all, and I have also been unable to reproduce the issue.

**Comment by FabioZumbi12** [comment]
My players never more have reported this, then i think is fixed! If happens again i will say to my player to rec a video to be easy to know how works.

**Comment by Glitchfinder** [comment]
Good to hear! If the bug crops up again, just reopen the issue with information on how to set it up.
