### ISSUE TITLE
mcMMO not aware of enchanted books as enchantable item

### ISSUE THREAD

**Issue by hoorigan** [mcMMO-Dev/mcMMO#3333]
mcMMO does not count enchanted books as an enchantable item, and will only give an enchanted book without enchants as treasure.

I have submitted a pull request which adds enchanted books to the enchantable item checks, and which should force enchanted books to always get an enchantment when retrieved as fishing treasure.  Please reference: Enchanted book fixes #3330

**Comment by hoorigan** [comment]
Not trying to be a pain, just wondering if anyone's looked at this.

**Comment by Glitchfinder** [comment]
@t00thpick1 I'm about six years out of date on the mcMMO treasure setup, so this one's all you.
