### ISSUE TITLE
Tring to use McMMO on my Apex Hosting minecraft server

### ISSUE THREAD

**Issue by TheKekOffensive** [mcMMO-Dev/mcMMO#3336]
I Installed the plugin and use the correct version yet when i load into the server nother happens. when i use /plugins its not even there. im not sure what to do, thanks

**Comment by t00thpick1** [comment]
I would ask your host if I were you.

**Comment by Glitchfinder** [comment]
Is this still an issue you're having, and if so, are you able to provide any more information?
