### ISSUE TITLE
treasures.yml config help

### ISSUE THREAD

**Issue by arkobat** [mcMMO-Dev/mcMMO#3338]
I have some troubles making custom items which you can fish.
I have tried some diffrent thing, and none worked, so i'm posting an example, that is understandable.
Is following item possible to configere, the example below ***dosn't*** work

treasures.yml
```treasures.yml
Fishing:
    DIAMOND_SWORD:
        Custom_Name: &4Warrior &cSword
        Lore: &eThis sword can only be wielded\n&eby the mightiest warriors
        Enchants: 
        - Smite: 5
        - Arthropods: 5
        - Unbreaking: 3
        - FireAspect: 2
        - Fortune: 3
        Amount: 1
        XP: 200
        Rarity: RECORD
```

**Comment by arkobat** [comment]
Bump

**Comment by Glitchfinder** [comment]
So, while the Custom_Name and Lore tags are things that the config currently uses, pre-specifying enchantments is not something that it currently allows for. Thus, marking this as a feature request for the time being.

**Comment by t00thpick1** [comment]
Closing due to 1.13 overhaul changes in progress touching the affected areas.

**Comment by Flavourized** [comment]
Didn't know where else to put this, but how can i figure out the mcmmo custom materials?

For example, mcmmo uses `INK_SACK_BLUE`, but the actual material has a data value. 

Basically, how do i handle items with data? I was not able to find anything

**Comment by ShadowFade** [comment]
Try using durability values with "INK_SACK"
This will break upon upgrading to 1.13, be advised.
