### ISSUE TITLE
Feature request for herbalism

### ISSUE THREAD

**Issue by MatrixKhan** [mcMMO-Dev/mcMMO#3343]
I need a way to get the extra drops from herbalism so I can make them automatically go in the player's inventory can you add a method in the api for this?

**Comment by Glitchfinder** [comment]
Herbalism actually uses the [McMMOItemSpawnEvent](https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/events/items/McMMOItemSpawnEvent.java) event to handle item drops. This is true of all mcMMO item drops, no matter the skill causing it.
