### ISSUE TITLE
Wrong text in advanced config?

### ISSUE THREAD

**Issue by Guddina-tim** [mcMMO-Dev/mcMMO#3349]
Found this bit of text under the repair section of advanced.yml. Seems incorrect to me to mention being disarmed here.

 _SuperRepair:
  **#ChanceMax: Maximum chance of preventing being disarmed
  #MaxBonusLevel: Level when the maximum chance to prevent being disarmed is reached**
  ChanceMax: 100.0
  MaxBonusLevel: 1000_

**Comment by Glitchfinder** [comment]
This appears to have been fixed at some point, although your config was likely generated prior to that fix.
