### ISSUE TITLE
the fluxmining issu

### ISSUE THREAD

**Issue by Rymfader** [mcMMO-Dev/mcMMO#3350]
the fluxming dosnt work at all！
spigot 1.12.2 mcmmo 1.5.0.9
and spigot 1.8.8 mcmmo 1.5.0.4

**Comment by Glitchfinder** [comment]
Having dug through the code, I found that at some point flux pickaxes were added. To use flux mining, you must take a fully repair pick and cook it in a furnace, at which point it will have the chance of instantly smelting any iron or gold ore you dig up.
