### ISSUE TITLE
[Question] Does setting Override_Vanilla_Treasures to false for fishing make mending books drop?

### ISSUE THREAD

**Issue by ignamiranda** [mcMMO-Dev/mcMMO#3353]
or do i also need to add the enchantment to the treasures.yml?

**Comment by Ironic8b498** [comment]
Override_Vanilla_Treasures set to false will only let default vanilla drops. Enchanted books are not in this list of the vanilla drops. https://minecraft.gamepedia.com/Fishing I have mine set to true and I get enchanted books.

**Comment by ignamiranda** [comment]
Enchanted books are in the vanilla drops. It says so in the link you sent. I'm getting enchanted books but never one with mending.

**Comment by Ironic8b498** [comment]
sorry about the mistake I made, I do know the only way to get a mending book is in trade with a villager. Can not get from enchanting table, and my guess will not get from fishing drop

**Comment by Mailleweaver** [comment]
I get mending books from fishing with vanilla drops enabled.

**Comment by ignamiranda** [comment]
Thanks! Guess I'll keep trying

**Comment by Glitchfinder** [comment]
To confirm, yes, that setting replaces mcMMO's fishing drops with the vanilla fishing drop system.

**Comment by Romaq** [comment]
I'd really like this issue reopened and MENDING added to the list of potential treasures in treasures.yml along with the new 1.13 enchantments for Loyalty, Riptide, and so on. Of course, this would also imply Curse of Binding and Curse of Vanishing.

An alternative would be some way to push "treasures.yml" into a "data pack" format that still allows for skewing the value of treasures upward, though I'm not clear if mcMMO has the hooks for this. https://minecraft.gamepedia.com/Loot_table has details on how Vanilla deals with loot tables in data-packs. If mcMMO could take advantage of "luck" at cast time and tinker with it in realtime, perhaps it would have the same effect?

This would allow things like Hermitcraft Data Packs and various other data packs in Vanilla to socket right into mcMMO AND future-proof mcMMO against the addition of new Vanilla enchantments without the "all or none" problem of turning on Vanilla drops with mcMMO while maintaining out-dated enchantments in treasures.yml.
