### ISSUE TITLE
Can't use mcmmo abilities when item is in offhand

### ISSUE THREAD

**Issue by MidnightSugar** [mcMMO-Dev/mcMMO#3354]
As the title suggests, when an item is in a players offhand slot, they are unable to use any mcmmo abilities. 
(ex. Superbreaker)

**Comment by Ironic8b498** [comment]
If you have anything in your left hand the abilities will not work.

**Comment by MidnightSugar** [comment]
Is there a reason for this?

**Comment by Ironic8b498** [comment]
no clue I never asked DEV of mcMMO

**Comment by Glitchfinder** [comment]
This is a result of an update to Minecraft. Left click corresponds to the main hand, right click corresponds to the off hand. If something is in your off hand, it prevents you from using an mcMMO ability as it fires a different event in Bukkit. That said, accommodating this change in behavior is definitely worth looking into.
