### ISSUE TITLE
herbalism don't level up

### ISSUE THREAD

**Issue by Ironic8b498** [mcMMO-Dev/mcMMO#3359]
I have trying to get this issue fixed since the end of October, when it was brought to my attention, when you farm carrots, potatoes, wheat, beets, netherwart, leaves and coco beans you don't get any XP, and the auto replant has about 5 second delay before it starts to work. I know herbalism works for sugarcane, grass, pumpkin, watermelon and cactus. Sorry if I missed testing some plants. My server is Spigot 1.12.2 tested this on latest DEV release #4

**Comment by sigmaroot** [comment]
Duplicated by #3311

**Comment by Glitchfinder** [comment]
Fixed by https://github.com/mcMMO-Dev/mcMMO/commit/6876f192de4b22f44d7080b65fbe71e68361824d.
