### ISSUE TITLE
Tree Feller and Skull Splitter

### ISSUE THREAD

**Issue by Inkzzz** [mcMMO-Dev/mcMMO#3361]
I don't know if this is true. But Tree Feller which is a McMMo ability that cuts down decently sized trees in 1 hit is disabled due to the fact that Skull Splitter is disabled. Skull Splitter was very OP (Reason this is disabled). 

I think the config/plugin cannot see the difference between both actions and therefore disables both features. Is there a way to activate Tree Feller without making Skull Splitter work?

[Post](https://fadecloudmc.com/forums/threads/shottys-skyblock-karma-bug-report.58879/)

**Comment by ezeiger92** [comment]
You should be able to disable the skull splitter permission `mcmmo.ability.axes.skullsplitter` without changing any config settings.

**Comment by Glitchfinder** [comment]
@ezeiger92 is correct. Denying the `mcmmo.ability.axes.skullsplitter` permission would prevent the use of skull splitter while still allowing players to use tree feller.
