### ISSUE TITLE
Superbreaker (pick) causing invisible block

### ISSUE THREAD

**Issue by datsme** [mcMMO-Dev/mcMMO#3365]
Server: CraftBukkit version git-Spigot-549c1fa-8c37e2e (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
mcMMO: 1.5.09-SNAPSHOT #4 

When superbreaker ends it leaves invisable block/s that can't be interacted with. If you log out then back in though the block/s appear and can be broken as normal.

**Comment by Flavourized** [comment]
These are called ghost blocks, and happens on every server that allows efficiency at or above lvl6-10.

Ghost blocks are not server side, they are only a visual bug on the client side.

There are some resources that aim to fix this issue, by having the player type a command, which then updates the blocks within a certain radius of the player.

https://www.spigotmc.org/resources/ghost-block-remover.26820/

I haven't tested this, so I would suggest putting this on a dev server before pushing it to your production server

**Comment by Glitchfinder** [comment]
This is a confirmed issue mcMMO can cause, however, as noted, it's not something we can directly control. It's the result of client/server sync issues, and the faster you can break blocks, the more likely it is to happen. The only "fix", such as it is, would be to go back to the older style instant break, where tapping a block broke it. Making use of the efficiency enchant is much more natural and preferable, despite the ghost blocks.
