### ISSUE TITLE
Anvil Concerns

### ISSUE THREAD

**Issue by johnsoncui02** [mcMMO-Dev/mcMMO#3368]
The current state of Anvils are working with mcmmo. It becomes a problem when players have high enchantment items such as sharpness 7 or along with crazy enchant plugin enchantments. The result of that makes the item "TOO EXPENSIVE" or aka irreparable. Is there a fix to it? An option to bypass any non vanilla enchantment level equips to be repairable?

**Comment by Glitchfinder** [comment]
I'm not entirely sure what you're trying to ask? mcMMO does not have a direct impact on enchantment cost or enchantment experience for repair, and the default configuration uses an iron block for item repairs rather than an actual anvil.
