### ISSUE TITLE
What is "Killing orphans"

### ISSUE THREAD

**Issue by RUSHyoutuber** [mcMMO-Dev/mcMMO#3369]
I wonder what 'Killing orphans' means and why it appears on the console.

**Comment by t00thpick1** [comment]
We have a multi data table setup, and sometimes there may be rows in one table without corresponding parent rows in the main table, in other words "orphaned rows"  which we "kill" by deleting them.

**Comment by RUSHyoutuber** [comment]
Now I understand. Thanks for the answer.
