### ISSUE TITLE
Taming is not effected by parrots

### ISSUE THREAD

**Issue by flanigomik** [mcMMO-Dev/mcMMO#3372]
parrots were added as a tameable mob using seeds and make no progress towards your taming score

**Comment by CollinHerber** [comment]
Have you added them to your experience.yml file?

You will also need it there, and declare how much experience you would get for this.

Taming can be found on line 232 in the default experience.yml file.

**Comment by t00thpick1** [comment]
Closing due to 1.13 overhaul changes in progress touching the affected areas.
