### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by Sodies** [mcMMO-Dev/mcMMO#3373]
09.01 02:54:15 [Server] ERROR Could not pass event McMMOPlayerLevelUpEvent to mcMMO v1.5.09-SNAPSHOT
09.01 02:54:15 [Server] INFO org.bukkit.event.EventException: null
09.01 02:54:15 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
09.01 02:54:15 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
09.01 02:54:15 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
09.01 02:54:15 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
09.01 02:54:15 [Server] INFO at com.gmail.nossr50.util.EventUtils.handleLevelChangeEvent(EventUtils.java:70) [mcMMO-1.5.09-CRACKED.jar:?]
09.01 02:54:15 [Server] INFO at com.gmail.nossr50.datatypes.player.McMMOPlayer.checkXp(McMMOPlayer.java:503) [mcMMO-1.5.09-CRACKED.jar:?]
09.01 02:54:15 [Server] INFO at com.gmail.nossr50.datatypes.player.McMMOPlayer.applyXpGain(McMMOPlayer.java:477) [mcMMO-1.5.09-CRACKED.jar:?]
09.01 02:54:15 [Server] INFO at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginUnsharedXpGain(McMMOPlayer.java:440) [mcMMO-1.5.09-CRACKED.jar:?]
09.01 02:54:15 [Server] INFO at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginXpGain(McMMOPlayer.java:430) [mcMMO-1.5.09-CRACKED.jar:?]
09.01 02:54:15 [Server] INFO at com.gmail.nossr50.skills.SkillManager.applyXpGain(SkillManager.java:32) [mcMMO-1.5.09-CRACKED.jar:?]
09.01 02:54:15 [Server] INFO at com.gmail.nossr50.skills.woodcutting.WoodcuttingManager.woodcuttingBlockCheck(WoodcuttingManager.java:67) [mcMMO-1.5.09-CRACKED.jar:?]
09.01 02:54:15 [Server] INFO at com.gmail.nossr50.listeners.BlockListener.onBlockBreak(BlockListener.java:221) [mcMMO-1.5.09-CRACKED.jar:?]
09.01 02:54:15 [Server] INFO at sun.reflect.GeneratedMethodAccessor589.invoke(Unknown Source) ~[?:?]
09.01 02:54:15 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
09.01 02:54:15 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
09.01 02:54:15 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
09.01 02:54:15 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
09.01 02:54:15 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
09.01 02:54:15 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
09.01 02:54:15 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:290) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
09.01 02:54:15 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:217) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]

**Comment by t00thpick1** [comment]
Since you didn't get this jar from one of the numerous freely available sources that actually lists build numbers, I can't do anything about it.  I would also advice you not to run "cracked" builds of literally free software, as they are likely to contain malicious code.
