### ISSUE TITLE
Not cracked 

### ISSUE THREAD

**Issue by Sodies** [mcMMO-Dev/mcMMO#3374]
10.01 01:43:17 [Server] ERROR Could not pass event McMMOPlayerLevelUpEvent to mcMMO v1.5.09-SNAPSHOT
10.01 01:43:17 [Server] INFO org.bukkit.event.EventException: null
10.01 01:43:17 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
10.01 01:43:17 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
10.01 01:43:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
10.01 01:43:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
10.01 01:43:17 [Server] INFO at com.gmail.nossr50.util.EventUtils.handleLevelChangeEvent(EventUtils.java:70) [mcMMO%20(2).jar:?]
10.01 01:43:17 [Server] INFO at com.gmail.nossr50.datatypes.player.McMMOPlayer.checkXp(McMMOPlayer.java:503) [mcMMO%20(2).jar:?]
10.01 01:43:17 [Server] INFO at com.gmail.nossr50.datatypes.player.McMMOPlayer.applyXpGain(McMMOPlayer.java:477) [mcMMO%20(2).jar:?]
10.01 01:43:17 [Server] INFO at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginUnsharedXpGain(McMMOPlayer.java:440) [mcMMO%20(2).jar:?]
10.01 01:43:17 [Server] INFO at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginXpGain(McMMOPlayer.java:430) [mcMMO%20(2).jar:?]
10.01 01:43:17 [Server] INFO at com.gmail.nossr50.skills.SkillManager.applyXpGain(SkillManager.java:32) [mcMMO%20(2).jar:?]
10.01 01:43:17 [Server] INFO at com.gmail.nossr50.skills.mining.MiningManager.miningBlockCheck(MiningManager.java:62) [mcMMO%20(2).jar:?]
10.01 01:43:17 [Server] INFO at com.gmail.nossr50.listeners.BlockListener.onBlockBreak(BlockListener.java:210) [mcMMO%20(2).jar:?]
10.01 01:43:17 [Server] INFO at sun.reflect.GeneratedMethodAccessor626.invoke(Unknown Source) ~[?:?]
10.01 01:43:17 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
10.01 01:43:17 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
10.01 01:43:17 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
10.01 01:43:17 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
10.01 01:43:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
10.01 01:43:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
10.01 01:43:17 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:290) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
10.01 01:43:17 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:217) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
10.01 01:43:17 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:889) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
10.01 01:43:17 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
10.01 01:43:17 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
10.01 01:43:17 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
10.01 01:43:17 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
10.01 01:43:17 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
10.01 01:43:17 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
10.01 01:43:17 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
10.01 01:43:17 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
10.01 01:43:17 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
10.01 01:43:17 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
10.01 01:43:17 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
10.01 01:43:17 [Server] INFO Caused by: java.lang.IllegalStateException: Unregistered scoreboard component
10.01 01:43:17 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scoreboard.CraftObjective.checkState(CraftObjective.java:112) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
10.01 01:43:17 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scoreboard.CraftObjective.unregister(CraftObjective.java:104) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
10.01 01:43:17 [Server] INFO at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.loadObjective(ScoreboardWrapper.java:374) ~[?:?]
10.01 01:43:17 [Server] INFO at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.setTypeSkill(ScoreboardWrapper.java:288) ~[?:?]
10.01 01:43:17 [Server] INFO at com.gmail.nossr50.util.scoreboards.ScoreboardManager.enablePlayerSkillLevelUpScoreboard(ScoreboardManager.java:258) ~[?:?]
10.01 01:43:17 [Server] INFO at com.gmail.nossr50.util.scoreboards.ScoreboardManager.handleLevelUp(ScoreboardManager.java:214) ~[?:?]
10.01 01:43:17 [Server] INFO at com.gmail.nossr50.listeners.SelfListener.onPlayerLevelUp(SelfListener.java:25) ~[?:?]
10.01 01:43:17 [Server] INFO at sun.reflect.GeneratedMethodAccessor801.invoke(Unknown Source) ~[?:?]
10.01 01:43:17 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
10.01 01:43:17 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
10.01 01:43:17 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
10.01 01:43:17 [Server] INFO ... 32 more
10.01 01:43:17 [Server] WARN Task #4632544 for mcMMO v1.5.09-SNAPSHOT generated an exception
10.01 01:43:17 [Server] INFO java.lang.IllegalStateException: Unregistered scoreboard component
10.01 01:43:26 [Multicraft] Skipped 12 lines due to rate limit (50/s)

**Comment by CollinHerber** [comment]
Please explain the issue you are having.

A stacktrace alone does not help the developers pinpoint the problem without knowing exactly when and where it's happening/

**Comment by Glitchfinder** [comment]
@CollinHerber This appears to be in response to @t00thpick1 dismissing and closing #3373.

**Comment by Glitchfinder** [comment]
There are multiple issues on the tracker that appear to be the same as this, so I am consolidating them all to #3406.
