### ISSUE TITLE
Leveling not working

### ISSUE THREAD

**Issue by Kmeade3** [mcMMO-Dev/mcMMO#3375]
I am currently playing skyblock on the server UberMC. The server uses mcMMO version 1.5.07.  After a while I realized that my mining level was not increasing past 34. Earlier in the day my mining level wouldn't gain xp while it was at 33, but after a while it finally gained a small amount of xp to finally hit 34. I was wondering if there was a way to fix my leveling. (all my other skills are leveling fine btw) Thanks in advance!

**Comment by CollinHerber** [comment]
Please contact the owners of the server, as this has nothing to with the mod itself.

@Kmeade3
