### ISSUE TITLE
Combat Skills XP from spawners

### ISSUE THREAD

**Issue by twistedwrister** [mcMMO-Dev/mcMMO#3376]
Is there a way the owner of a server can do a command to make it so you can obatin mcmmo combat xp from spawners such as zombie or skeleton spawners?

**Comment by CollinHerber** [comment]
`# Experience gained from mobs not naturally spawned will get multiplied by this value. 0 by default.
    Mobspawners:
        Multiplier: 0
    Breeding:
        Multiplier: 1.0`

Line 37 of the default experience.yml file.

Please be sure to read through all of the config files to ensure you are familiar with everything the mod is doing, and has to offer.

Judging by the comment made by the devs, it appears it is off by default.
