### ISSUE TITLE
Sword right click /w 1.8 combat on 1.12.2 server

### ISSUE THREAD

**Issue by RainOfPain125** [mcMMO-Dev/mcMMO#3377]
When I right click it gives me a shield, and doesn't allow me to "ready my sword"

Any fix?

**Comment by WyattLW** [comment]
Try shifting while right clicking..
Also i know there is some kind of plugin, named something like "OldStyle Combat System"
That breaks up some stuff in swords, try removing it.
Also make sure the server is actually running 1.12.2, happend to me once i connected with 1.12.2 client and server was 1.8

**Comment by Glitchfinder** [comment]
This is essentially a more specific copy of #3354.
