### ISSUE TITLE
Info 

### ISSUE THREAD

**Issue by xComboed** [mcMMO-Dev/mcMMO#3378]
I maybe wanna buy this plugin but before i buy i want to know or i can disable skills to. Cus if i look at permission list it says everyone but i dont want everyone got it. Can u only use it if u got the perms? Btw my server is running on 1.8.

**Comment by Glitchfinder** [comment]
The permissions are required to use the relevant skills, however many permissions are on by default. You would have to use a permissions plugin to manually deny those permissions, at which point the users would not be able to use the skills.

**Comment by Aquind** [comment]
@Glitchfinder If you allow just the perms you want then whatever you don't give, they will be blocked from using.  The list is here:

[https://github.com/mcMMO-Dev/mcMMO/wiki/List-of-permissions](https://github.com/mcMMO-Dev/mcMMO/wiki/List-of-permissions)

**Comment by Glitchfinder** [comment]
Having done a lot of work with permissions on this plugin, including being at least partially responsible for it having so many different permissions in the first place, I can say that yes, I am familiar with that list. All of the permissions marked as "Everyone" are granted by default to all players, and you would need to apply negative permissions on a permissions plugin to take them away again.
