### ISSUE TITLE
Infinite Potions

### ISSUE THREAD

**Issue by TrizzerArts** [mcMMO-Dev/mcMMO#3379]
I have a problem with the plugin and the problem is that when crafting potions the item that you put does not go, it stays there, therefore, you can make infinite potions because the item is not spent. I use the recent version mcmmo 1.5.09 Snapshot

Proof:
![1](https://user-images.githubusercontent.com/28847942/35080674-b1678cf0-fbd4-11e7-8146-6e6da7a15bee.png)
![2](https://user-images.githubusercontent.com/28847942/35080675-b181bfa8-fbd4-11e7-922b-7adecfbbd4ae.png)

**Comment by t00thpick1** [comment]
Interesting, Ill take a looksy later today

**Comment by TrizzerArts** [comment]
Thank you and if you can also look at this error that comes out every time someone craft a potion: https://github.com/mcMMO-Dev/mcMMO/issues/3370

**Comment by TrizzerArts** [comment]
17 days have passed and they have not fixed the bug that badly supports so they put a paid plugin if they can not repair the bugs?

**Comment by t00thpick1** [comment]
Ah so yeah, atm the latest version of mcMMO is not compatible back to 1.9  That would be your issue

**Comment by t00thpick1** [comment]
Im looking into rebuilding compatability backwards more versions, but its difficult with spigot breaking APIs

**Comment by TrizzerArts** [comment]
So what is the version compatible with spigot 1.9?

**Comment by t00thpick1** [comment]
1.5.06 there is a link on the spigot page
