### ISSUE TITLE
problem mcmmo / citizen

### ISSUE THREAD

**Issue by Yukyxy** [mcMMO-Dev/mcMMO#3380]
Hello i buy your plugin mcmmo, I have a problem with citizen (npc which attacks the players for a quest), I have this error with your plugin when the npc kills a player

https://pastebin.com/3cYHXrLF

**Comment by Yukyxy** [comment]
?

**Comment by t00thpick1** [comment]
Interesting, I see the problem, I'll try to get a fix in for it, fortunately its harmless to you and won't negatively effect anything.

**Comment by Yukyxy** [comment]
thank you^^

**Comment by Glitchfinder** [comment]
@t00thpick1 Any idea what the status is on this one?
