### ISSUE TITLE
Translation FR and leaderheads

### ISSUE THREAD

**Issue by Yukyxy** [mcMMO-Dev/mcMMO#3386]
Hello I have a problem with the translation FR MCMMO and LeaderHeads

After the translation of the plugin mmo-axes.yml becomes mmo-bûcheronnage.yml

on the sign:

[LeaderHeads]
mmo-bûcheronnage
1

"bûcheronnage" Is too long, it does not fit in the sign...

mmo-bûcheronnage.yml
mmol-bûcheronnage.yml

**Comment by Yukyxy** [comment]
up?

**Comment by Yukyxy** [comment]
?

**Comment by Glitchfinder** [comment]
Is there a more appropriate word that can be used, that would fit in the space provided?

**Comment by Quavelen** [comment]
Closed due to lack of response from @Yukyxy.
Can be re-opened if they return, and respond.
