### ISSUE TITLE
Unbreakable Axes "break", Then Can't Be Used For TreeFeller

### ISSUE THREAD

**Issue by PetrichorCraft** [mcMMO-Dev/mcMMO#3391]
Hello. So, I recently gave a player an Unbreakable axe as a voting reward (/give Player diamond_axe 1 {Unbreakable:1}) They used this axe, combined with TreeFeller, to break a tree. mcMMO said that the axe had broken, like it does sometimes (but usually the axe actually breaks, since most axes are not unbreakable). Something to the effect of "Your axe has splintered into dozens of pieces!". Since this axe was unbreakable, the axe did not break. However, the problem is that the axe is no longer usable with TreeFeller. When they attempt to use the axe with treefeller, it tells them that their axe splinters into dozens of pieces again, even on small oak trees.

Server Version: 1.12.2
mcMMO Version: 1.5.09-SNAPSHOT

Is there any fix for this? It would be nice to be able to have unbreakable axes as an option for my top voters, without them losing a big part of their function.

**Comment by PetrichorCraft** [comment]
May I ask why this was closed? (If I did something wrong, that's fine, but I do want to know)

**Comment by Glitchfinder** [comment]
It looks to have been addressed in the pull request that got accepted a day ago. The fix won't be on Spigot yet, but a current build will respect the Unbreakable tag.
