### ISSUE TITLE
Request: Shield Skill Ideas

### ISSUE THREAD

**Issue by WyattLW** [mcMMO-Dev/mcMMO#3393]
Since they added shields since a while, would it be possible to have some kind of leveling about that?
Like it might be a skill leveled up with blocking an attack, example about xp logic:

Block PVE Attack: (base_xp * absorbed dmg)/2
Block PVP Attack: (base_xp * absorbed_damage)

Or even separate melee and ranged attacks..

If it's just too complicated to make i would just make it child skill to: Acrobatics / Axes / Swords
Math example:    (level_Axes+level_Swords+level_Acrobatics*2)/4

Wich effect i suggest?
I would make so that when you have your shield equipped as offhand, you get extra Heart Canisters, like 1 Heart Canister every 100 Levels

Or slightly increase block chance (dodge from acrobatics) whenever shield is equipped, even if not in block animation (1-2% block rate every 100 Levels?)
I saw there is a mechanic for disarming, and one for dodging that (iron grip was it named?)
Maybe we can have a counter stat to that

Or might give the chance to decrease damage received / have hp regen effect while in blocking animation and shifting, makes sense to reduce movement speed to have more defense for a while (intended as passive skill, tho even as active would be good, activated on blocking)

Last idea that came to my mind? Active skill that reduces damage income by like 20% for a duration, depending on skill level (as ones for mining and excavation)

How to stick in active skill activation if it overrides with sword/axe one during fight? Activate it whenever is successful block! Passively activate an active skill, sounds cool uh?

Hope my suggestions and ideas don't fall too far from the mcMMO and that those keep the original style of the plugin!

P.S. I've been playing with mcMMO since ages and bought it in the end, please keep the good work up cause this is one of best plugins available around! :)

**Comment by WyattLW** [comment]
So, seeing the dev is actually back working on mcmmo, what about a "Bump"

**Comment by Chew** [comment]
This was technically already suggested in #3331, so discussion should merge there. Thank you!
