### ISSUE TITLE
Giga Drill Breaker - bugged ?

### ISSUE THREAD

**Issue by LazosPlaying** [mcMMO-Dev/mcMMO#3394]
Hello 😄 
My players reported an issue with Giga Drill, we tested it and we were able to replicate it (not just a occasional bug then)

Issue: When you activate Giga Drill and just keep spamming right click, you will keep it after it times out. The shovel will not have the enchantment visible, but will act like it has it until you relog or somehow fully reload the data (maybe also when switching worlds, we did not test that)

Server info:

MCMMO build: 1.5.07 snapshot (I did update to latest one now, I'll update the post if it will still be the same after the server reboot - tomorrow)
Server build: Spigot 1.11.2 
API version: 1.11.2-R0.1-sapshot

Thank you for any info in advance ^-^
Regards,
~Lazos

**Comment by Glitchfinder** [comment]
Are you able to provide more information on how to trigger this bug? I don't seem to be able to replicate it.

**Comment by LazosPlaying** [comment]
Sorry for not leaving extra into. Seems like the update patched things somehow. I'm not able to replicate this anymore with the latest build.

**Comment by Glitchfinder** [comment]
Good to hear! If it shows up again, just reopen the ticket and let us know how you manage to trigger it.
