### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by Orion91001** [mcMMO-Dev/mcMMO#3398]
I have installed the Mcmmo plugin and it is not working for me i have got the plugin installed on my server accept when i do /pl (ingame) it shows me the Mcmmo plugin is red and not working and all the other plugins that are working are in green. Can anyone tell me why Mcmmo is not working and how I can fix this situation

Console paste of mcmmo error
https://pastebin.com/hp9KKpiv

Console paste of versions
https://pastebin.com/CksLA45g

**Comment by Glitchfinder** [comment]
You're trying to run a current mcMMO build on Minecraft version 1.8.8, which came out two and a half years ago. If you want to run mcMMO on that server, you'll need an older build. [There is one suggested on the spigot page](http://www.dirkocraft.net/mcMMO.jar).

**Comment by Orion91001** [comment]
yeah i figured that out after i updated to a latest verion of bukkit
