### ISSUE TITLE
Fishing no longer giving experience.

### ISSUE THREAD

**Issue by jdk789** [mcMMO-Dev/mcMMO#3399]
I have been using this plugin leveling up my fishing level and I discovered that I am no longer being given experience for catching fish. I restarted my server, logged off and on and also tried in and outside a claimed area but no experience was given still. So far it is just my User having this issue however I am the owner so i am oped. My Fishing level is currently only 292 so not overly high and there is no max level set in the config.

I am running 1.5.09-snapshot (latest version)

Any help of advise would be much appreciated as if I am having this issue my members could have this issue aswell.

**Comment by Deathinflames** [comment]
This must be a config issue because i am using the same version and i still get experience whether i am opped or de-opped with fishing level over 600.

**Comment by jdk789** [comment]
See I have been thru the config file many times and can't find anything that would be causing this. The ability to gain XP came back after a while and then after a while of leveling it stopped giving XP again.

**Comment by Geekerandy** [comment]
Sounds like you might have diminishing returns turned on, and that is a config option. If not, this might be an actual issue.

**Comment by Glitchfinder** [comment]
There are two things that might affect experience that way. First is a database outage, which would cause notably more issues than just this. Second is diminishing returns, which is a config option that I thought was defaulted to off. Can you check your experience.yml file to see if Diminished_Returns is enabled?
