### ISSUE TITLE
Resetting all player skills

### ISSUE THREAD

**Issue by xComboed** [mcMMO-Dev/mcMMO#3402]
I know there is a command to reset the skills of a player. But is there also a way to reset all players there skill levels? My server is going to reset soon and i want everyone to start with 0 mcmmo levels.

**Comment by Glitchfinder** [comment]
If that's the case, it's easier to just clear out the mcMMO database. The plugin stores data in two locations. Information on player modified blocks is stored in the world directory in a folder named mcmmo_regions, while information on player levels is stored either in the plugin directory as a flatfile, or in an SQL database, depending on how it's configured. If you want to clear out all player levels, the fastest and simplest way to do so is to delete that player database and let mcMMO re-initialize it from scratch.
