### ISSUE TITLE
Sweeping attack and axes

### ISSUE THREAD

**Issue by Dzondzo** [mcMMO-Dev/mcMMO#3403]
I will start off by saying that this is not an issue, but a question I have not found an answer to anywhere. I also do not know where to ask questions so I will here.
If you spam your axe will it damage armor the same way it does when waiting out the attack cooldown?

**Comment by Glitchfinder** [comment]
To the best of my knowledge, none of the mcMMO combat abilities have been adjusted for the modern combat mechanics. In theory, yes. it would still act as it did back in 1.8.
