### ISSUE TITLE
SuperBreaker wont work

### ISSUE THREAD

**Issue by Regnak85** [mcMMO-Dev/mcMMO#3405]
Latest Dev Version 5 & 4

If we try SuperBreaker: Fireworks start, it seems to be fine... But if you mine, its normal Speed.
No Higher Drops, nothing.

GigaDrill, and everything else, works fine! Only SuperBreaker isnt going to be faster...

**Comment by Glitchfinder** [comment]
When you use Super Breaker, does the pickaxe get modified? It should have an additional 5 efficiency enchant levels applied to it, meaning that a normal unenchanted pick would be an Efficiency V pick, while one with the vanilla maximum of Efficiency V would be an Efficiency X (or 10, not sure how it gets rendered) pick.

**Comment by maverson** [comment]
yes it gets modified both enchanted and unenchanted pickaxes get the +V efficiency, so I became VI etc. Also the firework to notify it starts and stops also go off but the speed is still hindered.
