### ISSUE TITLE
Error when McMMO starts up. 

### ISSUE THREAD

**Issue by DKing328** [mcMMO-Dev/mcMMO#3411]
Hey there, I'm getting an error when this plugin starts up. 
https://i.imgur.com/qTN8pWD.png

Server Version: [18:22:07 INFO]: This server is running Paper version git-Paper-1338 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
McMMO Version: [18:25:51 INFO]: mcMMO version 1.5.09-SNAPSHOT

**Comment by Glitchfinder** [comment]
Luckily, this is a warning rather than an error. Also luckily, it [appears to have already been patched](https://github.com/mcMMO-Dev/mcMMO/commit/d4f2f0e11b538d0ee9ea06d91578a291b35c36a1), though I don't know if this is in the build on spigot's site yet.
