### ISSUE TITLE
MCMMO isnt working at all.

### ISSUE THREAD

**Issue by yitzil** [mcMMO-Dev/mcMMO#3412]
[22:43:51 INFO]: [mcMMO] Enabling mcMMO v1.5.09-SNAPSHOT
[22:43:51 ERROR]: [mcMMO] There was an error while enabling mcMMO!
> [22:43:51 WARN]: java.lang.NoSuchFieldError: MENDING
> [22:43:51 WARN]: at com.gmail.nossr50.util.EnchantmentUtils.<clinit>(EnchantmentUtils.java:34)
> [22:43:51 WARN]: at com.gmail.nossr50.config.treasure.TreasureConfig.loadEnchantments(TreasureConfig.java:368)
> [22:43:51 WARN]: at com.gmail.nossr50.config.treasure.TreasureConfig.loadKeys(TreasureConfig.java:105)
> [22:43:51 WARN]: at com.gmail.nossr50.config.treasure.TreasureConfig.<init>(TreasureConfig.java:46)
> [22:43:51 WARN]: at com.gmail.nossr50.config.treasure.TreasureConfig.getInstance(TreasureConfig.java:52)
> [22:43:51 WARN]: at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:385)
> [22:43:51 WARN]: at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:145)
> [22:43:51 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
> [22:43:51 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
> [22:43:51 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
> [22:43:51 WARN]: at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356)
> [22:43:51 WARN]: at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316)
> [22:43:51 WARN]: at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:153)
> [22:43:51 WARN]: at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505)
> [22:43:51 WARN]: at java.lang.Thread.run(Thread.java:748)
> [22:43:51 INFO]: [mcMMO] Disabling mcMMO v1.5.09-SNAPSHOT

**Comment by yitzil** [comment]
HELP!!!!

**Comment by Glitchfinder** [comment]
What server version are you using? This particular stacktrace tends to show up when someone uses a current mcMMO build on a server too old to have the Mending enchantment.

**Comment by yitzil** [comment]
OK thanks!
