### ISSUE TITLE
[1.7.10] Error on Enabling

### ISSUE THREAD

**Issue by Elrol** [mcMMO-Dev/mcMMO#3415]
I am making a new server to do some testing on, I have used craftbukkit and also cauldron, both still throw the same error. 

server log: https://pastebin.com/9gDJ2hrs

I am aware that this is an older version of mc, but seeing as how people still play on it, and it still works, I am hoping that someone will be able to help me solve this issue instead of closing it before it is solved.

**Comment by Glitchfinder** [comment]
The version of mcMMO you're trying to run uses features introduced in Minecraft much more recently, all the way up to 1.12. If you want to run mcMMO on a 1.7 server, you're going to need an appropriate build from [the old bukkitdev builds](https://dev.bukkit.org/projects/mcmmo/files). Version 1.4.08 looks like the one you need.
