### ISSUE TITLE
Kick error

### ISSUE THREAD

**Issue by EthanTG** [mcMMO-Dev/mcMMO#3420]
![screenshot 2018-03-23 at 4 08 41 pm](https://user-images.githubusercontent.com/29691919/37851255-8f4a368c-2eb4-11e8-87ce-48b68d875f8f.png)
My kick message is:

"Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/14 () was larged than I expected, found 6 bytes extra whilst reading packet 14"

As you can see in the image, I perform a command and I get kicked.

**Comment by EthanTG** [comment]
nobody yet? ;(

**Comment by t00thpick1** [comment]
Hmm.. I cannot reproduce this, do you have any additional information?

**Comment by EthanTG** [comment]
It was an isolated incident; nothing really happened afterward. The server is on Spigot 1.12.2 and running mcMMO using 1.5.09-SNAPSHOT.
