### ISSUE TITLE
How to put Limit skill levels mcmmo?

### ISSUE THREAD

**Issue by TrizzerArts** [mcMMO-Dev/mcMMO#3421]
Could you tell me how to add a limit of levels of mcmmo skills?

**Comment by Glitchfinder** [comment]
If you go to the Skills section of config.yml, you'll see each individual skill has a Level_Cap option. That lets you set per-skill maximums. If you would rather set an overall maximum, you can also set the Power_Level_Cap option toward the top of the file. Those options don't directly conflict with each other, and the default setting of 0 effectively means 'no maximum.'
