### ISSUE TITLE
/inspect not working on offline players

### ISSUE THREAD

**Issue by leaguest1358** [mcMMO-Dev/mcMMO#3424]
when I use the command /inspect [playername] it works fine with online players. But when I use an offline player it gives the following response: "Player profile not loaded yet".

I am using MCMMO version 1.5.09-SNAPSHOT.
There is no error log when executing the command.

**Comment by Momshroom** [comment]
Confirming that this has been the case on our server as well for quite some time.

**Comment by Glitchfinder** [comment]
I suspect this may be the end result of someone addressing #2284, but I'm not absolutely certain. What I do know is that, at least when UUIDs came out, we didn't have access to a direct username->UUID conversion that worked consistently.

**Comment by t00thpick1** [comment]
Closing due to 1.13 overhaul changes in progress touching the affected areas.
