### ISSUE TITLE
[Suggestion] Togglable Party System in config

### ISSUE THREAD

**Issue by DracarysPro** [mcMMO-Dev/mcMMO#3428]
Add a config toggle to entirely disable the Party system, which also does not register all the party commands at startup (to avoid conflicts with other plugins with /party commands) and all the party features.

**Comment by Glitchfinder** [comment]
This one has come up multiple times in the past. For more information, it's been discussed in #270, #611, #643, #698, #705, #1209, and #1637, among others.

**Comment by DracarysPro** [comment]
Dynamically registering commands is not possible? Instead of disabling them.

**Comment by Glitchfinder** [comment]
It's possible, but not in a way that would avoid breaking things, and definitely not in a way that is officially supported.
