### ISSUE TITLE
Disable repair/salvage use with /mcability

### ISSUE THREAD

**Issue by GiraffeCubed** [mcMMO-Dev/mcMMO#3432]
With /mcability toggled off, players can still accidentally salvage, or repair items and lose the items or enchantments. I have had players repair their items whilst fighting and lose their enchantments, the ability to toggle this off could resolve this problem.

It should be expected that toggling /mcability also affects repair and salvage.

Hopefully this is a simple request to implement!

**Comment by SXRWahrheit** [comment]
This would be beneficial to me, also. I tried disabling salvage via a permission for a specific world today, but it doesn't appear to be working. I was able to block repair anvils, though.

It would be nice to not have to resort to blocking the feature.

**Comment by t00thpick1** [comment]
Closing due to 1.13 overhaul changes in progress touching the affected areas.

**Comment by SXRWahrheit** [comment]
Can you clarify?
