### ISSUE TITLE
lag spike

### ISSUE THREAD

**Issue by Cobwebster** [mcMMO-Dev/mcMMO#3435]
https://timings.aikar.co/?id=d6598411402b4751a5c6f2350e6635f4

mcMMO::Event: c.g.n.l.PlayerListener (PlayerPickupItemEvent)

latest paperclip and mcmmo version, filter the timings like this https://gyazo.com/fb9cf86024935a71925f6ae8376f6e27

**Comment by Glitchfinder** [comment]
....What happened? That task averaged slightly longer than 1 millisecond, according to the timings you linked. But, in that eight or so minute timeframe, it ran a little over thirty-five *thousand* times. I'm going to need a bit more context to try to figure out what could have caused that.

**Comment by Cobwebster** [comment]
We're not entirely sure, we've got a basic survival setup with griefprevention. we've seen this before on our skyblock server also where it randomly spikes (not too often). Both are paperclip although its unlikely the cause.

**Comment by Glitchfinder** [comment]
Is anyone running some kind of impressively effective item farm? Because that timings log indicates just shy of 4,400 items being picked up *per minute* as the spike was happening.

**Comment by Cobwebster** [comment]
Potentially a grinder, someone picking that many items up can easily be achieved by smashing a full chest. and having a empty inventory, I guess all of those checks add up and destroys TPS.

**Comment by Glitchfinder** [comment]
No, probably not a chest. At least, not just one. This isn't individual items, per se. It's item stacks. A grinder might be able to cause that via individual item drops, but to get that many from smashing chests would be about 81 double chests per second. Unless, of course, breaking a chest splits stacks into individual items on your server. In which case even a few chests would be enough to do it.

**Comment by Cobwebster** [comment]
paperclip typically has good item merging, i can't really think of anything that would generate that many items which don't stack.
