### ISSUE TITLE
triggering ability "you ready your fist" when opening shulker boxes

### ISSUE THREAD

**Issue by leaguest1358** [mcMMO-Dev/mcMMO#3438]
update on my previous issue:
https://github.com/mcMMO-Dev/mcMMO/issues/3423
which should be fixed with:
https://github.com/mcMMO-Dev/mcMMO/commit/875db44afdd787a14e58d3e6240602908fd8c95e

now, on: https://popicraft.net/jenkins/job/mcMMO/
I have downloaded the newest version, it is fixed since build 6. so it says
But I keep having the problem that I am triggering an ability while opening a shulker box
![2018-04-29_14 58 52](https://user-images.githubusercontent.com/37934317/39406906-8d6f9812-4bbe-11e8-89fd-b46e7246f39b.png)

Is there something else causing this?
ps. there is no error log in console to help me out.

**Comment by GiovanH** [comment]
Did you see any change with 875db44 at all?

**Comment by Glitchfinder** [comment]
....that would be because, for some reason, that commit prevents shulker shells (the item) from activating abilities, This is now fixed as of https://github.com/mcMMO-Dev/mcMMO/commit/5b2ebf4aa866fa85335f237d5d401ff6ecd6e80b.

**Comment by leaguest1358** [comment]
I did not see any changes with https://github.com/mcMMO-Dev/mcMMO/commit/875db44afdd787a14e58d3e6240602908fd8c95e

**Comment by leaguest1358** [comment]
I will test the new version to see if it fixes it, Thanks for helping in so short notice 😄 🍪

**Comment by leaguest1358** [comment]
And so time passed, testing has happened, and it works just fine, thanks 😄 🍪
