### ISSUE TITLE
mcMMO build for 1.11.2?

### ISSUE THREAD

**Issue by AshtonMemer** [mcMMO-Dev/mcMMO#3442]
I have tried many mcMMO builds, and none work for my server version 1.11.2. They usually end up not running commands when typed, except one build I found works, but players do not earn EXP. Which build is the correct build for Spigot 1.11.2? Thank you!

**Comment by GiovanH** [comment]
Provide your server version (bukkit/spigot) and relevant logs.

**Comment by AshtonMemer** [comment]
Ended up switching to 1.12.2. Sorry for not responding.
