### ISSUE TITLE
Experience issue

### ISSUE THREAD

**Issue by AIphaDragon** [mcMMO-Dev/mcMMO#3443]
Hello,
I have got a problem with EXP from mobs. I use custom configuration with EXP receiving, so I forbade EXP from iron golems, snowmans, squids. The problem is, they still give EXP to players by initial configuration, not mine. So, how can I solve such problem?
I am looking forward to your answer

McMMo version: 1.5.09
Spigot vestion: 1.11.2
config.yml: https://pastebin.com/3AuADHw9
experience.yml: https://pastebin.com/

**Comment by Glitchfinder** [comment]
Are you able to provide a copy of your experience.yml file? It looks like the link may just be to pastebin. And can you clarify if you mean experience toward mcMMO skills, or experience orbs dropped by the mobs?

**Comment by AIphaDragon** [comment]
Well, here is a pastebin of experience.yml: https://pastebin.com/4MEKwYHN
And here is a link to download from Google Drive: https://drive.google.com/open?id=10lhd1rZdvlobV_UPpPiiCkCXStwzs_R8

**Comment by Glitchfinder** [comment]
Hmm. What happens if you remove those zeroed out lines from the config enirely? It's a dynamic config, so in theory removing those lines entirely would prevent players from earning experience from those mobs.

**Comment by Glitchfinder** [comment]
All right, so I confirmed that this is a bug and fixed it. However, current builds of mcMMO are not backwards compatible to 1.11 due to some changes made to the Bukkit API.

**Comment by AIphaDragon** [comment]
Okay, thank you for your help
