### ISSUE TITLE
McMMO needs update to latest spigot. Item stacks can be null.

### ISSUE THREAD

**Issue by andrewkm** [mcMMO-Dev/mcMMO#3446]
McMMO needs update.
https://pastebin.com/raw/CzBDnqRG

Reference: https://hub.spigotmc.org/jira/browse/SPIGOT-3923

**Comment by andrewkm** [comment]
Oops, accidentally clicked close on wrong issue.

**Comment by GiovanH** [comment]
It looks like this is an interaction between plugins. Please post a list of your installed plugins and an error log from the most recent version of mcMMO.

**Comment by andrewkm** [comment]
All good, you may close the issue, we’ve updated our fork of McMMO for 1.13

@giovanH you’ll eventually need to update this as the above is in fact an McMMO problem and McMMO will break with the coming spigot changes (that were for the time being rolled back by md_5)

**Comment by andrewkm** [comment]
@Glitchfinder can confirm, all our custom plugins have taken quite a while to get this done in advance. The change sucks.

**Comment by t00thpick1** [comment]
@andrewkm  I'm aware, 1.13 is going to be by far the largest amount of update effort I've put in for a while now.
