### ISSUE TITLE
There was an error while enabling mcMMO!

### ISSUE THREAD

**Issue by RixZtha** [mcMMO-Dev/mcMMO#3448]
I am trying to get MCMMO  plugin but it is showing errors. I am currently using minecraft version 1.11.2 and mcMMO version v1.5.00-b3547

> java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
50[07:41:56] [Server thread/WARN]: at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:163)
51[07:41:56] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
52[07:41:56] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
53[07:41:56] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
54[07:41:56] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376)
55[07:41:56] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326)
56[07:41:56] [Server thread/WARN]: at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:205)
57[07:41:56] [Server thread/WARN]: at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544)
58[07:41:56] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
59[07:41:56] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.5.00-b3547
60[07:41:56] [Server thread/ERROR]: Error occurred while disabling mcMMO v1.5.00-b3547 (Is it up to date?)
61java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
62	at com.gmail.nossr50.util.player.UserManager.saveAll(UserManager.java:53) ~[?:?]
63	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:204) ~[?:?]
64	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
65	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
66	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
67	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:193) [mcMMO.jar:?]
68	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
69	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
70	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
71	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
72	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
73	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:205) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
74	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [minecraft_server.jar:git-Spigot-3fb9445-6e3cec8]
75	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

**Comment by Glitchfinder** [comment]
You're running mcMMO version 1.5.00, which is a Minecraft 1.7 build, on a version 1.11 server. You need a more recent version, such as [one of the earlier builds on this tracker](https://popicraft.net/jenkins/job/mcMMO/).

**Comment by RixZtha** [comment]
Oh ok. thank you for your time
