### ISSUE TITLE
Herbalism don't work if your level is over 1000

### ISSUE THREAD

**Issue by Ironic8b498** [mcMMO-Dev/mcMMO#3456]
My herbalism is 1276 and has not gone up much in the past year due to me not getting all the XP for each block broken I get like 40XP for every 10 blocks broken, seems to work fine for players that have a few hundred skill level

**Comment by Glitchfinder** [comment]
There are several bugs related to herbalism experience that were recently patched, including not getting experience on crops (wheat, beetroot, carrots, potatoes, netherwart, and cocoa), and not getting experience when autoplanting crops (wheat, beetroot, carrots, potatoes, and netherwart), as well as not getting experience when using normal to grow crops (wheat, beetroot, carrots, potatoes, netherwart, and cocoa).

Can you double check with [the latest build](https://popicraft.net/jenkins/job/mcMMO/) to be sure it isn't one of those issues? You will likely need to harvest and replant the farm to clear existing flags marking the blocks as plauer-made.

**Comment by Ironic8b498** [comment]
I was testing on dev build 7

**Comment by Ironic8b498** [comment]
didn't seem to fix it,might be better, seems to work about 40% of the time

**Comment by Glitchfinder** [comment]
Just to be sure, this is after you replanted the farm to help clear the block flags we set?

If it is, could you test while preventing autoplant? To do that, harvest a farm with your inventory full of items that prevent you from picking up seeds, and make sure you have no seeds in your inventory.
