### ISSUE TITLE
Massive Lag due to Axes?

### ISSUE THREAD

**Issue by SoraShiunin** [mcMMO-Dev/mcMMO#3464]
It seems that as of the update some massive lag happens when someone uses Skull Splitter.
Dropping the log file here. Unsure if its actually mcmmo.
[2018-05-31-3.log](https://github.com/mcMMO-Dev/mcMMO/files/2060131/2018-05-31-3.log)

**Comment by AvarianKnight** [comment]
Could not pass event EntityDamageEvent to ProjectKorra v1.8.6

**Comment by t00thpick1** [comment]
Closing due to 1.13 overhaul changes in progress touching the affected areas.
