### ISSUE TITLE
RSS issue.

### ISSUE THREAD

**Issue by andrewkm** [mcMMO-Dev/mcMMO#3469]
The jenkins where this is hosted is giving me RSS issues for:
https://popicraft.net/jenkins/job/mcMMO/

The RSS shows the latest files just fine:
https://i.imgur.com/DKBSLMA.png

However, when clicking on a link it re-directs me to:
http://127.0.0.1:8081/jenkins/job/mcMMO/

There is some sort of RSS issue on your end as all my other feeds (for over 100+ plugins & jenkins) works perfectly fine.

**Comment by popcorn9499** [comment]
I will look into it sorry must not be redirecting internally or something. I'll try to fix later tonight

**Comment by popcorn9499** [comment]
The issue should be fixed to my knowledge. If anyone is better with apache modproxy and stuff I would gladly like to talk to them but the rss stuff is working now sorry about that @andrewkm

**Comment by andrewkm** [comment]
@popcorn9499 still not working for me.

**Comment by popcorn9499** [comment]
i just reloaded jenkins so could u check again?

**Comment by andrewkm** [comment]
Example: www.feedly.com

1. https://i.imgur.com/4F0lXS4.png
2. https://i.imgur.com/ydZGhNF.png
3. https://i.imgur.com/ReOaMXL.png
4. https://i.imgur.com/pK8DTrd.png
5. https://i.imgur.com/gNFv5T8.png

**Comment by popcorn9499** [comment]
https://popicraft.net/jenkins/job/mcMMO/rssAll
show me what shows up directly from here?

**Comment by andrewkm** [comment]
@popcorn9499 

Still no good here:
https://i.imgur.com/xeJvqNp.png

That link shows me:
(https://popicraft.net/jenkins/job/mcMMO/rssAll)
https://pastebin.com/raw/KcjXKqpP

**Comment by popcorn9499** [comment]
Its looking like it hasnt seen my change or is caching it..

**Comment by popcorn9499** [comment]
I say this as previously even the raw rss was referencing 127.x.x.x which i fixed now and in the raw it shows 

 href="http://popicraft.net:80/jenkins/job/mcMMO/"
as the link its going to so I have a suspicion that feedly is caching and only checking so often as to not overload the other rss servers

**Comment by popcorn9499** [comment]
Right now my actual slave build server is down due to a thunderstorm but I will look more when it comes back up. please andrew check in 24 hours tops and tell me if its till being like that as I am honestly unconvinced that its still not setup so u can use the rss

**Comment by popcorn9499** [comment]
thunderbird views it correctly now which is why i am thinking this https://i.imgur.com/7icAyEf.png

**Comment by andrewkm** [comment]
I'll try again in a few hours and let you know :)

**Comment by popcorn9499** [comment]
I have checked today and it seems to be working @andrewkm if a problem exists please let me know.

**Comment by popcorn9499** [comment]
thanks im glad
