### ISSUE TITLE
Caching layer for /mctop

### ISSUE THREAD

**Issue by andrewkm** [mcMMO-Dev/mcMMO#3471]
How often does /mctop hit the database to recalculate all the power levels?
I'm assuming the calculation isn't done on every single /mctop command usage as that would be killer on the database.

I'd basically like to ask how often it recalculates and where it stores this value (memory?).

**Comment by t00thpick1** [comment]
@andrewkm  You got your symptoms reversed, the mctop command is run every time, but changes to your skill levels are only saved every X seconds (Configured save interval)

**Comment by andrewkm** [comment]
Ah I see! So does it make the database do a huge amount of math every time a player runs it?

Couldn’t that be a little resource intensive when say 200 players run it at once on a remote database?

**Comment by t00thpick1** [comment]
@andrewkm Assuming you haven't skimped on a shitty server to run your database on, it should be negligible.

**Comment by t00thpick1** [comment]
Andrew, I guess I can look into it.  However I am unavailable until july.
I am traveling and will not have a computer.  I was hoping to postpone all
major work until the 1.3 update but it keeps seeming further out so this
might not be great to wait for.  Considering we have a save interval for
levels, there is no reason we couldn't have a caching layer of about the
same lifetime.(after all, if the values can't change why recalculate them)

**Comment by andrewkm** [comment]
Alright awesome :)
Changed the title and will test when ya got something thrown together. Thanks for considering!

**Comment by t00thpick1** [comment]
Starting work on this this week.

**Comment by JamieSinn** [comment]
Awesome thanks!

**Comment by t00thpick1** [comment]
@andrewkm Do you mind trying something really simple that might work.  I realized long ago we added a "now()" into the mctop SQL query to force it not to use mySQL's built in query cache, I have no idea why, but I'm sure there was a reason at the time.  I'm going to try just removing that and if you could measure its effects that would be swell.

**Comment by t00thpick1** [comment]
If you would, try this build:  
[mcMMO-bin.zip](https://github.com/mcMMO-Dev/mcMMO/files/2172259/mcMMO-bin.zip)

**Comment by t00thpick1** [comment]
The 2 things I am looking for are:
1: Does it solve the problem 
2: Do mctop's still update over time to get new results

**Comment by JamieSinn** [comment]
@andrewkm

**Comment by andrewkm** [comment]
@t00thpick1 my bad dude. Been up north Canada at a cottage vacation.
I'll try that soon and let you know what's up :)

In the meantime though, your cooldown message is broken and would be really nice to accept this:
https://github.com/mcMMO-Dev/mcMMO/pull/3481

The message is straight up broken.

**Comment by andrewkm** [comment]
@t00thpick1 

![3 weeks later](https://i.imgur.com/31qODgt.png)

Sorry, been a hectic summer, at the cottage, travelling a lot, 1.13 updates, and everything. I had this on my todo list and it seemed to have slipped down quite a bit. Anyways, tested with the build you gave me but cannot seem to get it to load: https://github.com/mcMMO-Dev/mcMMO/files/2172259/mcMMO-bin.zip

https://pastebin.com/raw/JAVB3zhK

How should we proceed?

**Comment by t00thpick1** [comment]
Mm I gave you the wrong output file(Didn't have libraries shaded in).  Unfortuanently my local checkout is all over the place as I am hoping to have the first half of my 1.13 rewrite done and in alpha either this weekend or next (Its hard as I really only have time to work on it during the weekends, and then it is competing with other commitments as well).  I will write up a real fix for this first thing after that is released, both in the rewrite branch and the current branch(Which I will do due to the potential issues that the rewrite alpha might have in the beginning)

**Comment by andrewkm** [comment]
Alright awesome, thanks a lot @t00thpick1 
I too am swamped with all the 1.13.x updates :P Been pretty crazy.

**Comment by andrewkm** [comment]
@t00thpick1 any updates on this? Not sure if you wrote the fix yet in the new 1.13.x mcmmo or not.
PS: https://github.com/mcMMO-Dev/mcMMO/pull/3481 is still broken and doesn't shoot the correct message.

**Comment by t00thpick1** [comment]
@andrewkm I'm thinking I might just add a new column that is a pre-added sum of the skills so we can just index it, rather than needing to math it all out every time, that should resolve the issue,  if I mock up a test jar would you be willing to give it a try?

**Comment by t00thpick1** [comment]
Actually when I think about it, you can test that theory without needing a custom build, just re-run your original test but instead of normal mctop,  do mctop for a particular skill so it hits the indexed columns.

**Comment by t00thpick1** [comment]
I'm going to do this regardless in the next few days because it will speed up the queries, but it will be interesting if you can get results back on that.

**Comment by andrewkm** [comment]
My github email was completely screwed up on my iphone and I wasn't getting any notifications for anything. Just fixed it recently and got blasted with outstanding emails, just now noticed this. Damn sorry @t00thpick1 - I'm all ready for any tests ya need. Just let me know when to download and what to test :)

**Comment by andrewkm** [comment]
@t00thpick1

I’m actually just in the middle of maintenance so I’ll backup the mcmmo DB and give it a spin. What specifically should I look out for in terms of issues l?

**Comment by t00thpick1** [comment]
@andrewkm Well it will either work, or not work...  and also it may take a while for the initial DB upgrade cause it has to populate the new field for every user.  I have no idea how long it might take, haven't worked with mysql in a while most of my professional work is nosql

**Comment by andrewkm** [comment]
@t00thpick1 

Startup: https://pastebin.com/raw/izihHfFk
DB: Looks good: https://i.imgur.com/MhK5Djm.png (I think?)
Now going to monitor performance.

**Comment by andrewkm** [comment]
@t00thpick1 /mctop now shows correct message btw:
https://i.imgur.com/Jqt1zyz.png

However, your /mcrank message (the one below it) is still broken.

**Comment by t00thpick1** [comment]
@andrewkm Awesome, keep me updated on if it solves the performance problem, I think it should, since it was doing the add and sort entirely in mysql every single time before, not indexed at all.

**Comment by andrewkm** [comment]
@t00thpick1
Do you want me to document the other issues as separate GitHub issues so they are organized?

**Comment by t00thpick1** [comment]
@andrewkm Please do.
