### ISSUE TITLE
Alchemy: somes potion not show progress

### ISSUE THREAD

**Issue by netherstar** [mcMMO-Dev/mcMMO#3476]
As you can see in this video, when i make "Potion of Absorption" progress not show
https://youtu.be/WdjsCx1ndBs
Mcmmo Latest version download from Spigotmc: [mcMMO] Running version 1.5.10
Server: Paperspigot 1.12.2

**Comment by LapizSeller** [comment]
Where can i download 2.0.0 version?

**Comment by mrfloris** [comment]
You can find the official mcMMO Spigot page here; 
https://www.spigotmc.org/resources/official-mcmmo.63489/

**Comment by Quavelen** [comment]
This is the overhaul repository, please use https://github.com/mcMMO-Dev/mcMMO-Classic for issues pertaining to mcMMO versions `1.6.x` and older.
