### ISSUE TITLE
Unarmed Item Pickup bug

### ISSUE THREAD

**Issue by Samfrog** [mcMMO-Dev/mcMMO#3480]
When attacking unarmed, if an item drops it skips the slot you have selected... and then every slot after. So if your selected slot is the first slot in your hotbar, every single second space in your inventory will be skipped. If your selected slot is the fourth slot, then items will fill your inventory normally until you get 4 items, and then every second space will be skipped. This only occurs attacking unarmed. Once your inventory is full and it has skipped spaces for 50% of your inventory, it will not let you pick items up unless you select a slot in your hotbar with an item in it. So if you remain unarmed, you can't pick things up, even if your inventory is actually only 50% full. I saw an option related to this in the config, but it had no effect.
In an effort to find a way to get rid of this bug, I tested this with:
All my plugins enabled
Only McMMO enabled
Multiple versions of McMMO
I even generated a completely fresh test server to test this on, tried two different versions of spigot, and even tried multiple versions of mcmmo individually on BOTH versions of spigot, both with and without other plugins.
Server version is 1.12
This bug was present on every version/test I tried. So, as I could not get rid of this bug myself, I'm reporting it to y'all. 
In the image attached below, you can see that my selected hotbar slot is the last slot, and that items filled my inventory normally until it hit that slot, but then skipped a slot from then on. There is also a named item below me on the very bottom edge towards the left that I am unable to pick up. In this specific case, other plugins were enabled, but as I mentioned before I did ample testing without other plugins. 
![image](https://user-images.githubusercontent.com/25758073/42121909-71fc750a-7c06-11e8-977d-208b9647beb5.png)

**Comment by t00thpick1** [comment]
Closing due to 1.13 overhaul changes in progress touching the affected areas.
