### ISSUE TITLE
McMMO treefeller bug? 

### ISSUE THREAD

**Issue by AccioAce** [mcMMO-Dev/mcMMO#3482]
Hi Author, with this latest version of McMMO. I believe there a tree feller bug from McMMO where they are only getting a few logs but not all of them as the players reported to me about. So I assume it's a McMMO bug.

**Comment by Glitchfinder** [comment]
Are you able to provide more information? Is it specific to any kind of tree, or does it happen with all trees? Is there a level range that is affected, or does it affect every player who uses Tree Feller?

**Comment by AccioAce** [comment]
I believe it happens to all trees.

**Comment by just1689** [comment]
Which version of the server, client and mcmmo are you now using? Is this an ongoing issue?
