### ISSUE TITLE
mcMMO not loading upon startup

### ISSUE THREAD

**Issue by MurryPuppins** [mcMMO-Dev/mcMMO#3483]
Hello, 

Recently updated my mcMMO to the latest version (1.5.10 at the time) and it produced [this error](https://hastebin.com/emibejupix.vbs). I did downgrade a version to the snapshot version before 1.5.10 and there were no issues loading it. Originally posted in IRC, but moved it to here after realizing it wasn't on my end (as far as I'm aware). Thanks and hopefully you can resolve this!

**Comment by t00thpick1** [comment]
This version was incompatible with older versions of spigot.
