### ISSUE TITLE
Spigot seems to have taken me off the buyer's list. O_o

### ISSUE THREAD

**Issue by krlsmnk** [mcMMO-Dev/mcMMO#3511]
Hi! I've been playing with McMMO since 2016 but I guess Spigot took me off the buyer's list. It's asking me to pay for the plugin again.
My current version seems to have stopped working in 1.13. Looks like you guys have updated it, though.

**Comment by t00thpick1** [comment]
Speak to spigot about that, but also the build server has all builds available for free...
