### ISSUE TITLE
Error fresh out the box MCMMO

### ISSUE THREAD

**Issue by younghans** [mcMMO-Dev/mcMMO#3512]
Hey installed MCMMO on my fresh, server, and cant seem to find a solution to this issue. Any ideas? Appreciate the input.

28.07 00:13:41 [Server] ERROR [mcMMO] Cannot read /plugins/mcMMO/experience.yml(File Permissions?)
28.07 00:13:41 [Server] INFO [mcMMO] Disabling mcMMO v1.5.10
28.07 00:13:41 [Server] WARN ... 11 more
28.07 00:13:41 [Server] WARN at java.lang.ClassLoader.loadClass(Unknown Source)
28.07 00:13:41 [Server] WARN at java.lang.ClassLoader.loadClass(Unknown Source)
28.07 00:13:41 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
28.07 00:13:41 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
28.07 00:13:41 [Server] WARN Caused by: java.lang.ClassNotFoundException: org.bukkit.NamespacedKey
28.07 00:13:41 [Server] WARN at java.lang.Thread.run(Unknown Source)
28.07 00:13:41 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542)
28.07 00:13:41 [Server] WARN at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:205)
28.07 00:13:41 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325)
28.07 00:13:41 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375)
28.07 00:13:41 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
28.07 00:13:41 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
28.07 00:13:41 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
28.07 00:13:41 [Server] WARN at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:167)
28.07 00:13:41 [Server] WARN at com.gmail.nossr50.mcMMO.registerCustomRecipes(mcMMO.java:437)
28.07 00:13:41 [Server] WARN at com.gmail.nossr50.util.ChimaeraWing.getChimaeraWingRecipe(ChimaeraWing.java:161)
28.07 00:13:41 [Server] WARN java.lang.NoClassDefFoundError: org/bukkit/NamespacedKey
28.07 00:13:41 [Server] ERROR [mcMMO] There was an error while enabling mcMMO!

**Comment by Glitchfinder** [comment]
You've got a version mismatch. Unfortunately, despite what the spigot page says (I don't have access to fix it), the latest builds are not backwards compatible to 1.11 servers. Would you be able to try [this build](https://popicraft.net/jenkins/job/mcMMO/3/) to see if it works?

@t00thpick1, the page on spigot needs to be updated with a specific latest build for 1.11, as at some point our 1.12 builds broke compatibility with 1.11 servers. I'm not sure where exactly that break happened, but 1.12 came out on June 7th of 2017, and I'm fairly certain the break happened before the first of my recent commits. That leaves about one and a half pages of potential commits, but I suspect [this commit](https://github.com/mcMMO-Dev/mcMMO/commit/d4f2f0e11b538d0ee9ea06d91578a291b35c36a1) is probably the breaking one. We'll know if that's the case if or when @younghans gets back to us.

**Comment by Haileykins** [comment]
If its any help, I'm 1.12.2 and the version I have running is 1.5.10-SNAPSHOT (just grabbed a version off of the Jenkins page)
