### ISSUE TITLE
Can't find the 1.6.0 version.

### ISSUE THREAD

**Issue by CSOUX** [mcMMO-Dev/mcMMO#3518]
I'm sorry if this is a dumb question but I paid for this plugin yesterday and haven't been able to use it at all. I'm using spigot 1.13 version so the 1.5.10 version isn't working. Where can I find the 1.6.0 version ?

**Comment by Glitchfinder** [comment]
You can find the 1.60 builds on our [development build server](https://popicraft.net/jenkins/job/mcMMO/). Any time a new commit goes to the repository, it will make a new build there.

**Comment by CSOUX** [comment]
Thanks a lot !
