### ISSUE TITLE
Won't work

### ISSUE THREAD

**Issue by codenameturtle** [mcMMO-Dev/mcMMO#3519]
To keep it short,
I tried all the links on the mcmmo page
I've tried blackspigot
I've tried everything
every single one when on my server is just in red and won't work
what do i do?

**Comment by BBoyJD10** [comment]
also have this

**Comment by Glitchfinder** [comment]
What is your server version? Is there an error in the startup log? If there is, can you post that? There's plenty of things that could be going wrong, but until we have more information, there isn't anything we can do to help.

**Comment by BBoyJD10** [comment]
paper 1.12.2

**Comment by Glitchfinder** [comment]
Okay, so [this](https://popicraft.net/jenkins/job/mcMMO/21/) should be the most recent build compatible with a 1.12 server. Just in case something odd happened with the configs, could you also delete the mcmmo folder in your plugins directory before you try it out? If there's something important in there you want to keep, copy it elsewhere and let mcMMO generate a new configuration from scratch.
