### ISSUE TITLE
Not receiving experience for certain skills

### ISSUE THREAD

**Issue by Haawhaaw** [mcMMO-Dev/mcMMO#3525]
People on my server do not receive any experience for Alchemy and very commonly we wont receive experience for fishing, everything seems to be running fine.
Using (https://popicraft.net/jenkins/job/mcMMO/32/) this version of the build on most recent spigot server and cant figure out why it isn't giving experience to folks. Thanks!

**Comment by Scorpionvssub** [comment]
fishing doesnt work for me
