### ISSUE TITLE
Errors on newest build

### ISSUE THREAD

**Issue by Amiroslo** [mcMMO-Dev/mcMMO#3527]
Im using the latest MCMMO with 1.12.2 and I am having an error, this happened after upgrading to the latest version

https://pastebin.com/8cqivaP2
https://pastebin.com/kZQtKnCw

**Comment by Glitchfinder** [comment]
1.60 is not backwards compatible to a 1.12 server. The latest build that will work on your server is [this one](https://popicraft.net/jenkins/job/mcMMO/21/).
