### ISSUE TITLE
Console error as of this morning with both #35 and #36

### ISSUE THREAD

**Issue by GothkittyGirl** [mcMMO-Dev/mcMMO#3529]
02.08 21:23:37 [Server] INFO [mcMMO] Enabling mcMMO v1.6.0-SNAPSHOT
02.08 21:23:39 [Server] ERROR [mcMMO] There was an error while enabling mcMMO!
02.08 21:23:39 [Server] WARN java.lang.IllegalArgumentException: Cannot get data for not block IRON_INGOT
02.08 21:23:39 [Server] WARN at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
02.08 21:23:39 [Server] WARN at org.bukkit.craftbukkit.v1_13_R1.block.data.CraftBlockData.newData(CraftBlockData.java:420)
02.08 21:23:39 [Server] WARN at org.bukkit.craftbukkit.v1_13_R1.CraftServer.createBlockData(CraftServer.java:1808)
02.08 21:23:39 [Server] WARN at org.bukkit.craftbukkit.v1_13_R1.CraftServer.createBlockData(CraftServer.java:1783)
02.08 21:23:39 [Server] WARN at org.bukkit.Bukkit.createBlockData(Bukkit.java:1185)
02.08 21:23:39 [Server] WARN at org.bukkit.Material.createBlockData(Material.java:1980)
02.08 21:23:39 [Server] WARN at com.gmail.nossr50.util.skills.SkillUtils.getRepairAndSalvageQuantities(SkillUtils.java:281)
02.08 21:23:39 [Server] WARN at com.gmail.nossr50.config.skills.repair.RepairConfig.loadKeys(RepairConfig.java:139)
02.08 21:23:39 [Server] WARN at com.gmail.nossr50.config.skills.repair.RepairConfig.<init>(RepairConfig.java:24)
02.08 21:23:39 [Server] WARN at com.gmail.nossr50.config.skills.repair.RepairConfigManager.<init>(RepairConfigManager.java:34)
02.08 21:23:39 [Server] WARN at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:399)
02.08 21:23:39 [Server] WARN at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:133)
02.08 21:23:39 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
02.08 21:23:39 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
02.08 21:23:39 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
02.08 21:23:39 [Server] WARN at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:425)
02.08 21:23:39 [Server] WARN at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:339)
02.08 21:23:39 [Server] WARN at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:214)
02.08 21:23:39 [Server] WARN at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686)
02.08 21:23:39 [Server] WARN at java.lang.Thread.run(Thread.java:748)
02.08 21:23:39 [Server] INFO [mcMMO] Disabling mcMMO v1.6.0-SNAPSHOT

**Comment by Glitchfinder** [comment]
There's an issue with the config. That said, there is already a copy of this error log in #3498, where we're consolidating all of the 1.13 update issues.

**Comment by GothkittyGirl** [comment]
oh ok sorry about that and ty for quick reply
