### ISSUE TITLE
Sugar Cane not give exp

### ISSUE THREAD

**Issue by crston** [mcMMO-Dev/mcMMO#3531]

**Comment by Momshroom** [comment]
I can verify that in dev build 37 and Spigot 1.13 sugarcane are not giving herbalism xp.  Neither are melons or kelp (not sure if kelp was intended to be added.) 

Wheat, flowers, cocoa, lilypads, carrots, potatoes, pumpkin, beats, and grass do.

**Comment by DevonPalma** [comment]
If you would like a quick fix edit line 173 "Experience.Herbalism.Sugar_Cane_Block" to "Experience.Herbalism.Sugar_Cane"
