### ISSUE TITLE
Instance grown crops, and Salvage issues

### ISSUE THREAD

**Issue by Ironic8b498** [mcMMO-Dev/mcMMO#3535]
I'm run Dev build #37 on Spigot 1.13 and I have a herbalism of 1303. When I break wheat, potatoes and carrots the replant is fully grown. Beets and Nether Wart don't replant at all. Also my salvage skill is 1177 when I salvage items I only get 50% of the materials when I have it set to give 100% after skill level of 1000.

**Comment by Momshroom** [comment]
We're running dev build 40 on Spigot 1.13.1 and have the same issue with salvage:  players are getting far less material than they should from it.   Also, and possibly related: players are getting MORE repair than they should.  A player with no prior repair skill is able to more than half repair most items with single ingot/diamond and a player with 514 Salvage who should be getting 51.4% of materials only gets a single ingot/diamond from a full health chestplate.
