### ISSUE TITLE
furnace event

### ISSUE THREAD

**Issue by Scorpionvssub** [mcMMO-Dev/mcMMO#3536]
Getting this error constantly:
https://hasteb.in/omoyucav.cs

**Comment by Scorpionvssub** [comment]
![image](https://user-images.githubusercontent.com/12249763/43679833-c656651a-982c-11e8-8f86-5458ce223e3b.png)
Also getting the above.... the names are blacked out for some weird reason

**Comment by broccolai** [comment]
Fixed by #3537
