### ISSUE TITLE
No XP receving with Alchemy skill

### ISSUE THREAD

**Issue by CirnoKaster** [mcMMO-Dev/mcMMO#3538]
There are no XP receiving with Alchemy skill on both using nether ward, redstone powder and pufferfish, others not tested.
*Using build #37

**Comment by thunderlight411** [comment]
Same issue with build [#40](https://popicraft.net/jenkins/job/mcMMO/40/)

**Comment by t00thpick1** [comment]
Tracking this issue with https://github.com/mcMMO-Dev/mcMMO/issues/3564
