### ISSUE TITLE
Any 1.13 items obtainable from fishing?

### ISSUE THREAD

**Issue by killerbutterfly** [mcMMO-Dev/mcMMO#3540]
Hello, I play on a server that hasnt upgraded to 1.13 yet and im wondering if Mcmmo has updated where you are able to get 1.13 items from fishing (tridents, nautilus shells, all types of fish, etc). If not i guess this could be a suggestion

**Comment by Thatsmusic99** [comment]
McMMO is not compatible with 1.13 after having it on a test server and I don't know if the developers are active or not. I have got a self-made build that I'm testing to see if it works in 1.13 but so far it's required a whole config reset due to item name changes. So far it partially works but I've still got to clean up some areas.

**Comment by Sikatsu** [comment]
You'd have to add it yourself.

**Comment by just1689** [comment]
Can we close this?

**Comment by Sikatsu** [comment]
Well, the official config has yet to be updated with nautilus shells.

**Comment by mrfloris** [comment]
If we fresh-install mcMMO it would be expected that items from 1.9, 1.10, 1.11, 1.12, and 1.13.2 would be there as some rewards, it's annoying to keep track ourselves when we configure servers, when the installation instructions are just drop the jar in the plugins folder and restart the server. 

I'd love to see newer items being added to rewards, and I believe mcMMO 2.1 or higher might introduce these?

**Comment by nossr50** [comment]
I'll be looking at newer items not being accounted for in mcMMO in 2.1.0

**Comment by GiraffeCubed** [comment]
More mobs supported by shake would also be nice.

**Comment by nossr50** [comment]
@GiraffeCubed good idea

**Comment by pie3636** [comment]
Any news on this? It's been a year and a half...

**Comment by Momshroom** [comment]
For now you can add things to your treasures.yml

**Comment by pie3636** [comment]
You cannot (as far as I'm aware) add newer enchantments such as mending. And even if you do, why is it not included by default in the config? The config already includes netherite tools which are 2 weeks old. Surely it could also include enchantments that were added in the game two years ago?

**Comment by Draycia** [comment]
It's a code limitation. The configs don't support mending books because they use material names / item IDs. Mending books don't have an I'd, they're enchanted_book with enchanted item data. There's a config rewrite going on so patching the old system is low priority.

**Comment by mrfloris** [comment]
I see this is closed, and I see some things were referenced, but I can't figure out if this now means that when we delete treasures.yml and let it rebuild that we will get the missing items from 1.9 --> 1.16.4 added?

**Comment by nossr50** [comment]
> I see this is closed, and I see some things were referenced, but I can't figure out if this now means that when we delete treasures.yml and let it rebuild that we will get the missing items from 1.9 --> 1.16.4 added?

I'd advise reading the changelog on the spigot page for 2.1.164 carefully, the fishing treasures have moved to a new file so its generation will inlcude some missing items such as nautilus shells, enchanted books, name tags, etc, but I have not added anything else to it, I did tweak some of the drops (such as making records drop across varying tiers). A rewrite to the loot tables will come in the future (also mentioned in the changelog)

**Comment by mrfloris** [comment]
> > I see this is closed, and I see some things were referenced, but I can't figure out if this now means that when we delete treasures.yml and let it rebuild that we will get the missing items from 1.9 --> 1.16.4 added?
> 
> I'd advise reading the changelog on the spigot page for 2.1.164 carefully, the fishing treasures have moved to a new file so its generation will inlcude some missing items such as nautilus shells, enchanted books, name tags, etc, but I have not added anything else to it, I did tweak some of the drops (such as making records drop across varying tiers). A rewrite to the loot tables will come in the future (also mentioned in the changelog)

Ah there's an mcMMO update, i thought it was still in progress, the changelog made more sense. Thanks for explaining. At the time of replying to github i wasn't aware a new build has come out

**Comment by nossr50** [comment]
> > > I see this is closed, and I see some things were referenced, but I can't figure out if this now means that when we delete treasures.yml and let it rebuild that we will get the missing items from 1.9 --> 1.16.4 added?
> > 
> > 
> > I'd advise reading the changelog on the spigot page for 2.1.164 carefully, the fishing treasures have moved to a new file so its generation will inlcude some missing items such as nautilus shells, enchanted books, name tags, etc, but I have not added anything else to it, I did tweak some of the drops (such as making records drop across varying tiers). A rewrite to the loot tables will come in the future (also mentioned in the changelog)
> 
> Ah there's an mcMMO update, i thought it was still in progress, the changelog made more sense. Thanks for explaining. At the time of replying to github i wasn't aware a new build has come out

Builds come out when the webhook goes out, and then it has to build, which can happen sometimes almost immediately, and other times it will take some time. I post in #news when the builds I put out on spigotmc are available.
