### ISSUE TITLE
MCMMO 1.7.10 link isnt working?

### ISSUE THREAD

**Issue by Salkio** [mcMMO-Dev/mcMMO#3550]
Hello,

Using an FTB server and trying to use MCMMO. I found some 1.7.10 files however it enables MCMMO creates the config files and then it gets disabled. Have any ideas why? 
https://pastebin.com/H1CdUzbh

Thanks

**Comment by L3Technosmith** [comment]
Are you using a version of mcMMO that works on Minecraft 1.7.10?

The exception looks like it is trying to create a recipe with an item the server cant find.  I would guess this is during the creations of the Chimera Wing recipe...which uses a Feather.  There is also a LEGACY_FEATHER in the source code.

May try disabling the Chimera Wing (Config.yml in Items, set Enabled to false).
Or ensure that you have an mcMMO that works with 1.7.10.
