### ISSUE TITLE
Visual Enchant Glitch

### ISSUE THREAD

**Issue by Felicette** [mcMMO-Dev/mcMMO#3552]
When using Super Breaker (or any other similar ability) and picking up the item in your inventory until the ability ends, it keeps the enchantment visually. https://gyazo.com/dd6749f72176e47cdc3a8460758aba0e. The visual efficiency is purely visual and stacks on top of other efficiencies (7 goes up to 12 etc).

**Comment by nossr50** [comment]
I'm sorry I'm having a hard time understanding the wording of this bug

Could you reword it in more simple terms?

**Comment by mrfloris** [comment]
Do you mean if you have an efficiency 5 pick axe and you drop it while in super breaker, and then pick it up, the 5+5 = now a pick axe with efficiency 10? I've never seen that happen.
