### ISSUE TITLE
mcMMO v1.5.09-SNAPSHOT Spigot 1.8.8

### ISSUE THREAD

**Issue by MyJumpsuit** [mcMMO-Dev/mcMMO#3553]
So I have a problem with mcMMO (this is the required version)

It keeps saying I do not have CompatNoChestPlus (witch  I do - and it is working fine and detects mcMMO) but mcMMO can not detect it, I also have an error

23.08 00:51:57 [Server] ERROR Plugin CompatNoCheatPlus v6.6.5-RC-sMD5NET-b90 has failed to register events for class me.asofold.bpl.cncp.hooks.mcmmo.HookmcMMO because com/gmail/nossr50/events/fake/FakeEntityDamageByEntityEvent does not exist.

then it disables, yet fails to disable

Disabling mcMMO v1.5.09-SNAPSHOT
23.08 00:51:44 [Server] ERROR Error occurred while disabling mcMMO v1.5.09-SNAPSHOT (Is it up to date?)

Note it said in console this was indeed the correct version

I will provide anything you need along with the whole console list on discord at Clitus#6205
SOMEONE HELP

**Comment by Glitchfinder** [comment]
mcMMO 1.5.09 is not backwards compatible to Spigot 1.8 builds. If you want to use mcMMO on a 1.8 server, the most recent build prior to breaking compatibility should be [this one](https://www.t00thpick1.net/mcMMO/mcMMO_1_8.jar)

**Comment by MyJumpsuit** [comment]
I owe you my life good sir

**Comment by MyJumpsuit** [comment]
it worked
