### ISSUE TITLE
1.13 Chimera Wings Cannot Be Crafted

### ISSUE THREAD

**Issue by L3Technosmith** [mcMMO-Dev/mcMMO#3554]
In 1.13, I am not able to craft Chimera Wings.  In a different server that is 1.12, I am able to craft them.

**Steps To Reproduce**:
1. Using default configs, give yourself 64 feathers.
2. In a crafting table put feathers into 5 piles. (I tried lots of variations)

**Expected Results**: I would see a Chimera Wing in the crafting output.
**Actual Results**: Cannot craft the wing.

Notes: 
N1. I cannot seem to make Flux Pickaxes either.  Interestingly, Smelting the Iron Pickaxe results in an Iron Nugget for me.
N2. I created a test plugin that simple added a simple SharedRecipe and a simple ShapelessRecipe. Those did not work either, so this might be a Spigot problem or Minecraft problem.  I was using these spigots:
This server is running CraftBukkit version git-Spigot-2b0e71c-4a24108 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
This server is running CraftBukkit version git-Spigot-fe3ab0d-3418f8d (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
N3. mcMMO version
[mcMMO] Running version 1.6.0-SNAPSHOT
and I ran a custom built version from the latest code as well.

**Comment by L3Technosmith** [comment]
Ok, I think I am onto something here.
I noticed that mcMMO loads the custom recipes during onEnable...but that happens BEFORE Minecraft loads its recipes. I moved mcMMO's loading of custom recipes (Chimera Wing and Flux Pickaxes) to be AFTER Minecraft loads its recipes and that fixes this issue. I did this by hacking the loading into a command which I ran after logging into the game...which is a horrible hack, but it helps gather info.

I dont know the proper place to put the custom loading of recipes...but I hope this helps someone else know how to fix this issue.

**Comment by just1689** [comment]
Could this be a way in which MCMMO needs to change? Is there a lack of a slot in the life-cycle for this sort of change?

**Comment by L3Technosmith** [comment]
I do not know the life-cycle...As a hack you could have a a part of the player login that only runs once per server start.

**Comment by just1689** [comment]
Thanks for looking into this!

I believe the mod is currently being caught up for 1.13.1. May once the code is there we can check this again on a 1.13.1 server + 1.13.1 MCMMO and see if it persists. It is my understanding that Minecraft 1.13 had lots of bugs. Perhaps they stuffed up the lifecycle here. We'll have more info soon

**Comment by t00thpick1** [comment]
Should be resolved, I wait a tick before registering recipes now.
