### ISSUE TITLE
Error enabling mcMMO on 1.12.2

### ISSUE THREAD

**Issue by LazyDkk** [mcMMO-Dev/mcMMO#3556]
So I've been trying to use mcMMO on my 1.12.2 server. I tried to run both mcMMO 1.5.08 and 1.5.10 but none of them worked.

Here's the error:
https://pastebin.com/4ggTXdGw

I'm not sure what's causing this error but I hope someone can help me. Thanks.

**Comment by Glitchfinder** [comment]
It looks like you have an invalid config. You probably tried 1.5.10 first, then didn't clear the configuration files before trying 1.5.08. Delete the entire mcMMO folder (back up what you want to keep), add in [this build right here](https://popicraft.net/jenkins/job/mcMMO/21/), and let it generate new config files from scratch. After that, copy in any settings you wanted to keep from your backups. Just be aware that the config files you currently have are using 1.13 material names, so block and item names may not be the same between the two.

**Comment by LazyDkk** [comment]
Okay so I did what you told me to. I deleted the folder and I tried both files under the link you gave me but they just give me a new error:
https://pastebin.com/D6GrvV9U

I tried using both mcMMO.jar and original-mcMMO.jar and both times I deleted the folder before trying to run but they both gave errors and the same error.

**Comment by Glitchfinder** [comment]
Everything but the last line there is a warning, which shouldn't prevent it from starting up. The last line in that error seems to be indicating that mcMMO can't create or read new config files. Is the config folder there, and if so, does experience.yml exist in that folder?

**Comment by LazyDkk** [comment]
The config folder is there but the experience.yml doesn't exist.

**Comment by Glitchfinder** [comment]
All right then. [This](https://raw.githubusercontent.com/mcMMO-Dev/mcMMO/aee60f2c098238858b0f40b6d06bc4219a6b42d4/src/main/resources/experience.yml) is a copy of the experience.yml file you need. Just save it to that directory and try to boot up again.

**Comment by LazyDkk** [comment]
It's still giving an error, but not the "cannot read file" error.
https://pastebin.com/8pc1pCmw

**Comment by nossr50** [comment]
At the moment I don't plan on offering support for this version of mcMMO

**Comment by nossr50** [comment]
If you still have this problem, you can likely solve it by deleting the .yml files in /plugins/mcMMO
