### ISSUE TITLE
auto replace crops with herbalisme 

### ISSUE THREAD

**Issue by thunderlight411** [mcMMO-Dev/mcMMO#3559]
With herbalisme above level 1000 there are normaly regulare replace mends of crops.
But now noting happens after harvesting a field of 50x50 with wheat.

**Comment by Sikatsu** [comment]
This is broken on 1.13+

**Comment by t00thpick1** [comment]
Looking into this today, thankyou for the report.

**Comment by Momshroom** [comment]
It's not broken.  You just need to give the permission-- it's no longer default.

**Comment by Momshroom** [comment]
https://github.com/mcMMO-Dev/mcMMO/issues/3566
The perm you need is: mcmmo.ability.herbalism.greenthumb.*
many thanks to lp's verbose mode for letting me find it...

**Comment by t00thpick1** [comment]
Fixed with https://github.com/mcMMO-Dev/mcMMO/commit/e2edbaad34a4bf969024ed5ea87139b057dc2824
