### ISSUE TITLE
update to 1.13.1 please

### ISSUE THREAD

**Issue by ecodiseniosweb** [mcMMO-Dev/mcMMO#3560]
can you update the plugin to 1.13.1 please?

**Comment by Glitchfinder** [comment]
To clarify why @t00thpick1 immediately closed this issue: It's in progress. If you would like to test the in progress builds, you can find them [here](https://popicraft.net/jenkins/job/mcMMO/). Just be aware that the 1.13 update changed a *lot* of things, and as a result there are a lot of bugs being sifted through across the board for the whole plugin.
