### ISSUE TITLE
Green Terra not working on Stone Brick, mcMMO 1.6.0-SNAPSHOT on 1.13

### ISSUE THREAD

**Issue by rtbentley** [mcMMO-Dev/mcMMO#3561]
We noticed the Green Terra capability is not working on stone brick with mcMMO 1.6.0-SNAPSHOT running on Spigot 1.13-R0.1-SNAPSHOT.  Green Terra works fine on dirt and cobblestone.

We genuinely enjoy mcMMO and greatly appreciate all the work on this.  We were really excited when we saw it working on the Spigot 1.13 snapshot, and we're thoroughly enjoying it.  We realize we're pushing the limits with our current configuration.  Since we noticed, though, we thought we'd report it.

Thank you again.

**Comment by t00thpick1** [comment]
What permissions have you granted your users in regards to green terra?  THe permission node has changed for Stone brick in particular because the node is based on material name, and the material changed.

**Comment by Sikatsu** [comment]
Whats the right permission as of 1.13?

**Comment by t00thpick1** [comment]
fixed by https://github.com/mcMMO-Dev/mcMMO/commit/e2edbaad34a4bf969024ed5ea87139b057dc2824
