### ISSUE TITLE
Green Thumb It doesn't work.

### ISSUE THREAD

**Issue by Ahkara** [mcMMO-Dev/mcMMO#3566]
Herbalism to Green Thumb doesn't work.

Server Settings 1.13 ~ 1.13.1

Is there anything I should check?

**Comment by Momshroom** [comment]
Try giving the permission 
mcmmo.ability.herbalism.greenthumb.*
It doesn't appear to be given by default and it fixed my issues with green terra not causing replant.

**Comment by Ahkara** [comment]
Thank you very much!!!!

It has been settled~~~

**Comment by t00thpick1** [comment]
Fixed by https://github.com/mcMMO-Dev/mcMMO/commit/e2edbaad34a4bf969024ed5ea87139b057dc2824
