### ISSUE TITLE
Option to rebind the super ability?

### ISSUE THREAD

**Issue by Hund** [mcMMO-Dev/mcMMO#3568]
When you have something in your left hand and want to place it and you run out of whatever it is, you activate the super ability. If you want to remove the bark of a tree you activate the super ability, and so on.. It get pretty annoying after a while. :)

Is it possible to change the keybinding for it? And if not, would it be possible to add the functionality? It would be nice if you could only activate it with `Ctrl` and the right mouse button.

**Comment by t00thpick1** [comment]
You can require the shift key, but unfortunately there is no other way to do it due to the way mc works.

**Comment by Hund** [comment]
Okay, thanks! :)
