### ISSUE TITLE
1.13.1 - stripping logs activates tree feller

### ISSUE THREAD

**Issue by ghost** [mcMMO-Dev/mcMMO#3571]
Right clicking a log to strip it of it's bark activates tree feller. Using build #43 from https://popicraft.net/jenkins/job/mcMMO/changes with Paper for 1.13.1 (Aikar's beta async chunk gen version)

**Comment by Romaq** [comment]
Spigot. Yup, it's a "thing". I'm not sure there's any way to fix that without rebinding. On our server we have to use "sneak" to use special actions. At the LEAST if we are TRYING to strip a log, if we don't sneak, we don't get Tree Feller. What may be useful is something like, "I see you are sneaking. You must want Tree Feller! Well, I'll do that and not strip the bark off for you." I'm not sure there are many options for resolving this one. :(

**Comment by Duqino** [comment]
We have the same problem. Strip bark from a tree and breaks only the block you hit.

**Comment by madscientist032** [comment]
My server has the same issue - strip the bark from the tree and it activates Treefeller. Additionally, treefeller does not break the whole tree if you chop the stripped-log - it only destroys only the non-stripped-logs.

**Comment by nossr50** [comment]
I've fixed the issue regarding tree feller and stripped wood preventing it from going off
I'm not sure what to do about the other thing, activating the weapon when you strip wood, I could prevent that from happening but I think that might do more harm than good.

**Comment by Quavelen** [comment]
Stripping a log activating an axe has been resolved, so now all facets of this issue are fixed.
