### ISSUE TITLE
Please add the new wood types to woodcutting xp

### ISSUE THREAD

**Issue by DovahKaal1** [mcMMO-Dev/mcMMO#3574]
I really want the new wood types in 1.13 to be added to the woodcutting experience. I've tried doing this myself and it does not work. I noticed there was only the stripped wood types but not the "wood" types which are as follows... 

oak_wood
spruce_wood
jungle_wood
dark_oak_wood
acacia_wood
birch_wood

**Comment by Glitchfinder** [comment]
Those are not part of the default config, as they do not naturally generate. If you want to add them yourself, add them below [this header](https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/experience.yml#L142) in the experience configuration. They should work exactly as you quoted them.

**Comment by DovahKaal1** [comment]
I did this already. Is there an error in this, because it does not work.

    Woodcutting:
        Oak_Log: 70
        Spruce_Log: 80
        Birch_Log: 90
        Jungle_Log: 100
        Acacia_Log: 90
        Dark_Oak_Log: 90
        Stripped_Oak_Log: 70
        Stripped_Spruce_Log: 80
        Stripped_Birch_Log: 90
        Stripped_Jungle_Log: 100
        Stripped_Acacia_Log: 90
        Stripped_Dark_Oak_Log: 90
        Stripped_Oak_Wood: 70
        Stripped_Spruce_Wood: 80
        Stripped_Birch_Wood: 90
        Stripped_Jungle_Wood: 100
        Stripped_Acacia_Wood: 90
        Stripped_Dark_Oak_Wood: 90
        Huge_Mushroom_1: 70
        Huge_Mushroom_2: 70
        Oak_Wood: 70
        Spruce_Wood: 80
        Birch_Wood: 90
        jungle_wood: 100
        Acacia_Wood: 90
        Dark_Oak_Wood: 90
        Brown_Mushroom_Block: 70
        Red_Mushroom_Block: 70
        Mushroom_Stem: 70

**Comment by Glitchfinder** [comment]
There doesn't appear to be. The experience config reads those and compares them against bukkit Materials, and those should match. Just to be sure, there isn't an error on startup from misreading the config, is there?

**Comment by DovahKaal1** [comment]
No. Clean startup.

**Comment by Glitchfinder** [comment]
And how are you testing it? As noted, the blocks do not generate naturally. If I remember correctly, the block tracking we use doesn't care what game mode you're in when you place the block, so it would need to be placed either via a plugin like worldedit (replacing blocks that were not placed by hand), or the block tracking files need to be removed after you place them.

**Comment by DovahKaal1** [comment]
I have the plugin "EpicWorldGenerator" which uses those blocks to generate trees. However, I've also tested it by placing them down in a normal vanilla world and also placing them with world edit. XP is not given in any scenario.

**Comment by Glitchfinder** [comment]
All right. I just confirmed on my end that simply adding them to the config file should work, assuming the blocks aren't tracked as player-placed. So, running down other potential sources of the issue:

- Do you have access to the Woodcutting skill?
- Do you currently earn experience when using the skill on a tree?
- What game mode are you currently in?
- Assuming the answers to the above questions are yes, yes, and survival, can you copy your experience config into a response, while putting a set of three ` symbols right before and after to preserve formatting and spacing?

**Comment by DovahKaal1** [comment]
Here is the experience.yml [https://pastebin.com/1GjQhEDx] and here's the config.yml for good measure. [https://pastebin.com/E8cw8Apr]

**Comment by DovahKaal1** [comment]
Update: I tried my config on my test server and it works. So it's obviously some plugin messing with it so I'll update when I find out which one it is.

**Comment by DovahKaal1** [comment]
Update 2: My main server ended up crashing and restarting and the problem is fixed. The old saying turn it off and then back on must be true.
