### ISSUE TITLE
MCMMO Treasures Error

### ISSUE THREAD

**Issue by MemeCaptain** [mcMMO-Dev/mcMMO#3575]
First off, amazing plugin. Been using it for years and is still to this day my favorite of all time. Great work keeping it updated!

The problem: It seems that with excavation treasures (and what appears to be fishing as well), treasures stop dropping at a certain level. I have my server set up to cap at lvl 100 for each skill, and unlock new treasures at every 10 levels. The treasures that appear at lvl 0 for excavation show up just fine, and have been tested for multiple drop chances. But the lvl 10 and above drops, even if set to a 90% drop chance, won't drop. Here's a screenshot of the YML file:
![mcmmo error](https://user-images.githubusercontent.com/43398073/45731574-3c928280-bba6-11e8-9ebe-7eb3d755381d.png)
Everything highlighted is what doesn't drop. Are item names changed? Because most of them I ripped right out of the original file.

Thanks! If I can be of any more help or if you have any questions, let me know.

**Comment by nossr50** [comment]
This could indicate a serious problem with our code, I'll take a look
As it happens I refactored some code related to our RNG mechanics recently

**Comment by MemeCaptain** [comment]
Oh my god I didn’t expect to ever hear back from anyone. I decided to pay
for MCMMO to support the devs but also ran into some problems. A lot of
items arent registered to be drops and are either corrupting the file or
not showing up when at 100% chance. Also, grass shades and grass in general
aren’t dropping at all. Let me know if I can help at all or give specifics.

**Comment by nossr50** [comment]
I'll look into those as well.

I don't sell mcMMO currently, if you paid for mcMMO recently you are paying for the version t00thpick1 is offering, he used to be on the team until recently. As of this moment the mcMMO team offers no paid version (but we plan to in the future).

**Comment by nossr50** [comment]
Sorry I'm not going to comment on that.
I'll take a look at this bug before the next release, it sounds quite serious.

**Comment by MemeCaptain** [comment]
Okay sounds good. It’s working the same way on both toothpick’s version and
yours. Let me know if you need any other info.
By the way, if your version is updated to 1.13 and your team is more active
with updates, I might switch over to your version despite paying for the
other. Is there a place to download?

**Comment by nossr50** [comment]
https://www.spigotmc.org/resources/official-mcmmo.63489/

**Comment by nossr50** [comment]
Treasures are being rewritten in 2.2, I also think this is not a valid bug.
