### ISSUE TITLE
[1.13.1] Disabling Tree Feller

### ISSUE THREAD

**Issue by NolanMC** [mcMMO-Dev/mcMMO#3586]
This might be multiple issues, but I will report here to condense. 

1. Negating the permission: mcmmo.ability.woodcutting.treefeller does nothing. This is the permission that supposedly controls Tree Feller. When applying this to a group or player, they are still able to use Tree Feller with no issues. This has been happening for multiple versions. 

2. The Max_Seconds value in config for Tree Feller seems to be ignored. If a value is set here for Tree Feller, it will still simply set the max length of tree feller based on whatever the Woodcutting level of a player is. I tried messing with this value after negating the permission did nothing. 

Server version: Paper 1.13.1 build 295
MCMMO config.yml: https://gist.github.com/NolanMC/e71b11c8cebcab956fa1af566b4a861f
MCMMO Version: 1.6..0-SNAPSHOT build 47 from https://popicraft.net/jenkins/job/mcMMO/changes
I know the issues section on here is a little inactive, but I hope to hear back on these issues. Thank you.

**Comment by t00thpick1** [comment]
Ok, so this is the best place to contact so thanks for posting here rather than private messaging me somewhere.    As for Max_Seconds,  it looks like we only support whole numbers for that right now,  I can look into changing that but not at this moment.  I am however having trouble finding your issue with the Tree Feller permissions at a cursory glance, I'll try to get a more in depth look this weekend.

**Comment by NolanMC** [comment]
@t00thpick1 Thank you for responding! 

I discovered that it supports whole numbers on my own and forgot to edit the issue. I was able to limit it to a 1 second ability max, and so I believe the Max_Seconds value does work as intended. Supporting anything other than whole numbers wouldn't be needed for me if I was simply able to turn off Tree Feller. 

If there is nothing found wrong with the permission for Tree Feller, would it be possible to simply add a config option for the ability? Currently you can only turn them all on or all off. I have currently turned all of them off for the sole sake of disabling Tree Feller.

**Comment by nossr50** [comment]
I'll take a look at the perms code and see what's going on
Regarding individual settings for each super-ability, that sounds like a smart idea

**Comment by Quavelen** [comment]
So, I'm going to go ahead and close this for now as I'm fairly certain @nossr50 has resolved this in the overhaul.
If you still use mcMMO classic (mcMMO versions `1.6.x` and older) and this issue persists, please open a new issue on their repository: https://github.com/mcMMO-Dev/mcMMO-Classic
