### ISSUE TITLE
mcmmo and enchanting

### ISSUE THREAD

**Issue by hatjim** [mcMMO-Dev/mcMMO#3587]
so i was just wondering why there isnt an enchanting thing with mcmmo, it kinda makes using mcmmo kinda unbalanced in servers that have jobs that are affected by mcmmo, while enchanting jobs dont get anything, so please explain why there isnt a mcmmo boost of some kind

**Comment by Glitchfinder** [comment]
Well, when Enchanting first came out, it was handled almost entirely clientside, meaning we couldn't touch it. I'm fairly certain that has since changed, but the number of people actively working on mcMMO has dwindled down to 0-1 in the interim.

**Comment by hatjim** [comment]
damn, thanks for the info

**Comment by nossr50** [comment]
@hatjim what would you expect mcMMO to do in regards to enchanting?

**Comment by Quavelen** [comment]
Closed due to lack of response from @hatjim.
Can be re-opened if they return, and respond.
