### ISSUE TITLE
[1.13.1] mcscoreboard is not there

### ISSUE THREAD

**Issue by Baktus79** [mcMMO-Dev/mcMMO#3588]
Hi

I cant seem to be able to use /mcscoreboard at all. It doesnt show.

![2018-09-29_12 40 20](https://user-images.githubusercontent.com/19745447/46244817-009cc000-c3e5-11e8-9db5-7f3073968fcc.png)

**Comment by Baktus79** [comment]
Still nothing. It wont show

**Comment by Tomographix** [comment]
Have same bug if that helps :) Also on 1.13.1 but has been an issue for quite a while.

**Comment by DiamondDagger590** [comment]
Unsure as to why this is happening but there is a 1.13+ replacement for mcmmo coming out soon and scoreboards work perfectly fine on there.

**Comment by nossr50** [comment]
@Baktus79 Let me know if you still have this problem on 1.13.2 w/ 2.0.0 mcMMO

**Comment by Quavelen** [comment]
Closed due to lack of response from @Baktus79.
Can be re-opened if they return, and respond.
