### ISSUE TITLE
[1.13] New wood types (not logs) don't work (no xp/no tree feller)

### ISSUE THREAD

**Issue by MadByteDE** [mcMMO-Dev/mcMMO#3589]
[Wood type wiki page](https://minecraft.gamepedia.com/Wood)

Still need to be implemented.

**Comment by Glitchfinder** [comment]
If you're referring to the one with bark on all sides, see #3574. If you're referring to stripped logs, there is an issue with Tree Feller's block check that has yet to be addressed.
