### ISSUE TITLE
1.13.1 Error Loading McMMO

### ISSUE THREAD

**Issue by Gnoarn** [mcMMO-Dev/mcMMO#3594]
Loading McMMO fail.

https://pastebin.com/SMpua7ms

**Comment by QuiquePineyro** [comment]
You should put this log in pastebin.com or hastebin.com

**Comment by Gnoarn** [comment]
Made the appropriate Changes.

**Comment by Glitchfinder** [comment]
You have an old config. If you made any changes to them that you want to keep, back them up and then remove them from the mcMMO directory. It will generate new ones with materials compatible with 1.13.

**Comment by Gnoarn** [comment]
Thank you. did not think of that one.
