### ISSUE TITLE
Cannot redeem Credits on Unarmed?

### ISSUE THREAD

**Issue by MamaBeau** [mcMMO-Dev/mcMMO#3595]
Hello, we are running a 1.13.1 server and we have encounter an issue with McMMO. 
We cannot redeem credits to the unarmed skill. 

There are no errors that pop up, nothing in console, we also tried it as OPs. 
Wondering if this is meant to happen or is an issue.
Any insight welcomed!

Ver: 1.6.0-SnapShot

**Comment by MamaBeau** [comment]
You can give players points or “credits” to boost their mcmmo levels on each ability

**Comment by t00thpick1** [comment]
Thats not a feature of this plugin
