### ISSUE TITLE
Bug: update delay bug

### ISSUE THREAD

**Issue by madtomic** [mcMMO-Dev/mcMMO#3596]
Update_Check: false

[21:45:51 INFO]: [mcMMO] Enabling mcMMO v1.5.09-SNAPSHOT
[21:46:03 INFO]: [Vault] Enabling Vault v1.7.1-b91

It is still checking for update even with the update check set to false. Can you fix this bug. Thanks!

**Comment by nossr50** [comment]
What makes you think its checking for an update?

**Comment by Quavelen** [comment]
Closed due to lack of response from @hatjim.
Can be re-opened if they return, and respond.
