### ISSUE TITLE
Not saving.

### ISSUE THREAD

**Issue by Gojan1** [mcMMO-Dev/mcMMO#3602]
Whenever a player logs out of my server it says : 
18.10 09:27:23 [Server] INFO INFO]: [mcMMO] User found, removing...
18.10 09:27:22 [Disconnect] User INFO]: Wrathlucifer has disconnected, reason: Disconnected

server version : 1.12.2
mcmmo ver : https://popicraft.net/jenkins/job/mcMMO/21/

more version info
[10:29:49] [Client thread/INFO]: [CHAT] This server is running Paper version git-Paper-1562 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[10:29:49] [Client thread/INFO]: [CHAT] Previous version: git-Paper-1574 (MC: 1.12.2)

**Comment by Gojan1** [comment]
-database added

i thought by adding mysql database to it, it would be better..
But now whenever a player relogs. it says player profile is not loaded yet.

even tho i have setup the same database settings as i use with cmi which does connect to the database.

---------settings--------
MySQL:
    Enabled: true
    Database:
        User_Name: mc_5212
        User_Password: removedforsecurityreasons
        Name: mc_5212
        TablePrefix: newmcmmo_
        # This setting is the max simultaneous mysql connections allowed at a time, needs to be
        # high enough to support multiple player logins in quick succession
        MaxConnections:
            Misc: 30
            Load: 30
            Save: 30
        # This setting is the max size of the pool of cached connections that we hold available
        # at any given time
        MaxPoolSize:
            Misc: 10
            Load: 20
            Save: 20
    Server:
        Port: 3306
        Address: db.stickypiston.co

**Comment by nossr50** [comment]
Are you only using mcMMO when this issue happens?
Does it still happen with 2.0.0?

**Comment by Quavelen** [comment]
Closed due to lack of response from @Gojan1.
Can be re-opened if they return, and respond.
