### ISSUE TITLE
/mcrank MYSQL query failure

### ISSUE THREAD

**Issue by BiGUNMAN** [mcMMO-Dev/mcMMO#3611]
When a player types /mcrank in-game, the following error is output to the console: https://i.imgur.com/NtwoLdW.png

This is what the player is returned in-game: https://i.imgur.com/7BGT3jk.png

**Comment by BiGUNMAN** [comment]
@t00thpick1 So it's been quite a while... But here is the schema dump: https://drive.google.com/file/d/1W90J66onCU1AyrSVHrsC74oR5ta0qpgb/view?usp=sharing

**Comment by nossr50** [comment]
As t00thpick1 mentioned, something is likely wrong with your DB, I'll have a look at your schema when I get the chance to confirm

**Comment by Draycia** [comment]
Closing due to age and inactivity.
Please reopen and comment if you're still having this issue.
