### ISSUE TITLE
Perk permission nodes not working. ( XP )

### ISSUE THREAD

**Issue by RustyDagger** [mcMMO-Dev/mcMMO#3618]
As the title says applying the permission nodes from the wiki to any player or group has no effect
Tested on paperspigot 1.13.2 with mcmmo 1.6.0 snapshot.

Video below shows all.
https://www.youtube.com/watch?v=7649m2FyIR4&feature=youtu.be

**Comment by nossr50** [comment]
We don't control the wiki, can you tell me in specific which permission nodes you are attempting to use? You may be entering invalid permission nodes.

**Comment by RustyDagger** [comment]
Its in the video but i guess i can type it here.
mcmmo.perks.xp.50percentboost

I also turned on the debug mode for luckperms and mcmmo is not doing any check for any xpboost permission node when blocks are broken.

**Comment by Quavelen** [comment]
This is the overhaul repository, please use https://github.com/mcMMO-Dev/mcMMO-Classic for issues pertaining to mcMMO versions `1.6.x` and older.
