### ISSUE TITLE
[mcMMO] Task #646 for mcMMO v1.6.0-SNAPSHOT generated an exception

### ISSUE THREAD

**Issue by andrewkm** [mcMMO-Dev/mcMMO#3620]
During spam /mctop test:
https://pastebin.com/raw/EYxm6hKr

Reference: https://github.com/mcMMO-Dev/mcMMO/issues/3471

**Comment by nossr50** [comment]
I know it's been a while but does this issue still occur? Trying to figure out which issues are current.

**Comment by andrewkm** [comment]
Yes, obviously they are if they are open...
Did you not get a brief run through from @t00thpick1 on the current state  of things or did you just toss him and take over...?

Really on the edge here as to why I should be using this repo as opposed to t00thpicks which has been trusted for years.

**Comment by andrewkm** [comment]
This was an occurence we caught during an /mctop spam test to check for performance.
Please read this closed ticket/project for reference:
https://github.com/mcMMO-Dev/mcMMO/issues/3471

**Comment by nossr50** [comment]
It's definitely what I would consider an edge case bug, but its a bug nonetheless so I'll see what I can do

**Comment by andrewkm** [comment]
mctop is fixed now.
