### ISSUE TITLE
/mcrank broken & cooldown message broken.

### ISSUE THREAD

**Issue by andrewkm** [mcMMO-Dev/mcMMO#3621]
Using /mcrank does nothing:
https://i.imgur.com/UJJSJgA.gifv

Cooldown message is also broken for /mcrank.
The /mcrank command however does obey cooldown.
Once cooldown runs out, which you can see via /mctop, /mcrank command goes through. (However once again does nothing).

**Comment by nossr50** [comment]
can you confirm if this bug is still happening for you?
and does this bug happen when your only plugin is mcMMO?

Try it with version 2.0.0 and report back

**Comment by andrewkm** [comment]
Discord me dude #andrewkm001
Have some questions regarding your take over...?

**Comment by nossr50** [comment]
my discord is nossr50#1337 if you want to talk

**Comment by nossr50** [comment]
I thought the results would be cache'd so I'm not sure why they are on a cooldown, I can go look into it though

**Comment by andrewkm** [comment]
They are on cooldown as per the config as there have been severe lag issues with users spamming mctop and mcrank in the past.

Detailed issues regarding this can be found here:
https://github.com/mcMMO-Dev/mcMMO/issues/3471

It was quite the server killer.
The cooldowns are a must as a preventative measure.

**Comment by nossr50** [comment]
I'm surprised the results are not cache'd (and updated every x minutes) which would prevent the need for a cooldown

**Comment by andrewkm** [comment]
Fixed.
