### ISSUE TITLE
Jenkins down

### ISSUE THREAD

**Issue by SXRWahrheit** [mcMMO-Dev/mcMMO#3630]
Just an FYI. I know you don't host it.

**Comment by t00thpick1** [comment]
Any volunteers?

**Comment by SXRWahrheit** [comment]
Hey, @mcmonkey4eva... think Citizens can spare a Jenkins slot?

**Comment by mcmonkey4eva** [comment]
Citizens jenkins has approximately negative disk space left on it >.> (it's a broken into hell VPS with 30GB max disk space given by CreeperHost as a sponsorship)
mcMMO has no relation to Citizens either way.
Being a fairly popular Spigot plugin, you might be able to talk your way onto ci.md-5.net

**Comment by t00thpick1** [comment]
@andrewkm Do you still have the pull to make something like that happen?

**Comment by andrewkm** [comment]
@SXRWahrheit here ya go:
https://ci.ecocitycraft.com/job/McMMO/

**Comment by SXRWahrheit** [comment]
Nice one, cheers @andrewkm!
