### ISSUE TITLE
 mcmmo incompatibility with infernal mobs what to do?

### ISSUE THREAD

**Issue by comonier** [mcMMO-Dev/mcMMO#3632]
mcmmo version: v1.6.0-SNAPSHOT
paper version: Paper version git-Paper-411 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
worldguard version: worldguard-legacy-7.0.0-1761
worldedit version: worldedit-bukkit-7.0.0-3954
console spam error when uplevel mcmmo skill hunter: https://codeshare.io/5NJ4M8

**Comment by comonier** [comment]
more errors: https://codeshare.io/2Bv4Lb

**Comment by comonier** [comment]
FOUND THE PROBLEM!!!!
Infernal Mobs 5.6
https://www.spigotmc.org/resources/infernal-mobs.2156/updates
Without that plugin Mcmmo works . =/

**Comment by comonier** [comment]
https://github.com/mcMMO-Devcan you takl with 
https://github.com/NyaaCat to try solve the problem ?

**Comment by nossr50** [comment]
It seems the issue was a plugin incompatibility and solved by the user.
