### ISSUE TITLE
1.12.2 Error in console

### ISSUE THREAD

**Issue by PengBread** [mcMMO-Dev/mcMMO#3634]
I'm getting this error spamming in my console

https://pastebin.com/C2RVdmjh

Version mcMMO v1.5.10

**Comment by nossr50** [comment]
I'll consider this a request for legacy support, at the moment I don't plan to offer support for 1.12.2 but that could change in the future

**Comment by Quavelen** [comment]
This is the overhaul repository, please use https://github.com/mcMMO-Dev/mcMMO-Classic for issues pertaining to mcMMO versions `1.6.x` and older.
