### ISSUE TITLE
Mining Double Drop Bug

### ISSUE THREAD

**Issue by Roy416** [mcMMO-Dev/mcMMO#3638]
There's a huge bug with mining. Once you get to level 1000, and double drops become 100%, when you mine something, it doesn't drop normally and is a little crazy on how it drops. So when a ore is within a wall and is mined, it seems like sometimes the ores go within the wall, and sometimes elevate? Meaning the players don't get their ores. I tried isolating the plugin with other plugins that I thought may have caused it, but it seems to be 100% Mcmmo. I tried it on the server version 1.13.2 and paper spigot 405. Our server uses paper spigot. 

Here is a video: https://drive.google.com/file/d/1bW8LrQt-oiJxDEMUt0FnBXm5dooaUiSE/view

**Comment by Roy416** [comment]
I dont know how to code ;-;

**Comment by Quavelen** [comment]
Fixed in commit 54d8566.

If you still have this issue, and continue to use mcMMO Classic (versions `1.6.x` and older), then please use https://github.com/mcMMO-Dev/mcMMO-Classic for issues pertaining to that. This is the mcMMO Overhaul repository.
