### ISSUE TITLE
Drops from mining end up on surface

### ISSUE THREAD

**Issue by Ironic8b498** [mcMMO-Dev/mcMMO#3641]
while mining a 2x1 tunnel the drops spawn on surface. I have noticed it when running mcMMO-1.6.0-Snapshot I tried mcMMO-#51 and #51 and still the drops spawn on surface.

**Comment by LogGits** [comment]
Also having this issue: I tested spawning an item with the two different methods.
```java
    @EventHandler
    private void onBreak(BlockBreakEvent event) {
            event.getBlock()
                    .getWorld()
                    .dropItem(
                            event.getBlock().getLocation().add(0.5, 0, 0.5),
                            new ItemStack(Material.ROTTEN_FLESH));
            event.getBlock()
                    .getWorld()
                    .dropItemNaturally(
                            event.getBlock().getLocation().add(0.5, 0, 0.5),
                            new ItemStack(Material.POPPY));
    }
```
I noticed the Poppy would get thrown up blocks instead of spawning at the block it was broken at. Whereas the RottenFlesh spawned as expected. @Ironic8b498 can you test this without mcmmo and see if this type of thing still happens? Also are you using Paper or Spigot and which version?

**Comment by Ironic8b498** [comment]
On my test server I added plugins one by one till the issue happened again, WG and WE, then I add EssX, then I added mcMMO,  I can try with just mcMMO, but I feel thats the problem since I don't have this issue on my Vanilla world which has WG, WE and EssX

**Comment by LogGits** [comment]
Can u try with mining level 0 and mining level 1000 and let me know if 1000 mining level causes more issues?

**Comment by Ironic8b498** [comment]
sorry took me so long, I just tested with a player starting at mining level 1 and they went up to 12 and no blocks spawned on the surface. All my testing before was with my player which has a mining level of 2396 and the perks stop at 1000

**Comment by LogGits** [comment]
Ok so this is related to #3638. I will make a change and PR it real quick.
