### ISSUE TITLE
No Enchantment Books From Fishing

### ISSUE THREAD

**Issue by Disorbs** [mcMMO-Dev/mcMMO#3643]
So some of my players are saying they only get Tools and Armor from fishing
which not sure why its doing it and wanted to see how to fix it?

`
   Fishing:
       Level_Cap: 1000

       Drops_Enabled: true

       Override_Vanilla_Treasures: true

       # Always catch fish, even when treasure is found
       Extra_Fish: true

       Lure_Modifier: 4.0`

Treasures.yml - https://pastebin.com/raw/6ERGnXBi

**Comment by Quavelen** [comment]
Enchanted books from fishing treasure are a planned feature in mcMMO version 2.2, for now what @AllianceJE said will be what you have to do.
