### ISSUE TITLE
[Error] There was an error while enabling mcMMO!

### ISSUE THREAD

**Issue by xMystc** [mcMMO-Dev/mcMMO#3646]
> The plugin works when using 1.6.0 on 1.13.2 but I recently downgraded the server due to Essentials not having a stable build for anything above 1.8. https://www.spigotmc.org/resources/mcmmo.2445/history < none of the previous download links work here.
So I attempted this Version https://dev.bukkit.org/projects/mcmmo 
^^^^ Not entirely sure if this is vital information but thought it was important to note. also full disclosure I did purchase the premium on Spigotmc

14.12 21:49:16 [Server] ERROR Error occurred while disabling mcMMO v1.5.00-b3547 (Is it up to date?)
14.12 21:48:16 [Server] INFO Disabling mcMMO v1.5.00-b3547
14.12 21:48:16 [Server] WARN at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
14.12 21:48:16 [Server] WARN at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458)
14.12 21:48:16 [Server] WARN at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:153)
14.12 21:48:16 [Server] WARN at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
14.12 21:48:16 [Server] WARN at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
14.12 21:48:16 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
14.12 21:48:16 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
14.12 21:48:16 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
14.12 21:48:16 [Server] WARN at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:173)
14.12 21:48:16 [Server] WARN at com.gmail.nossr50.metrics.MetricsManager.setup(MetricsManager.java:72)
14.12 21:48:16 [Server] WARN at java.io.InputStreamReader.<init>(Unknown Source)
14.12 21:48:16 [Server] WARN at java.io.Reader.<init>(Unknown Source)
14.12 21:48:16 [Server] WARN java.lang.NullPointerException
14.12 21:48:16 [Server] ERROR There was an error while enabling mcMMO!
14.12 21:48:15 [Server] INFO Enabling mcMMO v1.5.00-b3547
14.12 21:48:15 [Server] INFO Loading EssentialsProtect v2.13.1
14.12 21:48:15 [Server] INFO Loading EssentialsAntiBuild v2.13.1
14.12 21:48:15 [Server] INFO Loading EssentialsChat v2.13.1
14.12 21:48:15 [Server] INFO Loading EssentialsSpawn v2.13.1
14.12 21:48:15 [Server] INFO Loading Essentials v2.13.1
14.12 21:48:15 [Server] INFO Loading mcMMO v1.5.00-b3547
14.12 21:48:15 [Server] INFO Loading WorldEdit v6.1.9;caf0ad9
14.12 21:48:15 [Server] INFO Set PluginClassLoader as parallel capable
14.12 21:48:14 [Server] INFO Starting Minecraft server on 198.24.164.162:44650
14.12 21:48:14 [Server] INFO Generating keypair
14.12 21:48:14 [Server] INFO Using 4 threads for Netty based IO
14.12 21:48:14 [Server] INFO Server Ping Player Sample Count: 12
14.12 21:48:14 [Server] INFO Debug logging is disabled
14.12 21:48:14 [Server] INFO This server is running CraftBukkit version git-Spigot-1.7.9-R0.2-208-ge0f2e95 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
14.12 21:48:14 [Server] INFO Default game type: SURVIVAL
14.12 21:48:14 [Server] INFO Loading properties
14.12 21:48:14 [Server] INFO Starting minecraft server version 1.7.10
14.12 21:48:08 [Server] INFO *** Any bug reports not running the very latest versions of these softwares will be ignored ***
14.12 21:48:08 [Server] INFO Please report any such issues to http://www.spigotmc.org/, stating your client, server, and if applicable BungeeCord versions.
14.12 21:48:08 [Server] INFO *** It is imperative that backups be taken before running this build on your server! ***
14.12 21:48:08 [Server] INFO This Spigot build supports Minecraft clients both of versions 1.7.x and of 1.8.x.
14.12 21:48:08 [Server] INFO Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
14.12 21:48:08 [Multicraft] Loaded config for "Spigot (Bukkit Alternative)"
14.12 21:48:08 [Multicraft] Starting server!

**Comment by EHAndrew** [comment]
Why not use EssentialsX? It runs fine on 1.13.2

**Comment by xMystc** [comment]
because with the 19 hours of research I did not a single time did EssentialsX ever pop up through my Essentials 1.13 compatability search

**Comment by braddevans** [comment]
this appears to be an issue on 1.7.10
mcMMO version: v1.5.00-b3547 
```
14.12 21:48:14 [Server] INFO Starting minecraft server version 1.7.10
```

**Comment by electronicboy** [comment]
This issue no longer exists and hasn't done for a good while, nor is there much capacity for us to go back and start patching 5 year old versions of the software; fwiw, this can easily be fixed by yanking out the metrics from the plugin

**Comment by braddevans** [comment]
if he wanted to try it with 1.7.10 he should have used the latest release
https://github.com/mcMMO-Dev/mcMMO/releases/download/1.4.06-rerelease/mcMMO-1.7.10.jar
whitch is working
