### ISSUE TITLE
Salvage not giving correct amount of items

### ISSUE THREAD

**Issue by Ironic8b498** [mcMMO-Dev/mcMMO#3649]
I have noticed that when players with the skill level of 1000 or more in Salvage they only get 2 of the 5 items they should get in return for salvaging a helmet. Spigot 1.13.2 and build #56

    Salvage:
        # MaxPercentage: Maximum percentage of materials to be returned when Salvaging
        # MaxPercentageLevel: On this level, the Salvage percentage will be <MaxPercentage>
        MaxPercentage: 100.0
        MaxPercentageLevel: 1000

**Comment by mrfloris** [comment]
I actually have players who salvage a shovel and get 2 diamonds, instead of 1.

**Comment by Quavelen** [comment]
This has been fixed in the mcMMO overhaul, as such this issue is being closed.
If you use mcMMO classic (mcMMO versions `1.6.x` and older), and this issue still happens, please open an issue on their repository: https://github.com/mcMMO-Dev/mcMMO-Classic
