### ISSUE TITLE
Melee Weapon exp bug

### ISSUE THREAD

**Issue by ProfEnd** [mcMMO-Dev/mcMMO#3651]
I seem to be having issues on my private server in which while using axes and swords, after killing mobs we gain no exp. (on 1.13.2) Some mobs give xp, chicken, sheep, cow, pig. But it seems to be that almost every hostile mob gives no xp. Any help?

**Comment by Quavelen** [comment]
Closed due to lack of details from @ProfEnd.
If you would like to re-open this, please provide basic information such as mcMMO version, Minecraft version, Paper/Spigot version, etc.
