### ISSUE TITLE
Gold Ore does not double drop

### ISSUE THREAD

**Issue by Roy416** [mcMMO-Dev/mcMMO#3653]
Mcmmo Mining is 1000+, but gold ore does not double drop at all. mcmmo 1.6.0 dev version, paper spigot (470) 1.13.2

**Comment by nossr50** [comment]
Thanks for the report, I'll look into it.

**Comment by Roy416** [comment]
apparently the same thing occurs with Andesite/Diorite/Granite blocks

**Comment by basicmark** [comment]
We are seeing what could be the same issue.

Server info:
[04:00:26] [Server thread/INFO]: Starting minecraft server version 1.13.2
[04:00:26] [Server thread/INFO]: Loading properties
[04:00:26] [Server thread/INFO]: Default game type: SURVIVAL
[04:00:26] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-26a8d99-38e4c01 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

mcMMO: 1.6.0-SNAPSHOT

When breaking blocks with a minner level where there would be no double drops the itemstack drops as normal. When breaking blocks with a very high minner (and thus a high chance of double drop) it looks like there is no itemstack dropped. However, watching carefully you do see it for a second before it  seems to dissapear. We then went to the surface and saw the itemstack which looks like it handn't dropped.

Testing further if we remove a block above the one we want to break (and thus ensure there is an air gap above the block to break) then we clearly see the itemstack "jump" higher (into the air gap we've created) but this time it drops to the ground as expected.

My guess is mcMMO is spawning a new itemstack which is slightly higher then the orginal itemstack and the two itemstacks are being merged into the higher one which is then in a sold block and the itemstack is thus "elevated" through the solid blocks to the surface.

**Comment by Quavelen** [comment]
Closed for two reasons:
1. This was fixed in the mcMMO overhaul (2.1.xx). Use that if you want it to function, otherwise see reason 2.
2. This is the overhaul repository, please use https://github.com/mcMMO-Dev/mcMMO-Classic for issues pertaining to mcMMO versions `1.6.x` and older.
