### ISSUE TITLE
TreeFeller not working with custom trees

### ISSUE THREAD

**Issue by Zenya4** [mcMMO-Dev/mcMMO#3654]
TreeFeller does not work with custom trees supplied by external world generation plugins such as EpicWorldGenerator or OpenTerrainGenerator. Refer to https://gyazo.com/6f757d55eee5dbb2b5a7029d1ec01370 for more info.

McMMO 1.6.1 Snapshot
PaperSpigot 1.13.2

**Comment by Zenya4** [comment]
It used to work when my server was on MC 1.12

**Comment by nossr50** [comment]
I'll look into this

**Comment by OpalMoonstride** [comment]
I believe this is also my issue, although I think it's caused by the six-sided blocks, moreso than the custom trees. The ones grown by saplings tend to be 4-sided bark, while EWG does 6-sided bark for a lot of trees.

**Comment by OpalMoonstride** [comment]
Sure. It's a premium one, though. 
https://www.spigotmc.org/resources/epicworldgenerator-1-8-8-1-13-2-support-all-update-aquatic-features.8067/

**Comment by Zenya4** [comment]
@nossr50 as mentioned by Opal, it's a premium resource so I can't just share the jarfile like this on GitHub. If you cannot reproduce it or really need it for testing purposes, perhaps I can send it to you privately through Discord or something. You can't send it to anyone else, though.

Zenya4#0093 (send me a friend request if you have Discord)

**Comment by nossr50** [comment]
I'll contact the author and see if hes willing to give me a copy to make mcMMO more compatible

**Comment by Quavelen** [comment]
I believe this issue can be closed, due to @nossr50's reply on issue #3667.

>t00thpick1 pointed out that there is no thread safe way to read the blocks in Minecraft, and the solutions to make tree feller threaded without reading blocks from the main thread are costly, so its likely Tree Feller will remain on the main thread unless someone comes up with a really clever solution and lets me know.
