### ISSUE TITLE
Rework skills to be on a 1-100 scale

### ISSUE THREAD

**Issue by nossr50** [mcMMO-Dev/mcMMO#3656]
Skills will be rescaled to work on a 1-100 scale in the next update
The new system will be opt-in and old mcMMO installs will still use the 0-1000 system unless they run an admin command to convert

**Comment by andrewkm** [comment]
Please include a way for us to keep our 1000 level system.
Many of us have servers that have been running for nearly 8 years, and have our entire game modes revolve around the 1000 level system.

A change this massive is very extreme and there needs to be a config value/setting allowing some of us to remain on the old system. It’s simply impossible to force a change like this on established communities as it would destroy their setups and force them into forked mcmmo versions.

Hopefully this is done carefully, and is just a default / downsizing of the values in config.

**Comment by nossr50** [comment]
I have received a lot of feedback about this change

This is how I will approach it

1) Existing servers will remain on the old system ( 0-1000 ) unless the server runs a command to switch
2) New mcMMO installs with an empty database will use the new system ( 1-100 )
3) Both systems are functionally identical, but with the numbers differing between them by a factor of 10

**Comment by SXRWahrheit** [comment]
Players seem to enjoy the more frequent level-ups that a 1000-scale system affords. Out of curiosity, what's the motivation for the change?

**Comment by nossr50** [comment]
@SXRWahrheit I've written about that here in my roadmap for mcMMO
https://docs.google.com/document/d/1rCgBbKkldYd_OoQY1ls_nxn6Ly_NV9Adfpl7_BYBF6k/edit?usp=sharing

The change for the skill system will be opt-in for existing mcMMO installs

**Comment by nossr50** [comment]
Completed
