### ISSUE TITLE
Make Tree Feller Async

### ISSUE THREAD

**Issue by nossr50** [mcMMO-Dev/mcMMO#3667]
for some reason Tree Feller isn't async
I'll look into this soon

**Comment by mrfloris** [comment]
kinda the same; https://github.com/mcMMO-Dev/mcMMO/issues/3654

**Comment by nossr50** [comment]
So I'm late to close this but, @t00thpick1 pointed out that there is no thread safe way to read the blocks in Minecraft, and the solutions to make tree feller threaded without reading blocks from the main thread are costly, so its likely Tree Feller will remain on the main thread unless someone comes up with a really clever solution and lets me know.
