### ISSUE TITLE
Player death messages occasionally have hearts instead of mob names.

### ISSUE THREAD

**Issue by Numpty-Clodpole** [mcMMO-Dev/mcMMO#3672]
So, I see in #934 this issue was resolved, but it appears to be back in the 2.1.0 snapshots. Here's a gif I recorded of the issue:

![2019-01-01_03-09-40](https://user-images.githubusercontent.com/19168008/50570104-9c86f080-0d73-11e9-803f-83809b17dee2.gif)

It's pretty inconsistent, and will only occasionally show up. Other info if needed:

* Operating System: Linux (amd64) version 2.6.32-642.4.2.el6.x86_64
* Java Version: 1.8.0_101, Oracle Corporation
* Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
* JVM Flags: 4 total; -XX:MaxMetaspaceSize=256M -XX:+UseConcMarkSweepGC -Xmx6144M -Xms128M
* CraftBukkit version: git-Spigot-518206a-5be2ddc (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
* Plugins (22): CoreProtect, PlayerHeads, dynmap, LuckPerms, WorldEdit, VotingPlugin, Essentials, EssentialsProtect, Minecart_speedplus, EssentialsChat, EssentialsGeoIP, EssentialsAntiBuild, AutoAnnouncer, mcMMO, EnderSurfer, Whitelist, Votifier, EssentialsSpawn, ProtocolLib, Multiverse-Core, DiscordSRV, mcMMOAction
  * All plugins are up to date, as per their dev/jenkin builds.

**Comment by nossr50** [comment]
Hmm, do any of your mods modify death messages?

**Comment by mrfloris** [comment]
For what it's worth, I use DeathMessagePlus, which is pretty popular, it actually has a value to toggle "if hearts instead of entity name, toggle this to true (or false or whatever it is)'

**Comment by Quavelen** [comment]
> Hmm, do any of your mods modify death messages?

Nope, I listed the plugins that the server uses. None of them control, or create death messages.

**Comment by nossr50** [comment]
Alright I'll take a look and see what our code that puts hearts above mob heads is doing and see if its being naughty.

**Comment by Quavelen** [comment]
Well, for the time being I've just disabled the hearts display in mcmmo config. That removed it from death messages. Here's hoping it's resolved in a future version.

**Comment by nossr50** [comment]
I'll see if I can get around to working on this bug before 2.1.0 launches, quite busy with that atm

**Comment by hamcoremusic** [comment]
I am also having this issue and have no plugins that override the mob names or death messages.

**Comment by nossr50** [comment]
It's fixed boys.

**Comment by LoXR** [comment]
It isnt fixed for my server, how did you guys fix it?

**Comment by nossr50** [comment]
@LoXR if you patched mcMMO it only works on newly created mobs, so all old mobs will still have the bug.

**Comment by LoXR** [comment]
Aha I see!, I've noticed no hearts in the chat anymore!

**Comment by Quavelen** [comment]
Hmm... @nossr50, I guess I should post on here and let you know that this still occurs even with newly spawned mobs. Using the latest version on the Jenkins, of course. I'll open a new issue with updated info, if needed as the stuff I listed in the opening post is pretty inaccurate now.

**Comment by lizeidsness** [comment]
this is still happening on latest build with health bars on.  It's logged to file as well
![image](https://user-images.githubusercontent.com/25915485/80820524-07814b00-8ba5-11ea-9353-c1bc8d2a9dcf.png)

It's not every time.  Perhaps just while the health bars are displayed since that only happens when you hit one?
