### ISSUE TITLE
Trident counting as unarmed when Items_As_Unarmed is true

### ISSUE THREAD

**Issue by TheBentoBox** [mcMMO-Dev/mcMMO#3679]
Tridents are being treated as an unarmed weapon with `Items_As_Unarmed` enabled which causes balance issues for tridents and unarmed XP gain rate. Probably obvious but to be clear this only applies to when tridents are used as a melee weapon, not when thrown.

**Comment by nossr50** [comment]
Fixed in 77c12dcc20e1a574b45b92d33766bacb7858b16f
