### ISSUE TITLE
Leftover debug.

### ISSUE THREAD

**Issue by mibby** [mcMMO-Dev/mcMMO#3700]
McMMO v2.1.0-SNAPSHOT dev 324
https://github.com/mcMMO-Dev/mcMMO/commit/b572c0aea970a225ea27a843f879be5e3573bd9d

Typed ```/mining```, then clicked on the json skill hover text input.

```
[06:18:12] [Server thread/INFO]: mibby issued server command: /mmoinfo BlastMining
[06:18:12] [Server thread/INFO]: [mcMMO] Debug: Grabbing info for skill BlastMining
```

**Comment by mrfloris** [comment]
I assume in 2.1 the debug infos will go away once the plugin gets released to the public.

**Comment by nossr50** [comment]
I can probably remove this particular debug string as I don't need it anymore
