### ISSUE TITLE
Party friendly fire

### ISSUE THREAD

**Issue by BeeRando** [mcMMO-Dev/mcMMO#3705]
Could we add an option in the config to set friendlyfire on or off for parties? My server has friendlyfire server wide, and partys prevent it, and it kind of messes with the servers set up. A simple true/false option in the config for disablefriendlyfire would be fantastic! =D

**Comment by nossr50** [comment]
Yes I'll add this.

**Comment by nossr50** [comment]
https://github.com/mcMMO-Dev/mcMMO/commit/76ddcc4cf0933bc3e8b80b800f52204961c769d0
