### ISSUE TITLE
SkillType - Question

### ISSUE THREAD

**Issue by Rocologo** [mcMMO-Dev/mcMMO#3708]
Hi I have a long time ago added support for McMMO Classic in my own plugin MobHunting and if works fine, but one of users has upgraded to McMM 2.x and when I try to use McMMO i get an error.

java.lang.NoClassDefFoundError: com/gmail/nossr50/datatypes/skills/SkillType

It seems the SkillType has been removed from the new McMMO? Is there somewhere else I can find SkillType?

**Comment by nossr50** [comment]
Yes I've documented almost all of the API changes in 2.1.0 here, give it a read!

http://api.mcmmo.org

**Comment by nossr50** [comment]
You can also ask me about any specific API question on our discord
