### ISSUE TITLE
[Suggestion] Ability to convert exp/lvls towards Vault /money

### ISSUE THREAD

**Issue by mrfloris** [mcMMO-Dev/mcMMO#3715]
Using /addexp, or /addlevels, we can run our own non-mcMMO commands to calculate some /money or /eco from a players' balance into exp and/or levels. But we can't really go the other way as far as I know.

It would be nice if we had the ability to do so. If it's already possible, then I am sorry - i can't find it to be honest. 

I know there's mmoedit to "set" a level, but this doesn't take into account of course the current exp/lvl, it just overrides it. If someone's levelling up in the meantime through a /party grind during quad xprate, they then miss out obviously. Even if it is minor, it's not precise. I rather have a /takeexp and /takelevels, or maybe a more global command like /mcmmo exp|lvl give/take/set/add whatever.. 

Posting this here for consideration.

**Comment by nossr50** [comment]
I'm not sure if we properly support it, but there might be a way to just drain XP from a player to sort of achieve this affect. With that said, I'm not sure I'd add in proper vault support anytime soon, it's possible if enough people sell me on it though.

**Comment by mrfloris** [comment]
> I'm not sure if we properly support it, but there might be a way to just drain XP from a player to sort of achieve this affect. With that said, I'm not sure I'd add in proper vault support anytime soon, it's possible if enough people sell me on it though.

Seeing from the 25+ little addons in skript and java for mcMMO that a good chunk are about credits, redeeming levels, and converting stuff to money or exp levels, i'd say there's at least some desire for it

**Comment by mrfloris** [comment]
Since it sounds like this isn't going to happen, and this is probably best suited for unofficial addon, which haven't seen someone create yet. I think it's fair that we can close this.
