### ISSUE TITLE
[Suggestion] Berserk + Treefeller are friends!

### ISSUE THREAD

**Issue by mrfloris** [mcMMO-Dev/mcMMO#3717]
It would be quite fun if unarmed's berserk and woodcutting's treefeller are friends, allowing you a combined skill for breaking down a tree with unarmed ala treefeller. Using just your fist if your levels are high enough to break a block with a fist to break the whole tree, or a mushroom. Additionally, if your leafblower is high enough the berserk could also result in more leafs disappearing when you do that.

**Comment by nossr50** [comment]
I'm liking this lore you are developing
