### ISSUE TITLE
[Suggestion] mmoinfo as a scheduled tip?

### ISSUE THREAD

**Issue by mrfloris** [mcMMO-Dev/mcMMO#3718]
Currently on some of our servers we've taken some of the mcMMO tips we have for players and added them to auto-msg, so for me right now this isn't like a problem I am looking to solve. But I think it might be an idea to think about this outloud and see what others think or want, and if it is somehow possible to achieve this rather easily (if so, perhaps pls add it so i can uninstall automsg hehe)

To have the ability to turn on a timer for say 15 minutes, so once every 15 minutes one of the dozen skills might post a tip from mminfo to the public chat. Slowly educating players that they could use mcMMO skills to gain perks, benefits, etc.

**Comment by nossr50** [comment]
Not a bad idea, I actually have some ideas for scheduled tips

**Comment by mrfloris** [comment]
Just a notice that I am closing this. I don't see this in 2.1 at the moment, and I have started using scheduler.yml from CMI to achieve this. Using json hoverable text players can click on the skillname triggering /mining for example or a help page. This solved that for me without need for custom plugin.

**Comment by nossr50** [comment]
@mrfloris I have ideas for scheduled tips, its probably going to be a 2.3 thing.

**Comment by mrfloris** [comment]
Thanks for the information! I appreciate it. This response gives me an indication on time frame as well.

**Comment by nossr50** [comment]
Scheduled tips for players has been near the forefront of my mind when it comes to features I want to implement
