### ISSUE TITLE
[Suggestion] placeholders for mcMMO to use in chats, tabs etc

### ISSUE THREAD

**Issue by mrfloris** [mcMMO-Dev/mcMMO#3719]
We'd love to get rid of one of our custom plugins that makes placeholders for mcmmo, and use built-in ones, i dont know if 2.1 introduced this yet, or if it is possible.

But on /party we'd like to display the name of the party and the party level sometimes. 

With global chat we have a few servers where we'd like to display the power level in the main wilderness world. 

We also use this in a few servers to display things like xprate in the TAB list as well as someone's power level and/or if they're in a party.

It would be quite fantastic if mcMMO 2.1 and up could have some placeholders, perhaps through placeholderapi as an ecloud to import, if that's not already possible. (i dunno if there's an official one)

**Comment by nossr50** [comment]
I actually do have some ideas regarding linking stuff into chat with mcMMO

**Comment by mrfloris** [comment]
Closing this after a year, I don't see any built in placeholders, and I think it supports placeholdersapi (which i would love to uninstall tbh), but together with electriccats jar for mcmmo 2.1 placeholders, this will do until it's added in the future perhaps. Right now i have this suggestion solved, so closing ticket.
