### ISSUE TITLE
[Bug?] /mcconvert database sql does not write mySQL data to flatfile.

### ISSUE THREAD

**Issue by Quavelen** [mcMMO-Dev/mcMMO#3726]
So, it appears this was fixed according to t00thpick in issue #1682, but it's not functioning again? Upon using the command it simply states this:

![image](https://user-images.githubusercontent.com/19168008/51718141-dfb74500-203b-11e9-8f35-a47c52a85e47.png)

According to this page: https://github.com/mcMMO-Dev/mcMMO/wiki/Frequently-asked-questions#convertdatabase

I'm under the impression that using `/mcconvert database sql` is meant to write all mySQL data to flatfile. If this is not the case and I am misunderstanding entirely, could this please be a thing? We need a way to backup the mcmmo mySQL data, and I would really not like to have to delve into third-party mySQL tools to do it.

**Comment by nossr50** [comment]
@Quavelen You can backup your MySQL DB using the CLI on linux without any third party software. With that said, the command to convert the database from SQL to FlatFile only works if you switch the database mode to FlatFile first.

I hope that helps and if you have any further questions or request let me know here or on discord.
