### ISSUE TITLE
[Bug] Issue with /inspect

### ISSUE THREAD

**Issue by DutchUser** [mcMMO-Dev/mcMMO#3727]
**Server-version:** Paper(469) 1.13.2-R0.1-SNAPSHOT
**mcMMO-version:** 2.1.0-SNAPSHOT

**Error you see in the Console:** https://pastebin.com/TB1y3tUh
**What you see ingame(as executer)** "An internal error occurred while attempting to perform this command"

There is no error on startup, we use the MySQL.

Additional:
- It did work in 1.6, but is now broken again.

**Comment by nossr50** [comment]
This should be getting fixed soon.
