### ISSUE TITLE
Restore traps/kraken?

### ISSUE THREAD

**Issue by aegisjester** [mcMMO-Dev/mcMMO#3728]
Fishing traps and the Kraken were removed in the latest builds. We extensively use these to discourage AFK fish farms/mcmmo grinding, can they be put back in (even as optional)?

**Comment by nossr50** [comment]
They will not be put back in as I felt they did not find them appropriate for mcMMO, I will be adding another measure of protection against AFK fishing soon that won't involve spawning TNT or deadly squids appearing out of nowhere.

**Comment by andrewkm** [comment]
An anti auto fishing measure would be lovely!

**Comment by nossr50** [comment]
@andrewkm I added one in 2.1.1 or 2.1.2
