### ISSUE TITLE
Mcmmo internal error occured

### ISSUE THREAD

**Issue by Camohunter7t** [mcMMO-Dev/mcMMO#3731]
When ever I use any of the /achery, /mining/ etc I get An internal error occured while attempting to perform this command.
Please help.
https://pastebin.com/UqDrhY90

**Comment by nossr50** [comment]
This error is a result of not using Spigot or Paper when running your server

Spigot/Paper are an extension of the Bukkit API, imagine Bukkit with a few more features and you have Spigot/Paper. mcMMO requires you to run Spigot or paper in order for it to function.

You can grab paper here

https://papermc.io/
