### ISSUE TITLE
[mcMMO] Warning Max Bonus Level for Skills.Fishing.Shake.MaxBonusLevel is set to 0! Typically this value should be 100.

### ISSUE THREAD

**Issue by ktr0x** [mcMMO-Dev/mcMMO#3737]
Similar issues have been reported before and solved. The error is logged when the /fishing command is executed.

**Comment by nossr50** [comment]
@ktr0x this should be fixed in the latest builds, which build are you on?

**Comment by ktr0x** [comment]
Build #287, second to latest dev build
