### ISSUE TITLE
100% Green Thumb chance does not always replant crops

### ISSUE THREAD

**Issue by GiraffeCubed** [mcMMO-Dev/mcMMO#3742]
Having 100% Green Thumb chance, through levels, or a mix of levels + lucky perk, doesn't always replant crops. The chance seems to cap out at maybe ~75%, where it should replant every single time as long as the correct resources are in the players inventory.

**Comment by nossr50** [comment]
That's a bit strange I'll look into it

**Comment by nossr50** [comment]
I think this issue is related to another issue, I will look into it soon 😸

**Comment by broccolai** [comment]
Fixed when Green Thumb was linked to Hoes
