### ISSUE TITLE
Mcmmo crop drop issue

### ISSUE THREAD

**Issue by LogGits** [mcMMO-Dev/mcMMO#3749]
Having this issue with harvesting crops messing with inventory.

https://gyazo.com/de90738c8c7da359a26cab198923c848

**Comment by Quavelen** [comment]
Yup, nossr50 is on it. He just did commit 7e5a8bc before you opened this issue.

**Comment by nossr50** [comment]
I have a pretty good idea why this is happening, I hope to fix this soon 🙇

**Comment by broccolai** [comment]
No longer an issue
