### ISSUE TITLE
You reached max furnace count  mcmmo

### ISSUE THREAD

**Issue by Cobzer** [mcMMO-Dev/mcMMO#3751]
Hello!  

When I click on a furnace I got this message: You reached max furnace

And I do not "level up" in reapir or smelting.  Whats wrong?

I am on pc- version 1.13.2

**Comment by mrfloris** [comment]
Isn't that from jobs plugin?

**Comment by nossr50** [comment]
I'm not sure... doesn't sound like an mcMMO feature
