### ISSUE TITLE
Missing locales

### ISSUE THREAD

**Issue by muehre** [mcMMO-Dev/mcMMO#3759]
There a multiple locale messages missing:

- Unlock Skill Chat message (i.e. [ mcMMO@Skill Rank X Unlocked! ])
- Skill Level increased (i.e. Mining increased to X)
- Bossbar/Title during xp gaining: Skillname is still english (Woodcutting instead of the translation)

**Comment by muehre** [comment]
/<skill> overview  is also not translateable (XP GAIN/Sub-Skills)

**Comment by muehre** [comment]
Any updates? You did remove the In Progress label

**Comment by nossr50** [comment]
I don't even removing that label or adding it 😱 

Are you sure these are missing? I think they are in the locale.

`JSON.SkillUnlockMessage=[[GOLD]][ mcMMO[[YELLOW]] @[[DARK_AQUA]]{0} [[GOLD]]Rank [[DARK_AQUA]]{1}[[GOLD]] Unlocked! ]`

`Overhaul.Levelup=[[BOLD]]{0} increased to [[RESET]][[GREEN]][[BOLD]]{2}[[RESET]][[WHITE]].`

for the boss bar title, the skill name SHOULD be getting pulled from the locale, you have to define that here

`Overhaul.Name.Acrobatics=Acrobatics
Overhaul.Name.Alchemy=Alchemy
Overhaul.Name.Archery=Archery
Overhaul.Name.Axes=Axes
Overhaul.Name.Excavation=Excavation
Overhaul.Name.Fishing=Fishing
Overhaul.Name.Herbalism=Herbalism
Overhaul.Name.Mining=Mining
Overhaul.Name.Repair=Repair
Overhaul.Name.Salvage=Salvage
Overhaul.Name.Smelting=Smelting
Overhaul.Name.Swords=Swords
Overhaul.Name.Taming=Taming
Overhaul.Name.Unarmed=Unarmed
Overhaul.Name.Woodcutting=Woodcutting`

and here

`JSON.Acrobatics=Acrobatics
JSON.Alchemy=Alchemy
JSON.Archery=Archery
JSON.Axes=Axes
JSON.Excavation=Excavation
JSON.Fishing=Fishing
JSON.Herbalism=Herbalism
JSON.Mining=Mining
JSON.Repair=Repair
JSON.Salvage=Salvage
JSON.Swords=Swords
JSON.Taming=Taming
JSON.Unarmed=Unarmed
JSON.Woodcutting=Woodcutting`
