### ISSUE TITLE
ERROR Could not pass event BlockDamageEvent to mcMMO v2.1.3

### ISSUE THREAD

**Issue by Sorry** [mcMMO-Dev/mcMMO#3762]
Receiving this error on my Spigot 1.13.2 server, multiple times over.

01.02 14:39:20 [Server] ERROR Could not pass event BlockDamageEvent to mcMMO v2.1.3
01.02 14:39:20 [Server] INFO org.bukkit.event.EventException: null
01.02 14:39:20 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-b634e05]
01.02 14:39:20 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-b634e05]
01.02 14:39:20 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-b634e05]
01.02 14:39:20 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-b634e05]
01.02 14:39:20 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callBlockDamageEvent(CraftEventFactory.java:357) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-b634e05]
01.02 14:39:20 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:179) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-b634e05]
01.02 14:39:20 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1162) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-b634e05]
01.02 14:39:20 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-b634e05]
01.02 14:39:20 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-b634e05]
01.02 14:39:20 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-b634e05]
01.02 14:39:20 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
01.02 14:39:20 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
01.02 14:39:20 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-f56e2e7-b634e05]
01.02 14:39:20 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-f56e2e7-b634e05]
01.02 14:39:20 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-f56e2e7-b634e05]
01.02 14:39:20 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-f56e2e7-b634e05]
01.02 14:39:20 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-f56e2e7-b634e05]
01.02 14:39:20 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
01.02 14:39:20 [Server] INFO Caused by: java.lang.IndexOutOfBoundsException: Index: 0
01.02 14:39:20 [Server] INFO at java.util.Collections$EmptyList.get(Collections.java:4454) ~[?:1.8.0_191]
01.02 14:39:20 [Server] INFO at com.gmail.nossr50.util.player.UserManager.getPlayer(UserManager.java:99) ~[?:?]
01.02 14:39:20 [Server] INFO at com.gmail.nossr50.listeners.BlockListener.onBlockDamageCleanup(BlockListener.java:527) ~[?:?]
01.02 14:39:20 [Server] INFO at sun.reflect.GeneratedMethodAccessor377.invoke(Unknown Source) ~[?:?]
01.02 14:39:20 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
01.02 14:39:20 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
01.02 14:39:20 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-b634e05]
01.02 14:39:20 [Server] INFO ... 17 more

**Comment by broccolai** [comment]
Cannot reproduce, if this is still an issue on the latest version, please update this issue.
