### ISSUE TITLE
Help with default Skill Duration and Starting Level

### ISSUE THREAD

**Issue by WolfenOmega** [mcMMO-Dev/mcMMO#3766]
On a completely new generation of the MCMMO folder with the latest MCMMO jar, the skills unlock at level 5 and the duration seems really high (10 seconds or more). I thought maybe the unlock level was the Ability_Activation_Level_Gate in the config file, but changing that did nothing for me. I also read that the starting duration should be 2 seconds, but it's going way over.

Maybe I'm blind (more likely than not), but for the life of me I can't find the area to change these settings, nor can I find any documentation for this part in particular. Any help is appreciated.

**Comment by ImNotShady** [comment]
You will have to define the Ability_Activation_Level_Gate for every individual skill. It is the config that affects when the skill ability be accessed. So you can make the requirement for unarmed be level 5 and at the same time make the requirement for woodcutting to be 20.
Make sure you do a full server restart after you change your CFGs as McMMO doesn't have a reload command at this time. The changes will not be applied until you do so.

**Comment by nossr50** [comment]
Abilities shouldn't be using gates anymore and instead be based on the skill unlock level in skillranks.yml @ImNotShady  I'll double check to make sure I cleaned up the gate code

**Comment by WolfenOmega** [comment]
I was literally just about to comment the Ability_Activation_Level_Gate didn't change anything after a restart when you jumped in nossr50 - that makes a lot of sense, I even looked there but I was too focused on the Ability_Activation_Level_Gate to think much of anything else. I'm all set now, thanks guys!
