### ISSUE TITLE
[Suggestion] Blast-mining using pickaxe and tnt

### ISSUE THREAD

**Issue by mrfloris** [mcMMO-Dev/mcMMO#3782]
It would be more logical to add blast mining to a pick axe. A player with enough levels can unlock blast mining, then put tnt in their inventory. Each time they trigger blast-mining it will deduct the tnt from the inventory.

**Comment by nossr50** [comment]
I'll add this soon for 2.2.0 😸

**Comment by mrfloris** [comment]
Since this got locked, but things got delayed (which is ok!), just bumping this anyway, as a friendly reminder so tnt-blasting-alternative is maybe not forgotten.
