### ISSUE TITLE
The IronArmStyle configuration within "advanced.yml" generates without BonusMax and BonusMin.

### ISSUE THREAD

**Issue by Quavelen** [mcMMO-Dev/mcMMO#3785]
The title pretty much explains it. Here is a screenshot:

![image](https://user-images.githubusercontent.com/19168008/52545281-2b911a80-2dae-11e9-9832-9ac2d1fc48ff.png)

**Comment by nossr50** [comment]
Closing this since it won’t be relevant in 2.2
