### ISSUE TITLE
Options for us poor server admins?

### ISSUE THREAD

**Issue by FlailoftheLord** [mcMMO-Dev/mcMMO#3795]
Welp... its all fishy and premium now, not even a jenkins link anymore??
Is there any way for those who can't afford to spend money on the plugin to obtain a build??

I know you've put a ton of work into the plugin, and i really love it, but money's just not something i'm comfortable spending online.

**Comment by Quavelen** [comment]
Please join the discord, and look at the links channel. It contains the Jenkins.

**Comment by nossr50** [comment]
@FlailoftheLord You can compile the source code yourself (its very easy), we have jenkins links in the discord
