### ISSUE TITLE
Fish types other than Salmon and Cooked Salmon are not supported by Fisherman's Diet

### ISSUE THREAD

**Issue by Nicofisi** [mcMMO-Dev/mcMMO#3803]
https://github.com/mcMMO-Dev/mcMMO/blob/ba88831c8872464fd84b62661ad47a8f289185f4/src/main/java/com/gmail/nossr50/listeners/EntityListener.java#L769-L782

In 1.13, there's also for example Raw Cod, Cooked Cod and Tropical Fish that can be eaten.

Edit: might be worth checking if the other food lists in this event are up to date, too ;)

Cheers!

**Comment by nossr50** [comment]
Fixed a while ago
