### ISSUE TITLE
Some Sub-Skills do not Display in Chat

### ISSUE THREAD

**Issue by DoragonKeiyou** [mcMMO-Dev/mcMMO#3808]
I've noticed that some skills using Overhaul do not show up in chat.  With the example image, fishing was leveled to 10, where you would gain Ice Fishing at Lv5 and Treasure Hunter at Lv10.  Neither were prompted in chat.
![fwokrjypgv](https://user-images.githubusercontent.com/9502203/53459206-91acad00-39fe-11e9-9c1e-5d869b841c47.png)

**Comment by nossr50** [comment]
Thanks I'll look into this soon.
