### ISSUE TITLE
Acrobatics xp cannot be gained when the absorption status effect is active.

### ISSUE THREAD

**Issue by Quavelen** [mcMMO-Dev/mcMMO#3809]
The title is self-explanatory. It was reported in the discord via `#🐛-bug-reports` by `echoblast53#4663`.

**Comment by jstnf** [comment]
[`EventUtils#isRealPlayerDamaged(EntityDamageEvent)`](https://github.com/mcMMO-Dev/mcMMO/blob/33a68daa9c1920619c11b549eb0560123c4a2b65/src/main/java/com/gmail/nossr50/util/EventUtils.java#L95) only checks `EntityDamageEvent#getFinalDamage()` and not `EntityDamageEvent#getDamage()` despite Acrobatics using `getDamage()` and not `getFinalDamage()` to calculate experience gain.

When a Player takes damage and has Absorption, Absorption is considered a damage modifier- thus, when `EntityDamageEvent#getFinalDamage()` is called, it might return 0 if all of the fall damage is covered by the Absorption hearts.

**Comment by nossr50** [comment]
Thanks I'll review this PR soon.

**Comment by nossr50** [comment]
Fixed by #3884
