### ISSUE TITLE
Items rising to surface

### ISSUE THREAD

**Issue by Noufaris** [mcMMO-Dev/mcMMO#3817]
When McMMO is enabled, and only then, our server has an issue of mined blocks often rising through the ceiling and up to the surface or an above cave. It's resulted in players loosing ore and stone  while mining.

**Comment by nossr50** [comment]
As I described on github, there might be something I can do to mitigate this problem, I'm not 100% sure it's mcMMO's fault however.

**Comment by Adversarius13293** [comment]
The same happens when salvaging tools on a gold block. I have a hopper minecart inside the gold block to pick items up, encased it with other blocks, and one half slab space above the gold block. It worked fine previously, but now most of the items get scattered around this construction.

**Comment by broccolai** [comment]
Is this still an issue?

**Comment by Quavelen** [comment]
This is no longer an issue @broccolai, no. It was resolved on Spigot's end a while back.
