### ISSUE TITLE
Two smelting issues.

### ISSUE THREAD

**Issue by Quavelen** [mcMMO-Dev/mcMMO#3818]
The first issue is that the fuel efficiency does not seem to have a cap. For example, at lvl 629 mining and lvl 1002 repair, the efficiency multiplier is at 25.45x, as seen here: 

![image](https://user-images.githubusercontent.com/19168008/54067423-c9ee8f80-4237-11e9-9575-0ea95967aa7e.png)

Default vanilla behaviour allows you to smelt 100 items per lava bucket. This means that without the cap, mcmmo allows you to smelt 2,545 ores if you place a single lava bucket in at 25.45x effciency as shown in the above image. 

The second issue is that you receive mining and repair xp with a fully automatic smelter. I used this one to test:

![image](https://user-images.githubusercontent.com/19168008/54067475-66b12d00-4238-11e9-8d56-d5f283308a24.png)

It's a simple design that feeds the furnace fuel and ores, then spit the ingots out into a chest below. Without any interaction whatsoever, you still gain xp in the aforementioned skills.

**Comment by nossr50** [comment]
Fixed
