### ISSUE TITLE
Kelp XP calculation

### ISSUE THREAD

**Issue by x1p** [mcMMO-Dev/mcMMO#3820]
Herbalism counts the kelp_plant no matter how tall the plant is. That's not logical to me.
The chorus plants or sugar cane also detects the amount of blocks. It somehow counts the length of the plant. Imho Kelp should be counted likewise.

**Comment by nossr50** [comment]
Thanks I'll look into it

**Comment by x1p** [comment]
Version 2.1.17 still suffers from this. I have Kelp_plant set to 1 xp. If I break it low from the stem, it give me 3 xp. If I destroy the plant bit by bit from top to bottom I get much much more xp, something like 20 xp.

**Comment by nossr50** [comment]
@x1p Oh this is a bit embarrassing, I'll fix it for the other way as well

**Comment by nossr50** [comment]
@x1p Should be fixed now, it turns out Kelp was made of multiple block types and we had some hardcoded limit for how many plants of XP to calculate which I tweaked
