### ISSUE TITLE
Fishing skill not gaining XP

### ISSUE THREAD

**Issue by xenxero1** [mcMMO-Dev/mcMMO#3826]
Currently running version 2.1.12 on our server, and it appears that players are unable to gain fishing XP. The fishing skill is not disabled on our server, but we are using the Jobs plugin which could be causing conflicts.

**Comment by nossr50** [comment]
Make sure your Spigot or Paper server is up to date, the most likely cause for this is a missing API definition that was added semi-recently.

Check your console for errors, if you see NoClassDef found, the fix I'm describing should work.

Feel free to reopen this issue if this did not fix the bug.
