### ISSUE TITLE
Some herbalism double drops don't work

### ISSUE THREAD

**Issue by Adversarius13293** [mcMMO-Dev/mcMMO#3832]
Nether Wart, Wheat, Carrots, Potatoes, Beetroot and Cocoa don't give double drops, while still giving xp.

If I add "Wheat" and "Beetroots" to the double drops in config.yml, the double drops for this two crops work. But I can't get the other ones to work.

**Comment by nossr50** [comment]
Thanks I'll look into this today and see if I can push out a fix.
