### ISSUE TITLE
Double Drops for Andesite/Diortie/Granite

### ISSUE THREAD

**Issue by Adversarius13293** [mcMMO-Dev/mcMMO#3834]
The stonetypes Andesite, Diortie and Granite will give mining xp, but don't work with double drops like they did in 1.12.
Even adding these three blocks to the config.yml under double drops wont' work.

**Comment by nossr50** [comment]
Thanks I'll look into this today and see if I can push out a fix.

**Comment by nossr50** [comment]
Fixed in dev builds, expect it in 2.1.23
