### ISSUE TITLE
Rupture not working with Looting

### ISSUE THREAD

**Issue by Adversarius13293** [mcMMO-Dev/mcMMO#3835]
If a mob dies from Rupture, the Looting effect of the sword is not applied.
This is a very negative effect, because as a player you can't prevent rupture, and it will reduce your mobfarm drops by a lot.

There are a lot of mobs in your mobfarm, and you hit them all with a sweeping edge and looting sword. They dont die from the first hit, but 1 second later from rupture. You have nearly no time to attack a second time with your sword to kill them with looting, and they just die without looting.

I would absolutly rather not have the skill at all, than missing out on all the looting effects.

In vanilla you can use arrows, potions, or any other cause to kill a mob and get the looting effect, as long you are holding your looting sword at the moment of death in your hand.

**Comment by nossr50** [comment]
Hmm this is a strange one, I'll look into it.

**Comment by nossr50** [comment]
Fixed in dev builds, expect it in 2.1.23
