### ISSUE TITLE
Default treasures.yml shake

### ISSUE THREAD

**Issue by Adversarius13293** [mcMMO-Dev/mcMMO#3836]
Feature request 1: Change the shake loot for Iron Golem and Snowman from Pumpkin to Carved_Pumpkin.

Feature request 2: Add shake entries for some of the new 1.13 mobs: Drowned, Turtle, Phantom

**Comment by Adversarius13293** [comment]
Also the default Head drops for Shake should be changed.
Creeper drop Skeleton_Skull instead of Creeper_Head, same for Zombie. And they don't need the data tag anymore.

**Comment by nossr50** [comment]
Thanks I'll look into this today and see if I can push out a fix.

**Comment by u-C-m** [comment]
can confirm that zombies only drop skeleton skulls. haven't looked into creeper or skeletons yet.

**Comment by broccolai** [comment]
Cannot reproduce anymore
