### ISSUE TITLE
Shulkerbox duplication glitch

### ISSUE THREAD

**Issue by andris155** [mcMMO-Dev/mcMMO#3838]
1. Start Paper 1.13.2 server with mcMMO plugin.
2. Join and add 1000 level to Mining ability.
3. Activate Super Breaker Once.
4. Break Shulkerbox.
5. Shulkerbox duplicated.

https://drive.google.com/file/d/14Lio_yi6xcINEt_BCoWMuuI70O5J7YpO/view?fbclid=IwAR2KKtykaDty63uCepGqpFP-eC9vHrnUykaunxlDCWP9XkWyQY1-lXM-Y6U
mcMMO 2.1.23
Paper 1.13.2 build 584

**Comment by nossr50** [comment]
Investigating now

**Comment by nossr50** [comment]
I cannot reproduce this @andris155
