### ISSUE TITLE
Receiving error / Version 2.1.24

### ISSUE THREAD

**Issue by oPqnda** [mcMMO-Dev/mcMMO#3839]
I am currently using the latest version of mcMMO and I am starting to receive this error and it's getting pretty spammy in my console. Before the update, I wasn't receiving this error all so after the recent update, the error started to occur

**Error link**: https://pastebin.com/U2pyZnTE

**Comment by nossr50** [comment]
you need to update Spigot or Paper to the newest version and this error will disappear
