### ISSUE TITLE
World specific skills and abilities.

### ISSUE THREAD

**Issue by ghost** [mcMMO-Dev/mcMMO#3840]
Per-world abilities & skills
Per World XP boost events.
Per World skills and abilities

Example:
I only want PVP to be leveled up in the PVP world & special abilities related to PVP only be used in PVP world.
I'd like to run a daily command to enable XP boosts in a specific world.
does that make sense?

**Comment by broccolai** [comment]
You can use permissions to negate things in certain worlds
