### ISSUE TITLE
[BUG] DB call returns NullPointer Exception & General API issues

### ISSUE THREAD

**Issue by Ineusia** [mcMMO-Dev/mcMMO#3842]
mcMMO.getDatabaseManager().readRank("playerName").get(skillEnum)

Returns NullPointer Exception when the level of skillEnum is zero

Sidenote: readRank should use uuids instead of strings to identify players (uuids are already stored in DB)

**Comment by nossr50** [comment]
![image](https://user-images.githubusercontent.com/407458/55272411-85c03f00-5279-11e9-9a91-b73732291dec.png)

posting this as a reminder

**Comment by Ineusia** [comment]
Inconsistency:

ExperienceAPI.getOfflineXPRemaining() 
Return type: Float

ExperienceAPI.getOfflineXPToNextLevel()
Return type: Integer
Should return: Float
Why: If getOfflineXPRemaining has the potential to return a float, then I don't see why this method doesn't.

ExperienceAPI.getOfflineXP()
Return type: Integer
Should return: Float
Why: Same as above. This is probably the same for any API method regarding experience.

**Comment by nossr50** [comment]
Fixed in the PR sort of
