### ISSUE TITLE
[BUG] mcfools command

### ISSUE THREAD

**Issue by Ineusia** [mcMMO-Dev/mcMMO#3847]
01.04 01:19:27 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'mcfools' in plugin mcMMO v2.1.30
01.04 01:19:27 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-559]
01.04 01:19:27 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-559]
01.04 01:19:27 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-559]
01.04 01:19:27 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1798) ~[patched_1.13.2.jar:git-Paper-559]
01.04 01:19:27 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1606) ~[patched_1.13.2.jar:git-Paper-559]
01.04 01:19:27 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-559]
01.04 01:19:27 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-559]
01.04 01:19:27 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-559]
01.04 01:19:27 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
01.04 01:19:27 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
01.04 01:19:27 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-559]
01.04 01:19:27 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-559]
01.04 01:19:27 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-559]
01.04 01:19:27 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-559]
01.04 01:19:27 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-559]
01.04 01:19:27 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
01.04 01:19:27 [Server] INFO Caused by: java.lang.NullPointerException
01.04 01:19:27 [Server] INFO at com.gmail.nossr50.commands.skills.AprilCommand.getXPGainString(AprilCommand.java:73) ~[?:?]
01.04 01:19:27 [Server] INFO at com.gmail.nossr50.commands.skills.AprilCommand.onCommand(AprilCommand.java:40) ~[?:?]
01.04 01:19:27 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-559]
01.04 01:19:27 [Server] INFO ... 15 more

**Comment by nossr50** [comment]
2.2 is removing the April Fools stuff
