### ISSUE TITLE
Crafting skill and villager trading

### ISSUE THREAD

**Issue by Adversarius13293** [mcMMO-Dev/mcMMO#3849]
If you trade with villagers, put items/emeralds in their trading slot, und trade with shift+click, you get a crafting skill notification and fireworks for every single trade made. 
If a farmer buys 8 Pumpkins for 1 emerald, and you sell 48 at once with shift, you get 6 notifications, all at once.
I guess thats way too fast "leveling". Even making only one trade with shift creates a notification.

If you trade by clicking without holding shift, and picking up one trade after another, it doesn't level you up each time.

**Comment by nossr50** [comment]
Crafting is not a skill in mcMMO

**Comment by Adversarius13293** [comment]
this was about the mcfools "skills", if it was not clear enough.

**Comment by Adversarius13293** [comment]
Just trade with villagers while holding shift at 1. april.
https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/util/HolidayManager.java

**Comment by nossr50** [comment]
TBH April Fools probably won't be in mcMMO much longer, as I don't like it.

**Comment by Adversarius13293** [comment]
okay, sounds fair enough
