### ISSUE TITLE
Question : Acrobatics and gaining XP

### ISSUE THREAD

**Issue by thunderlight411** [mcMMO-Dev/mcMMO#3850]
is there some sort of cool-down between the times you gane XP for acrobatics, trying to fall on different place when jumping of a mountain but i only get XP from the first fall.
The other falls cost live as well but dont give any XP.

i have read some rumors in discord that there is a 60 seconds cooldown between the times you can gain XP.

Is there any why to tweak this.

60 seconds cooldown and a remember of the last x amount of fall locations feels a bit to hard to level acrobatics if you compair this with the past that you can gain XP from falling from a acrobatics tower over and over again like this clip 
https://www.youtube.com/watch?v=VNA8Bd4kQGs

**Comment by nossr50** [comment]
It will be configurable in the Config update, and yes it is on a 60 second CD to discourage grinding.

**Comment by thunderlight411** [comment]
good to know, need to overlook our ranking requirements for Acrobatics for now because leveling from 0 >150 > 400 > 750 > 1000 is going to be a very long way to level with that CD.

i understand that you want to discourage grinding but i think this is is just one 1 step to far

**Comment by nossr50** [comment]
There's a setting to turn it off and configure it in 2.2

There is really no effective way to combat Acrobatics fall XP grinding other than doing something like this IMO.
