### ISSUE TITLE
Salvage and Repair both giving incorrect number of items

### ISSUE THREAD

**Issue by Momshroom** [mcMMO-Dev/mcMMO#3852]
Repair and salvage are still broken in overhaul so that repair repairs more than it should and salvage salvages less than it should. At 285 salvage, I'm getting one leather salvaging full health leather armor, regardless of the piece, and at a repair level of only 420 (retro mode) it's taking only one piece of leather to repair almost completely broken chestplates.  Resetting my stats to zero, I can still almost fully repair an iron helm with one ingot and if I edit my repair and fishing each to 1000, I can still only get one ingot salvaging an iron chestplate.

More detailed example.  Gold chestplate with 2/112 durability, player with 421 repair, one ingot brings it to 105/112. The same player, who has salvage of 285, finishes repairing to full health the chestplate with another ingot, and salvages it and it only yields one ingot. A player with maxed salvage of 1000 STILL only receives one ingot salvaging the gold plate. A player with a repair skill of zero can take that plate from 4/112 to 60/112 with only one ingot.

 I had a very old ticket on classic about it. I see two related tickets:  #3649 which addresses only the salvage half of he issue and is open, but the comment about it being included in 2.1 implies that it is fixed and #2290 which also only addresses the salvage half of the issue and seems to have been misinterpreted as a question of how it is supposed to work rather than a bug report and closed.  

I'm using Spigot 1.13.2 
This server is running CraftBukkit version git-Spigot-3cb9dcb-8d8475f (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
And mcmmo version 2.1.32 
[mcMMO] Running version 2.1.32

**Comment by nossr50** [comment]
Upon testing Salvage does give the correct #, which makes me believe you need to update or delete your salvage config file.

Repair on the other hand seems to be giving too much for small amounts of skill.

**Comment by Momshroom** [comment]
Regenerating my salvage.vanilla.yml did fix salvaging.  Ty.

**Comment by FatherWh0** [comment]
I have the same issue. Players with over 1000 salvage only get 2 pieces back salvaging a chestplate. I tried regenerating my salvage.vanilla.yml and repair.vanilla.yml both but it didn't fix the issue. The fact is, I regenerated all mcmmo files when I updated to 1.13 as instructed.
mcmmo 1.6.0
paper 1.13.2 #614

**Comment by nossr50** [comment]
@FatherWh0 Did you mean to post this on classics issue page?

Either way its fixed in mcMMO, but for classic its only fixed in dev

http://spigot.mcmmo.org - New version of mcMMO
