### ISSUE TITLE
Unable to use /<SKILLNAME> commands.

### ISSUE THREAD

**Issue by kingriku1** [mcMMO-Dev/mcMMO#3854]
Hello. I installed the latest build of mcMMO onto my 1.13.2 paperSpigot server and having issues with it. The skills themselves seem to work, and all other commands work as well, but the /<skillname> commands are not working. Here is the paste bin of the error

https://pastebin.com/RTiVhvna

Any help would be appreciated, thanks.

**Comment by electronicboy** [comment]
That error is because you are running CraftBukkit, as oppose to paper/spigot
