### ISSUE TITLE
Compiling error: void cannot be converted to boolean

### ISSUE THREAD

**Issue by waterlubber** [mcMMO-Dev/mcMMO#3866]
I was compiling from master (ᵇᵉᶜᵃᵘˢᵉ ᴵ ᵈᵒⁿ'ᵗ ʰᵃᵛᵉ ᵃ ᶜʳᵉᵈⁱᵗ ᶜᵃʳᵈ) and I got the following error: 
`[ERROR] /mnt/main/home/waterlubber/Downloads/mcMMO/src/main/java/com/gmail/nossr50/runnables/player/PlayerProfileSaveTask.java:[15,48] error: incompatible types: void cannot be converted to boolean`
([full stacktrace](https://pastebin.com/bY1QurMU))

It appears to be caused by [this commit](https://github.com/mcMMO-Dev/mcMMO/commit/426b1304e2c2137202cbbde26959b8288ed1f7ce#diff-475daae23f4c7ec416d66b42f3ee2135)
and the following line:
`boolean saveSuccess = playerProfile.save();`
It looks like playerProfile.save returns a void, and the code is expecting a boolean.

I was able to fix it by reverting the changes to said file (removing the "success" logic), although the proper solution would probably be just to change the playerProfile function (I'm not super familiar with java, so I wasn't able to find this in the source, sorry.)

The "fixed" variant compiles and runs on the server. I'll update this issue if I find any problems testing.

**Comment by nossr50** [comment]
Yeah this is an error in the dev builds, the dev builds are not recommended for live servers. I'll be correcting it soon.

**Comment by nossr50** [comment]
https://github.com/mcMMO-Dev/mcMMO/commit/87bf3a5b40ec98044405a8ba8c43038b02d7e3b0

Fixed
