### ISSUE TITLE
[Suggestion] Ability to /mcstats <player> from console

### ISSUE THREAD

**Issue by mrfloris** [mcMMO-Dev/mcMMO#3869]
Hey,

It would be wonderful if we could inspect players their details from the console for logging and review reasons. Right now I believe I have to vanish and tp to the player, and use /inspect

But I rather remain offline in most cases and type: `mcstats <playername>` from console to get a list of their stats. Especially in cases where we're adjusting their stats manually or resetting them. 

If this is already possible, then I have overlooked this, I tried but it did not work.

**Comment by nossr50** [comment]
There is a permission node to bypass the inspect distance, and in 2.2 I'm making it so OPs bypass the distance restriction

I think the node is mcmmo.commands.mcrank.others.far

**Comment by mrfloris** [comment]
Ah cool, thank you.
