### ISSUE TITLE
[Suggestion] 100% salvaging drop chance permission

### ISSUE THREAD

**Issue by GiraffeCubed** [mcMMO-Dev/mcMMO#3872]
Similar to the Arcane Forging Bypass permission, which allows players a 100% chance to keep enchantments on repaired gear, it would be great to have a permission for salvaging which allowed a 100% drop rate on enchantment books from salvaged gear.

The suggestion does stem from a recent bug, however it was popular on my server and players are eager for a way to legitimately acquire these 100% drop rates.

**Comment by nossr50** [comment]
Added
