### ISSUE TITLE
Salvaging Bypass message error

### ISSUE THREAD

**Issue by GiraffeCubed** [mcMMO-Dev/mcMMO#3873]
The new salvaging bypass permission works like a charm. My server are over the moon with it! They're a little confused by this message, which appears even though enchants were not removed or downgraded on the book, but otherwise - top notch!

http://prntscr.com/nbnxr7

For now I'm going to cancel the packet if the player has the permission, but I thought it worth bringing up!

**Comment by nossr50** [comment]
Ah that is a bit odd, I'll go take a look and see why its happening.
