### ISSUE TITLE
Not receiving any XP 

### ISSUE THREAD

**Issue by RussCat** [mcMMO-Dev/mcMMO#3874]
My commands work and all but i dont recieve any XP and i cant use my abilities

**Comment by RussCat** [comment]
14.04 11:15:00 [Server] ERROR [mcMMO] Plugin mcMMO v2.1.44 has failed to register events for class com.gmail.nossr50.listeners.BlockListener because org/bukkit/event/block/BlockDropItemEvent does not exist.
14.04 11:15:00 [Server] ERROR [mcMMO] Plugin mcMMO v2.1.44 has failed to register events for class com.gmail.nossr50.listeners.EntityListener because org/bukkit/event/entity/EntityTransformEvent does not exist.

i get those only issues when i reload the server

**Comment by nossr50** [comment]
` because org/bukkit/event/block/BlockDropItemEvent does not exist.`

Update Spigot to the newest version via BuildTools
