### ISSUE TITLE
MCMMO skills and abilities not working

### ISSUE THREAD

**Issue by Barren-Soul** [mcMMO-Dev/mcMMO#3882]
I have a  Spigot 1.13.1 server running MCMMO 2.1.44, which says it's for 1.13. Installation seemed to go fine and when in-game, I can use commands like /mining to view the mining skill, abilities, and exp, and I can right-click to start activating an ability (it'll say 'You ready your axe' and such) but abilities do not ever actually activate, and exp is not going up for any skill as far as I can tell. 
If I need to post a log or something, please let me know how to do that, I'm very new to Minecraft servers.

**Comment by nossr50** [comment]
Mcmmo requires the latest versions of 1.13.2 for spigot,  I cannot specify anything other than 1.13 on that website sorry for the confusion
