### ISSUE TITLE
Party members

### ISSUE THREAD

**Issue by Huntermaster0** [mcMMO-Dev/mcMMO#3889]
Hello, the party command displays only the online members, and there is no command to see all members of the party. Can you place back the old solution, which is:
-Offline members with light grey
-online members with normal white characters
-offline leader with 1 yellow (&6) letter
-online leader with full yellow
or something like this. Now it's hard to say how many people are in the party, please fix it. (Sorry for my bad English, i'm hungarian).

**Comment by nossr50** [comment]
I'll look into it 😄
