### ISSUE TITLE
Party command error

### ISSUE THREAD

**Issue by Huntermaster0** [mcMMO-Dev/mcMMO#3898]
Hello, I opened #3889 2 days ago, and since it's closed, the party command gives me an error, when the leader is offline. When the leader is online, the command works perfectly.

**Comment by thunderlight411** [comment]
found the following errors in my console when players try using /party when the leader is offline
Error can be found here : https://paste.gg/p/anonymous/277f618a3e27413f8f939a65578df551

when party leader is offline 
https://i.imgur.com/bcPvsBu.png

If you want a full log let me know

**Comment by nossr50** [comment]
Fixing this soon boys
