### ISSUE TITLE
Can't disable event titles

### ISSUE THREAD

**Issue by Sikatsu** [mcMMO-Dev/mcMMO#3909]
Tried to disable the titles for the xp event, however it still sends the big text in my screen.

    Events:
        XP:
            SendTitles: false

**Comment by nossr50** [comment]
I'm unable to replicate this bug, nothing looks off in the code either.

![Screenshot from 2019-04-28 06-46-25](https://user-images.githubusercontent.com/407458/56865303-6f44fa80-6981-11e9-82e7-a9275adb8fc0.png)
