### ISSUE TITLE
not gaining mcmmo mining xp on a server

### ISSUE THREAD

**Issue by Jaquez2678** [mcMMO-Dev/mcMMO#3912]
Im playing on a prisons server and I'm not getting any mcmmo mining xp from breaking blocks, I only get it from smelting ores. I have made bug reports and im told that its not a server issue but its an issue with my Minecraft

**Comment by broccolai** [comment]
If you're a player then you need to contact your server admins, if you're a server admin you can contact us in the discord for support.
