### ISSUE TITLE
[Bug] locale reload issue.

### ISSUE THREAD

**Issue by Remski01** [mcMMO-Dev/mcMMO#3915]
Hello.

So, when you edit any guides lines and then use "/mcmmoreloadlocale" it wont update it.

**Comment by mikroskeem** [comment]
That's sadly because [how skill guide command is set up](https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/commands/skills/SkillGuideCommand.java#L20), it stores strings into class fields.

Might send a PR soon...

**Comment by DutchUser** [comment]
Nossr said this more early, 

```
that stuff might be cache'd which is why
I could add it in, slap an issue on git
```
