### ISSUE TITLE
[Bug] mcMMO does hide away the skill in "/inspect" but does it in "/mcstats"

### ISSUE THREAD

**Issue by Remski01** [mcMMO-Dev/mcMMO#3917]
So.

We have as example "salvage" disabled by using its permissions. 

And in "/mcstats" the skill is not visible. 
But in "/inspect" the skill still shows up.

This one is `/mcstats`
https://postimg.cc/jCw1ZC30

This one is `/inspect`
https://postimg.cc/DJWxjYgd

**Comment by DutchUser** [comment]
This also a issue in /<skill>, under the `Commands.Stats.Self.Overhaul` the info regarding the abiltity are removed. 

But the ability's are not removed from `Effects.SubSkills.Overhaul`

We've disabled the following Ability: `Bigger Bombs`, `Blast Mining`, and `Demolitions Expertise`.
We used the following permission: `mcmmo.ability.mining.blastmining.all`
Have i used the wrong permission node?
