### ISSUE TITLE
[Request] Reached max level.

### ISSUE THREAD

**Issue by Remski01** [mcMMO-Dev/mcMMO#3918]
So, 

Could you add something what change the required xp to just `-1` or something else then what the next level actually requires in `/mcstats`as example.

As example, we have a cap level of 550. However, when you skill is `550` it still shows the amount of xp you need for the next level while they have reached the max level...? Its quite confussing in my opinion

I hope you can add or change something what can remove this.

**Comment by Shrek5InTheatres2019** [comment]
Is implemented, please close :)

**Comment by Remski01** [comment]
Thanks <3
