### ISSUE TITLE
Bug: Repair skill will always recover 50% of its max durability without any sub skill.

### ISSUE THREAD

**Issue by LazyGon** [mcMMO-Dev/mcMMO#3919]
The title means, repair skill will always require 2 material to repair item completely.
This will make Repair Mastery meaningless because Super Repair with max rank will recover full durability.
I think recovered durability per one repairing should be 1 / (amount of material to craft).
Bukkit.getRecipeFor(ItemStack item) might be useful to get how many materials are used for repaired item in repair.vanilla.yml
(I wrote above is implementation of mcMMO classic)

server version: Paper version git-Paper-616 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
mcMMO version: 2.1.52

**Comment by nossr50** [comment]
Post the values of your repair config at paste.gg

**Comment by LazyGon** [comment]
https://paste.gg/p/anonymous/7899419dd35a4ebeb9170de21298ff2e

**Comment by LazyGon** [comment]
Method I wrote has already used...
I am embarassed...
I would like to know result of debug on development team side.
Is it working well on environment other than mine?

**Comment by LazyGon** [comment]
In RepairConfig.java:
`
            // Minimum Quantity
            int minimumQuantity = (itemMaterial != null ? SkillUtils.getRepairAndSalvageQuantities(new ItemStack(itemMaterial), repairMaterial, repairMetadata) : config.getInt("Repairables." + key + ".MinimumQuantity", 2));
`
This part may be cause of this bug.
If config has no setting of minimum quantity, amount of need material should always 2.
Please add default config the section of MinimumQuantity.
