### ISSUE TITLE
[Suggestion] Add functionality to the Luck of the Sea Fishing Rod enchantment.

### ISSUE THREAD

**Issue by Talath44** [mcMMO-Dev/mcMMO#3920]
Currently the Luck of the Sea enchantment has no effect while fishing. Would love to see this enchantment do something.

**Comment by Kidyeon** [comment]
Would like to see this as well

**Comment by NoFace851** [comment]
same, that would be cool

**Comment by broccolai** [comment]
This is accounted for while fishing.
