### ISSUE TITLE
McMMo No Exp 

### ISSUE THREAD

**Issue by mcmmoneedhek** [mcMMO-Dev/mcMMO#3926]
I don't get any xp from doing things for the mcmmo plugin

**Comment by Geekerandy** [comment]
Let’s start with the basics from this copypasta directly from the mcMMO discord.

**COMMON PROBLEM TROUBLESHOOTING**
If you are having issues with certain aspects of mcMMO not working run through the following checklist.

-- **Are you running Spigot or Paper?** --

If you aren't or if you don't know, type /version in game and it will tell you. mcMMO requires Spigot or Paper to run, it will not run on CraftBukkit currently.

-- **Are you having an issue where typing commands causes errors or doesn't show anything for mcMMO?** --

Most likely you are not using Spigot or Paper, which are required to run mcMMO.

-- **Skills are not working for you** --

Typically this is a problem with your permissions plugin, remove your permission plugin as an experiment and see if mcMMO suddenly starts working.

-- **Are you running World Guard?** --

If yes, make sure you are using the NEWEST versions of World Guard 7, old versions of World Guard 7 are not compatible with mcMMO.
You must also update your World Edit to the newest version of World Edit 7.

NOTE: You don't need to do this if you aren't using World Guard.

-- **Are there any errors in your server console?** --

If yes post those errors and someone will be able to help you shortly.

-- **Are you using Classic mcMMO?** --

Classic's code is quite different from mcMMO, please let us know if you are using classic.

On a side note, make sure mcMMO is up to date.
