### ISSUE TITLE
Bug: /mining command shows wrong stats of double drop

### ISSUE THREAD

**Issue by LazyGon** [mcMMO-Dev/mcMMO#3927]
`        if (canDoubleDrop) {
            messages.add(getStatMessage(SubSkillType.HERBALISM_DOUBLE_DROPS, doubleDropChance)
                    + (isLucky ? LocaleLoader.getString("Perks.Lucky.Bonus", doubleDropChanceLucky) : ""));
            //messages.add(LocaleLoader.getString("Mining.Effect.DropChance", doubleDropChance) + (isLucky ? LocaleLoader.getString("Perks.Lucky.Bonus", doubleDropChanceLucky) : ""));
        }`
This is written code in MiningCommand.java
SubSkillType.HERBALISM_DOUBLE_DROPS should be SubSkillType.MINING_DOUBLE_DROPS

If this issue is already known, please ignore and close issue.

**Comment by nossr50** [comment]
@LazyGon Good catch, I'll go fix.

**Comment by nossr50** [comment]
Ah so this actually does not show the wrong stats, but it shows the wrong message (the text right before the stats)

Effectively this bug is harmless, but I'll fix anyways
