### ISSUE TITLE
Unable to brew mcmmo extended and level II potions

### ISSUE THREAD

**Issue by ofc2000alex** [mcMMO-Dev/mcMMO#3929]
Whenever i try to convert my haste potions into haste II or haste extended potions, by adding redstone or glowstone, the potions turn from haste potions into thick potions(useless potions). The same holds true for other mcmmo special potions like mining fatigue. Additionally, I am unable to turn splash water bottles into splash potions of haste or other mcmmo splash potions. The ingredient simply does not brew into the splash water bottles. Is this a bug, or have you never been able to make haste II or haste extended or splash potions of haste?

**Comment by nossr50** [comment]
Alchemy is getting rewritten in 2.2, so I'm closing this issue as all the current Alchemy code is going bye bye
