### ISSUE TITLE
[Bug] Some skills are not gaining exp after level 6

### ISSUE THREAD

**Issue by Desnecessaulo** [mcMMO-Dev/mcMMO#3936]
I made a spigot server in version 1.13.2, I bought and installed mcMMO (version 2.1.61) everything as it should be done, however some skills are only gaining xp until level 6 after that the player does not receive more experience.
The skills that I noticed that have this problem are: Swords and Bows

**Comment by nossr50** [comment]
the first 5 levels get huge amounts of bonus XP to make the first skill unlocks faster, this isn't documented in game though, in game documentation will improve soon
