### ISSUE TITLE
Experiencing this issue in latest version

### ISSUE THREAD

**Issue by PengBread** [mcMMO-Dev/mcMMO#3942]
Previously I've reported this one similar issue for the older version. The latest version also pops this issue. From what I've see seems like its related to bleed timer. To replicate the issue, I am unsure how to replicated it.
https://pastebin.com/Bujf5dM8

**Comment by nossr50** [comment]
I'm not sure if this is because of mcMMO or another plugin modifying the Bleed task list while its being iterated. Do you run any plugins that hook into mcMMO?

**Comment by PengBread** [comment]
GuiMcMMO Redeem and mythicmobs only.

**Comment by nossr50** [comment]
to be honest, I'm not able to replicate this myself so I'm a bit stumped, it shouldn't be causing this error from anything mcMMO is doing as far as I can tell
