### ISSUE TITLE
Call of the Wild and Config Error

### ISSUE THREAD

**Issue by Pabi7** [mcMMO-Dev/mcMMO#3943]
I just switched over to 1.14 and downoaded the latest mcmmo file as of June 3rd. I started up my server and got this error: https://pastebin.com/GidtahwR

So far I've double checked my config and nothing seems out of order there. Any help would be greatly appreciated. First time posting.

**Comment by nossr50** [comment]
Try removing the .yml files found in /plugins/mcMMO

**Comment by Pabi7** [comment]
This worked! Thank you good sir!
