### ISSUE TITLE
Everytime I make changes to my advanced.yml File and Restart the server, It deletes all my changes to the file and resets it.

### ISSUE THREAD

**Issue by Ninjatops** [mcMMO-Dev/mcMMO#3945]
I have tried many different spacing methods and getting It debugged by a Server admin, But nothing has stopped it from resetting itself.

**Comment by nossr50** [comment]
mcMMO doesn't overwrite existing settings, could you zip up your /plugins/mcMMO directory and email it to me at nossr50@gmail.com so I can take a look at what might be going on

also provide me with a copy of a log file from when this last happened

**Comment by Ninjatops** [comment]
Did you check it out?

**Comment by nossr50** [comment]
I had no idea you emailed me, I get dozens of emails a day

What email did you use to send it?

**Comment by Ninjatops** [comment]
Ninjatops12@gmail.com

**Comment by nossr50** [comment]
Which edits are you making to advanced.yml exactly? the file is quite large so I can't really tell by skimming it.

**Comment by broccolai** [comment]
Cannot reproduce, if this is still happening, please update this issue.
