### ISSUE TITLE
Could not pass event PlayerInteractEvent to mcMMO v2.1.36

### ISSUE THREAD

**Issue by LegalSmeagol** [mcMMO-Dev/mcMMO#3946]
Seems to be occurring after update 1.14.2. Both MCMMO and WorldGuard are up to date.

**Comment by nossr50** [comment]
2.1.36 is an extremely outdated version that does not have 1.14 support, please update mcMMO

**Comment by LegalSmeagol** [comment]
That's strange as I downloaded 2.1.69 about 10 minutes ago to see if the issue was with the previous version I had. My version should be 2.1.69 as the mcMMO.jar is a fresh file.

**Comment by LegalSmeagol** [comment]
The download located on BlackSpigot isn't up to date. I freshly installed mcMMO and it still does not work.

**Comment by Draycia** [comment]
Are you actually running a cracked / leaked version?

**Comment by nossr50** [comment]
Please don't mention leak sites.

**Comment by mrfloris** [comment]
Asking support for pirated version, classic.
