### ISSUE TITLE
Learning new skill???

### ISSUE THREAD

**Issue by cheesepufftyler** [mcMMO-Dev/mcMMO#3948]
every player is getting this then goes away after it gets full. Running 2.1.71. MC spigot 1.14.2
![1](https://user-images.githubusercontent.com/19861859/59154997-b88e6c80-8a4c-11e9-84cc-989eef5b93dc.png)

**Comment by nossr50** [comment]
read the changelog for https://www.spigotmc.org/resources/official-mcmmo-original-author-returns.64348/update?update=280342
