### ISSUE TITLE
Mcmmo Classic bug? 

### ISSUE THREAD

**Issue by slvlr** [mcMMO-Dev/mcMMO#3965]
Smelting is a child skill (secondary) skill that is leveled by adding the mining and repair skills together, then dividing by 2 to get the smelting skill in Mcmmo.
The second smelt ability is a thing that with 1000 smelting skill, gives 2 products for every imput smelted by a player
https://mcmmo.fandom.com/wiki/Smelting
McMMO Wiki
Smelting
Smelting is a child skill of Mining and Repair. The effective Smelting level is the average of the parent skill levels. Smelting was the first child skill added to McMMO. Fuel Efficiency is a...

The Furnaces have the automatic privatization that maxes at 20 furnaces
and when this occurs, x<20 furnaces, there is no second smelt from mcmmo
but furnaces in excess of 20<x will yield the second smelt at the amount stated by a players "smelting" skill
Essentially, for players cooking stuff, the smelting skill doesnt work for the max number of countable furnaces

Server Type (Spigot/Paperspigot/etc): Paperspigot

Server Version (using /ver): Paperspigot 1.14.2 build 97

Relevant plugins (Delete if this isn't needed): Jobs Reborn, Mcmmo

**Comment by nossr50** [comment]
can't really solve that on mcMMO's end
