### ISSUE TITLE
Timings Report mcMMO event for PlayerStatisticIncrementEvent

### ISSUE THREAD

**Issue by Pabi7** [mcMMO-Dev/mcMMO#3980]
Not sure what is happening here:

mcMMO::Event: c.g.n.l.PlayerListener (PlayerStatisticIncrementEvent

Timings: https://timings.aikar.co/?id=2f1cfd0cc54f4169a86f4defaa15ae57

**Comment by broccolai** [comment]
This timings link has expired, if it's still an issue please comment on this issue with a new link or join the discord.
