### ISSUE TITLE
In 1.14.3 when someone enters PARTY, it crashes the server...

### ISSUE THREAD

**Issue by MrKiller01** [mcMMO-Dev/mcMMO#3984]
As I said, a member on our server initiated party and asked me to join, that is when the server crashed, halted and never got out of it.
part 1: https://pastebin.com/BXjDDy3e
and part 2: https://pastebin.com/dYvQXTYb

I hope I have all info here.....

**Comment by t00thpick1** [comment]
@nossr50 This looks like 2.x

**Comment by electronicboy** [comment]
This was a vanilla issue which has since been patched in the server
