### ISSUE TITLE
Players not lvl;ing in some skills

### ISSUE THREAD

**Issue by vox4455** [mcMMO-Dev/mcMMO#3985]
Running updated mcmmo jar, cmi, quickshopreremake, coreprotect, illegalstack. on minecraft 1.14.3. 

everything is updated and using the default config for mcmmo and most of the other plugins, not seeing any errors in counsel.

**Comment by nossr50** [comment]
Typically this is a permission issue
Which skills are they unable to level?
Which version of mcMMO?

**Comment by broccolai** [comment]
If you're still having this issue, comment with more information or join the discord for support
