### ISSUE TITLE
/party invite kicks the player.

### ISSUE THREAD

**Issue by FeroxDrood** [mcMMO-Dev/mcMMO#3987]
Hello,

When my players typ /party invite they get kicked to the lobby.

_Running paper spigot 1.13.2 build 637

Running the latest version of Overhauled McMMO 2.1.96_

**The error below is the error that appears on the server they were kicked off.**
https://pastebin.com/tQJaj8wv

**The error below is the error that appears in the bungee console when the player is kicked**
https://pastebin.com/BQTBvxHs

**Comment by nossr50** [comment]
Try using just mcMMO and see if you can reproduce the error

**Comment by broccolai** [comment]
Cannot reproduce
