### ISSUE TITLE
When compiling 

### ISSUE THREAD

**Issue by DrbLOXoG** [mcMMO-Dev/mcMMO#4005]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project mcMMO: Compilation failure: Compilation failure:
[ERROR] error: Source option 6 is no longer supported. Use 7 or later.
[ERROR] error: Target option 6 is no longer supported. Use 7 or later.

**Comment by nossr50** [comment]
User resolved this error on discord
