### ISSUE TITLE
Question to McMMOAPI

### ISSUE THREAD

**Issue by Pyario** [mcMMO-Dev/mcMMO#4014]
Does the McMMO-Api have a function to interrogate when fixing something on the iron block if it has a specific name to cancel it?

If not, would it be possible to implement? Because I'm just programming a CustomItem which can degrade 3x3x1 and should be fixable.

Best Regards,

Pyario

**Comment by electronicboy** [comment]
McMMOPlayerRepairCheckEvent sounds like what you're looking for?

**Comment by Pyario** [comment]
Yes, i think. Thanks.

**Comment by Pyario** [comment]
is a query for the skills of a skill in Api? So when I mine with my pickaxe, the 3x3 declines. And if then the SuperBreaker uses the pickaxe disappears? Is there an event to cancel custom items?

**Comment by Pyario** [comment]
I found it. // Closed
