### ISSUE TITLE
BleedTimerTask is causing a ConcurrentModificationException

### ISSUE THREAD

**Issue by Deathinflames** [mcMMO-Dev/mcMMO#4019]
I noticed this in the console after updating to mcMMO v2.1.100 

https://pastebin.com/raw/hdJFzykG

It looks very similar to this now closed ticket https://github.com/mcMMO-Dev/mcMMO/issues/2173

This server is running Paper version git-Paper-639 (MC: 1.13.2)
mcMMO v2.1.100

**Comment by electronicboy** [comment]
Can you reproduce this consistently? I thought that I'd solved the only risk of this happening, do you have any other plugins that might interact with mcmmo?

**Comment by Deathinflames** [comment]
I've not been able to re-produce it consistently. I did notice that it happened with a player that has a really high sword level, perhaps that could be related?

We do have quite a few plugins that "hook" into mcMMO but we haven't made any radical functionality yet beyond that of the default configurations. Those plugins are PlaceholderAPI, FeatherBoard, MMOItems, MythicMobs, Jobs Reborn, and QuestCreator.

It seems at the time of the incident, the player with the really high sword level was killing villagers for a quest and i do believe they were using a MMOItems sword.

**Comment by electronicboy** [comment]
![image](https://user-images.githubusercontent.com/1228900/63134614-2497ce80-bfc2-11e9-8d67-8ee92ddafe58.png)
(From https://papermc.io/forums/t/mcmmo-error-in-console/1544/)

**Comment by electronicboy** [comment]
as per #4028, should be fixed in https://github.com/mcMMO-Dev/mcMMO/commit/5ea2c493e8f1b92ed0731a27a5c5a2803bf0f2ba

**Comment by electronicboy** [comment]
The underlying issue has been fixed, it's no longer possible to trigger this in mcmmo itself; The only real risk I can see is that mmoitems is triggering damage on some other player other than what rupture is trying to damage, or some plugin has broken our flag somehow

There is very little we can do around premium plugins, we don't have access to their source to see what is going on, nor do I have the ability to test them
