### ISSUE TITLE
Plugin Command Interfere

### ISSUE THREAD

**Issue by UnknowngrimR** [mcMMO-Dev/mcMMO#4020]
I've been having so many issues with the plugins I've been using because of their aliases. I use three plugins that all have /p which are MCMMO, ProCosmetics, and PlotSquared. I've looked into the bukkit solution which was, "PluginName:command," but it does not seem to work with some of the plugins, ProCosmetics requires me to do /pc open and I cannot use an alias plugin since it would just open up the MCMMO party chat, is there any other solution to this? PlotSquared is normally fixed with the alias plugin so there's nothing too wrong with that.

**Comment by Tautrollet** [comment]
I have the same issue

**Comment by andris155** [comment]
I have the same issue.

**Comment by nossr50** [comment]
( This is copy pasted from our discord bot command )

Three ways you can create command aliases are the oldschool bukkit commands.yml file in the root server directory, the CMI  plugin, or the  EssentialsX  plugin.
For a specific example, the /repair command can be given a custom command through usage of the configuration file located at .. \plugins\Essentials\custom.txt

•  Information on the commands.yml file can be found here: https://bukkit.gamepedia.com/Commands.yml
• EssentialsX can be found here: https://www.spigotmc.org/resources/essentialsx.9089/
 -- Dev builds here: https://ci.ender.zone/job/EssentialsX/
 -- GitHub here: https://github.com/EssentialsX/Essentials
• CMI can be found here: https://www.spigotmc.org/resources/cmi.3742/

Notes:
CMI is a closed source premium plugin, whereas EssentialsX is free, and open source.
The commands.yml file is the recommended method for creating command aliases; but you're welcome to use plugins instead. CMI and EssentialsX are not the only plugins which do this.

**Comment by andris155** [comment]
The commands.yml works for PlotSqaured /p command, but this method or mcMMO breaks command tab complete.
