### ISSUE TITLE
mcMMO Performance Issue

### ISSUE THREAD

**Issue by Hyronymos1337** [mcMMO-Dev/mcMMO#4023]
Performance Issue: https://timings.aikar.co/?id=5f88dde3c5be48e1916b80470dd0cdaa

mcMMO overhaul version: 2.1.100

**Comment by electronicboy** [comment]
I was going to reply to this earlier, but figured I'd wait until I had more time to look into it as I couldn't see anything; I cannot see any form or indication that mcmmo is causing performance issues? if you wanna highlight the issue more clearly, we could look into this, but as-is, I can't see anything wrong outside  of your server suffering badly in general
