### ISSUE TITLE
Fishing quantities

### ISSUE THREAD

**Issue by NoFace851** [mcMMO-Dev/mcMMO#4024]
So, i have a problem with quantities of items in fishing. If i type for example

REDSTONE_BLOCK:
Amount: 64
XP: 500
Rarity: LEGENDARY

when i go ingame, i should get 64 blocks of redstone, but i only got 56, same with other items:

NAUTILUS_SHELL:
Amount: 4
XP: 300
Rarity: RARE

got 2 nautilus shells instead of 4

SPIDER_EYE:
Amount: 16
XP: 300
Rarity: RARE

got 11 spider eyes instead of 16

how do i fix this please? And if this is intentional, is there any way i can disable this so i can get EXATCLY the number of items i specified in treasures.yml?

**Comment by nossr50** [comment]
I'll be looking into this ASAP and I will get back to you with the results of my investigation!

**Comment by NoFace851** [comment]
tested and fixed
