### ISSUE TITLE
mcMMO blacklisting worlds not working

### ISSUE THREAD

**Issue by 0fficerMike** [mcMMO-Dev/mcMMO#4025]
When i go from a non-disabled world to a disabled world my scoreboard is still there.

**momshroom:** Scoreboards are surprisingly persistent.  Is the plugin actually giving xp/abilities or do you just have scoreboards?

**electroniccat:** mcmmo just seemingly doesn't care if they're blacklisted there

**Comment by nossr50** [comment]
Yeah the scoreboard code is messier than I thought, either I need to rewrite it which would delay other important updates or I implement a hacky fix...
