### ISSUE TITLE
Rupture: Cannot add task while iterating timers

### ISSUE THREAD

**Issue by PengBread** [mcMMO-Dev/mcMMO#4028]
Hello, I'm getting error on the latest McMMO version.

https://pastebin.com/2C4qD6h1

The server is on Paper spigot 1.13.2 latest.

**Comment by Bayminkk** [comment]
the same issue on paperspigot 1.13.2 latest

**Comment by nossr50** [comment]
@electronicboy Has a solution prepared for this once he gets some sleep, should be fixed within the next day or two hopefully!

**Comment by electronicboy** [comment]
Should be fixed in https://github.com/mcMMO-Dev/mcMMO/commit/5ea2c493e8f1b92ed0731a27a5c5a2803bf0f2ba
