### ISSUE TITLE
EntityDamageByEntityEvent

### ISSUE THREAD

**Issue by cappe12345** [mcMMO-Dev/mcMMO#4036]
Console	: [17:19:40] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to mcMMO v2.1.103
Console	: org.bukkit.event.EventException: null
Console	: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-798ea6a-2012f1e]
Console	: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-798ea6a-2012f1e]
Console	: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) [spigot.jar:git-Spigot-798ea6a-2012f1e]
Console	: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) [spigot.jar:git-Spigot-798ea6a-2012f1e]
Console	: 	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:221) [spigot.jar:git-Spigot-798ea6a-2012f1e]
Console	: 	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:893) [spigot.jar:git-Spigot-798ea6a-2012f1e]
Console	: 	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:792) [spigot.jar:git-Spigot-798ea6a-2012f1e]
Console	: 	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:925) [spigot.jar:git-Spigot-798ea6a-2012f1e]
Console	: 	at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity0(EntityLiving.java:1620) [spigot.jar:git-Spigot-798ea6a-2012f1e]
Console	: 	at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity(EntityLiving.java:1073) [spigot.jar:git-Spigot-798ea6a-2012f1e]
Console	: 	at org.bukkit.craftbukkit.v1_14_R1.entity.CraftLivingEntity.damage(CraftLivingEntity.java:245) [spigot.jar:git-Spigot-798ea6a-2012f1e]
Console	: 	at com.gmail.nossr50.util.skills.CombatUtils.dealNoInvulnerabilityTickDamageRupture(CombatUtils.java:586) [mcMMO.jar:?]
Console	: 	at com.gmail.nossr50.runnables.skills.BleedTimerTask.run(BleedTimerTask.java:118) [mcMMO.jar:?]
Console	: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) [spigot.jar:git-Spigot-798ea6a-2012f1e]
Console	: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot.jar:git-Spigot-798ea6a-2012f1e]
Console	: 	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1022) [spigot.jar:git-Spigot-798ea6a-2012f1e]
Console	: 	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot.jar:git-Spigot-798ea6a-2012f1e]
Console	: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970) [spigot.jar:git-Spigot-798ea6a-2012f1e]
Console	: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815) [spigot.jar:git-Spigot-798ea6a-2012f1e]
Console	: 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Console	: Caused by: java.lang.IllegalStateException: Cannot add task while iterating timers!
Console	: 	at com.gmail.nossr50.runnables.skills.BleedTimerTask.add(BleedTimerTask.java:182) ~[?:?]
Console	: 	at com.gmail.nossr50.skills.swords.SwordsManager.ruptureCheck(SwordsManager.java:78) ~[?:?]
Console	: 	at com.gmail.nossr50.util.skills.CombatUtils.processSwordCombat(CombatUtils.java:64) ~[?:?]
Console	: 	at com.gmail.nossr50.util.skills.CombatUtils.processCombatAttack(CombatUtils.java:322) ~[?:?]
Console	: 	at com.gmail.nossr50.listeners.EntityListener.onEntityDamageByEntity(EntityListener.java:429) ~[?:?]
Console	: 	at sun.reflect.GeneratedMethodAccessor264.invoke(Unknown Source) ~[?:?]
Console	: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
Console	: 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
Console	: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-798ea6a-2012f1e]
Console	: 	... 19 more

**Comment by electronicboy** [comment]
Duplicate of #4028
