### ISSUE TITLE
1.14 working station blocks trigger ability on right click

### ISSUE THREAD

**Issue by kaonashi97** [mcMMO-Dev/mcMMO#4050]
Hello,

I've using mcMMO on my server heavily with 1.14 and I ran into this issue that on right click a barrel with empty hand or some tool it will activate my ability. This applies for all interacting blocks added with 1.14 (barrel, stonecutter, smoker, ...).
Using mcMMO 2.1.105-SNAPSHOT.

Thanks for making this awesome plugin. Love it <3
~Kaonashi

**Comment by nossr50** [comment]
I will fix this shortly 😊

**Comment by kaonashi97** [comment]
Hey,
I've updated to 2.1.108-snapshot just a couple minutes ago. Seems that this issue is not fully fixed. On smoker, blast furnace and stone cutter my abilities will still activate when holding a tool or with empty hand. Can you please review this?

Thanks
~Kaonashi
