### ISSUE TITLE
McMMO / DiscordSRV

### ISSUE THREAD

**Issue by ZEROOblivious** [mcMMO-Dev/mcMMO#4057]
Can we make it to where Admin Chat is not seen via Discord SRV?

Discord Logs the chat if you toggle the chatroom
But if you do /a it won't toggle it.

DiscordSRV does not log/detect party chat at all?  So would it be possible with /A  ?

**Comment by ZEROOblivious** [comment]
Has been posted on DiscordSRV's GitHub too.

https://github.com/DiscordSRV/DiscordSRV/issues/542

**Comment by nossr50** [comment]
I'm not sure of a practical fix we could employ other than DiscordSRV adding support for mcMMO and including an option to filter out such messages,

**Comment by Vankka** [comment]
https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/java/github/scarsz/discordsrv/DiscordSRV.java#L823 here's DiscordSRV's implementation. Prehaps setting the party/admin 'toggle' on before sending the event and then turning it off right after it has been sent

**Comment by electronicboy** [comment]
I don't have discordsrv setup and not really super intent on tryna install this myself to test; What is the replication steps, and behavior seen/expected?

To my understanding, you're saying that toggling admin/party chat on and chatting passes it through to discord? or?

**Comment by Vankka** [comment]
if you have admin/party chat toggled on, it will be ignored 
however if you send a message by running the command, eg. `/teamchat hello`, it won't be ignored

That's at least how i've understood this, and it makes sense because DiscordSRV checks if either of those are toggled & then ignores it

**Comment by electronicboy** [comment]
I'm somewhat ill, so not really looked too deeply, but that doesn't seem like it would be the case; I have spotted a flaw in dsrv's mcmmo hooks, however

**Comment by Vankka** [comment]
Link to DiscordSRV dev builds in case you'd like to try to reproduce: http://nexus.scarsz.me/service/local/artifact/maven/redirect?r=snapshots&g=com.discordsrv&a=discordsrv&v=LATEST

**Comment by broccolai** [comment]
Is this still an issue? Couldn't reproduce on a test server
