### ISSUE TITLE
ServerTransfer MCMMO stats gone

### ISSUE THREAD

**Issue by SteinebachM** [mcMMO-Dev/mcMMO#4061]
I recently worked on a server transfer and the MCMMO stats are all gone, atleast ingame it says i have no skills in anything. Now the MCMMO.users file is still intact and that information is still all good. I also transfered all the SQL data from the old database to the new one but still it shows that I have no skills in anything.

So the mcmmo.users file has all the correct data and my SQL database has all the correct data too but none of it is showing ingame. What am I missing???

**Comment by nossr50** [comment]
If you are using FlatFile then you need to only xfer mcmmo.users

However if you were using SQL, you need to xfer the MySQL/MariaDB instead and then go into config.yml and setup the SQL options to point to the location of the new DB
