### ISSUE TITLE
Gaining herbalism exp on placing bamboo sticks

### ISSUE THREAD

**Issue by kaonashi97** [mcMMO-Dev/mcMMO#4063]
Hello,
I'm using 2.1.108-snapshot and ran into a little issue with the herbalism skill.

When placing bamboo sticks the upcoming block will gain skill experience on breaking.
As with other skills this should not happen in my opinion, like placed dirt by players will not give you experience when digging.

~Kaonashi

**Comment by nossr50** [comment]
Not able to replicate
