### ISSUE TITLE
Resting Config Files On Server Restart

### ISSUE THREAD

**Issue by GreenGhostYT** [mcMMO-Dev/mcMMO#4075]
This problem has been talked about before but I'm not finding a fix for it. I guess this was a 2014 problem but im experiencing it on my Minecraft 1.12.2 paper server. Uppon editing my yml files (I'm trying to take out Disarm) they reset. I stop the server, edit, and start the server and it loads up fine but upping checking the config it is back to the defaults. I looked in the config and I'm wondering if Config_Update_Override should be false and if this is the problem. Ik what I'm doing as far as space-sensitive and all that beginner stuff I don't believe this is a problem. Thanks

**Comment by electronicboy** [comment]
Wrong repo? We don't support 1.12.2, I've also yet to hear of people having such issues outside of their editors not saving the files properly
