### ISSUE TITLE
Override_Vanilla_Treasures: false ignored

### ISSUE THREAD

**Issue by Tarluin** [mcMMO-Dev/mcMMO#4080]
Setting Override_Vanilla_Treasures: false in config.yml still uses the treasures.yml for fishing loot.

This server is running CraftBukkit version git-Spigot-56f8471-7554e08 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

[mcMMO] Enabling mcMMO v2.1.110

There are definitely items from treasures.yml showing up but it may be a combination of vanilla loot and mcmmo loot.

**Comment by electronicboy** [comment]
Setting that to false means that it won't replace vanilla fishing treasures in favor of its own loot/salmon, this does not disable mcmmo's own fishing mechanism, you would wanna remove the fishing treasure hunter permission or disable fishing drops for that
