### ISSUE TITLE
Trouble compiling 1.4.06 Rerelease (Minecraft 1.7.10)

### ISSUE THREAD

**Issue by Shinare-I** [mcMMO-Dev/mcMMO#4081]
Hello,
I need to add/modify some files in the plugin to make it work with a mod. However, this requires compiling the plugin once the modifications are done.
I have no previous experience with Maven, so this is all pretty new.
The modifications were easy to make, but I have run into some issues with the compilation.
If I understood it right, the bukkit repository is down now. So I referred to spigot repo instead. However, this does not have 1.7.10 either, and I had to try if 1.8 is similar enough. 
I do not understand much of the logic in the repositories, and so I cannot just find the 1.7.10-R0.1 files in the web and make own repository.

Also the turt2live repository seems to be down, but it also didn't seem to be too important so I tried just removing it. I did not see any issues with that in compiling.

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project mcMMO: Compilation failure: Compilation failure: 
[ERROR] /home/shinare/Documents/MCMMO/Testrun_8/src/main/java/com/gmail/nossr50/skills/fishing/FishingManager.java:[107,30] error: reference to getTargetBlock is ambiguous
[ERROR]   both method getTargetBlock(HashSet<Byte>,int) in LivingEntity and method getTargetBlock(Set<Material>,int) in LivingEntity match
[ERROR] /home/shinare/Documents/MCMMO/Testrun_8/src/main/java/com/gmail/nossr50/listeners/PlayerListener.java:[239,36] error: reference to getTargetBlock is ambiguous
`

Here is what it is complaining about now, but I am pretty sure it will have more issues once this is solved (I played a bit with another copy of the source, which led to this assumption)

It would be great if I could get help in compiling this plugin.
Thanks,
Shinare

**Comment by Shinare-I** [comment]
What I forgot to mention in first post, is that I tried fixing the error with the tips from https://www.spigotmc.org/threads/the-method-gettargetblock-hashset-byte-int-is-ambiguous-for-the-type-player.50606/
However, it only produced another kind of error, if I replaced the part of code with either getTargetBlock((HashSet<Byte>) null, 100) or getTargetBlock((Set<Material>) null, 100)

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project mcMMO: Compilation failure: Compilation failure: 
[ERROR] /home/shinare/Documents/MCMMO/Testrun_8/src/main/java/com/gmail/nossr50/skills/fishing/FishingManager.java:[107,47] error: cannot find symbol
[ERROR]  class FishingManager
[ERROR] /home/shinare/Documents/MCMMO/Testrun_8/src/main/java/com/gmail/nossr50/listeners/PlayerListener.java:[239,53] error: cannot find symbol

**Comment by electronicboy** [comment]
This issue tracker is for issues with the supported version of mcmmo, not for support with compiling legacy versions of the software; The issue is that you're building against a different version of the server than the version of the source you're using, which will create it's own set of issues
