### ISSUE TITLE
Cooking a pickaxe with enchantments

### ISSUE THREAD

**Issue by INoaahGuy** [mcMMO-Dev/mcMMO#4082]
Cooking a pickaxe with enchantments on it to make a flux pickaxe results in a flux pickaxe with no enchantments

**Comment by Momshroom** [comment]
What version of mcMMO?  What server software?  Any errors on startup or when the pick is smelted?

**Comment by electronicboy** [comment]
This feature was removed a good while ago, mcmmo doesn't touch this anymore
