### ISSUE TITLE
Players are still leveling up skills after they hit level 100

### ISSUE THREAD

**Issue by skerit** [mcMMO-Dev/mcMMO#4084]
So in my settings `RetroMode - Enabled` is set to false, but players are still able to level up their skills after they hit level 100.

2 players are already at +150 in Archery, 1 has level 200 in Axes, 2 are just getting over lvl 100 in mining.

I never enabled classic mode, so I don't know what's going on there?

**Comment by Remski01** [comment]
Server version & mcMMO version would be nice.

**Comment by Draycia** [comment]
RetroMode controls scaling. That does not determine if there is a level cap or not. By default there is not one. I'm on mobile so I cant easily check but i believe there is a different setting for that.

**Comment by Momshroom** [comment]
There is a setting for level caps.  The “extra” levels your players have provide only cosmetic benefit (bragging rights) or, possibly longer super abilities.   The scaling range is just where the benefits are.
