### ISSUE TITLE
 No-Treasure IN callEvent(PlayerFishEvent), only XP in Skill

### ISSUE THREAD

**Issue by Escanor2019** [mcMMO-Dev/mcMMO#4095]
I am rebuilding PlayerFishingEvent

Everything was going well.

Mcmmo was giving xp, and spawning the kraken.

however mcmmo does not reward players.

but the message 'Hmmmm .... you found ....' appears

It works normal if for example I expect the fish to bite naturally and pull, what I don't understand is how mcmmo treats natural fishing events with artificial fishing events.

I tried to replicate the construction of natural fishing events and had no result.

**Comment by electronicboy** [comment]
This version of mcmmo no longer contains the kraken, so Wrong repo;
But, the caller of the event gives the item to the player, mcmmo just manipulates the item inside the event
