### ISSUE TITLE
drop in callEvent(PlayerFishingEvent) and mcmmo treasure

### ISSUE THREAD

**Issue by Escanor2019** [mcMMO-Dev/mcMMO#4098]
I am trying to call PlayerFishingEvent, but this one doesn't drop item

I put to manually add the fish to the inventory, so everything was ok, but now the problem is that mcmmo does not reward with its treasures despite receiving the xp in mcmmo and minecraft xp

I asked the mcmo developers and he said:
This version of mcmmo no longer contains the kraken, so Wrong repo;
But, the caller of the event gives the item to the player, mcmmo just manipulates the item inside the event

look my code
`<code>
net.minecraft.server.v1_9_R2.ItemStack it = new net.minecraft.server.v1_9_R2.ItemStack(Item.getById(349),1,0);

EntityItem entityitem = new EntityItem(MinecraftServer.getServer().getWorld());
entityitem.setItemStack(it);

Entity caugthFishBEntity = entityitem.getBukkitEntity();

eth.world.addEntity(entityitem);
fish.setTicksLived(500);

Entity caugthFishBEntity = entityitem.getBukkitEntity();
PlayerFishEvent pfe1 = new PlayerFishEvent(p, caugthFishBEntity, fish, PlayerFishEvent.State.CAUGHT_FISH);
getServer().getPluginManager().callEvent(pfe1);

pfe.setExpToDrop(6);
p.getInventory().addItem(new ItemStack(Material.RAW_FISH,1,(short)1));
</code>`

**Comment by electronicboy** [comment]
Please don't create new issues, especially when you're not actually using this software; But, as per the last issue, *you* need to give the item to the player after the event is fired, that item needs to be the one that was passed into the event, otherwise you're not going to see any changes
