### ISSUE TITLE
Sweet Berry Bush XP too high

### ISSUE THREAD

**Issue by GiraffeCubed** [mcMMO-Dev/mcMMO#4099]
Sweet Berry Bushes currently give 300 Herbalism XP when broken (No XP for right click harvesting). In comparison to other crops/farmables, this is very high, as Sweet Berry Bushes grow rather fast, just a couple of ingame days. In order to balance this out, I've reduced this amount to 75 XP in my own experience.yml, and I suggest that it is reduced in the default experience.yml too. As a bonus, XP for right click harvesting berries would be sweet! (☞ﾟヮﾟ)☞

**Comment by nossr50** [comment]
Fixed
