### ISSUE TITLE
Archery Damage is Very High at low levels

### ISSUE THREAD

**Issue by rptallman** [mcMMO-Dev/mcMMO#4102]
On default settings, standard bows do nearly double damage at Archery level 6. In this screenshot, I shot the creeper once with a fully cocked bow and it's health came down to 1. 
![image](https://user-images.githubusercontent.com/43195764/72227773-8f433b00-355d-11ea-86f0-31a9f4f60d2a.png)

I'm running:
- MineOS Spigot (1.14.4)
- MCMMO 2.1.110
No other server mods

Steps to reproduce:
1. Create fresh Spigot server with mcMMO 2.1.110 or 2.1.111
2. Kill some mobs with a bow to get to level 1 and activate Skill Shot ability (which increases damage)
3. Shoot a mob and observe how much damage is being done (I used [ToroCrafts Damage Indicators](https://nexus-mods.com/minecraft-mod/torocrafts-damage-indicators-mod-1-14-4-1-12-2/) for fabric)

I'm guessing the source of the error is within Skill Shot because there is no damage boost until the Archery skill is learned and Skill Shot is given.

edit: the high damage is still present on mcMMO 2.1.111 (most recent version)

**Comment by Eris7090** [comment]
I just wanna comment saying I was literally just thinking "Why am I one shoting everything" and then I saw this in discord

**Comment by nossr50** [comment]
Fixed
