### ISSUE TITLE
Feature: Add glass breaking option for Berserk.

### ISSUE THREAD

**Issue by andrewkm** [mcMMO-Dev/mcMMO#4106]
Long ago we wanted to add glass breaking to Berserk, and as mcMMO was not active we ended up forking and doing it ourselves.

However maintaining a fork now with all the upstream activity would be extremely annoying.

Can we please revisit this, and potentially add it <3
Lots of users have been dying for a quick way to break glass. It’s like the one thing missing from Minecraft that I’ve been getting begged for throughout the years lol.

Old PR: https://github.com/mcMMO-Dev/mcMMO/pull/3169 https://github.com/mcMMO-Dev/mcMMO/pull/3169/commits/37280856d5f509d965b7d344b0f4f2caf6ccad88

Above commit would of course need some work such as plugin.yml perms, glass pane type splits, etc. It’s just an example that I found and thought I’d link :)

**Comment by andrewkm** [comment]
Using this workaround for now.
Added under excavation in experience.yml

https://pastebin.com/iND3E4vX

**Comment by nossr50** [comment]
Done
