### ISSUE TITLE
Plugin attempted to register task while disabled

### ISSUE THREAD

**Issue by andrewkm** [mcMMO-Dev/mcMMO#4108]
Randomly caught this while stopping server.

https://pastebin.com/JHEytqAV
Was simply running some tests with berserk, and was in the middle of my berserk ability activated. Ran a stop through console and got the above. Thought I'd report.

**Comment by nossr50** [comment]
The exception is mostly harmless but we can implement a fix to help clean up the logs

**Comment by andrewkm** [comment]
Closing as I do not recall it happening since.
