### ISSUE TITLE
Top kelp does not give herbalism EXP.

### ISSUE THREAD

**Issue by andrewkm** [mcMMO-Dev/mcMMO#4110]
Report made was:

> Break kelp 1 piece at a time from top to bottom, get 0 herbalism.
> Only get herbalism exp when breaking from the bottom/middle of the kelp.

Confirmed bug.
Breaking from bottom get correct amount.
Breaking from middle get correct amount.
Break from top to bottom, don't get any exp.

No idea why anyone would break from top to bottom lmfao but hey, it's a bug. *shrug*

**Comment by nossr50** [comment]
I'll see if I can correct this soon

**Comment by andrewkm** [comment]
Any news on this one @nossr50
