### ISSUE TITLE
McMMO "Repair Event" Api

### ISSUE THREAD

**Issue by Pyario** [mcMMO-Dev/mcMMO#4123]
Can the api query that a custom item cannot be canceled via the iron block? I can not find anything ..

Best Regards, 

Pyario

**Comment by electronicboy** [comment]
https://github.com/mcMMO-Dev/mcMMO/blob/f7eb06e80b552fb3dcd2f0690e7a43dd7611691c/src/main/java/com/gmail/nossr50/events/skills/repair/McMMOPlayerRepairCheckEvent.java
