### ISSUE TITLE
[request] Shield Repair

### ISSUE THREAD

**Issue by thunderlight411** [mcMMO-Dev/mcMMO#4130]
Its self explaining i think
But can we get the possibilitie for repairing shields?

**Comment by Momshroom** [comment]
You can already do that yourself by adding them to your salvage config in salvage.vanilla.yml

**Comment by Momshroom** [comment]
Oops.  I meant repair.vanilla.yml

**Comment by nossr50** [comment]
The main hesitation I have for adding stuff like crossbows, tridents, shields etc to Repair is in 2.1 the repair config file system is quite simple and I am a bit worried about balance implications. In 2.2 I would feel more comfortable with it. With that said, I can add things to 2.1 and see how it goes.

**Comment by Chew** [comment]
This was added in https://github.com/mcMMO-Dev/mcMMO/commit/c22a65f9f3dce22e5e92e1056f05ab6a14d89be7

Thanks for the suggestion!
