### ISSUE TITLE
error

### ISSUE THREAD

**Issue by PhanaticD** [mcMMO-Dev/mcMMO#4132]
https://pastebin.com/raw/mtBC5wQw

using as of this commit https://github.com/mcMMO-Dev/mcMMO/commit/d525f754a7ab78895a5dfb54cc8cb15adbe4560d

**Comment by electronicboy** [comment]
nothing to do with that commit, crazyenchantments is firing a damage event while processing rupture damage

**Comment by PhanaticD** [comment]
i put that so you know what version i am on
