### ISSUE TITLE
Multiple Vote Party Rewards

### ISSUE THREAD

**Issue by ghost** [mcMMO-Dev/mcMMO#4134]

**Comment by electronicboy** [comment]
maybe i'm missing something, but, wrong plugin?

**Comment by CriticallyStable** [comment]
> wrong plugin?

No I was just saying GoldenCrates is the plugin I use for the crates, not the wrong plugin. Sorry if this was worded badly!

**Comment by Chew** [comment]
Closed due to no message and the user being deleted.
