### ISSUE TITLE
Conflict with UltimateStacker causes infinite mob respawn bug.

### ISSUE THREAD

**Issue by Amblyopia** [mcMMO-Dev/mcMMO#4137]
I'm using this plugin (mcMMO-2.1.122) with UltimateStacker from Songoda (ultimatestacker-1.11.6) and am having an issue where after a stacked mob is killed it gets respawned as another stack.

I had Songoda check into this and they couldn't figure out what was causing the conflict.  https://support.songoda.com/plugins/servlet/desk/portal/3/SD-4871

To test create enough chickens until they stack and then kill the stack.  The stack then regenerates and you're able to kill the entire stack over and over.

Video of the issue: https://www.youtube.com/watch?v=wb-yykH7mS0

**Comment by broccolai** [comment]
This is something stackers need to support on their side
