### ISSUE TITLE
Nether Quartz Ore and Mining

### ISSUE THREAD

**Issue by Snowflake101** [mcMMO-Dev/mcMMO#4140]
It would appear that the chance of doubling ore doesn't work correctly if an fortune tool is used on the  nether quartz ore only one set of shards are droped unlike in over world where a two sets or three if super-breaker is active is been recorded of droping. It would appear that Nether quartz ore might have been excluded? And or simply not working as expected.

**Comment by Geekerandy** [comment]
This issue should have been fixed in 2.1.75, this issue must’ve been forgotten to be closed since then.
