### ISSUE TITLE
Locale error with database command cooldowns

### ISSUE THREAD

**Issue by nkomarn** [mcMMO-Dev/mcMMO#4149]
When running a command like /mctop, or any other command with database cooldowns, the message output seems to be broken. The output is `!Commands.Database.Cooldown!`, which is something I also can't seem to find in the locale file.

![image](https://user-images.githubusercontent.com/22900187/78380776-45308b00-7589-11ea-8d3d-8e74fdeeb47b.png)

**Comment by broccolai** [comment]
This has been fixed.
