### ISSUE TITLE
Mcmmo not using default settings

### ISSUE THREAD

**Issue by RaesWolf** [mcMMO-Dev/mcMMO#4155]
So I am having an issue with mcmmo leveling like 10x faster than the normal and has 100% arcane forging even at the lowest ranks when its not suppose to ever have 100% even based off the files which are default as I did not edit any file.  I even deleted the files it suggests and upgraded to premium.  It was working 2 days ago then it started working like this.  I have tried switching retro mode on and off and added a couple screen shots below of the repair portion.  The endurance perk seems to be 100% as it always lasts a long time with a super short cooldown after using super breaker we can almost instantly use it again.  I am attaching the config files as I have combed them and do not understand why its so crazy fast leveling unles this is how its is suppose to be now.  My guys prefer to work for their levels.  But even over level 200 which took time to get to is now going up insanely fast.  I have purchased the original and the new premium version in the pasts and most recently.  I appreciate all your hard work!  I just want to see it working right again on my server

[Mcmmo Filess.zip](https://github.com/mcMMO-Dev/mcMMO/files/4461988/Mcmmo.Filess.zip)

In retro mode
[![Screenshot from Gyazo](https://gyazo.com/c2417d8032038285d2d1e87c7315e223/raw)](https://gyazo.com/c2417d8032038285d2d1e87c7315e223)

Retromode disabled
[![Screenshot from Gyazo](https://gyazo.com/b8ad3dcec28b57c69c30939d8575134b/raw)](https://gyazo.com/b8ad3dcec28b57c69c30939d8575134b)

Mining in retromode
[![Screenshot from Gyazo](https://gyazo.com/0efdc12c93c3e4212ed47ef228976333/raw)](https://gyazo.com/0efdc12c93c3e4212ed47ef228976333)

**Comment by Momshroom** [comment]
Did you give mcmmo related permissions?   
The short refresh times and your arcane forging issue sound very much like mcmmo.* or * was given.  
Turning retro mode on and off will not affect already gained levels/xp.

**Comment by RaesWolf** [comment]
No permissions were given. We let it default normally.

**Comment by RaesWolf** [comment]
This is a copy of our current permissions file.  I did not find anything in it.  

[text.json.gz](https://github.com/mcMMO-Dev/mcMMO/files/4462046/text.json.gz)

**Comment by RaesWolf** [comment]
Resolved
