### ISSUE TITLE
Community Edition

### ISSUE THREAD

**Issue by ByteCompiler** [mcMMO-Dev/mcMMO#4165]
if you can't offer the help I need; so you don't offer any help;

the basis of the whole community is reciprocal learning; if you don't want to learn and understand me, there's no way for me to find what you do useful; even bill gates already answered me on twitter about quantum cognitive energy;

https://github.com/PaperMC/Travertine/issues/126

**Comment by ByteCompiler** [comment]
You will never be able to create 1 company if you cannot create 1 useful product for 1 child's game;

**Comment by broccolai** [comment]
Hilarious, don't spam issues for no reason. It's not funny nor does it have any impact on anyone.

**Comment by ByteCompiler** [comment]
Even more so if you can't communicate with other developers with different interests in things you never thought of working on;

**Comment by ByteCompiler** [comment]
Larry Page hired Indians because they are good at spamming;

**Comment by ByteCompiler** [comment]
Search for Satya Nadella(Microsoft) and Sundar Pichai(Google)

**Comment by ByteCompiler** [comment]
If you don't control the spam world, you control nothing;

**Comment by ByteCompiler** [comment]
Research the books that Bill Gates reads; all about the quantum of common energy that could be scaled to solve all of humanity's problems;

**Comment by ByteCompiler** [comment]
Real developers are entrepreneurs and are able to communicate with the people and the community he created;

**Comment by ByteCompiler** [comment]
Look Bill Gates Brain Docs in Netflix: https://www.netflix.com/br/title/80184771

**Comment by ByteCompiler** [comment]
> Hilarious, don't spam issues for no reason. It's not funny nor does it have any impact on anyone.

no one cares if you are a nerdy and depressed idol simply because you don't care about anyone, you are just 1 particle of light if you come down to it; you are a child who still does not understand what it is to work hard and what it is to help someone beyond words and loop of abstract primitive stimuli because of their your psychic laziness;

i am coching, psicology, neuro scientist, and full stack developer, and know all universe languages;

**Comment by CriticallyStable** [comment]
You sir are an idiot. You may be books mart but in ways you are unable to comprehend any sort of structural and other types of work of this plugin. Maybe you should realize that although there are problems with every plugin this plugin has many as well. However, you cannot deny that this plugin is one of the most used in the world.

Plus you are using the GitHub page to post a non issue related post/thread. If you cannot follow even the simplest and smallest of rules and guidelines than there is no use for the random "facts" you have in your head, especially when you have no brain (obviously). Nobody cares if you tweeted to Bill Gates and he responded, he would never remember your name if you don't bear a known one. You most likely saw something in a documentary or History Channel movie and thought, "Hey I could sound super smart if I asked someone important about this!" Also why would Bill Gates know anything about quantum cognitive energy (correct me if I'm wrong if he does know about that topic)?

Don't be such a fucking idiot next time. Respect the people that have worked hundreds of hours on end to give the community something that greatly benefits most of them. If you can look at only its errors maybe it's time you focus on your own.

**Comment by CriticallyStable** [comment]
Deleted my comment

**Comment by ByteCompiler** [comment]
this work doesn’t have a structure, that’s what I’m talking about; they messed things up in a way that only they understand;

I was wondering if there is any logic or benefit of structuring this way or if they have a tool to quantify the entire minecraft protocol but they don't want to communicate;

there is no way to learn if only 1 of the objects is learning; learning is reciprocal;  that is why bill gates and elon musk did not put their children in ordinary school, teachers do not want to teach, teachers just want to repeat light data to earn food to survive;

**Comment by ByteCompiler** [comment]
> You sir, are an idiot. You may be books mart but in ways you are unable to comprehend any sort of structural and other types of works of this plugin. Maybe you should realize that although there are problems with every plugin this plugin has many as well. However, you cannot deny that this plugin is one of the most used in the world.
> 
> Plus you are using the GitHub page to post a non issue related post/thread. If you cannot follow even the simplest and smallest of rules and guidelines than there is no use for the random "facts" you have in your head, especially when you have no brain (obviously). Nobody cares if you tweeted to Bill Gates and he responded, he would never remember your name if you don't bear a known one. You most likely saw something in a documentary or History Channel movie and thought, "Hey I could sound super smart if I asked someone important about this!" Also why would Bill Gates know anything about quantum cognitive energy (correct me if I'm wrong if he does know about that topic)?
> 
> Don't be such a fucking idiot next time. Respect the people that have worked hundreds of hours on end to give the community something that greatly benefits most of them. If you can look at only its errors maybe it's time you focus on your own.
> 
> If I am not understanding something please correct me, I'm not a neuro scientist.

Bill gates addresses several forms of quantum energy; even about the quantum energy of your home's toilet;

**Comment by ByteCompiler** [comment]
Being inconvenient, random and stupid is the only thing to understand things; if you don't like it then you shouldn't create a public repository; if you dirty the internet with information that slows down progress then you should be judged and criticized;

If an idiot thinks something is wrong, it is a sign that something is wrong;

**Comment by ByteCompiler** [comment]
You understand things by the difference;
There is no way to understand light if light does not change into other forms;
This is basic quantum;
You are so stupid that you watch 20x star wars and avengers and don't understand the terms they use referring to the learning physics of the universe;

**Comment by ByteCompiler** [comment]
> Deleted my comment

It is no coincidence that writers earn more than developers; developers are children who think that if they don't communicate with people they will be smarter and more productive;

If you were really smart you would have 1 multi millionaire company;

**Comment by ByteCompiler** [comment]
> Deleted my comment

Everything I talked about you can find similarity with popular media languages and research about;

follow bill gates and elon musk on twitter; adam d angelo, zuck berg and read them all seriously even the ones you think is comedy;

**Comment by mass1ve-err0r** [comment]
@ByteCompiler 
Being considerate, reading documentations/ wiki and asking *appropriate* questions is the way to understand things or even the good old trial&error methodology.

FWIW, their code isn’t “messed up”. Available code is written however the author pleases to, it’s your lack of knowledge which leads to failure in understanding.

If you want to report an issue, please keep it brief and concise instead of rambling with various examples of public figures.

@broccolai please close this issue asap, this is getting unnecessary long.

**Comment by ByteCompiler** [comment]
> @ByteCompiler
> Being considerate, reading documentations/ wiki and asking _appropriate_ questions is the way to understand things or even the good old trial&error methodology.
> 
> FWIW, their code isn’t “messed up”. Available code is written however the author pleases to, it’s your lack of knowledge which leads to failure in understanding.
> 
> If you want to report an issue, please keep it brief and concise instead of rambling with various examples of public figures.
> 
> @broccolai please close this issue asap, this is getting unnecessary long.

physically you are wrong in every way, because you ignore the obvious;

**Comment by ByteCompiler** [comment]
> @ByteCompiler
> Being considerate, reading documentations/ wiki and asking _appropriate_ questions is the way to understand things or even the good old trial&error methodology.
> 
> FWIW, their code isn’t “messed up”. Available code is written however the author pleases to, it’s your lack of knowledge which leads to failure in understanding.
> 
> If you want to report an issue, please keep it brief and concise instead of rambling with various examples of public figures.
> 
> @broccolai please close this issue asap, this is getting unnecessary long.

you are only able to move light by seeing the light move; reflect on that a little; and when you reach the conclusion you will have 1 company, whoever that was bill gates, take a closer look at what you think and what others say before you speak;

**Comment by ByteCompiler** [comment]
> @ByteCompiler
> Being considerate, reading documentations/ wiki and asking _appropriate_ questions is the way to understand things or even the good old trial&error methodology.
> 
> FWIW, their code isn’t “messed up”. Available code is written however the author pleases to, it’s your lack of knowledge which leads to failure in understanding.
> 
> If you want to report an issue, please keep it brief and concise instead of rambling with various examples of public figures.
> 
> @broccolai please close this issue asap, this is getting unnecessary long.

you don't need to know about quantum physics to know about quantum physics; quantum physics is a concept, and concepts are not to be learned like wikis, quantum physics is a multi interpretation of all reality of different behaviors in equal spaces;

**Comment by ByteCompiler** [comment]
> @ByteCompiler
> Being considerate, reading documentations/ wiki and asking _appropriate_ questions is the way to understand things or even the good old trial&error methodology.
> 
> FWIW, their code isn’t “messed up”. Available code is written however the author pleases to, it’s your lack of knowledge which leads to failure in understanding.
> 
> If you want to report an issue, please keep it brief and concise instead of rambling with various examples of public figures.
> 
> @broccolai please close this issue asap, this is getting unnecessary long.

for you to talk to me you need to understand the infinite meanings for any term just as I have infinite meanings for the term quantity;

**Comment by ByteCompiler** [comment]
> @ByteCompiler
> Being considerate, reading documentations/ wiki and asking _appropriate_ questions is the way to understand things or even the good old trial&error methodology.
> 
> FWIW, their code isn’t “messed up”. Available code is written however the author pleases to, it’s your lack of knowledge which leads to failure in understanding.
> 
> If you want to report an issue, please keep it brief and concise instead of rambling with various examples of public figures.
> 
> @broccolai please close this issue asap, this is getting unnecessary long.

quantity refers to absolute 0; it is the theory of nothing; the best way to make people understand what they say is to repeat the same thing in different lines for so that she then starts to communicate with you for real;

**Comment by Draycia** [comment]
What are you going on about? You sound like you picked up a dictionary and decided you wanted to use every single word in there at least once. It's like you're some program attempting to mimick English messages.
