### ISSUE TITLE
Lang not it is working

### ISSUE THREAD

**Issue by JavituRec** [mcMMO-Dev/mcMMO#4171]
Hey,

I am using "locale_es.properties" in locale folder and config "Locale: es" but all message are in english.

![dadsad](https://user-images.githubusercontent.com/10663192/80411735-f72f4e80-88cc-11ea-9328-0b84490fcbad.png)

**Comment by Remski01** [comment]
mcMMO version?

**Comment by JavituRec** [comment]
2.1.125 the last version: https://www.spigotmc.org/resources/official-mcmmo-original-author-returns.64348/

**Comment by electronicboy** [comment]
The issue is that mcMMO does not have translations for those keys in your language, so it's falling back to english; The translation needs updating
