### ISSUE TITLE
Killed output problem (Killed by ❤️)

### ISSUE THREAD

**Issue by 0fficerSally** [mcMMO-Dev/mcMMO#4176]
"When one of my players died this happened:
**PileAtomic was slain by ❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️**
The 3 last hearts were empty."
(This is a repost from the discord server.)
This happens when you attack a mob and the hearts appear then while the hearts are still there you get killed by it, then you have this message.

**Comment by nossr50** [comment]
This bug is a bit hard to fix due with the API but there is a fix we can implement by manipulating packets, it’s likely we will go that route but don’t expect the fix to be deployed in the near future as sending out packets is a bit of a pain to wire up.
