### ISSUE TITLE
Where's the source' mcMMO 1.5.04 ?

### ISSUE THREAD

**Issue by vitorvd** [mcMMO-Dev/mcMMO#4180]
Hi guys, i'm using mcMMO 1.5.04 but I need the source to edit somethings to my server, where I can find it? I need help, please ✌️

**Comment by broccolai** [comment]
https://github.com/mcMMO-Dev/mcMMO-classic
Start there and go through the commits until you find the 1.5.04-SNAPSHOT commit. You can also view the history of the pom to find it quickly

**Comment by vitorvd** [comment]
broccolai, I saw this before create the Issue... Check the old versions there are all but the aren't 1.5.04

**Comment by broccolai** [comment]
Yes it is, you just need to go back through the commits
