### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by katsumag** [mcMMO-Dev/mcMMO#4181]
Looking for the Dev API Maven repo, or do I have to download the plugin and install it into my local repo?  I'm trying to use http://repo.mcmmo.org/ (which I see is no longer available) to get com.gmail.nossr50.mcMMO:mcMMO:LATEST.

**Comment by broccolai** [comment]
Currently you have to build it and add it to your MavenLocal, once the api is completed it'll published onto a repo.
