### ISSUE TITLE
Treefeller conflict in bordering protected areas.

### ISSUE THREAD

**Issue by LlmDl** [mcMMO-Dev/mcMMO#4189]
Hi, 

I've had a user come to me with [an issue with my plugin Towny,](https://github.com/TownyAdvanced/Towny/issues/4001) where Treefeller cancels all breaks if one fakeblockbreakevent is cancelled. I traced it back to [here](https://github.com/mcMMO-Dev/mcMMO/blob/899a0152badf00869048a3ebd60053ec9f9c2aa6/src/main/java/com/gmail/nossr50/skills/woodcutting/WoodcuttingManager.java#L273) where you've actually got it marked with a TODO: saying it should likely be a continue.

If it were a `continue;` then players who are able to break some of the tree in the Towny plot they're working in, would at least be able to harvest the part of the tree they would otherwise be able to break manually.

As a `break;` it gets completely stopped from treefelling by Towny, with the standard "You don't have permission to break" message.

**Comment by Momshroom** [comment]
Hi - I'm the user above.  If it matters, I'm on Mcmmo version 2.1.127.
