### ISSUE TITLE
The mcMMO unarmed ability duplicate all Slimefun plugin glass machine

### ISSUE THREAD

**Issue by andris155** [mcMMO-Dev/mcMMO#4197]
## Description (Required)

The mcMMO unarmed ability duplicate all Slimefun plugin glass machine.

## Steps to reproduce the Issue (Required)

1. Install mcMMO  + Slimefun your server.
2. Place glass Slimefun machines.
3. Set unarmed level to 1000. /addlevels player unarmed 1000
4. Activate mcMMO unarmed ability.
5. Break Slimefun glass machines.
6. Glass machines duplicated. (Example.: Heated Pressure Chamber, Electric Dust Washer, ...)

https://www.youtube.com/watch?v=rYvKlXRGTck

## Expected behavior (Required)

The mcMMO unarmed ability NO duplicate all Slimefun plugin glass machine.

## Environment (Required)

 - Minecraft Version: 1.15.2
 - Slimefun Version: Slimefun vDEV - 523 (git f65ac6b6)
 - CS-CoreLib Version: CS-CoreLib vDEV - 85 (git 4a7fce52)
 - mcMMO version: 2.1.129-SNAPSHOT

The Slimefun author says:
> You should probably report that to mcMMO instead.
> Looks like they are firing a BlockBreakEvent twice here.

https://github.com/TheBusyBiscuit/Slimefun4/issues/1947

**Comment by TheBusyBiscuit** [comment]
This was fixed in the latest build of Slimefun.
The Issue can be closed now :)

**Comment by andris155** [comment]
Thanks. :)
