### ISSUE TITLE
Mcmmo xp not gained from zombie pigmen that spawn from portals

### ISSUE THREAD

**Issue by 0n3La99yB01** [mcMMO-Dev/mcMMO#4199]
I have an overworld zombie pigmen portal farm on a server and none of the pigmen seem to let me gain any sort of mcmmo xp no matter what i do. Is there some sort of config that's causing this?

**Comment by Neffc** [comment]
Pigmen spawned from portals are counted as coming from a 'Mob Spawner', which is set to 0 by default. To enable this, adjust the xp modifier value in experience.yml.
