### ISSUE TITLE
Swapping mcmmo level on a server between accounts

### ISSUE THREAD

**Issue by memesdraws** [mcMMO-Dev/mcMMO#4204]
Hey so I play a lot on the cynagen minecraft server, I have spent many hours but I need to swap all my information between my original account, and my new account. I was wondering if it was possible for the server dev to be able to swap all the mcmmo points over to my new account. There's security reasons as to why I need it switched over, and I have spent tons and tons of hours grinding the skills, and I really want it saved. Is it possible to switch the mcmmo level on a server between accounts (or donate the level to someone else)?

**Comment by broccolai** [comment]
They can try to rename the flatfile / sql but honestly just using /mmoedit would be easiest

**Comment by memesdraws** [comment]
thanks, it worked!
