### ISSUE TITLE
mcMMO is incompatible 1.16.1

### ISSUE THREAD

**Issue by BigChickenInc** [mcMMO-Dev/mcMMO#4208]
for some reason, mcmmo does not work for me on my server. the plugin is red on the plugin list. none of the plugins seem to be causing the issue, but I could be wrong. the weird thing is I can still type commands and it tries to fill them... like if I type /mcmmo, it tries to fill mcmmo commands. none of the XP works or anything like that.

**Comment by broccolai** [comment]
copying command from discord:

You are running an outdated build of Spigot.
If you wish to confirm this, run /version ingame.

There are numerous spigot builds for each Minecraft version, and there is a known issue with older builds of spigot which cause issues with mcMMO on 1.16.1.

Jars from sites that let you download spigot will be out of date and should not be trusted.
BuildTools is the only official way to obtain Spigot.

Rerun BuildTools (java -jar BuildTools.jar --rev 1.16.1) and use the new jar it provides, to update your spigot build.

**Comment by BigChickenInc** [comment]
Thank you so much! I downloaded Spigot from the wrong cite. it works now.
