### ISSUE TITLE
Mob names in kill feed showing up as "❤❤❤❤❤❤❤❤❤❤"

### ISSUE THREAD

**Issue by RalphORama** [mcMMO-Dev/mcMMO#4218]
What the title says.  I have the option enabled to show mob health above their heads.  When mobs that have their health showing are killed, the kill message looks like this:

```
RalphORama was blown up by ❤❤❤❤❤❤❤❤❤❤
```

I do not have any plugins that modify death messages.  Other death messages look like:

```
RalphORama suffocated in a wall
```

**Server Info**

- Version: `git-Paper-79 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)`
- mcMMO version: `2.1.132` (downloaded from Spigot page)
- mcMMO configs: [click here](https://gist.github.com/RalphORama/94d65e8929ae3bcdcf3e56a218d46765)
- Plugins: 
  - Chunkmaster
  - ConsoleSpamFix
  - CoreProtect
  - DiscordSRV
  - EmojiChat
  - Essentials
  - EssentialsChat
  - EssentialsGeoIP
  - EssentialsProtect
  - EssentialsSpawn
  - ExtraContexts
  - FastLeafDecay
  - GameModeInventories
  - GriefPrevention
  - HiddenLorax
  - IllegalStack
  - LimitPillagers
  - LuckPerms
  - Matrix
  - mcMMO
  - OpenInv
  - Plan
  - ProtocolLib
  - SAML
  - SelectionVisualizer
  - ServerListPlus
  - Shopkeepers
  - ShowItem
  - spark
  - StackMob
  - TimeControl
  - ViaBackwards
  - ViaVersion
  - VillagerModifications
  - VillagerOptimiser
  - WorldEdit
  - WorldGuard
  - WorldGuardExtraFlags
  - WorldResourcepacks

**Comment by Draycia** [comment]
CraftBukkit bug. 
CB strips colors from the death message in the event and mcMMO checks message equality. Which fails due to the missing colors. A fix is known but not yet implemented.
