### ISSUE TITLE
Build 2.1.134 Furnaces and Blast Furnaces broken

### ISSUE THREAD

**Issue by samurainate** [mcMMO-Dev/mcMMO#4232]
After upgrade from 2.1.133 to 2.1.134, furnaces would not light, and blast furnaces kept returning one or both items put in.  Breaking, replacing and re-registering had no effect.  Roll back to 2.1.133 fixed the issue.  

EDIT: Probably need some more information.  

This server is running CraftBukkit version git-Spigot-9639cf7-7c03d25 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

Also running Jobs, EssentialsX and Vault.

**Comment by Ineusia** [comment]
Unable to reproduce issue with the following plugins from SpigotMC plugin pages;

EssentialsX 2.18.0.0
Jobs 4.16.0
Vault 1.7.3-b131
mcMMO 2.1.134

nossr50 reverted a furnace related change in the latest dev build -- Unsure if that fixes your issue, but I cannot reproduce it with the release build prior to the change he just made.

**Comment by samurainate** [comment]
I will try to reproduce after the kids are done playing for the day.  It may be related to my config.

**Comment by samurainate** [comment]
Ineusia, it wasn't reproducible with my original report.  I didn't include the full list of plugins.  After eliminating plugins one at a time, I found it is an interaction between mcMMO 2.1.134 and Drop2Inventory 4.3.3.  The interaction doesn't occur in mcMMO 2.1.133 or 2.1.135, only in 2.1.134.   OK to close.  Thank you!
