### ISSUE TITLE
Feature Request: Disable Berserker Ability on Glass

### ISSUE THREAD

**Issue by ItsSynchro** [mcMMO-Dev/mcMMO#4242]
Due to mcMMO and Slimefun not really being compatible with each other, there are several duplication glitches. One of them being the Berserker ability duplicating Slimefun's "Reinforced Glass". There should be a config option to disable the Berserk ability from glass in order to prevent this. 

I'm certain everyone who uses both mcMMO and Slimefun would truly appreciate it, thank you.

**Comment by TheBusyBiscuit** [comment]
This was fixed in the latest build of Slimefun.
The Issue can be closed now :)
