### ISSUE TITLE
Users are experiencing ejection from server (Disconnects) when using skills.

### ISSUE THREAD

**Issue by Phoenixthedoggo** [mcMMO-Dev/mcMMO#4243]
I've had several users report that they are being "kicked" (really disconnected) from the server when attempting to use a skill / level up a skill. Not sure what's going on, but I have the latest version from Spigot.

A user managed to screenshot it for me, so here's what he sees when he gets disconnected:
![image](https://user-images.githubusercontent.com/20131900/89071568-a0f30100-d33c-11ea-970a-c7b2628b1ef5.png)
![image](https://user-images.githubusercontent.com/20131900/89071579-a5b7b500-d33c-11ea-8e9a-edcf0bd62a87.png)

And here's what I get in console when it happens:
![image](https://user-images.githubusercontent.com/20131900/89071640-bd8f3900-d33c-11ea-8a63-9b0c0d6dcf8c.png)
That's literally all it says for me, so that made it difficult until I got screenshots to pin-down what plugin was causing it.

**Comment by nossr50** [comment]
This is a bug with the server software, its happening for other plugins as well. I'm not sure when it will be fixed, but its not something mcMMO can fix.

**Comment by Phoenixthedoggo** [comment]
> This is a bug with the server software, its happening for other plugins as well. I'm not sure when it will be fixed, but its not something mcMMO can fix.

Thank you for assisting in this investigation, I appreciate your input. I'll see if updating PaperMC fixes it, but in the mean-time if it doesn't I'll just disable MCMMO until it's fixed.
