### ISSUE TITLE
[Suggestion] Right-click on Woodcutting to be like a Pickaxe

### ISSUE THREAD

**Issue by mrfloris** [mcMMO-Dev/mcMMO#4245]
Hey,

Right now we have to use /mccooldowns to see when we can use our /woodcutting skill again. If you right click right now on an axe it says "you ready your axe", but you can't hit a tree to try and trigger it, since it will remove the bark.. So you accidentally do that a few times. And when you check (since at the start you get hardly enough time for 1 tree) you waste your time trying to read the chat (or you accidentally break a log on the tree, which we can't 'replant', only 'replace'.

It would be rather fantastic if we right click an axe it says that woodcutting is ready or in x seconds .. 

I understand there might be a technical limitation because "axes" is also a skill for combat. But I rather have 2 msgs on the screen than a single one that isn't actually informative. 

<img width="1046" alt="Screenshot 2020-08-01 at 06 56 04" src="https://user-images.githubusercontent.com/28841349/89094431-1eae1f80-d3c4-11ea-8c1e-fd7a5d8c0cd0.png">

**Comment by nossr50** [comment]
I will try to add this in the next round of feature requests

**Comment by mrfloris** [comment]
I hope it's possible and that you can figure out how to do this. Thank you for considering and trying.

**Comment by nossr50** [comment]
Added

**Comment by mrfloris** [comment]
Yesh!!! Thank youuuuu
