### ISSUE TITLE
[Bug] Blaze fire_ball is considered 'arrow deflect'

### ISSUE THREAD

**Issue by mrfloris** [mcMMO-Dev/mcMMO#4246]
When a blaze attacks you it correctly detects that you're deflecting/dodging something, but it doesn't distinguish between an arrow type or fire_ball type.

<img width="1026" alt="Screenshot 2020-08-01 at 06 59 21" src="https://user-images.githubusercontent.com/28841349/89094483-bf9cda80-d3c4-11ea-8330-ecf8dbacc1f5.png">

**Comment by nossr50** [comment]
This was fixed in a recent update

**Comment by mrfloris** [comment]
Excellent, thank you.
