### ISSUE TITLE
[Suggestion] Add blast furnaces to the list of improving repair skill and giving more items on smelting.

### ISSUE THREAD

**Issue by mibby** [mcMMO-Dev/mcMMO#4247]
Would it be possible to add blast furnaces to the list of furnace types to improve repair skill and giving more items on smelting? May need some balance adjustments however since it smelts twice as fast by default.

**Comment by nossr50** [comment]
Blast Furnaces should be identical to furnaces.

**Comment by mibby** [comment]
I'd assume it is a bug somewhere as two separate users specifically request for blast furnaces to be added to improving repair skill and give more items. Unless they never double checks that it actually does, it seems odd they would request it.
