### ISSUE TITLE
mcMMO skill credits didnt transfer correctly

### ISSUE THREAD

**Issue by rkrout3** [mcMMO-Dev/mcMMO#4254]
I used 500 mcmmo credits on fishing and when i use /fishing on the command/text line it shows 875 as the level but when i use /lf it shows a completely different level. I play on opskyblocks and my character name is trahodrom3000. I want to see if someone could fix this issue that im am having.

**Comment by broccolai** [comment]
mcMMO does not include a credit system by default, please report this to your server admins or to the maker of the credit plugin.
