### ISSUE TITLE
using mcmmo with CompatNoCheatPlus

### ISSUE THREAD

**Issue by wallace329** [mcMMO-Dev/mcMMO#4256]
i have add NoCheatPlus/CompatNoCheatPlus and mcMMO on my minecraft server
player using mcmmo with sword skill.
i have ask to NCP, buy they need you tell them what is the event causes bleeding to deal damage?

Server version 1.16.1 
papermc133 
mcMMO version 2.1.139
NCP version 3.17(b5.9.5)
CNCP version b90
https://proxy.spigotmc.org/5351bdc95336d4dc28805df25d1df8d049847de8?url=https%3A%2F%2Fmedia.discordapp.net%2Fattachments%2F720761582614872185%2F741732271106687026%2Funknown.png
https://proxy.spigotmc.org/0376a0930848afa3db71a7eec3736340ff2f2025?url=https%3A%2F%2Fmedia.discordapp.net%2Fattachments%2F720761582614872185%2F741729723436105739%2Funknown.png

**Comment by nossr50** [comment]
I can't really help with this, talk to the anti-cheat author. Most people seem to use Spartan or ACP for anti-cheat.
