### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 100petr** [mcMMO-Dev/mcMMO#4258]
I'm getting this error: https://pastebin.com/9dEaU1jV
I think it's because the player is somehow "immortal" (he can't get any damage), but god is turned off
mcMMO version 2.1.134-SNAPSHOT
This server is running Paper version git-Paper-134 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[11:34:55 INFO]: You are running the latest version

**Comment by Quavelen** [comment]
Please update your mcMMO to `2.1.140`, as it fixes a large number of errors, including the one you reported. There are still more issues to tackle, but I'm *mostly* positive yours is resolved.

mcMMO `2.1.140` was on the 9th of August, at 04:21 UTC.
mcMMO `2.1.134` was on the 24th of July, at 04:27 UTC.

In the off chance that updating to this version does not resolve it, please let us know.

**Comment by 100petr** [comment]
Okay, I'll try it and I'll get back to you soon!

**Comment by 100petr** [comment]
I updated to version 2.1.140 and the error is no longer there. But the player is still "immortal" even if god doesn't have, is it a problem of mcmmo or some other plugin?

**Comment by Quavelen** [comment]
A player being "immortal" is most certainly another plugin. Thankfully mcMMO can't make players like that.


However, there is one context where what you're describing is possible - the party system. By default, users who are in the same party cannot hurt one another. The setting to change this is here, in the `config.yml file:

```yaml
Party:
    # Enable Hurting other players in the same party
    FriendlyFire: false
```


If they are not in a party, then yes, it's another plugin.

**Comment by 100petr** [comment]
Well, the player doesn't even get a falldamage. The easiest way will be to
try it without mcmmo. I'll get back to you tomorrow.

út 11. 8. 2020 v 18:10 odesílatel Flannery Lue Moore <
notifications@github.com> napsal:

**Comment by 100petr** [comment]
ok, mcmmo doesn't do it. thank you for your time. I'm going to look for what it does.Odesláno z mého chytrého telefonu Samsung Galaxy.
-------- Původní zpráva --------Od: Flannery Lue Moore <notifications@github.com> Datum: 11.08.20  18:10  (GMT+01:00) Komu: mcMMO-Dev/mcMMO <mcMMO@noreply.github.com> Cc: 100petr <pitilonek@gmail.com>, Author <author@noreply.github.com> Předmět: Re: [mcMMO-Dev/mcMMO] Error (#4258) 
A player being "immortal" is most certainly another plugin. Thankfully mcMMO can't make players like that.
However, there is one context where what you're describing is possible - the party system. By default, users who are in the same party cannot hurt one another. The setting to change this is here, in the `config.yml file:
Party:
    # Enable Hurting other players in the same party
    FriendlyFire: false
If they are not in a party, then yes, it's another plugin.
