### ISSUE TITLE
[Suggestion] Tweak Acrobatics and Alchemy to give XP when abilities are disabled

### ISSUE THREAD

**Issue by Tencryn** [mcMMO-Dev/mcMMO#4260]
Currently, acrobatics and alchemy do not collect experience when their abilities are disabled. They require roll and concoctions respectively to be enabled in order to collect experience.

For server owners who want to avoid changing vanilla game play, it would be nice if we can disable those abilities while still able to collect experience in those skills.

**Comment by nossr50** [comment]
I will add this in the next round of feature requests

**Comment by nossr50** [comment]
Alchemy is too hacky for this, but now Acrobatics will gain XP without requiring Roll SubSkill
