### ISSUE TITLE
[BUG] Falling from a high place does not give acrobatics experience

### ISSUE THREAD

**Issue by Tencryn** [mcMMO-Dev/mcMMO#4262]
I have discovered that you do not gain acrobatics experience if you fall from 24 blocks (or jump off of 23) above the ground. Nothing shows up in `/mmodebug` at all. You will gain experience from falling off heights less than this, usually. In my testing, there was a case where I didn't gain experience but I was unable to replicate it.

In case there is any correlation, falling off of 23 blocks will give you 22800 experience.

I have tested this in the latest 1.16.1 paper with mcMMO 2.1.141 with default configuration and no other plugins.

I wouldn't consider this major by any means as in most cases, you do not fall off of heights that great and perhaps that is why it hasn't been noticed before, or that it is new to 1.16. It's anyone's guess really.

**Comment by SundraLOL** [comment]
This actually happens a lot. I was playing on UMC towny with the same plugin for 1.15.2 and it gives me experience maybe once or twice but, it stops giving me acrobatics after a that and I have to wait or go to a new chunk.

**Comment by nossr50** [comment]
This was fixed a while back
