### ISSUE TITLE
[Suggestion] New Skill regarding Shields

### ISSUE THREAD

**Issue by kagneel** [mcMMO-Dev/mcMMO#4270]
I've been thinking about this for a while during my time on a dungeons server on minecraft,there are always problems when going in one. One of them being the boss will switch aggro.
A shielding skill would be pretty nice. I havent thought much about it but I can offer a few suggestions.
->An AOE skill that would taunt all monsters within an area and draw them to the caster.
->A passive skill which offers an off-limits Resistance level (IV+) while the player is holding the shield in his right hand
->A skill accessible in very high level which offers Resistance to all (party?) members. Maybe even Strength, could be called "Morale Boost"
->Passive skill which gives Regeneration II+ after the player gets under 50% HP.
->High level accessible skill which gives absorption hearts on activation.

**Comment by Chew** [comment]
This was suggested already in #3331, so discussion should merge there. Thank you for the suggestion!
