### ISSUE TITLE
How do i understand the locale file?

### ISSUE THREAD

**Issue by jeeshen** [mcMMO-Dev/mcMMO#4278]
I have been asking for so many times in the discord for help. I dont understand what is that locales about, I cant use any color code to modify it

**Comment by nossr50** [comment]
The supported color codes are &+0-9/a-f and [[COLOR_RED]] etc
You can use https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/locale/locale_en_US.properties as an example of how to use [[COLOR_XXX]]
