### ISSUE TITLE
DoubleDrops ability issue

### ISSUE THREAD

**Issue by HexedHero** [mcMMO-Dev/mcMMO#4281]
This is a very weird one I've been testing for hours now.

The best way I've been able to produce this is go into the nether at y 15~ and mine out an area, then place blocks that normally get doubled by double drops like ancient debris under you in different places. When you mine them with haste 10 it'll sometimes give double when the block should actually be protected since it was played placed and even in the debug mode, it says it's not natural. It does not work in the same block space twice. I could spend 10 mins trying this and not work then all of a sudden I get 3/4 blocks near each other that doubles.

Video: https://i.imgur.com/2c24GYk.mp4

**Comment by nossr50** [comment]
What plugins are running when you are experiencing this issue?
Can you replicate with just mcMMO?
What version of mcMMO?
What version of Minecraft?

**Comment by HexedHero** [comment]
Completely fresh new 1.16.3 Paper server with new worlds, no prior plugins installed or anything.

[17:00:33 INFO]: This server is running Paper version git-Paper-203 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[17:00:33 INFO]: Checking version, please wait...
[17:00:33 INFO]: You are running the latest version

[17:00:41 INFO]: Plugins (1): mcMMO

[17:00:48 INFO]: mcMMO version 2.1.145

All information is included in the video https://i.imgur.com/CT4YPja.mp4
I placed the block then mined it and it gave me xp and double drops.

Not sure if haste is part of the issue at hand, it's so random it's hard to test.

**Comment by nossr50** [comment]
I will look into this ASAP and see if I am able to replicate

**Comment by nossr50** [comment]
I can't replicate this, follow up with me in DM on discord.
