### ISSUE TITLE
Summoned Entity may not disapper and be able to reproduce

### ISSUE THREAD

**Issue by emanondev** [mcMMO-Dev/mcMMO#4289]
****How to reproduce the bug:****
1. Summon a wolf with Taming skill (or any kind of mob)
2. Change world
3. Wait until the wolf should have disappeared
4. Get back to the wolf
5. Repeat steps 1-4 for multiple wolfs
6. Optional: feed the to reproduce them

****Proposed solutions:****
A. On player teleport teleport all summoned entity by the player as well with the player
this solution may be bypassed with player logout maybe? on player logout summoned entity should be removed and optionally readded if player gets back online befor them should have disappeared

B. Add a permanent tag on summoned entity which remember when the entity was summoned, any interaction with the entity should check if the entity should have disappeared already, remove the entity if true

C. On chunk unload check if any entity on the chunk are summoned entity, then remove/move them

A solution should be the faster for performance and probably the best
B solution can work too
C solution may be a bit heavy for cpu

**Comment by nossr50** [comment]
COTW entities are persistent now (even in 2.1.149) so you shouldn't be able to reproduce with them, as for killing them when they are past their life expectancy, I have yet to add anything to address that.
