### ISSUE TITLE
CrazyAuction and mcMMO Incompatibility

### ISSUE THREAD

**Issue by ItsSynchro** [mcMMO-Dev/mcMMO#4292]
**Describe the bug**
Theirs a bug where when you activate Super Breaker and sell it to an auction house and then unlist it to get it back it stays with Efficiency 11 permanently. When you drop it it goes back to normal but still can cause issues as someone may figure out a way to keep the enchantment.

**Versions**
 - Minecraft Server Version: 1.16.3
 - Plugin Version: 2.1.148

**Issue**
Players can obtain Efficiency 11 upon auctioning an item when they use Super Breaker from mcMMO.

**Screenshots**
![enchant](https://user-images.githubusercontent.com/16171807/95663343-81cad980-0b0c-11eb-86f6-d8d3ffac4670.png)

**Comment by Pandas0** [comment]
Would like to add, I have to same issue with the AuctionHouse plugin (A different one from this user) but the bug seems to only effect Netherite items. I tried on a diamond pickaxe and it will restore back to the original efficiency.

**Comment by nossr50** [comment]
@Pandas0 mcMMO will clear the buffs once it sees the item has been boosted (stored in NBT) and the player is not currently using super breaker, if a plugin changes the item that can cause this intended behaviour to fail. With that said, its up to the auction plugins to support mcMMO, there's almost nothing we can do from our end.
