### ISSUE TITLE
The mcMMO salvage ability reclaim the vanilla materials from Slimefun tools and armors

### ISSUE THREAD

**Issue by andris155** [mcMMO-Dev/mcMMO#4294]
https://www.youtube.com/watch?v=8x65SR2xvj0

Paper 1.16.3
mcMMO version 2.1.148
Slimefun vDEV - 712 (git 15884c6)
CS-CoreLib vDEV - 91 (git e42a05d1)

https://github.com/Slimefun/Slimefun4/issues/2452

**Comment by TheBusyBiscuit** [comment]
Since I am working on a bit of mcMMO integration atm anyway, I noticed that there is a handy `McMMOPlayerSalvageCheckEvent`.
So I'm fixing this from the Slimefun side right now, the issue can be closed :)

**Comment by andris155** [comment]
Okay. Thanks. :)
