### ISSUE TITLE
Green Thumb (Herbalism) not working 1.15.2 

### ISSUE THREAD

**Issue by Vyvhen** [mcMMO-Dev/mcMMO#4297]
The herbalism ability is not working at all.
No replant of crops of any kind.

Server-Version: 1.15.2 (paper build 387)
mcMMO-Version: 2.1.147

No interfering with other plugins, therefor tested on a clean server setup (only mcmmo and luckperms installed)

**Comment by nossr50** [comment]
Are you using a Scythe? It was changed to require a Scythe.

**Comment by Vyvhen** [comment]
No Bug - rtfm

Thanks for that hint. We didn't realise, that this was changed.
