### ISSUE TITLE
Adding a rarity to treasures.yml for fishing.

### ISSUE THREAD

**Issue by codemaster101gangster** [mcMMO-Dev/mcMMO#4301]
I added a rarity for fishing drops. I also added new items for that rarity. However when I fish it will drop the new rarity items even though it has a 0% chance of dropping in the tier I am in. Is there a way to fix?

**Comment by nossr50** [comment]
The rarities are hard coded, in the config update the loot system is being completely rewritten to be similar to games like Morrowind/Skyrim/Oblivion etc.
