### ISSUE TITLE
Netherite pickaxe does not double drop.

### ISSUE THREAD

**Issue by FyreByrns** [mcMMO-Dev/mcMMO#4302]
On a 1.16.3 server using 2.0.0-SNAPSHOT, netherite pickaxes *never* double mine, despite level 429 mining.
Regular diamond pickaxes double mine at the expected rate.

**Comment by Quavelen** [comment]
Your explained what's causing your issue:

>2.0.0-SNAPSHOT

If memory serves, this is from 2018. You need to update to the latest version of mcMMO, which is `2.1.149`. You can find it here: https://www.spigotmc.org/resources/official-mcmmo-original-author-returns.64348/


Please also ensure you are on the latest version of Paper, or Spigot by typing `/version` ingame. I suggest using Paper, personally. You can find the latest version of Paper, here: https://papermc.io/downloads

**Comment by FyreByrns** [comment]
Just found out from the server owner that they're using an old version because it isn't updated to spigot. Sorry about that, I thought it was newest because of the SNAPSHOT, I should know better.
