### ISSUE TITLE
Fishing speed is broken

### ISSUE THREAD

**Issue by Airtheon** [mcMMO-Dev/mcMMO#4304]
Currently, the logic for improved fishing speed, in the form of added bitechance, is perfectly coded.
However for about the past 4 years, Minecraft has changed the way fishing works, thus bitechance no longer has any effect.
Spigot has deprecated the setBiteChance method, but as of right now, has not provided another way of changing fishing speed.

There might be a workaround, which I will look into, but I thought you should know in case you get questions about why it is not working.

**Comment by Airtheon** [comment]
A work around in doable, but requires interfacing directly with net.minecraft.server. As this is not an advisable thing to do, I'll see if I can create an issue with the Bukkit or Spigot team to address this.

**Comment by nossr50** [comment]
Thanks for the post, I was aware of this issue and the NMS work around, however it seemed hacky to do it through NMS so this is why it hasn't been touched yet.

**Comment by Airtheon** [comment]
Hi, small update. My PR for modification of fishing speed has just been committed. It will probably be available in the next Spigot update. See this commit ( https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/1871ca9d3d5b312945bb7a8e92013d2cabbbaad5 ) for the API implementation.

**Comment by nossr50** [comment]
Fixed
