### ISSUE TITLE
Experience gain with bow/crossbow changes with different arrowtypes

### ISSUE THREAD

**Issue by SeraphoenixMc** [mcMMO-Dev/mcMMO#4310]
Like the title said, you get different experience values with different arrowtypes like spectral arrows. It almost tripled the amount of ep you'll get per shot compared to a normal arrow.

**Comment by nossr50** [comment]
This sounds like a bug, XP given is influenced by damage dealt, so if the arrow isn't dealing more damage it shouldn't be giving more XP.

**Comment by nossr50** [comment]
This was fixed
