### ISSUE TITLE
Console addlevels silence output?

### ISSUE THREAD

**Issue by mrfloris** [mcMMO-Dev/mcMMO#4311]
Hey nossr50,

Would it be possible to get a parameter for addlevels so we can silently add a level to a player?

For example, when they vote I wouldn't mind adding a level to their account but I would rather add it manually as text to the reward output than a bright green line I have no control over. 

If `addlevels %player% repair 1` could be like this: `addlevels %player% repair 1 -s` then this would be super helpful in this and quite a few other situations. 

Sidenote: if gaining a level triggers unlocks for ranks, so they output and make noise, that's perfectly fine. Those can still happen.

<img width="1034" alt="Screenshot 2020-10-27 at 07 29 11" src="https://user-images.githubusercontent.com/28841349/97264958-1d0ac100-1826-11eb-9adf-360aaf824324.png">

**Comment by Quavelen** [comment]
I really like this suggestion, lol.
Recently, I also came across a situation where I'd like to have this option. Hopefully nossr will add it.

**Comment by nossr50** [comment]
Yeah this could be done, would addlevels be the only place a silent flag would be useful?

**Comment by mrfloris** [comment]
For me personally, yes.

**Comment by nossr50** [comment]
Added in 05f2763311af4af6b6570a97b205ed600d3aee9e
