### ISSUE TITLE
Useless plugin message when using public chat

### ISSUE THREAD

**Issue by kajahofman** [mcMMO-Dev/mcMMO#4312]
In the latest compiled build there is a bug that shows a message of disabling admin/party chat each time any public chat message was sent.

![image](https://user-images.githubusercontent.com/30930670/97332535-db583580-187a-11eb-9e23-4626682c12f9.png)

**Comment by nossr50** [comment]
Dev builds are works in progress, you are not meant to use them in production. I am already aware of this issue. The issue page on github is only for bugs present in the latest stable build.
