### ISSUE TITLE
Party/Admin Chat + HEX

### ISSUE THREAD

**Issue by Pandas0** [mcMMO-Dev/mcMMO#4313]
With the new recode of the chat systems, the chats no longer seem to support HEX colors within nicknames (from essentials) not sure if its something to report to you or them, it worked prior to the recode but stopped once I updated to it. The hex colors still work with default chat (from essentials).

**Comment by ZEROOblivious** [comment]
Quote from Update in Spigot:
Added new permission node 'mcmmo.chat.colors' which allows players to use color codes, negate to disallow this

Did you give the permission to your community/staff team to use Color Codes & HEX? 

& /nick is Essentials ; NOT McMMO.

**Comment by nossr50** [comment]
mcMMO chat code only touches chat if someone is sending to party or admin chat, I'm not familiar with what interaction or hooks Essential does with mcMMO and how the update (the recode of chat code in mcMMO) may have affected them. I would go talk to the essentials authors and see if they have an mcMMO dependency and if they do find out whether or not it needs to be updated to support the latest API.

mcMMO has a few events where Chat plugins can change the names for players, or chat plugins can cancel these events and handle everything themselves.

**Comment by Pandas0** [comment]
> Quote from Update in Spigot:
> Added new permission node 'mcmmo.chat.colors' which allows players to use color codes, negate to disallow this
> 
> Did you give the permission to your community/staff team to use Color Codes & HEX?
> 
> & /nick is Essentials ; NOT McMMO.

I stated that it could be an essentials issue if you read what I posted I also stated that "HEX colors within nicknames (from essentials)" never said the nicknames was mcMMO, I gave every rank on my server the 'mcmmo.chat.colors' permission so it can't be due to lack of permissions. As for the post by nossr, thank you I will contact them today and relay any useful information (if any) they give.

**Comment by andris155** [comment]
The player name black or white on the new party chat.
I use hex color codes for prefix, and nick names. (EssentialsX chat plugin)
![123549684_372824173924007_7903089945070482959_n](https://user-images.githubusercontent.com/8324198/97898710-89128b00-1d38-11eb-9892-25a8cdca5843.png)
<img width="208" alt="Capture" src="https://user-images.githubusercontent.com/8324198/97898764-992a6a80-1d38-11eb-8b3c-9312c927d6b3.PNG">

**Comment by nossr50** [comment]
Fixed in a4fd632d533c10bc6f00b0a562670444f42ed5d1
