### ISSUE TITLE
Rupture/bleeding prevents sweeping edge from working

### ISSUE THREAD

**Issue by InfernoSuperNova** [mcMMO-Dev/mcMMO#4315]
When any enemy is bleeding, you can't do any sweeping edge attacks (still damages primary target however)

**Comment by InfernoSuperNova** [comment]
Server version is 1.16.3 paper, however the server admin refuses to tell me the mcmmo version. Presumably latest.

**Comment by nossr50** [comment]
I'll need him to file the report as you can only provide limited information.
