### ISSUE TITLE
Mcmmo-chat notification

### ISSUE THREAD

**Issue by kaiticat** [mcMMO-Dev/mcMMO#4319]
I am unsure on how to remove/fix this notification that continues to pop up every time someone sends a message it is down right annoying if there is a way to fix it. I'd be very much appreciated thanks!

![2020-10-31_08 10 26](https://user-images.githubusercontent.com/73750534/97783086-92da9980-1b52-11eb-9a45-f24fd095f4db.png)

**Comment by Quavelen** [comment]
Lol, update mcMMO. 
https://www.spigotmc.org/resources/official-mcmmo-original-author-returns.64348/
That is a bug which appeared in one of the dev builds, not a release version. It has been fixed in the latest release.
