### ISSUE TITLE
Fishing "Shake"

### ISSUE THREAD

**Issue by placestamphere** [mcMMO-Dev/mcMMO#4325]
Working with a few people on my server we discovered that the ability 'Shake' does not give any xp for the fishing level. After looking into the code it shows that mobs can be hooked, do take damage, and they xp reward for shake is set to 50, any ideas?

**Comment by nossr50** [comment]
I'll look into this, thanks for the report.

**Comment by nossr50** [comment]
Shake is rewarding 50 XP as intended, it only rewards it when a successful shake is performed. Just confirmed myself.
