### ISSUE TITLE
Mob Farms

### ISSUE THREAD

**Issue by moveit124** [mcMMO-Dev/mcMMO#4327]
When using a Piglin xp farm you can use swords/crossbow and get MASSIVE experience.  Level 0-1000 in about 30 minutes.  And you can level all others as well, just by spamming click.

**Comment by nossr50** [comment]
Can you post more details? I don't quite understand how the farm is set up.

**Comment by moveit124** [comment]
Here is a video of the farm made in my server:

https://www.youtube.com/watch?v=nMBYnGD8PbQ
