### ISSUE TITLE
Party Member/Leader Chat

### ISSUE THREAD

**Issue by Pandas0** [mcMMO-Dev/mcMMO#4329]
I have modified the design of the party chat in the newer updates to be like how I had it previously on my server through a locales file. For some reason it seems that the chat for party leaders stays the default version that comes default with the plugin, while all the members in the party use the design I specified in the locales file.

I'm not sure if I missed something within the locales file (I have looked a few times) or if its  just an issue within the plugin.

My locales file: [locale_en_US](https://pastebin.com/siidEAAi)
(Note: It's a pastebin link)

Screenshot from in game: [Screenshot](https://prnt.sc/vh63i3)
(Note: It's a prnt.sc link)

**Comment by nossr50** [comment]
Party leaders have their own locale key for their style, defined by 'Chat.Style.Party.Leader' in en_US
