### ISSUE TITLE
Ability to salvage non vanilla level enchants

### ISSUE THREAD

**Issue by SplitX1** [mcMMO-Dev/mcMMO#4331]
Hello I play on quite a few servers where they give you an option to buy items with enchants on them that are above vanilla minecraft cap (protection 6 for example) but do not fit the item where the whole goal was to salvage the item to gain the book via mcmmo salvage. I was wondering if it is possible to add this feature into the plugin itself or if there is up to date plugins out there that are up to date and does this exact thing. Any help is greatly appreciated.

**Comment by nossr50** [comment]
Turn on allow unsafe enchantments and it should work, its either in config.yml or advanced.yml

**Comment by SplitX1** [comment]
Hello thank you for the response but I cant seem to find that option in either of the mention .yml files and (it is already enabled in essentials config file) and when salvaging an item it still only gives vanilla capped enchant.
![mcmmo](https://user-images.githubusercontent.com/43014427/99017979-f8feed80-2550-11eb-85d7-b7916532c774.PNG)

**Comment by SplitX1** [comment]
Nevermind I found it in experience.yml, not the first place I would look but its there. Thank you for your help!
