### ISSUE TITLE
How to Disable Mcmmo in Certain Worlds

### ISSUE THREAD

**Issue by Anston06** [mcMMO-Dev/mcMMO#4333]
This is a duplicate of an older thread, but I didn't understand it. I would like to disable mcmmo in certain worlds. I have luckperms, but it didn't work. You are going to have to walk me through it. How do you do this?

Old Thread: [#254](https://github.com/mcMMO-Dev/mcMMO/issues/254)

**Comment by nossr50** [comment]
in the blacklist.txt file each line is the name of a world

**Comment by Anston06** [comment]
Thanks, I didn't notice that!
