### ISSUE TITLE
BUG: "customboost" xp percentage gain breaks ranking chain permissions

### ISSUE THREAD

**Issue by Yertled** [mcMMO-Dev/mcMMO#4334]
Hello, when I was testing the mcmmo permissions to get more XP, I noticed some of them didn't work as intended.
Here are the woodcutting XP I got with each permissions:
70 - No permissions
77 - mcmmo.perks.xp.10percentboost.all
87.5 - mcmmo.perks.xp.customboost.all (set to 1.25 in config)
87.5 - mcmmo.perks.xp.50percentboost.all
87.5 - mcmmo.perks.xp.double.all
87.5 - mcmmo.perks.xp.150percentboost.all

This is based of a ranking system, where X rank is a parent of Z rank for example. The permission(s) works alone if the player has no rank, but the permissions break once there is a chain of ranks that inherit from eachother.

After some testing, any rank that inherits "customboost" is set to that boost, even tho they have the higher percentage permission. I fixed this by stopping the chain, and making the next rank after customboost "mcmmo.perks.xp.customboost.all false".

Plugins used for permissions:
LuckPerms

**Comment by nossr50** [comment]
In 2.1 (and this will be the same for 2.2/Tridents & Crossbows when its out) custom boost has priority over the other ones, can you not just remove the custom boost permission when they advance? mcMMO (all versions until config update is out) does not stack XP boost perks, it will always only apply the highest OR custom boost if the player has custom boost.

In the config update which hasn't rolled out yet and won't be out for a while, perks stack and you can define an infinite number of custom perks with custom names
