### ISSUE TITLE
/mctop issue

### ISSUE THREAD

**Issue by xl3ehindTim** [mcMMO-Dev/mcMMO#4335]
When using commands involving /mctop I get the following result in my chatbox:
![afbeelding](https://user-images.githubusercontent.com/32740573/99193590-4ca04f80-277a-11eb-8448-1cbf12b06660.png)

**Comment by Remski01** [comment]
Hello.

Please check what mcmmo version you have, you can do it by using `/version`. 

If you have an lower version then 2.1.157, **Update to the build then, if have fixed an issue related to the leaderboards.**

**Comment by xl3ehindTim** [comment]
Thank you for helping me!
