### ISSUE TITLE
Is it possible to enable some RCON commands?

### ISSUE THREAD

**Issue by Moon-developer** [mcMMO-Dev/mcMMO#4338]
I built a discord bot that makes use of RCON to run some commands and the guys asked if they can view and track progress of the mcMMO stats on the channel.

Realized after awhile that using mcRCON to call `mstats <player>` returns an error saying `This command does not support console usage.`. Not sure how hard it would be to enable some of these features for console usage.

**Comment by Momshroom** [comment]
/inspect (player) gives similar results to /mcstats, but expects a player name to be given to it.   Try that?

**Comment by nossr50** [comment]
What @Momshroom has suggested should work, let me know if it doesn't

**Comment by Moon-developer** [comment]
This was perfect. Thank you 🙏
