### ISSUE TITLE
File permission 1.16.2

### ISSUE THREAD

**Issue by ChikkieNuggie** [mcMMO-Dev/mcMMO#4339]
I recently started a 1.16.2 server with friends and tried adding in mcMMO. I managed to add it to my plugin lists via FTP and have a few commands in game. However no one can gain exp or see their stats, its almost like we dont have the whole plugin. When /plugins is used, mcMMO shows up in green, so the plugin should be working. I'm not sure what to do/how to fix it.

I belive the problem is with:
19.11 19:12:19 [Server] Server thread/ERROR Cannot read /plugins/mcMMO/config.yml(File Permissions?)
19.11 19:12:19 [Server] Server thread/ERROR Cannot read /plugins/mcMMO/experience.yml(File Permissions?)
19.11 19:12:19 [Server] Server thread/ERROR Cannot read /plugins/mcMMO/treasures.yml(File Permissions?)
19.11 19:12:19 [Server] Server thread/ERROR Cannot read /plugins/mcMMO/advanced.yml(File Permissions?)
19.11 19:12:19 [Server] Server thread/ERROR Cannot read /plugins/mcMMO/repair.vanilla.yml(File Permissions?)

I realize that the files dont have the proper permissions, however when I try and give them the proper permissions via FileZilla, the FTP, I get an error: Response 550: not enough privileges.

Any help would fixing the permission problem would be greatly appreciated.

**Comment by PoProstuMieciek** [comment]
Its issue with your FTP client/server. Not the plugin itself.

**Comment by nossr50** [comment]
This is an issue with your server not mcMMO

You give proper file permissions via CLI on linux with the chmod command, I'd avoid using FileZilla to do it as the ftpuser is usually not going to have the right permissions to do that
