### ISSUE TITLE
ChunkUnloadEvent High Timings

### ISSUE THREAD

**Issue by HexedHero** [mcMMO-Dev/mcMMO#4347]
For the past week or so I've been noticing on my timing reports mcMMO normally being the top consumer due to its ChunkUnloadEvent

https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/listeners/WorldListener.java#L87

I'm on v2.1.158, one version out of date but nothing has changed due to chunks on recent commits
https://i.imgur.com/cdmTqLE.jpg

I'm curious if others are having similar issues and what could maybe be done to help minimize the performance hit on this.

**Comment by nossr50** [comment]
You didn't post your timings

**Comment by nossr50** [comment]
No response

**Comment by HexedHero** [comment]
https://timings.aikar.co/?id=ec230173167a4aa29ae3ef678d60c8fd#plugins

**Comment by nossr50** [comment]
@HexedHero Check your timings again after 2.1.156 rolls out, should be improved.
