### ISSUE TITLE
Are there any existing maven repos for this project?

### ISSUE THREAD

**Issue by rbluer** [mcMMO-Dev/mcMMO#4352]
I've been searching for a maven repo that has build artifacts for this project.  

Is there an official maven repo for this github project? If so, what are the connection details?  Also could you add those references to this project's readme.md file too?

I'm asking because I'm trying to build another third-party project that references either a private maven repo, or a repo that has been removing resources in the last few weeks.  

Last thing I want to do is hack together another temp repo out the just to get a successful build, so thought I would first check if there are any official repos out there.

Thanks greatly for your time and assistance!
   Blue

**Comment by garfieldowner** [comment]
Compile yourself?

**Comment by rbluer** [comment]
That kind of defeats the whole purpose of Maven.  I thought that since this has been a pretty successful and wide spread project that it would naturally have a maven repo setup for it.

Compiling this myself just to use the apis just feels too hacky and unprofessional.

But I guess this project has not reached the point of maturity that I was thinking.  That's sad I guess.

Alright... I'll give up my search then.  Thanks for your time.
   Blue

**Comment by garfieldowner** [comment]
I see what you are asking, you want solely the API. I don't think that's available. Your best shot is just compiling yourself as it is _opensource_...

**Comment by TheBusyBiscuit** [comment]
> I've been searching for a maven repo that has build artifacts for this project.
> 
> Is there an official maven repo for this github project? If so, what are the connection details? Also could you add those references to this project's readme.md file too?
> 
> Thanks greatly for your time and assistance!
> Blue
@rbluer 

There is no official Maven repo as of yet.<br>
But there is a third-party Maven repository which also hosts mcMMO and that'd be CodeMC (https://repo.codemc.io/#browse/browse:maven-public).

Here's the Maven reference for it:

```xml
<repository>
    <id>codemc-repo</id>
    <url>https://repo.codemc.org/repository/maven-public</url>
</repository>
```

```xml
<dependency>
    <groupId>com.gmail.nossr50.mcMMO</groupId>
    <artifactId>mcMMO</artifactId>
    <version>2.1.161</version>
    <scope>provided</scope>
```

Again, that is **not the official repository**, but a viable third-party solution for now until an official one is created.<br>
If I remember correctly, nossr50 (the developer of mcMMO) also plans to seperate the API into a seperate entity, so this is all subject to change in the future.


> Compile yourself?
@garfieldowner I think you are missing the point here which a Maven repository is for.<br>
The Maven reference allows developers to **hook** into a project, not to compile it (although that is a theoretical option via shading too).


> Compiling this myself just to use the apis just feels too hacky and unprofessional.
> But I guess this project has not reached the point of maturity that I was thinking. That's sad I guess.
> 
> Alright... I'll give up my search then. Thanks for your time.
> Blue
@rbluer No need to "rage-close" your issue because of one confusing comment tbh. We are on the internet here, not every answer is guaranteed to be completely true and concrete.

**Comment by garfieldowner** [comment]
Sorry. I was just trying to say what I did. Not every solution is perfect.

**Comment by rbluer** [comment]
Hey thanks for the repo info I was unable to find that before.  It now compiles successfully and I'll open a pull request with the original project so they can update their source too.  

I also now see what happened.  The repository ID was changed in the last 4 months, and that explains why it was no longer found.  Same server, but under a different id.

If that repo info could be added somewhere in the docs it would help others too. 

Thanks so much for your help!
  Blue

**Comment by nossr50** [comment]
There is no official repo yet, but there will be in the near future.

**Comment by Oreoezi** [comment]
> There is no official repo yet, but there will be in the near future.

famous last words

**Comment by TheBusyBiscuit** [comment]
> > There is no official repo yet, but there will be in the near future.
> 
> famous last words
@Oreoezi 

*plot twist: there is an official mcMMO maven-repo which went live shortly after that post*
https://nexus.neetgames.com/repository/maven-public/

```xml
<repository>
  <id>mcmmo-repo</id>
  <url>https://nexus.neetgames.com/repository/maven-public</url>
</repository>
```

**Comment by Oreoezi** [comment]
> > > There is no official repo yet, but there will be in the near future.
> > 
> > famous last words
> @Oreoezi 
> 
> *plot twist: there is an official mcMMO maven-repo which went live shortly after that post*
> https://nexus.neetgames.com/repository/maven-public/
> 
> ```xml
> <repository>
>   <id>mcmmo-repo</id>
>   <url>https://nexus.neetgames.com/repository/maven-public</url>
> </repository>
> ```
> 
> 

Didn't notice, sorry. Thanks for letting me know
