### ISSUE TITLE
Timings problem with Mcmmo

### ISSUE THREAD

**Issue by Hadusch** [mcMMO-Dev/mcMMO#4353]
Hello i got a problem with my Timings in TPS since around the end of November this was the highest i got it spikes sometimes 

https://timings.aikar.co/?id=34c5d2ccfe8b4a4da8103baea72240ab

https://timings.aikar.co/?id=c112cb1c6cee4b3e997015d78bc75b64

would be great if someone can Help me on discord i didnt get an answer here seems like a better place, thank you.

**Comment by SrBedrock** [comment]
Probably related to issue #4347 

Tip not having to do with the problem encountered with mcMMO..
If you can, change your startup flag to the one suggested in [this article created by Aikar.](https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/)

**Comment by Hadusch** [comment]
yes might be but i got no clue about it :(

sadly i cant change the Startup flags the hoster permits it and im basically forced to stay on this host^^

**Comment by Hadusch** [comment]
btw im using 2.1.161 but after i had the problem i rolled back from the newest to a outdated version but had the same problem after some time so it may be buggy cause it doesnt happen alle the time

**Comment by nossr50** [comment]
Try running just mcMMO to see if its an issue with mcMMO or another plugin hooking into mcMMO (when plugins hook into mcMMO and do expensive instructions during our events it gets attributed to mcMMO in the timings report, this is one flaw timings)

**Comment by Hadusch** [comment]
hmm dont really wanna run the server too long without the other plugins cause it doesnt happen all the time but i will if it needs to be done but what kind of plugins would hook into mcMMO i got on my Server right now

AncientGates
AntiCreeper
chunkmaster-1.3.2
easybackup-plugin-3.3.4
EssentialsX-2.18.1.0
FirstJoinPlus
Harbor-1.6.3
LogBlock
LuckPerms-Bukkit-5.2.16
mcMMO
modifyworld-1.15.2
Multiverse-Core-4.2.2
Multiverse-Inventories-4.2.1
Multiverse-NetherPortals-4.2.1
OpenInv
PlayerHeads
StackMob-5.3.7
WorldBorder
WorldResetPlus

and ty for the help

**Comment by Hadusch** [comment]
well it didnt happen again since i deleted chunkmaster-1.3.2 cause i didnt need it anymore so maybe that one was the problem or it just didnt happen yet again

**Comment by LucidAPs** [comment]
Same problem here but I also have an issue with the (PlayerQuitEvent) along with (ChunkUnloadEvent)
https://timings.aikar.co/?id=a004830149dd4d4bbf11df0829a4445c
Can we stop mcmmo from being the most taxing plugin on players list please?

**Comment by nossr50** [comment]
Author resolved the issue
