### ISSUE TITLE
CreatureSpawnEvent Error

### ISSUE THREAD

**Issue by 0liverGMC** [mcMMO-Dev/mcMMO#4356]
Running on a test server using Yatopia 1.16.4 and Java 14
Using the version that is in the log (latest on spigot)
https://hastebin.com/latomosuce.properties

**Comment by nossr50** [comment]
That is not the latest mcMMO version, update and also try to see if this error happens on Paper not yatopia

**Comment by nossr50** [comment]
No response from the author
