### ISSUE TITLE
Add setting to allow XP from NPC tagged entities

### ISSUE THREAD

**Issue by ZukiLTU** [mcMMO-Dev/mcMMO#4358]
Hello,
I want to ask if there's a way to get experience while killing NPC's from Citizens plugin ?
If yes, what's the config to do ?

Thanks,
Zuki.

**Comment by nossr50** [comment]
Hmm, well we intentionally prevent XP from things seen as NPC(s) from Citizens normally, I could add a setting to ignore this. Tag me on discord on Monday or sometime this week to remind me and I'll add it in quick!

**Comment by ZukiLTU** [comment]
> Hmm, well we intentionally prevent XP from things seen as NPC(s) from Citizens normally, I could add a setting to ignore this. Tag me on discord on Monday or sometime this week to remind me and I'll add it in quick!

Ping.
