### ISSUE TITLE
Fishing Collisions with Lure Enchantments

### ISSUE THREAD

**Issue by Rynnth** [mcMMO-Dev/mcMMO#4359]
At a high enough level of mcmmo fishing there is a collision with non-vanilla lure enchantments (i.e. Lure 4+). The result of this is no more splashing in the water when fishing and fish will never bite. Is there any fix to this to ensure this interaction doesn't stop you from fishing?

**Comment by nossr50** [comment]
This does not happen on my own test server for Lure 4 and Lure 5, what version of mcMMO?

**Comment by nossr50** [comment]
No response from ticket issuer
