### ISSUE TITLE
[1.16.4] Infinite Acrobatics Exp With No Harm

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [mcMMO-Dev/mcMMO#4360]
Players can farm acrobatics exp by falling in a place where they don't take fall damage. For example, world guard claims with fall damage disabled or having some sort of `/fly` plugin enabled and falling.

I came across this bug on play.cultivatemc.com and after downloading & compiling from the source I could reproduce this bug on Paper 1.16.4.

**Comment by Geekerandy** [comment]
Unable to replicate under these conditions:
1.16.4 Spigot server with mcMMO, Worldguard and WorldEdit
Set a region with fall damage disabled. 
Relogged to clear fall places cache. 
Unable to get xp from it. 
Also unable to get xp with invincibility flag.
Unable to get xp with both Fall Damage and Invincibility flags

I do not own CMI, so I cannot test /fly.

**Comment by PiggiesGoSqueal** [comment]
> 
> 
> Unable to replicate under these conditions:
> 1.16.4 Spigot server with mcMMO, Worldguard and WorldEdit
> Set a region with fall damage disabled.
> Relogged to clear fall places cache.
> Unable to get xp from it.
> Also unable to get xp with invincibility flag.
> Unable to get xp with both Fall Damage and Invincibility flags
> 
> I do not own CMI, so I cannot test /fly.

Peculiar. Maybe is an issue for just those using Paper?

**Comment by nossr50** [comment]
This is likely a bug resulting from other plugins interfering, try removing one plugin at a time until the bug goes away.

**Comment by CERIBES** [comment]
Running the latest version of Paper just a private family server and cannot replicate this. 
mcMMO is the only plugin running.

**Comment by broken1arrow** [comment]
I use cmi and is beter in new versions.

He did a fix and it fix it half way zirps on cmi. You get xp now , but you get easy rolling bug and if you don't have anti cheat on you get xp like was no tomorrow.


If you fall straight down is no problem, but if you walking or shift clicking you get problem. I think it work fine earlyer in the beginning of 1.15 was some versions after that it start the bug.

**Comment by nossr50** [comment]
No response from ticket issuer
