### ISSUE TITLE
SuperBreaker on hand made items?

### ISSUE THREAD

**Issue by andrewkm** [mcMMO-Dev/mcMMO#4362]
Recently got a report that states:

Trying to activate super breaker on hand made items such as smooth stone does not work.
However if you activate super breaker on normal stone, and then switch over to the smooth stone it works.

Is this intended?
Seems like a bug...

Thoughts?

**Comment by nossr50** [comment]
Sounds like a bug, I'll go see if I can replicate it.

**Comment by nossr50** [comment]
Working on a fix for this now, will be part of 2.1.156

**Comment by nossr50** [comment]
Fixed in dev

**Comment by andrewkm** [comment]
Confirmed fixed <3
