### ISSUE TITLE
Why is fishing giving me constant double treasures?

### ISSUE THREAD

**Issue by andrewkm** [mcMMO-Dev/mcMMO#4363]
Ever since the latest update, fishing is always giving me double treasures.
This is my fishing rank: https://i.imgur.com/fkzvkYQ.png
No matter what I do it is always a double treasure. Any ideas why?
Video: https://youtu.be/PFcXSAv1pRQ
fishing_treasures.yml: https://pastebin.com/raw/jLpAGNLY

**Comment by nossr50** [comment]
Likely reason is another plugin is shooting this event twice or doing weird stuff with mcMMO fishing and the code change has caused issues for it.

**Comment by andrewkm** [comment]
@electronicboy any thoughts?
This has been happening since your latest mcmmo update @nossr50

**Comment by nossr50** [comment]
Should be fixed in dev

**Comment by andrewkm** [comment]
Confirmed fixed <3
