### ISSUE TITLE
Spark depend shooting warning on startup.

### ISSUE THREAD

**Issue by andrewkm** [mcMMO-Dev/mcMMO#4364]
`[21:59:47] [Server thread/WARN]: [mcMMO] Loaded class net.kyori.examination.Examinable from spark v1.4.3 which is not a depend, softdepend or loadbefore of this plugin.`
Please fix for my OCD mind.

**Comment by nossr50** [comment]
Examinable is used by mcMMO (it's from the adventure library) and is not plugin specific, perhaps Spark isn't doing proper shadowing/relocation and they also use this library? I'm not sure.

**Comment by nossr50** [comment]
My bad, wasn't properly relocating this library.
