### ISSUE TITLE
latest has startup shit going down.

### ISSUE THREAD

**Issue by andrewkm** [mcMMO-Dev/mcMMO#4367]
https://gist.githubusercontent.com/andrewkm/4f9aae047792eb87bd7d9da6112625b8/raw/789fb4be7f0cc7711e1973290aceef20c8173015/gistfile1.txt

PS: Discord bruh

**Comment by nossr50** [comment]
This issue is already fixed, I don't recommend using dev builds in a production environment.

**Comment by andrewkm** [comment]
I'm not using it in a production environment, why make assumptions?

**Comment by nossr50** [comment]
Wasn't assuming, just mentioning it in case. :)

**Comment by andrewkm** [comment]
Confirmed fixed <3
