### ISSUE TITLE
[BUG] /mctop <skill> stopped working

### ISSUE THREAD

**Issue by SrBedrock** [mcMMO-Dev/mcMMO#4372]
### Error description:

The `/mctop <skill>` command stopped working after the 2.1.168 update, it suggests commands in English but I translated all the skills into my language.

### More information:

Command on version `2.1.167` (name of skills translated into my language and working)

![image](https://user-images.githubusercontent.com/51332006/103609260-39993880-4efc-11eb-8f03-da82792a8712.png)

Command on version `2.1.168` (if i try to use the command an error message is sent: `Commands.Skill.Invalid`)

![image](https://user-images.githubusercontent.com/51332006/103609107-ddceaf80-4efb-11eb-9de5-425e494944e5.png)

**Comment by nossr50** [comment]
Thanks I think I know what is causing this, I'll have it patched in the near future.
