### ISSUE TITLE
Level up broadcast not supported hex color codes on rank prefix

### ISSUE THREAD

**Issue by andris155** [mcMMO-Dev/mcMMO#4378]
![104090437-0b5a8680-5277-11eb-9291-8fc3edf1c21b](https://user-images.githubusercontent.com/8324198/104090519-989ddb00-5277-11eb-98e5-0aed751362cf.png)

<img width="397" alt="Screenshot 2021-01-09 124007" src="https://user-images.githubusercontent.com/8324198/104090563-d7339580-5277-11eb-9c36-5e2ed180809e.png">

mcMMO version 2.1.171
Server: Yatopia 1.16.4

**Comment by SrBedrock** [comment]
Message:
![image](https://user-images.githubusercontent.com/51332006/104379076-b71a0580-5507-11eb-973b-4020cec279c8.png)

Nick:
![image](https://user-images.githubusercontent.com/51332006/104379127-c6994e80-5507-11eb-8c3c-c5a9b2cda0d7.png)
