### ISSUE TITLE
unable to change admin chat color

### ISSUE THREAD

**Issue by kuraiskrap** [mcMMO-Dev/mcMMO#4380]
says (AdminChat) now instead of just (A) so file is being used, 

FILE: /home/container/plugins/mcMMO/locales/locale_en_US.properties

#Modern Chat Settings
Chat.Style.Admin=&b(AdminChat) &r{0} &b\u2192 &r{1}&e

**Comment by nossr50** [comment]
You are editing it wrong
For example, the default is
`Chat.Style.Admin=&b(A) &r{0} &b\u2192 &r{1}`

If I change this to

'Chat.Style.Admin=&b(A) &r{0} &b\u2192 &6{1}'

Then the text has become gold, notice the r at the end (reset color) has been changed to 6 (gold color)
