### ISSUE TITLE
If a player uses Super Breaker, changes bungee servers, then places the pickaxe in a chest, the enchantment remains on the pick

### ISSUE THREAD

**Issue by JacksonWillford** [mcMMO-Dev/mcMMO#4381]
I am running mcMMO 2.1.158

Steps to reproduce
1. Activate super breaker
2. Switch to a different bungee server (a notification will show that super breaker is done)
3. Place the pick to a chest

Sometimes the enchant will remain even after switching servers and doesn't require placing the pick into a chest.

I've also observed that subsequent uses of super breaker may upgrade the pick a further 5 efficiency levels. Sometimes all efficiency levels are removed after super breaker is complete, but not always.

It seems that the enchant is not being properly removed after a player teleports between servers.

**Comment by JacksonWillford** [comment]
Just replicated this by simply moving the pick around in my inventory

**Comment by nossr50** [comment]
You are on a very old version of mcMMO, you should update.
Enchantments are left on "boosted" tools that are taken out of an inventory prematurely until someone tries to use them, the reason mcMMO isn't more aggressive about this in particular is to save on performance, we wait until the last moment to check for tools that are boosted when they shouldn't be. However upon writing this there are other places we can add some removal checks for better consistency.
