### ISSUE TITLE
Massive tps drops

### ISSUE THREAD

**Issue by unholymac** [mcMMO-Dev/mcMMO#4385]
Heya im getting massive tps drops when people are farming
https://timings.aikar.co/?id=eeb21985a3be496d8850f4b01982f403

**Comment by unholymac** [comment]
This is a timings report i just created and its definitely when people are farming
https://timings.aikar.co/?id=8ded8b9c27894166bf5ddaafeb362209

**Comment by unholymac** [comment]
I have updated to the latest version of the plugin and the latest paper version and this is the timings report - https://timings.aikar.co/?id=0619255f67cb41aba516325ac0c86027

Issue seems to be worse than tuinity

**Comment by t00thpick1** [comment]
this was determined to be a permissions plugin issue unrelated to mcMMO.
