### ISSUE TITLE
Archery Skill "Retrieve" works with infinity

### ISSUE THREAD

**Issue by w1tcherrr** [mcMMO-Dev/mcMMO#4389]
Hey, a little bug (or feature?) report.

When you use a bow with archery up at lvl 1000 the "Retrieve" skill allows you to get your arrow back 100% of the time. This I assume is not intended to work with infinity. However when you use infinity the retrieve skill still works and you get an arrow each time you kill a mob (obviously by the "Retrieve" Skill activating).

**Comment by Momshroom** [comment]
What version are you on?  This was recently fixed.

**Comment by w1tcherrr** [comment]
2.1.170

**Comment by nossr50** [comment]
This was fixed in 2.1.171
