### ISSUE TITLE
Hard-coded translation message ''Data has not yet been loaded''

### ISSUE THREAD

**Issue by Sikatsu** [mcMMO-Dev/mcMMO#4391]
When I join the server and I immediatly start using the party chat, this message shows up and I can not seem to translate it.

![image](https://user-images.githubusercontent.com/5664135/104714505-9202de00-5725-11eb-84d9-49c9b240c613.png)

**Comment by Remski01** [comment]
Yes, mcmmo have a delay on loading you're data.

**Comment by Sikatsu** [comment]
I know that, just would like to translate the message for players.

**Comment by TheBusyBiscuit** [comment]
> Yes, mcmmo have a delay on loading you're data.

@Remski01 Though that message is not translatable, it is hardcoded, as seen here:
https://github.com/mcMMO-Dev/mcMMO/blob/4abf64f6257ff0e1232b96531339bcfa28a8112e/src/main/java/com/gmail/nossr50/commands/CommandManager.java#L99-L103

Ideally, this message should have been loaded from `Commands.NotLoaded` or `Profile.PendingLoad`.

**Comment by nossr50** [comment]
Stuff like this is really my laziness, I tend to be lazy when it comes to errors/etc and locale, I'll try to localize this and other messages

**Comment by Sikatsu** [comment]
Thanks, mostly wanna translate it since players can see it ^^
