### ISSUE TITLE
[Feature Request] Disable XP gain in specific dimensions

### ISSUE THREAD

**Issue by MithicSpirit** [mcMMO-Dev/mcMMO#4392]
I'm on a server where the admins consider the Nether and End too OP for mcMMO XP, so they've had to disable mcMMO altogether in those dimensions, but then we can't benefit from any of our mcMMO in those dimensions. It would be nice if we could just disable mcMMO XP gain in those dimensions (if this is already possible I couldn't find it in the wiki so maybe that should be updated to be clearer).

**Comment by nossr50** [comment]
If its only the XP you want disabled the only solution right now is to make use of our WG region flag support, we have a WG region flag for XP and if you deny it, then they won't gain XP

'mcmmo-xp' is the flag for this in our World Guard support

**Comment by MithicSpirit** [comment]
Alright, that's exactly what I was looking for. Thank you.
