### ISSUE TITLE
Some commands don't disappear from the tab completion menu despite lack of permission to use them

### ISSUE THREAD

**Issue by TheosisOfficial** [mcMMO-Dev/mcMMO#4396]
The title pretty much says it all - the only commands I've found so far that behave this way are `/adminchat` and `/partychat`, but there could be more.

Some arguments also behave this way too - for example, all skills show up for the first argument of the `/mctop` command, whereas only the skills the player has access to should (or this should at least be configurable for those who want to disable certain skills on their server and have done so via negating permissions).

**Comment by nossr50** [comment]
I'll look into this issue, both adminchat and partychat use ACF so I might have missed something when setting them up.

**Comment by TheosisOfficial** [comment]
Hey, I notice you've just fixed this in the newest release which is awesome, but there's a small problem.

If someone tries to use the command, it seems to send them a "no permission" message that is neither from the mcMMO locale nor the default permission message - it sends this one:
![image](https://user-images.githubusercontent.com/26799016/105426907-f4873d00-5c43-11eb-8eb0-1253dd04cb10.png)
