### ISSUE TITLE
bug heart mariagemaster

### ISSUE THREAD

**Issue by istarengwa** [mcMMO-Dev/mcMMO#4398]
Hello, I come to see you for a minimal bug but which makes all the difference on my server, people married either with their hearts in the chat in front of their rank / nickname. This error is only active when the mcmmo plugin is active, no error in the console on the part of the 2 plugins, this has not always been the case, it is since some updates of mcmmo but I could not say which. 

I'm currently looking for the version it works with and tell you.

**Comment by nossr50** [comment]
I'm sorry I'm not sure I understand the issue?

**Comment by istarengwa** [comment]
Hello sorry I no longer had access to my github account.

After 16 hours of testing, I found the real cause of the problem, it was the ultimate stacker plugin that caused this, but the same in relation to mcmmo, so mcmmo is not wrong, but mcmmo, with ultimate stacker, breaks the master marriage prefix. You can close the ticket. But so if someone else comes to you talk about it you know the cause of the problem (which is not your plugin)

I love your work with all my heart =D
