### ISSUE TITLE
Not an issue, just a question/idea. Fishing durability loss.

### ISSUE THREAD

**Issue by Ane5577** [mcMMO-Dev/mcMMO#4401]
Is there or will there be a way to disable the increased fishing rod use in the current build?
I'm trying to make my server feel like vanilla but wil the McMMO plugin as an extra feature that enhances, rather than hinders, the experience. Having fishing rods enchanted with Unbreaking 3 break within an hour of fishing is getting a little old, I've gotta be honest.

**Comment by nossr50** [comment]
mcMMO won't do this anymore in the next release
