### ISSUE TITLE
Hex color codes not works perfectly on the party chat

### ISSUE THREAD

**Issue by andris155** [mcMMO-Dev/mcMMO#4402]
Hex color codes:
&#33FF8Ea&#84FF33b
The correct colors:
<img width="196" alt="Screenshot 2021-01-23 141029" src="https://user-images.githubusercontent.com/8324198/105579114-c3625600-5d84-11eb-9ada-ee9bd18d5160.png">
The colors on the party chat:
<img width="184" alt="Screenshot 2021-01-23 141107" src="https://user-images.githubusercontent.com/8324198/105579133-d9701680-5d84-11eb-8690-ab8c631ba666.png">

mcMMO version 2.1.172
1.16.5

**Comment by TheBusyBiscuit** [comment]
Do you have the permission node `mcmmo.chat.colors`?
Because if not, then hex colors are going to fallback to the nearest valid chatcolor which sounds like what is happening here.

**Comment by andris155** [comment]
I tested with op permissions.

**Comment by nossr50** [comment]
Thanks, I'll look into this.
