### ISSUE TITLE
Lucky Perk math issue

### ISSUE THREAD

**Issue by austv** [mcMMO-Dev/mcMMO#4405]
After adding **mcmmo.perks.lucky.all** permission, I went to check the new percentages. I saw that there was an error in the account and that the 33% chance applied **twice**.

This is a print of the normal skill, without any permission and perk: https://prnt.sc/xio99s

This is a photo after adding the permission described above: https://prnt.sc/xio9cl

According to my accounts, the 33% chance increase account was applied twice:
37,5 * 1,33 = 49,875
49,875 * 1,33 = 66,3

Is that correct? I thought and would like it 49.8 as final chance with the perk. I tested with players without any other permission and without an operator. Everything working that way.

**Comment by nossr50** [comment]
Thanks for the report, I'll look into it on Monday.
