### ISSUE TITLE
Security Vulnerability - Jenkins

### ISSUE THREAD

**Issue by thisismygithubok** [mcMMO-Dev/mcMMO#4414]
Hey, just thought you'd like to know that currently your Jenkins server is publicly accessible, allowing anyone to download the plugin without having paid for it - https://popicraft.net/jenkins/job/mcMMO/

**Comment by t00thpick1** [comment]
This is intentional although purposefully not advertised.

**Comment by thisismygithubok** [comment]
@t00thpick1 - gotcha, please feel free to edit and remove the URL from my ticket.
