### ISSUE TITLE
Replacing treasure with Salmon causes incompatibilities with other plugins

### ISSUE THREAD

**Issue by Kunfury-blep** [mcMMO-Dev/mcMMO#4428]
https://github.com/mcMMO-Dev/mcMMO/blob/f9144e624ab9d96f052dfe18ecded6703a2f33ff/src/main/java/com/gmail/nossr50/listeners/PlayerListener.java#L299

MCMMO turns vanilla treasure into salmon before running it's treasure handler on them. This causes issues with other plugins that watch for when vanilla fish are caught (specifically my plugin [Blep Fishing](https://www.spigotmc.org/resources/blep-fishing.78555/)), especially with MCMMO utilizing the "HIGHEST" event priority for the PlayerFishEvent. A quick and easy fix to this would be to just change the item from a salmon to a massively uncommon block such as AIR.

**Comment by rochadvdgit** [comment]
Please Devs, just change the priority onPlayerFishHighest to at least HIGH and let all us be happy using others plugins too. PLEASE!

**Comment by nossr50** [comment]
I made the changes suggested, I also added a new event (McMMOReplaceVanillaTreasureEvent) to further help with compatibility if needed

**Comment by SmallSansSerif** [comment]
Not sure if this is a result of change: https://pastebin.com/YHFAyJPj
