### ISSUE TITLE
mcMMo and SlimeFun Item compatibility issues

### ISSUE THREAD

**Issue by Evil0ctal** [mcMMO-Dev/mcMMO#4433]
When the mcMMO and Slimefun plugin are used at the same time(Paper Spigot server 1.16.5), if player A (reaching the slimefun mining level to unlock some specific pickaxes) throws these pickaxes to player B (player B does not reach the slimefun level using the item of the pickaxe ), when player B tries to mine block with the SlimeFun pickaxe given by player A, the slimefun plugin will remind player B that the level is insufficient and cant allow you use this pickaxe,  and slimefun plugin will restore the block that player B destroyed, but the mcMMO plugin will drop gold coins even the block had been restored, and the player B can use this loophole to keep mining one Block to earn unlimited gold coins.The block and item wont consume.

**Comment by nossr50** [comment]
Not mcMMO
