### ISSUE TITLE
Wolves don't avoid magma

### ISSUE THREAD

**Issue by fettered** [mcMMO-Dev/mcMMO#4443]
Wolves are programmed to dodge environmental hazards with mcmmo. 

However, after magma blocks were added this behavior was not updated. 

Wolves will not avoid magma and will take unnecessary damage and die.

The wolf pathfinding should be updated to include magma blocks as a hazard OR environmental conditioning should render them immune to magma based fire damage.

**Comment by fettered** [comment]
Note that wolves likely also don't recognize wither roses as dangerous

**Comment by nossr50** [comment]
I added magma blocks to Environmentally aware
