### ISSUE TITLE
[Minor Issue] Update 8 year old party DB schema update code

### ISSUE THREAD

**Issue by andrewkm** [mcMMO-Dev/mcMMO#4447]
https://gist.githubusercontent.com/andrewkm/1992f677faaa5f927132ac9742fad7d1/raw/8a66036acd23cf6476924acb8e4e6bb7ac2d9edc/gistfile1.txt

Paper 1.16.5 - 541
mcMMO built on: https://github.com/mcMMO-Dev/mcMMO/commit/6c69cd2aea04a503a9e76b9e8e05a89edfa77daf
Using mySQL.

No issues prior to DB changes.

**Comment by nossr50** [comment]
I deployed a hacky fix for this in https://github.com/mcMMO-Dev/mcMMO/commit/e8a0e6e4a48acb65ca3647e6a95f5504de4f6abe
A real fix will come later, it will  only be an issue for people upgrading from an 8 year old version of mcMMO to modern which is hopefully no one (this update should be safe for 99.9% of users)
