### ISSUE TITLE
[Bug] Death Messages issue by Mcmmo (After paper adventure update)

### ISSUE THREAD

**Issue by slvlr** [mcMMO-Dev/mcMMO#4448]
I reported it to Paper, but it turns out it's Mcmmo causing the issue: https://github.com/PaperMC/Paper/issues/5332

Death messages are no longer displaying in colour, and the item text is no longer "hoverable" 
Mcmmo build 2.1.179

**Comment by nossr50** [comment]
Duplicate of #4463
