### ISSUE TITLE
mcMMO name change bug / Weakness potion bug

### ISSUE THREAD

**Issue by LtSam** [mcMMO-Dev/mcMMO#4450]
There is a bug in offline mode servers (i didn't tested on online mode), it keep spamming on console. The message is like this: [mcMMO] Name change detected: samuka321 => 
This account samuka321 is mine, but i didn't change my nickname

And there is another bug(don't know if i'ts mcmmo related), for some reason, when a player is with weakness effect, they can't hit with hands, only with weapons

**Comment by Remski01** [comment]
Hello, what is the full line before [McMMO], 

We have seen reports like this this what tutned to be not related to McMMO, but by the Plan plugin hooks into McMMO. Do you have this plugin? If yes. Try to turn off the McMMO hook, if that fixed the spam. Report it to the Plan plugin dev. If you do have the plugin. Ignore this message.

**Comment by nossr50** [comment]
Make a separate issue for the weakness bug
