### ISSUE TITLE
mcMMO breaks death messages for kills using renamed items

### ISSUE THREAD

**Issue by WhatsTheBadNews** [mcMMO-Dev/mcMMO#4463]
Tested with just Paper & mcMMO

mcMMO version: 2.1.181
Paper Version: 565 MC 1.16.5

How it should look:
![image](https://user-images.githubusercontent.com/29821149/112130417-7806d100-8b96-11eb-858a-b3fbf763f97b.png)

You should also be able to hover over the item for details, like so:
![image](https://user-images.githubusercontent.com/29821149/112130510-9076eb80-8b96-11eb-882f-fd04779d532b.png)

How it looks like with mcMMO:
![image](https://user-images.githubusercontent.com/29821149/112130162-2d855480-8b96-11eb-8608-8696e641cff8.png)

**Comment by TheBusyBiscuit** [comment]
Highly likely to be related to #4448, your Paper version backs that up to.

**Comment by lexikiq** [comment]
this also breaks any plugins attempting to use translatable death messages via Adventure due to it running as lowest priority
