### ISSUE TITLE
/mcstats causing NPE.

### ISSUE THREAD

**Issue by andrewkm** [mcMMO-Dev/mcMMO#4464]
https://pastebin.com/raw/XJceA68J
Built on: https://github.com/mcMMO-Dev/mcMMO/tree/2c5e11138bbae840961ac0566d4b8484156ea367

**Comment by nossr50** [comment]
Will look into this soon-ish

**Comment by nossr50** [comment]
Does this still occur after 2.1.182?

**Comment by andrewkm** [comment]
Fixed :)
