### ISSUE TITLE
Treasures of Excavation, all skill level required: 0

### ISSUE THREAD

**Issue by Silmarost** [mcMMO-Dev/mcMMO#4471]
Hi, I have a problem since the last update (2.1.183) with the excavation treasures, the level of the excavation is no longer taken into account (all treasures are obtained regardless of the level, even level 1).. (i suppose that this  is this modification wich have broken the level detection of each tresor treasures. yml now has separate settings for Drop_Level for Standard / Retro mode). I have try with the native config of plugin and it is the same (same for standard / Retro mode). Thank you in advance for you're help.
When i do /mcmmodebugmode (when I do /mmodebug, I have nothing apart this sentence “not enough args.) and I whack sand, I have this:, 
![test2](https://user-images.githubusercontent.com/52896544/113214490-de1be400-9279-11eb-81a4-aa6d8eb614d9.png)
the skill level required is 0 for all.
I  have tried before my custom files at the beginning but here it is all the default file (all are new files).

treasures.yml (https://pastebin.com/L2yt2LXk)
log  (https://pastebin.com/RAgSW0Kj)

**Comment by nossr50** [comment]
This was fixed
