### ISSUE TITLE
[BUG] Super Breaker keep the dig_speed enchantment with item frame

### ISSUE THREAD

**Issue by Rothes** [mcMMO-Dev/mcMMO#4474]
## Steps to reproduce:

1.Activate Super Breaker Skill with a pickaxe
2.Put the pickaxe in a item frame
3.Wait for the skill to end
4.Remove the pickaxe from the frame.
5.The dig_speed enchant doesn't remove.
6.Repeat the operation. You can get unlimited enchantment level.

## Plugins:
Plugins (56): AAC5, AACAdditionPro, AntiSeedCracker, Ath, AutoBroadcastLite, BBSToper*, BetterEnchantBook*, BloodMoon, BungeeTabListPlus, ChanLang, CMI, CMIEInjector*, CMILib, CMIPaperLib, ColorMOTD*, CoreProtect, CoreProtectTNT, Guilds, HeadDatabase, InteractiveChat, InventoryRollbackPlus, JukeBox, LockettePro, LuckPerms, mcMMO, Multiverse-Core, NeverLag*, NoteBlockAPI, OpenInv, Patch4, PlaceholderAPI, PlayerCustomPlus, PlayerPoints*, PlugMan, ProtocolLib, QuickShop, Residence, RothesExpansion, Slimefun, SlimefunItemId*, spark, Stp*, Stratos, StringReplacer, Terra, TitleManager, TrMenu, Vault, ViaBackwards, ViaRewind, ViaVersion, WGAcheck, WorldEdit, WorldEditSUI, WorldLagManager, XrayNotifier*

## Server:
This server is running Tuinity version git-Tuinity-"1b0d783" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

## mcMMo version:
[mcMMO] Running version 2.1.184

**Comment by nossr50** [comment]
The item has NBT data marking it as being "buffed", the next time you try to use it mcMMO will clear the buffs from it. This is how mcMMO handles it if you try to use a buffed item outside of the ability duration.

**Comment by Rothes** [comment]
Opps sorry, I missed a condition.
After getting the enchantment, place it in the Auto-Disenchanter of Slimefun through the hopper. But I think I should go to the issue Tracker of Slimefun now. Thanks.

**Comment by nossr50** [comment]
Yeah this would need to be fixed on their end
