### ISSUE TITLE
[Bug] UltimateTimber bug (apparently mcMMO is the cause)

### ISSUE THREAD

**Issue by TheosisOfficial** [mcMMO-Dev/mcMMO#4480]
Hello, I use a plugin called [UltimateTimber](https://songoda.com/marketplace/product/ultimatetimber-the-realistic-tree-chopper.18) which has mcMMO compatibility. I noticed an exception that happened in a certain situation, so I created a bug report to the UltimateTimber developers. The bug report is [here](https://support.songoda.com/plugins/servlet/desk/portal/3/SD-8009). One of the developers said that it seems like mcMMO is causing the bug and to report here, so here I am. :)

**Comment by TheBusyBiscuit** [comment]
Can you please post that exception here (preferabbly via pastebin or similar), as well as your mcMMO version?
It seems like that site requires a login to view the actual bug report.

**Comment by TheosisOfficial** [comment]
> Can you please post that exception here (preferabbly via pastebin or similar), as well as your mcMMO version?
> It seems like that site requires a login to view the actual bug report.

Sorry, I forgot that you had to log into the website. I've just reproduced the issue using the latest mcMMO version and latest UT version, here is the exception: https://pastebin.com/hnbFn9z3.

**Comment by nossr50** [comment]
Well at a glance it appears they are passing null values into our API, seems like that would be a mistake on their end to me.

**Comment by TheosisOfficial** [comment]
> Well at a glance it appears they are passing null values into our API, seems like that would be a mistake on their end to me.

I will bring this back to them then, thank you. :)
