### ISSUE TITLE
Essentials nicknames using HEX display incorrectly via PartyChat.

### ISSUE THREAD

**Issue by andrewkm** [mcMMO-Dev/mcMMO#4487]
Essentials nicknames that use the new HEX: https://i.imgur.com/CbjM0nV.png
Are completely broken in Party chat: https://i.imgur.com/cBmlh74.png

**Comment by Revanrose6** [comment]
Also broken for ChatControlRed Hexcolor Nicknames. Which means its probably just all Hexcolor Codes.
<img width="332" alt="Screen Shot 2021-04-12 at 12 02 04 PM" src="https://user-images.githubusercontent.com/6682989/114447151-eaac1080-9b86-11eb-8eaa-d95975a29139.png">
<img width="277" alt="Screen Shot 2021-04-12 at 12 01 50 PM" src="https://user-images.githubusercontent.com/6682989/114447153-eb44a700-9b86-11eb-9c45-0a53d2718ece.png">

**Comment by nossr50** [comment]
This will be looked into soon, hopefully fixed this week.

**Comment by nossr50** [comment]
I'm not sure how to reproduce this one, loaded up the EssentialsX dev build and the latest mcMMO and it is working for me

![Screenshot from 2021-04-14 16-45-29](https://user-images.githubusercontent.com/407458/114800305-55f40f00-9d4e-11eb-8149-263d248f9330.png)

**Comment by Agaloth** [comment]
Try using the release essentials and not dev builds?

**Comment by nossr50** [comment]
> Try using the release essentials and not dev builds?

What would be the point? That means they fixed it on their end and you just have to wait until they put out an update.

**Comment by andrewkm** [comment]
Fixed.
Issue was that users did not have the **mcmmo.chat.colors** permissions.
God bless LuckPerms verbose. :)
