### ISSUE TITLE
i keep getting build failure when i do mvn clean package install

### ISSUE THREAD

**Issue by HeresJohnny320** [mcMMO-Dev/mcMMO#4490]
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------< com.gmail.nossr50.mcMMO:mcMMO >--------------------
[INFO] Building mcMMO 2.1.189-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ mcMMO ---
[INFO] Deleting G:\own-git-server\minecraft-shit\mcMMO\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ mcMMO ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 19 resources to .
[INFO] Copying 21 resources to com/gmail/nossr50/locale
[INFO] Copying 4 resources to mods
[INFO] Copying 1 resource to .
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ mcMMO ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 470 source files to G:\own-git-server\minecraft-shit\mcMMO\target\classes
[INFO] /G:/own-git-server/minecraft-shit/mcMMO/src/main/java/com/gmail/nossr50/skills/axes/AxesManager.java: Some input files use or override a deprecated API.
[INFO] /G:/own-git-server/minecraft-shit/mcMMO/src/main/java/com/gmail/nossr50/skills/axes/AxesManager.java: Recompile with -Xlint:deprecation for details.
[INFO] /G:/own-git-server/minecraft-shit/mcMMO/src/main/java/com/gmail/nossr50/commands/database/ConvertDatabaseCommand.java: G:\own-git-server\minecraft-shit\mcMMO\src\main\java\com\gmail\nossr50\commands\database\Convert
DatabaseCommand.java uses unchecked or unsafe operations.
[INFO] /G:/own-git-server/minecraft-shit/mcMMO/src/main/java/com/gmail/nossr50/commands/database/ConvertDatabaseCommand.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ mcMMO ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ mcMMO ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 9 source files to G:\own-git-server\minecraft-shit\mcMMO\target\test-classes
[INFO] /G:/own-git-server/minecraft-shit/mcMMO/src/test/java/com/gmail/nossr50/database/FlatFileDatabaseManagerTest.java: G:\own-git-server\minecraft-shit\mcMMO\src\test\java\com\gmail\nossr50\database\FlatFileDatabaseMana
gerTest.java uses or overrides a deprecated API.
[INFO] /G:/own-git-server/minecraft-shit/mcMMO/src/test/java/com/gmail/nossr50/database/FlatFileDatabaseManagerTest.java: Recompile with -Xlint:deprecation for details.
[INFO]
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ mcMMO ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.gmail.nossr50.database.FlatFileDatabaseManagerTest
Added the following lines to the FlatFileDatabase for the purposes of the test...
mochi:1000:::0:1000:640:1000:1000:1000:1000:1000:1000:1000:1000:16:0:500:0:0:0:0:0::1000:0:0:0:1593543012:0:0:0:0::1000:0:0:1593806053:HEARTS:1000:0:588fe472-1c82-4c4e-9aa1-7eefccb277e3:0:0:
mochi:1000:::0:1000:640:1000:1000:1000:1000:1000:1000:1000:1000:16:0:500:0:0:0:0:0::1000:0:0:0:1593543012:0:0:0:0::1000:0:0:1593806053:HEARTS:1000:0:631e3896-da2a-4077-974b-d047859d76bc:0:0:
Apr. 14, 2021 9:34:29 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: (C:\Users\johna\AppData\Local\Temp\1618414469695-0\test.mcmmo.users) Validating database file..
Apr. 14, 2021 9:34:29 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: Saving the updated and or repaired FlatFile Database...
File Path: C:\Users\johna\AppData\Local\Temp\1618414469798-0\healthydb.users
Apr. 14, 2021 9:34:29 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: (C:\Users\johna\AppData\Local\Temp\1618414469798-0\healthydb.users) Validating database file..
File Path: C:\Users\johna\AppData\Local\Temp\1618414469866-0\healthydb.users
Apr. 14, 2021 9:34:29 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: (C:\Users\johna\AppData\Local\Temp\1618414469866-0\healthydb.users) Validating database file..
Apr. 14, 2021 9:34:29 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: (C:\Users\johna\AppData\Local\Temp\1618414469888-0\test.mcmmo.users) Validating database file..
-- saveUser bufferedreader feed --
# mcMMO Database created on 2021/04/14 09:34:29
-- saveUser (FileWriter contents before save) --
# mcMMO Database created on 2021/04/14 09:34:29
nossr50:0:IGNORED:IGNORED:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:IGNORED:0:0:0:0:0:0:0:0:0:IGNORED:0:0:0:IGNORED:IGNORED:0:0:588fe472-1c82-4c4e-9aa1-7eefccb277e3:0:0:1618414469889:

Added the following lines to the FlatFileDatabase for the purposes of the test...
nossr50:1000:::0:1000:640:1000:1000:1000:1000:1000:1000:1000:1000:16:0:500:0:0:0:0:0::1000:0:0:0:1593543012:0:0:0:0::1000:0:0:1593806053:HEARTS:1000:0:588fe472-1c82-4c4e-9aa1-7eefccb277e3:0:0:
mrfloris:2420:::0:2452:0:1983:1937:1790:3042:1138:3102:2408:3411:0:0:0:0:0:0:0:0::642:0:1617583171:0:1617165043:0:1617583004:1617563189:1616785408::2184:0:0:1617852413:HEARTS:415:0:631e3896-da2a-4077-974b-d047859d76bc:5:16
00906906:
powerless:0:::0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0::0:0:0:0:0:0:0:0:0::0:0:0:0:HEARTS:0:0:e0d07db8-f7e8-43c7-9ded-864dfc6f3b7c:5:1600906906:
Apr. 14, 2021 9:34:29 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager purgePowerlessUsers
INFO: Purging powerless users...
Apr. 14, 2021 9:34:29 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager purgePowerlessUsers
INFO: Purged 1 users from the database.
Added the following lines to the FlatFileDatabase for the purposes of the test...
nossr50:1000:::0:1000:640:1000:1000:1000:1000:1000:1000:1000:1000:16:0:500:0:0:0:0:0::1000:0:0:0:1593543012:0:0:0:0::1000:0:0:1593806053:HEARTS:1000:0:588fe472-1c82-4c4e-9aa1-7eefccb277e3:0:0:
mrfloris:2420:::0:2452:0:1983:1937:1790:3042:1138:3102:2408:3411:0:0:0:0:0:0:0:0::642:0:1617583171:0:1617165043:0:1617583004:1617563189:1616785408::2184:0:0:1617852413:HEARTS:415:0:631e3896-da2a-4077-974b-d047859d76bc:5:16
00906906:
electronicboy:0:::0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0::0:0:0:0:0:0:0:0:0::0:0:0:0:HEARTS:0:0:e0d07db8-f7e8-43c7-9ded-864dfc6f3b7c:
Apr. 14, 2021 9:34:29 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: (C:\Users\johna\AppData\Local\Temp\1618414469917-0\test.mcmmo.users) Validating database file..
Apr. 14, 2021 9:34:29 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: Saving the updated and or repaired FlatFile Database...
Added the following lines to the FlatFileDatabase for the purposes of the test...
nossr50:1000:::0:1000:640:1000:1000:1000:1000:1000:1000:1000:1000:16:0:500:0:0:0:0:0::1000:0:0:0:1593543012:0:0:0:0::1000:0:0:1593806053:HEARTS:1000:0:588fe472-1c82-4c4e-9aa1-7eefccb277e3:0:0:
mrfloris:1000:::0:1000:640:1000:1000:1000:1000:1000:1000:1000:1000:16:0:500:0:0:0:0:0::1000:0:0:0:1593543012:0:0:0:0::1000:0:0:1593806053:HEARTS:1000:0:588fe472-1c82-4c4e-9aa1-7eefccb277e3:0:0:
Apr. 14, 2021 9:34:29 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: (C:\Users\johna\AppData\Local\Temp\1618414469929-0\test.mcmmo.users) Validating database file..
Apr. 14, 2021 9:34:29 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: Saving the updated and or repaired FlatFile Database...
Added the following lines to the FlatFileDatabase for the purposes of the test...
mochi:1000:::0:1000:640:1000:1000:1000:1000:1000:1000:1000:1000:16:0:500:0:0:0:0:0::1000:0:0:0:1593543012:0:0:0:0::1000:0:0:1593806053:HEARTS:1000:0:588fe472-1c82-4c4e-9aa1-7eefccb277e3:0:0:
mochi:1000:::0:1000:640:1000:1000:1000:1000:1000:1000:1000:1000:16:0:500:0:0:0:0:0::1000:0:0:0:1593543012:0:0:0:0::1000:0:0:1593806053:HEARTS:1000:0:631e3896-da2a-4077-974b-d047859d76bc:0:0:
Apr. 14, 2021 9:34:29 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: (C:\Users\johna\AppData\Local\Temp\1618414469947-0\test.mcmmo.users) Validating database file..
Apr. 14, 2021 9:34:29 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: Saving the updated and or repaired FlatFile Database...
Added the following lines to the FlatFileDatabase for the purposes of the test...
nossr50:1000:0:500:0:0:0:0:0::1000:0:0:0:1593543012:0:0:0:0::1000:0:0:1593806053:HEARTS:1000:0:588fe472-1c82-4c4e-9aa1-7eefccb277e3:0:0:
mrfloris:2420:::0:2452:0:1983:1937:1790:3042:badvalue:3102:2408:3411:0:0:0:0:0:0:0:0::642:0:1617583171:0:1617165043:0:1617583004:1617563189:1616785408::2184:0:0:1617852413:HEARTS:415:0:631e3896-da2a-4077-974b-d047859d76bc:
5:1600906906:
Apr. 14, 2021 9:34:29 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: (C:\Users\johna\AppData\Local\Temp\1618414469959-0\test.mcmmo.users) Validating database file..
Apr. 14, 2021 9:34:29 A.M. com.gmail.nossr50.database.FlatFileDataProcessor processData
SEVERE: Some corrupt data was found in mcmmo.users and has been repaired, it is possible that some player data has been lost in this process.
Apr. 14, 2021 9:34:29 A.M. com.gmail.nossr50.database.FlatFileDataProcessor processData
SEVERE: Not enough data found to recover corrupted player data for user: nossr50
Apr. 14, 2021 9:34:29 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: Saving the updated and or repaired FlatFile Database...
Apr. 14, 2021 9:34:29 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: (C:\Users\johna\AppData\Local\Temp\1618414469971-0\test.mcmmo.users) Validating database file..
Added the following lines to the FlatFileDatabase for the purposes of the test...
nossr50:1000:::0:100:0:0::1000:0:0:1593806053:HEARTS:1000:0:588fe472-1c82-4c4e-9aa1-7eefccb277e3:0:0:
mrfloris:2420:::0:2452:0:1983:1937:1790:3042:1138:3102:2408:3411:0:0:0:0:0:0:0:0::642:0:1617583171:0:1617165043:0:1617583004:1617563189:1616785408::2184:0:0:1617852413:HEARTS:415:0:631e3896-da2a-4077-974b-d047859d76bc:5:16
00906906:
corruptdataboy:?:::???0:2452:0:1983:1937:1790:3042?????:1138:3102:2408:3411:0:0:0:0:0:0:0:0::642:0:1617??????583171:0:1617165043:0:1617583004:1617563189:1616785408::2184:0:0:1617852413:HEARTS:415:0:d20c6e8d-5615-4284-b8d1-
e20b92011530:5:1600906906:
?japaneseuser?:333:::0:2452:0:444:1937:1790:3042:1138:3102:2408:3411:0:0:0:0:0:0:0:0::642:0:1617583171:0:1617165043:0:1617583004:1617563189:1616785408::2184:0:0:1617852413:HEARTS:415:0:25870f0e-7558-4659-9f60-417e24cb3332:
5:1600906906:
sameUUIDasjapaneseuser:333:::0:442:0:544:1937:1790:3042:1138:3102:2408:3411:0:0:0:0:0:0:0:0::642:0:1617583171:0:1617165043:0:1617583004:1617563189:1616785408::2184:0:0:1617852413:HEARTS:415:0:25870f0e-7558-4659-9f60-417e24
cb3332:5:1600906906:
Apr. 14, 2021 9:34:29 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: (C:\Users\johna\AppData\Local\Temp\1618414469978-0\test.mcmmo.users) Validating database file..
Apr. 14, 2021 9:34:29 A.M. com.gmail.nossr50.database.FlatFileDataProcessor processData
SEVERE: Some corrupt data was found in mcmmo.users and has been repaired, it is possible that some player data has been lost in this process.
Apr. 14, 2021 9:34:29 A.M. com.gmail.nossr50.database.FlatFileDataProcessor processData
SEVERE: Not enough data found to recover corrupted player data for user: nossr50
Apr. 14, 2021 9:34:29 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: Saving the updated and or repaired FlatFile Database...
Apr. 14, 2021 9:34:29 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: (C:\Users\johna\AppData\Local\Temp\1618414469992-0\healthydb.users) Validating database file..
Apr. 14, 2021 9:34:30 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: (C:\Users\johna\AppData\Local\Temp\1618414469992-0\healthydb.users) Validating database file..
Apr. 14, 2021 9:34:30 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: Saving the updated and or repaired FlatFile Database...
Added the following lines to the FlatFileDatabase for the purposes of the test...
nossr50:1000:0:500:0:0:0:0:0::1000:0:0:0:1593543012:0:0:0:0::1000:0:0:1593806053:HEARTS:1000:0:588fe472-1c82-4c4e-9aa1-7eefccb277e3:0:0:
mrfloris:2420:::0:2452:0:1983:1937:1790:3042:badvalue:3102:2408:3411:0:0:0:0:0:0:0:0::642:0:1617583171:0:1617165043:0:1617583004:1617563189:1616785408::2184:0:0:1617852413:HEARTS:415:0:631e3896-da2a-4077-974b-d047859d76bc:
5:1600906906:
Apr. 14, 2021 9:34:30 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: (C:\Users\johna\AppData\Local\Temp\1618414470009-0\test.mcmmo.users) Validating database file..
Apr. 14, 2021 9:34:30 A.M. com.gmail.nossr50.database.FlatFileDataProcessor processData
SEVERE: Some corrupt data was found in mcmmo.users and has been repaired, it is possible that some player data has been lost in this process.
Apr. 14, 2021 9:34:30 A.M. com.gmail.nossr50.database.FlatFileDataProcessor processData
SEVERE: Not enough data found to recover corrupted player data for user: nossr50
Apr. 14, 2021 9:34:30 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: Saving the updated and or repaired FlatFile Database...
Added the following lines to the FlatFileDatabase for the purposes of the test...
:1000:::0:1000:640:1000:1000:1000:1000:1000:1000:1000:1000:16:0:500:0:0:0:0:0::1000:0:0:0:1593543012:0:0:0:0::1000:0:0:1593806053:HEARTS:1000:0:588fe472-1c82-4c4e-9aa1-7eefccb277e3:0:0:
mrfloris:2420:::0:2452:0:1983:1937:1790:3042:1138:3102:2408:3411:0:0:0:0:0:0:0:0::642:0:1617583171:0:1617165043:0:1617583004:1617563189:1616785408::2184:0:0:1617852413:HEARTS:415:0:631e3896-da2a-4077-974b-d047859d76bc:5:16
00906906:
aikar:0:::0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0::0:0:0:0:0:0:0:0:0::0:0:0:0:HEARTS:0:0:e0d07db8-f7e8-43c7-9ded-864dfc6f3b7c:5:1600906906:
Apr. 14, 2021 9:34:30 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: (C:\Users\johna\AppData\Local\Temp\1618414470017-0\test.mcmmo.users) Validating database file..
Apr. 14, 2021 9:34:30 A.M. com.gmail.nossr50.database.FlatFileDataProcessor reportBadDataLine
WARNING: FlatFileDatabaseBuilder Warning: No name found for data - [MISSING NAME]
Apr. 14, 2021 9:34:30 A.M. com.gmail.nossr50.database.FlatFileDataProcessor reportBadDataLine
WARNING: FlatFileDatabaseBuilder: (Line Data) - :1000:::0:1000:640:1000:1000:1000:1000:1000:1000:1000:1000:16:0:500:0:0:0:0:0::1000:0:0:0:1593543012:0:0:0:0::1000:0:0:1593806053:HEARTS:1000:0:588fe472-1c82-4c4e-9aa1-7eefcc
b277e3:0:0:
Apr. 14, 2021 9:34:30 A.M. com.gmail.nossr50.database.FlatFileDataProcessor reportBadDataLine
WARNING: mcMMO will repair this data if automatically (if it is possible).
Apr. 14, 2021 9:34:30 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: Saving the updated and or repaired FlatFile Database...
File Path: C:\Users\johna\AppData\Local\Temp\1618414470032-0\baddatadb.users
Apr. 14, 2021 9:34:30 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: (C:\Users\johna\AppData\Local\Temp\1618414470032-0\baddatadb.users) Validating database file..
Apr. 14, 2021 9:34:30 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: Saving the updated and or repaired FlatFile Database...
Apr. 14, 2021 9:34:30 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: (C:\Users\johna\AppData\Local\Temp\1618414470049-0\test.mcmmo.users) Validating database file..
Added the following lines to the FlatFileDatabase for the purposes of the test...
nossr50:1000:::0:1000:640:1000:1000:1000:1000:1000:1000:1000:1000:16:0:500:0:0:0:0:0::1000:0:0:0:1593543012:0:0:0:0::1000:0:0:1593806053:HEARTS:1000:0:588fe472-1c82-4c4e-9aa1-7eefccb277e3:0:0:
z750:2420:::0:2452:0:1983:1937:1790:3042:1138:3102:2408:3411:0:0:0:0:0:0:0:0::642:0:1617583171:0:1617165043:0:1617583004:1617563189:1616785408::2184:0:0:1617852413:HEARTS:415:0:3:5:1600906906:
powerless:0:::0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0::0:0:0:0:0:0:0:0:0::0:0:0:0:HEARTS:0:0:e0d07db8-f7e8-43c7-9ded-864dfc6f3b7c:5:1600906906:
Apr. 14, 2021 9:34:30 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: (C:\Users\johna\AppData\Local\Temp\1618414470059-0\test.mcmmo.users) Validating database file..
Apr. 14, 2021 9:34:30 A.M. com.gmail.nossr50.database.FlatFileDataProcessor reportBadDataLine
WARNING: FlatFileDatabaseBuilder Warning: Invalid UUID data found for user - 3
Apr. 14, 2021 9:34:30 A.M. com.gmail.nossr50.database.FlatFileDataProcessor reportBadDataLine
WARNING: FlatFileDatabaseBuilder: (Line Data) - z750:2420:::0:2452:0:1983:1937:1790:3042:1138:3102:2408:3411:0:0:0:0:0:0:0:0::642:0:1617583171:0:1617165043:0:1617583004:1617563189:1616785408::2184:0:0:1617852413:HEARTS:415
:0:3:5:1600906906:
Apr. 14, 2021 9:34:30 A.M. com.gmail.nossr50.database.FlatFileDataProcessor reportBadDataLine
WARNING: mcMMO will repair this data if automatically (if it is possible).
Apr. 14, 2021 9:34:30 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: Saving the updated and or repaired FlatFile Database...
File Path: C:\Users\johna\AppData\Local\Temp\1618414470068-0\missinglastlogin.users
Apr. 14, 2021 9:34:30 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: (C:\Users\johna\AppData\Local\Temp\1618414470068-0\missinglastlogin.users) Validating database file..
Apr. 14, 2021 9:34:30 A.M. com.gmail.nossr50.database.FlatFileDatabaseManager checkFileHealthAndStructure
INFO: Saving the updated and or repaired FlatFile Database...
[INFO] Tests run: 20, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.831 s - in com.gmail.nossr50.database.FlatFileDatabaseManagerTest
[INFO] Running com.gmail.nossr50.database.flatfile.FlatFileDataUtilTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s - in com.gmail.nossr50.database.flatfile.FlatFileDataUtilTest
[INFO] Running com.gmail.nossr50.database.FlatFileDataProcessorTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 s - in com.gmail.nossr50.database.FlatFileDataProcessorTest
[INFO] Running com.gmail.nossr50.datatypes.BlockLocationHistoryTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in com.gmail.nossr50.datatypes.BlockLocationHistoryTest
[INFO] Running com.gmail.nossr50.util.blockmeta.ChunkStoreTest
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.004 s <<< FAILURE! - in com.gmail.nossr50.util.blockmeta.ChunkStoreTest
[ERROR] com.gmail.nossr50.util.blockmeta.ChunkStoreTest  Time elapsed: 0.004 s  <<< FAILURE!
org.opentest4j.MultipleFailuresError:
Multiple Failures (2 failures)
        java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java
.lang" to unnamed module @1f36e637
        java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java
.lang" to unnamed module @1f36e637

[INFO] Running com.gmail.nossr50.util.text.TextUtilsTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in com.gmail.nossr50.util.text.TextUtilsTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures: 
[ERROR]   ChunkStoreTest Multiple Failures (2 failures)
        java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java
.lang" to unnamed module @1f36e637
        java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java
.lang" to unnamed module @1f36e637
[INFO]
[ERROR] Tests run: 30, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.762 s
[INFO] Finished at: 2021-04-14T09:34:31-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project mcMMO: There are test failures.
[ERROR]
[ERROR] Please refer to G:\own-git-server\minecraft-shit\mcMMO\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by nossr50** [comment]
Honestly I'm not a maven expert, so I only have a few guesses (and as I write this I will note that it compiles locally and on jenkins, and it also passes github action checks)

1) Make sure you are using Java 8 (java -version in terminal)
2) If you edited the source code, that could cause the tests to fail
3) Make sure your maven is up to date

I'll see if I can reproduced your error by playing around, but I'm not sure that I will be able to.

**Comment by nossr50** [comment]
Here's my own log running ``mvn clean install`` from terminal

[mvnrun.txt](https://github.com/mcMMO-Dev/mcMMO/files/6312260/mvnrun.txt)

**Comment by HeresJohnny320** [comment]
![image](https://user-images.githubusercontent.com/34362911/114744347-d4c75880-9d0a-11eb-94c0-be5981d2c6db.png)
and i have not done anything to the source code

**Comment by nossr50** [comment]
It shows Java version 16 there, you need to use Java 8 (although I thought our pom.xml forced Java 8)
It does show your mvn home is in the Java 8 directory, but it is listing Java 16 for the runtime and version

**Comment by HeresJohnny320** [comment]
ya im not sure im confused also

**Comment by HeresJohnny320** [comment]
and when i go into my java folder i have jre1.8.0_241 and jdk-16
