### ISSUE TITLE
Locale not loading

### ISSUE THREAD

**Issue by samukatb** [mcMMO-Dev/mcMMO#4492]
In the version 2.1.192, the locale in the plugins/mcmmo/locales is not loading anymore, it keeps loading the default (english)

**Comment by nossr50** [comment]
Hmm I don’t think I changed any code related to locale... I’ll see if I can reproduce

**Comment by samukatb** [comment]
I was in the version 2.1.188 when i updated to 2.1.192. I went back to the version I was on and is working normally.
