### ISSUE TITLE
World Height bounds issue

### ISSUE THREAD

**Issue by Espantonius** [mcMMO-Dev/mcMMO#4496]
Hello,

I have seen this problem and I don't know if it is really a problem with me or with the plugin.

Having the mining skill raised to at least 100/1000 when chopping any block that gives us double we have a 100% ratio.
I do not know if it is from the ability or if it is so.

**To check:**
1st- Go to level 1
2nd- Put the chopping blocks on level 1
3rd- Chop them with the mining level higher than the maximum (100/1000)
4th- You get double of all the blocks

**I leave a video where it looks better.**
https://www.dropbox.com/s/1mg32wbsdjaf4kl/javaw%202021-04-18%2017-32-56-068.mp4?dl=0

**Server version:** Paper 1.16.5 (last)
**McMMo version:** 2.1.194-SNAPSHOT 
**Plugins on the test server :** Only McMMo

Ps: I have realized when watching the video again that the experience also adds it. Even if you have put that block, it still gives you the level xp.

**Comment by nossr50** [comment]
@Espantonius I cannot replicate with the newest mcMMO build, I even tried putting the block under water like in your vid.

**Comment by nossr50** [comment]
@Espantonius 

EDIT: nevermind, I got it to work by putting blocks on y 0 instead of y 1

**Comment by Espantonius** [comment]
Sorry for the confusion 😅. It's just the first block there is in the height of the world.

**Comment by nossr50** [comment]
Fixed in 2.1.194
