### ISSUE TITLE
Error - PlayerJoinEvent

### ISSUE THREAD

**Issue by ghost** [mcMMO-Dev/mcMMO#4522]
https://pastebin.com/ePFMVA5v

https://pastebin.com/EZx9pxiS

**Comment by lexikiq** [comment]
Duplicate, update your viaversion

https://github.com/mcMMO-Dev/mcMMO/issues/4502#issuecomment-825871597

**Comment by LtSam** [comment]
> Duplicate, update your viaversion
> 
> [#4502 (comment)](https://github.com/mcMMO-Dev/mcMMO/issues/4502#issuecomment-825871597)

ViaVersion is in the latest version

**Comment by lexikiq** [comment]
Download the latest version from their Jenkins CI

**Comment by LtSam** [comment]
https://pastebin.com/cyC0QDFB

Even so, it gives the error of PlayerJoinEvent
McMMO - v2.1.196
ViaVersion - 3.2.2 version from their Jenkins

**Comment by lexikiq** [comment]
You should be downloading from the Dev repo, atleast version 3.3 https://ci.viaversion.com/job/ViaVersion-DEV/

**Comment by Chew** [comment]
Closing due to duplicate and OP is gone.
