### ISSUE TITLE
Player Data Transfer Feature

### ISSUE THREAD

**Issue by LvXP0** [mcMMO-Dev/mcMMO#4542]
How to mcMMO player's data transfer?

ex. /mctransferdata [(A's nickname (or UUID)] [B's nickname (or UUID)]
-> A's mcMMO data -> move to B's data

**Comment by Greymagic27** [comment]
Transferring levels might be possible through editing this file: https://mcmmo.fandom.com/wiki/Mcmmo.users_file however this has already been suggested here: #4528

**Comment by Chew** [comment]
As stated, this is a duplicate. Thank you for reporting!
