### ISSUE TITLE
Max HP Incompatibility

### ISSUE THREAD

**Issue by Beastman9095** [mcMMO-Dev/mcMMO#4544]
We have been receiving these error messages for a pretty long time caused by other plugins who allow players to have more HP than default which is in this case AdvancedEnchantments I believe, maybe a config option for the Maximum HP value of the plugin could help out or direct support for the plugin.

```
[15:08:00 WARN]: [mcMMO] Task #9957281 for mcMMO v2.1.193 generated an exception
java.lang.IllegalArgumentException: Health must be between 0 and 28.0, but was 28.83333396911621. (attribute base value: 20.0, player: <player>)
```

**Comment by TheBusyBiscuit** [comment]
Can you please post the full stacktrace or the entire server log via pastebin?
That error has been truncated, so it only shows a very small part of it.

You should also update your mcMMO version.

**Comment by nossr50** [comment]
@Beastman9095 Does this happen with new mcMMO versions? And please post the full error.

**Comment by Beastman9095** [comment]
We will be updating McMMO soon and I will post a full error when we do, thank you for the help

**Comment by Beastman9095** [comment]
After some good time of monitoring, we've come to the conclusion that the issue doesn't re-appear after the latest updates. Thank you for helping out, have a nice day!
