### ISSUE TITLE
McMMO Level up Message SPAMS CHAT!!

### ISSUE THREAD

**Issue by BrawlingJoker16** [mcMMO-Dev/mcMMO#4558]
I am making a server and I added McMMO for reasons.. Anyway whenever people are mining it spams the chat with "you are now level 554 in mining skill" and it gets really annoying. Is there anyway i can disable this message? I've tried a lot but I can't seem to find anything. Please Help

**Comment by stepech** [comment]
advanced.yml -> Feedback -> ActionBarNotifications -> LevelUps -> SendCopyOfMessageToChat: false
It's like 45th line or so...

**Comment by BrawlingJoker16** [comment]
Thanks bro
