### ISSUE TITLE
Armor breaking bug

### ISSUE THREAD

**Issue by samukatb** [mcMMO-Dev/mcMMO#4562]
I use a plugin to do clan warfare, and during the preparation period, where there is no PvP, players can still hit the enemy to break the armor, but the player doesn't take damage, only the armor.

There is probably an incompatibility between the 2 plugins.

Server version: 1.16.5
mcMMO version: 2.1.196
Plugin link: https://www.spigotmc.org/resources/titansbattle.47145/

**Comment by RoinujNosde** [comment]
I'm the author of TitansBattle.
My plugin is cancelling the damage event, but it seems mcMMO still damages the armor.

**Comment by timderspieler** [comment]
This bug is over 2 years old, but the issue still exists that if a plugin cancels the EntityDamageByEntity event, the armor still takes damages by the axe skill.

@RoinujNosde is there anything you've or the author of mcmmo ( @nossr50 ) did to fix this?

**Comment by RoinujNosde** [comment]
@timderspieler I fixed it by setting my listener to run _before_ mcmmo's

https://github.com/RoinujNosde/TitansBattle/blob/master/src/main/java/me/roinujnosde/titansbattle/listeners/EntityDamageListener.java#L34-L56

**Comment by timderspieler** [comment]
@RoinujNosde thank you very much for the tip. I will try to also change that in my code.

**Comment by nossr50** [comment]
This one is not easily solved by mcMMO, but I could add an event to the damage of armor and other plugins could listen and cancel it, there are of course other solutions.

**Comment by RoinujNosde** [comment]
> This one is not easily solved by mcMMO

IMO a "fix" is not necessary on mcMMO's part, this is just a matter of setting the right priority on listeners...
