### ISSUE TITLE
Smelting ores grants you repairing skill XP and weird bossbar texture glitch

### ISSUE THREAD

**Issue by lordrius** [mcMMO-Dev/mcMMO#4567]
Hi!

I have noticed that if you smelt ores, two XP bossbars are rendered, Mining and Repair. Also the repair bossbar shows a weird glitch with the texture. I don't know if this makes sense but, why smelting ores gives you repairing XP?

I'm using latest mcMMO 2.1.200 and Paper-1.17.1-99 versions. Also using default launcher and no resource packs.
![2021-07-11_20 02 16](https://user-images.githubusercontent.com/483570/125205535-ff319f00-e282-11eb-82ac-af5a932f7e3f.png)

Greetings and keep up the good work!

**Comment by nossr50** [comment]
This is normal, the glitch on the boss bar is a vanilla client bug. You get XP for both skills because that is what makes up Smelting (Smelting is a child skill of those two)
