### ISSUE TITLE
`/mctop` doesn't work if the skill name has a space in it

### ISSUE THREAD

**Issue by MrPowerGamerBR** [mcMMO-Dev/mcMMO#4568]
If a skill name has a space, it is impossible to check their stats with `/mctop`

Example: Woodcutting is named "Corte de árvore" in mcMMO's portuguese translation, trying to TAB complete the name appends `\` but it still doesn't work

```
> mctop Corte\ de\ árvore
[00:17:09 INFO]: O jeito certo de usar é /mctop [habilidade] [página]
```

Even if you remove the slashes manually, it still doesn't work.

Using `/mctop Woodcutting` also doesn't work.

Maybe the skill name be renamed to something that *don't* have a space (in previous versions, the name was "Lenhador", which didn't cause any issues, however "Lenhador" is the translation of "Lumberjack"), to avoid issues with commands?

**Comment by nossr50** [comment]
Skills shouldn't have a space in them, thanks for letting me know.
