### ISSUE TITLE
mcMMO Configuration/Disabling Error

### ISSUE THREAD

**Issue by akaAdam7** [mcMMO-Dev/mcMMO#4570]
Im super new to reading scripts and coding lines as this is my first experience hands on with the back end of MC servers, but I've been skimming the console and trying different file versions to see whats compatible. As of right now my server is running at v1.16.5 and I've tried running mcMMO version 1.4.6, 1.4.7, 1.4.8, and 1.5.0. None have worked and they all seem to display this same error in the console:

[Server] ERROR There was an error while enabling mcMMO!
[Server] WARN java.lang.NoSuchMethodError: 'org.bukkit.configuration.file.YamlConfiguration 
                         org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(java.io.InputStream)'
[Server] WARN at com.gmail.nossr50.config.HiddenConfig.load(HiddenConfig.java:31)
[Server] WARN at com.gmail.nossr50.config.HiddenConfig.<init>(HiddenConfig.java:18)
[Server] WARN at com.gmail.nossr50.config.HiddenConfig.getInstance(HiddenConfig.java:23)
[Server] WARN at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:400)
[Server] WARN at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:134)
[Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[Server] WARN at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[Server] WARN at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[Server] WARN at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:270)
[Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069)
[Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[Server] WARN at java.base/java.lang.Thread.run(Thread.java:829)
[Server] INFO Disabling mcMMO v1.5.00-b3547

Any tips to try or any solutions that have been found would be very much appreciated.

**Comment by nossr50** [comment]
That's a very old version of mcMMO, please use the latest version
https://spigot.mcmmo.org
