### ISSUE TITLE
Feller not dropping leaf loot

### ISSUE THREAD

**Issue by MissPotato** [mcMMO-Dev/mcMMO#4575]
mcMMO Version: 2.1200 Overhaul
Environment: Paper 1.17.1 Build 108 

When using feller it destroys the leaf blocks but does not drop either the saplings or the sticks. If using silk touch it doesn't drop the leaves either. The logs drop fine.

**Comment by nossr50** [comment]
Is Knock On Wood rank 2? That is required to get the additional loot.

**Comment by MissPotato** [comment]
It is not. I had looked in "/woodcutting ?" to see if there was anything there that would explain it. Thank you for the explanation!
