### ISSUE TITLE
Bug report 1.17.1

### ISSUE THREAD

**Issue by thiagogebrimm** [mcMMO-Dev/mcMMO#4581]
When adding a tag to a mob the name disappears after a while, for the bug to be reproduced I need to have the mcmmo along with griefprevention (I'm using the dev version for 1.17.1, and they said the bug is not there)

But I can apply the nametag without it disappearing by slapping the entity and right after the hearts appear apply the nametag

**Comment by CodeByCam** [comment]
@nossr50, I can confirm this bug too. 

Paper: `1.18.1 #81`
mcMMO: `2.1.206`
GriefPrevention: `16.17.1-33-g6debf36`

Using a name tag on mobs whilst `Mob_Healthbar` is disabled works fine, and they stay after you enable the setting, but then any further name tags you use will vanish after a few seconds whilst the setting is enabled. 

I used `BAR` for the `Display_Type`, haven't checked `HEARTS`.

**Comment by thiagogebrimm** [comment]
It was solved by GriefPrevention
