### ISSUE TITLE
furnace bug 1.17.1

### ISSUE THREAD

**Issue by popcorn9499** [mcMMO-Dev/mcMMO#4583]
So when I went to open a new furnace with mcmmo on minecraft 1.17.1 I would try to put an item into the inventory and it would kick me out of the inventory and if I shift clicked the item that item would be missing from my inventory never to be seen again. It would also not be in the furnace I placed it in. However after this initial bug you will never see it again on the same furnace. [a video of the bug ](https://photos.popicraft.net/u/files/13.21.13-23.07.21-PW11QEyGL2.mp4)

/version: This server is running CraftBukkit version 3202-Spigot-18c71bf-64d149a (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)

running the latest mcmmo built from the master repo. 

This issue does not appear on spigot 1.17 only 1.17.1

**Comment by popcorn9499** [comment]
I apologize I realize I forgot to send a copy of the server log so [here it is ](https://pastebin.com/HjJHJCTh)

**Comment by levtey** [comment]
Seems like the issue stems from [this](https://github.com/PaperMC/Paper/commit/170382fe3552586dc381c001b08e6fdbb42d47c0) commit, specifically the last CraftBukkit change to "properly clear tile entities before replacing."

**Comment by popcorn9499** [comment]
ah that makes alot of sense actually. doesn't make it any less annoying but its cool to understand what's going on.

**Comment by CodeByCam** [comment]
This doesn't happen on the latest Paper/[Tuinity](https://github.com/Tuinity/Tuinity/commit/e4b092272731f380727b0f69c32c03039cb429bb), however I was facing this issue with mcMMO whilst running a specific version of Tuinity:

```
[02:02:06 INFO]: This server is running Tuinity version git-Tuinity-25 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: de19b33 on HEAD)
Unknown version
Previous version: git-Tuinity-26 (MC: 1.17.1)
[02:02:21 INFO]: mcMMO version 2.1.200
```

**Comment by levtey** [comment]
Yep, the bug should be fixed on Spigot and all forks that have pulled from Spigot within the past 15 hours or so (Paper, Tuinity, Purpur, etc.)

**Comment by NightLife-SG** [comment]
Im having the issue tho,running paper 1.17.1 build 127

When shift clicking into furnace the item just gone.
But this bug appear when you place down a new furnace and try to put item in it.
This issue wont be appearing if the furnace has been registered.

**Comment by popcorn9499** [comment]
Thank you. Hadn't realized that one of the builds from today fixed it.  Sorry that I made a bug report for not really a mcmmo bug

**Comment by NightLife-SG** [comment]
still,having the issue using latest build on paper 130 #1.17.1

**Comment by levtey** [comment]
Yep, I tested it with Spigot, Paper, Tuinity, and Purpur last night and they all worked... except Paper. Paper asked me to open a bug report describing replication details but I personally am not sure of the code that causes this to happen. For the time being, you can switch to one of the other forks (Tuinity has better performance anyways) to fix your issues.

**Comment by nossr50** [comment]
For now you can use Spigot until Paper patches this issue

**Comment by mrfloris** [comment]
Using paper for a few days now and can't reproduce this. they upstream patch. Update your spigot/paper and this goes away.

**Comment by popcorn9499** [comment]
since I imagine this issue was fixed long ago and according to the latest comment it was patched upstream so I will make this as closed
