### ISSUE TITLE
(mcMMO) <player> has reached power level 5000

### ISSUE THREAD

**Issue by mrfloris** [mcMMO-Dev/mcMMO#4593]
The <player> is old non-hex nicknames, but hex is supported in other elements, and it seems to show okay in console.

a smooth dark blue to blue hex color ends up with some black/yellow/blue/green/black/green list of random old colors. looks weird :)

**Comment by Chew** [comment]
Fixed in https://github.com/mcMMO-Dev/mcMMO/commit/81faf93f31545282cc3ef65c145c79687e7e966a
Thanks for the report!
