### ISSUE TITLE
mcmmo lag server

### ISSUE THREAD

**Issue by brasilcraft54** [mcMMO-Dev/mcMMO#4614]
https://timings.pl3x.net/?id=3a4dd28bd771436998725df8bea4b9e5

version purpur 1.17.1

**Comment by SturdyFool10** [comment]
I can second that I am having issues with server lag, but I am on timings 1 and have not been lucky enough to catch the server while it's claiming to be overloaded

**Comment by Chew** [comment]
Thanks for the report, unfortunately the timings link is no longer valid so we can't look into this issue. Thank you for reporting, however!
