### ISSUE TITLE
Add Feature Update to change sound sorce or disable sound option of Bleeding passive from Swords

### ISSUE THREAD

**Issue by comonier** [mcMMO-Dev/mcMMO#4615]
Please add an option on mcmmo to players [disable/enable] features that they doesnt like. Exemple: a lot of players on my server hates the sound of [bleeding] from sword skills. And to remove that they really need to disable sounds of [blocks] on minecraft volume. There is no option to change that sound sorce on config to other sorce [like hostile creatures] "an solution" cause they already remove that kind of sound when they are farming experience on some mobtrap

**Comment by nossr50** [comment]
You can disable its particle effect already in 'Particles.Bleed' in config.yml
