### ISSUE TITLE
mcmmo bug chat

### ISSUE THREAD

**Issue by XeminO** [mcMMO-Dev/mcMMO#4622]
Salut quand on se connecte au serveur mcmmo envoy dans le chat un message mais nous ne voulons pas que sa envoy un message comment faire ?
![2021-08-16_11 20 55](https://user-images.githubusercontent.com/89012309/129541474-6528e9e8-938d-4236-8ee0-1f0329e705b5.png)

**Comment by Zoriot** [comment]
Hey change the ``MOTD_Enabled: true`` to ``MOTD_Enabled: false`` in config.yml.
If you dont like Skill Event Info's on join disable EventInfoOnPlayerJoin too.

Also you issue Name isn't correct ;)

**Comment by Chew** [comment]
> Hi when connecting to the server mcmmo sends in the chat a message but we don't want its send a message how to do?

That can indeed be disabled in the config.

Reference: https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/config.yml#L52
