### ISSUE TITLE
double smelting on raw copper

### ISSUE THREAD

**Issue by rasmus123d** [mcMMO-Dev/mcMMO#4626]
doesnt want to doublesmelt for me, gold and iron works fine

**Comment by Geekerandy** [comment]
I can confirm this still occurs as of version 2.1.202

**Comment by dodieboy** [comment]
In the config.yml, it also does not have copper

https://github.com/mcMMO-Dev/mcMMO/blob/def676d8d7a28b7f966014dda28dd3e9933616b3/src/main/resources/config.yml#L612

**Comment by Lyther** [comment]
Adding the following line to your config might be useful:

 Smelting: 
     Iron_Ingot: true 
     Gold_Ingot: true 
     ...
     **Copper_Ingot: true**

DoubleSmelt automated checks items in the config and processes them.

Also works for Netherite_Scrap.

**Comment by Chew** [comment]
Fixed in #4626, guess it didn't get linked. Thanks for reporting!
