### ISSUE TITLE
mcMMO Mining double drop dupe glitch

### ISSUE THREAD

**Issue by SkeletonAce** [mcMMO-Dev/mcMMO#4634]
With high levels in mcMMO mining players can abuse the double drops by placing a `block` on top of a naturally generated stone block and by breaking the stone block the `block` that was placed on top is duplicated. 
This works with bells, torches, lanterns and possibly more.

mcMMO version:(2.1.201)
Server version:(purpur-1.17.1-1378)

**Comment by rasmus123d** [comment]
cant replicate on newest release

**Comment by SkeletonAce** [comment]
Funny you should say that, I'm on the newest release of mcmmo, are you talking about a dev build that I don't know about?

**Comment by rasmus123d** [comment]
I have 2700 mining and this does not happen, actually the stone where something is placed on only drops 1 stone on break.

**Comment by SkeletonAce** [comment]
That would be because you placed the stone block, you need to use a stone block that has been naturally spawned in..

**Comment by rasmus123d** [comment]
i did not

**Comment by SkeletonAce** [comment]
Well the way that mcMMO works is that when you have over lvl 1000 in mining you get two stone for every stone you mine

**Comment by nossr50** [comment]
@SkeletonAce what blocks are you duplicating when you do this? TileEntities (Chests, etc) shouldn't be getting duplicated

**Comment by Momshroom** [comment]
I cannot replicate this, either.  I tried with lanterns, bells and torches, on natural stone and I have 100% double drop chance.  What server software are you using?  Can you replicate it with only mcmmo? I'm using mcmmo 2.1.201 and an admittedly out of date Paper 190. I confirmed everything was natural with /mmodebug and tried several times. I did not use superbreaker.   @SkeletonAce
