### ISSUE TITLE
mcMMO not enabling.

### ISSUE THREAD

**Issue by andrewkm** [mcMMO-Dev/mcMMO#4637]
https://pastebin.com/raw/GepV5C3C
Updated from https://github.com/mcMMO-Dev/mcMMO/commit/5575309b7914137b95223a920d347179bb258dd8 to https://github.com/mcMMO-Dev/mcMMO/commit/7fc65771967db46df61b5246992cf771eb9c7809

**Comment by nossr50** [comment]
Should be fine now
