### ISSUE TITLE
Is it possible to enable alchemy xp gain from hoppers?

### ISSUE THREAD

**Issue by Sorphius** [mcMMO-Dev/mcMMO#4641]
I would like to enable alchemy experience gain from potions brewed using hoppers, can this be done in the configs?

**Comment by Lyther** [comment]
This function cannot be set in configs.

As I noticed that the furnaces are using a cache player owner to handle items from the hopper. The brew stand may have similar processing to make it possible.

@nossr50 if you think it's OK to have such a listener, I can work on it.
