### ISSUE TITLE
McMMO memory leak for entity meta datas

### ISSUE THREAD

**Issue by JHarris12345** [mcMMO-Dev/mcMMO#4643]
It looks like entity meta data is not being cleared correctly and is taking up stupid amounts of room 
![image](https://user-images.githubusercontent.com/46936647/139609740-47eaa383-4636-4196-a174-792f0b107c5a.png)
https://gyazo.com/844c4f712c9a3c773fa9bcf4db948935

4GB stored for JUST McMMO entity meta data

**Comment by nossr50** [comment]
Thanks for this report, I did a pretty thorough review of entity metadata and leaks not too long ago, must have missed something.

**Comment by skw359** [comment]
Yeah it happens here too - 
![image](https://user-images.githubusercontent.com/75508453/141537914-225642f2-575c-4e87-b9d1-bad9752e3f92.png)
The issue gets a ton worse once there are thousands of entities, which happens to be my server lol
If needed, I can provide the heapdump files, or any other information :D

**Comment by L4BORG** [comment]
I think it's too soon to tell but with gamemodes where entities could fall into void such as Skyblock, Skygrid, etc... this would add up super fast, 10gb wasted in 24h or less, I'll know for sure tomorrow but it seems 

```
    @EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = true)
    public void onEntityRemoveFromWorldEvent(EntityRemoveFromWorldEvent event)
    {
        Entity entity = event.getEntity();
        if(entity == null)
            return;

        if(!(entity instanceof LivingEntity livingEntity))
            return;

        mcMMO.getTransientEntityTracker().removeSummon(livingEntity, null, false);
    }
```

would fix the issue. Now there is a downside, as stated before event is only available on PaperSpigot.

**Comment by nossr50** [comment]
Fixed in dev, will be in next patch
