### ISSUE TITLE
Alchemy not working with Paper Build #359

### ISSUE THREAD

**Issue by MCTGE** [mcMMO-Dev/mcMMO#4645]
After updating to paper build #359 Alchemy seems to have broken.  All the data still loads in and is visible however, players are not able to craft mcMMO potions or level up.

**Comment by thiagogebrimm** [comment]
The error actually happened in Paper build 355
More info: https://github.com/PaperMC/Paper/pull/6848

**Comment by MCTGE** [comment]
Ahh thank you,  I upgraded several versions so That is when I noticed it.  Thank you. I from the link you posted it seems the issue is already known and being worked on thank you.

**Comment by Erlpil** [comment]
Adding more info to this issue
Error during runtime: https://pastebin.com/raw/48cPMBDV
Error on shutdown: https://pastebin.com/raw/8SSffY7F

**Comment by nossr50** [comment]
Fixed
