### ISSUE TITLE
Mcmmo plugin not enabling at server start-up

### ISSUE THREAD

**Issue by DaddySoccer** [mcMMO-Dev/mcMMO#4646]
Hi, Im trying to figure out why no version of Mcmmo is working on my server.

This post is kind of a duplicate to others, but I have never seen any fixes in the comments except that it has been updated.

Here's a pastebin link to the error logs I got in my console. Let me know in advance if this pastebin link is not accessible or working.
https://pastebin.com/vJaDSF2K

The start-up (or enabling plugin) messages only appear when the server starts up or starts enabling plugins in order for them to load. This does not spam or fill up the console. This error occurs only once.

Here are my current files in my plugin folder. 

AdminFun
AdminFun.jar
AUpdater
bStats
CMILib
CMILib1.0.4.2.jar
Essentials
EssentialsX-2.19.0.jar
HealthBar
HealthBar.jar
Jobs
Jobs5.0.0.9.jar
MarriagePlus
MarriagePlusPlus.jar
Multiverse-Core
Multiverse-Core-4.3.1.jar
PluginMetrics
PowerRanks
PowerRanks.jar
ProtocolLib
ProtocolLib.jar
SilkSpawners
SilkSpawners.jar
Updater
WorldEdit
worldedit-bukkit-7.2.7.jar
WorldGuard
worldguard-bukkit-7.0.6-dist.jar

Spigot Version - 1.17.1

**Comment by PikaMug** [comment]
According to https://github.com/mcMMO-Dev/mcMMO/issues/3309, you're likely using a very old version of mcMMO.

**Comment by Lyther** [comment]
Maybe you should use a VPS instead of some "free Minecraft server provider". Since the newer version of mcMMO is premium, to use the newer version you should purchase distribution and send it to your own server.

The older version uses an abandoned method in the new spigot. Downgrade your spigot server jar file can also solve the problem.

**Comment by DaddySoccer** [comment]
> Maybe you should use a VPS instead of some "free Minecraft server provider". Since the newer version of mcMMO is premium, to use the newer version you should purchase distribution and send it to your own server.
> 
> The older version uses an abandoned method in the new spigot. Downgrade your spigot server jar file can also solve the problem.

I mean this is just a chill server for me and friends, not tryna take it public or anything, which is why i’m using a free server provider.

**Comment by Lyther** [comment]
> I mean this is just meant to be a chill server for me and friends, not tryna take it public or anything, which is why i’m using a free server provider.

Doesn't mean to be rude. Take a try of AWS or Azure free trial for 6 months :)

It's enough for personal use, and you can upgrade McMMO freely.

**Comment by DaddySoccer** [comment]
> > I mean this is just meant to be a chill server for me and friends, not tryna take it public or anything, which is why i’m using a free server provider.
> 
> Doesn't mean to be rude. Take a try of AWS or Azure free trial for 6 months :)
> 
> It's enough for personal use, and you can upgrade McMMO freely.

No worries. Thanks for the recommendation and help, i’ll check it out.

**Comment by Chew** [comment]
As stated this is a highly outdated version of mcMMO. Not much we can do here. Thanks for reporting!
