### ISSUE TITLE
Could not pass event BrewEvent to mcMMO v2.1.202 Spam

### ISSUE THREAD

**Issue by TenkyuChimata** [mcMMO-Dev/mcMMO#4648]
https://paste.ubuntu.com/p/nZVzTWptWG/

**Comment by Erlpil** [comment]
Duplicate of [https://github.com/mcMMO-Dev/mcMMO/issues/4645](https://github.com/mcMMO-Dev/mcMMO/issues/4645)

**Comment by nossr50** [comment]
Fixed
