### ISSUE TITLE
Alchemy not working on 1.17.1 Purpur

### ISSUE THREAD

**Issue by Blueraguard** [mcMMO-Dev/mcMMO#4661]
Running latest version of plugin get this error when brewing, i couldn't find anywhere that said anything about purpur on the site or if it worked

12.11 12:02:18 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
12.11 12:02:18 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1394]
12.11 12:02:18 [Server] INFO at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1283) ~[patched_1.17.1.jar:git-Purpur-1394]
12.11 12:02:18 [Server] INFO at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Purpur-1394]
12.11 12:02:18 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:493) ~[patched_1.17.1.jar:git-Purpur-1394]
12.11 12:02:18 [Server] INFO at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1635) ~[patched_1.17.1.jar:git-Purpur-1394]
12.11 12:02:18 [Server] INFO at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:821) ~[patched_1.17.1.jar:git-Purpur-1394]
12.11 12:02:18 [Server] INFO at net.minecraft.world.level.World.tickBlockEntities(World.java:1106) ~[patched_1.17.1.jar:git-Purpur-1394]
12.11 12:02:18 [Server] INFO at net.minecraft.world.level.chunk.Chunk$c.a(Chunk.java:1430) ~[patched_1.17.1.jar:git-Purpur-1394]
12.11 12:02:18 [Server] INFO at net.minecraft.world.level.chunk.Chunk$a.a(Chunk.java:1478) ~[patched_1.17.1.jar:git-Purpur-1394]
12.11 12:02:18 [Server] INFO at net.minecraft.world.level.block.entity.TileEntityBrewingStand.a(TileEntityBrewingStand.java:183) ~[patched_1.17.1.jar:git-Purpur-1394]
12.11 12:02:18 [Server] INFO at net.minecraft.world.level.block.entity.TileEntityBrewingStand.a(TileEntityBrewingStand.java:253) ~[patched_1.17.1.jar:git-Purpur-1394]
12.11 12:02:18 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1394]
12.11 12:02:18 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1394]
12.11 12:02:18 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1394]
12.11 12:02:18 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1394]
12.11 12:02:18 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor81.execute(Unknown Source) ~[?:?]
12.11 12:02:18 [Server] INFO at com.gmail.nossr50.listeners.InventoryListener.onBrew(InventoryListener.java:356) ~[mcMMO.jar:?]
12.11 12:02:18 [Server] INFO at com.gmail.nossr50.runnables.skills.AlchemyBrewTask.finishImmediately(AlchemyBrewTask.java:111) ~[mcMMO.jar:?]
12.11 12:02:18 [Server] INFO at com.gmail.nossr50.skills.alchemy.AlchemyPotionBrewer.finishBrewing(AlchemyPotionBrewer.java:136) ~[mcMMO.jar:?]
12.11 12:02:18 [Server] INFO at com.gmail.nossr50.events.fake.FakeBrewEvent.<init>(FakeBrewEvent.java:12) ~[mcMMO.jar:?]
12.11 12:02:18 [Server] INFO java.lang.NoSuchMethodError: 'void org.bukkit.event.inventory.BrewEvent.<init>(org.bukkit.block.Block, org.bukkit.inventory.BrewerInventory, java.util.List, int)'
12.11 12:02:18 [Server] ERROR Could not pass event BrewEvent to mcMMO v2.1.204

![image](https://user-images.githubusercontent.com/94195547/141521310-9a2a26e3-b67d-469e-a0a4-912bb28d93bf.png)

list of all current plugins

**Comment by Warriorrrr** [comment]
Update your version of purpur to build 1423 or above.

**Comment by Chew** [comment]
Issue with mcMMO, please update.
