### ISSUE TITLE
mcMMO double drop dupes at y 255 end even though It's disabled

### ISSUE THREAD

**Issue by RareRarity** [mcMMO-Dev/mcMMO#4665]
although double drops are disabled in the end dimension they still work at y 255, I can't seem to figure out the issue and they only work for blocks that are included in the double drop list in the config

**Comment by Geekerandy** [comment]
unable to reproduce, is your mcmmo updated?

**Comment by nossr50** [comment]
you likely need to update your mcMMO, feel free to open a new issue if you are on the latest with more information
