### ISSUE TITLE
Herbalism Issue (Lilypad + Beetroot)

### ISSUE THREAD

**Issue by Flibknort** [mcMMO-Dev/mcMMO#4667]
Beetroot isn't affected by Double Drops but still give xp and auto replant.
Lilypads on the other hand, doesn't give xp and doesn't work with herbalism in general. No Double drop, no xp, no interaction. 
Diagnosing via `/mmodebug`, Lilypads still give "plant processed : 1" but after that nothing else shows up.
![image](https://user-images.githubusercontent.com/94317388/141695017-fe06bc11-044c-423f-9c64-a1806ddf1ca5.png)

Running on Airplane-92 (R0.1 Snapshot) 1.17.1, mcMMO v204
![image](https://user-images.githubusercontent.com/94317388/141695094-0f791165-9742-4a6f-a36a-f95495f6991e.png)

**Comment by Lyther** [comment]
Working on this issue.

By the definition of `Material.class`, BEETROOT is an ageable plant, while LILY_PAD isn't:

```java
BEETROOTS(22075, Ageable.class),
LILY_PAD(19271),
```

The lily_pad only shows up in the debug mode `plants processed`, but never actually processed as a plant.

I'll fix the beetroot's double drop properly, but not going to add lily_pad as a plant.

**Comment by Chew** [comment]
Fixed in #4669 I suppose?
