### ISSUE TITLE
Could not pass event BlockBreakEvent to mcMMO v2.1.205

### ISSUE THREAD

**Issue by skw359** [mcMMO-Dev/mcMMO#4668]
I'm not sure how to reproduce or much details on this, but it started happening on version 2.1.205 - https://pastebin.com/vyQS6dx5
I can teleport to the coordinates mentioned in the error logs and send a screenshot if that helps 
Please comment if more information is needed :D

**Comment by nossr50** [comment]
It seems that eco plugin is likely throwing an event that puts a block outside of legal world height limits, this causes the error, the block itself may not ever actually exist. I could add some code to squelch edge cases like this, I'm undecided on it.

**Comment by skw359** [comment]
oh, is there anything i can do in the meanwhile?

**Comment by nossr50** [comment]
Technically it is a safe error but obviously it will clog your log file, I am still recovering from a cold but I'll try to address it once I'm better.

**Comment by skw359** [comment]
Sure no worries! I don't mind it lol - feel better :)

**Comment by nossr50** [comment]
An ideal fix would be for that eco plugin to avoid sending block events for impossible block positions

**Comment by skw359** [comment]
Sure I'll notify the author of it :)
