### ISSUE TITLE
Memory leak with metadata (v2.1.205)

### ISSUE THREAD

**Issue by skw359** [mcMMO-Dev/mcMMO#4670]
I know this was addressed in version 2.1.205, but I analyzed a heapdump after G1 Old got triggered on my server, hinting a memory leak.  I think metadata for entities is not being cleared correctly in version 2.1.205, but here's a screenshot to help: 
![image](https://user-images.githubusercontent.com/75508453/141993878-d82e4296-9a1c-4757-905f-4e23f59fc02f.png)

I can send the full heapdump file privately upon request, feel free to ask for more information :)

**Comment by nossr50** [comment]
That would be appreciated, I'm a bit perplexed on how there can be a leak, and I would love to plug it ASAP if there is one. If you don't mind me asking, are you running paper or spigot or another server software?

You can send the dump to business@neetgames.com

**Comment by skw359** [comment]
Ya sure I'll send it in an archive! I use Purpur

**Comment by nossr50** [comment]
Can you check to see if this potential leak also exists in paper? Also about how long until you check, is it just until the first garbage collection? Potentially there can be many entities with metadata flags at that point as they only get cleaned if they had been killed.

**Comment by nossr50** [comment]
Let me know when you have sent the dump, I'm still on the fence of whether or not this is a leak or just a result of thousands of mobs having metadata and not yet being dead. You're welcome to try persistent data options to mitigate this ( should be in persistent_data.yml ) but it can tank TPS

**Comment by skw359** [comment]
Sure, I have to upload it when I get home since this super slow wifi won't cut it lol

**Comment by skw359** [comment]
It's been sent to the provided email above.

**Comment by skw359** [comment]
Here's something that might help too: 
![image](https://user-images.githubusercontent.com/75508453/143029150-179713c2-61da-46f6-977f-2b82dd2cfa8d.png)

**Comment by JHarris12345** [comment]
I cant update my server to 1.17 I have to stay on 1.16.4, so it would be appreciated if the memory leak could be fixed on 1.16

**Comment by nossr50** [comment]
@JHarris12345 which server software are you using? I'll take a look at this issue over the weekend, I find it odd that a leak could be possible but I will investigate it nonetheless.

**Comment by JHarris12345** [comment]
@nossr50 I use OVH infra 2 servers on debian OS. Version 1.17.1

**Comment by nossr50** [comment]
> @nossr50 I use OVH infra 2 servers on debian OS. Version 1.17.1

I meant spigot / paper or another fork

**Comment by JHarris12345** [comment]
@nossr50 Airplane spigot fork. Issue persists on just paper though.

**Comment by JHarris12345** [comment]
@nossr50 This was not fixed https://gyazo.com/98875518d08d4a79bce91869a478f08b

**Comment by JHarris12345** [comment]
Looks like you didn't fix meta data leaks from spawner mobs in your fix you linked above, which was the main leak
