### ISSUE TITLE
Mcmmo - Not creating plugin folder (config)

### ISSUE THREAD

**Issue by MxLNinjaz** [mcMMO-Dev/mcMMO#4689]
Hi so I am running a spigot server. I just moved my mcmmo.jar file into my plugins folder however it has not installed the plugin to the server. What I mean by this is there is no mcmmo folder inside of my plugins folder to edit the config. Would someone be able to give me a hand please. 

Running 1.17 minecraft.

**Comment by MattW-source** [comment]
Hi There,

Would you be able to provide what version of the server you are running. For example Paper-1.17 402?

Also have you checked the plugin has actually loaded and is enabled? Check with /plugins that it shows up and is green (not red)

If it does not show up or is red, you should look through your console logs on server start up for "mcmmo". This may provide hints as to why the plugin is not loading.

**Comment by MxLNinjaz** [comment]
Hi Matt,

I do apologise for wasting your time I managed to figure out the issue it
was the version of mcmmo I was running I think it was mcmmo 2.1.202 I had
to use I might be wrong but it’s all working now.

**Comment by MattW-source** [comment]
Hi Again,

Glad you got it sorted!
