### ISSUE TITLE
java.lang.ExceptionInInitializerError: null error causing mcmmo not to load in

### ISSUE THREAD

**Issue by pupshadow** [mcMMO-Dev/mcMMO#4706]
server version: 

[00:25:26 INFO]: This server is running Paper version git-Paper-133 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 5e30e19)

Plugin version: 

mcMMO v2.1.207

mcmmo error: https://pastebin.com/c8Tfrpa5

**Comment by TreemanKing** [comment]
Dupe of #4702

**Comment by pupshadow** [comment]
Sadly the new versions of spigot fixed a few bugs that were caused on the production server so I'm not using that answer you gave but thanks for trying though. All the other plugins that had this issue fixed it a couple days ago.
