### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by JHarris12345** [mcMMO-Dev/mcMMO#4720]
I would like to point out that the memory leak in McMMO was still not fixed. 11GB heap of meta data from McMMO. All "mcmmo_mob_spawner_mob" and "from_spawner" https://gyazo.com/98875518d08d4a79bce91869a478f08b

**Comment by JHarris12345** [comment]
In #4670 this was "fixed". It seemed to not fix issues from spawner mob meta data leaks which was the main issue

**Comment by nossr50** [comment]
Please provide the dump, would be useful information if you could reproduce on Paper as well ( and provide a dump for that as well )

**Comment by JHarris12345** [comment]
It replicates on paper but I cannot send the full dumps as they’re 24GB in size. Can show you screenshots of anything you’d like though

**Comment by nossr50** [comment]
> It replicates on paper but I cannot send the full dumps as they’re 24GB in size. Can show you screenshots of anything you’d like though

It may be useful to see all the nodes from the leak ( the one selected in your first screenshot ), seeing 11 million entities isn't a priority of mine but seeing ten of them would be interesting information to me.

**Comment by nossr50** [comment]
Additionally I personally don't mind downloading a 24GB file if you want to send me it via any means

**Comment by JHarris12345** [comment]
Do you know any free ways to upload a 24GB file?

**Comment by nossr50** [comment]
> Do you know any free ways to upload a 24GB file? 

Off the top of my head? I guess in theory you could make a torrent for it and send me the magnet link in email ( business@neetgames.com )

**Comment by L4BORG** [comment]
On Paper it would be possible to use https://papermc.io/javadocs/paper/1.17/com/destroystokyo/paper/event/entity/EntityRemoveFromWorldEvent.html to avoid such issues? Sorta shotgun approach but it should ensure metadata is removed when entities are removed?

**Comment by nossr50** [comment]
> On Paper it would be possible to use https://papermc.io/javadocs/paper/1.17/com/destroystokyo/paper/event/entity/EntityRemoveFromWorldEvent.html to avoid such issues? Sorta shotgun approach but it should ensure metadata is removed when entities are removed?

Thanks for informing me, I will consider it!

**Comment by nossr50** [comment]
> > > Do you know any free ways to upload a 24GB file?
> 
> > 
> 
> > Off the top of my head? I guess in theory you could make a torrent for it and send me the magnet link in email ( [business@neetgames.com](mailto:business@neetgames.com) )
> 
> 
> 
> @nossr50 Might be a lot easier to give you access to my dev server so you can download it direct. If you add my discord JHarris#0482 I can set it up

I sent you a friend request, but it seems you didn't notice so I'm mentioning it here 👍
