### ISSUE TITLE
Sugested change for log message get less confusing

### ISSUE THREAD

**Issue by broken1arrow** [mcMMO-Dev/mcMMO#4721]
I only mess my changes up more an it was before when try make pull request.

here Have you my improvement suggestion.
https://github.com/broken1arrow/mcMMO/commit/98603eb57ac57ad359dea8a281f06706280e078f

**Comment by nossr50** [comment]
I don't understand

**Comment by broken1arrow** [comment]
> I don't understand

The current message are confusing. So I suggest a cange.
