### ISSUE TITLE
Mcmmo "Bonus" doesn't work on Nether_quartz_ore

### ISSUE THREAD

**Issue by Laukage** [mcMMO-Dev/mcMMO#4742]
Mcmmo "Bonus" doesn't work on Nether_quartz_ore, i've ran tests all multiple scenarios one of them being a totally clean config and latest version of McMMo.
Please let me know if theres anything else i can do to troubleshoot.

Originally these problem was discovered because of fortune so pickaxes i've tested with are:
- Netherite Pickaxe with Fortune 3
- Netherite Pickaxe
- Diamond Pickaxe with Fortune 3
- Diamond Pickaxe

**Server version:** 
![image](https://user-images.githubusercontent.com/46964809/153244132-60ede895-ee03-435e-b93e-0114bd1fd75d.png)
**Mcmmo version:** 
![image](https://user-images.githubusercontent.com/46964809/153243925-5c95bbf0-e600-45de-8fcf-60639f8e3f25.png)

**Comment by Laukage** [comment]
Seems this issue was touched recently #4140

**Comment by MADS0LADEN** [comment]
The reason behind this is that the default ID in the config is "Nether_Quartz" but the id of the drop that needs to be doubled is "Quartz".

To fix this the default ID needs to be updated in the code ;)
