### ISSUE TITLE
Bug chunk in Mcmmo faction

### ISSUE THREAD

**Issue by DzaRGitH** [mcMMO-Dev/mcMMO#4746]
Https://i.imgur.com/7t2Rzko.png
Https://i.imgur.com/fQeRF7G.png

Bug chunk 1 blocks
Like F3 + G in 1.12.2

Mcmmo run version : 1.5.10
mc version : 1.12.2

**Comment by Chew** [comment]
I'm going to close this since there's no real information here. This, to my knowledge, cannot be the result of any plugin, much less mcMMO. If this somehow still happens on the latest version, please make a new issue. Thank you!
