### ISSUE TITLE
Tree Feller inconsistencies/improvment

### ISSUE THREAD

**Issue by Remski01** [mcMMO-Dev/mcMMO#4768]
Hello.

Noticed some inconsistencies between Tree feller and when destroying leaves with an axe, as example. When removing all leaves from an tree i get 3/4 Saplings. (sometimes 2)But when using Tree Feller i just get 1 per tree. While on an small scale this isnt a lot. When on an lager scale it is annoying. 

Could this be improved that if you cut an tree that is connected by leaves to an other or trees, that it still count it as more then 1 per connected tree? Or add an setting for this. 

(or)can it be explained why it cannot be changed to the above?

Also worth to say, cutting multiple trees in a row sometimes do not drop any leaves and leaves sometimes do not get completely removed Is this intended?

**Comment by Momshroom** [comment]
You don’t get saplings from treefeller until you unlock knock on wood.
After you do, you’ll get plenty!

**Comment by Remski01** [comment]
Alrighty, wasnt sure what Knock on wood was tbh.

Thx for the quick respons!
