### ISSUE TITLE
Latest build trips antivirus? 

### ISSUE THREAD

**Issue by level42ca** [mcMMO-Dev/mcMMO#4770]
Download location: https://popicraft.net/jenkins/job/mcMMO/

Build number: 31 (11 days ago)

Alert: 
![image](https://user-images.githubusercontent.com/12260575/170739784-caf84717-45c2-4ed8-9676-194ee19f274b.png)

**Comment by TheBusyBiscuit** [comment]
The link you posted is **NOT** an official mcMMO website.
I highly suggest to avoid it.

**Comment by level42ca** [comment]
My apologies, please ignore this request. Is there an official source for nightly builds that I'm not aware of, or just what is on Spigot?

**Comment by Chew** [comment]
I won't link to it here, but it's in the #links channel on [Discord](https://discord.gg/mcmmo) if you want it. Obviously assuming you've purchased first 😄

**Comment by popcorn9499** [comment]
> Download location: https://popicraft.net/jenkins/job/mcMMO/
> 
> Build number: 31 (11 days ago)
> 
> Alert: ![image](https://user-images.githubusercontent.com/12260575/170739784-caf84717-45c2-4ed8-9676-194ee19f274b.png)

Just realized this was a issue. scanned builds 28-35 with virustotal.com and found no issues. however when scanning with microsoft defender 30-35 seemed to bring up false positives. however Obviously download from official mcmmo channels if you have purchased. Its a great plugin and supporting the devs is super important!

As for the devs of mcMMO I am sorry that my build seems to bring you people asking questions about my build server that quite honestly I setup cuz it was easier to just download a file than wait 2 minutes for something to build and keep something automatically creating builds. Anyways to hopefully ensure people do not pester you guys in the future I put a note in the description on the build saying that this isn't in any way official download at your own risk type things. Just don't wanna in some way affect you guys. 

have a great day and sorry to bother you all!

**Comment by nossr50** [comment]
Thanks for the info
