### ISSUE TITLE
 dupe? Still same issue with BlastMining. Is a problem from 1.17 and forward.

### ISSUE THREAD

**Issue by broken1arrow** [mcMMO-Dev/mcMMO#4783]
Because it drop the ors as blocks, with the change in 1.17 it will give players 3 times more an versions before even on the lowest setting of BlastMining. I have not see any settings for this. I use version 2.1214 and test on 1.18.2 379

you can check the original issue https://github.com/mcMMO-Dev/mcMMO/issues/4682

**Comment by Chew** [comment]
Please don't open duplicate issues, we'll get to it when we can.
