### ISSUE TITLE
Changes made to the locale_override.properties file don't have any effect

### ISSUE THREAD

**Issue by Tomographix** [mcMMO-Dev/mcMMO#4788]
mcMMO version - 2.2.214
Server Jar - Latest PaperSpigot for 1.19

Hi,
Making changes to the locale_override.properties file does not seem to change any of the formatting ingame.
I've tested this with a clean installation of MCMMO (brand new configs) to see if I could change the formatting for the admin chat so that it was easier to read.

`Chat.Style.Admin=&b[&r{0}&b] &b\u2192 &b{1}`

Is the default format. I changed all of the &b to &d so that it would be pink instead but this did not change the formatting ingame.
Thanks

**Comment by Complex1t** [comment]
Adding on to this, the `Overhaul.Levelup` locale also does not change the formatting ingame. It has worked in 1.18, but seems to have broken on 1.19. Some locales seem to have been unaffected though - for example, the `Commands.PowerLevel.Leaderboard` locale still works fine on 1.19.

**Comment by nossr50** [comment]
None of it is working?

**Comment by Chew** [comment]
Closed due to no response. Please open a new issue if you're still experiencing this!
