### ISSUE TITLE
Mangrove tree & treeFeller

### ISSUE THREAD

**Issue by thunderlight411** [mcMMO-Dev/mcMMO#4799]
When cutting down a mangrove tree, the Mangrove_log is not giving any XP. /mmodebug tells me the block is natural but that there a no treasures found and no xp is given for logs.

When using treeFeller only the Mangrove_roots are removed.
Everything above will not be felled.

If a mangrove tree is grown from a Mangove_propagule the full tree is marked as not natural where all other trees grown from a sapling are considered natural.

Can this please be fixed?

**Comment by Chew** [comment]
This should be fixed in the next update (2.1.215).

**Comment by nossr50** [comment]
What Chew said is true and that next update will be out soon
