### ISSUE TITLE
Unarmed skill - Berserk permanently activated | McMMO 2.1.215 

### ISSUE THREAD

**Issue by Meustrabil** [mcMMO-Dev/mcMMO#4801]
hello!
sorry to interrupt the devs but current updates of McMMO build 2.1.215 showing some bugs with the unarmed active skill, Berserk. 
the mcmmo.ability.unarmed.berserk seems to be applied to every players no matter what unarmed levels they have.

from [this short clip](https://imgur.com/JmYoEZS) showing a new player from my server instant mining a dirt block without manually activating the ability.

**Comment by nossr50** [comment]
Sorry about that, fixed it in 2.1.216
