### ISSUE TITLE
Revert Fishing loot table changes

### ISSUE THREAD

**Issue by unfairDude** [mcMMO-Dev/mcMMO#4808]
hello, im running a 1.19 survival server. Actually i noticed that my fishing loot table was altered by mcmmo plugin. 
I disabled the "ovverride-vanilla treasure" but the loot table is already changed.

Can someone help me to restore the default one?

**Comment by Greymagic27** [comment]
Out of interest, what did you do to make this work?

**Comment by unfairDude** [comment]
> Out of interest, what did you do to make this work?

Used Lucky perms to deny fishing permission of mcmmo plugin
