### ISSUE TITLE
1.19.1 - Hovering over skills in chat output does not return anything.

### ISSUE THREAD

**Issue by mibby** [mcMMO-Dev/mcMMO#4813]
Paper dev 109 / Purpur dev 1749 (Spigot 1.19.1)
mcMMO dev 1326 (https://github.com/mcMMO-Dev/mcMMO/commit/8feba60e2c747d10e6d60ea80a626d88b2413769)

RE: https://github.com/mcMMO-Dev/mcMMO/issues/4792

@nossr50 This issue seems to be back for 1.19.1. Need to update kyori adventure-platform dependencies again and recompile?

**Comment by nossr50** [comment]
Potentially, there were some chat changes in this MC update so I'll look into it soon

**Comment by mibby** [comment]
ShowItem has released an update that fixes hover messages again for 1.19.1+, so assuming possible same problem as before with mcMMO.

**Comment by Greymagic27** [comment]
#4814 - Looks like the 2 dependencies that it relies upon had an update. Both are updated in that PR and it works fine now.

**Comment by nossr50** [comment]
Should be fixed now
