### ISSUE TITLE
My server crashes when players use the tree feller ability

### ISSUE THREAD

**Issue by ItzRobin** [mcMMO-Dev/mcMMO#4815]
Hey,
When my players use the tree feller ability the server crashes. I doesn't happen with any other ability and I have this problem for I while now. I use the latest build of mcMMO: [mcMMO] Running version 2.1.217. This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)

For now I negated the mcmmo.ability.woodcutting.treefeller permission but I would prefer a fix :)
Please see https://pastebin.com/PgKPWx55 for the logs of our latest crash

What should I do to fix this?

**Comment by Greymagic27** [comment]
How much RAM have you allocated to the server? Does it happen on the latest paper update for 1.19?

**Comment by ItzRobin** [comment]
I'm sorry for my late reply, the server has 18 GB and the crash also occurs when the memory is 24 GB. And yes, this is the latest 1.19 build and currently I do not want to run 1.19.1 or 1.19.2

**Comment by nossr50** [comment]
Try changing your -Xss flag to increase the limit on stack memory
