### ISSUE TITLE
There is a conflict between the "VentureChat" plugin and the "party" command.

### ISSUE THREAD

**Issue by Angsimosaurus** [mcMMO-Dev/mcMMO#4823]
With "VentureChat" present, when you enter the "party" command, you receive an error that you do not have permission.

"You do not have permission for this command!"
![image](https://user-images.githubusercontent.com/79510039/187159880-42c2bd2f-7ae9-432c-a1fb-19b7840918d0.png)

**Comment by Greymagic27** [comment]
Venturechat adds a party command so that may be what it's trying to use. 
![image](https://user-images.githubusercontent.com/46166848/187160249-83a8565b-7918-4f3e-970a-35b4f16f5582.png)


Possibly running /MCMMO:party might be a way around this?

**Comment by Angsimosaurus** [comment]
As you said, the command "/mcmmo:party" can be used normally.

I attached the server console window log, but I'm not sure if this is right
https://paste.gg/p/anonymous/f94842acbe0a48c1bd88d6f06bd6d24b
