### ISSUE TITLE
Big amounts of wood breaking at once

### ISSUE THREAD

**Issue by Mappors** [mcMMO-Dev/mcMMO#4834]
**Issue:**
The Tree Feller ability is now breaking down huge amounts of wood which are not trees, when using the Tree Feller ability.

**See example:**
https://youtu.be/iV_xWmxFGyg

Before updating, McMMO checked whether the player was actually hitting a tree that was within the size limit of their limit. Now it just destroys any wood until the limit is reached, with every log they break.

**Comment by ChimpGamer** [comment]
In some cases, this is indeed a pretty game breaking issue.
Please fix!

**Comment by nossr50** [comment]
Unable to replicate with latest paper and latest mcMMO

**Comment by Caleston** [comment]
Tree Feller is just brokenly OP now and that is apparently intended.
