### ISSUE TITLE
no experience gain

### ISSUE THREAD

**Issue by Gnibily1** [mcMMO-Dev/mcMMO#4843]
I have switched perms from Luckperms to PowerRanks. For over a month everything worked fine with mcmmo while using luck perms. I switched over to powerranks for their ranking system and chat config... when i did, I lost all exp gain from Mcmmo. I did not lose any other function. All menues and querier complete and act normal for everyone, but zero exp is given and hitting blocks with the debug says all is well except permissions.
So for the last 4 days... I have contacted your discord, powerranks, my server, and the public... I have gotten alot of advice. So far here is what I have done...
Does it work without any perms... yes
does it work with luckperms... yes
does it work with powerranks... no
does it load properly in server console... yes
are there any errors... no
have you deleted and re-uploaded mcmmo... yes
have you deleted and re-uploaded powerranks, mcmmo, and clearlagg at the same time and spent hours readding all the perms to power ranks from all your other plugins as well as all the perms found in yml... yes
have you added every mcmmo.command and every mcmmo.ability and every mcmmo.skill for each and every item covered in same yml? yes
Does any of this work to establish the connection from the plugin to the players recorded skills and saved info? no
I bought this plugin within the last 2 months. I went to see if there was an update... went to redownload from your site and saw I need to spend more to get a differenty copy than the one I already paid for... So what is going on? Why is everything working out the box except exp gain... and no matter what i do, even giving players all owner and admin capability grants no permission to gain exp... my players at one point could change every aspect of this plugin and yet didnt get a single point of exp when hitting a crop or breaking a block etc... This is across the board. I have had to reload my server many times now messing with any advancements any player might be able to make. 
Is there something in you program that turns on and of exp gains?

**Comment by Gnibily1** [comment]
oh, and to avoid confusion... i do NOT run powerranks and luckperms together as I FULLY understand they are both perm plugins, so that isnt the issue either. Only One perm source in my build, thats poewrranks.

**Comment by Chew** [comment]
Yeah, I'm not sure why you switched off of LuckPerms because it's generally more supported and has a lot more features, and it's what's universally recommended at this point.

```
Does it work without any perms... yes
does it work with luckperms... yes
does it work with powerranks... no
```

Makes it seem like it's PowerRanks based off your own PoE. I'll close until we can confirm this isn't a PowerRanks issue.

**Comment by Gnibily1** [comment]
I moved from luckperms because their ranking system needed total 3 plugins to do the work powerranks does, The issue was fixed by adding in each permission individually, all 100+ of them lol. The issue i found is that Powerranks does not recognize group nodes and only accepts the actual perms on individual basis, wish Luckperms had a better ingame ranking look, I would have stuck with them if i didnt need to add so many plugins to get anything besides chat or basic look guis.

**Comment by nossr50** [comment]
Glad to hear it was resolved, and thank you chew for helping 👍
