### ISSUE TITLE
Unarmed XP bug

### ISSUE THREAD

**Issue by introvertism** [mcMMO-Dev/mcMMO#4844]
Just found out on my server if you have exactly 1 cookie in your hand and you right click a parrot it will instantly kill the parrot which is how it works in vanilla, but once that cookie disappears it thinks you killed it with unarmed and gives you a ridiculous amount of exp... lol for example on my server which I believe has the default XP rates I went from level 1 to level 14000.

Server version: purpur-1856 1.19.2
Mcmmo version: v2.1.218-SNAPSHOT (latest dev I believe)

If you need any other info just let me know! :)

**Comment by introvertism** [comment]
This may be a duplicate of #4838 because if you switch to a sword immediately after using the cookie on the parrot you can do also get 14k swords levels.

**Comment by Chew** [comment]
It does seem to be the same underlying issue, so I'll close this in favor of that. Thank you, though!
