### ISSUE TITLE
Could not pass event TrackDamageByEntityEvent to mcMMO v2.1.218-SNAPSHOT

### ISSUE THREAD

**Issue by SrMonsterYT** [mcMMO-Dev/mcMMO#4845]
this error appears in the console

server: 1.19.2 pufferfish
mcmmo version: 2.1.218-SNAPSHOT

error: https://pastebin.com/XDr50FHx

**Comment by Chew** [comment]
Seems to be related to your other issue, #4846. Closing in favor of that.
