### ISSUE TITLE
The server has not responded for 10 seconds! Creating thread dump

### ISSUE THREAD

**Issue by SrMonsterYT** [mcMMO-Dev/mcMMO#4846]
Server version: 1.19.2 pufferfish
Mcmmo version:  v2.1.218

by removing the plugin the server stopped crashing, everything was fine, this started to happen about 7 days ago, before that everything was ok, and the server is online for more than 6 months

error: https://pastebin.com/rxKs6CZG

**Comment by Chew** [comment]
This seems to be some conflict with `WildStacker`. Does removing that also fix it? Will probably need a heap dump for this to really be useful or diagnosable, though...

**Comment by Chew** [comment]
Closing due to no response.
