### ISSUE TITLE
[Bug] Other plugins having issues with FakeEntityDamageByEntityEvent

### ISSUE THREAD

**Issue by TheosisOfficial** [mcMMO-Dev/mcMMO#4848]
I keep seeing these big exceptions (https://pastebin.com/ArK2XJ3c) saying that it could not pass `FakeEntityByEntityEvent` to some of the plugins I use. I think it might have something to do with Tree Feller but I'm not sure. Was told to raise this issue here as it could be fixed on mcMMO's end, so here I am. :)

**Comment by Chew** [comment]
This seems to have been fixed by #4863. Thank you for reporting!
