### ISSUE TITLE
McMMO crashes with five distinct errors on startup

### ISSUE THREAD

**Issue by Zestari** [mcMMO-Dev/mcMMO#4867]
Coming here with an issue with mcMMO on a Magma 1.18.2 Forge 40.2.0 modded minecraft server. I am using Java 17.

Every time I try to start up my server with mcMMO, it crashes with several different errors ranging from a recipe needs to be non-AIR, no experience.yml file, "out of date?" and com.gmail.nossr50.database.DatabaseManager.onDisable() cause it's null. Not really sure what could possibly be giving the recipe error, and the experience.yml file never loaded up. It's in the jar file, but refuses to become a seperate folder on startup, it doesnt enable.

The host I am using is ApexMC, The modlist is as follows:

18.02 20:26:31 [Server] Server thread/INFO [/]: Mods (160): YUNG's Better Dungeons (betterdungeons v.1.18.2-Forge-2.1.0), Unusual Fish Mod (unusualfishmod v.1.1.0), Stackable Potions (stackablepotions v.1.0.0), Blue Skies (blue_skies v.1.3.12), Goat Horns & Copper Horns Mod (goat_horns_mod v.1.0), YUNG's Better Witch Huts (betterwitchhuts v.1.18.2-Forge-1.0.1), capybara (capybaramod v.0.0.1), Wild Berries (wildberries v.1.1.2), Floral Enchantment (floralench v.1.18.2-1.4.0), YUNG's Better Ocean Monuments (betteroceanmonuments v.1.18.2-Forge-1.0.3), The King of the Village (kingvillager v.1.10), Sophisticated Core (sophisticatedcore v.1.18.2-0.5.37.202), Gem Crab (gem_crab v.1.0.0), Villager Names (villagernames v.5.1), JRFTL (jrftl v.1.4.1), Controlling (controlling v.9.0+22), Prism (prism v.1.0.1), Placebo (placebo v.6.6.6), YUNG's API (yungsapi v.1.18.2-Forge-2.2.7), Feature NBT Deadlock Be Gone (feature_nbt_deadlock_be_gone v.2.0.0+1.18.2), Culinary Construct (culinaryconstruct v.1.18.2-4.3.1.0), Bookshelf (bookshelf v.13.2.52), Turtles Enhanced (turtles_enhanced v.1.0.0), Guard Villagers (guardvillagers v.1.4.3), Bygone Nether (bygonenether v.1.2.2), Balm (balm v.3.2.2+0), Immersive Armors (immersive_armors v.1.5.4+1.18.2), Just Enough Resources (jeresources v.0.14.1.171), Chat Heads (chat_heads v.0.6.1), Cloth Config v4 API (cloth_config v.6.4.90), Structure Gel API (structure_gel v.2.4.7), FlytreLib (flytre_lib v.1.8.2), Enemy Expansion (enemyexpansion v.1.10.0), Mage Flame (mageflame v.1.2.0), Repurposed Structures (repurposed_structures v.5.1.14+1.18.2), More Villagers (morevillagers v.3.3.2), Biomes O' Plenty (biomesoplenty v.0.0NONE), Simple Shops (simpleshops v.1.1.4), Geode+ (geode v.1.1.2+1.18.2), Chunk Animator (chunkanimator v.1.18.2-1.3.4), Craftable Bell (craftablebell v.1.0-1.18.2), Axolotl Bucket Fix (axolotlbucketfix v.1.2.1), Unusual End (unusualend v.1.3.0), SuperMartijn642's Core Lib (supermartijn642corelib v.1.1.2), YUNG's Bridges (yungsbridges v.1.18.2-Forge-2.1.0), Immunity Enchantments (immunity_enchantments v.1.1.0), wthit (wthit v.4.13.6), waila (waila v.4.13.6), Pam's HarvestCraft 2 - Food Extended (pamhc2foodextended v.1.0), You Died (you_died v.1.0.2.9), Creatures and Beasts (cnb v.1.5.1), Curios API (curios v.1.18.2-5.0.8.0), Tinted Campfires (tintedcampfires v.1.18.2-1.2.3), Collective (collective v.6.48), dragonmod (dragonmod v.1.0.0), YUNG's Extras (yungsextras v.1.18.2-Forge-2.1.0), NoCube's Villagers Sell Animals (villagersellanimals v.1.1.4), Better village (bettervillage v.2.0.0), YUNG's Better Strongholds (betterstrongholds v.1.18.2-Forge-2.1.1), Overweight Farming (overweight_farming v.1.18.2-1.6.0-forge), GottschCore (gottschcore v.2.0.0), Chunk Pregenerator (chunkpregen v.1.18-4.1.1), Architectury (architectury v.4.11.89), Curious Elytra (curiouselytra v.1.18.1-5.0.1.0), Chimes (chimes v.1.1.2), Glow Inc. (glowinc v.1.18.2_1.2.3), The Undergarden (undergarden v.0.7.1), Mushlings Mod (mushlings v.1.0.0), Easy Shulker Boxes (easyshulkerboxes v.3.1.1), More Axolotl Variants Mod (mavm v.1.2.0), FastLeafDecay (fastleafdecay v.28), CodeChicken Lib (codechickenlib v.4.1.3.480), YUNG's Better Mineshafts (bettermineshafts v.1.18.2-Forge-2.2), GeckoLib (geckolib3 v.3.0.57), Blåhaj - Reforged (blahaj v.0.1.1), Skillcloaks (skillcloaks v.1.18.2-1.0.8), Kiwi (kiwi v.6.1.3), Xtra Arrows (xtraarrows v.2.4.1), Pam's HarvestCraft 2 - Trees (pamhc2trees v.1.0.1), Shield Mechanics (shieldmechanics v.1.18.2-3.2), DeathKnell (deathknell v.3.0.2), Nyf's Spiders 2.0 (spiderstpo v.2.0.3), Creatures from the Lush Cave (creaturesfromthelushcave v.1.0.1), Additional Lanterns (additionallanterns v.1.0.3), Tiny Item Animations (tia v.1.18.2-1.0), Just Enough Items (jei v.10.2.1.1002), JEI Enchantment Info (jeienchantmentinfo v.1.17.1-2.0.0), Universal Bone Meal (universalbonemeal v.3.0.5), MMOParties (mmoparties v.2.4.0), Library ferret (libraryferret v.3.0.0), Dog Yeeter (dog_yeeter v.22.08.11), Caelus API (caelus v.1.18.1-3.0.0.2), Kobolds (kobolds v.2.1.2), Waystones (waystones v.10.1.0), Builder's Delight (buildersdelight v.1.0), Fast Suite (fastsuite v.3.0.2), Journeymap (journeymap v.5.9.3), Dual Riders (dual_riders v.1.1.1), Bad Packets API (badpackets v.0.1.3), Alcocraft (alcocraft v.1.0.0), BotanyPots (botanypots v.8.1.25), Snuffles (snuffles v.1.0.2), YUNG's Better Desert Temples (betterdeserttemples v.1.18.2-Forge-1.3.1), Terralith (terralith v.0.0NONE), Blueprint (blueprint v.5.5.0), EnderStorage (enderstorage v.2.9.0.182), Forge (forge v.40.2.1), More Wandering Trades (more_wandering_trades v.1.0.0), Valued XP (valuedxp v.1.18.2-1.0.3), Friends&Foes (friendsandfoes v.1.4.6), Selene (selene v.1.18.2-1.17.9), Supplementaries (supplementaries v.1.18.2-1.5.16), Iron Chests (ironchest v.1.18.2-13.2.11), Minecraft (minecraft v.1.18.2), No Night Vision Flashing (no_nv_flash v.1.4.0.2), Undergarden Gem Crabs (undergarden_gem_crabs v.1.0.0), Simply Swords (simplyswords v.1.30-1.18.2), TerraBlender (terrablender v.1.2.0.126), Mouse Tweaks (mousetweaks v.2.21), Baby Fat (babyfat v.1.18.2-1.1.2), Silent Lib (silentlib v.6.2.0), Pam's HarvestCraft 2 - Crops (pamhc2crops v.0.0NONE), Majrusz Library (mlib v.3.1.0), Sculpt (FORGE) (sculpt v.1.1.1), Iceberg (iceberg v.1.0.49), Pam's HarvestCraft 2 - Food Core (pamhc2foodcore v.1.0.1), Dyed (dyed v.1.1.0), Croptopia (croptopia v.2.1.0), Fast Workbench (fastbench v.6.1.1), Sit (sit v.1.3.3), UnusualGIfts (unusual_gifts v.1.0.1), Effective (Forge) (effective_fg v.1.2.4), Dyeable Fishing Lines (dyeablefishinglines v.1.0.0), FastFurnace (fastfurnace v.6.0.3), Creeper Overhaul (creeperoverhaul v.1.3.1), AppleSkin (appleskin v.2.4.1+mc1.18.2), Alex's Delight (alexsdelight v.1.3.3), Citadel (citadel v.1.11.3), Alex's Mobs (alexsmobs v.1.18.6), Farmer's Delight (farmersdelight v.1.18.2-1.2.0), Enhanced Mushrooms (enhanced_mushrooms v.4.0.1), Variant Crafting Tables (vct v.1.18.2-1.7.0_1), Pollen (pollen v.1.6.1), Opulence (opulence v.0.1.2), Nethers Delight (nethersdelight v.2.2), Visuality: Reforged (visuality v.1.0), DamageTilt (damagetilt v.0.1.1), Puzzles Lib (puzzleslib v.3.3.5), Plus The End (plus_the_end v.1.0.0), Oh The Biomes You'll Go (byg v.1.4), Dramatic Doors (dramaticdoors v.1.18.2-2.1.9), featherToString (feathertostring v.1.0.0), Aquaculture 2 (aquaculture v.1.18.2-2.3.10), Majrusz's Enchantments (majruszsenchantments v.1.8.0), CHA&S - Craftable Horse Armour and Saddle (craftablehorsearmour v.1.8), Silk Touch Spawners (silk_touch_spawners v.1.0.0), Crossbowverhaul (crossbowverhaul v.1.4.1), quartz colors (quartz_colors v.5), More Axolotl Variants API (mavapi v.1.0.1), CosmeticArmorReworked (cosmeticarmorreworked v.1.18.2-v2a)

The log will be massive, but the errors for mcMMO start when you see the LuckPerms logo near the bottom. 

I am not concerned for any other mod issue at this time, but if any others stand out, I'd love to see what other stuff is erroring, however it is not game-breaking as of now.

[latest (2).log](https://github.com/mcMMO-Dev/mcMMO/files/10775128/latest.2.log)

**Comment by Chew** [comment]
We do not support issues that solely happen Bukkit+Forge hybrids, they are unstable and unsupported. If you can reproduce this on just Bukkit, preferably Paper, we can reopen this issue.
