### ISSUE TITLE
Option to disable party?

### ISSUE THREAD

**Issue by L4BORG** [mcMMO-Dev/mcMMO#4873]
In the past there were some issues around hacky ways of disabling party feature, this should mostly be resolved now by recent MC updates?

Same way mcmmo chat features/commands can be toggled on/off and then loaded by CommandManager class whole party system could be toggled on/off?

**Comment by djcflores** [comment]
I agree with this. People in Discord server doesn't provide any concrete answer on how to do it. They will only just say to check "config.yml" but there is nothing there.
