### ISSUE TITLE
Folia support

### ISSUE THREAD

**Issue by Q2297045667** [mcMMO-Dev/mcMMO#4892]
Are there any plans to support Folia in the future?
Folia is a great project, he solved many problems
https://github.com/PaperMC/Folia

**Comment by kit8379** [comment]
Is there any news?

**Comment by Q2297045667** [comment]
> Is there any news?

NO

**Comment by Chew** [comment]
Folia isn't a huge priority but this is an open source project and we always accept contributors :)

**Comment by TechnicallyCoded** [comment]
@nossr50 Could this be marked as resolved?

**Comment by Yomamaeatstoes** [comment]
Lol

**Comment by Q2297045667** [comment]
> @nossr50 Could this be marked as resolved?

Yes, I will close this issue because mcmmo seems to run well under Folia
