### ISSUE TITLE
How to remove/change command from the plugin.yml

### ISSUE THREAD

**Issue by SeussCZ** [mcMMO-Dev/mcMMO#4938]
Hi, how do I remove or change commands from the plugin.yml? Everytime I do, and restart, it doesn't work. It shows up broken. Can anyone help?

Negating the permission nodes using a permission plugin doesn't work when I want to use another plugin for the same command (McMMo has always priority).

**Comment by SrBedrock** [comment]
You should use the `commands.yml` file where your `server.jar` is located: https://bukkit.fandom.com/wiki/Commands.yml

**Comment by SeussCZ** [comment]
> You should use the `commands.yml` file where your `server.jar` is located: https://bukkit.fandom.com/wiki/Commands.yml

`commands.yml` file cant help with this. I want to use another Party system plugin, so if I use mcmmo party command has always priority. Its necessary to remove this command.

**Comment by Chew** [comment]
I would need an example of such a party plugin, because using the alias to override mcMMO's does indeed look possible per that link, something like this:

```yml
aliases:
  party:
  - "myplugin:party $1-"
```

But either way, this is out of scope of this plugin/issue tracker. I'm sure there's also safer ways around this as well.
