### ISSUE TITLE
Minecraft 1.20.2 broke ability activation messages on screen.

### ISSUE THREAD

**Issue by andrewkm** [mcMMO-Dev/mcMMO#4947]
Paper 1.20.1 Build 196 - **Works**
Paper 1.20.2 Build 197 - **Broken**
Testing against latest mcMMO on both above; compiled against: https://github.com/mcMMO-Dev/mcMMO/commit/12e5a7f054234e4eb49fd4351df4fbd46dc35de7
Testing on clean default environment with only Paper + mcMMO on server, nothing else.

Reproduction:
1. /mmoedit <username> woodcutting 1000
2. Hold Diamond Axe.
3. Right click, the "you ready your axe" as well as "tree feller activated" ability messages do not appear.

Same goes for all ability messages.
@nossr50

**Comment by Popoboxxo** [comment]
+1

**Comment by andrewkm** [comment]
Confirmed fixed with https://github.com/mcMMO-Dev/mcMMO/commit/a54590576f996ba58d1caa5796f5a760527722ee
Thanks! :)

**Comment by andrewkm** [comment]
@nossr50 this is broken once more.
