### ISSUE TITLE
1.20.4 can not show the skill cooldown message

### ISSUE THREAD

**Issue by saiyzh** [mcMMO-Dev/mcMMO#4957]
1.20.4 can not show the skill cooldown message or use skill message

**Comment by tticehurst** [comment]
Can confirm running same version, no "you ready your <tool here>" messages nor cooldown messages

**Comment by saiyzh** [comment]
![image](https://github.com/mcMMO-Dev/mcMMO/assets/40679184/c79c25af-6229-475f-88de-57ef30ac19da)

**Comment by tticehurst** [comment]
The Oct fix for text not being displayed is prior 1.20.4 where this bug occurs. It worked fine in 1.20.2

**Comment by nossr50** [comment]
This might require an adventure API update, I'll look into this soon
