### ISSUE TITLE
Discrepancies between the stated defaults and actual defaults, and more

### ISSUE THREAD

**Issue by jonjbm** [mcMMO-Dev/mcMMO#4960]
On the Changelog page on mcmmo.org, it says the following:

> New Level Scaling
> - mcMMO now features an optional 1-100 scaling mode!
> - This is on by default for new installs, if you are upgrading mcMMO you will be put into Retro Mode instead (1-1000) scaling.

Yet you can look at the config.yml file on Github right now and see the following line:

>     RetroMode:
>         Enabled: true

So, the new level scaling is actually not on by default.

Also, why is the Acrobatics XP this high in experience.yml:

>     Acrobatics:
>         Dodge: 800
>         Roll: 600
>         Fall: 600

Everywhere online, including your own wiki, states "120XP per half heart of damage is gained when taking fall damage", which seems much more reasonable. The current defaults, quoted above, result in a player often gaining several levels at a time from one short fall. This seems a bit ridiculous.

I simply want to use mcMMO with the default values, but that is proving to be difficult when its not even clear what the default values are supposed to be.

**Comment by nossr50** [comment]
Standard Mode was a mistake, retro mode has been the default for a few years.
Default values are put into the default config folder (generated in new versions)
