### ISSUE TITLE
Mining level XP goes up when you place block by yourself

### ISSUE THREAD

**Issue by SirvydasS** [mcMMO-Dev/mcMMO#4964]
Video: https://youtu.be/J5dYWMEbhRw
https://youtu.be/kh432OwOI6s

**Comment by Chew** [comment]
There seems to be a lot of plugins on the server, so it's hard to pinpoint just mcMMO as the cause. Additionally, what's the plugin and server version?

**Comment by SirvydasS** [comment]
mcMMO: 2.1.228-SNAPSHOT

Current: git-Purpur-2127 (MC: 1.20.4)*
* You are running the latest version

**Comment by SirvydasS** [comment]
Seems ok for now maybe, problem was with AdvancedEnchantments plugin https://github.com/GC-spigot/AdvancedEnchantments/issues/4047
