### ISSUE TITLE
Items are not replanted if they are off-hand

### ISSUE THREAD

**Issue by thiagogebrimm** [mcMMO-Dev/mcMMO#4994]
I place the item as an example carrot in the off-hand and it does not replant with the skill

**Comment by neviskcubo** [comment]
really, players who play massively and farm a lot end up being harmed by the simple fact that the autoreplant ignores the offhand, I don't see it as something difficult to fix

**Comment by thiagogebrimm** [comment]
https://github.com/mcMMO-Dev/mcMMO/pull/4997
