### ISSUE TITLE
Extreme lag in swords counter after recent update

### ISSUE THREAD

**Issue by madebygood** [mcMMO-Dev/mcMMO#4995]
![image](https://github.com/mcMMO-Dev/mcMMO/assets/43653581/33eb39d4-bd7c-467b-8f60-1df73180f823)

The swords' counter skill causes extreme lag during combat.

Please solve it quickly!
thank you

**Comment by nossr50** [comment]
Could you provide the spark report?

**Comment by madebygood** [comment]
> Could you provide the spark report?

https://spark.lucko.me/nN5YJEmnzY

**Comment by akiakyo** [comment]
happens to me too: https://mclo.gs/C2Dogzn

**Comment by nossr50** [comment]
@madebygood looks like I didn't get to that spark report in time and it expired, do you mind posting another?

**Comment by nossr50** [comment]
Closing this issue due to lack of response, feel free to reopen if you can get another spark report.
