### ISSUE TITLE
Maces showcases, command output and small translation issues

### ISSUE THREAD

**Issue by ILikeOrangeJuice** [mcMMO-Dev/mcMMO#5009]
Hello, not sure when it occured as we just updated after a while, but in 2.2.007 (assuming 8 too but that won't start up), at least in the de_DE translation, using /mcrank, there is a maces skill, however it is not present in /mcstats. Also using /maces has no output or anything. 

Is this intended? I know they come in 1.21, so it makes no sense to implement/output either in a lower versions, in our case 1.20.1, but  also shouldn't it show in both commands and have an output in /maces if it is alrdy implemented.

Also in the de_DE translation it says Tridents which should be Dreizack, Crossbows which should be Armbrust in the /mcstats command.
In /mcrank it is CROSSBOWS which should be again Armbrust, TRIDENTS which should be Dreizack and even taming is wrong and all capitalized in that one, it is ZÄHMEN while it should be Zähmen. MACES is also full caps.

Best regards.

**Comment by nossr50** [comment]
I added code to support maces to mcMMO in 2.2.007, however it is not in the game yet so I've disabled the command.

The locale is updated by the community, feel free to update that translation and submit the update here on github via pull request.
