### ISSUE TITLE
Night vision does not work with redstone dust

### ISSUE THREAD

**Issue by broken1arrow** [mcMMO-Dev/mcMMO#5011]
Version: 2.2.010
paper: 
This server is running Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)
[Server] INFO You are running the latest version.

For at least night vision the redstone dust does not extend the time.

**Comment by broken1arrow** [comment]
I have not get check all potions, but at least night vision works now and swiftness still working in the latest.

**Comment by nossr50** [comment]
Closing as fixed, reopen if you find something new
