### ISSUE TITLE
Spawner Plugin hook

### ISSUE THREAD

**Issue by ClickErrorxD** [mcMMO-Dev/mcMMO#5016]
![image](https://github.com/mcMMO-Dev/mcMMO/assets/87890013/26c5c49e-6a15-4aa0-b52e-497a5bdead94)
Please add a hook for https://www.spigotmc.org/resources/upgradeable-spawners-⭕-spawner-levels-plugin-✅-entity-stacking-butcher-1-20-support.77717/updates. Player's are getting thousand of sword levels from mob spawner mobs from this plugin under a month of the server being opened.

**Comment by nossr50** [comment]
The other plugin could hook into us, so it's really a matter of "who wants to do it first"

**Comment by Chew** [comment]
Considering we're the more popular plugin, and we're actually open source like we should be, we will leave this up to the author to hook into us as needed.

Alternatively, consider tuning your config to scale it to match the plugin's scaling.
