### ISSUE TITLE
mcMMO Super Breaker Efficiency holding when interacting with QuickShop Remake

### ISSUE THREAD

**Issue by skyefugate** [mcMMO-Dev/mcMMO#5018]
Hi! When using the Super Breaker ability for mcMMO, a user can take the implicated tool that has the buff, input it into a QuickShop shop and then break the chest that is holding the tool. Once the chest breaks, it will permanently hold the modified efficiency enchantments on the tool. 

This was tested on the below configuration
Minecraft 1.20.4
QuickShop 5.1.2.5
mcMMO 2.1.223

**Comment by nossr50** [comment]
Likely this other plugin would need to call our API to remove the "super ability" buffs.
