### ISSUE TITLE
Super breaker eff increase maintained if put into a pot.

### ISSUE THREAD

**Issue by andystar22** [mcMMO-Dev/mcMMO#5019]
placing a tool under the effects of super breaker into a pot allows it to maintain its increased eff after the pot is broken.

**Comment by Geekerandy** [comment]
Cannot reproduce under
Minecraft 1.20.6 launched with Paper Build #138 (latest as of this comment)
and mcMMO v2.2.012 (latest as of this comment)
Are there other plugins that may affect the NBT/Component data of items?

**Comment by Geekerandy** [comment]
And I would like to clarify when the item came out of the pot, it did still have the boosted Efficiency but would revert back to its original state after a brief period.

**Comment by andystar22** [comment]
issue may be that placing item in pot removes the check for moving super breaker items into containers
players were able to use it in a anvil

**Comment by Geekerandy** [comment]
Tested once more on my personal server under these conditions

**Comment by Geekerandy** [comment]
Unable to produce once more on my server under these conditions
Minecraft 1.20.6 launched with Paper Build 138
mcMMO v2.2.012
Activated Super Breaker, put the pickaxe into the pot, waited for super breaker to end, opened the pot, opened the anvil, and mcMMO's safeguard to clear boosted enchants upon opening any container kicked in.
Attempted these exact steps again without waiting for super breaker to end, boosted enchants were cleared upon accessing the anvil.
This was tested with Mining level 1000 and a base wooden pickaxe.

**Comment by andystar22** [comment]
may be a plugin conflict then

**Comment by Geekerandy** [comment]
Just adding on one last reproduction attempt here, I managed to get it into my inventory still enchanted with the anvil accessed through a hopper-dispenser setup, but the moment I even attempted to move the pickaxe, whether by shift-clicking or manual clicking, it would *immediately* revert to normal.
