### ISSUE TITLE
Error with advanced enchantments

### ISSUE THREAD

**Issue by MarcosClemente13** [mcMMO-Dev/mcMMO#5022]
I have the advanced enchantments plugin and when adding the mcmmo in version 2.1.231, I get an error with various custom enchantments and I get this error in the console.
[message (1).txt](https://github.com/user-attachments/files/15859896/message.1.txt)

**Comment by nossr50** [comment]
Looks like a problem on the end of the other plugin, or possibly from corrupted JARs
