### ISSUE TITLE
[2.2.013, Paper 1.21-37 (latest as of this report)] Super Breaker/Giga Drill Breaker granting Luck of the Sea instead of Efficiency

### ISSUE THREAD

**Issue by Geekerandy** [mcMMO-Dev/mcMMO#5026]
As shown in the video, under the conditions of MC 1.21:
with mcMMO 2.2.013
and the latest Paper build for 1.21, being Build 37 at the time of this issue
with freshly regenerated mcMMO configs
with a freshly spawned Iron Pickaxe, free of any additional Components
Activating Super Breaker grants Luck of the Sea V instead of the expected Efficiency V.
https://youtu.be/xP-8GRyj-EM
The same occurs with Giga Drill Breaker.

**Comment by xpvtryanx** [comment]
I am having this same issue!

**Comment by MC-MrBirdy** [comment]
Could this issue be because Paper now by default is Mojang mapped?
I have solved the issue by changing the functions like `initEfficiency()`

Instead of having the for loop:
```java
for (Enchantment enchantment : Registry.ENCHANTMENT) {
    if (enchantment.getKey().getKey().equalsIgnoreCase("EFFICIENCY")
            || enchantment.getKey().getKey().equalsIgnoreCase("DIG_SPEED")
            || enchantment.getName().equalsIgnoreCase("EFFICIENCY")
            || enchantment.getName().equalsIgnoreCase("DIG_SPEED")) {
        return enchantment;
    }
}
```

I replaced it with the following:
```java
if (Registry.ENCHANTMENT.get(NamespacedKey.minecraft("efficiency")) != null)
{
	return Registry.ENCHANTMENT.get(NamespacedKey.minecraft("efficiency"));
}
```

**Comment by nossr50** [comment]
I don't think Paper being Mojang mapped has anything in particular to do with this, but I'm not certain of it either. In mcMMO we don't really use any NMS, so the mappings shouldn't affect us. I'm looking into this issue, which may be a Paper bug, or may be something I need to change on my end.

**Comment by nossr50** [comment]
> Could this issue be because Paper now by default is Mojang mapped? I have solved the issue by changing the functions like `initEfficiency()`
> 
> Instead of having the for loop:
> 
> ```java
> for (Enchantment enchantment : Registry.ENCHANTMENT) {
>     if (enchantment.getKey().getKey().equalsIgnoreCase("EFFICIENCY")
>             || enchantment.getKey().getKey().equalsIgnoreCase("DIG_SPEED")
>             || enchantment.getName().equalsIgnoreCase("EFFICIENCY")
>             || enchantment.getName().equalsIgnoreCase("DIG_SPEED")) {
>         return enchantment;
>     }
> }
> ```
> 
> I replaced it with the following:
> 
> ```java
> if (Registry.ENCHANTMENT.get(NamespacedKey.minecraft("efficiency")) != null)
> {
> 	return Registry.ENCHANTMENT.get(NamespacedKey.minecraft("efficiency"));
> }
> ```

Thanks for this info, I was able to come up with a workaround
