### ISSUE TITLE
no taming levels

### ISSUE THREAD

**Issue by SexyLemonz** [mcMMO-Dev/mcMMO#5028]
i get zero taming levels from taming wolfs and zero levels from the wolf killing mobs, ive tried it on 3 different servers because i thought another plugin may be causing it, ive even tried it with just mcmmo installed and it does it on the latest version

**Comment by sirparz** [comment]
We also have this issue with dogs not getting taming XP and dogs apparently taking more damage from wither skeleton more often in the wither skeleton grinder

**Comment by nossr50** [comment]
I'm unable to replicate this problem, I summoned a wolf and skeleton, tamed the wolf, had it attack the skeleton, and I got XP for when the wolf was tamed and for when the wolf damaged the skeleton.
