### ISSUE TITLE
Alchemy doesn't work properly with the experience

### ISSUE THREAD

**Issue by Wisconsie** [mcMMO-Dev/mcMMO#5040]
Hi, 

We created a potion stage and the experience of each potion is completely random. We kept the basic configuration for the potion experience.

For example : a stage 1 is giving 600 on the configuration and it give us first 2500exp, we make another one it was 2250

I hope it's clear. 

Have a nice day. 
Wisconsie

**Comment by nossr50** [comment]
You likely are trying to edit the old configuration keys
In https://github.com/mcMMO-Dev/mcMMO/commit/5ba6305ad4d5047cd22fdf6614a73c8dd4953ed6#diff-c063a86d713adee861c705391d73e5ae46dab41f15099e382bca1088c98a4fb5 I changed the potion XP to be increased and moved their configuration keys into a Potion_Brewing section, you will need to edit the values for this new section.
