### ISSUE TITLE
Please Add in Config to set Bonus Dmg per Attack Strength

### ISSUE THREAD

**Issue by Lia-LV** [mcMMO-Dev/mcMMO#5048]
Let the server set up bonus dmg proportional application according to "attack strength".

in mcMMO 2.2.015 update:
```
Fixed a bug where spamming attacks would still apply full bonus dmg and full chance to proc abilities (see notes) 

When you swing your weapon in Minecraft, you gain an "Attack Strength" value, which is relative to your cooldown, mcMMO was supposed to be making use of this value, but at some point in the past this was broken.
I have fixed this and now mcMMO will use the attack strength value to determine the bonus damage and chance to proc abilities.
For servers modifying Minecraft combat to not have this "cooldown", mcMMO should behave as you would expect, with full damage and full chance to proc abilities even when spamming attacks.
```

On my server, there are users who want bonus dmg that is not proportional to the attack strength. 
Can't you let the server's admin set this content by skills in config.yml or advanced.yml?

**Comment by nossr50** [comment]
I was thinking that servers would disable the whole attack cooldown mechanic if they wanted this, but I can add in a config option. It'd just be strange to have the attack cooldown mechanic left as-is and then have mcMMO ignore it, or so I thought.
