### ISSUE TITLE
Player can't get Alchemy exp on mcMMO 2.2.017 (Paper 1.20.6)

### ISSUE THREAD

**Issue by Lia-LV** [mcMMO-Dev/mcMMO#5051]
Alchemy isn't able to increase the experience even in the latest version.
I'm on Paper 1.20.6 latest version, and mcMMO latest version(2.2.017)

![image](https://github.com/user-attachments/assets/acfbc3ec-9cf6-4004-adec-b5a15c9de9c2)
![image](https://github.com/user-attachments/assets/c7abc0ec-e9fc-459c-ad75-7567697e617e)

**Comment by nossr50** [comment]
Not able to reproduce, check player permissions, reopen ticket if issue persists
