### ISSUE TITLE
Acrobatics (% of dodge error

### ISSUE THREAD

**Issue by neviskcubo** [mcMMO-Dev/mcMMO#5054]
after the bug in acrobatics where the dodge chance increased infinitely was fixed, it was no longer necessary to have 1000 acrobatics to reach the maximum, it was now at level 200

![image](https://github.com/user-attachments/assets/5b6ef68d-5b0a-4c3c-b2d1-1d57cee7db09)
![image](https://github.com/user-attachments/assets/2e856321-adae-4bc9-aaac-2509d7d6532d)
![image](https://github.com/user-attachments/assets/4f09d0a2-78bd-44a4-b3e9-54c70cded3d4)

config:
https://mclo.gs/gJ5N5qO

**Comment by Chew** [comment]
Can you please provide a description or log so we can investigate this?

**Comment by neviskcubo** [comment]
> Can you please provide a description or log so we can investigate this?

I attached it again, for some reason it came out empty
