### ISSUE TITLE
Acrobatics (dodge skill not scaling correctly)

### ISSUE THREAD

**Issue by neviskcubo** [mcMMO-Dev/mcMMO#5055]
After the bug in acrobatics where the dodge chance increased infinitely was fixed, it was no longer necessary to have 1000 acrobatics to reach the maximum, it was now at level 200

![image](https://github.com/user-attachments/assets/b8802fca-da76-4cef-9236-d76f3c018b00)
![image](https://github.com/user-attachments/assets/94d34942-0f8c-4ffa-bd75-821cd57f1e6d)
![image](https://github.com/user-attachments/assets/a5e0cc5a-69d9-4718-aa94-539013c5de23)

config:
https://mclo.gs/mtiFWPN

**Comment by thiagogebrimm** [comment]
same problem

**Comment by nossr50** [comment]
Thanks for the report, I will look into it.
