### ISSUE TITLE
MCMMO skills being blocked by anticheat

### ISSUE THREAD

**Issue by Nexis-Black** [mcMMO-Dev/mcMMO#5057]
Hi we're having issues with MCMMO being compatible with our anticheat, we were working with the dev for the anticheat and we had most of the issue resolved but he said "It's a problem of McMMO API, is it possible for you to contact the creator about it? It's always returning false when this needs to be true." Is there any chance we could get a fix for this or does something for it already exist? Thank you!

**Comment by Chew** [comment]
We would need context for what "It's always returning false when this needs to be true" is referring to. Could you happen to get them to reply to this so we can fix the issue?

**Comment by Nexis-Black** [comment]
Here's the code he was referring to, said it had to do with the return boolean of the API. I also have the jar file for this but it won't let me attach it here so lmk how I can get that to you if needed.
[mcMMOManager.txt](https://github.com/user-attachments/files/16397230/mcMMOManager.txt)

**Comment by Chew** [comment]
Yeah that looks like their code, but we need to know what mcMMO function on our end is returning false so we can fix it.

Looks like the calls I'm seeing are:

* [WorldBlacklist#isWorldBlacklisted](https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/config/WorldBlacklist.java#L24-L32)
* [WorldGuardUtils#isWorldGuardLoaded](https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/worldguard/WorldGuardUtils.java#L44-L51) 
* Various [WorldGuardManager](https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/worldguard/WorldGuardManager.java#L21-L41) functions.
* [UserManager#hasPlayerKey](https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/util/player/UserManager.java#L163-L165)
* [McMMOPlayer#getAbilityMode](https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/datatypes/player/McMMOPlayer.java#L388-L396)

Only a few of these are booleans though

**Comment by Nexis-Black** [comment]
I think it's returning this: "[FA] [mcMMO] The player is in a blacklisted world!"

[2024-07-28 (1).txt](https://github.com/user-attachments/files/16404210/2024-07-28.1.txt)

Also here's the logs for activating tree feller and super breaker. Idk if this helps any or not but the anticheat dev said to get those and send them too so.

**Comment by SexyLemonz** [comment]
i have the same issue, anyone figure out how to fix it?
