### ISSUE TITLE
Massive console spam due to potion errors

### ISSUE THREAD

**Issue by HorusApl** [mcMMO-Dev/mcMMO#5059]
As far as I can tell, there isn't any duplicates in the potions.yml but it constantly spams this error whenever someone is brewing potions:
https://mclo.gs/7ZpKSOU

**Comment by nossr50** [comment]
1. Update Paper/Spigot if you haven't already, /version can tell you how many versions behind you may be
2. Delete potions.yml and mcMMO will make a new one next start up

Questions
1. What version of mcMMO?
2. What version of Minecraft?
3. What version of Paper/Spigot?

**Comment by HorusApl** [comment]
Version 1.21-2275 Purpur
Version 2.2.017 McMMO
Normal 1.21 MC client
I have already attempted to regen my options.yml and I didn't help

**Comment by HorusApl** [comment]
Just an update, I do believe this might be causing some possible crashes if multiple people are brewing at the same time and with many brewing stands. I made the potions.yml blank, and all crashes I was having stopped

**Comment by nossr50** [comment]
The error is indicating you have multiple entries in potions.yml which are designated as the "result" for a brewing stand, you probably didn't edit potions.yml yourself, but if you did, this might be why. I'd normally recommend deleting potions.yml and restarting the server when seeing this error.

You have indicated you have already done this, so my next suspicion is that perhaps the issue lies with PurPur, try to see if you can recreate this problem on Paper and report back.

**Comment by HorusApl** [comment]
That was the first thing I tried and I have made no edits to potions yml

**Comment by HorusApl** [comment]
Will try with Paper

**Comment by Tomographix** [comment]
Hi,

I can confirm the issue with paper. I also deleted the potions.yml file thinking that would be a quick fix but sadly that didn't make a difference.

Paper version: 1.21-122
MCMMO Version: 2.2.017

**Comment by HorusApl** [comment]
Confirmed happening on paper as well, with a fully fresh potions.yml

**Comment by Baktus79** [comment]
Same here.

Paper version 1.21-130
mcMMO version 2.2.018

**Comment by nossr50** [comment]
Can you post your potions.yml file? I know you generated a fresh one, but I just want to sanity check that it generated correctly.

**Comment by HorusApl** [comment]
Here ya go: https://mclo.gs/JPxtEou

**Comment by Cruwzky** [comment]
We also see this issue

Config: https://mclo.gs/LWAWwk6
Version: 2.2.019-SNAPSHOT
Minecraft: Purpur 1.21-2281-7950960 (MC: 1.21)*

**Comment by Baktus79** [comment]
This issue is still present. Are there any progression on this matter?

**Comment by nossr50** [comment]
> This issue is still present. Are there any progression on this matter?

Hoping to put a patch out this weekend
