### ISSUE TITLE
Alchemy is way to easy to level now

### ISSUE THREAD

**Issue by 777555777** [mcMMO-Dev/mcMMO#5062]
With a proper (vanilla) setup you can farm level 1 to 1000 in 20-30 minutes, which is almost impossible with any other skill.
With the old values (from 10 years ago) farming level 1000 with a proper setup would have taken almost 19 times as long (6+ hours) which might be too grindy, as stated in the changelog. So my suggestion would be to restore the values from 2.2.007 or even chose slightly smaller values (e. g. 300 for stage 4, which would still be 2.5 times as fast as previously (3h+ with the proper setup)).

Compared to other skills like archery, alchemy wasn’t that grindy. Although, archery is usually leveled on the side through normal gameplay, while alchemy is mostly actively leveled to increase the level. So a somewhat increased value (compared to 120 xp for stage 4) might be sensible.

**Comment by nossr50** [comment]
Alchemy was an absurd grind for the casual player who didn't want to setup a factory for the sole purpose of leveling Alchemy, and I think it's better this way, server admins can configure the XP values however they want and change it back.
