### ISSUE TITLE
Alchemy doesn't work for bedrock players

### ISSUE THREAD

**Issue by JHarris12345** [mcMMO-Dev/mcMMO#5070]
Bedrock players are not able to put alchemy recipes in  a brewing stand. E.g. It wont let them click an apple in

**Comment by Greymagic27** [comment]
I'm not surpised and wouldn't be surprised if this issue was closed. This is a Java edition plugin. Bedrock compatability is not garunteed.

**Comment by nossr50** [comment]
> Bedrock players are not able to put alchemy recipes in a brewing stand. E.g. It wont let them click an apple in

Likely would not be able to fix this on my end even if I wanted to.

**Comment by Chew** [comment]
To add, this is likely a bedrock limitation and can't be worked around anyway.
