### ISSUE TITLE
[Bug] Tool durability becomes negative.

### ISSUE THREAD

**Issue by RunqRun** [mcMMO-Dev/mcMMO#5072]
Tree Feller makes the tool unbreakable with a negative durability value.
![image](https://github.com/user-attachments/assets/7f8b78b6-33e6-4b3d-aaf7-5feb3ff90434)

**Comment by Greymagic27** [comment]
I can't reproduce this. I'm using 1.12.1-41 paper with the latest mcmmo.

**Comment by nossr50** [comment]
Can't reproduce
