### ISSUE TITLE
Scoreboard cannot display all skill (stats)

### ISSUE THREAD

**Issue by mrfloris** [mcMMO-Dev/mcMMO#5076]
/mcstats
<img width="265" alt="Screenshot 2024-08-28 at 10 47 58" src="https://github.com/user-attachments/assets/5d4009dc-327a-4e20-90cf-f6c692ee7f47">

Crossbows and Maces are not listed, probably because it can only list 15 skills.
Could we perhaps get pagination?

/mcstats -> /mcstats 1
/mcstats 2

```
mcMMO Stats <gray>(1/2)
---------------------------
Power Level: 12345
skill 17
skill 16
skill 15
skill 14
skill 13
skill 12
skill 11
skill 10
skill 9
--------------------------
More: /mcstats 2
```
```
mcMMO Stats <gray>(2/2)
---------------------------
Power Level: 12345
skill 8
skill 7
skill 6
skill 5
skill 4
skill 3
skill 2
skill 1
--------------------------
Back: /mcstats 1
```
And of course /mcsb keep, to keep the appropriate page.

Or some other solution, this would potentially also open it up to have a config yml toggle to include salvage and other 'child' skill stats.

**Comment by Momshroom** [comment]
Noting here that the output is sorted by your level, so whichever  skills you are lowest level in do not show in the scoreboard: it's not specific to any individual skills.  
Also, if you have /stats configured to show in chat, all skills do show there.

Floris' suggestion of two scoreboards would fix it.

**Comment by mrfloris** [comment]
Yeah, i figured, but it is sometimes the lower stats that we want to grind, so you /mcstats to get the overview. 
Yeah, we show it in chat, and it does show fully there, indeed.
