### ISSUE TITLE
/party command not taking priority

### ISSUE THREAD

**Issue by Projecki** [mcMMO-Dev/mcMMO#5087]
Is there a way to rename /party command? It is overridden by MythicDungeons party command, even when I type /mcmmo:party it still directs to the mythicdungeons party command?

**Comment by RichAudio** [comment]
We use both mcMMO and dungeons. MD is saying that mcMMO is not properly registering / party with the bukkitAPI.
Is it possible to change  mcMMO party command to /mparty or something similar?

**Comment by nossr50** [comment]
Look into command aliasing, I believe that's a popular solution
