### ISSUE TITLE
[BUG] Could not pass EntityDamageEvent to MCMOO

### ISSUE THREAD

**Issue by kristouffe** [mcMMO-Dev/mcMMO#5101]
[pastebin link](https://pastebin.com/x1ufppQW)

happens sometimes when you hit entities. Cannnot clearly reproduce.

**Comment by kristouffe** [comment]
Got told that you are using damage cause MAGIC for your acrobatic skill, which is apparently not applicable to players anymore.

This happens when I fall from flying/stop flying. Not when I hit ennemies. Can now clearly reproduce it.

**Comment by nossr50** [comment]
I'm unable to reproduce, have you tried updating Paper?
