### ISSUE TITLE
Players report they get double drops from placed blocks

### ISSUE THREAD

**Issue by mrfloris** [mcMMO-Dev/mcMMO#5115]
Not sure what else to say here, but on Paper 1.21.3 and build mcMMO 2.2.0.28 from Spigot, we get players reporting they place blocks and later they mine them, and those blocks double drop. These are fairly recently placed blocks.

**Comment by nossr50** [comment]
I tried my best to replicate but could not, if you could provide some kind of replication steps that would be great.

**Comment by mrfloris** [comment]
I showed you in the video, all I have to do is go to an existing build -mine's recently made in 1.21.1, and then I mine or use woodcutter to get the logs and it double drops. i broke 4, ended up with 9. the player mentioned they were mining netherrack they've placed. they only played for a week on the server. 


i guess it's another plugin causing this, sucks.. testing required.

**Comment by nossr50** [comment]
Yeah, I tried something similar on my end and was not able to reproduce. I built something, closed server, loaded it up, tried to get XP from the materials used, and was unable.

Feel free to reopen if you find evidence it is a genuine mcMMO and not from another plugin mucking things up.
