### ISSUE TITLE
Brewing infestation potions no mcmmo alchemy experience is awarded.

### ISSUE THREAD

**Issue by andrewkm** [mcMMO-Dev/mcMMO#5122]
When brewing infestation potions no mcmmo alchemy experience is awarded.
*This also applies when turning the infestation potions into their splash potion variant.

Bug report:
https://ecocitycraft.com/forum/threads/.226604/

**Comment by andrewkm** [comment]
Even after the latest PR this is still an issue;

I attempted to brew potions with;
Stone
Breeze Rod
Slime Block
Cobweb

None of the resulting potions awarded mcmmo EXP. @momshroom @nossr50

**Comment by Momshroom** [comment]
Sorry for the slow response here, though I see the report is now changed.  Did you regen your potions.yml (or copy *all* changes)?   Because these potions (not breeze rod, which I didn't add), do work for me on a freshly generated potions.yml.

**Comment by andrewkm** [comment]
This has been fixed, sorry for not closing.
