### ISSUE TITLE
LifeSteal

### ISSUE THREAD

**Issue by Jorkayus** [mcMMO-Dev/mcMMO#548]
When you hit or recieve hits, you gain in lifesteal, Whats that?
It is that you take a little % of life depending of the damage that you have done in that hit. I mean a little percentage, only as extra life because you sometimes in mob arenas or at night you need to fight with lot of mobs, and this extra life will be fantastic, i thought something like every 10 lvls 1% of the damage done is recovered. You do little damage so it will not be so much if you dont have a great lvl in that skill, but

**Comment by JH159753** [comment]
please make this soon

**Comment by pokeball99** [comment]
2 year later.....

**Comment by Nextshot** [comment]
2 years liking that idea later...

**Comment by ShadowSplicer** [comment]
I ended up making my own, completely from-the-ground-up plugin to replace McMMO. Was an amazing plugin while it lasted. <3 Thanks guys.
