### ISSUE TITLE
Disable chat notifications

### ISSUE THREAD

**Issue by yoshinat0r** [mcMMO-Dev/mcMMO#594]
Is there a way to disable the message that pops up when you make an enemy bleed? It gets very annoying after a while when you have a high sword skill level.

**Edit:** _I'm hijacking this issue to refer to all types of chat notifications provided by mcMMO. If it gets sent to a player, and it isn't the result of explicitly typing out a command, it needs to be possible to disable it. Which it isn't currently. This needs to have a configurable server default, and a command to control the setting per-player._ - @Glitchfinder

**Comment by Akamu94** [comment]
Is there a permission i can negate ?
