### ISSUE TITLE
Unarmed base damage is unbalanced

### ISSUE THREAD

**Issue by strontkever** [mcMMO-Dev/mcMMO#702]
the iron arm style +3 damage buff starting from level 0 is way to overpowered for the survival server i run, hitting mobs kills them in 2-3 hits unarmed, while using a diamondsword takes more.

i would like a request to make this configurable or balanced (0 damage buff at level 0)

**Comment by CollinHerber** [comment]
6 years later and this is still a problem.
NEAT!
