### ISSUE TITLE
MCMMO disable time taking minutes on server /stop

### ISSUE THREAD

**Issue by MutinyCraft** [mcMMO-Dev/mcMMO#749]
MCMMO Version 1.4.00-b1726

Issue: MCMMO sometimes take minutes to disable.  I have noticed this since 1.4.00-beta3 or possibly sooner.  When issuing the /stop command MCMMO takes a very lengthy amount of time to disable.  I was testing the release build (1726) today on my test server and it took a full 2 minutes just to disable MCMMO (see pastie below).  Is there any reason the disable time is so much longer with the most recent beta and release builds than with previous builds?

Disable: http://pastie.org/private/3ld8jreg5diszxwzdvgma

**Comment by clipartinc** [comment]
Still having this same issue 2 years later. Any fix to this?

**Comment by Brodys** [comment]
5 years later, still having this issue.

**Comment by andrewkm** [comment]
Not happening here at all.
