### ISSUE TITLE
Option to disable fireworks!

### ISSUE THREAD

**Issue by yoshinat0r** [mcMMO-Dev/mcMMO#790]
Please add an option to disable fireworks, I personally find them cheesy and wish they weren't there :/

**Comment by RobbieWill95** [comment]
> Change this to false https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/resources/config.yml#L363


So, I have a question, I have this Mod installed, and say that you responded to this saying to change it.  However, I don't have the know-how to do so and to make it work in-game.  If possible, could you assist me?
